### ISSUE TITLE
Trial Period Length

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/power-platform#100]
It would be helpful to confirm the length of the initial trial period. I'm assuming that it is 30 days, but this is not explicitly stated. I see that the extension is for 30 days.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6888aa90-ee04-f8dd-5b30-04e0a529ebb0
* Version Independent ID: 4e59e2e4-5c99-7e44-5afa-91b288e57b62
* Content: [Sign up for a Power Virtual Agents trial - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/sign-up-individual#trial-expiration)
* Content Source: [power-virtual-agents/sign-up-individual.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/sign-up-individual.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by clmori** [comment]
@mvakoc can you help with this request?
cc: @GitikaG

**Comment by mvakoc** [comment]
The trial policy is specified in the welcome email we send to all users after they sign up for PVA. It is currently 60 days, however, this is subject to change. cc @iaanw

**Comment by aliyoussefi** [comment]
Hi @mvakoc, 

I wanted to bring this one back up as I am still seeing a discrepancy between the trial verbiage within the Microsoft Office portal for the PVA trial add-on vs the user email. This is impacting an organization as they are confused into how to broadcast usage of the trial. 

If the trial policy is for 60 days, can we update the portal to reflect this as well for consistency? 

Thanks!

Ali
alyousse
