### ISSUE TITLE
This page has poor titles and is confusing and hard to find

### ISSUE THREAD

**Issue by Customery** [MicrosoftDocs/power-platform#1001]
Hello, in the left-hand navigation, this page is entitled "Audit data and user activity for Dynamics 365 entities" yet it has nothing to do with Dynamics 365 entities (which were 'tables' a year ago, in case you hadn't heard). Dynamics 365 is not referenced anywhere in the page. If it was a page about Dynamics 365 then it shouldn't be located under Power Platform.

The main page title is "Audit data and user activity for security and compliance". This is a confusing title because it sounds a lot like a another auditing feature (https://docs.microsoft.com/en-us/power-platform/admin/enable-use-comprehensive-auditing). 

One auditing feature audits Dataverse data changes and a little bit of user activity and its logs are stored in Dataverse. This feature is the old Dynamics CRM audit feature and is hard to find when searching in Microsoft Docs.

The other auditing feature audits Dataverse data changes and a lot of user activity and its logs are sent to Microsoft 365 Compliance Center. 

Please, please find distinct names for these two similar features and don't use the words 'auditing' and 'activity logging' in both of them.

If you perform a Bing search for "Microsoft Docs Dataverse auditing" the first result is a page for developers: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/auditing-overview. There is no link from here to either of the articles about auditing or activity logging for administrators. If you are an administrator, it's really hard to search for audit or activity logging pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837f9db7-667d-814f-1df6-98e2f89a44cc
* Version Independent ID: f53ea984-3798-d3fb-ec0c-d31f81db9250
* Content: [Audit data and user activity for security and compliance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity)
* Content Source: [power-platform/admin/audit-data-user-activity.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/audit-data-user-activity.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by jimholtz** [comment]
@Customery 
Thank you for your feedback. Valid points. We’ll review your requests as we revise content and features in later product updates.
