### ISSUE TITLE
Data export service deprecated

### ISSUE THREAD

**Issue by rjback** [MicrosoftDocs/power-platform#1002]
This page should mention that the product is deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sabinn-msft** [comment]
Yes. It was to be updated when the blog went out. However, we had a small glitch due to which it didn't get updated. We are working on this asap. Thanks for reporting.
