### ISSUE TITLE
More clarity on the "1000" limit

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/power-platform#1003]
Dear colleagues,

can you please rephrase / clarify the limitation from the beginning of the docs article: "Self-managed database encryption keys are only available for customers who have more than 1000 Power Apps per user licenses and/or Dynamics 365 Enterprise licenses (or a combination of these)"

The statement is being understood in this sense: I need either 1000 Power Apps licenses OR I need 30 Dynamics 365 Enterprise licenses. 

Suggestion to make this clearer: "Self-managed database encryption keys are only available for customers who have  more than 1000 Power Apps per user licenses or more than 1000 Dynamics 365 Enterprise licenses or a combination of these"

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c43b88-32f5-49ab-d715-bfcf75c9ba3e
* Version Independent ID: 70179da7-e3b6-8775-97cc-361990404677
* Content: [Manage the encryption key - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-encryption-key)
* Content Source: [power-platform/admin/manage-encryption-key.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/manage-encryption-key.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Mattp123
* Microsoft Alias: **miferlan**

**Comment by Mattp123** [comment]
@MichaelWeberMSFT  - The article has been updated with your suggestion and will be published live in a few hours. Closing issue.
