### ISSUE TITLE
Missing Access tile

### ISSUE THREAD

**Issue by ckey1** [MicrosoftDocs/power-platform#1005]
In the section "Assign security roles to users in an environment that has no Dataverse database", step 3 refers to the Access tile where the permissions can be viewed or assigned. I don't see that tile in my Power Platform admin center when I select an environment, and I don't see anywhere else to view or assign those permissions. Is it possible that the admin center was updated and these instructions are out of date?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure user security in an environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/database-security)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/database-security.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by ckey1** [comment]
Update: I have 2 types of environments listed. I realized that the one listed as type Default does have the Access tile. The ones with type Microsoft Teams are the ones missing it.

**Comment by jimholtz** [comment]
@ckey1 
Thanks for the update.
