### ISSUE TITLE
Sharepoint video is private

### ISSUE THREAD

**Issue by BuhtigUser1** [MicrosoftDocs/power-platform#1009]
The video " Connect to SharePoint Online" is private and not accessible on YouTube.  Signing in to YouTube does not allow access - message indicates a private video.  The video link is located on this page: https://docs.microsoft.com/en-us/power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b6702c-b45c-9c90-f809-fe0d276ab526
* Version Independent ID: fc9e44c1-fa3e-93c4-f574-ae2cd6c3ffdc
* Content: [Set up customer engagement apps to use SharePoint Online - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online)
* Content Source: [power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@BuhtigUser1 - thank you for your feedback. The video has been taken down so the link has been removed from the article and be reflected in the published article soon.
