### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by denzy134** [MicrosoftDocs/power-platform#101]
Can the bot be configured in a way which would allow it to display images to the the customer ?

**Comment by iaanw** [comment]
If this comment is about Power Virtual Agents, we are working on bringing images as a feature soon. It's currently targeted for July-October 2020 timeframe. https://docs.microsoft.com/en-us/power-platform-release-plan/2020wave1/power-virtual-agents/add-images-videos-topics
