### ISSUE TITLE
Trial environment creation not supported for Service Principal in tenant with powershell New-AdminPowerAppEnvironment

### ISSUE THREAD

**Issue by vitlachner** [MicrosoftDocs/power-platform#1010]
Hello,

we are manage CI/CD for PowerApps environments with DevOps Pipelines. When we have try to create environment with DevOps or with same powershell command New-AdminPowerAppEnvironment -DisplayName 'TEST Trial Principal' -Location europe -EnvironmentSku Trial we are faced to issue Trial environment creation not supported for Service Principal in tenant. We use service principal based on this power-platform/powerplatform-api-create-service-principal.md at 3d8964aa9402b148a7f96229391eba29e010.... We can create Sandbox, Production without issue.

 
![obrazek](https://user-images.githubusercontent.com/18088886/144755528-cf41f6aa-ae1e-4223-966b-97a5378fbb0d.png)

**Comment by jimholtz** [comment]
@vitlachner 
Sorry for the late response. If this is still an issue, please contact Support: https://powerapps.microsoft.com/support/
