### ISSUE TITLE
"Web client experience for security settings is being depreciated"

### ISSUE THREAD

**Issue by JoeJordan1** [MicrosoftDocs/power-platform#1013]
This support page instructs us to use the Advanced Settings in PowerApps, although PowerApps instructs us that "Web client experience for security settings is being depreciated". There isn't an equivalent section in the PowerApps Admin Centre that manages these settings though, that I am aware of. Can you make a reference to the section being depreciated, and if possible, point to the new place if you are aware of it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d0d5ce-9fb1-926e-ef38-18f70e200c3b
* Version Independent ID: 88ae146e-1e90-21a3-5c83-917e3a5d0f48
* Content: [Field-level security - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/field-level-security)
* Content Source: [power-platform/admin/field-level-security.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/field-level-security.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@JoeJordan1 
Greetings. If I understood your question correctly, the settings in this topic haven't yet been migrated to the Power Platform admin center. Settings migration is ongoing.
