### ISSUE TITLE
Update required since the availability of Exchange Online cross-tenant authentication

### ISSUE THREAD

**Issue by maeseleg** [MicrosoftDocs/power-platform#1014]
[Enter feedback here]

It's my assumption that impact 3 - E-mail is no longer relevant, since the introduction of the new Exchange Online cross-tenant authentication functionality (https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-online-server-profile-oauth).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7535eaaf-ce30-a021-f766-9c30c8cc6cdb
* Version Independent ID: fb995be3-f205-2cb6-0691-38762076662d
* Content: [Invite users with Azure Active Directory B2B collaboration - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/invite-users-azure-active-directory-b2b-collaboration)
* Content Source: [power-platform/admin/invite-users-azure-active-directory-b2b-collaboration.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/invite-users-azure-active-directory-b2b-collaboration.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@maeseleg 
Sorry for the delayed response. We've passed this on to the product group for their attention. If this is still an issue, please contact Support: https://powerapps.microsoft.com/support/
