### ISSUE TITLE
Incorrect links found in document

### ISSUE THREAD

**Issue by LiamVMG** [MicrosoftDocs/power-platform#1016]
The following sections contain the link [Microsoft 365 admin center](https://admin.microsoft.com/):
- Enable an entity for access teams
- Create a team template
- Add a team template to the entity form

These links should be [Power Apps admin center](https://admin.powerplatform.microsoft.com/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1579637e-7845-9830-1d8f-40d371d28587
* Version Independent ID: 6f00c801-369f-01e4-df15-36ad10c5f1bd
* Content: [Create a team template and add to an entity form - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-team-template-add-entity-form)
* Content Source: [power-platform/admin/create-team-template-add-entity-form.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-team-template-add-entity-form.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by jimholtz** [comment]
@LiamVMG 
Thanks for bringing this to our attention. This will be corrected today.
