### ISSUE TITLE
Error after import

### ISSUE THREAD

**Issue by jfren484** [MicrosoftDocs/power-platform#1017]
I followed the directions here (and the linked page), but when I try to open my chatbot in Teams -> Power Virtual Agents, I get an error (described by another user here: https://powerusers.microsoft.com/t5/Building-PVA-chatbots-in/Unable-to-import-Teams-Chatbot/td-p/1367316).

Here's the error:
We ran into a problem creating your bot
An unexpected error occurred while creating your bot.
Exception of type 'Microsoft.CCI.ManagedStore.Exceptions.BotWithoutBotComponentsException' was thrown.
Trace ID: 0HMDQEKUJ5O2L:00000001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9951d6a0-cec3-5bb0-c1d9-f0db99866436
* Version Independent ID: c2a46f79-6e8e-1043-95cb-0cae2857b423
* Content: [Export and import bots in Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/teams/authoring-export-import-bots-teams)
* Content Source: [power-virtual-agents/teams/authoring-export-import-bots-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/teams/authoring-export-import-bots-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by progmatic73** [comment]
I have the exact same issue as jfren484.

**Comment by v-alarioza** [comment]
@jfren484 @progmatic73 There was a bug in the export/import process, but it now appears to be fixed. I ran through the [export/import docs](https://docs.microsoft.com/power-virtual-agents/teams/authoring-export-import-bots-teams) and confirmed that it works as of today.

If you have any problems moving forward, the best place for bug reports or troubleshooting is [the Power Virtual Agents forum](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums).
