### ISSUE TITLE
Documentation is incomplete for API Authentication

### ISSUE THREAD

**Issue by safari137** [MicrosoftDocs/power-platform#1019]
The documentation is sufficient for delegated access, however application access does not provide enough details.

> **Obtain a token for client authentication**

> This can only be used after you have registered this client application ID with Microsoft Power Platform.

The documentation does not provide any details or references on how to register the client application with Microsoft Power Platform.  This is also inconsistent with normal access to APIs via an application registration (normally this would be granted via application permissions instead of delegated permissions inside the portal).

Could someone please provide steps on registering an already created application with Microsoft Power Platform?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d371632c-55c8-508b-86ac-b2ebd6f66dfe
* Version Independent ID: bfb53cc7-061d-07d9-97e3-1cb37ecb59fe
* Content: [Programmability and Extensibility - Authentication - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/programmability-authentication)
* Content Source: [power-platform/admin/programmability-authentication.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/programmability-authentication.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by safari137** [comment]
I was able to figure this out by reading this:
https://docs.microsoft.com/en-us/power-platform/admin/powerplatform-api-create-service-principal

I think a link to that article would solve this issue for others.

**Comment by jimholtz** [comment]
@safari137 
Thanks for the suggestion. We've added a See Also and may update the content further at a later time.
