### ISSUE TITLE
import / export Subjects in D365 Customer Service?

### ISSUE THREAD

**Issue by tmsquared** [MicrosoftDocs/power-platform#102]
Is there a way to import a Subject list? Looking at a client that changes the list of subjects at set periods and has multiple orgs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b10ea23f-970e-6831-b18f-4af29e17de25
* Version Independent ID: 890c06d6-7b65-455f-95df-e71eba36494e
* Content: [Define subjects to categorize cases, products, and articles - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/define-subjects-categorize-cases-products-articles#feedback)
* Content Source: [power-platform/admin/define-subjects-categorize-cases-products-articles.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/define-subjects-categorize-cases-products-articles.md)
* Service: **power-platform**
* GitHub Login: @shubhadaj
* Microsoft Alias: **shujoshi**

**Comment by jimholtz** [comment]
@tmsquared 
Sorry but there is currently no way to export/import the subject tree.
