### ISSUE TITLE
Link to the Trust Center is broken

### ISSUE THREAD

**Issue by Sealjay** [MicrosoftDocs/power-platform#1020]
- Open https://docs.microsoft.com/en-us/power-platform/admin/wp-compliance-data-privacy#trust-center
- Click on the link to the Trust Center Information "https://www.microsoft.com/TrustCenter/CloudServices/business-application-platform/default.aspx"
![image](https://user-images.githubusercontent.com/19361656/145842321-814576ae-f6ae-4445-a4fa-9a3fdd1d0c47.png)
- You are redirected to https://docs.microsoft.com/en-us/dynamics365/get-started/availability
- Expected behaviour is to end up at the trust center - https://www.microsoft.com/en-gb/trust-center/product-overview - on the PowerApps section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5356b36-4de4-cdce-c585-40ab0adc6710
* Version Independent ID: 4ac3ddec-b31b-c965-b3a2-0e42f4810d90
* Content: [Compliance and data privacy - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/wp-compliance-data-privacy)
* Content Source: [power-platform/admin/wp-compliance-data-privacy.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/wp-compliance-data-privacy.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Sealjay 
Thanks for bringing this to our attention. We'll get the link updated.
