### ISSUE TITLE
HELPER – ObjectOperations needs to removed form the list. Run-only property is not required from this flow. 

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1023]
![image](https://user-images.githubusercontent.com/33668478/145887699-71e14777-4832-4a0d-9a30-c9caad65b295.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
There has been a recent product change for Power Automate that now sets the run-only users correctly for all flows. We are updating our docs for the January release, and I have fixed this locally for the next docs update now!
