### ISSUE TITLE
Flow running multiple times: some of these flows are time consuming and expensive. Probably need to double check if the statements are written in the correct order.

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1024]
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-flows

![image](https://user-images.githubusercontent.com/33668478/145887934-be7d6fee-ea1d-4975-9e18-c5c3de2b4b95.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-flows)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Please raise any issues related to the CoE Starter Kit functionality itself here: https://github.com/microsoft/coe-starter-kit/issues/new?assignees=Jenefer-Monroe&labels=coe-starter-kit&template=coe-starter-kit-bug.yaml&title=%5BCoE+Starter+Kit+-+BUG%5D+your+issue

The issues here are just for documentation.
