### ISSUE TITLE
I assume the instructions here are turn both the flows or it is just the first one?

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1025]
Recommendation/Assumption: I assume the instructions here are turn both the flows or it is just the first one?

![image](https://user-images.githubusercontent.com/33668478/145888382-bc09423d-7337-466c-8061-3a4135e581de.png)

Available Flows.
![image](https://user-images.githubusercontent.com/33668478/145888173-97916b5e-b179-410f-9602-9215580e19dc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-flows)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are updating our docs for the January release, and I have fixed this locally for the next docs update now!

**Comment by bigpix2000** [comment]
@jimholtz your on a roll (ticket closings, new years' resolutions done ;-)) THANKS
