### ISSUE TITLE
Recommendation/Assumption: There are few other flows that are not turned on. I Just wanted to check if this is intentional or we need to update these instructions

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1026]
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-flows

![image](https://user-images.githubusercontent.com/33668478/145888564-7d3f8c5d-92df-449d-8340-a7dffc70c339.png)

Available flows that are not turned on:
Sync Flow Errors, Portal or Flow Action Details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-flows)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are updating our docs for the January release, and I have fixed this locally for the next docs update now!
