### ISSUE TITLE
image needs to be updated

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1028]
![image](https://user-images.githubusercontent.com/33668478/145888834-88356d2e-3fe0-4a06-91db-f15133d2a124.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#power-platform-request-center)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
It is also unfortunately impossible for us to always keep updating our docs as the product changes. If the overall functionality on how to navigate is still the same, we won't be able to always make updates. In this case, it should be obvious to the user to click on Test and skip Code. Please understand that there is no Product / Development or Support team behind the CoE Starter Kit, and we have very limited resources available to update the kit and docs.
