### ISSUE TITLE
Specify instructions to update Authority field for each type of environment/offering. GCC/DOD/commercial

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1029]
![image](https://user-images.githubusercontent.com/33668478/145889157-93b490cd-9388-4f06-a01d-4849b8cabf26.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#optional-create-an-azure-ad-app-registration-to-connect-to-microsoft-graph)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are updating our docs for the January release, and I have fixed this locally for the next docs update now!
