### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by dawidvanheerden** [MicrosoftDocs/power-platform#103]
"You can edit bot of these topic types in the same manner as for topics you create, however you cannot delete them." should say both, and not bot. Bots are top of mind ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7cb5611-5c8a-cb6b-c99f-328c623a3dba
* Version Independent ID: 0d6c40cc-275d-99be-0c51-cdac81536e56
* Content: [Use topics to design a Power Virtual Agents bot conversation - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/authoring-create-edit-topics)
* Content Source: [power-virtual-agents/authoring-create-edit-topics.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/authoring-create-edit-topics.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
oops nice catch :) Fixing it now, thanks!
