### ISSUE TITLE
Recommendation/Assumption: Image needs to be updated along with instructions to point to step 5 instead of 4

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1031]
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content

![image](https://user-images.githubusercontent.com/33668478/145889423-8e0a7ae4-f787-436b-aff4-ce1a571cefc7.png)

![image](https://user-images.githubusercontent.com/33668478/145889439-fa2047b9-26ac-4b65-9c2d-4876b40971c2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
It is also unfortunately impossible for us to always keep updating our docs as the product changes. If the overall functionality on how to navigate is still the same, we won't be able to always make updates. In this case, it should be obvious to the user to click on Test and skip Code. Please understand that there is no Product / Development or Support team behind the CoE Starter Kit, and we have very limited resources available to update the kit and docs.
