### ISSUE TITLE
Recommendation/Assumption: Name needs to be updated in the documentation for point 6 and 7. Remove “Admin |”

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1032]
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

![image](https://user-images.githubusercontent.com/33668478/145889713-c31a3e4d-7317-4adb-8063-a76504d69ab1.png)

![image](https://user-images.githubusercontent.com/33668478/145889724-9d53a042-6723-45bc-b758-a9990016f91f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are updating our docs for the January release, and I have fixed this locally for the next docs update now!
