### ISSUE TITLE
Update the see environment variable text to a link on How to look at All Environment Variables

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1034]
Recommendation/Assumption: Update the see environment variable text to a link on How to look at All Environment Variables. See Environment Variable link only shows the variables which has no value setup by default. The first three variables in the guide has preset value by default, hence not visible in the list of See environment variables and causes confusion to the user. 

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#update-environment-variables

![image](https://user-images.githubusercontent.com/33668478/145890208-7345146e-beef-489e-8b7d-34fdfea26196.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14181d4-574f-95e3-c2c9-545116549c9b
* Version Independent ID: bf449b92-6756-e08a-a58c-d561e36947cb
* Content: [Set up governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#update-environment-variables)
* Content Source: [power-platform/guidance/coe/setup-governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-governance-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are updating our docs for the January release, and I have fixed this locally for the next docs update now!
