### ISSUE TITLE
Recommendation/Assumption: Update the image on the doc site. The new image has data flow name appended by ‘3’. 

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1035]
![image](https://user-images.githubusercontent.com/33668478/145890577-b067891c-afd6-4704-966a-9ae3adb53308.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14181d4-574f-95e3-c2c9-545116549c9b
* Version Independent ID: bf449b92-6756-e08a-a58c-d561e36947cb
* Content: [Set up governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#update-environment-variables)
* Content Source: [power-platform/guidance/coe/setup-governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-governance-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
We have renamed the dataflow back to Maker Assessment Start Dataflow. It is also unfortunately impossible for us to always keep updating our docs as we change the UI or names in the CoE Starter Kit. Please understand that there is no Product / Development or Support team behind the CoE Starter Kit, and we have very limited resources available to update the kit and docs.
