### ISSUE TITLE
Recommendation/Assumption: at step 6 and 7 Update text to Publish. New sceen has publish now and later buttons instead of create.

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1036]
![image](https://user-images.githubusercontent.com/33668478/145890763-f5fd8862-8df4-4902-9c6d-6f1cf2d13a10.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fc749-2ecd-61d7-4146-16fe1a373848
* Version Independent ID: fcd148f1-795e-a99c-e2e9-da06e1129d3c
* Content: [How to set up nurture components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#update-and-run-the-dataflow-to-load-initial-data-into-dataverse)
* Content Source: [power-platform/guidance/coe/setup-nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Closing as this is a duplicate
