### ISSUE TITLE
Recommendation/Assumption: Not really clear from the following instructions if we are asking user to turn the flow on? The link referred in this section talks about different set of flows with very specific instructions.

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1038]
![image](https://user-images.githubusercontent.com/33668478/145890955-818a6c9d-d9fc-4bb4-932d-260b57c7f59a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fc749-2ecd-61d7-4146-16fe1a373848
* Version Independent ID: fcd148f1-795e-a99c-e2e9-da06e1129d3c
* Content: [How to set up nurture components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#update-and-run-the-dataflow-to-load-initial-data-into-dataverse)
* Content Source: [power-platform/guidance/coe/setup-nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are updating our docs for the January release, and I have fixed this locally for the next docs update now!
