### ISSUE TITLE
It also takes few seconds to 1 minutes instead of 10 – but I think the statement is given just to be on the safe side? 

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1039]
![image](https://user-images.githubusercontent.com/33668478/145891432-1ea77f70-860d-4fcd-86c3-ee749ca21352.png)

Also not sure why we are saying Run > Run Flow instead Jut click on "Run" to execute flow? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c74207b-a220-3f22-4f0a-1505c8848770
* Version Independent ID: 49a8f967-a8a6-5500-dbd9-256d568d73f9
* Content: [Set up Innovation Backlog components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-innovationbacklog#option-1-import-the-solution-into-a-production-environment)
* Content Source: [power-platform/guidance/coe/setup-innovationbacklog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-innovationbacklog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We have seen in some tenants that these take longer to run so we added this statement there.
