### ISSUE TITLE
Prerequisites: Office 365 admin roles

### ISSUE THREAD

**Issue by ValerianHeints** [MicrosoftDocs/power-platform#104]
Could you change the list of the admin to the actual names?
Couldn't find the "Support" admin 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3296698b-48cc-9655-267e-92775f33e0b7
* Version Independent ID: fe8f88d2-5fd4-6946-4ae6-d1abb856bf2f
* Content: [Get Help + Support - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/get-help-support)
* Content Source: [power-platform/admin/get-help-support.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/get-help-support.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@ValerianHeints 
Thanks for the feedback. We're pulling the list for now and considering providing a list at a later date.
