### ISSUE TITLE
PAL

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/power-platform#1040]
Hi,

this page is great. I would be very helpful to have a separate page, in this same section, where we provide a practical example on how can two different partners use the Partner Admin Link (PAL), to connect to 2 different Power Apps, aligned to this documentation:

	Link a partner ID to your Power Platform and Dynamics Customer Insights accounts
	https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/link-partner-id-power-apps-accounts  

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6985ca13-b574-4d28-52f1-eca702b268bb
* Version Independent ID: d15b3013-95b5-1e57-825c-055f50d45878
* Content: [Add a Partner of Record (POR) for sales and tech support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/add-partner-record-subscription)
* Content Source: [power-platform/admin/add-partner-record-subscription.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/add-partner-record-subscription.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Taking to internal thread.
