### ISSUE TITLE
	• In section Set up the Power Automate flow, step 6, note that there might not be an unmanaged layer to remove.   	• I ran into this error: https://github.com/microsoft/coe-starter-kit/issues/1365, in which the Office 365 Management API Connector was not in the correct DLP policy bucket.  In section: Start a subscription to audit log content, step 5 the button to Test was greyed out and we were not able to enable it. Our set-up looked exactly the same as the instructions. We found simply logging into an incognito browser did the trick

### ISSUE THREAD

**Issue by jjg133** [MicrosoftDocs/power-platform#1041]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog?source=docs#feedback)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are unable to repo this in our setup, it may have been a caching issue on your side. We have not heard about this from other customers so at this point will not amend the docs as that may add confusion!
