### ISSUE TITLE
What you should know section is inaccurate

### ISSUE THREAD

**Issue by eccountable** [MicrosoftDocs/power-platform#1044]
There is a bullet point that says "The Data Export Service doesn't work for sandbox or production environments that are configured with Enable administration mode turned on. " However one of my staff was able to set up this service on a sandbox environment without Administration Mode being enabled. Is the documentation inaccurate, or is the feature malfunctioning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#export-profile)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sabinn-msft** [comment]
More importantly, effective November 2021, Data Export Service was deprecated. While DES will continue to work and will be fully supported until it reaches end-of-support and end-of-life in November 2022, we highly encourage you start moving to Synapse Link now and not set this up for any new environments. In fact, we are planning to remove the DES add-in from Appsource as well. https://aka.ms/DESDeprecationBlog

**Comment by eccountable** [comment]
That is too bad. DES was a perfect fit for my clients that needed to have no-code / on-prem SQL replication. From what I have read in Synapse, I will have to develop a synchronization utility now to move data to their on-prem SQL server, which will probably cost more than their SQL instance. :(
