### ISSUE TITLE
Admin |Sync Templat v3 activation

### ISSUE THREAD

**Issue by jesslyn-omm** [MicrosoftDocs/power-platform#1045]
The instuctions need to state that there is a 1 to potentially 900 minute delay to run this flow for the 1st time before continuing with the configuration of the COE.  

The instructions state: "
Turn on Admin | Sync Template v3.
Wait for Admin | Sync Template v3 to complete its run and then turn it back off. This will avoid write conflicts for large organizations.
"
My issues are :
1.  My 1st run is set at 350 minutes - not acceptable
2. There is no place in the documentation that I've seen that says the initial setup could take multiple work days
3. Who could possibly think this was an appropriate process for initial configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-the-solution)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback. The CoE Starter Kit is not part of the Power Platform product, it is just a set of templates aiming to provide a starting point for customers to implement their own administration and governance policies when it comes to rolling out Power Platform. We are continiously improving and optimizing the kit based on product capabilities, but if what the kit provides doesn't work for you, you may have to invest in building your own solution for managing the platform. The CoE Starter Kit is built entirely with the Power Platform, but you may choose build solutions on Azure that are more performant. https://docs.microsoft.com/en-us/power-platform/admin/self-service-analytics provides a new way of getting your inventory and telemetry information into an Azure Datalake for example.
