### ISSUE TITLE
Merging in Dataverse with custom entities

### ISSUE THREAD

**Issue by emcdkr** [MicrosoftDocs/power-platform#1046]
Does anyone know how the Merge feature of the out of box Duplicate Detection functions with the Account or Contact has associated custom entities? 

Any feedback would be helpful - I can't seem to find anything in the documentation. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91f18ff-1cd7-ca7d-5256-84dde67cf8af
* Version Independent ID: 06982fe4-d779-92a2-0344-a92149f78170
* Content: [Use Microsoft Dataverse to detect duplicate records and merge - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/detect-duplicate-records)
* Content Source: [power-platform/admin/detect-duplicate-records.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/detect-duplicate-records.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@emcdkr 
Sorry for the delayed response. Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
