### ISSUE TITLE
Add Power Apps player URLS

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/power-platform#1048]
Could the Power Apps US government service URLs section be updated to also include Power Apps player URLS. I believe they are: For a GCC environment: <https://apps.gov.powerapps.us/>
For a GCC High environment: <https://apps.gov.powerapps.us/>
Unsure about DoD 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea524f2a-1e2a-6ade-8e2b-bc61173107c5
* Version Independent ID: 5990c060-8907-62b4-a8b3-f7ed8339a70e
* Content: [Microsoft Power Apps US Government - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government)
* Content Source: [power-platform/admin/powerapps-us-government.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-us-government.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Handling via internal thread.
