### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by rajakp123** [MicrosoftDocs/power-platform#1049]
[Enter feedback here]

Apart from steps, can you also publish video on this page for this as tutorial

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598df6b5-6691-3a4c-8112-ec6aec43d175
* Version Independent ID: 0a34a661-5035-3946-c2e4-a7ce5e697832
* Content: [Quickstart: Create and deploy a bot in Microsoft Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/teams/fundamentals-get-started-teams)
* Content Source: [power-virtual-agents/teams/fundamentals-get-started-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/teams/fundamentals-get-started-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
Thanks for your feedback! We're working to add video content where possible.
