### ISSUE TITLE
Is there a recommended procedure for Export and Import of PowerApp forms associated with SharePoint Lists?

### ISSUE THREAD

**Issue by git-gone** [MicrosoftDocs/power-platform#105]
I have a SharePoint List that we use to administer Change Approvals.  I have made some significant changes to a Test Version (within the same tenant as live) and would like to import the forms to the Live List

How would I go about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f7d9def-ccc0-6bf9-d9b4-945f4ccfd19b
* Version Independent ID: cd12491c-b19e-d626-a9e1-e8fc57ccd242
* Content: [Migrate apps between environments and tenants - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/environment-and-tenant-migration#feedback)
* Content Source: [power-platform/admin/environment-and-tenant-migration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/environment-and-tenant-migration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@git-gone 
Unfortunately, currently there is no way to export/import forms other than copy and paste. I heard back from the product team that work is under way to provide improved functionality. It's not possible to provide an ETA yet.
