### ISSUE TITLE
Adding a Security Role

### ISSUE THREAD

**Issue by GarryPope** [MicrosoftDocs/power-platform#1050]
Hello,

For the section https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#users--permissions when adding a user, the steps don't talk about adding a security role. But in the process of manually adding a user there is a step of "Manage security roles". 

![image](https://user-images.githubusercontent.com/68440710/147531588-c5ef7c28-43c6-448e-93ed-a57bd732e42f.png)

The documentation either needs to be updated to say add a security role and which role it should be, or they need to say to ignore this step and click cancel.

Thanks,

Garry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66be7882-5440-7cff-142f-4436a2d648ca
* Version Independent ID: b1876c76-62e5-2e0f-c823-09be35cfd7a5
* Content: [About the Microsoft Dataverse for Teams environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#user-access-to-dataverse-for-teams-environments)
* Content Source: [power-platform/admin/about-teams-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/about-teams-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@GarryPope 
Thanks for bringing this to our attention. We've passed this information on to the product team for their action.
