### ISSUE TITLE
Step 3 in the activate the flows section isn't correct.

### ISSUE THREAD

**Issue by msjebo** [MicrosoftDocs/power-platform#1051]
At https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-flows, step 3 states:
Turn on: CLEANUP HELPER - Check Deleted (Cloud Flows), CLEANUP HELPER - Check Deleted (Model Driven Apps), CLEANUP HELPER - Check Deleted (Canvas Apps) and CLEANUP HELPER - Check Deleted (PVA).

This should be:
Turn on: CLEANUP HELPER - Check Deleted (Cloud Flows), CLEANUP HELPER - Check Deleted (Model Driven Apps), CLEANUP HELPER - Check Deleted (Canvas Apps), CLEANUP HELPER - Check Deleted (Custom Connectors)  and CLEANUP HELPER - Check Deleted (PVA).

Otherwise the next step (4.) will result in an error as the flow can't be turned on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are updating our docs for the January release, and I have fixed this locally for the next docs update now!
