### ISSUE TITLE
Amendment to section entitled 'How to setup an Azure Key Vault' 

### ISSUE THREAD

**Issue by mattmblackmore** [MicrosoftDocs/power-platform#1059]
Within the section entitled 'How to setup an Azure Key Vault'  would it be possible to add a small note to elaborate a point in relation to the following:

**$connectionString. The connection string to the Azure SQL Database. You can use the ADO.NET connection string as it is displayed in your Azure dashboard.**

If the connection string is copied and pasted from the Azure portal, it is important to stress that the user ID must have appropriate permissions to the target SQL database. As it is assumed that the global admin account taken when copying and pasting the string has permissions, which is not always the case. Which can lead to validation failures in Dynamics when creating a DES profile. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#azure-key-vault-service)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by jimholtz** [comment]
Taking to internal thread.
