### ISSUE TITLE
API or PowerShell access?

### ISSUE THREAD

**Issue by justlikeed** [MicrosoftDocs/power-platform#106]
Previously we were able to automate ingestion of this data via the CRM instance API "/api/data/v9.1/savedorginsightsconfigurations" - this no longer seems to work, where are the equivalent API or PowerShell cmdlets to continue supporting this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c99626-6458-46b4-f099-ce10c30890c7
* Version Independent ID: d3766ded-359b-160c-d7f5-a7e6ffa103d6
* Content: [Common Data Service analytics - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service#feedback)
* Content Source: [power-platform/admin/analytics-common-data-service.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/analytics-common-data-service.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by JimDaly** [comment]
@justlikeed 
The SavedOrgInsightsConfiguration entity is a private, undocumented entity. Use of these private entities is not supported. See [About the Entity Reference](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/reference/about-entity-reference)

It was the data source for these charts until recently. The internal implementation has changed.
Did you find this entity documented anywhere?

**Comment by justlikeed** [comment]
Hello @JimDaly , there used to be an article (about 3 years ago) on this entity but, that article is gone.  I've connected with the orginsights product team outside of GitHub, they've confirmed this endpoint can't be used (anymore) and working on making alternatives available.

**Comment by markleavesley** [comment]
Is there any update on this? We need to report on storage usage across 50+ clients, bit of a pain logging into each and checking.

**Comment by NiklasJWolfe** [comment]
Hi,

Is there any update on this? 

Or is it possible to simply access the PowerBI tiles/dataset? 

Nik

**Comment by TMGMarcel** [comment]
We also have many clients we monitor, and having access for a common Power BI Dashboard was great. Any update on having access to the current data?

**Comment by justlikeed** [comment]
The internal team told me that they are not going to pursue developing this API any further. They are focusing on other avenues and suggested that I create an Idea on the ideas site, if the API was still relevant.

I created this idea a while ago, in the hope they would do something with this.
https://powerusers.microsoft.com/t5/Power-Apps-Ideas/API-or-CmdLets-for-programmatically-retrieving-analytics-from/idi-p/630412
