### ISSUE TITLE
See Also - Bad Link

### ISSUE THREAD

**Issue by gmykon** [MicrosoftDocs/power-platform#1060]
Dead link in See also
https://docs.microsoft.com/en-us/power-platform/admin/system-settings-dialog-box-service-tab#see-also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0443c09-1c18-dccb-5922-c8836f8abeef
* Version Independent ID: 658e5c37-517a-69a4-5d28-d7d5ae214d30
* Content: [System Settings Service tab - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/system-settings-dialog-box-service-tab)
* Content Source: [power-platform/admin/system-settings-dialog-box-service-tab.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/system-settings-dialog-box-service-tab.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@gmykon 
Thanks for bringing this to our attention. The link has been updated.
