### ISSUE TITLE
Deployment Settings File - SharePoint URL

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/power-platform#1062]
How it possible to include the SharePoint Site URL in the settings file?

Is there a schema available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1df5d8-ef79-c56d-3950-0617da9f976b
* Version Independent ID: ff132857-2fc9-57d0-df24-d42c054cbf1c
* Content: [Pre-populate connection references and environment variables for automated deployments using Power Platform Build Tools - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools#step-2-get-the-connection-reference-and-environment-variable-information)
* Content Source: [power-platform/alm/conn-ref-env-variables-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/conn-ref-env-variables-build-tools.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by fowl2** [comment]
OK I've worked it out.

First configure that app to use a datasource from environment variables, then the environment variables can be set using the deployment settings file. 


https://docs.microsoft.com/en-us/powerapps/maker/data-platform/environmentvariables#use-data-source-environment-variables-in-canvas-apps

**Comment by kkanakas** [comment]
Glad you were able to
