### ISSUE TITLE
CoE kit Upgrade Instructions documentation missing

### ISSUE THREAD

**Issue by tchagan** [MicrosoftDocs/power-platform#1063]
[Enter feedback here]
The Upgrade Instructions link now goes to nowhere, need this information to update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Here's the link with upgrade instructions https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup

We'll get that fixed in the setup instructions document

**Comment by manuelap-msft** [comment]
Could you share a screenshot of the  Upgrade Instructions link that goes to nowhere so I can see what we need to fix on this page?

**Comment by manuelap-msft** [comment]
Oh I think I know what you mean - you mean from the CoE Starter Kit release notes (https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-January2022) not from this docs page. Sorry! Fixed that now, thanks for letting us know - we missed that

![image](https://user-images.githubusercontent.com/55705669/148916375-2df8e0a4-d51d-418b-ad44-d882264a8465.png)

**Comment by tchagan** [comment]
The page is here https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-January2022

![image](https://user-images.githubusercontent.com/8684518/148916381-1059f7e6-a5ce-4199-81b5-c104109d2879.png)

**Comment by tchagan** [comment]
ahh, you beat me to it ;-)

**Comment by tchagan** [comment]
> Oh I think I know what you mean - you mean from the CoE Starter Kit release notes (https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-January2022) not from this docs page. Sorry! Fixed that now, thanks for letting us know - we missed that
> 
> ![image](https://user-images.githubusercontent.com/55705669/148916375-2df8e0a4-d51d-418b-ad44-d882264a8465.png)

Thanks for fixing it so quickly, appreciated!

**Comment by manuelap-msft** [comment]
It's still pre-coffee for me so took me a while :D Thanks for letting us know!
