### ISSUE TITLE
Different AdminCompliance workflows in Dataverse and Dataverse for Teams

### ISSUE THREAD

**Issue by JonTaylor5** [MicrosoftDocs/power-platform#1066]
We installed the core components on a Datavease for Teams environment and noticed that the Admincompliance functionality is different. In Teams no notifications or status updates seem to be automated. 

When checking the solutions we see that there are less workflows in the Teams core components so I am seeknig conformation this is by desirg (or not) and what the suggested workaround would be
<img width="554" alt="2022-01-11 13_04_37-Different workflows in Dataverse and Dataverse for Teams - Word" src="https://user-images.githubusercontent.com/97525276/148950336-29f69cf1-aacd-4268-8ea1-dbf487563305.png">
.

**Comment by jimholtz** [comment]
@JonTaylor5 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/

**Comment by JonTaylor5** [comment]
Hi Jim,

Thank you for your help.

Kind regards,

Jon
