### ISSUE TITLE
Outdated info?

### ISSUE THREAD

**Issue by Nianwei** [MicrosoftDocs/power-platform#1068]
[Enter feedback here]
Isn't the CRM SDK deprecated long time ago, and MS never updated beyond VS 2015, and only community hacks for VS 2017 and 2019? 

Kind of surprised to see a documentation page updated in 2021 referencing this tool. 

Having been trying to see if MS have an alternative in ALM space, but no results beyond some PS scripts..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78dd2e38-9d0c-3bbf-0db3-138416d4063b
* Version Independent ID: 51455bd4-3294-0ccd-2b1b-6d9857c0f50f
* Content: [Package Deployer tool - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/package-deployer-tool)
* Content Source: [power-platform/alm/package-deployer-tool.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/package-deployer-tool.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by fowl2** [comment]
The [last time this was brought up](https://github.com/MicrosoftDocs/power-platform/issues/636#issuecomment-963592774), a link to [Power Platform Tools for Visual Studio](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/tools/devtools-install) was posted, but it doesn't seem to have any packaging functionality. :/

**Comment by phecke** [comment]
@Nianwei @fowl2  I can look into this issue to see what the current recommendation is with regard to Package Deployer and update the topic.

**Comment by Pankaj-Thakur** [comment]
@Nianwei @fowl2 Packaging was excluded for the initial version of Power Platform Tools for Visual Studio but will be added in an upcoming release
