### ISSUE TITLE
Document roles that can delete environments

### ISSUE THREAD

**Issue by jthomps19** [MicrosoftDocs/power-platform#1069]
Hello - It would be nice to include some documentation that says which roles can actually delete an environment. 
This link has some info but doesn't make clear if they can delete:  
https://docs.microsoft.com/en-us/power-platform/admin/use-service-admin-role-manage-tenant#service-administrator-permission-matrix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb92ca9-41dc-d1d0-90df-09e7159e47d7
* Version Independent ID: 6c2a02de-a8db-cafa-6d81-861a027c07f2
* Content: [Delete an environment in Power Platform admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/delete-environment)
* Content Source: [power-platform/admin/delete-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/delete-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jthomps19 
Thanks for the feedback. We've updated the topic to include environment deletion.
