### ISSUE TITLE
Trial licenses should not be able to create production environments

### ISSUE THREAD

**Issue by ImadYanni** [MicrosoftDocs/power-platform#107]
only trial but not prod (under who can create environments).
We probably should simplify by combining/consolidating Dynamics 365 plan and Dynamics 365 apps plan (since the plan was deprecated and most users wouldn't know the difference as well as we do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform Admin center - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/create-environment#feedback)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Thanks for the suggestion. Content updated.
