### ISSUE TITLE
Missing Information regarding Security Group source

### ISSUE THREAD

**Issue by FerretyWorld** [MicrosoftDocs/power-platform#1070]
When creating an environment, and selecting a security group, it should be noted that on-prem AD synced security groups will not work correctly. Only cloud based security groups will function correctly for group members and the platform admins. The documentation here is missing that "warning" which has led me through 2 weeks of trying to resolve this with Microsoft Support, only to discover that it's not supported. The other reason it should be a warning on this page: When you select a security group, it doesn't stop you from picking an on-prem synced group. 

Hope this helps others and saves them time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/control-user-access)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by jimholtz** [comment]
@FerretyWorld 
Thanks for the feedback. We've heard the same from other customers and added the following note:
"When you select a security group, be sure to select an Azure AD security group and not one created in on-prem Windows Active Directory. On-prem Windows AD security groups aren't supported."
