### ISSUE TITLE
Environment Variables missing service message client id/secret

### ISSUE THREAD

**Issue by NHSharePointGuy** [MicrosoftDocs/power-platform#1071]
Since the client application and associated secret IDs are requested as environment variables during setup, it would be ideal to reference the necessary app registration in the environment variables section to avoid the subsequent failure in the "Turn on setup flows" section where "Command Center App > Get M365 Service Messages" is to be turned on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Updated docs now.
