### ISSUE TITLE
missing app registration

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/power-platform#1073]
The documentation forgets to mention that you need to register the Command-Center-App

It just assumes you have already done so, this becomes a problem when you try to enable the **Command Center App > Get M365 Service Messages** flow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#feedback)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
It doesn't, we just mixed up the order of steps - how to create the app registration and update environment variables is mentioned here below https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-admin---command-center-app, we just missed to move the two flows to this step as well. We're working on updating that as per #1071

**Comment by manuelap-msft** [comment]
tracking as per #1071 so closing this one out as a duplicate
