### ISSUE TITLE
URL for "Combined effect of multiple DLP policies" incorrect

### ISSUE THREAD

**Issue by chris-nguyen-MSFT** [MicrosoftDocs/power-platform#1074]
The URL reference for "Combined effect of multiple DLP policies" below is incorrect:

- current: https://docs.microsoft.com/en-us/admin/dlp-combined-effect-multiple-policies
- should be: https://docs.microsoft.com/en-us/power-platform/admin/dlp-combined-effect-multiple-policies ; URL is missing `/power-platform` after `/en-us`

[Check that no other DLP policies apply to this environment. Learn more: Combined effect of multiple DLP policies](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#:~:text=Check%20that%20no%20other%20DLP%20policies%20apply%20to%20this%20environment.%20Learn%20more%3A%20Combined%20effect%20of%20multiple%20DLP%20policies)

**Comment by jimholtz** [comment]
@chris-nguyen-MSFT 
Thanks Chris. Making this correction today.
