### ISSUE TITLE
Need more information for "Obtain a token for client authentication"

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/power-platform#1075]
Regarding "Obtain a token for client authentication", when I registered a AAD app and configure "API permissions" to access "PowerApps Service" (Application ID: 475226c6-020e-4fb2-8a90-7a972cbfc1d4), I can only configure "Delegate permission" and "Application permission" is grayed out. If "Application permission" is grayed out, how can we get authenticated by using "Client Credential" flow which you mentioned at "Obtain a token for client authentication"? I also got error message as well. need more information for that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d371632c-55c8-508b-86ac-b2ebd6f66dfe
* Version Independent ID: bfb53cc7-061d-07d9-97e3-1cb37ecb59fe
* Content: [Programmability and Extensibility - Authentication - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/programmability-authentication)
* Content Source: [power-platform/admin/programmability-authentication.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/programmability-authentication.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
Have an update in the pipeline, will get it published soon.  Thanks!
