### ISSUE TITLE
ALM. Unmanaged solution packed from repo and then import as Managed solution doesn't work

### ISSUE THREAD

**Issue by tacklers** [MicrosoftDocs/power-platform#1076]
I have been developing Azure Dev Ops pipelines for the last few weeks. Happily exporting Managed and Unmanaged solutions, storing .zipfiles, unpacking code storing in repo, building release and all that stuff. All fine.

I now try to pack code from an unmanaged solution into a .zip and import as managed but it always imports wrongly as unmanaged.
I have tried every combination of settings. Deleted every trace of the unmanaged solution from the target environment, published customisations from every level  and it still installs as unmanaged even though the logs say it's fine.
 I then installed the solution manually as managed and ran the pipeline import which is rejected as it states that it is trying to install as unmanaged when the parameter is set as managed. 
Logs attached. I don't know what else to try so an idea would be appreciated. Cheers, Richard UK
[Enter feedback here]

---
[Unmanaged-source-pack-and-import-as-managed-doesnt.pdf](https://github.com/MicrosoftDocs/power-platform/files/7888106/Unmanaged-source-pack-and-import-as-managed-doesnt.pdf)
![pack-unmanaged-code-into-solution](https://user-images.githubusercontent.com/19391937/149917127-01d0f717-f2d2-401d-ab77-cd8ab36ac2b1.png)
![import-as-managed-solution](https://user-images.githubusercontent.com/19391937/149917163-b128062c-be4e-4eb1-ae57-cba7e07f12a8.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks#solution-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tool-tasks.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by bigpix2000** [comment]
Question is if you are able to recreate the issue with a fresh package?  (or an older one that had worked?)

**Comment by tacklers** [comment]
Hi. Thanks for the response.
This is the first time I have used this function so have no good runs.
1. Pack code taken from unmanaged solution from source repo into solution.zip
2. Import solution.zip as managed.
I guess there is no requirement for me to edit  src/other/solution.xml beforehand in the repo and change the manifest entry from 0 to 1. This should be what the import does, or something similar?
Any other trial you'd like me to do?

**Comment by tacklers** [comment]
Power platform Import Solution
This is such an important task in the build tool kit.
I find it hard to believe that it's not working.
I cannot think of what else I can try to fix as it's a blocker for me on our ALM journey.
Any advice greatly appreciated.
Cheers, richard

**Comment by tacklers** [comment]
I don't think what I am trying to do will work. I now understand that there are differences between the components of managed and unmanaged solutions. the expectation that unmanaged components can be imported as managed does not compute.
I will have to import the unmanaged code components in as unmanaged then export as managed, luckily I have just set up a sandbox build environment dedicated for the purpose. Thanks for looking
https://docs.microsoft.com/en-us/power-platform/alm/solution-packager-tool#managed-and-unmanaged-solutions
See ISSUE #312

**Comment by tacklers** [comment]
So I will have to get used to building something now and it may be history in 3 months, thats life!
