### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bfanger** [MicrosoftDocs/power-platform#1077]
>  All customizable properties are listed in defaultStyleOptions.js. 

The defaultStyleOptions.js link to

https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/defaultStyleOptions.js

is broken, the file is moved to:

https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/api/src/defaultStyleOptions.ts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b1fcdf-f5ae-8302-1a7c-984c2dd2f81b
* Version Independent ID: ec989e88-349e-6a1b-c55d-7a4b4b600815
* Content: [Customize the web chat canvas - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/customize-default-canvas)
* Content Source: [power-virtual-agents/customize-default-canvas.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/customize-default-canvas.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
Thank you for reporting this! I've made the fix which should be merged next week.
