### ISSUE TITLE
Depricated?

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/power-platform#108]
I'm a bit confused about the Wave 1 2020 and this article. Does this article describes the new module, that improves the existing change tracking based functionality?

Regards,
Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#feedback)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@soutchilin 
Please provide the Release Plan topic you're referring to above. Thanks.

**Comment by jimholtz** [comment]
@soutchilin 
Perhaps you're looking for  ‘Export to data lake’ - https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake which is a similar service that instead of going from Common Data Service to Azure SQL, it exports to Azure data lake.
