### ISSUE TITLE
home.dynamics.com

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#1083]
I guess the home.dynamics.com portal does not exist anymore, and the following statements can be removed?

- When you assign a security group to an environment, that environment will not show up in home.dynamics.com for users not in the group.
- If you do not assign a security group to an environment, the environment will show up in home.dynamics.com even for those who have not been assigned a security role in that Dataverse environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/control-user-access)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by jimholtz** [comment]
@petepuu 
Thanks, Pete. This change will be made today.
