### ISSUE TITLE
Replace skype by Teams? 

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/power-platform#1084]
the graphic shows skype as proposed service to integrate with dynamics, shouldnt it be replaced by teams ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe101898-1e9c-e55c-5dd8-58345be38232
* Version Independent ID: 604928b2-9fe0-486f-7622-76ef818866f0
* Content: [Add Microsoft 365 Online services - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/add-office-365-online-services)
* Content Source: [power-platform/admin/add-office-365-online-services.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/add-office-365-online-services.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jeffangama 
Thanks for the suggestion. This change will go live today.
