### ISSUE TITLE
https://play.geforcenow.com/

### ISSUE THREAD

**Issue by mharrshra** [MicrosoftDocs/power-platform#1085]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 61ad60e7-0308-31f9-8e05-31020e3d4b67
* Version Independent ID: 30cbae86-6165-5c35-45af-a5b21ac32247
* Content: [Solución de problemas: desbloquear direcciones URL necesarias - Power Platform](https://docs.microsoft.com/es-es/power-platform/admin/troubleshooting-unblock-urls-required)
* Content Source: [power-platform/admin/troubleshooting-unblock-urls-required.md](https://github.com/MicrosoftDocs/power-platform-pr.es-ES/blob/live/power-platform/admin/troubleshooting-unblock-urls-required.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@mharrshra 
Greetings. I don't see any request comment. Please add in English and reopen issue. Thanks.
