### ISSUE TITLE
Missing Steps for Inventory Flows

### ISSUE THREAD

**Issue by dylanhaskins** [MicrosoftDocs/power-platform#1086]
The page is missing steps in Inventory Flows, to turn on the CLEANUP HELPER Flows before trying to turn on the CLEANUP Flows, which used the helpers as Child Flows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello! We mention turning on the CLEANUP HELPER flows in this section https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows
