### ISSUE TITLE
First sentence on page is abstract and misleading

### ISSUE THREAD

**Issue by anttipajunen** [MicrosoftDocs/power-platform#1088]
"If you can access Teams, and if you can add the Power Virtual Agents app, then it's likely you already have all the necessary licenses."

This is probably the worst possible comment you can make about licensing on an official docs page. Not only does PVA licensing take work to figure out, but you're also now leaving it up to the reader to deduce whether or not they're licensed. Either remove this sentence or clarify clearly when a user is licensed and when they're not. As the sentence is now, it does more harm than good.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff34d1c-25af-da12-e0b6-ffa0f64234f8
* Version Independent ID: 64328cdd-7455-697f-493b-61c2fb1d350f
* Content: [Assign user licenses and manage access in Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/teams/requirements-licensing-teams)
* Content Source: [power-virtual-agents/teams/requirements-licensing-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/teams/requirements-licensing-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
Thanks for your feedback! We've just published some changes to this page that make it more clear how to determine which license you have.
