### ISSUE TITLE
Configuration for Sync to work across tenants ?

### ISSUE THREAD

**Issue by aovar** [MicrosoftDocs/power-platform#109]
&gt; Connecting model-driven apps in Dynamics 365 with Exchange Online in a different
&gt; tenant is supported by setting up hybrid profile connections to the separate tenant
&gt; infrastructure.

The page seems to be missing information about what values we are supposed to input in each field of which records to setup Server-Side Synchronization with Exchange Online in a different tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81157f78-2ddc-0f01-e785-5e8630e43354
* Version Independent ID: d9a69cce-0ada-9d02-bf12-853d64d5fcc1
* Content: [Supported email service configurations for server-side synchronization - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/supported-email-service-configurations-server-side-synchronization#feedback)
* Content Source: [power-platform/admin/supported-email-service-configurations-server-side-synchronization.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/supported-email-service-configurations-server-side-synchronization.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@aovar 
Thanks for the feedback. We've revised to note that currently, connecting model-driven apps in Dynamics 365 with Exchange Online in a different tenant is not supported.
