### ISSUE TITLE
Limitations of service principals

### ISSUE THREAD

**Issue by luisleong** [MicrosoftDocs/power-platform#1090]
Hello,

Is there an estimation of when service principals will be allowed to access Power Automate (Flows)

"Currently, service principal authentication works for environment management, tenant settings, and Power Apps management. Any cmdlets related to Flow are not supported for this kind of authentication. This support will be added in the future."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cffb7b79-7591-396f-ff5a-3bc4b28e5ad6
* Version Independent ID: 0785b1c3-fd5b-a261-7598-002485a34f01
* Content: [Programmability and Extensibility - PowerShell - Creating a service principal - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powershell-create-service-principal)
* Content Source: [power-platform/admin/powershell-create-service-principal.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powershell-create-service-principal.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
Have an update in the pipeline, will get it published soon.  Thanks!
