### ISSUE TITLE
Update on Power Platform Requests reporting

### ISSUE THREAD

**Issue by aliyoussefi** [MicrosoftDocs/power-platform#1091]
Hi,

Looking for clarification on the verbiage currently included in the documentation. I reviewed the 2022 Release Wave 1 notes and did not see this feature included. If not planned for first quarter can we adjust the documentation to reflect this?

"Generally available reporting for Power Platform Requests is expected in the first quarter of calendar 2022. Any potential high usage enforcement wouldn't start until six months after reports have been made available. Assignment of add-on capacity packs should be aligned to high usage enforcement."

Thanks!
alyousse

**Comment by aliyoussefi** [comment]
Link to documentation: https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#what-happens-if-a-licensed-or-non-licensed-user-exceeds-limits

**Comment by jimholtz** [comment]
@aliyoussefi 
Taking to internal thread.
