### ISSUE TITLE
[COE CLI] Exception when attempting to generate install file.

### ISSUE THREAD

**Issue by TBag** [MicrosoftDocs/power-platform#1092]
When I run the COE CLI to generate the install file it throws an exception that a file is missing (coe-cli\config\alm.schema.json).  Where do we get the file?

Here is the log generated by the coe cli for two attempts.

{"level":"info","message":"Generate Install start","timestamp":"2022-01-25 03:32:22 PM -0500"}
{"date":"Tue Jan 25 2022 15:41:14 GMT-0500 (Eastern Standard Time)","error":{"code":"ENOENT","errno":-4058,"path":"D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\config\\alm.schema.json","syscall":"open"},"exception":true,"level":"error","message":"uncaughtException: ENOENT: no such file or directory, open 'D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\config\\alm.schema.json'\nError: ENOENT: no such file or directory, open 'D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\config\\alm.schema.json'","os":{"loadavg":[0,0,0],"uptime":522173},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\topsh\\AppData\\Roaming\\npm\\node_modules\\coe\\coe","alm","generate","install","-o","test.json"],"cwd":"D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":41550,"external":969162,"heapTotal":51363840,"heapUsed":48486128,"rss":73998336},"pid":12708,"uid":null,"version":"v16.13.2"},"stack":"Error: ENOENT: no such file or directory, open 'D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\config\\alm.schema.json'","timestamp":"2022-01-25 03:41:15 PM -0500","trace":[]}
{"level":"info","message":"Generate Install start","timestamp":"2022-01-25 03:43:45 PM -0500"}
{"date":"Tue Jan 25 2022 15:44:56 GMT-0500 (Eastern Standard Time)","error":{"code":"ENOENT","errno":-4058,"path":"D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\config\\alm.schema.json","syscall":"open"},"exception":true,"level":"error","message":"uncaughtException: ENOENT: no such file or directory, open 'D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\config\\alm.schema.json'\nError: ENOENT: no such file or directory, open 'D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\config\\alm.schema.json'","os":{"loadavg":[0,0,0],"uptime":522395},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\topsh\\AppData\\Roaming\\npm\\node_modules\\coe\\coe","alm","generate","install","-o","test2.json"],"cwd":"D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":41613,"external":968771,"heapTotal":51888128,"heapUsed":48957344,"rss":74944512},"pid":28932,"uid":null,"version":"v16.13.2"},"stack":"Error: ENOENT: no such file or directory, open 'D:\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\config\\alm.schema.json'","timestamp":"2022-01-25 03:44:56 PM -0500","trace":[]}

Even though the file was not generated, there are some questions I have about the settings.  Can you help me with them?  They are in the callouts in the attached screenshot.

![1](https://user-images.githubusercontent.com/1407310/151236243-3d6f381c-25c9-4563-ab2b-374328264ed0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9e18449-730e-0332-bb2c-7b7a80a6f6cf
* Version Independent ID: a9e18449-730e-0332-bb2c-7b7a80a6f6cf
* Content: [Set up ALM Accelerator for Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/admin-install)
* Content Source: [power-platform/guidance/coe/cli/alm/admin-install.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/cli/alm/admin-install.md)
* Service: **power-platform**
* GitHub Login: @Grant-Archibald-MS
* Microsoft Alias: **grarchib**

**Comment by mikefactorial** [comment]
Hey @TBag, you may need to pull the latest of the coe-cli to fix this (https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/upgrade). 

The file in question was missing when we first released last week but we've since added it back to the main branch. https://github.com/microsoft/coe-starter-kit/blob/main/coe-cli/alm.schema.json

**Comment by mikefactorial** [comment]
@TBag since these aren't necessarily doc update related questions and more focused on the functionality of the cli. Would you mind taking this conversation over to the microsoft/coe-starter-kit repo for better visibility to others working with the cli and the accelerator. Unfortunately, I can't transfer this issue over from here.

**Comment by mikefactorial** [comment]
Closing for now. Will reply on coe-starter-kit repo once moved over.

**Comment by TBag** [comment]
Awesome, this fixed the issue!  Thanks!

Here's a link to the new issue in the other repo where I put the open questions.

https://github.com/microsoft/coe-starter-kit/issues/1855
