### ISSUE TITLE
Turn on setup flows section must be after the app registration section

### ISSUE THREAD

**Issue by msjebo** [MicrosoftDocs/power-platform#1094]
Hi,

First of all, thx for updating the docs earlier this month !

However, I found an issue following the instructions.
If you want to turn on the command center flows in this section:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-setup-flows 
The actions fails, because the environment variables:
- Command Center - Application Client ID
- Command Center - Client Secret
Aren't filled in yet. 

The data for those two environment variables are available after finishing the this step:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-an-azure-ad-app-registration-to-connect-to-microsoft-graph

So the order should be changed somehow in my opinion.

Kind regards,

Jeroen Boiten

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-an-azure-ad-app-registration-to-connect-to-microsoft-graph)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback, we're already tracking this one per #1071 and are planning to have the updated docs live next week. I will close this out as a duplicate.
