### ISSUE TITLE
email to Makers with rss feed missing

### ISSUE THREAD

**Issue by mihaistanciu-techdev** [MicrosoftDocs/power-platform#1095]
[Enter feedback here]
Hello, i know there was a flow scheduled weekly that was using rss feed to get updates regarding power platform. Has this flow been removed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e88f289-b527-30ab-a2b5-a27d98745516
* Version Independent ID: 4fffa137-7df2-546c-988e-fa7ddf1028b5
* Content: [Microsoft Power Platform Center of Excellence Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/starter-kit)
* Content Source: [power-platform/guidance/coe/starter-kit.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/starter-kit.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello

this flow is part of the Nurture components still - you can find more details about it here https://docs.microsoft.com/en-us/power-platform/guidance/coe/nurture-components#flows - it's called Admin | Newsletter with Product Updates

Thanks for your interest in the CoE Starter Kit,
Manuela
