### ISSUE TITLE
Add clarity on Dataverse specific messages capable of handling multiple records

### ISSUE THREAD

**Issue by bhshastr** [MicrosoftDocs/power-platform#1099]
_Below_ paragraph needs clarity on Dataverse specific requests those allows submitting and receiving batches of records. For example Batch/Executemultiple/RetrieveMultiple etc. How an API call like api/data/accounts returning 500 records will be counted? as one request or 500 requests?

_Dataverse – all create, read, update, and delete (CRUD), assign, and share operations including user-driven and internal system requests required to complete CRUD transactions, and special operations like share or assign. These can be from any client or application (including Dynamics 365) and using any endpoint (SOAP or REST). These include, but are not limited to, plug-ins, classic workflows, and custom controls making the earlier-mentioned operations._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Taking to internal thread.
