### ISSUE TITLE
Update flow Set-flow is missing

### ISSUE THREAD

**Issue by scubaracer** [MicrosoftDocs/power-platform#11]
The documentation states we can update a flow, but how? I don't have a Set-flow command. Please explain how I can update a flow e.g. set it's connections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#feedback)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@scubaracer 
There is no Set-AdminFlow command. You can submit product-related feedback at https://ideas.powerapps.com. For flow configuration documentation, please see: https://docs.microsoft.com/en-us/power-automate/.
