### ISSUE TITLE
Per-app plan questions in the Office 365 section

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/power-platform#110]
In the "Office 365" section of the document, there are two questions pertaining to per-app licensing: "The Power Apps per app plan allows users to run specific apps. Can you explain what this means in terms of the number and types of apps I can use?" and "Do embedded canvas apps in model-driven apps count toward the two-apps limits?". Am I right that these should be moved into the "General licensing questions" section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#feedback)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@rgsteele 
Thanks for the suggestion. We've moved the content.
