### ISSUE TITLE
Import File name for Dataverse for Teams

### ISSUE THREAD

**Issue by SirChristopher** [MicrosoftDocs/power-platform#1100]
Please delete this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a381e-f728-50ed-e5d4-5605b948c57f
* Version Independent ID: a50a381e-f728-50ed-e5d4-5605b948c57f
* Content: [Get started setting up the governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov)
* Content Source: [power-platform/guidance/coe/before-setup-gov.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/before-setup-gov.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Verified the correct info is in docs.
