### ISSUE TITLE
Flow missing from solution

### ISSUE THREAD

**Issue by ThatTechieGirl** [MicrosoftDocs/power-platform#1101]
Hi, under the header - Turn on Flows
I cannot find flow - App Catalog > Request Access - in the solution. Is this updated or removed from the core component solution?

Regards
Roma

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea239a1-b656-9976-7566-87c927c8d8b7
* Version Independent ID: 9ea239a1-b656-9976-7566-87c927c8d8b7
* Content: [Set up other core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-othercore-components)
* Content Source: [power-platform/guidance/coe/setup-othercore-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-othercore-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

this flow is part of the February release (https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-January2022). If you do not see this flow, you may be on an older version of the CoE Starter Kit. It has not been removed and is still called that
![image](https://user-images.githubusercontent.com/55705669/152139403-4388ca8b-b723-4805-9f13-ec51f7112bef.png)
