### ISSUE TITLE
AppSource link is not working

### ISSUE THREAD

**Issue by anilvem1** [MicrosoftDocs/power-platform#1102]
Or, find it on [Microsoft AppSource](https://appsource.microsoft.com/product/dynamics-365/mscrm.44f192ec-e387-436c-886c-879923d8a448).

Above AppSource link it not working. Can you please check?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#what-you-should-know-before-using-the-data-export-service)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sabinn-msft** [comment]
Service has been deprecated and so not available to new customers. Only existing customers using DES can find and install it from Appsource.
https://docs.microsoft.com/en-us/power-platform/important-changes-coming#data-export-service-deprecation
