### ISSUE TITLE
Canvas App Name is changed: Archival – Cleanup Unused Objects now is Cleanup Old Objects App Cleanup Old Objects App

### ISSUE THREAD

**Issue by eduardorivas9** [MicrosoftDocs/power-platform#1103]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fefdb513-c458-0deb-9a26-f5d8102e3c81
* Version Independent ID: fefdb513-c458-0deb-9a26-f5d8102e3c81
* Content: [Set up archive components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components)
* Content Source: [power-platform/guidance/coe/setup-archive-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-archive-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you! Update locally to go live with our next docs update

**Comment by manuelap-msft** [comment]
Fixed with the latest update.
