### ISSUE TITLE
Cannot create a bot in german environment / Workaround not working

### ISSUE THREAD

**Issue by MarvinBangert** [MicrosoftDocs/power-platform#1104]
"If you create bots in Teams from an unsupported location (Germany, United Arab Emirates (UAE), or South Africa), your bot will be created in Europe."

Unfortunately this does not work, at least for Germany. Tried it within my environment that is located in Germany (Power Platform Default environment and Teams data location) and it's not possible to create a bot/the dataverse for teams environment in Europe. Microsoft support (third-party) only offers to move the environments to Europe.

Power Virtual Agents Community question: https://powerusers.microsoft.com/t5/Building-PVA-chatbots-in/Error-while-creating-a-bot-in-german-environment/m-p/1408316#M599

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f1cf2e-d785-c516-5872-30c7eeb17bcf
* Version Independent ID: e9a0cbc5-f426-c861-7d0f-875068ceddac
* Content: [Regional settings and data locations in Microsoft Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/teams/data-location-teams#data-locations)
* Content Source: [power-virtual-agents/teams/data-location-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/teams/data-location-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
@MarvinBangert Thanks for reporting this! This portion of the article was incorrect, and has been removed.
