### ISSUE TITLE
Repeated information

### ISSUE THREAD

**Issue by nvythms** [MicrosoftDocs/power-platform#1106]
The last 2 paragraphs under **Business Unit** are similar to each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f837f71b-c2d0-ad5e-9099-494702864ab5
* Version Independent ID: 569c759e-1ba0-98cf-30e0-014fd0e02856
* Content: [Security concepts in Microsoft Dataverse - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds)
* Content Source: [power-platform/admin/wp-security-cds.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/wp-security-cds.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@nvythms 
Thanks for bringing this to our attention. We'll get this corrected.
