### ISSUE TITLE
Maker Command Center

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [MicrosoftDocs/power-platform#1107]
Hello!  The maker command center is blank on open.  When can we expect to see documentation for that here?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#flows-2)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
If you have issues with using the CoE starter kit tooling itself, please raise them here: https://github.com/microsoft/coe-starter-kit/issues/new?assignees=Jenefer-Monroe&labels=coe-starter-kit&template=a-coe-starter-kit-bug-report.yml&title=%5BCoE+Starter+Kit+-+BUG%5D+ISSUE+TITLE - where the team developing the kit can take a look! Please do so for this issue!

Adding documentation for the Maker - Command center is already on my backlog, so closing this out here.

Thank you
Manuela
