### ISSUE TITLE
[AA4PP Docs] Profile settings documentation

### ISSUE THREAD

**Issue by TBag** [MicrosoftDocs/power-platform#1111]
Thanks for this documentation.  It would be nice to see some documentation that describes what data to put into the system to make the recommended deployment user settings and deployment profiles that match watch is shown in the walkthrough videos.

You can reverse engineer some of the settings from the screen shot but it is not obvious or easy to see unless on a large monitor.  The screenshot does not show the recommended button text labels, and it would be very helpful to document their recommended values as well.

Adding a table to the document that lists each of the different recommended profiles to create, along with all the recommended settings for each of them would make it very clear to people setting this up how to proceed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5190b0eb-7cda-9642-07aa-519f28a08c9d
* Version Independent ID: 5190b0eb-7cda-9642-07aa-519f28a08c9d
* Content: [Configuring the ALM Accelerator for Power Platform App - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles#sharing-alm-accelerator-user-settings-and-profiles-using-aa4pp-administration-app)
* Content Source: [power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @mikefactorial
* Microsoft Alias: **v-mikeochs**

**Comment by mikefactorial** [comment]
@TBag thanks for this adding a link to the April release docs issue in coe-starter-kit to track this and resolve in the next release.
