### ISSUE TITLE
URL are out of date

### ISSUE THREAD

**Issue by MattB-msft** [MicrosoftDocs/power-platform#1112]
[Enter feedback here]
 Allow list for URL's is missing https://login.microsoftonline.com 
  we should likly reference this link for proper authority list: https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud#azure-ad-authentication-endpoint

it also looks like we need to clean up some of the legacy stuff from LiveID 

Really we need to consolidate all the PowerPlatform URL's to one page... 
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#ip-addresses
the one for Flow, and the one for Dataverse to this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215ab00d-9ad0-1e91-184c-218dd64a7d73
* Version Independent ID: 337562d4-dab0-ccf9-b272-5de16e88476a
* Content: [Requirements/supported configurations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/online-requirements#ip-addresses-and-urls)
* Content Source: [power-platform/admin/online-requirements.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/online-requirements.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Some of these suggestions have been done. More action will be taken over time.
