### ISSUE TITLE
Needs disambiguation between strict Power Apps functionality vs. Dynamics

### ISSUE THREAD

**Issue by Spocker** [MicrosoftDocs/power-platform#1113]
Across the documentation suite of Power Apps/Dataverse there is repeated references to Dynamics, which is extremely confusing.  These two products need to have their own distinct sets of documentation.  This article for example is about SharePoint Online document management in PowerApps, but refers to Dynamics.  So which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a791bf9c-a41c-47ad-3042-ea0cc056c776
* Version Independent ID: 8f82ce93-5b96-4443-8a9a-5bcce1f42f0e
* Content: [Requirements for using SharePoint document management - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/sharepoint-document-management-software-requirements)
* Content Source: [power-platform/admin/sharepoint-document-management-software-requirements.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/sharepoint-document-management-software-requirements.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Spocker - Thank you for your feedback. The article has been revised to include Power Apps model-driven apps as well as customer engagement apps, such as Dynamics 365 Sales and Dynamics 365 marketing.
Closing issue.
