### ISSUE TITLE
mod japanese

### ISSUE THREAD

**Issue by fj0rdingz** [MicrosoftDocs/power-platform#1115]
[フィードバックをこちらに入力してください]
[Eng]
If the new connector setting is Blocked, any new connectors that are blockable will be mapped to Blocked, as expected. However, any new connectors that are unblockable will be mapped to Non-Business because by design they can't be blocked.
[Jap]
新しいコネクタ設定が ブロック済み の場合、ブロック可能なすべての新しいコネクタが予想通りに ブロック済み にマップされます。 ただし、ブロックできない新しいコネクタはブロックされない設計のため、非ビジネス にマップされません。

一番最後の文において、日本語の意味が真逆になっています

Wrong
ただし、ブロックできない新しいコネクタはブロックされない設計のため、非ビジネス にマップされま**せん**。
↓
True
ただし、ブロックできない新しいコネクタはブロックされない設計のため、非ビジネス にマップされま**す**。

だと思います。
よろしくお願いします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dea88353-deff-d4d6-c1fc-ab36e1cf9d6d
* Version Independent ID: 600c9506-f379-092b-b32a-2e64b4999bed
* Content: [データ損失防止 (DLP) ポリシーを作成する - Power Platform](https://docs.microsoft.com/ja-jp/power-platform/admin/create-dlp-policy)
* Content Source: [power-platform/admin/create-dlp-policy.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/admin/create-dlp-policy.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@fj0rdingz 
Thanks for bringing this to our attention. This is being addressed.

**Comment by Vineyardhaven** [comment]
Yhuo
