### ISSUE TITLE
Question regarding application user

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/power-platform#1117]
Hello,
Is it possible for an application user to access a Premium connector on Power Automate?
Is there a licensing scheme for this?

Tx

Pierre-Olivier

**Comment by jimholtz** [comment]
@popujol 
Please let us know which topic this question is based on. Thanks.

**Comment by popujol** [comment]
Hello,
This is a power Automate licensing question.
Thank you

Pierre-Olivier Pujol

**Comment by jimholtz** [comment]
@popujol 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
