### ISSUE TITLE
Azure AD connector should be removed from the list of used connectors

### ISSUE THREAD

**Issue by briangre** [MicrosoftDocs/power-platform#1118]
This article states that the Azure AD connector is used within the COE components, however no one can figure out where or how. After doing a full install there is no connection to the Azure AD connector. This is causing issues with security as the Azure AD connector requires extreme privileges to Azure AD that most enterprises are not comfortable with. 

Either we need to a) remove the Azure AD reference from this page or b) document where and how the connector is being used. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you! Update locally to go live with our next docs update

**Comment by manuelap-msft** [comment]
Fixed with the latest update.
