### ISSUE TITLE
D4T setup documentation

### ISSUE THREAD

**Issue by pab74** [MicrosoftDocs/power-platform#1119]
[Enter feedback here]
In "Turn on setup flows" the documentation should differentiate between full and D4T setup. E.g. the following flows are not available for D4T
Command Center App > Get CoE Flows
Command Center App > Set CoE Flows State

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#before-you-start)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback. This is only an discrepancy with the latest release, we will bring those flows to the D4T version in March.
