### ISSUE TITLE
PowerApps Per-App Plan and Nested Flows.

### ISSUE THREAD

**Issue by EdneiMonteiro** [MicrosoftDocs/power-platform#112]
"Power Apps licenses will continue to include Power Automate capabilities. However, flows will need to run within the context of the Power Apps application, which refers to using the same data sources for triggers or actions as the Power Apps application_"

In this case, does the PowerApps license also cover nested executions of streams triggered in the context of the application? Does it allow the execution of child flows (in solutions) or flows nested by HTTP requests?

**Comment by jimholtz** [comment]
Topic:
https://docs.microsoft.com/power-platform/admin/powerapps-flow-licensing-faq#are-full-power-automate-capabilities-included-in-power-apps-licenses

**Comment by jimholtz** [comment]
@EdneiMonteiro 
Please see: https://go.microsoft.com/fwlink/?linkid=2085130
Page 8:
All types of enabled top level flows need to be licensed (Scheduled flows, automated flows, instant flows and business process flows). Flows that are only used as “child” flows (triggered by another flow) do not need to be additionally licensed
