### ISSUE TITLE
Update correct message

### ISSUE THREAD

**Issue by ThatTechieGirl** [MicrosoftDocs/power-platform#1123]
Hi Team

Please update the message, Select Application permissions, and then select ServiceMessage.Read.All.
to Select Application permissions, and then select Application.Read.All

Regards
Roma

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello! That's not correct, the permissions listed in the docs are the correct ones for this application registration.
