### ISSUE TITLE
unclear privleges definition

### ISSUE THREAD

**Issue by piotrgardynski** [MicrosoftDocs/power-platform#1125]
In the sentence "For a direct report, the manager has the Read, Write, Update, Append, AppendTo access to the report’s data. " please clarify what is the difference between "Write" and "Update" privileges. In the secuitiy roles there are no "Update" privileges.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2b746e-8a88-e3f9-9e55-592f2a186c44
* Version Independent ID: 482a7ffd-5ed5-a475-f9ba-6578bb6e97ee
* Content: [Hierarchy security - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/hierarchy-security)
* Content Source: [power-platform/admin/hierarchy-security.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/hierarchy-security.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by paulliew** [comment]
the Write and Update is the same privilege. Will remove 'Update' from the doc to match our published list of privileges

**Comment by jimholtz** [comment]
@piotrgardynski 
Thanks for the feedback. We've updated the documentation.
