### ISSUE TITLE
Per-app licensing needs clarification on when license is consumed

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [MicrosoftDocs/power-platform#1127]
Per-app licenses are consumed when a user actually launches the app for the first time, not when the app is shared.  Would it be possible to update the documentation to clarify this?  I just spent a significant amount of time testing and researching this, trying to help others in the future who may have the same question.  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1f9ece-05b6-907c-9d52-5a19f5bf9872
* Version Independent ID: 9eaed30a-4c07-ef03-e3b4-d3db9989a760
* Content: [About Power Apps per app plans - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-powerapps-perapp)
* Content Source: [power-platform/admin/about-powerapps-perapp.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/about-powerapps-perapp.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@DaveTheTeamsGuy 
Thanks for the feedback and sorry for the time spent. We're working on future availability of consumption reporting which should add clarity.

**Comment by DaveTheTeamsGuy** [comment]
Hi Jim, 

Thanks for the response.  Consumption reporting will be great, but the problem is that per-app licensing documentation doesn't accurately reflect how per-app licenses are consumed.  My request is for the document to be updated to show that per-app licenses are consumed when a user launches the app, not when the app is shared with a user.
