### ISSUE TITLE
Archive Score for Flow Archives Wrong High Score

### ISSUE THREAD

**Issue by CT9235** [MicrosoftDocs/power-platform#1135]
There should be a correction for Flow Archives, the highest score is 8 not 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d9f529-ccac-c9f5-8133-a3c31f1a6f3e
* Version Independent ID: 099d9362-d7be-3df2-cab2-0f68e3f28dfd
* Content: [Govern with the CoE Power BI dashboard - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern)
* Content Source: [power-platform/guidance/coe/power-bi-govern.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/power-bi-govern.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by CT9235** [comment]
Thank you!

Christina Tillbrook
Senior UX Consultant


 [BePNA5P+eRhAAAAAAElFTkSuQmCC]
Mobile: (203)213-8595  www.tallan.com<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.tallan.com%2F&data=04%7C01%7Csamantha.buccheri%40tallan.com%7C6d7a2ed50980421a661708d95cc0dfcf%7Cb7c4d562d8f647eebab9b9ee602bc6f0%7C0%7C0%7C637642805726770473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hrAsvwoOQ8G0Q63ikiqJlHdfG254fEd651B%2FfH4oxVk%3D&reserved=0>

 [A close-up of a card  Description automatically generated with low confidence]



From: Manuela Pichler ***@***.***>
Reply-To: MicrosoftDocs/power-platform ***@***.***>
Date: Wednesday, February 23, 2022 at 8:20 AM
To: MicrosoftDocs/power-platform ***@***.***>
Cc: "Tillbrook, Christina" ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/power-platform] Archive Score for Flow Archives Wrong High Score (Issue #1135)

[EXTERNAL EMAIL: Exercise Caution]

Thank you! Update locally to go live with our next docs update

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpower-platform%2Fissues%2F1135%23issuecomment-1048774208&data=04%7C01%7Cchristina.tillbrook%40tallan.com%7C18be7c5e317a4447ee1208d9f6cf3ce2%7Cb7c4d562d8f647eebab9b9ee602bc6f0%7C0%7C0%7C637812192250364806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KArbpsdsfYPjit8zVeKq3akoQOauSDCU97QvqitfCww%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATB4P6LWGCPZZX6PILPKRGDU4TNJFANCNFSM5O7ASIUQ&data=04%7C01%7Cchristina.tillbrook%40tallan.com%7C18be7c5e317a4447ee1208d9f6cf3ce2%7Cb7c4d562d8f647eebab9b9ee602bc6f0%7C0%7C0%7C637812192250364806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pMKFYSE45tvsDYwFqV5mJdC3XEbXo8yhrUdnjxv4TPg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristina.tillbrook%40tallan.com%7C18be7c5e317a4447ee1208d9f6cf3ce2%7Cb7c4d562d8f647eebab9b9ee602bc6f0%7C0%7C0%7C637812192250364806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QbVuiCjFBcM5fj9FvwsE7nI17OrFccoSRimfBeqnNO8%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchristina.tillbrook%40tallan.com%7C18be7c5e317a4447ee1208d9f6cf3ce2%7Cb7c4d562d8f647eebab9b9ee602bc6f0%7C0%7C0%7C637812192250364806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=riURtWpKM4SpOx6wOG4F%2FzriFbxIKZBvyq9mbIvkyO0%3D&reserved=0>.

**Comment by manuelap-msft** [comment]
Fixed with the latest update.
