### ISSUE TITLE
template library

### ISSUE THREAD

**Issue by sciencestudent-Sharon** [MicrosoftDocs/power-platform#1136]
"Power User Site URL (SharePoint Site)": "The site that your Microsoft Power Platform power users can use to communicate and share files. You'll use it here to house the template library for them."

To confirm, does the starter kit nurture components still create a template library "AppsTemplate" in this site or is this template library created manually?

My understanding is that previous iterations contained two flows that supported the implementation of this document library but the current solution doesn't include these flows. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fc749-2ecd-61d7-4146-16fe1a373848
* Version Independent ID: fcd148f1-795e-a99c-e2e9-da06e1129d3c
* Content: [How to set up nurture components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components)
* Content Source: [power-platform/guidance/coe/setup-nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
No, this was an oversight on our part. We do no longer create or use a SharePoint document library for templates, and instead use the Files tab of the Dataverse table here to reduce setup steps. We'll get this removed from the documentation with the next update. Thank you for letting us know!

**Comment by sciencestudent-Sharon** [comment]
Ok, I also noticed this SharePoint site + template catalog mentioned in other places in the documentation site for CoE Starter kit but will open an enquiry specific to those pages. Thank you
