### ISSUE TITLE
Add-AdminPowerAppsSyncUser cmdlets missing from this page

### ISSUE THREAD

**Issue by anmateusMSFT** [MicrosoftDocs/power-platform#1137]
There are some cmdlets missing on this page.

Example: Add-AdminPowerAppsSyncUser

https://docs.microsoft.com/pt-pt/powershell/module/microsoft.powerapps.administration.powershell/add-adminpowerappssyncuser?view=pa-ps-latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@anmateusMSFT 
Taking to internal thread.
