### ISSUE TITLE
Dataverse is referenced as Common Data Service

### ISSUE THREAD

**Issue by mikkelpkaas** [MicrosoftDocs/power-platform#1138]
Consider changing name of Common Data Service to Dataverse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6fd60a-4e8f-8280-cf14-d5721422f39e
* Version Independent ID: 3453f85a-f603-e541-9ee1-b5cd93ab8ee9
* Content: [Default solution vs. custom solution - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/use-solutions-for-your-customizations)
* Content Source: [power-platform/alm/use-solutions-for-your-customizations.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/use-solutions-for-your-customizations.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@mikkelpkaas - The article is referencing the Common Data Services Default Solution, which is still the name of the solution included as part of every Power Platform environment that includes Dataverse.
Closing issue.
