### ISSUE TITLE
Power Automate section wording doesn't match screenshot

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/power-platform#114]
In my instance, the wording is Enable Microsoft Flow and Show Microsoft Flow on forms and in the site map. You cannot disable Microsoft Flow once it is enabled in your organization.  In this article, the wording Enable Microsoft Power Automate doesn't match the wording in the screenshot.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63017419-1a44-fb00-68c3-a1f09b624f7d
* Version Independent ID: 8df68bc2-e216-f967-8b95-e76173587799
* Content: [Enable Power Automate integration to automate processes - Power Platform Admin center](https://docs.microsoft.com/en-gb/power-platform/admin/enable-embedded-flow-in-your-organization?source=docs#feedback)
* Content Source: [power-platform/admin/enable-embedded-flow-in-your-organization.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/enable-embedded-flow-in-your-organization.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@feridunkadir 
The user interface has not yet updated to the new terminology.
