### ISSUE TITLE
漢字の間違い : "健闘"してください⇒"検討" してください

### ISSUE THREAD

**Issue by AiHirano** [MicrosoftDocs/power-platform#1140]
「管理者、作成者、ユーザーとコミュニケーションを取る方法」の段落に漢字の誤字があります。
(誤) 健闘してください
(正) 検討してください

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [CoE スターター キットを設定する - Power Platform](https://docs.microsoft.com/ja-jp/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
@jimholtz Can you please pass on this feedback to the localization team? I believe it's to do with wrong kanji or word being used in the japanese translation. Thank you!

**Comment by jimholtz** [comment]
@AiHirano and @manuelap-msft 
Thanks for bringing this to our attention. We will get this corrected.
