### ISSUE TITLE
template catalog prerequisite

### ISSUE THREAD

**Issue by sciencestudent-Sharon** [MicrosoftDocs/power-platform#1141]
Template Catalog app
"Prerequisite: This app uses SharePoint in the background and requires a SharePoint site to be configured."

As per #1136 the template catalog app no longer relies on a SharePoint site for configuration but the Maker Assessment app does depend on an existing site to import the app's starter data.

If this is the case, the SharePoint site is no longer needed then after this configuration (of Maker Assessment)?

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52f603f-2e0d-b02b-4a51-de16511e79dd
* Version Independent ID: 5b0aa787-c4a4-423b-9504-80fa375a04ba
* Content: [Nurture components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/nurture-components)
* Content Source: [power-platform/guidance/coe/nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Fixed with the latest update.
