### ISSUE TITLE
Irrelevant reference to App passes under Fast and accurate search

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/power-platform#1142]
Under What is Dataverse search?, in the bullet point Fast and accurate search, the text "Check the App passes capacity for your environment" shouldn't be here.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f4b53c-095c-4bf9-46dd-62299f2568e5
* Version Independent ID: 92a06c7b-d9b6-1a85-fb46-8378273a5994
* Content: [Configure Dataverse search to improve search results and performance - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/configure-relevance-search-organization#set-up-dataverse-search)
* Content Source: [power-platform/admin/configure-relevance-search-organization.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/configure-relevance-search-organization.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@feridunkadir 
Thanks for bringing this to our attention. That link has been removed.
