### ISSUE TITLE
GitHub or DevOps licensing requirements

### ISSUE THREAD

**Issue by djmilt** [MicrosoftDocs/power-platform#1143]
[Enter feedback here]
While this article specifies that you need a Power Apps license, I think it should explicitly state whether makers using the accelerator would need GitHub/DevOps licensing or not.  It's something I've been asked several times, and having it stated in docs would be helpful.

--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7aec3bb-623f-4cfd-2886-d83f4fbff5f3
* Version Independent ID: 3ddb998e-8664-8527-50e0-7d8a271cac55
* Content: [ALM Accelerator for Makers - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-components)
* Content Source: [power-platform/guidance/coe/almaccelerator-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/almaccelerator-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by mikefactorial** [comment]
@djmilt thanks for this adding a link to the April release docs issue in coe-starter-kit to track this and resolve in the next release.
