### ISSUE TITLE
Whats the connection between Innovation Backlog and Maker Assessment?

### ISSUE THREAD

**Issue by rooobeert** [MicrosoftDocs/power-platform#1144]
Hi, 

I was wondering if someone could explain the connection between an Idea and the Maker Assesment. 

In the Innovation Backlog App I can (not very intuitively) share my Idea and get the Link to that idea from the sharing window. I take that Link and paste it into the Maker Assessment App. 

https://apps.powerapps.com/play/b15b307d-36fc-49....... (ist this the correct link type?)

The Maker Assessment App has no save to idea button or anything like that. 

From the Documenation it is not clear how those two apps connect and what impact it has. Can someone help me here please! 

Thanks, 
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52f603f-2e0d-b02b-4a51-de16511e79dd
* Version Independent ID: 5b0aa787-c4a4-423b-9504-80fa375a04ba
* Content: [Nurture components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/nurture-components)
* Content Source: [power-platform/guidance/coe/nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The Maker Assessment and Innovation Backlog can be used independently from each other, or together. If you indicate that you are using the Innovation Backlog (via setting the environment variable), the Maker Assessment will prompt you to provide the URL to the idea. If on the final screen you select "Contact us" to contact he admin with questions, they will be provided with a link to the idea + your questions/answers from the assessment.

If you have any ideas for approving either apps or general feedback you'd like to share, please file a Feature Request ask here: https://github.com/microsoft/coe-starter-kit/issues/new/choose
![image](https://user-images.githubusercontent.com/55705669/155989483-38aadb8c-e3a7-4b7e-a8b1-7d18df911387.png)


Thank you
Manuela
