### ISSUE TITLE
HeroCard list not showing up as a list in teams desktop app

### ISSUE THREAD

**Issue by ZagoSV** [MicrosoftDocs/power-platform#1146]
Hello. I'm trying to make so my bot displays a multi-select options list. I was able to follow this tutorial https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example2 on the official documentation and the list shows up fine in the test environment from pva.

![image](https://user-images.githubusercontent.com/77752467/156227457-aa65e13e-da8a-4bad-9c73-a145b3429aba.png)

But when I publish my bot to Teams desktop app, the list gets rendered as a card or something like that, is this intentional behavior or do I need to change something else?

This is how it shows on the Teams desktop app: 
![image](https://user-images.githubusercontent.com/77752467/156227720-4473908b-4018-4840-897a-b0424a81aea0.png)

**Comment by v-alarioza** [comment]
@ZagoSV Thanks for your message! The best place troubleshooting is [the Power Virtual Agents forum](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums). If you repost your question there an engineer, project manager, or someone with a similar issue/solution should be able to help you.

**Comment by ZagoSV** [comment]
@v-alarioza Got it. Thank you.
