### ISSUE TITLE
Add variables doc

### ISSUE THREAD

**Issue by anbhar** [MicrosoftDocs/power-platform#1147]
This is missing specific details on which variables are sent to OC, whether or not custom PVA variables are sent to OC, and how to use those variables in OC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3427b1fd-1a36-9e75-a3e6-d1850fdb4631
* Version Independent ID: 5b4e98a4-5798-f597-55d4-9f694c981682
* Content: [Configure hand-off to Dynamics 365 Customer Service - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-hand-off-omnichannel)
* Content Source: [power-virtual-agents/configuration-hand-off-omnichannel.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/configuration-hand-off-omnichannel.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
@anbhar Thanks for your question! The first two pieces of information you're looking for are currently documented on the top of the [omnichannel article](https://docs.microsoft.com/power-virtual-agents/configuration-hand-off-omnichannel):
> When you hand off a conversation, you share the full history of the conversation (the context) as well as all user-defined variables. This allows your omnichannel service to route incoming escalations to the right live agent queue and enables engaging live agents to review context from the prior conversation and resume the conversation.

> For more information about hand off, and how to use hand-off within a bot conversation, see the [Using Transfer to agent node](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-hand-off) topic.

However the last piece is indeed missing, but it will be added in a coming doc update. In the meantime, please refer to https://docs.microsoft.com/dynamics365/customer-service/context-variables-for-bot
