### ISSUE TITLE
service principle typo?

### ISSUE THREAD

**Issue by sciencestudent-Sharon** [MicrosoftDocs/power-platform#1148]
"Flows that are imported or owned by a service principle
The Admin | Sync Template v3 (Flows) flow will fail to collect inventory information for flows that were imported or are owned by a service principle."

Is "service principle" meant to be "service principal"?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d61c7e5-8eda-2412-1bef-ffc9b74887bb
* Version Independent ID: 45d039f7-eb71-efdb-334e-2dad2db5aac1
* Content: [Limitations - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#security-groups-and-approvals)
* Content Source: [power-platform/guidance/coe/limitations.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/limitations.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you! Fixed locally and will be updated when we next publish docs.
