### ISSUE TITLE
Mistake in example scenario

### ISSUE THREAD

**Issue by monty0018** [MicrosoftDocs/power-platform#115]
Four security groups are described but their are only three unique groups.  It seems the 'Coho Winery Service' environment should be secured by a group named 'Service_SG'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/control-user-access#feedback)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@monty0018 
Thanks for bringing this to our attention. Updated content.
