### ISSUE TITLE
Update to Get-AdminPowerAppOperationStatus Example 1

### ISSUE THREAD

**Issue by MichaelHolmesWP** [MicrosoftDocs/power-platform#1154]
Leaving this here as the edit link on the MSFT Doc Page for it appears to be linked to an old/missing repo name.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappoperationstatus?view=pa-ps-latest#example-1

Please change "-OperationUrl" parameter to "OperationStatusUrl"

**Comment by jimholtz** [comment]
@MichaelHolmesWP 
Thanks for the correction. Updated.
