### ISSUE TITLE
Additional context would be helpful on this page

### ISSUE THREAD

**Issue by bartsneary** [MicrosoftDocs/power-platform#1155]
It would have saved a customer and I about half an hour of digging if this article mentioned that turning on these flows had the dependency of having the "Helper" cloud flows on before attempting to start these.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b08b756-8274-5baa-21b0-301930f0aac6
* Version Independent ID: 0b08b756-8274-5baa-21b0-301930f0aac6
* Content: [Set up clean-up for orphaned objects - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-orphan-components)
* Content Source: [power-platform/guidance/coe/setup-orphan-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-orphan-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

this page mentions at the top that the assumption is you have the Governance components solution installed and setup:
![image](https://user-images.githubusercontent.com/55705669/157511121-eca20b5f-0004-4e9d-851e-fb1c9312db4f.png)


And that page mentions turning on the child flows - we try not to duplicate info across pages as that's hard for us to maintain
https://docs.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov#turn-on-child-flows

**Comment by bartsneary** [comment]
Agreed.  It wasn't assumed that this included turning on Helper cloud flows once the solution install completed for us anyway.  Probably not a big deal, but thought I'd submit the idea.

***@***.***
Bart Sneary
MTC Architect | 952-837-4560 W or 507-403-3088 M
***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
[X]

**Comment by manuelap-msft** [comment]
Thank you! These helper flows are used across all governance components, not just the orphan components which is why we only mention it once. But I'll make an amendment so that the first paragraph says "installed and configured the governance components" with a link to that section. I'll include that with the April release update!

**Comment by bartsneary** [comment]
Definitely a minor thing also, but the helpers were turned on by default with the install of the Core Solution, but these 3 helpers in the Audit/Governance solution were turned off by default after install.

***@***.***
Bart Sneary
MTC Architect | 952-837-4560 W or 507-403-3088 M
***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
[X]
