### ISSUE TITLE
Documentation correction to find the devops api permission

### ISSUE THREAD

**Issue by michaelstephensonuk** [MicrosoftDocs/power-platform#1156]
On the bit for setting up the app registrations where you setup the api permission for devops, when you search for the devops permission it does not show up.  You need to search for Azure DevOps and it is found.  Just a small correction to the documentation is needed i think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d58c244-3aaa-48e6-8b6d-205521a0bc52
* Version Independent ID: 5d58c244-3aaa-48e6-8b6d-205521a0bc52
* Content: [Set up ALM accelerator for Microsoft Power Platform components manually - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform)
* Content Source: [power-platform/guidance/coe/setup-almacceleratorpowerplatform.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almacceleratorpowerplatform.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @mikefactorial
* Microsoft Alias: **v-mikeochs**

**Comment by mikefactorial** [comment]
@michaelstephensonuk thanks for this adding a link to the April release docs issue in coe-starter-kit to track this and resolve in the next release.
