### ISSUE TITLE
Copy Environement takes longer then 60 min

### ISSUE THREAD

**Issue by sannicolao** [MicrosoftDocs/power-platform#1158]
Hi together

When i want to copy my environment via Devops and the Copy Tasks, the taks will fails every time, cause the copy job will run more than 60 mins. 

I couldn't find a way to increase that limit. 

Could anyone help me? thx.

**Comment by jimholtz** [comment]
@sannicolao 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/
