### ISSUE TITLE
Feedback on documentation section for configure alm accelerator in dataverse

### ISSUE THREAD

**Issue by michaelstephensonuk** [MicrosoftDocs/power-platform#1160]
Hi

Just got a little feedback on the documentation in this section.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#install-the-alm-accelerator-in-dataverse

1) On the link below when setting up the alm accelerator.  It says go to github and download the latest version of the ALM accelerator.  In the image ive attached (at the bottom) you can see there are 2 packages which are alm accelerators.  It doesnt say in the documentation which I need to import or if I should be importing both.  I am assuming from the instructions later on it is the CenterofExcellenceALMAccelerator_1.0.20220303.1_managed.zip package that needs to be installed rather than the maker ALM one?

2) 
There looks to be a typo in the note section when telling about the graph API url we should configure.  Looks like a ; rather than a :

Is it = https;//graph.microsoft.com
It should be= https://graph.microsoft.com

![image](https://user-images.githubusercontent.com/11812194/157651822-db06cea5-c9c6-4c1c-8d86-e77102f0bfc1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d58c244-3aaa-48e6-8b6d-205521a0bc52
* Version Independent ID: 5d58c244-3aaa-48e6-8b6d-205521a0bc52
* Content: [Set up ALM accelerator for Microsoft Power Platform components manually - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#install-the-alm-accelerator-in-dataverse)
* Content Source: [power-platform/guidance/coe/setup-almacceleratorpowerplatform.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almacceleratorpowerplatform.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @mikefactorial
* Microsoft Alias: **v-mikeochs**

**Comment by mikefactorial** [comment]
@michaelstephensonuk thanks for this adding a link to the April release docs issue in coe-starter-kit to track this and resolve in the next release.
