### ISSUE TITLE
Incorrect name for power app in documentation

### ISSUE THREAD

**Issue by michaelstephensonuk** [MicrosoftDocs/power-platform#1161]
Hi

Just have some feedback on this section of the documentation.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles#creating-user-settings-and-profiles-with-the-power-platform-alm-accelerator-administration-app

In step 1 I think the power app may have been renamed since the documentation was written and is now called "ALM Accelerator for Power Platform Administration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5190b0eb-7cda-9642-07aa-519f28a08c9d
* Version Independent ID: 5190b0eb-7cda-9642-07aa-519f28a08c9d
* Content: [Configuring the ALM Accelerator for Power Platform deployment user settings and profiles - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles#creating-user-settings-and-profiles-with-the-power-platform-alm-accelerator-administration-app)
* Content Source: [power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @mikefactorial
* Microsoft Alias: **v-mikeochs**

**Comment by mikefactorial** [comment]
@michaelstephensonuk thanks for this adding a link to the April release docs issue in coe-starter-kit to track this and resolve in the next release.
