### ISSUE TITLE
Why Cannot I View PowerApps Usage Data using http (or https) ?

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/power-platform#1165]
Hi
I want to access PowerPlatform Usage Data using a http (or https) command (So I can use it in PowerAutomate flow).  I cannot find it on this page.  Can you please tell me where I can find the documentation for this please ?

Thanks

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 184dd591-1250-2bcc-db42-35afc3a77bce
* Version Independent ID: 75aaea0f-6f52-3977-77ba-a79f3604ef5e
* Content: [Power Apps activity logging - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps#what-events-are-audited)
* Content Source: [power-platform/admin/logging-powerapps.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/logging-powerapps.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by jimholtz** [comment]
@NPrice99 
We've recently published this content:
https://docs.microsoft.com/en-us/power-platform/admin/powerapps-analytics-reports
