### ISSUE TITLE
Error in sample code.

### ISSUE THREAD

**Issue by StrikeZero** [MicrosoftDocs/power-platform#1166]
var userID = clientApplication.account ? .accountIdentifier != null ?
            ("Your-customized-prefix-max-20-characters" + clientApplication.account.accountIdentifier).substr(0, 64) :
            (Math.random().toString() + Date.now().toString()).substr(0, 64); // Make sure this will not exceed 64 characters

This line return me an error. I notice you have a extra period after the question mark. If I remove the period I get an error of unexpected character ";".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d60dd9-05e9-9c78-7d7b-53b26a92af06
* Version Independent ID: 282e50ba-61cf-6574-94ad-4dcf82b71a72
* Content: [Configure single sign-on - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configure-sso)
* Content Source: [power-virtual-agents/configure-sso.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/configure-sso.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
@StrikeZero Thanks for your report! 

The period after the question mark is correct. The [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) `?.` enables you to read the value of a property located deep within a chain of connected objects without having to check that each reference in the chain is valid.

However, while the current white space is valid, it doesn't exactly read clearly. So I'll update this line to read:
`var userID = clientApplication.account?.accountIdentifier != null ?`

I am curious though - what was the error that you saw when first running the example?

**Comment by drmanhatin** [comment]
If you had simply copied the line StrikeZero sent (and which is in the docs) you would have noticed that the dot is in the wrong place.

Furthermore, the code uses an outdated version of Msal-Browser. And the code is just a huge mess in general to be honest... Is there anyone working on a newer version of this document?

**Comment by iaanw** [comment]
I'm closing this issue as the original question/error is being rolled into other fixes that we're currently testing.

@drmanhatin please feel free to submit any suggested changes in a new issue for this page. We'll take a look and check with our engineering team.

Thanks all!
