### ISSUE TITLE
Per App Plan Details is Wrong

### ISSUE THREAD

**Issue by szerongtham** [MicrosoftDocs/power-platform#1168]
Hello, 

Under the first tip box, the per app plan details is shown wrongly. It should not be "two applications and one portal" anymore with the new revised per app plan. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0cbf8c-5c12-5aa2-3786-392d0f498303
* Version Independent ID: 2774f5ca-1c86-4fe6-c296-6f7f45aa6702
* Content: [Capacity add-ons for Power Apps and Power Automate - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on)
* Content Source: [power-platform/admin/capacity-add-on.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/capacity-add-on.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@szerongtham 
Thanks for bringing this to our attention. Content has been updated.
