### ISSUE TITLE
Need a bigger and clearer warning about the maker group adding process

### ISSUE THREAD

**Issue by guillaume-kizilian** [MicrosoftDocs/power-platform#1171]
There should be a way bigger warning (and clearer) that every maker (anybody who made a power app or flow some old days) will be added to the group choosen for makers, as soon as you install core components.

Just found myself with 250 new members to my Excellence center.

![image](https://user-images.githubusercontent.com/6792560/158776249-4ed1f560-f72b-4cd8-a899-e6a317e4e7a1.png)

This... is not enough.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Configurer les composants d’inventaire - Power Platform](https://docs.microsoft.com/fr-fr/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform-pr.fr-FR/blob/live/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

could you explain your concern in a bit more detail here? This group should be an Office 365 Group that you can then use to communicate with all your makers or share apps with, but by default this group doesn't have access to anything in the CoE kit. I'd like to understand your concern before we make changes to the documentation.

Thank you
Manuela

**Comment by guillaume-kizilian** [comment]
Hello,

I think this sentence is unclear about what will happen with the given group ID. I understood that is was to communicate with my makers, i didn't knew it will add every app owner to the specifed group.

Regards,

**Comment by manuelap-msft** [comment]
Great, thanks for the feedback! We can add a note further up in the documentation about this when you turn on the flows that add makers. I'll put that on our list for our next docs update!
