### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by femo1de** [MicrosoftDocs/power-platform#1172]
Typo in Quickstart section. It reads: 

> https;//graph.microsoft.com for both the Base Resource URL and Azure AD Resource URI.

But it should be 

> https://graph.microsoft.com

Semicolon instead of double colon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c049c09-0ffb-1994-6c5e-acd549988983
* Version Independent ID: 8c049c09-0ffb-1994-6c5e-acd549988983
* Content: [CoE CLI ALM accelerator for Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/overview#install-overview)
* Content Source: [power-platform/guidance/coe/cli/alm/overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/cli/alm/overview.md)
* Service: **power-platform**
* GitHub Login: @Grant-Archibald-MS
* Microsoft Alias: **grarchib**

**Comment by KumarVivek** [comment]
@femo1de This is fixed now; thanks for your feedback.
