### ISSUE TITLE
Getting Error while try to run the bot framework bot which is having PVA bot as skill  

### ISSUE THREAD

**Issue by jackdeesun** [MicrosoftDocs/power-platform#1179]
Sorry, something went wrong with publishing. Try again or exit out of this task.

Error: [2022-03-21T10:59:03+0530]:Invalid or non-existent JSON config file - 2: cannot LoadConfig() with config_or_path=C:\Users\admin_chatbot\AppData\Roaming\BotFrameworkComposer\models\pretrained.20200924.microsoft.dte.00.06.en, config.is_discarded()=0, config_folder="C:\\Users\\admin_chatbot\\AppData\\Roaming\\BotFrameworkComposer\\models\\pretrained.20200924.microsoft.dte.00.06.en", config_file="C:\\Users\\admin_chatbot\\AppData\\Roaming\\BotFrameworkComposer\\models\\pretrained.20200924.microsoft.dte.00.06.en\\config.json", fs::exists(config_or_path)=1, fs::is_directory(config_or_path)=1, fs::is_regular_file(config_or_path)=0, fs::exists(config_file)=0, FILE=D:\a\1\s\oc\Model.cc, FUNC=operator (), LINE=1894

When I manullay search for in specified path I couldn't find the config.json file as well.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227cd5cd-3022-fef0-da7b-0b3f49588a16
* Version Independent ID: af1a0565-cfbf-8faf-2322-3d67d67e079f
* Content: [Use a Power Virtual Agents bot as a skill in Bot Framework bots - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-use-pva-as-a-skill#test-your-power-virtual-agents-bot-as-a-skill-with-a-bot-framework-bot)
* Content Source: [power-virtual-agents/advanced-use-pva-as-a-skill.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/advanced-use-pva-as-a-skill.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
@jackdeesun Thanks for your message! The best place for troubleshooting is [the Power Virtual Agents forum](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums). If you repost your question there an engineer, project manager, or someone with a similar issue/solution should be able to help you.
