### ISSUE TITLE
Microsoft Power Automate Free license limits

### ISSUE THREAD

**Issue by jevgenij-martynenko** [MicrosoftDocs/power-platform#118]
I can't find exact numbers on limits for a free Power Automate plan.
Would help to have them on this page 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#what-is-a-microsoft-power-platform-request)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@jevgenij-martynenko 
We're working on revising the licensing documentation and will see if we can't get this information added or linked.
