### ISSUE TITLE
Example Images are no longer available.

### ISSUE THREAD

**Issue by hellokirilee** [MicrosoftDocs/power-platform#1184]
[Enter feedback here]

Content no longer available.
-https://contososcubademo.azurewebsites.net/assets/steak.jpg
-https://contososcubademo.azurewebsites.net/assets/chicken.jpg
-https://contososcubademo.azurewebsites.net/assets/tofu.jpg
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309a5abe-486a-bad3-4de9-abb6b7ed0869
* Version Independent ID: 36c5d403-655a-6222-b4db-dcfa73354669
* Content: [Use Bot Framework Composer adaptive cards in chatbots - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example1)
* Content Source: [power-virtual-agents/advanced-bot-framework-composer-example1.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/advanced-bot-framework-composer-example1.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hellokirilee. This issue has been assigned to the doc author for review.

**Comment by v-alarioza** [comment]
@hellokirilee Thanks for reporting this! I've updated the doc and it should be published soon.
