### ISSUE TITLE
Add a Link and steps in how to navigate to https://admin.powerplatform.microsoft.com/

### ISSUE THREAD

**Issue by GaneshKannusamy** [MicrosoftDocs/power-platform#1185]
[Enter feedback here]

It took a while to figure out how to navigate to the page to create a new "Application User", It will save time if we provide steps to navigate from make.powerplatform.com - select Admin Center - and go to - https://admin.powerplatform.microsoft.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce8d679-77f4-99c0-8d7f-f25db4ba1c9c
* Version Independent ID: daf77157-6c6f-7c3e-7f74-a6f9ba528ec1
* Content: [Tutorial: Get started with GitHub Actions for Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-start)
* Content Source: [power-platform/alm/tutorials/github-actions-start.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/tutorials/github-actions-start.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GaneshKannusamy. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@GaneshKannusamy - Yes you're correct the first two steps in the procedure were incorrect. I've updated the article. Closing issue.
