### ISSUE TITLE
Program Manager - Power Platform Governance

### ISSUE THREAD

**Issue by AnupmaSharma** [MicrosoftDocs/power-platform#119]
It will be good to call out how admins can turn on tenant isolation for their tenant. AFAIK as of now we facilitate this using a support ticket raised by the customer and are in the process of making this setting available in PPAC in near future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daeff591-4edf-8cc0-614a-47e59bec3825
* Version Independent ID: bad9dc45-d9f9-62c6-a7fd-7aa97fd8e3fd
* Content: [Restrict cross-tenant access - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/cross-tenant-restrictions#feedback)
* Content Source: [power-platform/admin/cross-tenant-restrictions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/cross-tenant-restrictions.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Taking this internal to work on.
