### ISSUE TITLE
Developer Compliance Center app for Flows? 

### ISSUE THREAD

**Issue by sciencestudent-Sharon** [MicrosoftDocs/power-platform#1194]
Hi there, 

Regarding:
"This app is used in the [auditing process](https://docs.microsoft.com/en-us/power-platform/guidance/coe/example-processes) as a tool for users to check whether their app, **flow**, chatbot or custom connector is compliant, and to submit information to the CoE admins as business justification to stay in compliance."

I noticed when modifying the Developer Compliance Center app there is definitely a screen for obtaining flows compliance (there also seem to be errors out of the box).
![image](https://user-images.githubusercontent.com/38770482/161368682-725f9d10-0367-4c0f-a459-b57325298fec.png)

But how does the Developer Compliance Center app get sent to Makers for flows compliance?
ex. "Developer Compliance Center URL + appName=AppIDString" for Apps <- but this doesn't seem to work for flow IDs

I understand that in the App auditing process, it's the 'Admin | Compliance Detail Request' flow in the CoE that sends out emails accompanied with the Developer Compliance Center URL to prompt Makers to fill out the form.

But when I review this 'Admin | Compliance Detail Request' flow, it looks like it's only sending out requests for Apps and ChatBots at the moment. 
![image](https://user-images.githubusercontent.com/38770482/161368532-061d606a-617e-463b-907a-7862efd06bbf.png)

Is there another flow that sends out the request for flows separately that I can look into?
I would also like to be able to send out the 'compliance app URL + flow ID' like we can for Apps to specific users on their specific flows (outside of the CoE automated flow). Is it possible to do this with flowIDStrings?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3445b35a-114e-010d-a42b-3d738fa68c56
* Version Independent ID: 87fcef34-4b4a-cee9-f171-e1bd1e8ec970
* Content: [Governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#developer-compliance-center)
* Content Source: [power-platform/guidance/coe/governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/governance-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sciencestudent-Sharon. This issue has been assigned to the doc author for review.

**Comment by sciencestudent-Sharon** [comment]
moved to Question under CoE Starter Kit
