### ISSUE TITLE
Typo の指摘です。

### ISSUE THREAD

**Issue by Toxumuharu** [MicrosoftDocs/power-platform#1197]
[フィードバックをこちらに入力してください]

項目「含まれる機能」(https://docs.microsoft.com/ja-jp/power-platform/admin/pricing-billing-skus#capabilities-included) に、次の文章があります。

> これらの制限付きの機能は、すべての Office アプリケーションに含まれている共通セットではありません。 これらの機能を使用する Microsoft 365 アプリケーションによっては異なる可能性があります。 さまざまな制限付き機能の完全なリストについては、これあｒの Dataverse プランを含むこれら Microsoft 365 アプリケーションのサービスの説明を参照してください。 Dataverse のこれらの制限された機能では、ライセンスを受けたユーザーにスタンドアロンの Power Apps や Power Automate、または Dataverse を使用するその他の Microsoft Power Platform アプリケーションを実行する権利は与えられません。

3 文目に「これあｒ」と言う文字列がありますが、恐らく「これらの」ではないかと思われます。

ご確認をお願いします。

Toxumuharu

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Microsoft Power Platform ライセンスの概要 - Power Platform](https://docs.microsoft.com/ja-jp/power-platform/admin/pricing-billing-skus#capabilities-included)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Toxumuharu. This issue has been assigned to the doc author for review.

**Comment by Toxumuharu** [comment]
Hi @bishalgoswami, I hope my comment is helpful:)

**Comment by jimholtz** [comment]
@Toxumuharu 
Thanks for letting us know. We'll get this addressed.
