### ISSUE TITLE
What is the difference between Membership Types

### ISSUE THREAD

**Issue by binaryjam** [MicrosoftDocs/power-platform#1199]
Im creating an AAD team and the membership type question is there,  whats the diff between "members" and "members and guests"
I kind of need to know this, exactly what effect this has, its not in this page, thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc48e173-18f4-85d8-5938-91be592204cd
* Version Independent ID: be1f1a63-c300-b120-0d1a-6c22ebc76e7a
* Content: [Manage group teams - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-group-teams)
* Content Source: [power-platform/admin/manage-group-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/manage-group-teams.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @binaryjam. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@binaryjam 
Thanks for the content suggestion. We've added content to address your question.
