### ISSUE TITLE
Clarification for the "What is a Microsoft Power Platform request" section

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/power-platform#12]
For some reason that section is mentioning async workflows but it's not differentiating "sync" plugins from "async" plugins. Is there any difference between sync/async in terms of counting the API requests made from those plugins/workflows? Or will all requests be counted no matter if it's from within a sync or async plugin/workflow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#what-is-a-microsoft-power-platform-request)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@ashlega 
What I heard back from our product team:
These are examples of calls. It is not a full list of all the types of patterns. So all requests are counted, No matter which type of plugin/workflow it comes from.

**Comment by JimDaly** [comment]
@jimholtz 
This topic would benefit from a link to [Common Data Service API limits overview] (https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview), a new topic that calls out the impact of various limits specifically for CDS.

**Comment by jimholtz** [comment]
@JimDaly 
Good suggestion. Done.
