### ISSUE TITLE
Data sync

### ISSUE THREAD

**Issue by nzkelvin** [MicrosoftDocs/power-platform#120]
Does Microsoft have best practice, tools and services on data sync between master and slave data source in the context of multi-tenant deployment? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c5c060a-c1f1-64d8-42fc-dba04c35ac29
* Version Independent ID: 7c4820ec-a83c-141b-dcd2-13fd7c45082b
* Content: [Multiple environments or tenants - Power Platform Admin center](https://docs.microsoft.com/en-nz/power-platform/admin/multiple-online-environments-tenants)
* Content Source: [power-platform/admin/multiple-online-environments-tenants.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/multiple-online-environments-tenants.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@nzkelvin 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
