### ISSUE TITLE
PerApp Licensing Consumption report

### ISSUE THREAD

**Issue by Dlutchy** [MicrosoftDocs/power-platform#1200]
Do you have any estimate on when a PerApp License Consumption Report will be available? 
I have assigned 100 licenses and have no idea of consumption. If there is any current way to see consumption I would be interested to know.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1f9ece-05b6-907c-9d52-5a19f5bf9872
* Version Independent ID: 9eaed30a-4c07-ef03-e3b4-d3db9989a760
* Content: [About Power Apps per app plans - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-powerapps-perapp)
* Content Source: [power-platform/admin/about-powerapps-perapp.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/about-powerapps-perapp.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @alaug
* Microsoft Alias: **alaug**

**Comment by jimholtz** [comment]
@Dlutchy 
Thanks for your suggestion. We’re working on this feature but don’t yet have a date for public availability.
