### ISSUE TITLE
Upgrading holding solution - Error

### ISSUE THREAD

**Issue by IbrahimElSayed1** [MicrosoftDocs/power-platform#1207]
We received the following error while upgrading a holding solution. We are not entirely sure whether the issue is from the Power Platform Tools or Not. Thank you for the support.

The following is an error on a step in a Release Pipeline

![image](https://user-images.githubusercontent.com/103506329/162957420-855c00b2-2cd8-4134-a404-6d10ef460588.png)

**Comment by jimholtz** [comment]
@IbrahimElSayed1 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/
