### ISSUE TITLE
Types of environments

### ISSUE THREAD

**Issue by fhunth** [MicrosoftDocs/power-platform#121]
Type	You can choose production or trial.

Should be 

Type	You can choose production or trial or sandbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform Admin center - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/create-environment#feedback)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@fhunth 
Thanks for bringing this to our attention. We'll get this corrected soon.
