### ISSUE TITLE
翻訳の間違い

### ISSUE THREAD

**Issue by okuo** [MicrosoftDocs/power-platform#1210]
ページ内では「資源」という言葉が使われているが、実際のサイトでは「リソース」となっていたため、
修正が必要。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c3f8c1ca-4250-85c7-2b8e-caab633d8d9d
* Version Independent ID: 70065f90-617e-d812-e04e-7594708b0cce
* Content: [新しい Microsoft Dataverse ストレージ容量 - Power Platform](https://docs.microsoft.com/ja-jp/power-platform/admin/capacity-storage)
* Content Source: [power-platform/admin/capacity-storage.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/admin/capacity-storage.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @cpdSeattle
* Microsoft Alias: **camdebay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @okuo. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@okuo 
Thanks for the feedback. We've passed this on to our localization team for attention.
