### ISSUE TITLE
Is there an official icon for Power Portals? Can we get this added to the collection if so?

### ISSUE THREAD

**Issue by RicLund** [MicrosoftDocs/power-platform#1211]
Per the title. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1e3e9c-4177-7991-9e9a-861baf21cbd2
* Version Independent ID: 51970c35-5399-e9b2-ac1b-250032f2840d
* Content: [Microsoft Power Platform icons - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/icons)
* Content Source: [power-platform/guidance/icons.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/icons.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@RicLund No, we don't have an official icon for Power Apps portals. Thanks for checking.

**Comment by smadep** [comment]
it would be really great to have all icons (like for Azure) to document our Power Platform architecture with plantuml.
icons like:

- custom connector
- portal
- environment
- environment variable
- connection
- connection reference
