### ISSUE TITLE
PowerShell for Flow: How can we get the flow runs for a flow that is part of a solution?

### ISSUE THREAD

**Issue by drewbino-rcg** [MicrosoftDocs/power-platform#1212]
The Get-FlowRun cmdlet doesn't return anything for flows that are part of a solution.

The Get-AdminFlow seems to retrieve flows that are part of a solution but not the runs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @drewbino-rcg. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@drewbino-rcg 
Thanks for the feedback. Here's what the product team reports:

Cloud flow run history data is not available in Dataverse.  Desktop flow run history is available in Dataverse in the FlowSession table. Currently you can use the flow\X\runs API directly to get cloud flow run history data for a flow or create a custom connector for that API. 

We're working to correct different behavior for cloud flows in solution and not.
