### ISSUE TITLE
Power Platform requests limit in Teams (select Microsoft 365 subscriptions) was changed from 2,000 to 6.000.

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/power-platform#1213]
I believe Power Platform requests limit in Teams (select Microsoft 365 subscriptions) was changed from 2,000 to 6.000.

Could you check "Power Virtual Agents subscription limits" section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07c96368-89fa-6451-b091-d59ed754cd75
* Version Independent ID: 140f2cc2-70d0-334a-8707-a1cde39fd75b
* Content: [Rate limits for chatbots - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/requirements-quotas)
* Content Source: [power-virtual-agents/requirements-quotas.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/requirements-quotas.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MiyukiAmino. This issue has been assigned to the doc author for review.

**Comment by v-alarioza** [comment]
Hi @MiyukiAmino, I believe this is correct, but there might be something out of sync somewhere. Where did you read that the limit had been increased?

**Comment by MiyukiAmino** [comment]
Hi, @v-alarioza.
Oh. really? Perhaps, I'm misunderstanding about this limitation. I believed this 2000 api request is same as Power Platform requests: https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#licensed-user-request-limits.

API request limit with M365 license was increased in Nov. 2021, so I thought API request limit in PVA for Teams (select Microsoft 365 subscriptions) was also increased at the same time.

**Comment by v-alarioza** [comment]
@MiyukiAmino I double checked and you are indeed correct! We'll get this change published soon. Thanks for reporting it!
