### ISSUE TITLE
Please add to "Description" of "Teams member" of "Role assignments".

### ISSUE THREAD

**Issue by yamadaSANdes** [MicrosoftDocs/power-platform#1214]
Please add to "Description" of "Teams member" of "Role assignments".
Teams members can create flows within Microsoft Teams tabs, but they cannot create flows on the 'flow.microsoft.com' screen.
Also, Teams members cannot export / import flows.
Teams members can operate resources only within the microsoft Teams screen.

Please post this information not only in English but also in Japanese.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 66be7882-5440-7cff-142f-4436a2d648ca
* Version Independent ID: b1876c76-62e5-2e0f-c823-09be35cfd7a5
* Content: [Microsoft Dataverse for Teams について - Power Platform](https://docs.microsoft.com/ja-jp/power-platform/admin/about-teams-environment#role-assignments)
* Content Source: [power-platform/admin/about-teams-environment.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/admin/about-teams-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @yamadaSANdes. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@yamadaSANdes 
From the product team: 
Team members are assigned maker permissions so yes they can create flows in flow.microsoft.com as well. There isn’t any limitation there for members.
