### ISSUE TITLE
Clarity of two similar options needed (Basic and Minimum)

### ISSUE THREAD

**Issue by bronsonacoutts** [MicrosoftDocs/power-platform#1217]
This page could do with some clarity or an explanation about the differences between the SR contained within the downloadable "Minimum Privilege Security Role" and the Standard Role "Basic User".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure user security in an environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/database-security#predefined-security-roles)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/database-security.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@bronsonacoutts 
Thanks for the feedback. From the product team:
The minimum priv role doesn’t have any privileges to core tables which the Basic user sec role does. The min priv role is strictly for launching an app and the user will not be able to look up any records.
