### ISSUE TITLE
The abbreviation might be wrong here

### ISSUE THREAD

**Issue by johnsonmattMS** [MicrosoftDocs/power-platform#1218]
[Enter feedback here]

"Recovery Point Objective (RBO) is small and could take up to a few seconds or couple of minutes."
In another part of this article is is referred to as RPO. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b14fdc12-b544-951b-7275-f1e41eb72e1f
* Version Independent ID: 84cd2dac-d190-5a20-7dfb-71703016b43b
* Content: [Business continuity, disaster recovery for Dynamics 365 SaaS apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/business-continuity-disaster-recovery)
* Content Source: [power-platform/admin/business-continuity-disaster-recovery.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/business-continuity-disaster-recovery.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @MicroSri
* Microsoft Alias: **sriknair**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @johnsonmattMS. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@johnsonmattMS 
Thanks for the heads up. We'll get this fixed.
