### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by burtzz** [MicrosoftDocs/power-platform#122]
Hi, could you please update the article to explain what happens to existing apps?
You mention "If one of the person who is part of the DLP policy's environment create an app shares data between SharePoint or Salesforce and any service in the No business data allowed data group, the app will not be allowed to run."
But what if the App already exists? 
Is it guaranteed that a freshly made DLP policy will also block apps with connectors from different data groups?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0214fce6-e815-f25e-6a87-82feaa7670b1
* Version Independent ID: 5b6e253d-b2a1-afdd-1c3b-e586ba6fa321
* Content: [Data groups - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/introduction-to-data-groups#feedback)
* Content Source: [power-platform/admin/introduction-to-data-groups.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/introduction-to-data-groups.md)
* Service: **power-platform**
* GitHub Login: @manasmams
* Microsoft Alias: **manasma**

**Comment by jimholtz** [comment]
@burtzz 
Sorry for the delayed response. We are making updates to Power Apps data loss prevention and will be revising this documentation. Check back for changed content.
