### ISSUE TITLE
Missing standalone plans 

### ISSUE THREAD

**Issue by PowershellScripts** [MicrosoftDocs/power-platform#1220]
As per MS support, SharePoint Online standalone plans also include Power Automate capabilities.  That means that in this article 2 plans are missing from the list below the phrase "The following Office 365 licenses include Power Automate capabilities."
SharePoint Online Plan 1
SharePoint Online Plan 2

Case number for reference:  30746744 

Opening this as an issue, not PR, because perhaps that information should undergo additional verification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b98a3d2-eee9-5956-4e6f-65a0240db884
* Version Independent ID: 8b98a3d2-eee9-5956-4e6f-65a0240db884
* Content: [Frequently asked questions about Power Automate licensing - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/power-automate-licensing/faqs)
* Content Source: [power-platform/admin/power-automate-licensing/faqs.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/power-automate-licensing/faqs.md)
* Service: **power-platform**
* GitHub Login: @PriyaKodukula
* Microsoft Alias: **prkoduku**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PowershellScripts. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@PowershellScripts 
Thanks for the feedback. We're in the process of updating this content.
