### ISSUE TITLE
Read Write mode instead of Administrative

### ISSUE THREAD

**Issue by nishantranacrm** [MicrosoftDocs/power-platform#1223]
[Enter feedback here]

"Global and Power Platform admins who don't have a license are automatically synced into the environment with an access mode of 'Administrative' while administrators who have a license are synced into the environment with an access mode of 'Read-Write'. These administrators are assigned a System Administrator security role"

The user with with Global Admin role and no license assigned after sync was having access mode as Read-Write instead of Administrative. Could you please check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcee36d9-db29-ea20-5930-5c2f1413c1e8
* Version Independent ID: 3bb86810-579a-6f7f-f07c-61b6cd6b8e35
* Content: [Administrator access for unlicensed Power Platform and Global admins - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/global-service-administrators-can-administer-without-license)
* Content Source: [power-platform/admin/global-service-administrators-can-administer-without-license.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/global-service-administrators-can-administer-without-license.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nishantranacrm. This issue has been assigned to the doc author for review.
