### ISSUE TITLE
Is deprecation of Dynamics 365 connector also for Power Bi or is that a different connector?

### ISSUE THREAD

**Issue by SamoPaw** [MicrosoftDocs/power-platform#1224]
Is deprecation of Dynamics 365 connector also for Power Bi ? In the connection list in Power Bi (desktop) , the Dynamics connector is not renamed to 'Dynamics 365 connector (deprecated)' and remains 'Dynamics 365 (online)', checked this just now.
Do we need to change all older reports to the Dataverse connector as well?

If so, can it be mentioned on this page?

For now, only Power Automate, Logic Apps, Power Apps and Data integrations are mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps and Power Automate - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#dynamics-365-connector-is-deprecated)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/important-changes-coming.md)
* Service: **power-platform**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SamoPaw. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@SamoPaw 
Greetings. Only Power Automate, Logic Apps, and Power Apps are mentioned because those are the only ones affected by this change. Power BI is not.
