### ISSUE TITLE
Please describe separately "with Dataverse" and "without Dataverse"

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/power-platform#1226]
section: Summary of resources available for predefined security roles

This doc says, "EnvironmentMaker has not capability to create desktop flows".
If the Env has no dataverse, this is true, but if the Env has Dataverse, it's not true.

To clarify for the security role capability, please describe separately "with Dataverse" and "Without Dataverse".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure user security in an environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/database-security?msclkid=0d4103edc4fb11ec9eb6e4fbbbb96f9c#summary-of-resources-available-for-predefined-security-roles)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/database-security.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@MiyukiAmino 
Thanks for the feedback. Taking to internal thread.
