### ISSUE TITLE
Where do I run the PowerShell script for ALM Accelerator manual setup?

### ISSUE THREAD

**Issue by MattyBearBytes** [MicrosoftDocs/power-platform#1227]
Hi There,

Trying to run the PowerShell script.
Not clear where I run this - on my Windows Machine or within the PowerShell console in the Azure Portal?

When running in Azure Portal I get error on the 3rd line:
`New-PowerAppManagementApp: The 'New-PowerAppManagementApp' command was found in the module 'Microsoft.PowerApps.Administration.PowerShell', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerApps.Administration.PowerShell'.`

Thankyou

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d58c244-3aaa-48e6-8b6d-205521a0bc52
* Version Independent ID: 5d58c244-3aaa-48e6-8b6d-205521a0bc52
* Content: [Set up ALM accelerator for Microsoft Power Platform components manually - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform)
* Content Source: [power-platform/guidance/coe/setup-almacceleratorpowerplatform.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almacceleratorpowerplatform.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @mikefactorial
* Microsoft Alias: **v-mikeochs**

**Comment by mikefactorial** [comment]
@MattyBearBytes recommend running this on your machine. I've never tried running it in Azure Portal console, but you should be able to run it locally.

**Comment by mikefactorial** [comment]
If you have any follow-up questions can you open an issue on the github.com/microsoft/coe-starter-kit. We tend to triage / respond quicker over there. Closing for now.
