### ISSUE TITLE
How to get Latest Tag of 

### ISSUE THREAD

**Issue by MattyBearBytes** [MicrosoftDocs/power-platform#1228]
The example URL on this page of what Repo to clone is old.
The latest is April 2022.

For the non-GitHub aware user, I can get as far as seeing this when looking at the Repo's releases
https://github.com/microsoft/coe-alm-accelerator-templates/releases

However I'm not sure how to then get a URL to clone this into Azure DevOps

So I had to get the clone address for the master branch instead 

Can this be made more clear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d58c244-3aaa-48e6-8b6d-205521a0bc52
* Version Independent ID: 5d58c244-3aaa-48e6-8b6d-205521a0bc52
* Content: [Set up ALM accelerator for Microsoft Power Platform components manually - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform)
* Content Source: [power-platform/guidance/coe/setup-almacceleratorpowerplatform.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almacceleratorpowerplatform.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @mikefactorial
* Microsoft Alias: **v-mikeochs**

**Comment by alvarezskinner** [comment]
This is now resolved for our May Update, in summary you can now head to http://aka.ms/coe-alm-accelerator-templates-latest-release to always get the tag URL for the latest release of the templates.
