### ISSUE TITLE
missing information for portal reset

### ISSUE THREAD

**Issue by ShawnNulph** [MicrosoftDocs/power-platform#1229]
In this article, it states (in the purple bubble note) the following configurations are not preserved by the reset and will need to be reconfigured. However, there are no configurations listed. Is there information missing?

Note
The following configurations are not preserved by the portal reset and must be configured again in the new portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf83baaf-d9eb-6e3d-1040-9ae94cd410db
* Version Independent ID: ae37a7a0-1e5a-a2ef-72c8-bf6d2601cae1
* Content: [Migrate an environment to a different tenant - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/move-environment-tenant?tabs=image#confirm-if-any-of-the-solutions-below-are-installed-in-the-environments-to-be-migrated-as-these-may-require-additional-steps-either-from-you-or-support)
* Content Source: [power-platform/admin/move-environment-tenant.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/move-environment-tenant.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @matapg007
* Microsoft Alias: **matgupta**

**Comment by jimholtz** [comment]
@ShawnNulph 
Taking to internal thread.
