### ISSUE TITLE
MS docのタイトルを修正してほしい

### ISSUE THREAD

**Issue by WakakoWatanabe** [MicrosoftDocs/power-platform#1232]
以下のMS docのタイトルは、お客様に誤解を与える表現です。

Title : 例 2 - ユーザーが取引先企業レコードをグリッドに表示するときに生成されるログ ( Microsoft Excel へのエクスポート ログもこれと同様です)
https://docs.microsoft.com/ja-jp/power-platform/admin/enable-use-comprehensive-auditing#example-2--logs-generated-when-user-sees-account-records-in-a-grid-export-to-microsoft-excel-logs-are-like-this

このタイトルを見たお客様は「 “RetrieveMultiple”と同様に ”ExportToExcel” にもクエリ情報が記載される」と誤った認識をします。
実際に、サポート窓口にお客様が「 ”ExportToExcel” にクエリ情報が記載されない」と質問を送信してきました。

DEVにMS docの内容の確認を取り、お客様に以下のように説明をしました。
 - Dynamics 365 レコードをExcel へエクスポートした時に、“ユーザーが取引先企業レコードをグリッドに表示するときに生成される” 時と同様にそのクエリ情報が “RetrieveMultiple” に記載される、という意味である。

DEVもこのタイトルは紛らわしいことを認識しており、実際にお客様にも誤解を与えています。
スクリーンショットを見ると“RetrieveMultiple” を指していることを理解できますが、お客様はまずタイトルを先に見ます。
そして、このような誤解が今後も発生する可能性が高いです。
早急にタイトルの修正を検討していただけませんか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 97f28a46-531e-d373-40ad-f9e81b55fdf3
* Version Independent ID: a47230d1-92c1-28a3-2f2c-ada21450b1f2
* Content: [Microsoft Dataverse およびモデル駆動型アプリの活動ログ - Power Platform](https://docs.microsoft.com/ja-jp/power-platform/admin/enable-use-comprehensive-auditing#example-2--logs-generated-when-user-sees-account-records-in-a-grid-export-to-microsoft-excel-logs-are-like-this)
* Content Source: [power-platform/admin/enable-use-comprehensive-auditing.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/admin/enable-use-comprehensive-auditing.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by jimholtz** [comment]
Closing as this is a duplicate of 1231.
