### ISSUE TITLE
Missing connector requirement

### ISSUE THREAD

**Issue by ErenIsitan** [MicrosoftDocs/power-platform#1234]
In the "Before you start, Create connections" section, there is a missing connector that is required for the "Set up Audit Logs solution":
"Office 365 Management API"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

this is a custom connector and you'll set this one up and configure a connection for it here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

Thank you
Manuela
