### ISSUE TITLE
URL https;//graph.microsoft.com contains semi-colon rather than colon

### ISSUE THREAD

**Issue by Chris-WP** [MicrosoftDocs/power-platform#1236]
The URL https://graph.microsoft.com has a typo and includes a semi-colon rather than a colon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c049c09-0ffb-1994-6c5e-acd549988983
* Version Independent ID: 8c049c09-0ffb-1994-6c5e-acd549988983
* Content: [CoE CLI ALM accelerator for Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/overview)
* Content Source: [power-platform/guidance/coe/cli/alm/overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/cli/alm/overview.md)
* Service: **power-platform**
* GitHub Login: @Grant-Archibald-MS
* Microsoft Alias: **grarchib**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Chris-WP. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@Chris-WP 
Thanks for bringing this to our attention. We've corrected the typo.
