### ISSUE TITLE
Add a link to capacity add-ons instructions 

### ISSUE THREAD

**Issue by rickmcguire** [MicrosoftDocs/power-platform#1237]
We should add a link to capacity add-ons instructions here when talking about adding capacity, there are no instructions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e6d6293-77ef-6e80-46f3-fbe23d073964
* Version Independent ID: 9e6d6293-77ef-6e80-46f3-fbe23d073964
* Content: [Buy Power Automate licenses - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/power-automate-licensing/buy-licenses)
* Content Source: [power-platform/admin/power-automate-licensing/buy-licenses.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/power-automate-licensing/buy-licenses.md)
* Service: **power-platform**
* GitHub Login: @PriyaKodukula
* Microsoft Alias: **prkoduku**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rickmcguire. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
Closing and taking to internal thread.
