### ISSUE TITLE
When and How a tenant is created in Power Platform?

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/power-platform#124]
I have created 5 environments in power platform using a sub-domain name but can you 'point to' / 'add few lines' 
when, where and how a tenant is created. Is &lt;name&gt;.onmicrosoftonline.com is the tenant you are referring to?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c5c060a-c1f1-64d8-42fc-dba04c35ac29
* Version Independent ID: 7c4820ec-a83c-141b-dcd2-13fd7c45082b
* Content: [Multiple environments or tenants - Power Platform Admin center](https://docs.microsoft.com/en-gb/power-platform/admin/multiple-online-environments-tenants#uses-for-multiple-environments%C2%A0)
* Content Source: [power-platform/admin/multiple-online-environments-tenants.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/multiple-online-environments-tenants.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by sing-ideas** [comment]
Community reply says - Office 365 <name>.onmicrosoftonline.com is the tenant for your Power Apps.
Can you confirm in the doc by adding a line about tenant ID of power apps and O365 is one and the same.

Link : https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/PowerApps-is-Multi-Environment-in-Single-Tenant-what-is-my/m-p/491248#M2148

**Comment by jimholtz** [comment]
@sing-ideas
We will add a see also link to a blog explaining tenants.
