### ISSUE TITLE
Deployment Settings for Power Platform Deploy Package task

### ISSUE THREAD

**Issue by khoait** [MicrosoftDocs/power-platform#1245]
Hi,

I'm using "Power Platform Deploy Package" task to deploy my solution and configuration data. There are connection references in my solution. I couldn't find how to use Deployment Settings to set values for those connection references in Power Platform Deploy Package task. Is it possible for Deploy Package or only for Import Solution task?

Thanks,

Khoa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tool-tasks.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @khoait. This issue has been assigned to the doc author for review.

**Comment by caburk** [comment]
@khoait only for the solution import task currently.

**Comment by kkanakas** [comment]
Deploy package is different from deploying a solution. When a package is deployed it is not necessarily installed in the target. A package deploy action is usually staged and then you proceed to install the package via the Application install process.  Deployment settings is only available to solution import. You can provide runtime settings for packages. GitHub actions and Azure DevOps are based on the Power platform CLI. So, you can always test out the command outputs and see as well 
---------------------------------------------------
Microsoft PowerPlatform CLI
Version: 1.22.2+g401780b

Help:
Deploys package to Dataverse

Commands:
Usage: pac package deploy [--logFile] [--logConsole] --package [--settings] [--verbose]

  --logFile                   Log file path (alias: -lf)
  --logConsole                Output log to console (alias: -c)
  --package                   path to a package dll or zip file with a package (alias: -p)
  --settings                  Runtime Package Settings that are passed to the package that is being deployed.  The format of the string must be `key=value|key=value`. (alias: -s)
  --verbose                   Emit Verbose logs to the log outputs (alias: -vdbg)

**Comment by phecke** [comment]
@khoait Hope this answers your question. Closing this issue. If you still have questions, open another issue.
