### ISSUE TITLE
Article not acurate or needs updating?

### ISSUE THREAD

**Issue by mymebenha** [MicrosoftDocs/power-platform#1246]
In the Look for list, select System Jobs.

In the search criteria area, add criteria similar to the following:

I followed the steps exactly however, there is no look for list or any list that contains "system jobs"  There is no place for search criteria, only a search box and a filter icon.  These are steps 4 and 5 under Reduce database storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9c9aae-ceaa-2e78-3752-2770327f49a7
* Version Independent ID: acd2ddc9-6225-92e8-2636-2a02437c3d82
* Content: [Free up storage space - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/free-storage-space#reduce-database-storage)
* Content Source: [power-platform/admin/free-storage-space.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/free-storage-space.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Bluebear73
* Microsoft Alias: **munzinge**

**Comment by jimholtz** [comment]
@mymebenha 
Sorry you're having this issue. I tested the steps and they worked for me as documented. If the issue persists, please contact Support: https://powerapps.microsoft.com/support/
