### ISSUE TITLE
This page requires updates based on the new Team Member app enforcement

### ISSUE THREAD

**Issue by veeyeskay** [MicrosoftDocs/power-platform#125]
There is a new report which was added to the list of downloadable report, based on the new Team Member license enforcement which has been introduced recently. This needs to be updated on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c99626-6458-46b4-f099-ce10c30890c7
* Version Independent ID: d3766ded-359b-160c-d7f5-a7e6ffa103d6
* Content: [Common Data Service analytics - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service#feedback)
* Content Source: [power-platform/admin/analytics-common-data-service.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/analytics-common-data-service.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@veeyeskay 
Thanks for the notification. The content has been updated.
