### ISSUE TITLE
Get-AdminPowerAppConnector doesn't return all custom connectors in tenant

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/power-platform#1250]
It looks like Get-AdminPowerAppConnector doesn't return all custom customers in tenant. the custom connectors belongs to the solution cannot be returned from this cmdlet. we do have [Add Custom Connector to DLP #564](https://github.com/MicrosoftDocs/power-platform/issues/564#:~:text=Get-AdminPowerAppConnector%20does%20not%20return%20custom%20connectors%20that%20are,this%20is%20a%20known%20limitation%20at%20the%20moment.) mentioned the same limit. Can we add limit there or provide the walkaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @frankchen76. This issue has been assigned to the doc author for review.
