### ISSUE TITLE
How to increase file size from 32 MB

### ISSUE THREAD

**Issue by rashid60** [MicrosoftDocs/power-platform#1256]
[Enter feedback here]
Hi MS Power Platform Team,

I have one question about the file size. As mentioned on the page, currently max. size limit is 32 MB.  I would like to ask if there's possibility to increase the size from this limit value.

Thanks and Regards,
Rashid Ali

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57973473-982b-1752-f2f6-126bc93e32f5
* Version Independent ID: 6bda1f78-8a36-d327-fd3c-b86bffc6ba11
* Content: [System Settings Email tab - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/system-settings-dialog-box-email-tab)
* Content Source: [power-platform/admin/system-settings-dialog-box-email-tab.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/system-settings-dialog-box-email-tab.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rashid60. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@rashid60 
Please contact support: https://powerapps.microsoft.com/support/
