### ISSUE TITLE
Should we also mention Dataverse and AI Builder

### ISSUE THREAD

**Issue by cimaja** [MicrosoftDocs/power-platform#1257]
Dataverse is included in this pack and when are also working with Jason K. to add the AI Builder icon. For SEO purposes and highlight what the pack contains should we add Dataverse and AI Builder inside the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1e3e9c-4177-7991-9e9a-861baf21cbd2
* Version Independent ID: 51970c35-5399-e9b2-ac1b-250032f2840d
* Content: [Microsoft Power Platform icons - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/icons)
* Content Source: [power-platform/guidance/icons.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/icons.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @cimaja. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
@cimaja Closing this issue and following up internally.
