### ISSUE TITLE
ClientGlobalContext.js.aspx deprecated again?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/power-platform#1258]
The "Dynamics 365 and Power Platform Monthly Update-May 2022" mentions that the ClientGlobalContext.js.aspx will be deprecated in October 2022. Is this true or outdated information in the Monthly Update?

Link to the Monthly Update: https://community.dynamics.com/crm/b/crminthefield/posts/dynamics-365-and-power-platform-monthly-update-may-2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps and Power Automate - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/important-changes-coming.md)
* Service: **power-platform**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
@darshSWL It's outdated information. ClientGlobalContext.js.aspx isn't deprecated. Closing the issue.
