### ISSUE TITLE
What happens if Security Group is deleted in Office Admin site?

### ISSUE THREAD

**Issue by AgileXRM** [MicrosoftDocs/power-platform#126]
The Security Group cannot currently be de-associated, but what if the actual Group is deleted in office admin?
What would be the expected behavior? De-associate? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/control-user-access)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@AgileXRM 
Thanks for bringing this to our attention. We're aware of this issue and working on a fix.
