### ISSUE TITLE
PowerShell Forbidden Error

### ISSUE THREAD

**Issue by WilliamDO89** [MicrosoftDocs/power-platform#1260]
Getting the following error when running the PowerShell Command.

```
Invoke-RestMethod : {"error":{"code":"Forbidden","message":"The service principal with id '#######-####-####-####-##########' for application #######-####-####-####-########## does not have permission to access the path 
'https://10.0.1.32:20029/providers/Microsoft.BusinessAppPlatform/scopes/admin/environments?api-version=2020-10-01&$expand=properties.capacity,properties.addons' in tenant #######-####-####-####-##########."}}
```
The App Registration has the Power Platform API permissions and Service Principal has the PowerPlatform admin role too. 

Is this something else that should be added to make this work. 

![image](https://user-images.githubusercontent.com/105913408/169490976-724421fd-fb4d-4b79-ad9b-1bb504d83a35.png)

**Comment by jimholtz** [comment]
@WilliamDO89 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
