### ISSUE TITLE
External Users and portals

### ISSUE THREAD

**Issue by Papa-Cho** [MicrosoftDocs/power-platform#1261]
[Enter feedback here]
Hello 

About Pay-as-you-go, the FAQ indicates that it works for external users when registered as guest users in my AD. 
In the case I have a Portals app for these external users on which they authenticate. So they have an account on the POrtals app but not in my tenant AD (no guest user). Is this use case covered by the Pay-as-you-go plan?

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6030a2f5-a21a-dc04-577a-ac81009c9ac4
* Version Independent ID: 6030a2f5-a21a-dc04-577a-ac81009c9ac4
* Content: [Issues and FAQs about pay-as-you-go plans - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/pay-as-you-go-issues-faq)
* Content Source: [power-platform/admin/pay-as-you-go-issues-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/pay-as-you-go-issues-faq.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Kavishi
* Microsoft Alias: **kaagar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Papa-Cho. This issue has been assigned to the doc author for review.

**Comment by Papa-Cho** [comment]
Hello 
Apologies for chasing but it would really help me to get an answer here

**Comment by jimholtz** [comment]
@Papa-Cho 
Sorry for the delayed response. This content has been rewritten. Please reopen if your question is not addressed.
