### ISSUE TITLE
custom connector for management api

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/power-platform#1262]
is there a way to just import this audit log custom connector component, or do I need to import the whole coe solution and configure it? The section about setting up the audit log connector just shows that it is available in custom connectors. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

no, the Audit Log solution is an add-on to our Core components solution so you will need to install Core components first and you can then add the Audit Log solution on to it.

Thank you
Manuela
