### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by bronsonacoutts** [MicrosoftDocs/power-platform#1263]
The URL to download the min priv security role throws a 404.

[Microsoft Dataverse minimum privilege security role](https://download.microsoft.com/download/6/5/5/6552A30E-05F4-45F0-AEE3-9BB01E13118A/MinprivilegeSecRole_1_0_0_0.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c40f87c-1a3a-399d-d25f-ae348dc5e248
* Version Independent ID: 4784510f-a482-f73a-85e2-f2e6d74168c3
* Content: [Create or edit a security role - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-edit-security-role)
* Content Source: [power-platform/admin/create-edit-security-role.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-edit-security-role.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bronsonacoutts. This issue has been assigned to the doc author for review.

**Comment by paulliew** [comment]
+ @Jim ***@***.***>
We have upgraded the file (version 2) and Jim replaced it for me recently.

@jim to help respond Assigned #1263<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpower-platform%2Fissues%2F1263&data=05%7C01%7Cpaulliew%40microsoft.com%7C28a589988abc423bafe508da3bf3145b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637888212452605726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=B5K7YI6Zq%2FGuDBURanz7Qe1LtPNbaREVTDDak09giYw%3D&reserved=0> to @paulliew<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpaulliew&data=05%7C01%7Cpaulliew%40microsoft.com%7C28a589988abc423bafe508da3bf3145b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637888212452605726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fTD66pHrZYeMaqRLpcegXHsx%2FXtKTrSL4PDI6JbYWa4%3D&reserved=0>.



From: Bronson Coutts ***@***.***>
Sent: Sunday, May 22, 2022 5:34 AM
To: MicrosoftDocs/power-platform ***@***.***>
Cc: Paul Liew ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/power-platform] Broken URL (Issue #1263)


The URL to download the min priv security role throws a 404.

Microsoft Dataverse minimum privilege security role<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdownload.microsoft.com%2Fdownload%2F6%2F5%2F5%2F6552A30E-05F4-45F0-AEE3-9BB01E13118A%2FMinprivilegeSecRole_1_0_0_0.zip&data=05%7C01%7Cpaulliew%40microsoft.com%7Ca91cc4ac8ad846d4b23008da3bef5a2c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637888197027377967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tOcxcNMpw4m%2Br5AYw2oCZIJR0Uu24Taffoa4NJAgvFQ%3D&reserved=0>

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 3c40f87c-1a3a-399d-d25f-ae348dc5e248
  *   Version Independent ID: 4784510f-a482-f73a-85e2-f2e6d74168c3
  *   Content: Create or edit a security role - Power Platform<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpower-platform%2Fadmin%2Fcreate-edit-security-role&data=05%7C01%7Cpaulliew%40microsoft.com%7Ca91cc4ac8ad846d4b23008da3bef5a2c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637888197027377967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l%2FL8fpr2DfMfcrFEk3f9%2BMzxM74D2r59%2BPAWx8XZtP8%3D&reserved=0>
  *   Content Source: power-platform/admin/create-edit-security-role.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpower-platform%2Fblob%2Fmain%2Fpower-platform%2Fadmin%2Fcreate-edit-security-role.md&data=05%7C01%7Cpaulliew%40microsoft.com%7Ca91cc4ac8ad846d4b23008da3bef5a2c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637888197027377967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GxdEb%2F5oFrLUhu7q5UCXCgbfSc1yQj8XJbbfq4GqU28%3D&reserved=0>
  *   Service: power-platform
  *   Sub-service: admin
  *   GitHub Login: @paulliew<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpaulliew&data=05%7C01%7Cpaulliew%40microsoft.com%7Ca91cc4ac8ad846d4b23008da3bef5a2c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637888197027377967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X957T%2F3gYe2DODxHFYZZM9PJypbWaFZUXu9eCuZGzBc%3D&reserved=0>
  *   Microsoft Alias: paulliew

**Comment by jimholtz** [comment]
@bronsonacoutts 
Thanks for bringing this to our attention. The link has been fixed.
