### ISSUE TITLE
Refresh Error -Column 'admin_portalenvironment' in Table 'Portals' contains a duplicate value

### ISSUE THREAD

**Issue by Sishira** [MicrosoftDocs/power-platform#1264]
<html>
<body>
<span ng-transclude="" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, wf_segoe-ui_normal, helvetica, arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 249, 174); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span ng-bind="lastRefreshStatus">Last refresh failed: Sat May 14 2022 15:14:21 GMT+0530 (India Standard Time)</span><br><span ng-bind="lastRefreshFailureMessage">There was an error when processing the data in the dataset.</span></span><span ng-if="nameValuePairs!=null" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, wf_segoe-ui_normal, helvetica, arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 249, 174); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="detailsExpander" ng-click="detailExpand=!detailExpand" ng-switch="detailExpand" ng-show="showTitle" style="margin-left: 5px;"><a href="https://app.powerbi.com/" localize="SettingsDataset_HideDetails" ng-switch-when="true" style="background: 0px 0px; color: rgb(0, 120, 212); white-space: nowrap;">Hide details</a></span>

Data source error: | Column '<pii>admin_portalenvironment</pii>' in Table '<pii>Portals</pii>' contains a duplicate value '<pii>11bc932b-a788-4699-8130-b74caa15028f</pii>' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
-- | --
Cluster URI: | WABI-US-NORTH-CENTRAL-C-PRIMARY-redirect.analysis.windows.net
Activity ID: | b08b93ef-60a2-455d-9f20-137cbc976514
Request ID: | 0ef9d64a-22f7-447a-a2c9-5f7ee2d70a12
Time: | 2022-05-14 09:44:21Z

</span>
</body>
</html>Last refresh failed: Sat May 14 2022 15:14:21 GMT+0530 (India Standard Time)
There was an error when processing the data in the dataset.[Hide details](https://app.powerbi.com/)
Data source error:	Column '<pii>admin_portalenvironment</pii>' in Table '<pii>Portals</pii>' contains a duplicate value '<pii>11bc932b-a788-4699-8130-b74caa15028f</pii>' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
Cluster URI:	WABI-US-NORTH-CENTRAL-C-PRIMARY-redirect.analysis.windows.net
Activity ID:	b08b93ef-60a2-455d-9f20-137cbc976514
Request ID:	0ef9d64a-22f7-447a-a2c9-5f7ee2d70a12
Time:	2022-05-14 09:44:21Z``

**Comment by jimholtz** [comment]
@Sishira 
Please let us know which topic on docs.microsoft.com you found with the duplicate values.

**Comment by jimholtz** [comment]
@Sishira 
If this is still an issue, please contact support: https://powerapps.microsoft.com/support/
