### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by guildwebdev** [MicrosoftDocs/power-platform#1266]
Under the heading "What happens when my organization exceeds storage entitlements?"

There is no mention of performance degradation (or not).  You must state that information here, whether there is degradation or not. 
 A simple google search will show you that anybody using this product wants that question answered.  A simple paragraph under this heading would save a lot of trouble and support calls.

Also, is there a point at which we need to add more capacity ??  when we're at 70%?  80% ??  What are the recommended threshold for this ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5297a60-9f8d-0a32-5d51-4adc5fbb7856
* Version Independent ID: 2a027441-3f4d-42a8-b6b3-c24b54947b09
* Content: [What's new for storage administration in Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/whats-new-storage?WT.mc_id=ppac_inproduct_resources)
* Content Source: [power-platform/admin/whats-new-storage.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/whats-new-storage.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @cpdSeattle
* Microsoft Alias: **camdebay**

**Comment by cpdSeattle** [comment]
The actions for being over your tenant's storage entitlement are the specific environment-level administrative actions that are listed in the section below. To your question, there is currently no specific degradation in performance for being above storage entitlements. Capacity usage warnings are sent out at 15% remaining, 5% remaining, and zero percent remaining (said another way: at 85%, 95%, and >100% usage).  Individual purchase decisions for add-on storage vary tenant to tenant based on the number of licenses that impacts their overall entitlements, and their ongoing organic growth in usage, offset by any ongoing storage management approaches that reduce usage (examples such as: bulk delete, audit retention policies, deletion of old environments)
https://docs.microsoft.com/en-gb/power-platform/admin/capacity-storage?WT.mc_id=ppac_inproduct_resources#changes-for-exceeding-storage-capacity-entitlements

**Comment by guildwebdev** [comment]
Thanks for the info.  Yes I had read that, though being over capacity would imply performance degradation of some kind.  There are lots of people searching for clarification on this.  Thanks again.
