### ISSUE TITLE
SLA for DLP policy to take effect

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/power-platform#1267]
https://docs.microsoft.com/en-us/power-platform/admin/dlp-impact-policies-apps-flows

Seeing more than 5 minutes when adding connectors to DLP and also when removing environments from a policy.  Is there an SLA for when DLP policy is to be sure in effect? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 689d7424-a982-8dd6-3010-5747ea17bdfb
* Version Independent ID: 10bb9812-2719-5c3b-91d5-03551509d270
* Content: [Impact of DLP policies on apps and flows - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/dlp-impact-policies-apps-flows)
* Content Source: [power-platform/admin/dlp-impact-policies-apps-flows.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/dlp-impact-policies-apps-flows.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @mikferland-msft
* Microsoft Alias: **miferlan**

**Comment by jimholtz** [comment]
@samadane 
Sorry for the delayed response. Taking to internal thread.
