### ISSUE TITLE
Only groups of type "Security" work but any type of group is selectable when associating

### ISSUE THREAD

**Issue by AgileXRM** [MicrosoftDocs/power-platform#127]
There are 4 types of groups in Office Admin (Office365, DistributionList, Mail-enabled security and Security). 
When associating a group to the environment, many types of groups are listed for selecting, but only if the group is of type Security then things work correctly. In fact we noticed that "Office365" type groups work partially, which is really confusing.
I would specifically add to docs to make sure the group is not one of the other types (or even better ask dev team to filter and only show groups of type Security when associating).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/control-user-access)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@AgileXRM 
Thanks for bringing this to our attention. We've added the following to the topic:
Common Data Service environments support associating the following group types: Security and Office 365. Associating other group types is not supported.

If you're having an issue with the Office 365 group, please raise this with support.
