### ISSUE TITLE
Known limitation of Child Flows are related to "HTTP" connector, not "HTTP with Azure AD"

### ISSUE THREAD

**Issue by valeryplotnik** [MicrosoftDocs/power-platform#1272]
Hello,

The "Child Flows" section contains reference to "HTTP with Azure AD" as the connector, which shouldn't be blocked to support child flows running. It isn't true. Just "HTTP" connector is the right one. Here is the screenshot from my Dev account with only on HTTP connector blocked. Error is shown when you are trying to activate your parent flow:

![image](https://user-images.githubusercontent.com/1720689/170462306-583018e6-ab4f-4ec6-b009-6bbca5b005d6.png)

![image](https://user-images.githubusercontent.com/1720689/170462385-ce27dba8-2690-4d7c-9261-a9a6086ae689.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1458dc-a93c-ce85-244b-fc1d32a0c3d7
* Version Independent ID: 1448346a-d12e-871a-7549-c5e3529f7833
* Content: [Known limitations for data loss prevention (DLP) policies - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/dlp-known-issues)
* Content Source: [power-platform/admin/dlp-known-issues.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/dlp-known-issues.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @mikferland-msft
* Microsoft Alias: **miferlan**

**Comment by jimholtz** [comment]
@valeryplotnik 
Sorry for the delayed response. We'll pass this on to the product group for their attention.
