### ISSUE TITLE
The Enable Dynamics 365 apps decision 

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/power-platform#1274]
Hello, 

The documentation says :
The Enable Dynamics 365 apps decision is not reversible: Once you create an environment, if you don't select Enable Dynamics 365 apps at the time of database provisioning, you won't be able to make this change later nor be able to install Dynamics 365 apps on this environment.

But is doesn't say why one would choose an option or the other. In doubt we are tempted to enable it.
Can you clarify the consequences and use case of enabled/Not enabled?

Thank you

Pierre-Olivier

**Comment by jimholtz** [comment]
Refers to this topic: https://docs.microsoft.com/en-us/power-platform/admin/create-environment

**Comment by jimholtz** [comment]
@popujol 
Sorry for the delayed response and thank you for the suggestion. We'll be updating this content in the future and will review your suggestion then.
