### ISSUE TITLE
Switch environment type causes downtime? Update picture

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/power-platform#1275]
I just walked through the convert to prod and convert to sandbox and the screenshot in the documentation is not up to date.  This is what mine looks like and does not specify any down time.  

![image](https://user-images.githubusercontent.com/43175066/170729371-175dac75-f3e9-4a77-9ba8-592de918cea5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35d3f3b-0007-bbb7-fe0b-000e76932281
* Version Independent ID: d937d8d8-232d-ce0e-ae88-38d95e501793
* Content: [Change environment type - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/switch-environment)
* Content Source: [power-platform/admin/switch-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/switch-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @samadane. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@samadane 
Thanks for bringing this to our attention. We'll get this updated.
