### ISSUE TITLE
Dynamics 365 Connector actions/triggers cannot be edited in flows as of now, this article says they can

### ISSUE THREAD

**Issue by khoanguyen-ms** [MicrosoftDocs/power-platform#1279]
[Enter feedback here]

In https://docs.microsoft.com/en-us/power-platform/important-changes-coming#automate :
Automate
Dynamics 365 connector can't be selected for creating a new flow.
Existing flows will continue to run.
You will be able to edit an existing flow but you cannot add additional Dynamics 365 connector actions to the flow

Actual behavior:
Dynamics 365 connectors are not showing.
On April 29, 2022, Nadeem Ansari (CRM) posted an announcement email saying that following that day, ""Microsoft Power Automate flows will no longer be able to be created or edited using the Dynamics 365 connector".

Please fix the public document accordingly so we can provide it to support customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps and Power Automate - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#dynamics-365-connector-is-deprecated)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/important-changes-coming.md)
* Service: **power-platform**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @khoanguyen-ms. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@khoanguyen-ms 
Taking to internal thread.
