### ISSUE TITLE
Definition of Primary Environment vs Additional Environment

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/power-platform#128]
Unable to locate the Definition of Primary Environment vs Additional Environment.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c5c060a-c1f1-64d8-42fc-dba04c35ac29
* Version Independent ID: 7c4820ec-a83c-141b-dcd2-13fd7c45082b
* Content: [Multiple environments or tenants - Power Platform Admin center](https://docs.microsoft.com/en-gb/power-platform/admin/multiple-online-environments-tenants#feedback)
* Content Source: [power-platform/admin/multiple-online-environments-tenants.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/multiple-online-environments-tenants.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by sing-ideas** [comment]
Need documentation whether Primary environment can be changed.

**Comment by jimholtz** [comment]
@sing-ideas 
Thanks for the suggestion. We'll rewrite to add clarity.
