### ISSUE TITLE
Connector to Business Central

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/power-platform#1282]
Can I please confirm that this also related to Business Central?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd884343-7f2e-9765-4860-4cb4981a908e
* Version Independent ID: efe70284-6f99-698c-9406-802595535d97
* Content: [Integrate data into Microsoft Dataverse - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/data-integrator)
* Content Source: [power-platform/admin/data-integrator.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/data-integrator.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @makdaddy8888. This issue has been assigned to the doc author for review.

**Comment by makdaddy8888** [comment]
Can you please update the page with this information.

I thought business central was a dynamics product part of the power platform.

Kind Regards

**Comment by NHelgren** [comment]
While Business Central is part of Dynamics 365, Data Integration only specifically works between Dynamics CE and Dynamics Finance and Operations as stated in the opening paragraph.
