### ISSUE TITLE
Change wording from Data to Dataverse

### ISSUE THREAD

**Issue by Dlutchy** [MicrosoftDocs/power-platform#1284]
[Enter feedback here]
Under section **Set up the custom connector** in item number 1. change wording of Data > Custom Connectors to **Dataverse** > Custom Connectors

Also Item 5 please change Client secret to Client secret **Value**. The client secret has an ID and a Value so for clarity the instruction needs to be more specific.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Fixed locally ready for our next update. Thank you, looks like the Product UI has changed here to call this Dataverse now :)

**Comment by manuelap-msft** [comment]
Updated with latest release, thanks for the feedback!
