### ISSUE TITLE
GitHub link for issues needs updating. Refers to renamed project

### ISSUE THREAD

**Issue by aliyoussefi** [MicrosoftDocs/power-platform#1287]
[Enter feedback here]
The link to submit issues is broken. Please change to this:
https://github.com/microsoft/automation-coe-starter-kit/issues

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca7cc938-0b2d-7c1e-27d3-2681a3c7f058
* Version Independent ID: ca7cc938-0b2d-7c1e-27d3-2681a3c7f058
* Content: [Microsoft Power Platform Automation CoE starter kit (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/automation-coe/automation-coe-starter-kit)
* Content Source: [power-platform/guidance/automation-coe/automation-coe-starter-kit.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/automation-coe/automation-coe-starter-kit.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @kathyos
* Microsoft Alias: **kathyos**

**Comment by kathyos** [comment]
The aka.ms link has been updated and works correctly now.
