### ISSUE TITLE
ADD content on how to install the SAMPLE APPS

### ISSUE THREAD

**Issue by theresedevine** [MicrosoftDocs/power-platform#1288]
Please ADD content on how to install the SAMPLE APPS, this used to be one toggle button but now appears separate. Installing Sample Data did not install Sample Apps to do the Labs and Training.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987f5898-c9e4-40e7-9898-e27f6bc64922
* Version Independent ID: ebc7cbc9-2edb-b799-95a3-8b68c06a03ad
* Content: [Add or remove sample data - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/add-remove-sample-data)
* Content Source: [power-platform/admin/add-remove-sample-data.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/add-remove-sample-data.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @theresedevine. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@theresedevine 
You can get free trials of apps: 
https://dynamics.microsoft.com/en-us/dynamics-365-free-trial/
