### ISSUE TITLE
Does creating a new tenant means creating <Tenant2>.OnMicrosoftOnline.com?

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/power-platform#129]
Doc explains creating multi-tenant, can you clarify...

Does creating a new tenant means creating &lt;Tenant2&gt;.OnMicrosoftOnline.com?

Or provide a link that points to creating additional tenant relating Microsoft365, O365, Dynamics 365, Power Apps. 

Does creating additional tenant for Power Apps means creating additional Office365 tenant?
Can we make same O365 email for all the tenants?

Need clarification in the docs.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c5c060a-c1f1-64d8-42fc-dba04c35ac29
* Version Independent ID: 7c4820ec-a83c-141b-dcd2-13fd7c45082b
* Content: [Multiple environments or tenants - Power Platform Admin center](https://docs.microsoft.com/en-gb/power-platform/admin/multiple-online-environments-tenants#feedback)
* Content Source: [power-platform/admin/multiple-online-environments-tenants.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/multiple-online-environments-tenants.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@sing-ideas 
Thanks for the suggestions. We'll consider revising the document with requested information. We'll add some see also links to assist in the meantime.
