### ISSUE TITLE
More connectors to which the transport rule applies should be added.

### ISSUE THREAD

**Issue by hajimemutsuki** [MicrosoftDocs/power-platform#1290]
It is difficult to see from the title of the docs that only the "office 365 outlook" connector can control the transport rules from the power platform.
It is "Email exfiltration controls for connectors" and it seems to be for all MS connectors that can send email.
I would also like to see more connectors to which the trasport rule can be applied other than the "office 365 outlook" connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d16c2c-fbad-7ed0-ea2d-fd8faee42054
* Version Independent ID: 44d87949-1656-7360-e1e5-c8f45e029604
* Content: [Email exfiltration controls for connectors - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/block-forwarded-email-from-power-automate#feedback)
* Content Source: [power-platform/admin/block-forwarded-email-from-power-automate.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/block-forwarded-email-from-power-automate.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hajimemutsuki. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@hajimemutsuki 
Sorry for the delayed response. For product-related feedback, visit https://aka.ms/ppac-ideas
