### ISSUE TITLE
Small Typo in german version

### ISSUE THREAD

**Issue by PapaRiedel** [MicrosoftDocs/power-platform#1292]
Hi,

There is a typo in the matrix of the german version of the page:
You have written Microsot 365 instead of Microsoft 365.
The "f" is missing.

BR
Stefan

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1c1dd41e-5994-2eb5-f659-af836a1a3fc1
* Version Independent ID: f70008c9-ea14-96f1-8b29-d94bb510b680
* Content: [Verwenden der Serviceadministratorrollen zum Verwalten des Mandanten - Power Platform](https://docs.microsoft.com/de-de/power-platform/admin/use-service-admin-role-manage-tenant#service-administrator-permission-matrix)
* Content Source: [power-platform/admin/use-service-admin-role-manage-tenant.md](https://github.com/MicrosoftDocs/power-platform-pr.de-DE/blob/live/power-platform/admin/use-service-admin-role-manage-tenant.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PapaRiedel. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@PapaRiedel 
Thanks for bringing this to our attention. We'll get this fixed.
