### ISSUE TITLE
The content of a system backup for D365 CE

### ISSUE THREAD

**Issue by AncaRadu** [MicrosoftDocs/power-platform#1293]
[Having in mind that we cannot download (at least not directly) the backup to check the actual files, we need to point the partners/customers to this statement from the article:

"System backups occur continuously; this is different from previous versions where backups were once a day. Because the underlying technology used is Azure SQL Database, see [Automated backups] (https://docs.microsoft.com/en-us/azure/sql-database/sql-database-automated-backups) for details."]

Actually, one of my partners wants to know what type of data is backed up during this process, mentioned in this article:  https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments

Thank you,
AncaR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c58fb1-e6a2-5210-3774-4ea4bbff4572
* Version Independent ID: 57c1780c-b097-af8c-82fa-47e38a63995c
* Content: [Back up and restore environments - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments)
* Content Source: [power-platform/admin/backup-restore-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/backup-restore-environments.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AncaRadu. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@AncaRadu 
Sorry for the delayed response. Taking to internal thread.
