### ISSUE TITLE
Please document applicability to Dynamics 365

### ISSUE THREAD

**Issue by juha-ms** [MicrosoftDocs/power-platform#1295]
Please also document how the Customer Lockbox for Power Platform applies to different Dynamics 365 applications. Many of them store their data on Dataverse but it would be better if Dynamics 365 applications were explicitly mentioned as part of the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e8bdb9-1219-e935-0c23-5176bcf8c29b
* Version Independent ID: 36e8bdb9-1219-e935-0c23-5176bcf8c29b
* Content: [Securely access customer data using Customer Lockbox in Power Platform (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-lockbox)
* Content Source: [power-platform/admin/about-lockbox.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/about-lockbox.md)
* Service: **power-platform**
* GitHub Login: @mihaelablendea
* Microsoft Alias: **mihaelab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @juha-ms. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@juha-ms 
Sorry for the delayed response. Does the following note in the topic address your question?
 Note
Currently, the applications and services where lockbox policy is going to be enforced once enabled are Power Apps (including AI Builder, Power Apps portals), Power Automate, Dataverse, and Customer Insights.

If not, please reopen.
