### ISSUE TITLE
Update Gov Cloud Details

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1296]
We need to make some updates to the text below:

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-orphan-components#:~:text=The%20flows%20supporting%20this%20processes%20use%20the%20Microsoft%20Teams%20connector.%20Due%20to%20limitations%20of%20this%20connector%2C%20this%20process%20is%20currently%20not%20available%20in%20US%20Government%20(GCC%20High)%20and%20US%20Department%20of%20Defense%20(DoD).

The Teams connector is available in GCC High and DoD, so this statement is not accurate. What is not yet available in GCC, GCC High and DoD is the ability to post Adaptive Cards as a Flow Bot. Since these flows use Adaptive Cards posted by Flow Bots, we should make a statement that these Flows should be turned off in these regions as they will not work until that capability becomes available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b08b756-8274-5baa-21b0-301930f0aac6
* Version Independent ID: 0b08b756-8274-5baa-21b0-301930f0aac6
* Content: [Set up clean-up for orphaned objects - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-orphan-components)
* Content Source: [power-platform/guidance/coe/setup-orphan-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-orphan-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrwolfe. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
According to the connector documentation, the Microsoft Teams connector is not available in GCC High and DoD: https://docs.microsoft.com/en-us/connectors/teams/

![image](https://user-images.githubusercontent.com/55705669/173347151-0cc05a6a-3ee8-4d5a-a8af-f3b54ff662e4.png)

**Comment by manuelap-msft** [comment]
Changed the wording locally in our next release branch, will go live early July:

![image](https://user-images.githubusercontent.com/55705669/173347738-987414e6-2d0b-4ae9-8f17-9c23c767a375.png)

**Comment by rrwolfe** [comment]
Thanks for sharing. This is inaccurate as the Teams connector is available in both regions. I'll submit a request to update the docs sites.

Thanks!
Reed
________________________________

**Comment by manuelap-msft** [comment]
Updated with latest release, thanks for the feedback!
