### ISSUE TITLE
Cleanup for Orphaned Resources not supported in Gov Cloud

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1297]
We may want to add a note on the Cleanup for Orphaned Resources section stating that this solution area is not supported in GCC, GCC High and DoD due to lack of ability to post Adaptive Cards using Flow Bots.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#cleanup-for-orphaned-resources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3445b35a-114e-010d-a42b-3d738fa68c56
* Version Independent ID: 87fcef34-4b4a-cee9-f171-e1bd1e8ec970
* Content: [Governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#cleanup-for-orphaned-resources)
* Content Source: [power-platform/guidance/coe/governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/governance-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrwolfe. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Added note, ready for July release
![image](https://user-images.githubusercontent.com/55705669/173349804-a4012641-10ef-4fec-a13f-b00891eb8ad6.png)

**Comment by manuelap-msft** [comment]
Updated with latest release, thanks for the feedback!
