### ISSUE TITLE
Critical Update Needed: Microsoft Teams Governance area not supported in Gov Cloud

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1299]
We should add an Important section on lack of support for GCC, GCC High and DoD related to the Flows that facilitate the Microsoft Teams Governance solution area. These Flows will not run successfully in GCC, GCC High or DoD due to lack of ability to post Adaptive Cards using Flow Bots. If customers in these regions enable these flows, based on the default cleanup criteria, all Dataverse for Teams environments will be deleted within 7 days of installing the CoE Starter Kit governance solution since users will never receive the Adaptive Card with the request for business justification. It's critical that we document this so that customers in these regions do not accidentally have all D4T environments deleted as a result.

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-teams-components
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d744c67a-948f-63df-0e61-bb76809e534a
* Version Independent ID: d744c67a-948f-63df-0e61-bb76809e534a
* Content: [Set up Dataverse for Teams environment management - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-teams-components)
* Content Source: [power-platform/guidance/coe/setup-teams-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-teams-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrwolfe. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Added to the top - let me know if that's clear enough:

![image](https://user-images.githubusercontent.com/55705669/173349090-640a627f-7626-4903-a6f6-3783fdf62bbd.png)

Will go live with our July release.

**Comment by rrwolfe** [comment]
Looks great, thank you!
________________________________

**Comment by manuelap-msft** [comment]
Updated with latest release, thanks for the feedback!
