### ISSUE TITLE
MFA is not required to restrict IP address

### ISSUE THREAD

**Issue by toramaro2000** [MicrosoftDocs/power-platform#13]
If you just restrict IP address to Dynamics 365 Customer Engagement, MFA is not required but optional. 
Previously, MFA service settings had a rule to block IP addresses and this article seems to be based on that old settings, and just update partly but current setting should use Conditional Access. Once we configure a conditional access policy on Azure AD to block external access to Dynamics 365 CE, just block all access except trusted network location.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 003fe16c-7cf4-14c6-09f2-7b18b047cbf7
* Version Independent ID: 3c7059c0-3aff-2729-42a7-88c4e7de0157
* Content: [Restrict access with trusted IP rules - Power Platform Admin center](https://docs.microsoft.com/ja-jp/power-platform/admin/restrict-access-online-trusted-ip-rules#feedback)
* Content Source: [power-platform/admin/restrict-access-online-trusted-ip-rules.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/restrict-access-online-trusted-ip-rules.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@toramaro2000 
Thanks for the feedback. We've written the topic to address this and other issues.
