### ISSUE TITLE
Is Tenant Name space = <Tenant1NameSpace>.OnMicrosoftOnline.com?

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/power-platform#130]
Is Tenant Name space = &lt;Tenant1NameSpace&gt;.OnMicrosoftOnline.com? 

Clarify the wordings - "Each tenant must have its own namespace; UPN or SMTP namespaces cannot be shared across tenants."

Link : https://docs.microsoft.com/en-gb/power-platform/admin/multiple-online-environments-tenants#constraints-of-multi-tenants

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c5c060a-c1f1-64d8-42fc-dba04c35ac29
* Version Independent ID: 7c4820ec-a83c-141b-dcd2-13fd7c45082b
* Content: [Multiple environments or tenants - Power Platform Admin center](https://docs.microsoft.com/en-gb/power-platform/admin/multiple-online-environments-tenants#constraints-of-multi-tenants)
* Content Source: [power-platform/admin/multiple-online-environments-tenants.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/multiple-online-environments-tenants.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@sing-ideas 
We'll add see also and consider adding other information at a later date.
