### ISSUE TITLE
Pulse Feedback Maker Survey requires updates for Gov Cloud

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1301]
The Pulse Feedback Maker Survey solution area uses Flows that leverage Adaptive Cards posted by Flow Bots. This feature is not yet available in GCC, GCC High and DoD, so this part of the starter kit will not function correctly in these regions. We should update the text below to provide these details. Also, the Microsoft Teams connector is available in all Gov regions, so that text should be removed.

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#set-up-pulse-feedback-survey

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fc749-2ecd-61d7-4146-16fe1a373848
* Version Independent ID: fcd148f1-795e-a99c-e2e9-da06e1129d3c
* Content: [How to set up nurture components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components)
* Content Source: [power-platform/guidance/coe/setup-nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrwolfe. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Made changes ready for the next version:
![image](https://user-images.githubusercontent.com/55705669/173348000-2fd6f35e-577f-438f-ad5e-92d669197928.png)

**Comment by manuelap-msft** [comment]
Updated with latest release, thanks for the feedback!
