### ISSUE TITLE
PAC Paportal Download - File names

### ISSUE THREAD

**Issue by MarianZa** [MicrosoftDocs/power-platform#1303]
Hi,

there is an 8-digit hash added to the file names that are identified as duplicates. Would it be possible to reuse hashes already assigned to existing files from previous export?
For git changes it now seems like delete and recreate for all files without any modification.

Thank you. Best Regards.
Marian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0fc461-6778-1615-e9dd-f75433028f86
* Version Independent ID: df0fc461-6778-1615-e9dd-f75433028f86
* Content: [Microsoft Power Platform CLI paportal command - Power Platform](https://docs.microsoft.com/en-us/power-platform/developer/cli/reference/paportal-command)
* Content Source: [power-platform/developer/cli/reference/paportal-command.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/reference/paportal-command.md)
* Service: **power-platform**
* Sub-service: ****
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MarianZa. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@MarianZa 
This topic is part of the reference documentation for the PAC CLI, and so it only contains information about the commands and parameters for the PAC CLI. It isn't documentation about the power platform portal functionality.

I recommend you take a look at this topic: [Portals support for Microsoft Power Platform CLI](https://docs.microsoft.com/en-us/power-apps/maker/portals/power-apps-cli), which describes use of PAC CLI in the context of portals.

If you don't find what you need in those docs, please share your feedback there. The authors of that content have more subject matter expertise in portals.
