### ISSUE TITLE
Broken link to PowerApps Tools AdminInADay Lab

### ISSUE THREAD

**Issue by PlateSpinner** [MicrosoftDocs/power-platform#1305]
The AdmimInADay hyperlink in this line here is broken now.
https://github.com/MicrosoftDocs/power-platform/blob/05f6fa5aba95d91e79693eaa4c19057dfe5de77d/power-platform/admin/wp-task-automation-powershell.md?plain=1#L36

I think the target owner changed the structure a bit. My guess is that the link should now point to "https://github.com/microsoft/powerapps-tools/tree/master/Administration/AdminInADay"

**Comment by jimholtz** [comment]
@PlateSpinner 
Thanks for the feedback. We've corrected the link.
