### ISSUE TITLE
Link to Tenant isolation details link provided on this page is incorrect. PLease remove the link. 

### ISSUE THREAD

**Issue by AnupmaSharma** [MicrosoftDocs/power-platform#131]
Link to Tenant isolation details link provided on this page is incorrect. Please remove the link. I checked with APIhub team on any public documentation of their tenant isolation capability and nothing is available currently. We can refer to a internal document to add further details. I can provide the link offline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daeff591-4edf-8cc0-614a-47e59bec3825
* Version Independent ID: bad9dc45-d9f9-62c6-a7fd-7aa97fd8e3fd
* Content: [Restrict cross-tenant access - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/cross-tenant-restrictions)
* Content Source: [power-platform/admin/cross-tenant-restrictions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/cross-tenant-restrictions.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@AnupmaSharma 
Thanks for bringing this to my attention. Link removed.
