### ISSUE TITLE
Documentation section is an empty card

### ISSUE THREAD

**Issue by EllenWehrle** [MicrosoftDocs/power-platform#1311]
Documentation section is an empty card 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eadb9e2-bc3a-25e6-ec3d-e85e1f404405
* Version Independent ID: 5b70c7ac-bce9-36ec-09ce-c9291c1744e0
* Content: [Administer Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/admin-documentation)
* Content Source: [power-platform/admin/admin-documentation.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/admin-documentation.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @EllenWehrle. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@EllenWehrle 
Taking to internal thread.
