### ISSUE TITLE
Licensing picture is not correct

### ISSUE THREAD

**Issue by superfliege** [MicrosoftDocs/power-platform#1314]
https://github.com/MicrosoftDocs/power-platform/raw/main/power-platform/admin/media/power-automate-licensing/license-comparison.png

https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/power-automate-licensing/types.md

AI-Credits: 
Power Apps per app license 250 credits
Power Apps per user license 500 credits

**Comment by jimholtz** [comment]
@superfliege 
Thanks for bringing this to our attention. We'll get this reviewed and updated.
