### ISSUE TITLE
Links on the documentation page are not working

### ISSUE THREAD

**Issue by KodulkarNilesh** [MicrosoftDocs/power-platform#1317]
[Enter feedback here]

Links on the documentation page are not working
![image](https://user-images.githubusercontent.com/63402109/175307580-1190b889-0901-4d9e-92ef-4805c9cf6afe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95bfb99a-cdf3-2d32-7c9c-b6517e4716d5
* Version Independent ID: 95bfb99a-cdf3-2d32-7c9c-b6517e4716d5
* Content: [Configuration and data deployment in pipelines - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-config)
* Content Source: [power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-config.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-config.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @jenschristianschroder
* Microsoft Alias: **jeschro**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KodulkarNilesh. This issue has been assigned to the doc author for review.

**Comment by jenschristianschroder** [comment]
Hi @KodulkarNilesh,

Thank you for reporting this. We will fix these links as part of our next docs update.

In the meantime, you can find the referenced files here:
- deploymentSettings.json: https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceALMAccelerator/config/deploymentSettings.json
- customDeploymentSettings.json: https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceALMAccelerator/config/customDeploymentSettings.json
