### ISSUE TITLE
More detail needed for Input Parameters section

### ISSUE THREAD

**Issue by tombyang** [MicrosoftDocs/power-platform#132]
Could you please provide a little more detail/guidance on what people are entering for input parameters. For example, if I have a variable sent from PVA, where does that variable name go? What goes in the left and right boxes per row of inputs? It's not clear without having to manually test. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 010269b1-237d-eb71-7014-9d8ee8a29659
* Version Independent ID: b96cb487-cfc9-e60b-12e9-3c02efa06b99
* Content: [Automate Power Virtual Agents bot actions with flows - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-flow#feedback)
* Content Source: [power-virtual-agents/advanced-flow.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-flow.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Not sure if this is for an earlier version of the page - looking over it we have a pretty good example with the "today's forecast" scenario.
