### ISSUE TITLE
Given Team type does not exists

### ISSUE THREAD

**Issue by KodulkarNilesh** [MicrosoftDocs/power-platform#1321]
[Enter feedback here]
1. Given Team type does not exists. 
2. Documentation needs additional information e.g. Team Name and its purpose

![image](https://user-images.githubusercontent.com/63402109/175919271-e78affbd-4846-4acd-b7d7-eefea7826382.png)

![image](https://user-images.githubusercontent.com/63402109/175919366-d31367e0-3519-4e48-8a93-0ebe05ab866c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5190b0eb-7cda-9642-07aa-519f28a08c9d
* Version Independent ID: 5190b0eb-7cda-9642-07aa-519f28a08c9d
* Content: [Configuring the ALM Accelerator for Power Platform deployment user settings and profiles - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles)
* Content Source: [power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @jenschristianschroder
* Microsoft Alias: **jeschro**

**Comment by jenschristianschroder** [comment]
Hi @KodulkarNilesh,

Thank you for reporting this. We will fix this in our next docs update

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KodulkarNilesh. This issue has been assigned to the doc author for review.
