### ISSUE TITLE
Pre-populated Webhook url

### ISSUE THREAD

**Issue by KodulkarNilesh** [MicrosoftDocs/power-platform#1324]
Does the section becomes void from the documentation if webhook url is pre-populated in 'ALM Accelerator Admin Configuration' app?
Also no solution exists with name "Power Platform GitHub ALM"

![image](https://user-images.githubusercontent.com/63402109/176159091-e0fbde97-1b5e-4e6e-a313-56f92cbd8334.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d3a97-f062-9c7c-a5b6-8ec69178e1bc
* Version Independent ID: 476f4f57-b869-c759-74cc-beb4e2deaa26
* Content: [Set up ALM Accelerator for Makers components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator)
* Content Source: [power-platform/guidance/coe/setup-almaccelerator.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almaccelerator.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by jenschristianschroder** [comment]
This solution name will be corrected in next update of our docs
