### ISSUE TITLE
Entity Extraction doesn't work for sample

### ISSUE THREAD

**Issue by Katomasa0913** [MicrosoftDocs/power-platform#1325]
Following to your page, we made a sample chat bot.  But the entity extraction in that chat bot doesn't work.
Is this bug or do I need to change anywhere?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 598df6b5-6691-3a4c-8112-ec6aec43d175
* Version Independent ID: 0a34a661-5035-3946-c2e4-a7ce5e697832
* Content: [クイックスタート: Microsoft Teams でボットを作成して展開する - Power Virtual Agents](https://docs.microsoft.com/ja-jp/power-virtual-agents/teams/fundamentals-get-started-teams)
* Content Source: [power-virtual-agents/teams/fundamentals-get-started-teams.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-virtual-agents/teams/fundamentals-get-started-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Katomasa0913. This issue has been assigned to the doc author for review.

**Comment by v-alarioza** [comment]
Hi @Katomasa0913, are you referring to this section?

![image](https://user-images.githubusercontent.com/94562440/176963661-9eef4460-237b-4ca4-a2cd-cb3f27ca8abb.png)

If so, what is happening for you instead?

**Comment by Katomasa0913** [comment]
Thanks, forgive me too late to answer.

That's so.
When the user ask national holidays, the bot doesn't bypass the question. The bot show the selection of vacation type.

Our edition is Japanese.

Sincerely,

**Comment by Katomasa0913** [comment]
Thank you for your comment.

I think that the article in English is accurate, but when translating to Japanese, the search word is little bit changed.  So the entity extraction doesn't work for us.
So I changed the search word was shorter, the entity extraction worked.

This article was only machine translated, but not tested in Japanese.

Anyway, thanks a lot for my bad english.

Sincerely,

**Comment by v-alarioza** [comment]
@Katomasa0913 Ahh that makes sense. I'm going to reopen this issue so that I can bring it up to our localization team.

And your English is not bad at all 🙂

**Comment by vinceno** [comment]
Thx you very much @Katomasa0913 and @v-alarioza ..  I'm including @Dealgan12 who manages the translation of PVA documentation to follow thru and this this issue addressed.  Thanks once again for raise the issue !

**Comment by Dealgan12** [comment]
@Katomasa0913 @v-alarioza @vinceno I have send this onto our localization supplier to review and update. Will let you know when completed.

**Comment by v-alarioza** [comment]
@Dealgan12 Do you have any updates on this?

**Comment by Dealgan12** [comment]
@v-alarioza This is the response from our Japanese linguist

No fixing will be done based on the following reason. 

In this article, the source introduces how to build a chat bot but does not list the 2 search words in singular and plural forms "national holiday" and "national holiday". All the 9 occurrences of "national holidays" are all plural forms. And the linguist confirms that they are all translated consistently into "祝日"("holiday" in English). In ja-jp, there is no differences between singular and plural nouns, so the translation needs no fixing for this article according to the linguist.

The linguist suggests the following two different translation for the 2 search words to build the chat bot successfully. 
national holiday: 祝日 (単一)     back translation: national holiday (single) 

national holidays: 祝日 (複数)     back translation: national holiday (several)


Please tell us if any other fixings are needed.
