### ISSUE TITLE
Unable to track Power Apps / Flows contributing to Power Platform API limits

### ISSUE THREAD

**Issue by BhargavPrasadGorakanti** [MicrosoftDocs/power-platform#1326]
Hi, we've just started exploring the new reports for analytics and capacity consumption from power platform admin center. I'm looking for some help to better understand these reports and how to identify apps / flows that are contributing to high API requests. 

Firstly, I downloaded the "Power Platform Request Licensed User" report. It gives me the API requests count next to the entitlement limits for each user on a given day. Next, I downloaded the Power Apps Inventory and Flow Inventory reports from analytics section in power platform admin center. I can see several flows in the inventory but how do I identify which flows / apps to optimize or reduce run frequency or maybe even purchase a per flow license for? 

Is there a better way to figure this out? Any suggestions would be really helpful.

Thanks,
Bhargav

**Comment by jimholtz** [comment]
@BhargavPrasadGorakanti 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
