### ISSUE TITLE
colors of power apps

### ISSUE THREAD

**Issue by CiOuInfo** [MicrosoftDocs/power-platform#1327]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68355901-533e-7ecf-75f5-b49d97f3edf5
* Version Independent ID: 68355901-533e-7ecf-75f5-b49d97f3edf5
* Content: [Color enumeration and ColorFade, ColorValue, and RGBA functions in Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-colors)
* Content Source: [power-platform/power-fx/reference/function-colors.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-colors.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CiOuInfo. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@CiOuInfo Can you please provide more information about you issue with this topic: https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-colors 

Thank you,
Mints

**Comment by mduelae** [comment]
@CiOuInfo Since I haven't heard back, I'm closing this issue. Please feel free to open another issue if you see problems with the documentation.

Thanks,
Mints
