### ISSUE TITLE
PowerPlatform Build tools Update issues

### ISSUE THREAD

**Issue by satishkotaru** [MicrosoftDocs/power-platform#1329]
Hello,
We are facing some issues with power platform Import solution. In the import task after the import operation is completed it is publishing with in the task. which is causing the failures for the pipelines. I am attaching the  log files below.
![image](https://user-images.githubusercontent.com/43855722/176905824-27ce7314-b6f1-4129-a847-39a9fee6e73b.png)

**Comment by satishkotaru** [comment]
[Import error.txt](https://github.com/MicrosoftDocs/power-platform/files/9029266/Import.error.txt)

**Comment by phecke** [comment]
@satishkotaru We do not handle support issues here.

If you need assistance with the Microsoft Power Platform Build Tools, post a message to the [Power Apps component framework, ALM & Pro Dev](https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/bd-p/pa_component_framework) forum.
