### ISSUE TITLE
How to terminate a trial?

### ISSUE THREAD

**Issue by chuanqisun** [MicrosoftDocs/power-platform#133]
The documentation is missing on how we can terminate a trial. There a a few reasons we need to prematurely terminate a trial before the it naturally expires:

1. Need to purge the data and prepare a new trial (for field demo to customers)
2. Need to completely remove any data generated in the trial in case the customer wants to move on to a competitor product.

Also, the document doesn't explain what happens after a trial expires (even after extension). I wonder if I can provision new trials with the same tenant after its previous trial has expired.

Thanks!

**Comment by jimholtz** [comment]
@chuanqisun 
You can delete a trial in the Power Platform admin center.
https://docs.microsoft.com/en-us/power-platform/admin/delete-environment
