### ISSUE TITLE
Clarification is needed for "Paid Power Apps Portals login" request count (200 requests)

### ISSUE THREAD

**Issue by JulijaLudvigaELCA** [MicrosoftDocs/power-platform#1330]
Hi,

Could you please explain what exactly is meant by "Paid Power Apps Portals login" have 200 API Requests in 24h?
Does it mean each Power App Portal user (licensed as login) can do maximum 200 CRUD operations against Dataverse each day? If so, this limit is an extreemly low limit. What exactly will happen if it is exceeded? Is it counted for each user individually, or for all purchased monthly logins together? 
Or does it mean that each user can log in maximum 200 times each day?  
Or maybe it has some other meaning? 

Best regards,
Julija Ludviga

![2022-06-22 15_56_16-Requests limits and allocations - Power Platform _ Microsoft Docs and 14 more pa](https://user-images.githubusercontent.com/73485268/176928542-853a2c0b-2a3b-4f1f-bbaf-fcedbb34136f.jpg)

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @cpdSeattle
* Microsoft Alias: **camdebay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JulijaLudvigaELCA. This issue has been assigned to the doc author for review.

**Comment by cpdSeattle** [comment]
I can only comment on the entitlement logic.  Portals logins (authenticated users) are currently (July 2022) sold in packs of “100 login sessions.”  Each pack purchased would equal 100 logins * 200 Power Platform Requests = 20000 requests per day per month pooled at the “non-licensed user tenant-level limit.”  I am following-up with the Power Apps Portal Product Manager to confirm if the Docs should be updated to have the Portals limits documented under the “non-licensed user” limits section.

The usage scenario you’ve asked about would need to be tested and viewed through the Public Preview reports to see what is being counted.
