### ISSUE TITLE
Can we have a table with the Backup Retention rules for all environment types on this page?

### ISSUE THREAD

**Issue by MattB-msft** [MicrosoftDocs/power-platform#1331]
Would be supper helpful to have a 'simple' grid view of instance type to backup retention policy on this page. 

Currently one has to dig though several paragraphs of information regarding backup policies and there are notices of conditions scattered throughout the document. 

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c58fb1-e6a2-5210-3774-4ea4bbff4572
* Version Independent ID: 57c1780c-b097-af8c-82fa-47e38a63995c
* Content: [Back up and restore environments - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments)
* Content Source: [power-platform/admin/backup-restore-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/backup-restore-environments.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MattB-msft. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@MattB-msft 
Thanks for the suggestion. Taking to internal thread for action.
