### ISSUE TITLE
Example commands are outdated and do not align with current reference

### ISSUE THREAD

**Issue by khoanguyen-ms** [MicrosoftDocs/power-platform#1332]
[Enter feedback here]
In the [list of cmdlets](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#cmdlet-list---maker-cmdlets), the following commands do not align with [the reference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerapp?view=pa-ps-latest)

Incorrect:
Get-PowerApp (previously Get-App)
Remove-PowerApp (previously Remove-App)
Publish-PowerApp (previously Publish-App)
Set-PowerAppDisplayName (previously Set-AppDisplayName)
Get-PowerAppVersion (previously Get-AppVersion)

Correct:
Get-**Admin**PowerApp (previously Get-App)
Remove-**Admin**PowerApp (previously Remove-App)
Publish-**Admin**PowerApp (previously Publish-App)
Set-PowerAppDisplayName (previously Set-AppDisplayName) **is no longer available**
Get-PowerAppVersion (previously Get-AppVersion) **is no longer available**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#power-apps-cmdlets-for-app-creators)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by jimholtz** [comment]
@khoanguyen-ms 
Taking to internal thread.
