### ISSUE TITLE
New-AdminPowerAppCdsDatabase command is failing with error "Cannot bind argument to parameter 'InputObject' because it is null."

### ISSUE THREAD

**Issue by ancbhat** [MicrosoftDocs/power-platform#1333]
With the basic example command usage like:

New-AdminPowerAppCdsDatabase -EnvironmentName "$(EnvironmentGuid)" -CurrencyName "gbp" -LanguageName "1033" -Verbose

The execution is resulting in the following error : 
New-AdminPowerAppCdsDatabase : Cannot bind argument to parameter 'InputObject' because it is null.

Have tried variations to the command parameters (with quotes and without quotes, upper case/lower case) but result is the same.

Attaching the verbose log with this ticket.

[VerboseLog.txt](https://github.com/MicrosoftDocs/power-platform/files/9038983/VerboseLog.txt)

**Comment by jimholtz** [comment]
@ancbhat 
Sorry you're experiencing this issue. Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
