### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by sdieken** [MicrosoftDocs/power-platform#1336]
The hyperlink here does not go to intended page.  
https://docs.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types#transition-period:~:text=or%20flows.%20See-,Power%20Platform%20requests,-to%20understand%20both

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e5d831b-6683-e22f-f86e-1bb7475d067b
* Version Independent ID: 4e5d831b-6683-e22f-f86e-1bb7475d067b
* Content: [Types of Power Automate licenses - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types?source=docs#transition-period)
* Content Source: [power-platform/admin/power-automate-licensing/types.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/power-automate-licensing/types.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @PriyaKodukula
* Microsoft Alias: **prkoduku**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sdieken. This issue has been assigned to the doc author for review.

**Comment by RedsGT** [comment]
@sdieken Where is that URL being generated from? I don't see it in the referenced doc.

**Comment by jimholtz** [comment]
@sdieken 
Thanks for the heads up. Link fixed.
