### ISSUE TITLE
It says that you can accept files for upload in your PVA (Power Virtual Agent), but don't says how to use it, neither shows any example. It would be great!

### ISSUE THREAD

**Issue by MarkRobles** [MicrosoftDocs/power-platform#1337]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ad579e-a36d-2798-d94d-9a5e61a017c3
* Version Independent ID: 13a629a6-ac9d-37b7-f04a-598ba5905b50
* Content: [Configuration of advanced features - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-fundamentals)
* Content Source: [power-virtual-agents/configuration-fundamentals.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/configuration-fundamentals.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MarkRobles. This issue has been assigned to the doc author for review.

**Comment by v-alarioza** [comment]
Hi @MarkRobles, it appears this document is referencing features/documentation that has since been removed. Thank you for pointing this out - I'll get mentions of "file uploads" removed from this article.

**Comment by MarkRobles** [comment]
Thanks for the clarification!
