### ISSUE TITLE
Possibly incorrect service tag for IP address of dynamics environments 

### ISSUE THREAD

**Issue by valdik5379455** [MicrosoftDocs/power-platform#1338]
We were trying to find out IP addresses of our D365/Dataverse environments for network settings in local infrastructure. This page mentions that IP addresses are located in JSON file, under `AzureCloud` service tag. 

However, when we did `nslookup` for our environment domain names, IP addresses we've got were not under `AzureCloud` service tag. We found them under `PowerPlatformInfra` tag in JSON file. 

Is the `AzureCloud` a correct service tag to look for or is the correct service tag `PowerPlatformInfra`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215ab00d-9ad0-1e91-184c-218dd64a7d73
* Version Independent ID: 337562d4-dab0-ccf9-b272-5de16e88476a
* Content: [Power Platform URLs and IP address ranges - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/online-requirements)
* Content Source: [power-platform/admin/online-requirements.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/online-requirements.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @valdik5379455. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@valdik5379455 
All ip under PowerPlatformInfra will be still under AzureCloud. However it might not be the exact ip entry. For example, in PowerPlatformInfra, it will be 1.1.1.1, in AzureCloud, it will be 1.1.0.0/16.
