### ISSUE TITLE
Import Solution Build Task doesn't retrieve connection references from Deployment Settings file

### ISSUE THREAD

**Issue by GjorgeGogov47** [MicrosoftDocs/power-platform#1340]
Hi,

I'm building a CI/CD pipeline for a Power Platform solution and I'm having an issue with pre-populating the connection references.
The solution is unmanaged on the first environment and managed on the second environment. Environment variables are also included in the deployment settings file and their values are modified as expected during the pipeline deployment, while the connection references show an "Invalid Connection" error.

The LogicalName, ConnectionId, and ConnectorId values are all taken from already existing connection references on my second environment in my pre-existing "Connection Reference" table.

I've tried both simply importing the solution, and first importing it as a holding solution and then upgrading it with the "Apply Solution Upgrade" build task. Both approaches fail to get retrieve the connection references when importing the solution.

Is this a bug, or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1df5d8-ef79-c56d-3950-0617da9f976b
* Version Independent ID: ff132857-2fc9-57d0-df24-d42c054cbf1c
* Content: [Pre-populate connection references and environment variables for automated deployments using Power Platform Build Tools - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools?WT.mc_id=DT-MVP-5004113#feedback)
* Content Source: [power-platform/alm/conn-ref-env-variables-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/conn-ref-env-variables-build-tools.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GjorgeGogov47. This issue has been assigned to the doc author for review.

**Comment by kkanakas** [comment]
Hi @GjorgeGogov47 ,
                                    I would recommend that you open a support case and share the logs with us, so we can look at what is actually going on here.  Would please do that? Please do not post the logs of your org on the GitHub thread as it is public.

**Comment by GjorgeGogov47** [comment]
Thank you for your response.
A support ticket has been created for this issue.
