### ISSUE TITLE
Including documents doesn't work and shows the markdown

### ISSUE THREAD

**Issue by Jandev** [MicrosoftDocs/power-platform#1343]
[Enter feedback here]

There are several pages in the Power App documentation containing the following text:
```markdown
[!INCLUDE [record-scope]../../includes/record-scope.md)]
```
See this example:
![screenshot containing the raw markdown on a published page](https://user-images.githubusercontent.com/462356/177985385-b9977b05-1b9d-4519-a372-4e1e1ba4aab6.png)

I'd love to improve this but aren't familiar with this `include` feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b784f58-59eb-fb06-da8f-4747f6900db3
* Version Independent ID: 9b784f58-59eb-fb06-da8f-4747f6900db3
* Content: [Filter, Search, and LookUp functions in Power Apps (contains video) - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-filter-lookup#feedback)
* Content Source: [power-platform/power-fx/reference/function-filter-lookup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-filter-lookup.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Jandev. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your reaching out. Documentation has been fixed, please allow some time to reflect the changes.
