### ISSUE TITLE
Video Missing

### ISSUE THREAD

**Issue by kashanico** [MicrosoftDocs/power-platform#1345]
The Standard vs Managed video at the bottom is only a picture. 
![image](https://user-images.githubusercontent.com/64927104/178312463-dcc982f4-7f39-4f10-81ac-318862496b1a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8832c38-f621-879b-85a3-a0af993ddcd6
* Version Independent ID: f8832c38-f621-879b-85a3-a0af993ddcd6
* Content: [Managed Environments overview - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/managed-environment-overview)
* Content Source: [power-platform/admin/managed-environment-overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/managed-environment-overview.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @mikferland-msft
* Microsoft Alias: **miferlan**

**Comment by RedsGT** [comment]
@kashanico I think the arrow is supposed to be part of the diagram?  Not a play button?

**Comment by jimholtz** [comment]
@kashanico 
Thanks for the feedback. The image is an arrow and not a play button. If we get more feedback like this, we'll redo the arrow.
