### ISSUE TITLE
Syntax issues with examples...

### ISSUE THREAD

**Issue by gatep5** [MicrosoftDocs/power-platform#1346]
All of the examples are shown using double-quotes for the options of the Split method, but only single-quotes are accepted for the options.  Otherwise you get an "invalid syntax" error when using in Power Automate.    

For example Split("08/27/18", "/") should read as Split('08/27/18', '/').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed6bab97-51fe-39df-85e4-af074152baf6
* Version Independent ID: ed6bab97-51fe-39df-85e4-af074152baf6
* Content: [Split function in Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-split)
* Content Source: [power-platform/power-fx/reference/function-split.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-split.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli*
![Example](https://user-images.githubusercontent.com/109099736/178320847-6d49a913-61e3-45f7-a839-d90d36694b97.PNG)
*

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gatep5. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This is documented in Power Automate reference for using expressions, see [Split function reference](https://docs.microsoft.com/azure/logic-apps/workflow-definition-language-functions-reference#split). To navigate, go to [Cloud flows](https://docs.microsoft.com/power-automate/overview-cloud) > expand **How to** > select **Reference: Use functions in expressions** .
