### ISSUE TITLE
Delegation list link broken

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/power-platform#1347]
The link to the Delegation list is broken
The following URL produced a 404: 
https://docs.microsoft.com/en-us/power-platform/power-fx/maker/canvas-apps/delegation-overview.md#delegable-data-sources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b784f58-59eb-fb06-da8f-4747f6900db3
* Version Independent ID: 9b784f58-59eb-fb06-da8f-4747f6900db3
* Content: [Filter, Search, and LookUp functions in Power Apps (contains video) - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-filter-lookup)
* Content Source: [power-platform/power-fx/reference/function-filter-lookup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-filter-lookup.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by mduelae** [comment]
@jebalert Apologize for the delayed response. I checked the topic and all the links are working now. 

Thanks,
Mints
