### ISSUE TITLE
GCC Specific Endpoint Needed

### ISSUE THREAD

**Issue by rywilli** [MicrosoftDocs/power-platform#1348]
Can someone update this page to include a GCC specific endpoint for GCC customers? As it is written now, GCC customers will get an error. The issue is in the 'Deploy a custom canvas for your bot' section, in the code provided in step 2. The line below needs to be updated to be GCC specific when appropriate:

Commercial version: var theURL = "https://powerva.microsoft.com/api/botmanagement/v1/directline/directlinetoken?botId=" + BOT_ID;
GCC version: var theURL = "https://gcc.api.powerva.microsoft.us/api/botmanagement/v1/directline/directlinetoken?botId=" + BOT_ID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad35188-e674-e331-b2fc-eb3e6fb75560
* Version Independent ID: 31caa654-6112-bf08-f77b-ed2266a8bc24
* Content: [Automatically start a chatbot conversation - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configure-bot-greeting)
* Content Source: [power-virtual-agents/configure-bot-greeting.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/configure-bot-greeting.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
@rywilli Thanks for reporting this! The doc has been updated and is now published.
