### ISSUE TITLE
Note css is not working properly

### ISSUE THREAD

**Issue by Oodit** [MicrosoftDocs/power-platform#1349]
Dear team, 

On this page of sequence function, there is one note as below but looks like its css is not working as expected. 

[!NOTE] > Sequence is limited to 50,000 records.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1e7241-b0b0-08c7-31bb-ce1bdc25a03e
* Version Independent ID: 6b1e7241-b0b0-08c7-31bb-ce1bdc25a03e
* Content: [Sequence function in Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-sequence)
* Content Source: [power-platform/power-fx/reference/function-sequence.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-sequence.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Oodit. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been fixed and the changes will be reflected soon.
