### ISSUE TITLE
Is there a way to reallocate a capacity add-on?

### ISSUE THREAD

**Issue by TheArrayOfThings** [MicrosoftDocs/power-platform#135]
There is no information on reallocating capacity add-ons once consumed. 
Is this possible with capacity add-ons? For instance, if a user consumes an app pass erroneously, can we reclaim the app pass for another user?  
Many thanks,
Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0cbf8c-5c12-5aa2-3786-392d0f498303
* Version Independent ID: 2774f5ca-1c86-4fe6-c296-6f7f45aa6702
* Content: [Capacity add-ons for Power Apps and Power Automate - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on)
* Content Source: [power-platform/admin/capacity-add-on.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-add-on.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@TheArrayOfThings 
Please see: https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on#allocate-or-change-capacity-in-an-environment
