### ISSUE TITLE
Need ports and protocols

### ISSUE THREAD

**Issue by eccountable** [MicrosoftDocs/power-platform#1351]
Please add information about what ports and protocols are needed to connect to Exchange, because some implementations have strict security.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5033cf14-8912-471d-66b7-61ca7e29d752
* Version Independent ID: a7c05a79-cd65-1717-d4a4-0dde3c368263
* Content: [Connect to Exchange Server (on-premises) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-server-on-premises)
* Content Source: [power-platform/admin/connect-exchange-server-on-premises.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/connect-exchange-server-on-premises.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @eccountable. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@eccountable 
Thanks for the suggestion. We'll add the following to the article:
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deployment-ref/network-ports?view=exchserver-2019
