### ISSUE TITLE
Typo in formula

### ISSUE THREAD

**Issue by kamaleshbhamare** [MicrosoftDocs/power-platform#1353]
Patch( IceCream, Lookup( IceCream, Flavor = "Chocolate" ), { Quantity: 400 } )

In the above formula, 'Lookup' should be 'LookUp'. With uppercase 'U'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa25d2ca-ccc1-0e10-e065-731926bb673c
* Version Independent ID: fa25d2ca-ccc1-0e10-e065-731926bb673c
* Content: [Patch function in Power Apps (contains video) - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-patch)
* Content Source: [power-platform/power-fx/reference/function-patch.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-patch.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by mduelae** [comment]
@kamaleshbhamare Thank you for the feedback. The typo has been corrected.

Thank you,
Mints
