### ISSUE TITLE
Fix case in method call in Examples

### ISSUE THREAD

**Issue by andreylisovskiy** [MicrosoftDocs/power-platform#1354]
Please fix the function call name in your "Examples" on https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-patch

Copy pasting your function calls in this example fails, because it is not "Lookup" but "LookUp" in PowerApps!
![image](https://user-images.githubusercontent.com/21151899/179059229-39d18b59-5439-481f-aef3-b246adfc8ff7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa25d2ca-ccc1-0e10-e065-731926bb673c
* Version Independent ID: fa25d2ca-ccc1-0e10-e065-731926bb673c
* Content: [Patch function in Power Apps (contains video) - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-patch)
* Content Source: [power-platform/power-fx/reference/function-patch.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-patch.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @andreylisovskiy. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@andreylisovskiy We fixed the typo in our examples. Thank you for the feedback.

Thanks,
Mints
