### ISSUE TITLE
Dead links on a page

### ISSUE THREAD

**Issue by JaredRic** [MicrosoftDocs/power-platform#1355]
3 dead links from this sentence:

You can use Navigate to create or update [context variables](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/working-with-variables.md#use-a-context-variable) of the new screen. As an optional third argument, pass a [record](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/working-with-tables.md#records) that contains the context-variable name as a [column](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/working-with-tables.md#columns) name and the new value for the context variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b566f37-f394-2c64-b7eb-7649f1d59dcd
* Version Independent ID: 9b566f37-f394-2c64-b7eb-7649f1d59dcd
* Content: [Back and Navigate functions in Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-navigate?source=docs)
* Content Source: [power-platform/power-fx/reference/function-navigate.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-navigate.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JaredRic. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Links have been fixed and the changes will be reflected soon.
