### ISSUE TITLE
Translation mistake (zh-tw)

### ISSUE THREAD

**Issue by menghsinchen** [MicrosoftDocs/power-platform#1356]
「任何想要在一或多個環境中一直使用的連接器，都必須分類為 封鎖。」is wrong.
It should be「任何您完全不想要在一或多個環境中被使用到的連接器，都必須分類為 封鎖。」instead.

Original text: Any connectors that you want to keep from being used at all across one or more environments should be classified as Blocked. (https://docs.microsoft.com/en-us/power-platform/admin/dlp-connector-classification)

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: c7b19c11-5cc8-3608-01f7-f4729031f892
* Version Independent ID: dedd43cb-7f1a-ef3d-1c8c-f7f7e63d548f
* Content: [連接器分類 - Power Platform](https://docs.microsoft.com/zh-tw/power-platform/admin/dlp-connector-classification#list-of-connectors-that-cant-be-blocked)
* Content Source: [power-platform/admin/dlp-connector-classification.md](https://github.com/MicrosoftDocs/power-platform-pr.zh-TW/blob/live/power-platform/admin/dlp-connector-classification.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @mikferland-msft
* Microsoft Alias: **miferlan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @menghsinchen. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@menghsinchen 
Thanks for bringing this to our attention. Taking to internal email.
