### ISSUE TITLE
Need language and region support lists

### ISSUE THREAD

**Issue by tombyang** [MicrosoftDocs/power-platform#136]
Can we please add in what languages and regions PVA supports. Other products have this. Otherwise, customers don't know before they start

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d9a99e-c1d1-d2c6-3306-b9603ac5db77
* Version Independent ID: 799a66d3-bf5b-0309-794f-41396aabb619
* Content: [Power Virtual Agents overview - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/fundamentals-what-is-power-virtual-agents#feedback)
* Content Source: [power-virtual-agents/fundamentals-what-is-power-virtual-agents.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/fundamentals-what-is-power-virtual-agents.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
We have data locations listed, and are working to describe language and region support soon. https://docs.microsoft.com/en-us/power-virtual-agents/data-location
