### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by shammyowens** [MicrosoftDocs/power-platform#1360]
The [delegation list](https://docs.microsoft.com/en-us/power-platform/power-fx/maker/canvas-apps/delegation-overview.md#delegable-data-sources) and [delegation overview](https://docs.microsoft.com/en-us/power-platform/power-fx/maker/canvas-apps/delegation-overview.md) links are broken on this page.

I am guessing they should go to here

https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/delegation-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b784f58-59eb-fb06-da8f-4747f6900db3
* Version Independent ID: 9b784f58-59eb-fb06-da8f-4747f6900db3
* Content: [Filter, Search, and LookUp functions in Power Apps (contains video) - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-filter-lookup)
* Content Source: [power-platform/power-fx/reference/function-filter-lookup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-filter-lookup.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @shammyowens. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed and the changes will be visible soon.
