### ISSUE TITLE
specification_pwerBi

### ISSUE THREAD

**Issue by thayana2021js** [MicrosoftDocs/power-platform#1362]
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 85d9a99e-c1d1-d2c6-3306-b9603ac5db77
* Version Independent ID: 799a66d3-bf5b-0309-794f-41396aabb619
* Content: [Visão Geral - Power Virtual Agents](https://docs.microsoft.com/pt-br/power-virtual-agents/fundamentals-what-is-power-virtual-agents)
* Content Source: [power-virtual-agents/fundamentals-what-is-power-virtual-agents.md](https://github.com/MicrosoftDocs/power-platform-pr.pt-BR/blob/live/power-virtual-agents/fundamentals-what-is-power-virtual-agents.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @thayana2021js. This issue has been assigned to the doc author for review.

**Comment by v-alarioza** [comment]
Hi @thayana2021js, looks like you didn't add any details to this issue. Feel free to edit your first comment, or add a new one. If you opened this by accident, let me know and I'll close it.
