### ISSUE TITLE
Misleading licensing guidance

### ISSUE THREAD

**Issue by martin-dreyer-teck** [MicrosoftDocs/power-platform#1363]
The phrase "or the app needs to be assigned a Per App license" is misleading because it suggests one per-app license can be assigned to cover the app. In truth, per app licenses apply one-_per-user_.

I suggest this phrase be adjusted to "or the app needs to be assigned multiple Per App licenses".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @martin-dreyer-teck. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Thank you, I've made those changes locally and they will go live when we next update our docs!

**Comment by manuelap-msft** [comment]
We've made these updates now!
