### ISSUE TITLE
Wrong information on user-impersonation API permissions for application user

### ISSUE THREAD

**Issue by LuiseFreese** [MicrosoftDocs/power-platform#1369]
In 

[Configure service connections using a service principal](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools#configure-service-connections-using-a-service-principal) it is instructed to follow [Azure application registration](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/use-single-tenant-server-server-authentication#azure-application-registration), which advise to add **Dynamics CRM user_impersonation** API permissions to the app registration. 

This does not make any sense, as the app will not act on behalf on another user who would then need to consent to it. 

The application user gets an identity from the Azure AD app registration (AuthN) but will not need any permissions assigned (AuthZ). Privileges are handled exclusively by security roles.

This additional permission will not prevent the app from running, but the docs should be accurate, as many people  now wrongly think that they need user_impersonation.

I explained this here in more detail: [Why your Power Platform service principal doesn't need a Dynamics user_impersonation scope](https://www.m365princess.com/blogs/2022-07-25-why-your-service-principal-doesnt-need-a-dynamics-user_impersonation-scope/)

Happy to provide more feedback :-)

**Comment by rajyraman** [comment]
user_impersonation scope is only relevant if you are using Implicit grant.

![image](https://user-images.githubusercontent.com/5035266/180971615-f0e76568-1d60-4caf-8632-ec77485fb8cb.png)

Without adding the scope to the App Registration, you get this error.

![image](https://user-images.githubusercontent.com/5035266/180970335-193aea58-2515-4a65-980c-0c56dcd3919d.png)

Below is the sample code I used using MSAL

```csharp
var builder = PublicClientApplicationBuilder.Create("b744159c-a2eb-450d-96ca-244efeeb2b2d").WithAuthority("https://login.microsoftonline.com/57ffb2ab-2d19-4129-9a36-c17cf7c06bb4/").WithDefaultRedirectUri().Build();
var token = await builder.AcquireTokenInteractive(new string[] { "https://mydv.crm6.dynamics.com/.default"}).ExecuteAsync();
```
But, I haven't used implicit grant for a long time. I am only using App Registration + App User + Roles method. So, I guess the documentation should be updated to reflect that. I also only found this out last year from another MVP and I was quite surprised to find this out as well.

**Comment by phecke** [comment]
@LuiseFreese This documentation was fixed a few months ago. Under [Azure application registration](https://learn.microsoft.com/power-apps/developer/data-platform/use-single-tenant-server-server-authentication#azure-application-registration) step 7 it says:

_Note that Delegated permissions are not required for this server-to-server scenario._
