### ISSUE TITLE
Incorrect step details for new connection

### ISSUE THREAD

**Issue by VDMT** [MicrosoftDocs/power-platform#1370]
[Enter feedback here]
Step 2 below [create connections](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections) header references: Dataverse > Connections > + New connection.
But the URL from step 1: flow.microsoft.com does not have "Dataverse" as a link instead should say: 
Data > Connections > + New connection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VDMT. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Thanks for letting us know! Made the change locally now ready to be pushed live with our next update

**Comment by manuelap-msft** [comment]
This has been updated now!
