### ISSUE TITLE
missing Mandatory Environment variables during import

### ISSUE THREAD

**Issue by waiholiu** [MicrosoftDocs/power-platform#1371]
Mandatory Environment variables (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values) should include Power Automate Environment Variable.

If this is not set, then you can't turn on the below child flows in the next step.

CLEANUP HELPER - Check Deleted (Business Process Flows)
CLEANUP HELPER – Check Deleted (Canvas Apps)
CLEANUP HELPER – Check Deleted (Cloud Flows)
CLEANUP HELPER – Check Deleted (Custom Connectors)
CLEANUP HELPER – Check Deleted (Model Driven Apps)
CLEANUP HELPER – Check Deleted (PVA)
CLEANUP HELPER – Power Apps User Shared With

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @waiholiu. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Thanks for letting us know, we accidentally removed this when we we were moving stuff around in docs! I made the change locally now ready to be pushed live with our next update in a few days!

**Comment by manuelap-msft** [comment]
Updated now!
