### ISSUE TITLE
Data Export not available on PPAC version  1.2022.718.7

### ISSUE THREAD

**Issue by crowdedLeopard** [MicrosoftDocs/power-platform#1374]
Hello,

We cannot see the data export option in our version of the PPAC. Please advise on how we can enable this feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88890037-f7de-6084-f506-dc917adc0508
* Version Independent ID: 95103288-f976-3b83-d089-be6d315e563f
* Content: [Set up exporting to Application Insights - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/set-up-export-application-insights)
* Content Source: [power-platform/admin/set-up-export-application-insights.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/set-up-export-application-insights.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @crowdedLeopard. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@crowdedLeopard 
If your region shows availability:
https://docs.microsoft.com/en-us/power-platform/admin/set-up-export-application-insights#regional-availability
And you're still having this issue, please contact support: https://powerapps.microsoft.com/support/
