### ISSUE TITLE
Typo in paragraph Poortgebruik

### ISSUE THREAD

**Issue by JohnBontjer** [MicrosoftDocs/power-platform#1375]
Just a little typo in paragraph '[Poortgebruik](https://docs.microsoft.com/nl-nl/power-platform/admin/wp-onpremises-gateway#port-usage)'

typo: 
De uitgaande verbinding communiceert op de volgend epoorten

should be: 
De uitgaande verbinding communiceert op de volgende poorten

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c5127679-813b-594a-37f1-92ea81d6d41c
* Version Independent ID: 0aa9c171-4086-c462-8534-a5476f579401
* Content: [Info over on-premises gateways - Power Platform](https://docs.microsoft.com/nl-nl/power-platform/admin/wp-onpremises-gateway)
* Content Source: [power-platform/admin/wp-onpremises-gateway.md](https://github.com/MicrosoftDocs/power-platform-pr.nl-NL/blob/live/power-platform/admin/wp-onpremises-gateway.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JohnBontjer. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@JohnBontjer 
Thanks for the feedback. We'll get this corrected.

**Comment by Dealgan12** [comment]
Now updated - https://docs.microsoft.com/nl-nl/power-platform/admin/wp-onpremises-gateway
