### ISSUE TITLE
Legacy Portal no longer available

### ISSUE THREAD

**Issue by jimmyeao** [MicrosoftDocs/power-platform#1377]
[Enter feedback here]
https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-online#verify-that-you-have-the-profile-microsoft-exchange-online refers to the "Legacy Web Client" however this is not visible and no obvious way to switch to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d917db-1300-f212-067f-4ac688c18bec
* Version Independent ID: d19b118a-eddc-dc4f-75ad-2640f02aaeb4
* Content: [Connect to Exchange Online - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-online)
* Content Source: [power-platform/admin/connect-exchange-online.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/connect-exchange-online.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jimmyeao. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@jimmyeao 
For apps that have "Web" as the UI type, you'll see "Advanced Settings" when clicking the Settings gear.
This topic shows how to see the UI type.
https://docs.microsoft.com/en-us/power-apps/user/navigation#move-between-apps
