### ISSUE TITLE
Assign Power Apps per app baseline license

### ISSUE THREAD

**Issue by CarstenGrowth** [MicrosoftDocs/power-platform#138]
seems this part is being missed from above instructions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1f9ece-05b6-907c-9d52-5a19f5bf9872
* Version Independent ID: 9eaed30a-4c07-ef03-e3b4-d3db9989a760
* Content: [About Power Apps per app plans - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/about-powerapps-perapp#feedback)
* Content Source: [power-platform/admin/about-powerapps-perapp.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/about-powerapps-perapp.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
We will be updating the licensing documentation in the future to address.
