### ISSUE TITLE
Referencing old CRM 2015 Package Deployer Tool

### ISSUE THREAD

**Issue by joshua-soto-kitcher** [MicrosoftDocs/power-platform#1380]
The Documentation is making referencing and even links the old CRM 2015 Package Deployer tool:
https://marketplace.visualstudio.com/items?itemName=DynamicsCRMPG.MicrosoftDynamicsCRMSDKTemplates

Instead, it should be referencing the VS 2019 Power Platform Tools (and/or 2022 once that gets released):
https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatformTools

For reference, power platform package is one of the project templates, as described here:
https://docs.microsoft.com/en-gb/power-apps/developer/data-platform/tools/devtools-create-project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78dd2e38-9d0c-3bbf-0db3-138416d4063b
* Version Independent ID: 51455bd4-3294-0ccd-2b1b-6d9857c0f50f
* Content: [Package Deployer tool - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/package-deployer-tool)
* Content Source: [power-platform/alm/package-deployer-tool.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/package-deployer-tool.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @joshua-soto-kitcher. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@joshua-soto-kitcher  Yes, the documentation that specifies using VS 2015 is still applicable. However, I have added new information about using PAC CLI to creates packages.

See [Create packages for the Package Deployer tool](https://docs.microsoft.com/power-platform/alm/package-deployer-tool)

Also, I will look into using Power Platform Tools for creating packages. When I last looked at that tool, that specific functionality was not ready to document.

Thanks for pointing this out.
