### ISSUE TITLE
Update link to Application Insights environment from classic to new workspace based resource

### ISSUE THREAD

**Issue by jthomps19** [MicrosoftDocs/power-platform#1382]
The below line has a link to the "classic" Application Insights resource which will be deprecated.
Ensure that you have an **[Application Insights environment]**
(https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-new-resource)

Should be directed to the new workspace based link.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource

Thanks!

Jeff (jthomps@microsoft.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88890037-f7de-6084-f506-dc917adc0508
* Version Independent ID: 95103288-f976-3b83-d089-be6d315e563f
* Content: [Set up exporting to Application Insights - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/set-up-export-application-insights)
* Content Source: [power-platform/admin/set-up-export-application-insights.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/set-up-export-application-insights.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jthomps19. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@jthomps19 
Thanks for the suggestion. We updated the article.
