### ISSUE TITLE
What will happend with the channel associated with the Dataverse for Teams environment? 

### ISSUE THREAD

**Issue by FAC-1312** [MicrosoftDocs/power-platform#1383]
Documentation is not explicit about what could happen with teams channel if we do nothing to reactivate the Dataverse for Teams environment.

In case of deletion of this environment, the channel will continue to be available isn't?  

Thank you in advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027010ad-198c-2ae6-f96e-ac02ff02bf08
* Version Independent ID: 027010ad-198c-2ae6-f96e-ac02ff02bf08
* Content: [Automatic deletion of inactive Microsoft Dataverse for Teams environments (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/inactive-teams-environment)
* Content Source: [power-platform/admin/inactive-teams-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/inactive-teams-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @matapg007
* Microsoft Alias: **matgupta**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FAC-1312. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@FAC-1312 
We've recently updated this content. Please reopen this issue if your question wasn't resolved with the updates.
