### ISSUE TITLE
Starting point for instructions & email criteria

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/power-platform#1384]
As an infrequent Power Platform administrator, I would have found it helpful to be reminded how to get to the page where **Advanced Find** can be accessed: instructions along the lines of

1. From PPAC, access your **Environment URL**
2. Use the Settings cog (top right) to access **Advanced settings**
3. Within the **Business Management** page, use the Advanced filter funnel icon top right

Secondly, once I'd opened the **Advanced find** dialog, I'm attempting to follow **Method 3**, but the _Email messages_ **Look for** option doesn't include the _Attachments (item)_ as a criteria.  The closest I can see (_Attachments (item count)_) doesn't then allow me to add a subcriteria as per the screenshot.

![image](https://user-images.githubusercontent.com/83825222/182864484-b60ce55e-08ab-4848-a13b-cf641d4422c2.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9c9aae-ceaa-2e78-3752-2770327f49a7
* Version Independent ID: acd2ddc9-6225-92e8-2636-2a02437c3d82
* Content: [Free up storage space - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/free-storage-space)
* Content Source: [power-platform/admin/free-storage-space.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/free-storage-space.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrhkpmg. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@rrhkpmg 
Thanks for the feedback. We've revised the content to reflect the current UI. Attachments (item) appears further down in the list.
