### ISSUE TITLE
Package command not listed and errors out

### ISSUE THREAD

**Issue by craig-lund** [MicrosoftDocs/power-platform#1385]
Usage: pac package [init] [add-solution] [add-reference] [deploy] [show]

  init                        Initializes a directory with a new Dataverse package project
  add-solution                Adds a prebuilt Dataverse solution file to a PD Package project
  add-reference               Adds reference to Dataverse solution project
  deploy                      Deploys package to Dataverse environment
  show                        Shows details of Dataverse package

"add-solution                Adds a prebuilt Dataverse solution file to a PD Package project" is missing from the documentation. When I follow the help I get an error

> "Usage: pac package add-solution --path [--import-order] [--skip-validation] [--publish-workflows-activate-plugins] [--overwrite-unmanaged-customizations] [--import-mode] [--missing-dependency-behavior] [--dependency-overrides]
> 
>   --path                      Path to the Dataverse solution file (must be *.zip) (alias: -p)
>   --import-order              A whole number that indicates the order to insert this item into the final ImportConfig.xml file at build time. Negative numbers are inserted before existing elements. Positive numbers are added after existing elements.
>   --skip-validation           Adds the item to the project file even if the file does not exist or appears to be invalid. Note, this will not affect any validation that is performed by MSBuild. (alias: -sv)
>   --publish-workflows-activate-pluginsExplicitly indicates whether to publish the workflows and activate plugins when this solution is imported.
>                               Values: true, false
>   --overwrite-unmanaged-customizationsExplicitly indicates whether to overwrite unmanaged customizations when this solution is imported.
>                               Values: true, false
>   --import-mode               Explicitly specifies the required mode when importing this solution.
>                               Values: sync, async
>   --missing-dependency-behaviorSpecifies the behavior on import when a dependency of this solution is missing from the target environment.
>                               Values: skip, fault
>   --dependency-overrides      A semicolon delimited list of overrides. This value overrides any dependency information encoded in 

> the solution's metadata. Each override should be in the format: `<uniquename>:<minVersion>:<maxVersion>`. Where the 

> minVersion and maxVersion is optional but should be in .Net version format syntax." 

> 2022-08-05 14:52:08.7838|INFO|bolt.cli.Session|Product Version: 1.16.6+g21922f9; File Version: 1.16.6
> 2022-08-05 14:52:08.8098|INFO|bolt.cli.Session|Start new session. (sessionId: c187e7a4-fd26-4720-b47b-a8bf5309dc97; operationId: 5rZAfcT2Pak=; userId: b1ca933b-5b5c-477a-b0ca-857f9bee5d01)
> 2022-08-05 14:52:08.8874|INFO|bolt.cli.CommandProcessor|StartExecutingVerb (Verbs: ["package","add-solution"])
> 2022-08-05 14:52:08.8923|INFO|bolt.cli.Verb|Processing 'add-solution' verb arguments
> 2022-08-05 14:52:08.8923|INFO|bolt.cli.Verb|Executing 'add-solution' verb
> 2022-08-05 14:52:08.9044|INFO|bolt.module.package.PackageModule|Execute
> 2022-08-05 14:52:08.9044|INFO|bolt.cli.CommandProcessor|EndExecutingVerb (Success: False, Execution Time(ms): 22)
> 2022-08-05 14:52:08.9403|FATAL|bolt.cli.Session|Value cannot be null.
> Parameter name: inputUri
> 2022-08-05 14:52:08.9403|ERROR|bolt.cli.Session|   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
>    at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
>    at bolt.module.package.verbs.AddSolutionVerb.Execute(IContext context, Command command)
>    at bolt.cli.Verb.<>c__DisplayClass7_0.<<RunVerbExecutor>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at bolt.cli.Verb.RunVerbExecutor(IProcessCommandContext context, Command command)
>    at bolt.cli.Verb.Execute(IProcessCommandContext context, Command command, Queue`1 nextCommands)
>    at bolt.cli.CommandProcessor.ProcessCommands(Queue`1 commands, IVerbFactory factory)
>    at bolt.cli.CommandProcessor.LaunchCommand(IReadOnlyList`1 args, UserHelpText userHelpText, Boolean isNonInteractiveModeEnabled)
>    at bolt.cli.Session.Run(ProgramArguments args)
> 2022-08-05 14:52:09.0744|INFO|bolt.cli.Session|End session. (ResponseCode: 500)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d6013-5c83-4512-9a36-724ee67558d4
* Version Independent ID: 906d6013-5c83-4512-9a36-724ee67558d4
* Content: [Microsoft Power Platform CLI package command - Power Platform](https://docs.microsoft.com/en-us/power-platform/developer/cli/reference/package-command)
* Content Source: [power-platform/developer/cli/reference/package-command.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/reference/package-command.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @craig-lund. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@craig-lund

Thanks for reporting this. This is a known documentation issue. We are in the process of updating the PAC CLI reference documentation.  New content with the `add-solution` command is staged and we are waiting for final review before publishing.

FWIW: This is the content we have staged for this command, which is derived from the help content:

<hr />

## pac package add-solution

Adds a prebuilt Dataverse solution file to a PD Package project

### Required Parameters

#### `--path` `-p`

Path to the Dataverse solution file (must be *.zip)


### Optional Parameters

#### `--dependency-overrides`

A semicolon delimited list of overrides. This value overrides any dependency information encoded in the solution's metadata. Each override should be in the format: `<uniquename>:<minVersion>:<maxVersion>`. Where the minVersion and maxVersion is optional but should be in .Net version format syntax.

**Note**: Use a semicolon delimited list of dependency overrides of the format \<uniquename>:\<minVersion>:\<maxVersion>.

#### `--import-mode`

Explicitly specifies the required mode when importing this solution.

Use one of these values:

- `sync`
- `async`

#### `--import-order`

A whole number that indicates the order to insert this item into the final ImportConfig.xml file at build time. Negative numbers are inserted before existing elements. Positive numbers are added after existing elements.

#### `--layer-order-behavior`

This argument is applicable only for 1st party solutions.

Use one of these values:

- `above`
- `base`
- `below`

#### `--layer-order-solution-unique-names`

This argument is applicable only for 1st party solutions.

**Note**: Use a semicolon delimited list of solution uniquenames.

#### `--missing-dependency-behavior`

Specifies the behavior on import when a dependency of this solution is missing from the target environment.

Use one of these values:

- `skip`
- `fault`

#### `--overwrite-unmanaged-customizations`

Explicitly indicates whether to overwrite unmanaged customizations when this solution is imported.

Use one of these values:

- `true`
- `false`

#### `--publish-workflows-activate-plugins`

Explicitly indicates whether to publish the workflows and activate plugins when this solution is imported.

Use one of these values:

- `true`
- `false`

#### `--skip-validation` `-sv`

Adds the item to the project file even if the file does not exist or appears to be invalid. Note, this will not affect any validation that is performed by MSBuild.

This parameter requires no value. It is a switch.

<hr />

Unless this additional information helps, I suggest contacting technical support for the run-time issue you are experiencing.

I will share this information with the dev team, but we can't use documentation feedback issues to track product issues. So I'm closing this as a known documentation issue.

**Comment by joem-msft** [comment]
BTW, the reason for this error is that the command is not being called from a folder that contains a package project (*.csproj).
