### ISSUE TITLE
NFC Example causes errors. 

### ISSUE THREAD

**Issue by DoorKnob4531** [MicrosoftDocs/power-platform#1386]
Copying and pasting this example into a Power Apps project setup they proper way causes an error: "The function Coalesce has some invalid arguments".  

Thanks

Josh 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae46e7b-18ee-f3a0-0dfd-209e0d093ea5
* Version Independent ID: 6ae46e7b-18ee-f3a0-0dfd-209e0d093ea5
* Content: [ReadNFC function - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-readnfc#examples)
* Content Source: [power-platform/power-fx/reference/function-readnfc.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-readnfc.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @mikepenaMS
* Microsoft Alias: **mikepena**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please ensure the device is NFC capable. If issue persists, please reach out to support team through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with the investigation.
