### ISSUE TITLE
Teams Governance - GCC moderate now supports post of adaptive cards by bots

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1389]
Please update the "Important" section of the article, by removing "GCC" from the list of where posting adaptive cards via bot is not supported. This is now fully supported and the solution has been validated in a GCC tenant.

![image](https://user-images.githubusercontent.com/74214126/183422332-f5fa389e-518c-49cf-9398-a6473c751997.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d744c67a-948f-63df-0e61-bb76809e534a
* Version Independent ID: d744c67a-948f-63df-0e61-bb76809e534a
* Content: [Set up Dataverse for Teams environment management - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-teams-components)
* Content Source: [power-platform/guidance/coe/setup-teams-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-teams-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Wonderful, thanks for letting us know! Our next docs update is planned for early September, I'll make the changes for then!

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrwolfe. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Fixed locally and will go live with the September update!
