### ISSUE TITLE
Client Type property in Manage app properties

### ISSUE THREAD

**Issue by AbdulWahabWarind** [MicrosoftDocs/power-platform#139]
I can not find it in the mentioned link: https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/manage-app-properties. Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69fb152a-db7d-14c8-d20b-59646a5e7215
* Version Independent ID: 3bd6e336-5899-7e42-fc49-150288aa1348
* Content: [Update your apps to Unified Interface - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/update-apps-to-unified-interface)
* Content Source: [power-platform/admin/update-apps-to-unified-interface.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/update-apps-to-unified-interface.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@AbdulWahabWarind 
There's a note in this topic:
https://docs.microsoft.com/powerapps/maker/model-driven-apps/manage-app-properties

Note:
1The Client and App URL Suffix properties are no longer available when you create a new app.
