### ISSUE TITLE
Governance Components - GCC moderate now supports posting of adaptive cards by bots

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1391]
Please update the "Note" sections of the article, by removing "GCC" from the list of where posting adaptive cards via bot is not supported. This is now fully supported and the solution has been validated in a GCC tenant.

https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#microsoft-teams-governance
https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#cleanup-for-orphaned-resources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3445b35a-114e-010d-a42b-3d738fa68c56
* Version Independent ID: 87fcef34-4b4a-cee9-f171-e1bd1e8ec970
* Content: [Governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#microsoft-teams-governance)
* Content Source: [power-platform/guidance/coe/governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/governance-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrwolfe. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Fixed locally and will go live with the September update!
