### ISSUE TITLE
Pulse Survey - GCC moderate now supports posting of adaptive cards by bots

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1392]
Please update the "Note" section of the article, by removing "GCC" from the list of where posting adaptive cards via bot is not supported. This is now fully supported and the solution has been validated in a GCC tenant.

https://docs.microsoft.com/en-us/power-platform/guidance/coe/nurture-components#pulse-survey-components

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52f603f-2e0d-b02b-4a51-de16511e79dd
* Version Independent ID: 5b0aa787-c4a4-423b-9504-80fa375a04ba
* Content: [Nurture components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/nurture-components#pulse-survey-components)
* Content Source: [power-platform/guidance/coe/nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrwolfe. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Fixed locally and will go live with the September update!
