### ISSUE TITLE
New Languages supported

### ISSUE THREAD

**Issue by pavecer** [MicrosoftDocs/power-platform#1395]
It seems like we are not updating docs with new languages that are currently available in PVA

<img width="213" alt="image" src="https://user-images.githubusercontent.com/37548236/184097667-f2a92f63-6eb5-4539-804c-b96b9535bf9c.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c0f147-9e5c-a437-0873-7be9ce4809b6
* Version Independent ID: 95fa1262-ca57-e6fc-0de5-c4628fda0c16
* Content: [Language support - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/authoring-language-support)
* Content Source: [power-virtual-agents/authoring-language-support.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/authoring-language-support.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pavecer. This issue has been assigned to the doc author for review.

**Comment by v-alarioza** [comment]
@pavecer Thank you for your report, an update to this article has now been published.
