### ISSUE TITLE
Pay-as-you-go is now available in Norway

### ISSUE THREAD

**Issue by pettersh** [MicrosoftDocs/power-platform#1396]
Pay-as-you-go is now available in Norway. Please update FAQ
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6030a2f5-a21a-dc04-577a-ac81009c9ac4
* Version Independent ID: 6030a2f5-a21a-dc04-577a-ac81009c9ac4
* Content: [Issues and FAQs about pay-as-you-go plans - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/pay-as-you-go-issues-faq)
* Content Source: [power-platform/admin/pay-as-you-go-issues-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/pay-as-you-go-issues-faq.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Kavishi
* Microsoft Alias: **kaagar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pettersh. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@pettersh 
Thanks for the feedback. We're researching this and will make updates upon completion.
