### ISSUE TITLE
Print() Function for Microsoft PowerApps

### ISSUE THREAD

**Issue by hpkeong** [MicrosoftDocs/power-platform#1397]
HI

It works PERFECTLY when opening Power Apps from browser.
But for Win 10/11 Power Apps apps, it worked ONCE and then never worked.
Can you pls re-activate for this brilliant function?

TQ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49abb88-5ea7-9ef4-9a21-c0185e7768ca
* Version Independent ID: b49abb88-5ea7-9ef4-9a21-c0185e7768ca
* Content: [Print function in Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-print)
* Content Source: [power-platform/power-fx/reference/function-print.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-print.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hpkeong. This issue has been assigned to the doc author for review.

**Comment by hpkeong** [comment]
Hi BG Appreciate prompt feedback. In fact, in the Win 10/11 Apps, FEEDBACK pop-up, I had written the comments several times but look like the function is NOT working. So, if feedback function is included within the APPS, please kindly to have SOMEONE assigned to reply (such as in this GitHub), otherwise it is useless.[easy to make function but not easy to convince users what the function for] Currently, I have no choice but to ask client to use Desktop Apps to print. A positive feedbackFrom Win 10/11 Apps, you can nowUse LAUNCH to navigate from apps to apps seamlessly using PARAM(unluckily your PARAM documentation is poor. If OK, I can rewrite certain portion)PDF viewer can now view easily within the apps.For example, I launch pdf file which resides inside Google Drive and it shows up within second, smooth and nice. It doesn’t work on Desktop Apps.So I would say that Win 10/11 Power Apps are becoming better, exceptNew version update is SOMETIMES Fast and sometimes take days to update unless you sign out and sign in again. Thanks for support. NB:I am using everyday in average 5 hours for making MRP II for my client. Share with you the first page for fun  PK HongPrincipal Consultant www.sqipro.com From: Bishal GoswamiSent: 12 August 2022 11:00 AMTo: MicrosoftDocs/power-platformCc: hpkeong; MentionSubject: Re: [MicrosoftDocs/power-platform] Print() Function for Microsoft PowerApps (Issue #1397) Thanks for your comment, @hpkeong. This issue has been assigned to the doc author for review.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please create a [support service request](https://docs.microsoft.com/power-platform/admin/get-help-support) for further help and investigation of this problem.

**Comment by hpkeong** [comment]
Print() having latest issue of NOT print or fit to paper size.
Before May 2023, you can just choose Print to Portrait and it will fit to the desired H/W setting for A4 size, but now It is not. It becomes smaller and fit to Top / Left something like Letter size.
All previous Print() setting was corrupted and customers were pretty upset with such sudden change.
I suspect Team as added choices for Tablet / Mobile choice Canvas and most of us, as developer, feel like Team is making bugs and create "Redundant" improvement and then spoilt existing good product.

Pls help
