### ISSUE TITLE
Wrong screenshot for Enter the Skill manifest URL to add a Skill to your bot step 2

### ISSUE THREAD

**Issue by sereilly** [MicrosoftDocs/power-platform#140]
It should be highlighting the + Add skill button

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3987009c-4054-5e8e-8fdc-2e1291ded8f6
* Version Independent ID: 43ab4768-00c0-6fca-4fde-951406022248
* Content: [Extend your bot using Bot Framework Skills - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-add-skills)
* Content Source: [power-virtual-agents/configuration-add-skills.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/configuration-add-skills.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for identifying this, I've fixed this and it should go live in an update later tonight.
