### ISSUE TITLE
Get M365 Service Messages flow missing details for Azure Gov regions

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1400]
The documentation for manual updates concerning the [Get M365 Service Messages flow for a GCC High or DoD tenant](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#modify-the-command-center-app--get-m365-service-messages-flow-for-a-gcc-high-or-dod-tenant) doesn't include all the necessary updates needed to make this work in an Azure Gov tenant. See the highlighted changes that are needed for this action below.

![image](https://user-images.githubusercontent.com/74214126/184538665-f18fe4a7-8d27-436a-9ce7-85cf1b0660d7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrwolfe. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Fixed locally and will go live with the September update!
