### ISSUE TITLE
Assigning AAD Group teams as owners in model apps

### ISSUE THREAD

**Issue by brazierp** [MicrosoftDocs/power-platform#1401]
[Enter feedback here]
When manually assigning AAD group teams as owners using the built in form, the default options list does not pick up AAD group teams. It is possible to edit filter on the 'Default lookup view' of the Teams table so that it includes AAD groups but this was not immediately obvious to me. Can we add a note on this page to help others with this?
Regards,
Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc48e173-18f4-85d8-5938-91be592204cd
* Version Independent ID: be1f1a63-c300-b120-0d1a-6c22ebc76e7a
* Content: [Manage group teams - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-group-teams)
* Content Source: [power-platform/admin/manage-group-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/manage-group-teams.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @brazierp. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@brazierp 
Thanks for the suggestion. We've added a section in the topic to cover this.
