### ISSUE TITLE
Text describing how Search work is not Clear

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/power-platform#1402]
It is unclear in the description that Office 365 Documents are not able to be searched from within Dataverse or Model Driven apps. That the only Office documents are stored within the Attached notes section of Dataverse. this is an important distinction to make

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f4b53c-095c-4bf9-46dd-62299f2568e5
* Version Independent ID: 92a06c7b-d9b6-1a85-fb46-8378273a5994
* Content: [Configure Dataverse search to improve search results and performance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/configure-relevance-search-organization)
* Content Source: [power-platform/admin/configure-relevance-search-organization.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/configure-relevance-search-organization.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @devman2k. This issue has been assigned to the doc author for review.
