### ISSUE TITLE
Option convert change to Upgrade

### ISSUE THREAD

**Issue by lucianomontenegro** [MicrosoftDocs/power-platform#1407]
The "convert to production" option no longer exists in the interface, the procedure must be updated, I only find the "Upgrade" option.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e35d3f3b-0007-bbb7-fe0b-000e76932281
* Version Independent ID: d937d8d8-232d-ce0e-ae88-38d95e501793
* Content: [Alterar o tipo de ambiente - Power Platform](https://docs.microsoft.com/pt-br/power-platform/admin/switch-environment)
* Content Source: [power-platform/admin/switch-environment.md](https://github.com/MicrosoftDocs/power-platform-pr.pt-BR/blob/live/power-platform/admin/switch-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@lucianomontenegro 
I reviewed the interface and confirmed "Convert to production" and "Convert to sandbox" are in there. 

Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
