### ISSUE TITLE
Links in article doesnt work

### ISSUE THREAD

**Issue by donsvensen** [MicrosoftDocs/power-platform#1409]
The links in this paragraph doesn't work.

![image](https://user-images.githubusercontent.com/19202547/185884629-f9ce905f-bc04-4bc9-a51d-9e453cfa8958.png)

BR Erik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83b2196-8c32-86db-3c76-5464a62ae70f
* Version Independent ID: b83b2196-8c32-86db-3c76-5464a62ae70f
* Content: [AddColumns, DropColumns, RenameColumns, and ShowColumns functions in Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-table-shaping)
* Content Source: [power-platform/power-fx/reference/function-table-shaping.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-table-shaping.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @donsvensen. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been fixed and will reflect the changes soon.
