### ISSUE TITLE
Error in Description section

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/power-platform#1411]
The Description section reads:

Description
The ForAll function evaluates a formula for all the records in a table. The formula can calculate a value and/or perform actions, such as modifying data or working with a connection. Use the [With function](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-with) to evaluate the formula for a single record.

Use the [Sequence function](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-sequence) with the ForAll function to iterate based on a count.

[!INCLUDE [record-scope]../../includes/record-scope.md)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2ac30ff-c2c0-02b8-c502-4daaf0e15b00
* Version Independent ID: e2ac30ff-c2c0-02b8-c502-4daaf0e15b00
* Content: [ForAll function in Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-forall)
* Content Source: [power-platform/power-fx/reference/function-forall.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-forall.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @biterbit. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been fixed and will reflect the changes soon.
