### ISSUE TITLE
request timing when the new IP addresses were added and how we could have been notified

### ISSUE THREAD

**Issue by MarzelLaning42** [MicrosoftDocs/power-platform#1414]
Hi
We had an issue with connectivity between DES and an Azure resource caused by the fact that the static IP was changed from old to new as indicated in this document.

When was this changed and how would we have been notified of this pending change of IP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#azure-sql-database-static-ip-addresses-used-by-the-data-export-service)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MarzelLaning42. This issue has been assigned to the doc author for review.

**Comment by JasonHQX** [comment]
Hello @MarzelLaning42 The communication message has been sent to all active DES customer under the specific region (US: 5/16/2022 - MC383476; EU: 7/21/2022 - MC403599) using Email and Message center channel

**Comment by MarzelLaning42** [comment]
Hi @JasonHQX ,
Thank you for your comment. We cannot find the item in our EU message center. Please inform us which service it should mention and at which time it was sent. Searching the number you mention (403599) did not return anything.

**Comment by JasonHQX** [comment]
Can you share your orgID?

**Comment by MarzelLaning42** [comment]
> **[JasonHQX](/JasonHQX) ** commented [4 days ago](#issuecomment-1227597456)

84887cb0-1dc9-422b-86c1-93bd063a9e8c

**Comment by jimholtz** [comment]
@MarzelLaning42 
We believe the communication was sent. Please have the admin check the configuration of the message center to make sure such items are retained. If things check out at your end, please contact Support. https://powerapps.microsoft.com/support/
