### ISSUE TITLE
Hi... i have trouble with dropdown cause i need used it wiht more options than 255, have somebody any solution for this?  cheers 

### ISSUE THREAD

**Issue by BernardoTobon** [MicrosoftDocs/power-platform#1415]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: cc9345a5-e5f0-da01-be2c-5c187f9ca858
* Version Independent ID: cc9345a5-e5f0-da01-be2c-5c187f9ca858
* Content: [Función Choices en Power Apps - Power Platform](https://docs.microsoft.com/es-es/power-platform/power-fx/reference/function-choices)
* Content Source: [power-platform/power-fx/reference/function-choices.md](https://github.com/MicrosoftDocs/power-platform-pr.es-ES/blob/live/power-platform/power-fx/reference/function-choices.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BernardoTobon. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/

Closing this issue.
