### ISSUE TITLE
Update user permissions required to configure Office 365 Management API custom connector and connection

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#1417]
The following statement should be changed or removed. User configuring Office 365 Management API connection and custom connector does not have to have direct access to audit log as AAD app with ActivityFeed.Read permission provides necessary access to be able to configure everything. Global Admin is required to be able to create AAD app but Power Platform or D365 admin role is enough to configure connection and custom connector 

_You must have access to the audit log. The Microsoft Power Platform Service Admin role doesn't give you access to the audit log._

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#before-you-use-the-audit-log-connector

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Fixed locally ready for the September update.
