### ISSUE TITLE
System Backups for sandbox orgs

### ISSUE THREAD

**Issue by jthomps19** [MicrosoftDocs/power-platform#142]
It is not clear under the system backups section how long sandbox backups are available.  I believe it is 7 days.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c58fb1-e6a2-5210-3774-4ea4bbff4572
* Version Independent ID: 57c1780c-b097-af8c-82fa-47e38a63995c
* Content: [Back up and restore environments - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments#feedback)
* Content Source: [power-platform/admin/backup-restore-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/backup-restore-environments.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jthomps19 
I confirmed with product group that system backup of sandbox is retained for 7 days. We will add this to the documentation.
