### ISSUE TITLE
Typo / spelling mistake in screenshot

### ISSUE THREAD

**Issue by chumleesockson** [MicrosoftDocs/power-platform#1421]
https://docs.microsoft.com/en-us/power-platform/admin/media/block-cookie-replay-user-message.png

The above referenced screenshot states "Contact your administrator for mode information." - I believe this should be "more information" and there should be a space between the initial C and the full stop preceding it.

I haven't tested the feature yet, so I'm not sure if it has been fixed at the code level already.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd8269a0-99ff-e180-61a3-b17eedc47c93
* Version Independent ID: fd8269a0-99ff-e180-61a3-b17eedc47c93
* Content: [Block cookie replay attacks in Dataverse (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/block-cookie-replay-attack)
* Content Source: [power-platform/admin/block-cookie-replay-attack.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/block-cookie-replay-attack.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @ritesp
* Microsoft Alias: **ritesp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @chumleesockson. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@chumleesockson 
Thanks for the feedback. This has been corrected.
