### ISSUE TITLE
Is required https://api.powerplatform.com for Power Platform API?

### ISSUE THREAD

**Issue by TakiyaNakano-MSFT** [MicrosoftDocs/power-platform#1428]
[Enter feedback here]
Only "https://*.api.powerplatform.com" is in URLs for Dynamics 365 services table. 
But https://docs.microsoft.com/en-us/rest/api/power-platform/#call-a-rest-api-method article introduce  https://api.powerplatform.com as Rest API endpoint.

please update the table with https://api.powerplatform.com URL if it is required for Power Platform API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215ab00d-9ad0-1e91-184c-218dd64a7d73
* Version Independent ID: 337562d4-dab0-ccf9-b272-5de16e88476a
* Content: [Power Platform URLs and IP address ranges - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/online-requirements#urls-for-dynamics-365-services)
* Content Source: [power-platform/admin/online-requirements.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/online-requirements.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TakiyaNakano-MSFT. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
Taking to internal thread.
