### ISSUE TITLE
CreaterKitReferenceMDA hyperlink not working in Creater Kit Documentation

### ISSUE THREAD

**Issue by kbilakanti** [MicrosoftDocs/power-platform#1429]
Hi Team,

As part of Creater Kit documentation - I saw that hyperlink for Custom pages: "aka.ms/CreaterKitReferenceMDA" is not working. image below.
![image](https://user-images.githubusercontent.com/51436645/188072443-5293379a-e2a4-4c40-a99c-1fd692d0228e.png)

**Comment by denisem-msft** [comment]
This has been fixed.
