### ISSUE TITLE
Pay as you go option missing in article

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/power-platform#1431]
Hello,
There is a new option to enable Azure Pay a you Go, the article is not yet updated and could you please explain why one would use this option.

![image](https://user-images.githubusercontent.com/40460576/188127902-09cf5271-83e1-4234-96bd-1a5424c2678f.png)

![image](https://user-images.githubusercontent.com/40460576/188127744-cafa4a2a-6fe9-4a66-bc2a-f86240eccae8.png)

Thank you

Pierre-Olivier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-environment)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @popujol. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@popujol 
1GB is required even for environments created without a database. We don’t want to prevent customers from creating a database after they have created an environment (due to lack of capacity at a later time).

**Comment by popujol** [comment]
This doesn't seem related to my question 🤔

**Comment by jimholtz** [comment]
@popujol 
Sorry, response was for another issue. We're working on updating the documentation for your suggestion.

**Comment by jimholtz** [comment]
@popujol 
We've added text and updated the screenshots. Thanks again for the heads up.

**Comment by popujol** [comment]
Glad it was heard, thank you for the good work on the doc!
