### ISSUE TITLE
Flow details swapped

### ISSUE THREAD

**Issue by PPMini** [MicrosoftDocs/power-platform#1432]
Hi Team, 

Observed the following swap of definitions on the flow descriptions:

![FlowsFeedback](https://user-images.githubusercontent.com/112712553/188175960-1fa5bb49-7ed1-4399-8723-ff1178942237.PNG)

---
The description of the flows Admin| Sync Template v3(PVA) and the  Admin | Sync Template v3 (Solutions) is swapped 

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#admin---command-center)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for spotting that, updated locally and will go live with our next docs updated targeted for mid-next week!
