### ISSUE TITLE
Does Org ID or Org Name acts as a container for multi-tenant deployment

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/power-platform#1433]
Does Org ID or Org Name acts as a global container for a multi-tenant implementation, like example, FordMotorsGlobal.com as an Org, has multi-tenant business in USA, Europe, Asia, etc.

It is clearly understood that 1 tenant can have many environments, does 1 org have many tenants.

1 Org > many tenants > many environments to each tenant. Is this correct?

I read that org and tenants are the same, if so, how is multi-tenants are managed/contained.

regards,
Singaravelu S

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c5c060a-c1f1-64d8-42fc-dba04c35ac29
* Version Independent ID: 7c4820ec-a83c-141b-dcd2-13fd7c45082b
* Content: [Considerations for choosing multiple environments or tenants - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/multiple-online-environments-tenants)
* Content Source: [power-platform/admin/multiple-online-environments-tenants.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/multiple-online-environments-tenants.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sing-ideas. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@sing-ideas 
Organization is a term for tenant that Office 365 uses. We've been changing our documentation and UI to use tenant. Some legacy use of organization still exists in UI and documentation.  Organization in our documentation should refer to a company or business. A company can have multiple tenants. A tenant can have multiple environments. Org ID, in the context of a Power Platform environment, refers to the Dataverse instance ID in that environment. Hope this helps.

**Comment by sing-ideas** [comment]
Hi,
Thanks, for the roadmap on how you are planning to use the terminologies going forward.

Org > Tenant > Environment > Solutions > Apps.

Similar to Common Data Model, you guys need to build Common Document Terminology Model or Common Taxonomy.

All the best!

.
Singaravelu S,
Founder, Stack Radius

________________________________
