### ISSUE TITLE
Page Link not correct

### ISSUE THREAD

**Issue by girishuppal** [MicrosoftDocs/power-platform#1435]
In the hyperlink - the letter c is missing. Hence the link is invalid.

Please correct

![image](https://user-images.githubusercontent.com/17232756/188249297-134fcb8a-2a31-443d-902c-a7e58bc4bdb9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74154c-ce00-1e30-0806-9d9a1d5923ea
* Version Independent ID: 6b74154c-ce00-1e30-0806-9d9a1d5923ea
* Content: [Creator Kit - overview (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/overview)
* Content Source: [power-platform/guidance/creator-kit/overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/creator-kit/overview.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @girishuppal. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Link has been fixed, and the changes will be reflected soon.
