### ISSUE TITLE
Copy Paste Error from Microsoft team

### ISSUE THREAD

**Issue by girishuppal** [MicrosoftDocs/power-platform#1436]
In this page, there is a link to "Power Platform Adoption document"

![image](https://user-images.githubusercontent.com/17232756/188249569-9c22c100-ccbf-400b-b11d-25ad642515aa.png)

In one of the case study, the document talks about a customer named as "ARM"
However, the content if you see carefully talks about "H&M" company.
"H&M" company case study is part of previous slide. Hence the author might have copy pasted the content and forgot to edit the text. Hope it gets corrected before it reaches a wider audience.

![image](https://user-images.githubusercontent.com/17232756/188249488-b95b2bf4-3853-4dee-8bb4-9d0c52de80a5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f369f96-96f2-c9ca-8186-1e8b3bc102af
* Version Independent ID: c14b7fe5-48dd-348e-2d91-8df751614e3f
* Content: [Microsoft Power Platform adoption best practices - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/adoption/methodology)
* Content Source: [power-platform/guidance/adoption/methodology.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/adoption/methodology.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @girishuppal. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Hello,

can you help me understand where the incorrect screenshot is coming from? Is it from the Adoption workbook?

**Comment by girishuppal** [comment]
Hello,

Navigate to this link below

https://adoption.microsoft.com/en-us/powerplatform/

 and then click on "Centre of Excellence Planner"

![image](https://user-images.githubusercontent.com/17232756/188766301-4515a963-495e-42f9-8d8a-f2a7424626ac.png)



This is the direct link to view the document:


https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fdownload.microsoft.com%2Fdownload%2Fe%2F7%2F8%2Fe78e1e83-870f-4181-898f-f1304cfd8d91%2FPower%2520Platform%2520Center%2520of%2520Excellence%2520Customer%2520Flipbook.pptx&wdOrigin=BROWSELINK

**Comment by manuelap-msft** [comment]
Thank you, I've let the owner of this doc know so they can get that fixed!

**Comment by manuelap-msft** [comment]
Closing out as this is not hosted on docs.
