### ISSUE TITLE
Probably shouldn't exit to another document without warning user

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/power-platform#144]
In Adopt &gt; Innovate &gt;Best Practices &gt; Engage via apps &gt; Intelligent Experiences &gt; Modern web apps &gt; Referencing solutions for web apps   -  you don't remain in the Cloud Adoption Framework but go outside to a different document without warning.  The user also loses their place in the Cloud Adoption Framework unless they use the Back in their Browser.  I suggest creating a new page that then links to the different document.  Please remember to put a Feedback section on that new page also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea178b4-f20a-747b-9e84-8b09ab6218d4
* Version Independent ID: e97f75e7-469e-0dc1-319c-0fe0a84c4e2e
* Content: [Data loss prevention policies - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention?toc=https://docs.microsoft.com/azure/cloud-adoption-framework/toc.json&bc=https://docs.microsoft.com/azure/cloud-adoption-framework/_bread/toc.json)
* Content Source: [power-platform/admin/wp-data-loss-prevention.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/wp-data-loss-prevention.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@homeworryfree 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
