### ISSUE TITLE
Extra step required for "Install the creator kit solution" Step 1

### ISSUE THREAD

**Issue by PrimeDime1** [MicrosoftDocs/power-platform#1440]
[Enter feedback here]
When downloading the CreatorKitCore from https://aka.ms/creatorkitdownload, the download happens as a folder with contents and not a zip or compressed file.

New users will need to know that the contents of the folder need to be compressed into a zip file so that step for on page https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/setup under ["Step 1](https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/setup#step-1---install-the-creator-kit-solution) can be carried out.

Thanks,
Rui 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a869972-ce34-c5c9-c591-fd25347181c1
* Version Independent ID: 9a869972-ce34-c5c9-c591-fd25347181c1
* Content: [Set up the Creator Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/setup)
* Content Source: [power-platform/guidance/creator-kit/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/creator-kit/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PrimeDime1. This issue has been assigned to the doc author for review.

**Comment by swapp1012** [comment]
Hi,
It is throwing me error "power apps Solution "Creator Kit" failed to import: Import Solution Failed: Object reference not set to an instance of an object."

can u please guide

**Comment by denisem-msft** [comment]
This should be fixed (both issues reported) and download zip is in a state that allows direct import. Please reopen if you're still having issues.
