### ISSUE TITLE
references to PSA obsolete

### ISSUE THREAD

**Issue by standswell** [MicrosoftDocs/power-platform#1441]
[Enter feedback here]
another reference to PSA, rather than PO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998c5ac7-53b7-548a-4f73-7f8d586abffb
* Version Independent ID: 6ea1d35d-3459-34f9-aa01-e113dc7cb0c6
* Content: [Use the Microsoft 365 admin center to manage your subscription - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/use-office-365-admin-center-manage-subscription)
* Content Source: [power-platform/admin/use-office-365-admin-center-manage-subscription.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/use-office-365-admin-center-manage-subscription.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @standswell. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@standswell 
Thanks for the update. This affects many topics and we'll make this terminology change at a later time.
