### ISSUE TITLE
The prerequisites are not precise

### ISSUE THREAD

**Issue by fumi11** [MicrosoftDocs/power-platform#1442]
The pages describe the prerequisites. But it is not precise.

![image](https://user-images.githubusercontent.com/102130723/188339569-224778da-9b3a-4350-82ee-3c2f438b8ccd.png)

You do not need Power Platform Service admin, Dynamics 365 admin, or Microsoft 365 Global admin but system administrator.
Could you kindly update the descriptions of the prerequisites?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88890037-f7de-6084-f506-dc917adc0508
* Version Independent ID: 95103288-f976-3b83-d089-be6d315e563f
* Content: [Set up exporting to Application Insights - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/set-up-export-application-insights#feedback)
* Content Source: [power-platform/admin/set-up-export-application-insights.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/set-up-export-application-insights.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @fumi11. This issue has been assigned to the doc author for review.
