### ISSUE TITLE
Following this tutorial does not produce a working result

### ISSUE THREAD

**Issue by drmanhatin** [MicrosoftDocs/power-platform#1443]
Following this tutorial does not produce a working result, and debugging is close to impossible because of the error message: 

![image](https://user-images.githubusercontent.com/25794862/188468927-b227d242-8434-401b-840d-61ac7601ce14.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d60dd9-05e9-9c78-7d7b-53b26a92af06
* Version Independent ID: 282e50ba-61cf-6574-94ad-4dcf82b71a72
* Content: [Configure single sign-on - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configure-sso)
* Content Source: [power-virtual-agents/configure-sso.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/configure-sso.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @drmanhatin. This issue has been assigned to the doc author for review.
