### ISSUE TITLE
solution clone support?

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/power-platform#1445]
Hi

any chance that the Power Platform tools will support
```pac solution clone``` in the near future?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks#feedback)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tool-tasks.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ibruynin. This issue has been assigned to the doc author for review.

**Comment by davidjenni** [comment]
@ibruynin, my team, the engineering team that owns the PP-BT tasks, has no plan to add solution clone as task to the Power Platform Build Tools AzDevOps tasks.

The `pac solution clone` is intended for inner-dev loop only to populate an initial source tree from a solution, which then can be built via msbuild/dotnet build.

@bishalgoswami please transfer this issue to our product's issue tracker: 
https://github.com/microsoft/powerplatform-build-tools/issues

cc: @kkanakas

**Comment by KumarVivek** [comment]
@ibruynin Closing the issue based on response from David Jenni. If you have further feedback, please share here: https://github.com/microsoft/powerplatform-build-tools/issues.
