### ISSUE TITLE
Using deployment settings file for connection references

### ISSUE THREAD

**Issue by cT-m00cat** [MicrosoftDocs/power-platform#1447]
Reading  the official documentation at https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools#get-the-connection-reference-information it says one needs to obtain the connection reference information.. this defeats the entire purpose of automating the deployment. The connection references are part of the solution and don't exist until that first deployment. The document suggest that one has to prepopulate the id's of something that doesn't exist yet? 

Am I missing something vital here? 

Further to this.. one doesn't seem able to employ the use of the deployment settings file when using the Deploy Package task as opposed to simply Import Solution. 

Thank you for your time and effort. Would appreciate some guidance on the above questions.

**Comment by kkanakas** [comment]
@cT-m00cat    No, you need to create the connections in the target environment. Right now, you do not have the ability to create connections via the CI/CD process as connections are not stored in Dataverse. I understand and appreciate your frustration but that is reflective of the situation now.  As the situation changes, which will be later this year. We will update the documentation appropriately 
@phecke  - FYI

**Comment by cT-m00cat** [comment]
Hey there
Thanks for the response. What I do now.. Is manually create the connections in the target environment and then populate environment variable values where needed. I don't bother importing the settings file with the task.. then I use a bit of powershell to process the json and insert values into the environmentvariabledefinition and/or environmentvariablevalue entities as needed (i use a bit of logic.. if a current or default value exists already)... then for the empty connectionreferences 

Then i process the connectionreferences block and use Get-PowerAppConnection to get connectors in the environment and match FullConnectorName  to ConnectorId in the settings file... the ID i need is here - and this get;s popped right into the connectionreference entity (i look up the correct row from the logicalname.

I also skip empty env variable values as the task fails if you import a settings file with empty env vars. Quite often we deploy something and some of these env vars are deliberately left empty at the start... 

The ability to create connectors (outside of custom connectors) using a command line tool would be AMAZING. Like.. that would be a total game changer. 

I hope some of the above is useful in helping you assess how the tools are being used and what some of us are doing to get around what we see as limitations as they stand at the moment. 
Thanks

**Comment by cT-m00cat** [comment]
@kkanakas while I have your attention.. can I ask you about canvasapps, datasources and environment variables? It has never really worked how I would like and it seems, from what I have observed, the canvasapp can only access environment variables that exist in the same solution.. when I deploy a solution containing a canvasapp to a new environment - where all the datasources are environment variables.. changing the value, in my understanding, is done in the default solution.. which then places the value out of reach of the canvasapp. It only seems to work when the canvasapp is in an unmanaged solution? Is this correct? 

I have played about extracting the msapp from a solution - pre deployment.. and then automating the switching out of datasources in the those source files.. repackaging and deploying. this is an awful lot  of work though.. and I have found the files for the datasources/connectors that I have looked at when unpackaging a canvasapp (dataverse and sharepoint) are very different in structure - which makes it a bit more difficult for me to "standardize" a process around it.. 

Thanks for any input.

**Comment by kkanakas** [comment]
@cT-m00cat,  if a canvas app contains environment variables, and you need to change those in the target environment (as in the environment where the solution is being imported in to) then you can use the same deployment settings files that you can generate from pac solution create-settings. This will work for both managed and unmanaged solutions. 
<img width="812" alt="image" src="https://github.com/MicrosoftDocs/power-platform/assets/22942069/164c273c-1e11-4e07-b1fc-31ad9deb486f">
or you can do this 
<img width="785" alt="image" src="https://github.com/MicrosoftDocs/power-platform/assets/22942069/c3bc2c2b-462c-4105-8fa9-e7a0e92b2d55">
edit the settings file
<img width="777" alt="image" src="https://github.com/MicrosoftDocs/power-platform/assets/22942069/57e91f9a-42cb-4225-bea1-bdda49aac269">

and then run solution import with the settings 

<img width="887" alt="image" src="https://github.com/MicrosoftDocs/power-platform/assets/22942069/95d75885-49ae-4da0-bf2b-ccbaad7313ad">

**Comment by cT-m00cat** [comment]
thanks i already do this.. i realised my question was unclear and removed it... 

thanks anyway.. I have found another solution for what i need to do.
thanks a lot for your time. i really appreciate it
