### ISSUE TITLE
Note about sharing to users is wrong

### ISSUE THREAD

**Issue by Sirgoodman1234** [MicrosoftDocs/power-platform#1448]
In the article the Note states you cannot share Bots with users, only security groups. Just tested it, I can share to users and users will get the email.

This is a test question on PL-200 EXAM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459a93d6-f7cd-affc-078e-57d5bf504c6b
* Version Independent ID: 50c66cdc-41df-f930-df87-9426e57c4e9f
* Content: [Share and collaborate on chatbots with other users (contains video) - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/admin-share-bots)
* Content Source: [power-virtual-agents/admin-share-bots.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/admin-share-bots.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Sirgoodman1234. This issue has been assigned to the doc author for review.
