### ISSUE TITLE
Capacity Storage

### ISSUE THREAD

**Issue by RipVanIT** [MicrosoftDocs/power-platform#145]
"To free up storage capacity, delete outdated data."
Uh oh, base environment is all that is installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3017e0-867f-29eb-07b8-93e8a80e90d2
* Version Independent ID: 69fbf20e-6d59-3965-cce7-c8f45af0e593
* Content: [View self-service storage capacity - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/view-self-service-capacity)
* Content Source: [power-platform/admin/view-self-service-capacity.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/view-self-service-capacity.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@RipVanIT 
This topic might provide some suggestions:
https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/admin/free-storage-space
