### ISSUE TITLE
Update Power Automate URL

### ISSUE THREAD

**Issue by mscloud-pro** [MicrosoftDocs/power-platform#1454]
Should the environment variable for Power Automate be updated to https://make.powerautomate.com/environments/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components?source=recommendations)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mscloud-pro. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Thank you! Made the change locally, ready for our next docs update later this week.

**Comment by manuelap-msft** [comment]
Fixed yesterday with our latest docs update!
