### ISSUE TITLE
Mail merge template option is not available in Power Platform

### ISSUE THREAD

**Issue by CGrevlos** [MicrosoftDocs/power-platform#1455]
Going to Power Platform admin center, Settings > Templates does not provide an option for mail merge templates. No such item exists. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0a4189-13aa-26fb-e2d9-76fa745da9c1
* Version Independent ID: 0a658845-bbed-539f-23c1-dae24def7f84
* Content: [Work with mail merge templates - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/work-mail-merge-templates)
* Content Source: [power-platform/admin/work-mail-merge-templates.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/work-mail-merge-templates.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CGrevlos. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@CGrevlos 
Please see the note at the top of the topic:
The mail merge template feature has been deprecated and is not supported. In Dynamics CRM 2016 (version 8.0), we introduced server-side document generation using Word and Excel templates. You can use these templates to provide standardized documents or customized data analysis for your organization.

**Comment by CGrevlos** [comment]
I did see that note, I guess I was hoping there'd be a link somewhere in that note indicating the steps to take to use the server side document generation. As of right now, reading that leads me to a dead end as I don't understand how to proceed with mail merge.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
