### ISSUE TITLE
Requirements CoE Starter Kit

### ISSUE THREAD

**Issue by lukas-nC** [MicrosoftDocs/power-platform#1458]
Hi,

in the requirements, there is listed with licences are needed to install the Starter Kit.
Because of a current case, I would like to know which specific apps have to be enabled to install and use the starter kit, because some companies only activate certain apps.

Best redards
Lukas
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Einrichten des CoE Starter Kit - Power Platform](https://docs.microsoft.com/de-de/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform-pr.de-DE/blob/live/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lukas-nC. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Hello,

as your question is about the functionality of the CoE starter kit, and not the documentation, can you please raise a question here https://github.com/microsoft/coe-starter-kit/issues/new/choose for the development team of the CoE kit to take a look at. This repo is only used for documentation issues.

Thank you
Manuela
