### ISSUE TITLE
restore 

### ISSUE THREAD

**Issue by anapereiCRMSE** [MicrosoftDocs/power-platform#146]
Can we add the info that Source and destination environments must be in the same region.
this is already inside copy operation however would be great having the same info for restore operations has is not allowed. 

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c58fb1-e6a2-5210-3774-4ea4bbff4572
* Version Independent ID: 57c1780c-b097-af8c-82fa-47e38a63995c
* Content: [Back up and restore environments - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments#feedback)
* Content Source: [power-platform/admin/backup-restore-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/backup-restore-environments.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@anapereiCRMSE 
Thanks for the suggestion. Content updated.
