### ISSUE TITLE
properties mentioned for the Container to be used in the panel needs configuration updates.

### ISSUE THREAD

**Issue by dipteshbose** [MicrosoftDocs/power-platform#1461]
Seems like the X, Y, Width and Height settings of the container to use as an overlay to the panel is incorrect. Its not snapping right over the panel based on the configurations recommended.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1346323-c9a3-5c4e-d4d2-32080de5b27f
* Version Independent ID: f1346323-c9a3-5c4e-d4d2-32080de5b27f
* Content: [Panel control reference (experimental) - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/panel)
* Content Source: [power-platform/guidance/creator-kit/panel.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/creator-kit/panel.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dipteshbose. This issue has been assigned to the doc author for review.

**Comment by dipteshbose** [comment]
Bookmark to the section I am referring to: 
https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/panel#format-panel-content

**Comment by denisem-msft** [comment]
This has been fixed and will be published soon.
