### ISSUE TITLE
[PVA] Can not find bot item when build proactive flow in power automation

### ISSUE THREAD

**Issue by jiaqi3** [MicrosoftDocs/power-platform#1469]
I have published my bot, but there is no item in this flow
![image](https://user-images.githubusercontent.com/70375028/191193433-d377aea6-e66f-4665-9e32-2eab89c1f50d.png)
I don't kown why, could you please give me some advice?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c64db467-2159-e6ab-a4c9-15544eb78660
* Version Independent ID: c64db467-2159-e6ab-a4c9-15544eb78660
* Content: [Notify bot users in Teams with proactive messages - Power Virtual Agents](https://learn.microsoft.com/en-us/power-virtual-agents/advanced-proactive-message)
* Content Source: [power-virtual-agents/advanced-proactive-message.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/advanced-proactive-message.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jiaqi3. This issue has been assigned to the doc author for review.

**Comment by v-alarioza** [comment]
@jiaqi3 Have you also [added your bot to Teams](https://learn.microsoft.com/power-virtual-agents/publication-add-bot-to-microsoft-teams)? 

If that doesn't help, the best place for product requests or troubleshooting is [the Power Virtual Agents forum](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums). If you repost your questions there an engineer, project manager, or someone with a similar issue/solution should be able to help you.
