### ISSUE TITLE
Guest users in O365

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/power-platform#147]
Can guest users in O365 use embedded canvas apps without any specific O365 liceneses?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Licensing overview - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus#power-apps-and-power-automate-standalone-plans)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@eschrader 
The license requirements for an embedded app is the same as a ‘standalone’ app as called out in the table in this doc:
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#what-license-must-be-assigned-to-my-guest-so-they-can-run-an-app-shared-with-them
