### ISSUE TITLE
Adaptive Cards in MS Teams | The request failed. Error code: '400'. Error Message: 'Post as PVA is missing request recipient'.

### ISSUE THREAD

**Issue by JhinalRajput** [MicrosoftDocs/power-platform#1470]
Hello All,

We have been working on PVA and Deployed it in MS Teams. The "Post Adaptive card and wait for response" was working fine earlier.
Recently, we experienced some abnormality in getting Adaptive Card in Teams Chat. 

In the backend Power Automate Flow, It showed  **The request failed. Error code: '400'. Error Message: 'Post as PVA is missing request recipient'.** 

![image](https://user-images.githubusercontent.com/100519298/191266309-59a6a861-519f-4bdc-aaae-540087ce28dd.png)

**Comment by v-alarioza** [comment]
Hi @JhinalRajput, this was caused by a bug in the connector, but has been resolved.
