### ISSUE TITLE
Reuse Audit Log app registration when installing a new version of the COE

### ISSUE THREAD

**Issue by russgove** [MicrosoftDocs/power-platform#1471]
Hi,
I am trying to install the latest version of the COE in a separate , newly created , environment.
I have it running in an old environment with the Audit logs feature enabled. I created an app registration for thies way back when and it working

I am trying to reuse the App registration that I used with the old environment in my new environment. When I get to the step in the docs where it says Start a new Subscription I enter the tenant and Publisher and click 'Test Operation'  and I get this response:
{
  "error": {
    "code": "AF20024",
    "message": "The subscription is already enabled. No property change."
  }

Can I use  the same App registration in two environments running the COE? If not how do I delete the old subsription.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @russgove. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Hello this is an expected and documented error when you already have the subscription enabled, see
![image](https://user-images.githubusercontent.com/55705669/191790311-d6f1f43a-caf4-46cb-a60e-d3c6211e1dbe.png)

You can use the same app registration in multiple environments, yes.
