### ISSUE TITLE
Postal code is synced between Dataverse and Azure AD, Fax is not

### ISSUE THREAD

**Issue by khoanguyen-ms** [MicrosoftDocs/power-platform#1472]
[Enter feedback here]
In "User profile information" section, Fax number is included in the list of Azure AD sync targets, and postal code is not.
However, as of Sep 2022, postal code is synced between Dataverse and Azure AD, and Fax is not.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1b508b-e71a-b577-51cf-f21c76c58035
* Version Independent ID: 8725a7a3-7b54-3402-c94c-c9e9dee577be
* Content: [Create users - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/create-users#update-a-user-record-to-reflect-changes-in-azure-ad)
* Content Source: [power-platform/admin/create-users.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-users.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@khoanguyen-ms 
Taking to internal thread.
