### ISSUE TITLE
翻訳による表示項目名の違い

### ISSUE THREAD

**Issue by khoanguyen-ms** [MicrosoftDocs/power-platform#1473]
[フィードバックをこちらに入力してください]
「ユーザー プロファイル情報」項目の内容がAzureADやDataverseで表示されている内容とずれています。（翻訳の問題だと思われます）。読み手に混乱を起こさないよう、下記の通りに修正すべきと思われます。
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/KHOANG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/KHOANG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/KHOANG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=JA style='tab-interval:42.0pt;word-wrap:break-word;text-justify-trim:
punctuation'>

Dataverse表示名 | Dataverse属性名称 | Azure   AD/Microsoft 365ユーザー情報項目
-- | -- | --
ユーザー名 | domainname | ユーザー プリンシパル名
氏名 | fullname | 表示名（名 + 姓）
タイトル | title | 役職
既定電子メール* | internalemailaddress | メール
代表電話 | address1_telephone1 | 勤務先の電話番号
携帯電話 | mobilephone | 携帯電話番号
番地 1 | address1_line1 | 番地
市区町村 | address1_city | 市区町村
都道府県 | address1_stateorprovince | 都道府県
国/地域 | address1_country | 国または地域
郵便番号 | address1_postalcode | 郵便番号
Azure AD オブジェクト ID | azureactivedirectoryobjectid | オブジェクト ID

</body>

</html>

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0e1b508b-e71a-b577-51cf-f21c76c58035
* Version Independent ID: 8725a7a3-7b54-3402-c94c-c9e9dee577be
* Content: [ユーザーの作成 - Power Platform](https://learn.microsoft.com/ja-jp/power-platform/admin/create-users#user-profile-information)
* Content Source: [power-platform/admin/create-users.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/admin/create-users.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @khoanguyen-ms. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@khoanguyen-ms 
Taking to internal thread.
