### ISSUE TITLE
Add documentation for the 2 new tabs for tenant level analytics

### ISSUE THREAD

**Issue by jthomps19** [MicrosoftDocs/power-platform#1475]
Hello - there are 2 new tabs (Environments and License Utilization) that are not documented in this article.  Would be great to have documentation on what data these two tabs show.

![image](https://user-images.githubusercontent.com/31544538/191520660-f787402d-c625-40a2-ae62-f206c1f15e6c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ff66cf4-e8a7-7011-b270-8038b2f4e9d5
* Version Independent ID: 9ff66cf4-e8a7-7011-b270-8038b2f4e9d5
* Content: [Tenant-level Analytics for Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/powerapps-analytics-reports)
* Content Source: [power-platform/admin/powerapps-analytics-reports.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-analytics-reports.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jthomps19. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@jthomps19 
Documentation will be added when these tabs become generally available.
