### ISSUE TITLE
"Minimum privileges to run an app" doesn't tell you what they are

### ISSUE THREAD

**Issue by richatcosta** [MicrosoftDocs/power-platform#1477]
The section "Minimum privileges to run an app" has a helpful link to a pre-built solution with a role inside. However it would be useful if those role permissions details were also included on this page directly as eg bullet points / similar, so that it is easier to quickly apply to an existing setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure user security in an environment - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/database-security)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/database-security.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @richatcosta. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@richatcosta 
Thanks for the suggestion. We'll consider this for future revisions to this content.
