### ISSUE TITLE
Get-Adminflow doesen't return disabled Flows from solutions

### ISSUE THREAD

**Issue by johannes-svanborg-T** [MicrosoftDocs/power-platform#1479]
If i am running Get-Adminflow i don't get flows that are imported through a solution as inactive. I need to turn on flow and then turn off flow for it to be visible.

**Comment by Mattp123** [comment]
@johannes-svanborg-Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. 
To contact Support, see here: https://powerapps.microsoft.com/support/ 

Closing this issue.
