### ISSUE TITLE
Sales Manager Content Pack

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/power-platform#148]
Hi The information on this page is not accurate. I cannot see how to do this function

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe570ac-a602-a4fe-73de-853da3d4e584
* Version Independent ID: 49538399-56ce-03c9-d095-883674253478
* Content: [Use Power BI - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/use-power-bi)
* Content Source: [power-platform/admin/use-power-bi.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/use-power-bi.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@makdaddy8888 
Thanks for the feedback. Can you let us know which steps didn't work?

**Comment by makdaddy8888** [comment]
Happy to share a screen session but too hard to type 

Kind Regards
Ben Opit
+61411707070

**Comment by jimholtz** [comment]
@makdaddy8888 
Sorry, Ben. You'll need to contact PowerBi support: https://powerbi.microsoft.com/en-us/support/ to do a session.
