### ISSUE TITLE
Capacity Report not working. 

### ISSUE THREAD

**Issue by achaganti** [MicrosoftDocs/power-platform#1480]
[Enter feedback here]

I get the below error while attempting to try this. I am using service principal and secret. 

{"error":"unsupported_grant_type","error_description":"AADSTS70003: The app requested an unsupported grant type 'client_credential'.\r\nTrace ID:

![image](https://user-images.githubusercontent.com/34516164/192311092-7e65c922-1d5a-47e4-955e-c82f8ad94404.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 816403f3-0104-3d3a-e889-bf0d4cf9bcae
* Version Independent ID: 0f0d27e8-2aaa-0d7c-ea3e-fe949bd9b3b1
* Content: [Tutorial: Create a daily capacity report (preview) - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report?tabs=Azure)
* Content Source: [power-platform/admin/programmability-tutorial-create-daily-capacity-report.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/programmability-tutorial-create-daily-capacity-report.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @achaganti. This issue has been assigned to the doc author for review.

**Comment by jimholtz** [comment]
@achaganti 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/
