### ISSUE TITLE
Conditions to initiate the user mapping file dialog are unclear

### ISSUE THREAD

**Issue by partridgetim** [MicrosoftDocs/power-platform#1481]
Step 6 that reads "This step is applicable only if the data that you are importing contains the user information of the source system" does not fully specify the conditions required to initate the user mapping file dialog.

My import schema includes systemusers and teammembers, however whenever I import the data to the target the tool complains that a user mapping file is required. I am unable to get to the screen shown in step 6 to resolve the issue.

I added the systemuser table with all columns but it does not seem to be enough to trigger the dialog. I initially tried using a schema with the systemuser table only having the systemuserid, domainname fields because I want to update in the target environment based on domainname but neither schemas trigger the user mapping dialiog.

Information on the web about this issue is very sparse.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4761f9d2-e844-cd82-afea-3f44059cf20f
* Version Independent ID: 10f8e4e6-85bd-9bfd-4540-ace48a8b690d
* Content: [Import configuration data - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/import-configuration-data)
* Content Source: [power-platform/admin/import-configuration-data.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/import-configuration-data.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @partridgetim. This issue has been assigned to the doc author for review.

**Comment by partridgetim** [comment]
If you care to read a fulsome description of the issue I'm having see [Unable to migrate users when transfering data using the Configuration Migration Tool (A user map is required to proceed)](https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/467159/unable-to-migrate-users-when-transfering-data-using-the-configuration-migration-tool-a-user-map-is-required-to-proceed)

**Comment by jimholtz** [comment]
@partridgetim 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/
