### ISSUE TITLE
Admin | Inactivity notifications v2 (Check Approval) If approved in the past, but before deletion, it sends a reminder to archive the app or flow before deletion

### ISSUE THREAD

**Issue by russgove** [MicrosoftDocs/power-platform#1482]
Hi, The docs for Admin | Inactivity notifications v2 (Check Approval) says 'If approved in the past, but before deletion, it sends a reminder to archive the app or flow before deletion'.

I don't see anywhere in the flow where it does that. Can someone confirm that this flow does not send emails to anyone other than the admin?

Also , docs should be updated accordingly.

**Comment by jimholtz** [comment]
@russgove 
Thanks for the feedback. Please let us know which topic applies to the above.

**Comment by russgove** [comment]
This is related to the COE Starter Toolkit

**Comment by manuelap-msft** [comment]
Hello,

this repo is only used for documentation feedback, for issues with the features of the CoE Starter Kit itself, please raise an issue here https://aka.ms/coe-starter-kit-issues so the development team of the CoE kit can take a look.
