### ISSUE TITLE
Mistake in example of datatype?

### ISSUE THREAD

**Issue by nkatz01** [MicrosoftDocs/power-platform#1487]
![image](https://user-images.githubusercontent.com/55924227/192836976-533369d9-9d57-4158-a714-4e1fc771dcc7.png)
Is this not a field reference? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40a6dffa-6992-2346-10f3-3f04e1e64722
* Version Independent ID: eec5afa1-3422-417e-169d-b5d72ca69f49
* Content: [Data types - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/data-types?source=recommendations)
* Content Source: [power-platform/power-fx/data-types.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/data-types.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nkatz01. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
Accounts.Owner is an example of the polymorphic lookup it references in the description. In this case it actually points to the owner record.
