### ISSUE TITLE
The Hour(Now()) function doesn't work 

### ISSUE THREAD

**Issue by BastienMazzolini** [MicrosoftDocs/power-platform#1489]
Hello,
Last week I used the function Hour(now()) and it worked, but today it doesn't work anymore, is this normal ?
Waiting for an answer,
Have a good day,
Bastien Mazzolini

**Comment by phecke** [comment]
@BastienMazzolini Please provide a URL to the documentation that you are asking about so that we can assigned the correct writer to followup.

**Comment by phecke** [comment]
@BastienMazzolini Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
