### ISSUE TITLE
Error in explanation for "Non-licensed users/application users/Users with special free licenses"?

### ISSUE THREAD

**Issue by pkothree** [MicrosoftDocs/power-platform#149]
In the chapter for non-licensed usage, the is no mention of a Dynamics 365 Customer Service subscription. But it is used to explain who the request capacity is calculated. Either the Customer Server subscription is missing in this chapter or there is an error in the example.
From what I can understand, I can use the max of two subscriptions, so for the example I could reach either 75.000 (professional sub + PowerApps/PowerAutomate) or 125k (enterprise sub + PowerApps/PowerAutomate).

Example given:
If a tenant has multiple type of subscriptions, their base request capacity would be max of two subscriptions. For example, if a customer has both Dynamics 365 Customer Service and Power Apps per user subscription, their base request capacity would be 100,000 Requests per 24 hours.

Subscriptions listed:
This base request capacity would be based on the type of subscription and would be as follows:
If a tenant has at least one Dynamics 365 enterprise subscription, they will get 100,000 requests per 24 hours
If a tenant has at least one Dynamics 365 professional subscription, they will get 50,000 requests per 24 hours
If a tenant has at least one Microsoft Power Apps or Power Automate subscription, they will get 25,000 requests per 24 hours.

Link: https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#non-licensed-usersapplication-usersusers-with-special-free-licenses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#non-licensed-usersapplication-usersusers-with-special-free-licenses)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@pkothree 
Customer service is sold in enterprise and pro licenses. So depending on which one customer has bought the 100,000 or 50,000 will apply.

**Comment by pkothree** [comment]
The issue here is, that there is no explanation on how the math works and the example is off. Please add an example to the article that is inline with the example provided in the article.

**Comment by pkothree** [comment]
The issue is still not solved. The example does not make sense with the current explanation.

**Comment by cookyrag** [comment]
I agree its misleading , their example read the maximum of two subscriptions so 100,000 , which suggests they are referring to the maximum of any single subscription , but it could also be read as the SUM of your subscriptions. I think if their example figures are correct it should read , "The maximum of any single subscription within the tenants". in this section "Microsoft Power Platform requests allocations based on licenses" it refers to when a user has multiple licenses then the limits is a SUM of those limits , but in the Non Interactive they refer to maximum and the fact that they mention "two subscriptions" just confuses the issue.

**Comment by jimholtz** [comment]
Thanks for the feedback. We've revised the text to clarify.
