### ISSUE TITLE
Reference to Manage Properties option is vague due to non-intuitive UI

### ISSUE THREAD

**Issue by itprofessional68** [MicrosoftDocs/power-platform#1494]
In https://learn.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example2, the instructions read as follows:

"In your new DailySpecials dialog in Composer select the BeginDialog trigger to open the Authoring canvas. Go to Manage properties and select Set a property..."

Can you please update this to read as follows:

"In your new DailySpecials dialog in Composer select the BeginDialog trigger to open the Authoring canvas. On the Authoring canvas, click the + (plus) symbol below the BeginDialog trigger, then click Manage properties....Set a property..."

The instructions as written are confusing. I spent 10 minutes trying to find the Manage properties when the instructions read "Go to Manage properties". It's not intuitive where "Manage properties" is located. You have the click the + (plus) symbol on the cnavas to "go to" it. The phrase "go to Manage properties" does not help the beginner find the option.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65c68413-d758-f0d4-1253-fe9730dd0bc9
* Version Independent ID: 84b17640-22e3-130c-3233-d4af05b5b302
* Content: [Use Bot Framework Composer to display an options list in chatbots - Power Virtual Agents](https://learn.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example2)
* Content Source: [power-virtual-agents/advanced-bot-framework-composer-example2.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/advanced-bot-framework-composer-example2.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @itprofessional68. This issue has been assigned to the doc author for review.

**Comment by JonathanFingold** [comment]
Information has been posted here: https://github.com/microsoft/BotFramework-Composer/issues/9400

**Comment by JonathanFingold** [comment]
@bishalgoswami - This article has been updated. Thanks!
