### ISSUE TITLE
Change OnUnknownIntent to Unknown intent

### ISSUE THREAD

**Issue by itprofessional68** [MicrosoftDocs/power-platform#1495]
The documentation reads as follows:

"Once your new Composer content is successfully published, you can now see that **OnUnknownIntent** was added to the Topics page in Power Virtual Agents."

Please change to read as follows:

"Once your new Composer content is successfully published, you can now see that  **Unknown intent** was added to the Topics page in Power Virtual Agents."

Also, please update the following screenshots to reflect "Unknown intent" (instead of OnUnknownIntent":

https://learn.microsoft.com/en-us/power-virtual-agents/media/composer_example3/e3_bingsearch_intopicslist.png

https://learn.microsoft.com/en-us/power-virtual-agents/media/composer_example3/example3_cropped.png 

This may be due to differences in Bot Framework Composer versions. I was using BFC v2.1.2 to follow the instructions for creating a trigger to handle when the intent is unknown. 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 672a020a-ffb2-6987-63be-b19ae42064ca
* Version Independent ID: 48c7ae46-a318-b36d-df02-d78ef6317f15
* Content: [Use Bot Framework Composer to use Bing search in chatbots - Power Virtual Agents](https://learn.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example3)
* Content Source: [power-virtual-agents/advanced-bot-framework-composer-example3.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/advanced-bot-framework-composer-example3.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @itprofessional68. This issue has been assigned to the doc author for review.

**Comment by JonathanFingold** [comment]
@bishalgoswami - sorry for the delay. Researching some related issues before making an update.
