### ISSUE TITLE
Missing description for variables in file Set-PowerPlatformHubAsDLPErrorSettings.ps1

### ISSUE THREAD

**Issue by tomka75** [MicrosoftDocs/power-platform#1498]
In the documentation the setting of the variable in the script Set-PowerPlatformHubAsDLPErrorSettings.ps1 is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ff93b5f-b80f-45e4-7d90-9d22f5c56089
* Version Independent ID: 58c095c5-1963-bd82-cbca-a57ff90c91e0
* Content: [Create an internal Microsoft Power Platform hub - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/adoption/wiki-community)
* Content Source: [power-platform/guidance/adoption/wiki-community.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/adoption/wiki-community.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tomka75. This issue has been assigned to the doc author for review.
