### ISSUE TITLE
The pull request cannot be activated because the source and/or the target branch no longer exists, or the requested refs are not branches

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/power-platform#1499]
Hello,

I get error  while following the document: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-upgrade-config#updating-the-pipelines-in-azure-devops 

ERROR: TF401398: The pull request cannot be activated because the source and/or the target branch no longer exists, or the requested refs are not branches

**Comment by rsantos00** [comment]
Thanks for reporting this @phecke, we have a new experience to setup ALM projects that is under the AA4PP Admin App (Model Driven App). We will update this doc to include the new experience. If you need help, please create a question under https://github.com/microsoft/coe-starter-kit/issues and wr can follow up from there.
Thanks

**Comment by rsantos00** [comment]
We should move this discussion to https://github.com/microsoft/coe-starter-kit/issues , we need more information since we were not able to reproduce the situation.
