### ISSUE TITLE
Unable to enable admin mode for a Trial subscription based environment

### ISSUE THREAD

**Issue by ShanthiTV** [MicrosoftDocs/power-platform#1502]
Hi Team,

I have created a Trial(subscription-based) environment. I have started a per user plan of Power Apps and Power Automate with the same Tenant. When I try to enable the admin mode for the environment, I'm getting **The environment SKU 'SubscriptionBasedTrial' is invalid.** error. 
I'm following the docs from here. 

https://learn.microsoft.com/en-us/power-platform/admin/trial-environments#create-a-trial-subscription-based-environment-in-the-power-platform-admin-center

Please let me know what I'm missing out.

Thanks!

**Comment by jimholtz** [comment]
@ShanthiTV 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/
