### ISSUE TITLE
Inconsistent wording 

### ISSUE THREAD

**Issue by femo1de** [MicrosoftDocs/power-platform#1507]
I think this makes no sense, why choose "remove" to install?

![image](https://user-images.githubusercontent.com/90273092/194817030-39860060-7204-4415-8020-eb550172c8b5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Version Independent ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Content: [Microsoft Power Platform CLI - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction#install-power-platform-cli-for-windows)
* Content Source: [power-platform/developer/cli/introduction.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/introduction.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @femo1de. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
This was fixed.
