### ISSUE TITLE
Global Variables

### ISSUE THREAD

**Issue by LiorArmiev** [MicrosoftDocs/power-platform#151]
What about global variables in the conversation? same as the token

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3848c348-51bb-2370-4dc4-d8c16b588ab7
* Version Independent ID: 908ee503-90d3-d643-917e-a792432339b1
* Content: [Work with variables in Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/authoring-variables)
* Content Source: [power-virtual-agents/authoring-variables.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/authoring-variables.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by aledoy** [comment]
When is global variable coming out? Doesn't make sense that this is not out there yet, i had to store/retireve values into CDS using actions.

**Comment by iaanw** [comment]
Hey, thanks for your messages - global variables is coming with 202 release wave 1 - https://docs.microsoft.com/power-platform-release-plan/2020wave1/power-virtual-agents/use-global-variables-across-topics-within-bot

**Comment by dougmaloney** [comment]
> When is global variable coming out? Doesn't make sense that this is not out there yet, i had to store/retireve values into CDS using actions.

@aledoy I can't wait any longer for global variables. how did you get a unique ID for the conversation to store the values in CDS against ?
