### ISSUE TITLE
PAC CLI Doc says to choose remove option when trying to install.

### ISSUE THREAD

**Issue by MrRishabhJain** [MicrosoftDocs/power-platform#1512]
https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction#install-power-platform-cli-for-windows

The above section should say "choose the Install option" rather than "choose the Remove option".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Version Independent ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Content: [Microsoft Power Platform CLI - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction#install-power-apps-cli)
* Content Source: [power-platform/developer/cli/introduction.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/introduction.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@MrRishabhJain 
Thanks for catching this.
I've fixed it and the change will be visible later today.
