### ISSUE TITLE
How to stay up to date with the power platform documentaion

### ISSUE THREAD

**Issue by lukas-nC** [MicrosoftDocs/power-platform#1518]
Hi,

is there an easy way to get a notification, when something in the documentation changes? Or list when which site has been added/ edited?
I only found a [flow templete](https://powerautomate.microsoft.com/en-US/templates/details/4fcdb850e8204ce392f2353830264220/send-me-an-email-when-documentation-is-updated-on-docsmicrosoftcom/), but there I have to define a specific URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 532b6838-6e2a-2bfd-e0c7-5454446f7564
* Version Independent ID: d1448fc4-5eb9-9f01-cbaf-c3edf64a2e1c
* Content: [Overview - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/overview)
* Content Source: [power-platform/guidance/coe/overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/overview.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lukas-nC. This issue has been assigned to the doc author for review.
