### ISSUE TITLE
power platform graph api

### ISSUE THREAD

**Issue by russgove** [MicrosoftDocs/power-platform#152]
Hi,
When can i find information on the graph apis that can be used to get information about powerapps and flows, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2bb683-51c1-2dbb-d65d-20f879320106
* Version Independent ID: cd768223-1723-b37a-9537-5398761b0fe0
* Content: [Power Apps analytics - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/analytics-powerapps)
* Content Source: [power-platform/admin/analytics-powerapps.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/analytics-powerapps.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@russgove 
Please let us know what information you're looking for that's missing from this topic. Thanks.

**Comment by RohitBundele** [comment]
Where can the actual data be accessed from? Are there any connectors available to fetch this telemetry data? Using which we can create our own visuals and calculated metrics

**Comment by russgove** [comment]
thanks for following up,
i am trying to find out if the rest apis that are called by powerapps admin connector can be called from my own custom code, Are these apis documented anywhere?

**Comment by pnghub** [comment]
Have you taken a look at these - 
https://docs.microsoft.com/en-us/connectors/powerappsforadmins/
https://powerapps.microsoft.com/en-us/blog/gdpr-admin-powershell-cmdlets/

**Comment by jimholtz** [comment]
@russgove 
Let me know if the above links did not provide what you're looking for.
