### ISSUE TITLE
Expand Education/Academic

### ISSUE THREAD

**Issue by WyattBest** [MicrosoftDocs/power-platform#153]
This article could benefit from more information about Office 365 for Education besides "Non-Profit, Government and Academic pricing is available in respective program channels."

There are many scenarios where college administrators would like to build Power Apps to process input from students, but if it requires licensing a thousand students at $40/mo, that's half a million dollars and a non-starter.

Who exactly requires a license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#trial-licenses)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@WyattBest 
Thanks for the suggestion. I'm researching a contact for this.

**Comment by jimholtz** [comment]
@WyattBest 
Probably best to contact sales and get in the loop with an advisor.
https://info.microsoft.com/ww-landing-Contact-Microsoft-Education-website.html?lcid=en-us
