### ISSUE TITLE
Licencing for inactivity process

### ISSUE THREAD

**Issue by lukas-nC** [MicrosoftDocs/power-platform#1530]
Hi, 

which licensing is required for who in the inactivity processes? 
Specifically, I'm in interested in, does the one who gets the approval from "Admin | Inactivity notifications v2 (Start Approval for Apps)" flow need a premium licence, if he just approves or rejects and doesn't use the link to the clean up app?

Best Regards

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 3445b35a-114e-010d-a42b-3d738fa68c56
* Version Independent ID: 87fcef34-4b4a-cee9-f171-e1bd1e8ec970
* Content: [Governance-Komponenten - Power Platform](https://learn.microsoft.com/de-de/power-platform/guidance/coe/governance-components)
* Content Source: [power-platform/guidance/coe/governance-components.md](https://github.com/MicrosoftDocs/power-platform-pr.de-DE/blob/live/power-platform/guidance/coe/governance-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

no premium license is required for interacting with the Approvals via eMail. However, if you want to share the Cleanup old objects app this requires a premium license - either per user or per app - or for the environment to be covered with Pay as you go.

Manuela
