### ISSUE TITLE
Power Pages Authenticated Users licensing

### ISSUE THREAD

**Issue by avsrot** [MicrosoftDocs/power-platform#1531]
Thanx for the detailed  "Power Platform" FAQ.

There is one angel of Power Pages licensing which I still can't get my head wrapped around it - 
if I have **500** 'Authenticated Per User' users **registered** already to my site, but on a specific month only **200** of them have **actually accessed the site** - how many licenses will I be charged for on this specific month?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Platform licensing FAQs - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @avsrot. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for your feedback.

I encourage you to speak with your Microsoft rep about your needs. 

You would need to pay for whatever subscription capacity you select, whether the users log in or not. 

If your site only has 200 users per month (out of your total user population) then you may want to consider getting a subscription that covers only that usage. Please see this [FAQ item](https://learn.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#if-i-create-a-power-pages-website-that-can-potentially-be-used-by-100000-authenicated-users-however-in-a-given-month-it-will-only-be-used-by-5000-users-out-of-the-100000-do-i-need-to-purchase-authenticated-per-user-capacity-for-100000-users-or-5000-users) for more information. 

The other option is to consider [pay-as-go](https://learn.microsoft.com/en-us/power-platform/admin/pay-as-you-go-meters?tabs=image#power-pages-meters-preview) licensing, which is currently in preview, in that scenario, you would only pay for which users logged in ($4 per user per month).
