### ISSUE TITLE
platform

### ISSUE THREAD

**Issue by CCSdany2021** [MicrosoftDocs/power-platform#1533]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 706b8a1d-984e-f4f0-deaa-ed4e8b740dc5
* Version Independent ID: 706b8a1d-984e-f4f0-deaa-ed4e8b740dc5
* Content: [Función Notify en Power Apps - Power Platform](https://learn.microsoft.com/es-es/power-platform/power-fx/reference/function-showerror)
* Content Source: [power-platform/power-fx/reference/function-showerror.md](https://github.com/MicrosoftDocs/power-platform-pr.es-ES/blob/live/power-platform/power-fx/reference/function-showerror.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CCSdany2021. This issue has been assigned to the doc author for review.
