### ISSUE TITLE
Display names modified on solution export/import should be more thoroughly explained.

### ISSUE THREAD

**Issue by gregli-msft** [MicrosoftDocs/power-platform#1534]
[Enter feedback here]

The section under [display names and identifiers](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/operators#display-names-and-logical-names) should be expanded to include solution import and export.  We have had an ICM where the logical names didn't match up between two environments, the Canvas app correctly updated the names, but it was surprising to the customer that we would rewrite their formulas on a solution import.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bae1ecd0-a13c-440d-f536-e79c38c79f05
* Version Independent ID: bae1ecd0-a13c-440d-f536-e79c38c79f05
* Content: [Operators and Identifiers in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/operators#display-names-and-logical-names)
* Content Source: [power-platform/power-fx/reference/operators.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/operators.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gregli-msft. This issue has been assigned to the doc author for review.
