### ISSUE TITLE
The AsType and IsType Syntax "TableType" parameter definitions are switched up

### ISSUE THREAD

**Issue by Underdoge** [MicrosoftDocs/power-platform#1535]
The AsType and IsType [Syntax](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-astype-istype#syntax) "TableType" parameter definitions are switched up. AsType is for casting, IsType is for testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d90a4f0f-2811-9c48-b262-8ff54b4661c9
* Version Independent ID: d90a4f0f-2811-9c48-b262-8ff54b4661c9
* Content: [AsType and IsType functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-astype-istype)
* Content Source: [power-platform/power-fx/reference/function-astype-istype.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-astype-istype.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Underdoge. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@Underdoge.  Thank you for the feedback. I fixed the Syntax section and corrected the definitions. 

Thanks,
Mints
