### ISSUE TITLE
Misleading section title - Provision a Sandbox Environment

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/power-platform#154]
Please consider renaming the section "Provision a Sandbox Environment" to "Change a production environment to sandbox".
I assisted someone in forums who thought this section described how to create a sandbox environment and unintentionally converted their production instance to a sandbox.

I also suggest adding a new section named "Create a Sandbox Environment" that either describes how to create a sandbox or links to the appropriate section in the Create Environments page (https://docs.microsoft.com/en-us/power-platform/admin/create-environment)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd73afb-e2cf-acba-4d91-ec5700c36864
* Version Independent ID: 83657a57-1fc6-8270-24cf-00d68f9918de
* Content: [Sandbox environments - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/sandbox-environments#feedback)
* Content Source: [power-platform/admin/sandbox-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/sandbox-environments.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by businessuser123** [comment]
Upvoted because of the sheer fact that I thought exactly the same when reading this documentation. First thing I thought: "But, you have to create an environment to convert it, right? Otherwise you'll convert your production environment to a sandbox.". Please change this to prevent faulty interpretation :-).

**Comment by jimholtz** [comment]
@feridunkadir @businessuser123 
Thanks for the suggestions! Topic will update today.
