### ISSUE TITLE
Format panel content table with wrong values

### ISSUE THREAD

**Issue by danielvi1787** [MicrosoftDocs/power-platform#1540]
Hello, 

In the section Format panel content, the table with the example values for the component inside the panel should be:

x -> cmp_panel.ContentX
y -> cmp_panel.ContentY
width - > cmp_panel.ContentWidth
height -> cmp_panel.ContentHeight

and no all cmp_panel.X as it shows.

Best!
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1346323-c9a3-5c4e-d4d2-32080de5b27f
* Version Independent ID: f1346323-c9a3-5c4e-d4d2-32080de5b27f
* Content: [Panel control reference (experimental) - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/panel)
* Content Source: [power-platform/guidance/creator-kit/panel.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/creator-kit/panel.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @danielvi1787. This issue has been assigned to the doc author for review.

**Comment by denisem-msft** [comment]
This has been fixed and will be published soon. Thank you for your feedback.
