### ISSUE TITLE
IsBlank() vs =Blank()

### ISSUE THREAD

**Issue by benjdv** [MicrosoftDocs/power-platform#1543]
[Enter feedback here]
Documentation for isblank function seems to differ from reality of PBI

Documentation says : 
`The IsBlank function tests for a blank value or an empty string. The test includes empty strings to ease app creation since some data sources and controls use an empty string when there is no value present. To test specifically for a blank value use if( Value = Blank(), ... instead of IsBlank.`

But in PBI, it's the exact opposite : 
- IsBlank() return True only on blank value
- =Blank() return True on Blank value AND empty string

problemDocumentation1 = if(isblank(blank()),"isblank(blank())=>True","isblank(blank())=>False")
=> isblank(blank())=>True -- **Conform with documentation**

problemDocumentation2 = if(isblank(""),"isblank("""")=>True","isblank("""")=>False")
=> isblank("")=>False -- **NOT conform with documentation**

problemDocumentation3 = if(blank()=blank(),"blank()=blank()=>True","blank()=blank()=>False")
=>blank()=blank()=>True -- **Conform with documentation**

problemDocumentation4 = if(""=blank(),"""""=blank()=>True","""""=blank()=>False")
=> ""=blank()=>True -- **NOT conform with documentation**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a0ff904-ed1a-c723-ff0b-905b0280b22c
* Version Independent ID: 2a0ff904-ed1a-c723-ff0b-905b0280b22c
* Content: [Blank, Coalesce, IsBlank, and IsEmpty functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-isblank-isempty)
* Content Source: [power-platform/power-fx/reference/function-isblank-isempty.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-isblank-isempty.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @benjdv. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
IsBlank("") returns true in Power Fx. You mention PBI so are you talking about Power BI? If so, that documentation is here: https://learn.microsoft.com/en-us/dax/isblank-function-dax

**Comment by benjdv** [comment]
@jorisdg, you are right. Thanks.
I don't remember how I got to the power-fx page, but I clearly missed the "fx" of power.
Apologize me for this pointless warning.
