### ISSUE TITLE
Step is missing in enabling previews in Power Platform admin center

### ISSUE THREAD

**Issue by neeranelli** [MicrosoftDocs/power-platform#1544]
Hello,

It would be great if the step to expand **Product** and select **Features** is added in the [In the Power Platform admin center](https://learn.microsoft.com/en-us/power-platform/admin/what-are-preview-features-how-do-i-enable-them#in-the-power-platform-admin-center) procedure.

![image](https://user-images.githubusercontent.com/52775901/197748985-ca98aaa1-e9ba-4303-b068-bce9b2d707d4.png)

Also, in the [In a Unified Interface app](https://learn.microsoft.com/en-us/power-platform/admin/what-are-preview-features-how-do-i-enable-them#in-a-unified-interface-app) procedure, the UI says license terms, while the article refers to it as Supplemental Terms of Use. It causes a slight confusion because the user tends to search for supplemental terms.

Thank you.
Neeraja
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 483c5e01-d37a-29de-a580-c5614247e95a
* Version Independent ID: c492ece3-17f6-1085-e717-401b68032c11
* Content: [Enable Preview features to get early access - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/what-are-preview-features-how-do-i-enable-them)
* Content Source: [power-platform/admin/what-are-preview-features-how-do-i-enable-them.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/what-are-preview-features-how-do-i-enable-them.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @neeranelli. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
Fixed; will be live shortly.
