### ISSUE TITLE
This solution does not work in the current form of Power Apps.

### ISSUE THREAD

**Issue by jeremygiden1** [MicrosoftDocs/power-platform#1546]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b784f58-59eb-fb06-da8f-4747f6900db3
* Version Independent ID: 9b784f58-59eb-fb06-da8f-4747f6900db3
* Content: [Filter, Search, and LookUp functions in Power Apps (contains video) - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-filter-lookup)
* Content Source: [power-platform/power-fx/reference/function-filter-lookup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-filter-lookup.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jeremygiden1. This issue has been assigned to the doc author for review.

**Comment by jeremygiden1** [comment]
Team,

We have worked out the solution ourselves.
Appreciate the quick response.

Thank you for your time, / Best regards,

Jeremy Iden

Senior Director Technical Support, Service and Training
Farm Technologies Representative USA
Region NAM | North America

Email
Landline
Address
Web
***@***.******@***.***>
+1 630-548-8366
1385 N Weber Rd, Romeoville, IL 60446, United States of America
www.gea.com<https://t-eu.xink.io/Tracking/Index/ricAAAd1AACf21AA0>

**Comment by tapanm-MSFT** [comment]
Thank you for the update. Closing this issue for now.
