### ISSUE TITLE
Is there any On-Premise Data Gateway limitation ?

### ISSUE THREAD

**Issue by Jayesh040** [MicrosoftDocs/power-platform#155]
If we have PowerApps Standalone  license like "Power Apps
per user plan" or "Power Apps
per app plan" which includes On-Premise Data Gateway feature. 
Is there anything like only specific MB or GB of data publish is allowed, exceeding those can cost add-on price ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#feedback)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@Jayesh040 
Sorry for the delayed response. Have you reviewed the licensing guide:
https://go.microsoft.com/fwlink/?linkid=2085130
