### ISSUE TITLE
Provide clear link for product feedback on Power Platform CLI

### ISSUE THREAD

**Issue by martin-dreyer-teck** [MicrosoftDocs/power-platform#1553]
The product feedback link on the Power Platform CLI pages take us to https://powerusers.microsoft.com/ which is simply a launching page to a wide variety of forums. Please provide a link that is more specific so we can both see and add feedback on the Power Platform CLI specifically.

Example of a page with this problem: https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction

Thanks.

**Comment by alex-mclachlan-silverbear** [comment]
I agree with this comment. For example, I would like to submit an idea that it would be useful on `pac solution import` to have an option for dependency checking only. But I cannot find where this should be logged.

**Comment by JimDaly** [comment]
Added this section to the bottom of the page:

# Provide feedback
Use [github.com/microsoft/powerplatform-build-tools/discussions](https://github.com/microsoft/powerplatform-build-tools/discussions) to view and submit feedback for PAC CLI.
