### ISSUE TITLE
Please add links to and from PowerPlatform Security Topic. 

### ISSUE THREAD

**Issue by MattB-msft** [MicrosoftDocs/power-platform#1556]
This item is very hard to find when searching for information on security privileges in the system. 

Can this be linked to these topics please:
https://learn.microsoft.com/en-us/power-platform/admin/wp-security-cds
https://learn.microsoft.com/en-us/power-platform/admin/database-security

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f0c2675-2cf5-6319-493b-e5215a0a5dfa
* Version Independent ID: fc57a4d1-852a-ef61-f133-36add99d5323
* Content: [Miscellaneous privileges - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/miscellaneous-privileges)
* Content Source: [power-platform/admin/miscellaneous-privileges.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/miscellaneous-privileges.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by ChrisGarty** [comment]
@jimholtz , I submitted PR 5790 for this
