### ISSUE TITLE
Sentence repeated

### ISSUE THREAD

**Issue by EllenWehrle** [MicrosoftDocs/power-platform#1558]
[The following sentence is repeated following a table: To determine which license a user has, sign in to the [Microsoft 365 admin center](https://admin.microsoft.com/) and follow the steps in [Assign licenses to multiple users on the Active users page](https://learn.microsoft.com/en-us/office365/admin/manage/assign-licenses-to-users?view=o365-worldwide).]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform admin center - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/create-environment)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @EllenWehrle. This issue has been assigned to the doc author for review.
