### ISSUE TITLE
Change 'Azure Bot Framework'

### ISSUE THREAD

**Issue by tombyang** [MicrosoftDocs/power-platform#156]
This should be Microsoft Bot Framework; Azure Bot Framework isn't a thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b1fcdf-f5ae-8302-1a7c-984c2dd2f81b
* Version Independent ID: ec989e88-349e-6a1b-c55d-7a4b4b600815
* Content: [Customize the Power Virtual Agents web chat canvas - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/customize-default-canvas)
* Content Source: [power-virtual-agents/customize-default-canvas.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/customize-default-canvas.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
I've made these updates and they should go live today or tomorrow. Thanks for bringing this up.
