### ISSUE TITLE
Description of Admin| Sync Template v3 (call Updates) not clear

### ISSUE THREAD

**Issue by PPMini** [MicrosoftDocs/power-platform#1562]
Customer feedback: The description of the flow does not clarify ' which three flows will be triggered'

<img width="542" alt="image" src="https://user-images.githubusercontent.com/112712553/199066902-90b03453-651f-4414-aabf-8b11ba6002cf.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PPMini. This issue has been assigned to the doc author for review.
