### ISSUE TITLE
Grammar errors - assuming English isn't the writer's first language

### ISSUE THREAD

**Issue by hzigli** [MicrosoftDocs/power-platform#157]
Corrections:

1. If any user exceeds request capacity, admin for the tenant/environment would be notified and would be able to assign Power Apps and Power Automate request capacity to that user. - should be "will be notified and will be able".
2. overages at this point of time. - should be "at this point IN time" (capitalization for emphasis only)
3. Administrators would be notified should be "will be notified"
4. During this transition period reporting would be made available  - "will be made available" (seems to be confusion regarding when to use *would* versus *will*).

In general, you need a technical writer that has English as a first language to edit pages on this site. It's very clear this is either produced by someone who doesn't speak English as a primary language OR you are using a bot / translator to generate the content from another language. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#feedback)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@hzigli 
Thanks for the feedback. We'll get this topic edited.
