### ISSUE TITLE
Power Automate URL Correction

### ISSUE THREAD

**Issue by slgsperry** [MicrosoftDocs/power-platform#1571]
The Power automate URL has changed, it is no longer https://flow.microsoft.com/manage/environments, it is https://make.powerautomate.com/manage/environments/. Shouldn't the documentation reflect that change?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @slgsperry. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
For the time being, flow.microsoft.com still redirects to make.powerautomate.com but we'll put that change on our backlog.
