### ISSUE TITLE
Documentation for Setting up CoE for a subset of environments is wrong

### ISSUE THREAD

**Issue by slgsperry** [MicrosoftDocs/power-platform#1572]
The first bullet states "After import of the Core components and before you turn on flows, set the value of the `is All Environments` Inventory environment variable to No. Learn more: [Update environment variables](https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables)).".  The problem is there is no environment variable with that name. I found one called `FullInventory`, but that is as close as I could find. What should the environment variable be?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ae45dc4-b21f-7f21-fdce-b6cf794bee17
* Version Independent ID: 2ae45dc4-b21f-7f21-fdce-b6cf794bee17
* Content: [Frequently asked questions - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments)
* Content Source: [power-platform/guidance/coe/faq.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/faq.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The Environment Variable is called **is All Environments Inventory** and was introduced and added with the November release of the CoE starter kit, which was released yesterday. You'll have to upgrade to the latest version to use this feature. Please note, you will only have to use this feature if you want to perform a partial inventory (inventory a subset of environments vs all environments in your tenant).

**Comment by slgsperry** [comment]
I am in the process of importing the November CoE into a new environment and it is NOT there.


Regards,

Steven Perry
Business Application Architect
P: 212-324-8810

**Comment by manuelap-msft** [comment]
It has a Default value, so you won't be prompted on import but you can modify it afterwards. The November version is 3.56, 3.53 is October so you've got last months version. You can download the November release from here https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2022

**Comment by slgsperry** [comment]
I downloaded the `CoEStarterKit-Unmanaged.zip` to grab everything at once and it has the 3.53 version.

**Comment by manuelap-msft** [comment]
Please download the CoEStarterKit.zip to download and install the managed versions, and learn how to extend the kit with your own unmanaged solution here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

We won't have an unmanaged version for November as we had some issues with our automated release. The unmanaged version will be available again in December.

**Comment by slgsperry** [comment]
Thank you, I will do that.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @slgsperry. This issue has been assigned to the doc author for review.
