### ISSUE TITLE
Non existent Flow

### ISSUE THREAD

**Issue by slgsperry** [MicrosoftDocs/power-platform#1573]
The "Turn on setup flows" section mentions flow `Admin | Excuse Non Inventoried Envts from Governance Flows`.  This flow does not exist. At least not as part of the core solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#feedback)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
It does exist as part of the November release. It's a flow that was added with the latest release. Our docs will always reflect the latest version.
