### ISSUE TITLE
Backup restoration requesting details

### ISSUE THREAD

**Issue by BillyCottrell** [MicrosoftDocs/power-platform#1575]
Hi,

I have a production environment and want to restore that production environment to a sandbox environment.
For some reason, my sandbox environment won't appear.
Is it possible to restore a backup from a production to a sandbox, because there is no specification in the documentation from which type of environment you can restore a backup from to a sandbox environment?
Is this only sandbox to sandbox, or is production to sandbox possible as well?
Because I currently don't understand what is going wrong or what the cause might be for not being able to restore a backup from my production environment to a sandbox environment.

Any ideas?

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9c58fb1-e6a2-5210-3774-4ea4bbff4572
* Version Independent ID: 57c1780c-b097-af8c-82fa-47e38a63995c
* Content: [Back up and restore environments - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/backup-restore-environments)
* Content Source: [power-platform/admin/backup-restore-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/backup-restore-environments.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BillyCottrell. This issue has been assigned to the doc author for review.

**Comment by waynevelliott** [comment]
Hi @BillyCottrell. I realize this thread is over a year old so hopefully long resolved. Is your prod environment managed and other environments unmanged?

I found that you can only restore:
managed => managed
unmanaged => unmanaged

**Comment by BillyCottrell** [comment]
Hi @waynevelliott ,

I just checked and this issue is indeed resolved since I was placed on a different project I haven't been able to follow up on this and forgot about this issue. I don't know why but at the time it wouldn't show any sandbox environment when I wanted to convert my production environment.

I am afraid that the managed/unmanaged state doesn't apply to the environment, as the environment doesn't have such a state.
Unmanaged or managed only applies to solutions and in that case, you are correct a solution can only be changed, updated, etc with a solution that has the same state.

Nonetheless, this issue is resolved, thx for the reminder!

**Comment by waynevelliott** [comment]
Hi @BillyCottrell,

Environments are now also managed or (default) unmanaged. Recommend reviewing the doc below as its useful to understand which features are only available for managed environments (e.g. 28 day backup retention).

https://learn.microsoft.com/en-us/power-platform/admin/managed-environment-overview
