### ISSUE TITLE
"How severe is this issue?" when creating new support ticket for Power Apps is only Minimal

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/power-platform#158]
Hi team,

When creating new support ticket for Power Apps, it is always **Minimal** and there is **no other choices.** 
How can user submit higher severity ticket without Premier?

Kindly explain the "How severe is this issue?" when creating new support ticket for Power Platform products.

![image](https://user-images.githubusercontent.com/61499598/78205483-68decd00-74c6-11ea-9b5f-14cf763b939c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3296698b-48cc-9655-267e-92775f33e0b7
* Version Independent ID: fe8f88d2-5fd4-6946-4ae6-d1abb856bf2f
* Content: [Get Help + Support - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/get-help-support)
* Content Source: [power-platform/admin/get-help-support.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/get-help-support.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@DavidPaf 
Only paid subscriptions and ProDirect or Premier support plans provide higher severities.
