### ISSUE TITLE
Update page to show StartScreen instructions in favor of OnStart

### ISSUE THREAD

**Issue by joneselliot** [MicrosoftDocs/power-platform#1583]
Hello,

As the OnStart functionality will be deprecated/reduced, could you update this page to encourage use of the StartScreen property instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10559351-f355-f97f-e7a4-903cd6a804fc
* Version Independent ID: 10559351-f355-f97f-e7a4-903cd6a804fc
* Content: [Launch and Param functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-param#feedback)
* Content Source: [power-platform/power-fx/reference/function-param.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-param.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jorisdg** [comment]
Thank you for pointing this out, I'm making an update to this doc.
