### ISSUE TITLE
Source of DLP violation error message

### ISSUE THREAD

**Issue by AkunerTulachan** [MicrosoftDocs/power-platform#1588]
After I installed COE, the flow checker message seems to have updated for DLP violation. Can someone please help me to track down the source of the data? 
![image](https://user-images.githubusercontent.com/55730006/200976868-fe45cca0-2e3a-4903-9270-5a36a636236d.png)

**Comment by phecke** [comment]
@AkunerTulachan Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://admin.powerplatform.microsoft.com/support Closing this issue.

If you have a question about an article, please provide the article URL and your question. Thanks.
