### ISSUE TITLE
Need to update Date range that user can download the Reports

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/power-platform#159]
Hi Team,

Kindly review and confirm/update the date range that user can see/download the report (28 days/30 days)

The document only mentions 

The "Active Dynamics 365 Customer Engagement Plan Users by Application" report shows the last 30 days of data at the tenant level.

How about other reports? 

Best regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c99626-6458-46b4-f099-ce10c30890c7
* Version Independent ID: d3766ded-359b-160c-d7f5-a7e6ffa103d6
* Content: [Common Data Service analytics - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service#download-reports)
* Content Source: [power-platform/admin/analytics-common-data-service.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/analytics-common-data-service.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by pnghub** [comment]
Thanks for bringing this to our notice!  Will update the doc. All downloads pull in 30 day of data.
