### ISSUE TITLE
Power Automate URL does not exist since the new make.powerautomate.com change

### ISSUE THREAD

**Issue by poi-radvine** [MicrosoftDocs/power-platform#1590]
Setting the URL als EnviornmentVariable does not work since the change to make.powerautomate.com
It results in a 404 in my tenant. Try it out: https://make.powerautomate.com/environments/

<html>
<body>

Power Automate environment variable | The URL used by Power Automate for your cloud.For an environment in the commercial cloud: https://flow.microsoft.com/manage/environments/For a GCC, GCC High, or DoD environment, check Power Automate US government service URLs.
-- | --

</body>
</html>
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**Power Automate environment variable	The URL used by Power Automate for your cloud.
For an environment in the commercial cloud: https://flow.microsoft.com/manage/environments/
For a GCC, GCC High, or DoD environment, check [Power Automate US government service URLs](https://learn.microsoft.com/en-us/power-automate/us-govt#power-automate-us-government-service-urls).
Power Automate environment variable	The URL used by Power Automate for your cloud.
For an environment in the commercial cloud: https://flow.microsoft.com/manage/environments/
For a GCC, GCC High, or DoD environment, check [Power Automate US government service URLs](https://learn.microsoft.com/en-us/power-automate/us-govt#power-automate-us-government-service-urls).

**Comment by manuelap-msft** [comment]
Thanks for providing feedback - in this GitHub repo, we only track feedback related to documentation - if you have issues with the setup and configuration of the kit itself, can you please raise them via https://aka.ms/coe-starter-kit-issues for our development team to have a look at it! Thank you!

**Comment by poi-radvine** [comment]
Hi, this is feedback to the documentation.
The old URL https://flow.microsoft.com/manage/environments/ is not longer in use since the change performend in 5/22

**Comment by manuelap-msft** [comment]
We are tracking the URL change for Documation already via #1571 but there is still a redirect in place by the product from flow.microsoft.com to make.powerautomate.com
