### ISSUE TITLE
License Requirements for Admins to create and manage environments?

### ISSUE THREAD

**Issue by willdrobins** [MicrosoftDocs/power-platform#16]
I don't see in the licensing guide or this page where it talks about what licensing is required for Administrators who would be creating and managing additional Power Apps environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Licensing overview - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@willdrobins 
Administrators do not require a license for creating apps in Power Apps. Hence there is no license requirement for those.

**Comment by willdrobins** [comment]
I was talking about environments, not apps. I read somewhere there is a limit of 2 new environments per Plan 2 license. So if you wanted 6 new environments, you need at least 3 P2 licenses.

**Comment by jimholtz** [comment]
@willdrobins 
Please review: 
https://go.microsoft.com/fwlink/?linkid=2085130
