### ISSUE TITLE
Dynamics 365 App for Outlook

### ISSUE THREAD

**Issue by lubergst** [MicrosoftDocs/power-platform#160]
Trying to understand if the Set inactivity timeout settings can be configured for the Dynamics 365 App for Outlook.  Currently on this page only references Dynamics 365 for Outlook?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f16e06d-cc40-61c2-df7c-83b0c3c357f5
* Version Independent ID: a4da4da4-a640-3010-488c-f293db397b03
* Content: [Security enhancements: User session and access management - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/user-session-management?source=docs#feedback)
* Content Source: [power-platform/admin/user-session-management.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/user-session-management.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by mduelae** [comment]
@lubergst Thank you for the feedback. I'm checking with our internal team and will get back to you soon as I hear back.

Thanks,
Mints

**Comment by mduelae** [comment]
@sidhartg please reply.

**Comment by sidhartg** [comment]
Thanks for the feedback!

Dynamics 365 App for Outlook is a model-driven app. So, any inactivity timeout configurations and enforcement applicable for  model-driven apps is applicable for Dynamics 365 App for Outlook as well.

Regards,
Sid Gundavarapu
Product Owner

**Comment by KumarVivek** [comment]
Closing the issue as this seems to be addressed.
