### ISSUE TITLE
The Page says that Validate can be used for Verifying that a Column is Required. Its the first bullet. But how?

### ISSUE THREAD

**Issue by MichaelGernaey** [MicrosoftDocs/power-platform#1603]
[Enter feedback here]
Hello,
We want to use the Validate function to verify that a lookup column is required. DataSourceInfo does not work on lookups so we are trying to validate.

It says clearly below and on the page in the first bubble that it can validate if a column is required, but we cannot find an example. Please add one..

Thanks!

- **whether a column requires a value**
- how long a string of text can be
- how high and low a number can be
- how early and late a date can **be**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83a26be3-7363-1b3e-033e-ecfbf40f1f36
* Version Independent ID: 83a26be3-7363-1b3e-033e-ecfbf40f1f36
* Content: [Validate function in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-validate)
* Content Source: [power-platform/power-fx/reference/function-validate.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-validate.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MichaelGernaey. This issue has been assigned to the doc author for review.

**Comment by MichaelGernaey** [comment]
Thanks. Just an FYI. This is for an internal Microsoft Project for Federal and I realize doc changes etc can be slow. I retired from Microsoft myself. We just need to find out if its even possible to do what we want using the function, even before the document is updated. If thats possible please v-mgernaey@microsoft.com and before retirement mgern Thanks!

**Comment by jorisdg** [comment]
This function asks the underlying datasource to do the validation with the metadata it has. As the maker calling the function, you just specify which column you wish to validate. Is your question about adding your own validation?

**Comment by MichaelGernaey** [comment]
Ahh, sorry read this one a bit incorrectly.

We were expecting some type of metadata about the call that we could say “tell us if this is required”, versus, it can fail validation “because its required”, which isn’t us telling it we want to know if its required, it simply checks all the possibilities and then says yes or no 😊

I think.

Because the reason is, we wanted to do this
“if X is required” then show the red asterix if not required then don’t.

Couldn’t get this to work with DataSourceInfo, then thought sweet maybe we can use Validate, so we just jumped the gun.

Sorry about that and thanks for the response
