### ISSUE TITLE
Missing CenterOfExcellenceCoreComponentsTeams_x_x_x_xx_managed.zip in the downloaded CoEStarterKit.zip

### ISSUE THREAD

**Issue by muges01** [MicrosoftDocs/power-platform#1609]
The CenterOfExcellenceCoreComponentsTeams_x_x_x_xx_managed.zip is missing in the download CoEStarterKit.zip.
Downloaded Date 19/11/2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @muges01. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Please see the note in this section: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#decide-what-environment-type-to-use-production-or-dataverse-for-teams

We are no longer investing in the Dataverse for Teams version of the CoE Starter Kit. You can download the latest available version here: https://aka.ms/CoEStarterKitD4T but it will no longer be included in current releases.
