### ISSUE TITLE
Need comparison of Subject vs Category

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/power-platform#161]
Point to a content dedicated to explain the role of Subject and Category will be useful, as too much of criticism is out there about subject. Is subject likely to be deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b10ea23f-970e-6831-b18f-4af29e17de25
* Version Independent ID: 890c06d6-7b65-455f-95df-e71eba36494e
* Content: [Define subjects to categorize cases, products, and articles - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/define-subjects-categorize-cases-products-articles)
* Content Source: [power-platform/admin/define-subjects-categorize-cases-products-articles.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/define-subjects-categorize-cases-products-articles.md)
* Service: **power-platform**
* GitHub Login: @shubhadaj
* Microsoft Alias: **shujoshi**

**Comment by sing-ideas** [comment]
Title = Define subjects to "categorize" cases, products, and articles.

As D365 Service is having 2 features Subject and Categories, using the word categorize is overlapping our training process to our staffs.

Kindly define is real use of Subject and Category feature.

regards,
Singaravelu S

**Comment by neeranelli** [comment]
@sing-ideas,

I apologize for not responding to your suggestion earlier than today. I am looking into updating the reference to "category" with an alternative term.

As of now, I haven't heard about deprecation of "Subject". It's a supported feature that recently had some enhancements as well. More information: [Enable search control for subjects in custom forms](https://docs.microsoft.com/dynamics365/customer-service/search-control-for-subjects)

Please let me know if you have more questions.

Thank you.

**Comment by sing-ideas** [comment]
Hi,
Thanks for the reply, if possible, can you tell us which feature came first...
1. Subject or 2. Category
What problem D365 engineers tried to solve with these 2 features?

**Comment by KendalBond007** [comment]
Closing this issue because it has been open for over 3 years. The linked document was last updated 14 Feb 2022. If you're still experiencing the issue described here, please reopen or create a new issue.
