### ISSUE TITLE
Dynamics 365: Manage Roles for Apps

### ISSUE THREAD

**Issue by justinreading** [MicrosoftDocs/power-platform#162]
Could you please provide details on how we will be able to "Manage Roles" for Dynamics 365 Apps when this change occurs? We currently click the elipsis on the app shown on d365environment/apps to manage the roles of Dynamics users to control visibility of the app for users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a027bf-62d9-07f6-c15c-fc0e4d5b8686
* Version Independent ID: f88d00be-be73-a187-c287-66f151073abb
* Content: [Quickly navigate with the Office 365 app launcher and the Dynamics 365 home page - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/quickly-navigate-office-365-app-launcher#feedback)
* Content Source: [power-platform/admin/quickly-navigate-office-365-app-launcher.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/quickly-navigate-office-365-app-launcher.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by LinnZawWin** [comment]
@justinreading You still should be able to do it from the "My Apps" page in the classic Settings page.
But that is confusing for not being able to Enable Security Roles for the model-driven apps from the solution explorer just like Forms, Dashboard, etc.
![My Apps](https://user-images.githubusercontent.com/14156926/81988492-aae75b00-968f-11ea-9e09-fb6f3f9a9f0f.png)

**Comment by jimholtz** [comment]
@justinreading 
Sorry for the delayed response. Please see: https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/share-model-driven-app#assign-security-roles-to-users
