### ISSUE TITLE
Issue installing the profiler in the Plugin Registration Tool

### ISSUE THREAD

**Issue by U2UTrainer** [MicrosoftDocs/power-platform#1620]
Hi,

When I try to use _pac tool prt_ to install and launch the PRT I get an error installing the Profiler. The error message is:
Unhandled Exception: System.InvalidOperationException: Unable to locate the "PluginProfiler.Solution.zip" file. Make sure that it is in the same directory as the PluginProfiler.Library.dll assembly.

When I install the PRT using the Nuget package this issue does not occur and the Profiler can be successfully installed in the environment.

Jurgen

**Comment by phecke** [comment]
@U2UTrainer I will check on that. What version of PAC CLI are you using?

**Comment by phecke** [comment]
@U2UTrainer I uninstalled and then tried to install the profiler. I got an exception.

I will let the product team know. Thanks

@kkanakas I am running CLI version 9.1.0.167. I was not able to install the profiler.

Unhandled Exception: System.InvalidOperationException: Unable to locate the "PluginProfiler.Solution.zip" file. Make sure that it is in the same directory as the PluginProfiler.Library.dll assembly.

**Comment by kkanakas** [comment]
@U2UTrainer, can please raise a ticket with Microsoft support and provide the logs as well, it will help us identify the issue better.  The log for Pac CLI are located   (windows command line) 
 C:\Users\<username>\AppData\Local\Microsoft\PowerAppsCli\Microsoft.PowerApps.CLI.1.21.4\tools\logs
inside vs code 
C:\Users\<username>\AppData\Roaming\Code\User\globalStorage\microsoft-isvexptools.powerplatform-vscode\pac\tools\logs

Thanks

**Comment by fordosa90** [comment]
@kkanakas @phecke Is there any update available on this?
I am running pac version 1.21.5 and the command "pac tool prt"
I am facing the exact same issue and error message as in original topic
![image](https://user-images.githubusercontent.com/36542387/213006867-8f4c4fb9-b0bd-4473-99c8-6a4fff30955b.png)

**Comment by phecke** [comment]
@U2UTrainer You will have to log a support request. We handle documentation feedback here.
