### ISSUE TITLE
App name incorrect

### ISSUE THREAD

**Issue by RebekkaAalbers** [MicrosoftDocs/power-platform#1625]
Section 'Share apps with admins and makers'
The Environment Request App is actually called 'Maker - Environment Request'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c1223b3-ffe0-3f45-b537-f712cf21e5ea
* Version Independent ID: 4c1223b3-ffe0-3f45-b537-f712cf21e5ea
* Content: [Set up environment request components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-environment-components)
* Content Source: [power-platform/guidance/coe/setup-environment-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-environment-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you! Fixed locally ready for our next docs release!

**Comment by bishalgoswami** [comment]
Thanks for your comment, @RebekkaAalbers. This issue has been assigned to the doc author for review.
