### ISSUE TITLE
Link to PDF is dead

### ISSUE THREAD

**Issue by mattmblackmore** [MicrosoftDocs/power-platform#1627]
The following link on this page seems to be dead and no longer works:

https://download.microsoft.com/download/E/D/0/ED05CA70-190F-4BAE-9F6A-0BB2F0010B81/Setup%20Guide%20Server-side%20synchronization%20for%20CRM%20Online%20and%20Exchange%20Server.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 611b02d6-4bb1-2fa9-e35e-5cc65350562f
* Version Independent ID: 1f6d4023-fed8-7f86-9911-33c65993624a
* Content: [Use email message filtering and correlation to specify which emails are tracked - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/email-message-filtering-correlation)
* Content Source: [power-platform/admin/email-message-filtering-correlation.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/email-message-filtering-correlation.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by KumarVivek** [comment]
@mattmblackmore I just checked the link, and it works. Clicking on the link prompts you to download a PDF file and depending on your browser download settings, the file might be getting automatically downloaded to your PC.
