### ISSUE TITLE
Blank Power Automate Input Variables table 

### ISSUE THREAD

**Issue by BPPGitHubAdmin** [MicrosoftDocs/power-platform#1628]
Hi

It seems that all titles inside the power automate variable inputs are gone. 
I don't know where to input the different values. 
![image](https://user-images.githubusercontent.com/101800991/204478267-c2fa7c6b-725c-4f87-a30d-1d2b1d9e9c79.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e88f289-b527-30ab-a2b5-a27d98745516
* Version Independent ID: 4fffa137-7df2-546c-988e-fa7ddf1028b5
* Content: [Microsoft Power Platform Center of Excellence Kit - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/starter-kit)
* Content Source: [power-platform/guidance/coe/starter-kit.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/starter-kit.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BPPGitHubAdmin. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Hello,

as this happens before install of the CoE kit, it's unrelated to the CoE kit solution itself and likely a product/platform issue. We have sometimes seen this in an environment where English wasn't installed as a language. If your problem persists, I recommend raising a ticket with Microsoft Support https://learn.microsoft.com/en-us/power-platform/admin/get-help-support
