### ISSUE TITLE
Get-AdminFlow + Flows imported as disabled

### ISSUE THREAD

**Issue by davcano** [MicrosoftDocs/power-platform#1629]
Hello.

I'm facing the same issue as this one: https://github.com/MicrosoftDocs/power-platform/issues/687.
May be weirder than this, because I did a deployment yesterday, all my flows were disabled and impossible to retrieve them with the Get-AdminFlow on the moment.
But this morning, my flows are still disabled but I can retrieve them with the Get-AdminFlow command...

Can anyone help us on this?

Best regardes

**Comment by davcano** [comment]
Update: I did a new test, and after importing of my solution, Flows are retrieved by the Get-AdminFlow after 50 minutes... Do we have official delay by Microsoft on this?

**Comment by KumarVivek** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerautomate.microsoft.com/en-us/support/>
