### ISSUE TITLE
Clarification regarding who needs Power Automate license

### ISSUE THREAD

**Issue by mblennegard** [MicrosoftDocs/power-platform#163]
In the section about Power Automate and the question:

> Do users who run flows need to be licensed, or do only users who create flows need to be licensed?
> Any end user running a flow will need to be licensed either by the per user or per Power Automate plans.

You mention:

> There are features in Power Automate that are not running a flow directly, such as responding to an approval request or advancing a stage in a business process. These features are built on the Common Data Service. Normally, any use of these features requires either a standalone Power Automate per user plan, or, that the flow that creates these business process environments or approval requests to be licensed under the per flow plan.

If we have a Flow containing Premium connectors, as well as the built-in Flow Approval, do the users who are only part of the actual Flow Approval process (these users cannot trigger the actual Flow) need Premium licenses for Power Automate?
Or is it only the users who can actually trigger/run the Flow, as well as the users who can edit the Flow, who needs Premium license for Power Automate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#feedback)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@mblennegard 
Sorry for the delayed response. I'm not getting any info from the product time on this issue. Please try contacting:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
