### ISSUE TITLE
Not able to install Power Platform CLI on Linux (Ubuntu 22.04)

### ISSUE THREAD

**Issue by sunilbsharma** [MicrosoftDocs/power-platform#1632]
Hi Team,

We want to configure a Jenkins CICD for our power platform. Jenkins is installed on Linux Server (Ubunto 22.04).
We referred this article for installing the power platform cli -  (https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Pac-linux/m-p/1744332#M6738)
We tried this approach for macOS and Windows it worked. 
However we have run into issue for Linux.
we run the commands as below
chmod +x pac
./pac
and then we get following error

A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/[username]/TEMP/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet].
The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.22.04-x64&apphost_version=6.0.6
  
Following are the steps we did on linux server.
1. installed the .Net 6.0
2. installed vscode
3. installed the Power Platform Tools extension
4. extracted the nupkg file
5. Tried to run with chmod +x pac
6. We get error message as shown above.

Please help us resolve this issue as its critical for us have this installation done for Jenkins to run pac commands.

Thanks.

**Comment by JimDaly** [comment]
@sunilbsharma 

I'm sorry to hear you are experiencing this issue. 

This repository is for the PAC CLI documentation. We accept issues where people have feedback for the documentation. I don't see any comments about the documentation in this issue. This looks like a request for technical support. We don't have the resources to respond to technical support requests. 

I see you have also raised this in the forum. That is also a good idea. But if this is critical, I recommend you contact Microsoft Support to get a resolution for this issue. 

I'm going to close this issue.
