### ISSUE TITLE
It possible to install via CLI

### ISSUE THREAD

**Issue by BrianZhangLarsen** [MicrosoftDocs/power-platform#1636]
![image](https://user-images.githubusercontent.com/32098751/205312288-38272700-83ca-4196-8da8-cabcc911376c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a869972-ce34-c5c9-c591-fd25347181c1
* Version Independent ID: 9a869972-ce34-c5c9-c591-fd25347181c1
* Content: [Set up the Creator Kit - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/setup)
* Content Source: [power-platform/guidance/creator-kit/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/creator-kit/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BrianZhangLarsen. This issue has been assigned to the doc author for review.
