### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/power-platform#1639]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bae1ecd0-a13c-440d-f536-e79c38c79f05
* Version Independent ID: bae1ecd0-a13c-440d-f536-e79c38c79f05
* Content: [Operators and Identifiers in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/operators)
* Content Source: [power-platform/power-fx/reference/operators.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/operators.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by HandyAndyOnGitHub** [comment]
Should this sentence: "Although it isn't suggested, we could also use the logical name for this field. This will result in the same data being retrieved. Single quotes are required since this name doesn't contain spaces or special characters:" 

Instead be: "Although it isn't suggested, we could also use the logical name for this field. This will result in the same data being retrieved. Single quotes are **NOT** required since this name doesn't contain spaces or special characters:"?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @HandyAndyOnGitHub. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
@tapanm-MSFT This indeed looks like a typo. However I wanted to fix it but our repo seems to already have a fixed version of this? i.e. the git repo does not have the same text as the public doc?

**Comment by mduelae** [comment]
@HandyAndyOnGitHub - Thank you for the feedback. The typo has been fixed.

Thanks,
Mints

**Comment by HandyAndyOnGitHub** [comment]
Magic! Thanks :)
Andy
