### ISSUE TITLE
Marketing app  does not support G2G

### ISSUE THREAD

**Issue by HelioFerreira** [MicrosoftDocs/power-platform#164]
The Marketing app does not support G2G

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029aa7d3-e3e1-f99a-3f71-e11e998cb543
* Version Independent ID: 3d87af00-dcfd-697c-87df-3990a4cc8027
* Content: [Geo to geo migrations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/geo-to-geo-migrations#feedback)
* Content Source: [power-platform/admin/geo-to-geo-migrations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/geo-to-geo-migrations.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by alfergus** [comment]
You are correct, the Marketing app does not support Geo to Geo migration. See: https://docs.microsoft.com/en-us/dynamics365/admin/move-instance-tenant
