### ISSUE TITLE
Link doesnt work

### ISSUE THREAD

**Issue by donsvensen** [MicrosoftDocs/power-platform#1642]
The link to the component's github repository doesnt work

https://github.com/microsoft/powercat-creator-kit/tree/main/CreatorKitCore/SolutionPackage/CanvasApps/cat_powercatcomponentlibrary_0be3a_DocumentUri_msapp_src

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1346323-c9a3-5c4e-d4d2-32080de5b27f
* Version Independent ID: f1346323-c9a3-5c4e-d4d2-32080de5b27f
* Content: [Panel control reference (experimental) - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/panel)
* Content Source: [power-platform/guidance/creator-kit/panel.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/creator-kit/panel.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @donsvensen. This issue has been assigned to the doc author for review.

**Comment by denisem-msft** [comment]
This has been fixed. Thank you for your feedback.
