### ISSUE TITLE
Powerplatform communication site template failing to download

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/power-platform#1646]
https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/adoption/wiki-community.md#download-the-assets

link pointed to download: https://aka.ms/pphub-download

is failing with defender virus scan and getting deleted/archived.. Microsoft needs to fix this

**Comment by manuelap-msft** [comment]
This would be due to a policy on what files you can download by your organisation. The .zip contains PowerShell scripts - perhaps your organisation has blocked that from being downloaded. There's nothing we can do to address that.
