### ISSUE TITLE
Clarification Needed: Does Data Export Service Supports Azure SQL Data Warehouse /Azure Synapse

### ISSUE THREAD

**Issue by msjammu** [MicrosoftDocs/power-platform#165]
My team is building a Data Warehouse and we need data exported in it from CRM. Does Data Export Service Supports Azure SQL Data Warehouse /Azure Synapse as destination? I tried to set up a pull and it fails so confirming if this is failing due to lack of support?

Here is what current  documentation says:
From https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/data-export-service

Data Export is an add-on service made available as a Common Data Service solution that adds the ability to replicate Common Data Service data to a Microsoft Azure SQL Database store in a customer-owned Microsoft Azure subscription. T**he supported target destinations are Microsoft Azure SQL Database and Microsoft Azure SQL Server on Microsoft Azure virtual machines.**

Please confirm if this lacks support for Data Warehouse or its just an out of date doc?

**Comment by jimholtz** [comment]
@msjammu 
The newer ability Export to data lake exports CDS data to the lake in CDM format which can then be consumed by several consumers including Power BI, ADW and Azure Synapse. See: https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake
