### ISSUE TITLE
Insufficient explanation of parameters

### ISSUE THREAD

**Issue by JohnDoeKyrgyz** [MicrosoftDocs/power-platform#1651]
I am trying to use the pac cli to push a nuget package to Dataverse. I have no idea what value to use for the pluginId parameter. This parameter is required. NuGet packages are not referenced as components in the Solution.xml file, so there is no obvious id value associated with the plugin package.

This documentation would be more useful if it defined some of these terms and included examples of the commands to run to perform these types of tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 74585e68-ead5-b753-5dd1-de6de8b69719
* Version Independent ID: 74585e68-ead5-b753-5dd1-de6de8b69719
* Content: [Microsoft Power Platform CLI plugin command group - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/plugin)
* Content Source: [power-platform/developer/cli/reference/plugin.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/reference/plugin.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by JimDaly** [comment]
@JohnDoeKyrgyz 
I'm assuming that you are wanting to use the [Dependent Assembly plug-ins (preview)](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dependent-assembly-plugins) feature with [pac plugin push](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/plugin#pac-plugin-push)?

Can you confirm this is what you expect?

I don't think we have tested that command with plug-in packages yet. But I see the description of the required parameter does say "Id of plug-in assembly or plug-in package". 

Perhaps including plug-in package in that description is premature at this point.

**Comment by kkanakas** [comment]
You plugin id is what you get when you register the plugin in Dataverse first. This tool is not a replacement for the PRT but if you already have a plugin you can update it, once you have modified the code.




Kartik (He/Him)
I work in Seattle Time (Pacific Time).My working hours may not be your working hours. Please do not feel obligated to respond outside of your normal work hours.

From: John Atwood ***@***.***>
Sent: Friday, December 9, 2022 12:38 PM
To: MicrosoftDocs/power-platform ***@***.***>
Cc: Kartik Kanakasabesan (HE/HIM) ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/power-platform] Insufficient explanation of parameters (Issue #1651)


I am trying to use the pac cli to push a nuget package to Dataverse. I have no idea what value to use for the pluginId parameter. This parameter is required. NuGet packages are not referenced as components in the Solution.xml file, so there is no obvious id value associated with the plugin package.

This documentation would be more useful if it defined some of these terms and included examples of the commands to run to perform these types of tasks.

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 74585e68-ead5-b753-5dd1-de6de8b69719
  *   Version Independent ID: 74585e68-ead5-b753-5dd1-de6de8b69719
  *   Content: Microsoft Power Platform CLI plugin command group - Power Platform<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpower-platform%2Fdeveloper%2Fcli%2Freference%2Fplugin&data=05%7C01%7Ckartikka%40microsoft.com%7C0dbeed720b0e440d1f8208dada25522e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638062151082547321%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9gm2Vbo7TTBZMte0ImlDlqu2ZO%2FURdZxXHywkOfl3ZQ%3D&reserved=0>
  *   Content Source: power-platform/developer/cli/reference/plugin.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpower-platform%2Fblob%2Fmain%2Fpower-platform%2Fdeveloper%2Fcli%2Freference%2Fplugin.md&data=05%7C01%7Ckartikka%40microsoft.com%7C0dbeed720b0e440d1f8208dada25522e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638062151082547321%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=m%2Fn8xeGUy4EO6IxxJAgX3U7U2U1RqnZwThOmUZ7QRt4%3D&reserved=0>
  *   Service: power-platform
  *   Sub-service: developer
  *   GitHub Login: @kkanakas<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkkanakas&data=05%7C01%7Ckartikka%40microsoft.com%7C0dbeed720b0e440d1f8208dada25522e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638062151082547321%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kDdaq%2Bsk0deRIfT4XSXzfKdApd0DDljGfW6aOg3kyOY%3D&reserved=0>
  *   Microsoft Alias: kartikka

**Comment by kkanakas** [comment]
First things first, the pac plugin push is not a replacement for PRT. When you register a plugin in PRT, you have the plugin id provided there. Once you have the plugin id from PRT the command syntax is straight forward 
pac plugin push -id <id of the plugin, as obtained from PRT> -pf myfavorite.nupkg  and that should do it.

**Comment by JohnDoeKyrgyz** [comment]
Thanks for the hint @kkanakas. Using the Id of the plugin package obtained from the PRT or the pluginpackages entity is what it needed. The documentation would be better if it included a few sentences about where to find this id. Maybe even add a picture or two.

**Comment by JimDaly** [comment]
We need some examples and notes for [pac plugin commands](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/plugin) as well as incorporating this in the core [plug-in content](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/write-plug-in) and [tutorials](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/tutorial-write-plug-in)

This is a known gap we are working on, so closing this.
