### ISSUE TITLE
"Video hub - admin" is now "Nurture apps - Admin"

### ISSUE THREAD

**Issue by davins-msft** [MicrosoftDocs/power-platform#1654]
[Enter feedback here]
The Model driven app is no longer **Video hub - admin**. The Nurture solution version 2.19 has the App name of **Nurture apps - Admin**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a52f603f-2e0d-b02b-4a51-de16511e79dd
* Version Independent ID: 5b0aa787-c4a4-423b-9504-80fa375a04ba
* Content: [Nurture components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/nurture-components)
* Content Source: [power-platform/guidance/coe/nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @davins-msft. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
fixed locally, ready for next docs update
