### ISSUE TITLE
Security Role assignment to **Video hub** and **Nurture apps - admin** apps

### ISSUE THREAD

**Issue by davins-msft** [MicrosoftDocs/power-platform#1656]
(https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#share-apps-with-admins-and-makers)
The documentation mentions the following:
[Video hub - admin](https://learn.microsoft.com/en-us/power-platform/guidance/coe/nurture-components#video-hub---admin) app to manage content, playlists and comments. Share this app with other admins, and assign them the **Power Platform SR** security role.
[Video hub](https://learn.microsoft.com/en-us/power-platform/guidance/coe/nurture-components#video-hub) canvas app for video content. Share this app with your makers and assign them the **Power Platform SR** security role.
---

Shouldn't the Apps be shared with the corresponding security roles of **Nurture Admin SR** and **Nurture Maker SR** instead of **Power Platform SR**?
The **Video hub** canvas app shared with the **Nurture Maker SR** role and **Nurture apps - admin** model driven app with the **Nurture Admin SR** role?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fc749-2ecd-61d7-4146-16fe1a373848
* Version Independent ID: fcd148f1-795e-a99c-e2e9-da06e1129d3c
* Content: [How to set up nurture components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components)
* Content Source: [power-platform/guidance/coe/setup-nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @davins-msft. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
fixed locally, ready for the next release
