### ISSUE TITLE
microsoftxrmonlinemanagementapi link is bad.

### ISSUE THREAD

**Issue by OranguTech** [MicrosoftDocs/power-platform#1657]
[Enter feedback here]
Link under https://learn.microsoft.com/en-us/power-platform/alm/powershell-api#microsoftxrmonlinemanagementapi (https://learn.microsoft.com/en-us/powershell/powerapps/get-started-onlinemanagementap) is a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f108b474-2f9c-4b76-3d0f-e85bf77985ed
* Version Independent ID: 9627f1f9-82c5-49c8-5506-d3e09b977673
* Content: [Manage solutions using PowerShell - Power Platform](https://learn.microsoft.com/en-us/power-platform/alm/powershell-api)
* Content Source: [power-platform/alm/powershell-api.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/powershell-api.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment]
@OranguTech The Online Management API has been deprecated, and removed from the documentation. I will update the PowerShell topic.

There is a new admin REST API available here: [Microsoft Power Platform API reference](https://learn.microsoft.com/en-us/rest/api/power-platform/)
