### ISSUE TITLE
No examples of the "In Operator"

### ISSUE THREAD

**Issue by victorsj1** [MicrosoftDocs/power-platform#1659]
[Enter feedback here]

This article's title points out the "In" operator but there are no given examples.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bae1ecd0-a13c-440d-f536-e79c38c79f05
* Version Independent ID: bae1ecd0-a13c-440d-f536-e79c38c79f05
* Content: [Operators and Identifiers in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/operators)
* Content Source: [power-platform/power-fx/reference/operators.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/operators.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @victorsj1. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
There are multiple examples of "In" and "ExactIn" in this docs article.
