### ISSUE TITLE
premium connectors

### ISSUE THREAD

**Issue by MariusWeiss** [MicrosoftDocs/power-platform#166]
is there a list with all the premium connectors? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Licensing overview - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@MariusWeiss 
You can see the list here:
https://preview.flow.microsoft.com/en-us/connectors/?filter=&category=premium
