### ISSUE TITLE
[ALM using power platform build tool] what's the required permission for the Azure app registration

### ISSUE THREAD

**Issue by CDSSYW** [MicrosoftDocs/power-platform#1661]
What's the required permissions for this Azure app registration if I use the PP build tool to run ALM? 
I checked MS doc [[Microsoft Power Platform Build Tools for Azure DevOps - Power Platform | Microsoft Learn](https://learn.microsoft.com/en-us/power-platform/alm/devops-build-tools)](https://learn.microsoft.com/en-us/power-platform/alm/devops-build-tools) and [Use single-tenant server-to-server authentication (Microsoft Dataverse) - Power Apps | Microsoft Lea...](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-single-tenant-server-server-authentication#azure-application-registration) but it's not clearly documented at MSFT which permissions are required...is it only require Dynamics CRM permission, or should also include DevOps, PowerApps Runtime Service, and PowerApps-Advisor (Analysis All) permissions??

Also ,to run the ALM pipeline using power platform build tool,  is it required to create separate app registration for different power platfrom environment? or it's sufficient to register only one app at azure, add this app at different environments, and create different service connections at DevOps ?

**Comment by phecke** [comment]
@CDSSYW There is documentation on required permissions for Azure app registration here: [prerequisites](https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#prerequisites)

App registration should be good for all environments in the same tenant.

**Comment by kkanakas** [comment]
@CDSSYW, it is a matter of best practices, You can use the same service principal to deploy from dev to test and from test to production.  For those that are security conscious, such as myself, I use different service principals for different environments that I am deploying to, as in dev to test is a different SPN and Test to Production is a different SPN. But it is a matter what works for your organization. when creating a service principal, unless you are using managed identities, you do not need to call out Azure DevOps.  When you create an SPN using this script 
https://learn.microsoft.com/en-us/power-platform/alm/devops-build-tools#create-service-principal-and-client-secret-using-powershell

it creates an SPN with Azure and then adds the SPN as an application user in a target environment. If you create an environment using an SPN via CI/CD then the SPN is the owner of the newly created environment. 


<img width="1063" alt="image" src="https://user-images.githubusercontent.com/22942069/210421183-3fb75140-4235-4a25-b7d2-555d49668469.png">

**Comment by phecke** [comment]
@CDSSYW Thanks for the feedback
