### ISSUE TITLE
Can't see Video Hub- Admin App on actually Install

### ISSUE THREAD

**Issue by PPMini** [MicrosoftDocs/power-platform#1662]
I believe the Video Hub- Admin App is the Nurture apps - Admin 
<img width="318" alt="image" src="https://user-images.githubusercontent.com/112712553/207659196-ec953948-40b7-4090-ac63-f2dc28287a41.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fc749-2ecd-61d7-4146-16fe1a373848
* Version Independent ID: fcd148f1-795e-a99c-e2e9-da06e1129d3c
* Content: [How to set up nurture components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components)
* Content Source: [power-platform/guidance/coe/setup-nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-nurture-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PPMini. This issue has been assigned to the doc author for review.
