### ISSUE TITLE
Creator Kit Link is Broken

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1663]
The links to the Creator Kit are broken:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-creator-kit

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rrwolfe. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
PR to fix this is already open, awaiting final change and then approval #1687
