### ISSUE TITLE
404 Error upon clicking the link

### ISSUE THREAD

**Issue by davins-msft** [MicrosoftDocs/power-platform#1667]
![image](https://user-images.githubusercontent.com/91287781/208204655-b4d0b4c7-6362-4c60-ba6c-811a4f948653.png)
404 Error upon clicking the link

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f108b474-2f9c-4b76-3d0f-e85bf77985ed
* Version Independent ID: 9627f1f9-82c5-49c8-5506-d3e09b977673
* Content: [Manage solutions using PowerShell - Power Platform](https://learn.microsoft.com/en-us/power-platform/alm/powershell-api#microsoftxrmonlinemanagementapi)
* Content Source: [power-platform/alm/powershell-api.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/powershell-api.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by Mattp123** [comment]
@davins-msft - Thank you for your feedback. Since that PowerShell module has been deprecated, the article has been updated to remove the mention of it (along with the link). 
Closing issue.
