### ISSUE TITLE
Power platform 

### ISSUE THREAD

**Issue by Neowise01** [MicrosoftDocs/power-platform#1669]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9eadb9e2-bc3a-25e6-ec3d-e85e1f404405
* Version Independent ID: 5b70c7ac-bce9-36ec-09ce-c9291c1744e0
* Content: [Administer Power Platform - Power Platform](https://learn.microsoft.com/en-au/power-platform/admin/admin-documentation#home-page-dashboard)
* Content Source: [power-platform/admin/admin-documentation.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/admin-documentation.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by JimDaly** [comment]
Issues reported against the documentation must include some specific feedback to be actionable, preferably relating to a specific topic.
