### ISSUE TITLE
Audit History Privilege

### ISSUE THREAD

**Issue by AbdulWahabWarind** [MicrosoftDocs/power-platform#167]
I want to grant privilege to the user to see audit histories for the entities on which he has access. Can you please specify the privilege need to view audit history? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837f9db7-667d-814f-1df6-98e2f89a44cc
* Version Independent ID: f53ea984-3798-d3fb-ec0c-d31f81db9250
* Content: [Audit data and user activity for security and compliance - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity)
* Content Source: [power-platform/admin/audit-data-user-activity.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/audit-data-user-activity.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@AbdulWahabWarind 
By default users have access to the audit history of records they can access, so they can see the change history.
![audit-history](https://user-images.githubusercontent.com/19712577/82952837-93955100-9f5e-11ea-9fa6-502cf85a3396.png)

There is no role or permission that the admin needs to set.
