### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ivanange** [MicrosoftDocs/power-platform#1672]
[Enter feedback here]
On the line
[Error](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-iferror) – Create a custom error or pass throguh an error.

throguh  -> through 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4db6d199-e58a-d817-6da3-66fbfacef44b
* Version Independent ID: 4db6d199-e58a-d817-6da3-66fbfacef44b
* Content: [Power Fx formula reference for Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/formula-reference#s)
* Content Source: [power-platform/power-fx/formula-reference.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/formula-reference.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ivanange. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed and the changes will be visible soon.
