### ISSUE TITLE
Optimisation / simplification of a code example.

### ISSUE THREAD

**Issue by DS1060** [MicrosoftDocs/power-platform#1677]
On the trim part,

Instead of using:
Left( Concat( Products, Name & ", " ), Len( Concat( Products, Name & ", " ) ) - 2 )

I prefer to avoid evaluating the concat twice and put the ", " at the begining and use "mid" to ignore the first 2 characters.

Mid( Concat( ", " & Products, Name ),3 )
(Start at character 3, third parameter is optional so it take the rest of the string)

I believe this is a performance improvement, as small as it could be, it is still an improvement.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebedb7a-b3af-3ad9-cc70-ca29a9410047
* Version Independent ID: 1ebedb7a-b3af-3ad9-cc70-ca29a9410047
* Content: [Concat and Concatenate functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-concatenate)
* Content Source: [power-platform/power-fx/reference/function-concatenate.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-concatenate.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DS1060. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@jorisdg assigning this to you.

**Comment by jorisdg** [comment]
In fact, this example is entirely fiction and I will work on rewriting it. It's pointless to include a hardcoded separator since the Concat() function accepts an optional third parameter to specify a separator, which avoids this whole conundrum...

Just do: Concat( Products, Name, ", " )

**Comment by mduelae** [comment]
@DS1060 We have corrected the information and updated the topic: https://learn.microsoft.com/power-platform/power-fx/reference/function-concatenate. 

Thank you,
Mints
