### ISSUE TITLE
"pac admin list" doesn't list all environments (Default is excluded from that list)

### ISSUE THREAD

**Issue by davins-msft** [MicrosoftDocs/power-platform#1678]
![image](https://user-images.githubusercontent.com/91287781/209401267-073fc2ce-7d7e-43c0-92b8-3cbc76881c6b.png)

The command doesn't list the Default environment, so can that be explicitly called out - "All environments except Default."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 488078c6-838d-1722-114e-4eb64d94aa0d
* Version Independent ID: 488078c6-838d-1722-114e-4eb64d94aa0d
* Content: [Microsoft Power Platform CLI admin command group - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/admin)
* Content Source: [power-platform/developer/cli/reference/admin.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/reference/admin.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @davins-msft. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@davins-msft 
When I run this command in an environment where I am the tenant administrator, I see the Default environment.

Are you running this against the Microsoft Tenant? Are you the tenant administrator?

@kkanakas, depending on what @davins-msft  response is, it looks like there could be opportunity to improve the description here. It seems like there may be some filtering that is applied based on some other factors?

**Comment by davins-msft** [comment]
@JimDaly @kkanakas: It is a tenant created from CDX (https://cdx.transform.microsoft.com/)
The environments view (in ppac) by logging in as Global Administrator (MOD Administrator).
![image](https://user-images.githubusercontent.com/91287781/212377135-61f5ffe4-bf42-46d9-8cd6-af15fa761004.png)
 
The auth profile created for CLI is of **MOD Administrator** who is Global Administrator. 

The default environment doesn't get listed below:
![image](https://user-images.githubusercontent.com/91287781/212376324-a00d3514-381f-4bc2-9586-44986a31dcd1.png)

**Comment by JimDaly** [comment]
@davins-msft  
Let's take this offline.
