### ISSUE TITLE
IsBlank returns false when IsEmpty is true

### ISSUE THREAD

**Issue by agbeaton** [MicrosoftDocs/power-platform#1683]
The documentation here incorrectly states that IsBlank tests for null or empty values.  
IsBlank(cbo_MyField.SelectedItems) is returning false when IsEmpty(cbo_MyField.SelectedItems) is returning true. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a0ff904-ed1a-c723-ff0b-905b0280b22c
* Version Independent ID: 2a0ff904-ed1a-c723-ff0b-905b0280b22c
* Content: [Blank, Coalesce, IsBlank, and IsEmpty functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-isblank-isempty)
* Content Source: [power-platform/power-fx/reference/function-isblank-isempty.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-isblank-isempty.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @agbeaton. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@jorisdg waiting on your reply.

**Comment by jorisdg** [comment]
I'm updating the IsBlank documentation to explicitly mention that empty tables are not considered blank, and IsEmpty should be used instead.

**Comment by agbeaton** [comment]
Thanks for that clarification! Should we be able to use IsBlank(IsBlank(cbo_MyField.SelectedItems.**Name**) and have that work?

Adam

**Comment by jorisdg** [comment]
Can you clarify what cbo_MyField and SelectedItems are? If SelectedItems is a table, I'm not sure what the Name is? Not without selecting a record from the table? In general if Name is a string field IsBlank will return true if it's blank() or an empty string ( "" ).

**Comment by agbeaton** [comment]
cbo_MyField is a combobox control.  I'm trying to filter records from a table based the selected value in a combobox... when it isn't empty or blank.  "Name" would be the name of a specific column in the table being used to populate the combobox.

**Comment by jorisdg** [comment]
Sorry for the late response. Yeah sounds lik you need to use IsEmpty for SelectedItems. Looks like the small doc update hasn't gone out, I will follow up on that.
