### ISSUE TITLE
eMail Header Style is a required environment variable

### ISSUE THREAD

**Issue by maheshau1** [MicrosoftDocs/power-platform#169]
eMail Header Style is a required environment variable in CoE - Compliance and Report Components and default values are not provided. 

I used email header style values from this document: https://stevemordue.com/wp-content/uploads/CoE-Starter-Kit-Documentation-and-Setup-Instructions.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14181d4-574f-95e3-c2c9-545116549c9b
* Version Independent ID: bf449b92-6756-e08a-a58c-d561e36947cb
* Content: [Set up governance components - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#feedback)
* Content Source: [power-platform/guidance/coe/setup-governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-governance-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you for pointing that out, we have added the Default Value to the documentation as well, it's linked to from 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables
