### ISSUE TITLE
Typo...

### ISSUE THREAD

**Issue by cjkhan4** [MicrosoftDocs/power-platform#1691]
Text copied from page, last section:

### Backup and restore of default environment
Like every other environment type (sandbox, production, developer), the default environment also gets archived. However, there's no manual backup that you can request for the default environment. Like any other environment, a restore operation is possible and requires you to **content** Microsoft Support. Be aware that when you restore the default environment, you need to consider you might also be restoring all the unused or abandoned apps and flows that were removed after the cleanup.

I think the author meant **contact**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c36038a8-28f7-cb20-dc2c-caa3186b9aba
* Version Independent ID: c36038a8-28f7-cb20-dc2c-caa3186b9aba
* Content: [Manage the Power Platform default environment - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/adoption/manage-default-environment)
* Content Source: [power-platform/guidance/adoption/manage-default-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/adoption/manage-default-environment.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @rranjit83
* Microsoft Alias: **rranjit**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @cjkhan4. This issue has been assigned to the doc author for review.

**Comment by ProfessorKendrick** [comment]
Thanks for identifying this typo.  It has been corrected in the documentation. Closing the issue.
