### ISSUE TITLE
Where can I find 2023 Release Wave 1?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/power-platform#1696]
This article mentions "Model-driven app controls deprecation (2023 Release Wave 1)" and "With the upcoming 2023 release wave 1 (public preview in February 2023 and GA in April 2023)".
 
Where can I find the documentation about 2023 Release Wave 1? I'm not able to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps and Power Automate - Power Platform](https://learn.microsoft.com/en-us/power-platform/important-changes-coming)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/important-changes-coming.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. 2023 wave 1 release plan is not yet published. Documentation has been updated since this issue was submitted, hence closing this issue for now.
