### ISSUE TITLE
Incorrect: "Removing a security group from an environment is currently not supported"

### ISSUE THREAD

**Issue by marcuss75** [MicrosoftDocs/power-platform#17]
In the first paragraph, the sentence "Removing a security group from an environment is currently not supported." is not correct, because the security group can be removed.

- From "Admin Center", in the page "Details" of the environment, you can click on "edit"

- In the "Settings" page, click on "Edit Security Group" pencil

- In the "Edit Security Group", don't select any Security Role and click on "Done" button

- In the "Settings" page, click on "Save" button

In this way you can remove a Security Group associated to an instance

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform Admin center](https://docs.microsoft.com/it-it/power-platform/admin/control-user-access#associate-a-security-group-with-a-common-data-service-environment)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@marcuss75 
Thanks for bringing this to our attention. Topic has been updated.

**Comment by stevenfayers** [comment]
@jimholtz @marcuss75 I have found that this doesn't work. Although the steps above look like they remove the securty group, after saving, refresh the page and the security group is not removed.  There should be a way to remove a security group.

**Comment by deepalakhani** [comment]
Has this been resolved.  Is it possible to remove the security group now?

**Comment by ijqh** [comment]
I can successfully delete a security group that is assigned to a Dataverse environment however I cannot assign a new group. The selection of groups in the edit panel is not fully available and the search feature doesn't work. I can't manually type in the name of the group nor can I find a powershell script to assign a new security group to the environment. Any ideas?
