### ISSUE TITLE
Power virtual agents preview - Adaptive Cards Buttons are not working

### ISSUE THREAD

**Issue by sanketdixit2013** [MicrosoftDocs/power-platform#1700]
When we add an adaptive card json in the power virtual agent unified canvas/preview. The adaptive card is displayed as expected as shown below.
![image](https://user-images.githubusercontent.com/62757731/211507408-af051d09-ce32-4e65-a885-5c42bbbf6f4a.png)

However when we try to capture the button selection done using the post back adaptive card action, we are unable to capture the user's response. This can be done in composer using the **activity.value**.  But in the power virtual agents unified canvas when we add the adaptive card json and identify the user's entire response and save it in variable. We are unable to get the user's response in that variable.
![image](https://user-images.githubusercontent.com/62757731/211508228-cd586a6e-80fe-4233-8048-6412a121d47c.png)

When we click on the action.submit button while testing nothing happens. It just gets highlighted.

![image](https://user-images.githubusercontent.com/62757731/211509127-e313ae87-7f10-4eda-aee6-8635ebbdd60a.png)

Could you please let us know how we can capture the user's response from the adaptive card action buttons?

**Below is the sample json we used:**
{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"Present a form and submit it back to the originator"},{"type":"Input.Text","id":"firstName","placeholder":"What is your first name?"},{"type":"Input.Text","id":"lastName","placeholder":"What is your last name?"}],"actions":[{"type":"Action.Submit","title":"Action.Submit","data":{"x":13}}]}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1c3c662-6ca7-6377-2b2e-cacd927de33c
* Version Independent ID: a1c3c662-6ca7-6377-2b2e-cacd927de33c
* Content: [Send a message (preview) - Power Virtual Agents](https://learn.microsoft.com/en-us/power-virtual-agents/preview/authoring-send-message)
* Content Source: [power-virtual-agents/preview/authoring-send-message.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/preview/authoring-send-message.md)
* Service: **power-virtual-agents**
* GitHub Login: @v-alarioza
* Microsoft Alias: **v-alarioza**

**Comment by sanketdixit2013** [comment]
Hello @Team, Any updates on this issue?

**Comment by HenryJammes** [comment]
Hi @sanketdixit2013, I don't believe adaptive card form submits are supported at the moment in the unified authoring canvas. This is planned.

**Comment by sanketdixit2013** [comment]
Hi @HenryJammes , Thanks for the information. If possible could you provide us any ETA for this?

Thanks!
