### ISSUE TITLE
Power virtual agents preview - How can we update adaptive cards in an active conversation

### ISSUE THREAD

**Issue by sanketdixit2013** [MicrosoftDocs/power-platform#1701]
Hello Team,

We would like to understand how we can update adaptive cards in active conversation with the Bot using power virtual agents preview. We don't see any option to update activity in the unified canvas.

This is possible using the composer using update an activity action under manage properties as shown below.
![image](https://user-images.githubusercontent.com/62757731/211511116-74d745c0-11d7-491e-a341-8b31caba77b1.png)

But we don't get any such option in Power virtual agents preview.

Is there a way we can achieve this in PVA unified canvas?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1c3c662-6ca7-6377-2b2e-cacd927de33c
* Version Independent ID: a1c3c662-6ca7-6377-2b2e-cacd927de33c
* Content: [Send a message (preview) - Power Virtual Agents](https://learn.microsoft.com/en-us/power-virtual-agents/preview/authoring-send-message)
* Content Source: [power-virtual-agents/preview/authoring-send-message.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/preview/authoring-send-message.md)
* Service: **power-virtual-agents**
* GitHub Login: @v-alarioza
* Microsoft Alias: **v-alarioza**

**Comment by sanketdixit2013** [comment]
Hello @Team, Any updates on this issue?

**Comment by JonathanFingold** [comment]
@sanketdixit2013 does this article help?

https://learn.microsoft.com/en-us/power-virtual-agents/preview/authoring-send-message#add-an-adaptive-card

**Comment by HenryJammes** [comment]
Not sure this is possible in the current version @sanketdixit2013.
@garypretty do you know?
