### ISSUE TITLE
Links 404

### ISSUE THREAD

**Issue by MartinWhiteDAZN** [MicrosoftDocs/power-platform#1708]
The 2 links in this paragraph go to 404.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-creator-kit

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you. We have a PR open to address this already
https://github.com/MicrosoftDocs/power-platform/pull/1687

Closing as duplicate.
