### ISSUE TITLE
Links to Creator Kit results in a 404.

### ISSUE THREAD

**Issue by samaea** [MicrosoftDocs/power-platform#1715]
The links within this paragraph do not work unfortunately:-

> Import Creator Kit
> The CoE Starter Kit includes features that required the installation of the [Creator Kit](https://learn.microsoft.com/en-us/creator-kit/overview) in the environment where you install the CoE Starter Kit.
> 
> [Install the Creator Kit](https://learn.microsoft.com/en-us/creator-kit/setup) before proceeding.

Thanks,

Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you for raising this! We have a PR open to address this already https://github.com/MicrosoftDocs/power-platform/pull/1687, just waiting for some minor changes and approval there. 

Closing as duplicate.
