### ISSUE TITLE
Lack of clarity around which connector to update.

### ISSUE THREAD

**Issue by samaea** [MicrosoftDocs/power-platform#1716]
For Step 9 under the heading "Set up the Power Automate flow" it states:-

> For the custom connector, Dataverse and Office 365 Outlook, change the value to Use this connection (userPrincipalName@company.com). If there's no connection for any of the connectors, go to Dataverse > Connections, and create one for the connector.

In this step, three connectors are shown Office 365 Management API, Microsoft Dataverse and Office 365 Outlook. My understanding of the text was to only update the two connectors; Microsoft Dataverse and Office 365 Outlook and point them to (x@contoso.com). However, the screenshot shows the amendment of the Office 365 Management API. In this scenario, I am assuming all three connectors should be pointing to (x@contoso.com). If so, it might be worth stating Office 365 API Management API in the text too.

Thanks,
Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The text highlights all three connectors

For the (1) custom connector, (2) Dataverse and (3) Office 365 Outlook.

The Office 365 Management API is the custom connector. But we'll add the specific name in our next update.

**Comment by samaea** [comment]
Oh I see - thanks for the clarity. Perhaps in brackets stating the reference to the Office 365 Management API custom connector might be useful.

On a related note, I am able to point the Office 365 Mgmt API and O365 Outlook connector to my UPN, but not for the Dataverse connector, the only option available is "Provided by run-only user". I do in fact have a Dataverse connector but it doesn't get picked up. Even creating another new connection for Dataverse doesn't solve the problem. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/32162601/212726163-5670582a-4a68-4076-82d6-1aa02e4270ae.png)

![image](https://user-images.githubusercontent.com/32162601/212726421-98e3ab4c-b5ff-44ea-a3fd-6f7e6283e4cc.png)

**Comment by manuelap-msft** [comment]
Hello,

we'll add that with the next update!

No, we've unfortunately seen this issue a few times recently. It seems to be a product bug with Power Automate itself - some users have found that turning the flow on and off and then going back to editing the details brings up the connection.

**Comment by samaea** [comment]
Turning it on and back off again didn't do the trick, however, if I turn it on, I can see the option. However, if I turn it off again, the field shows as blank now, but is then populated again once I turn it back on. Nonetheless, seems to have solved the issue. Thank you!

**Comment by bishalgoswami** [comment]
Thanks for your comment, @samaea. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Updated with a recent docs update.
