### ISSUE TITLE
Creator Kit Links are showing 404

### ISSUE THREAD

**Issue by davins-msft** [MicrosoftDocs/power-platform#1719]
![image](https://user-images.githubusercontent.com/91287781/213014792-bb34c475-f014-41b6-b0f6-c5796241c0c0.png)

The links are broken, getting 404.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @davins-msft. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Fixed with a recent docs update.
