### ISSUE TITLE
Clarity on supported environments and gateways

### ISSUE THREAD

**Issue by willdrobins** [MicrosoftDocs/power-platform#172]
What's not clear in the diagram and documentation is whether multiple Power Apps environments can connect through a single gateway to on-premises data. The diagram shows multiple source technologies connecting to a single gateway but not multiple of one type. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5127679-813b-594a-37f1-92ea81d6d41c
* Version Independent ID: 0aa9c171-4086-c462-8534-a5476f579401
* Content: [Preview: About On-premises gateways - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/wp-onpremises-gateway)
* Content Source: [power-platform/admin/wp-onpremises-gateway.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/wp-onpremises-gateway.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by arthiriyer** [comment]
You can use the same gateway in multiple environments as long as the gateway region an d the environment region matches. https://docs.microsoft.com/en-us/power-automate/regions-overview
