### ISSUE TITLE
Update Azure AD app registration with the redirect URL instruction update

### ISSUE THREAD

**Issue by Dlutchy** [MicrosoftDocs/power-platform#1720]
In the section **Update Azure AD app registration with the redirect URL** Step 2 needs rewording:

From: Under Overview, select Add a Redirect URI.
To: Under **Manage** select **Authentication** 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#create-an-azure-ad-app-registration-for-the-office-365-management-api)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Dlutchy. This issue has been assigned to the doc author for review.
