### ISSUE TITLE
Update CoE Starter Kit Documentation

### ISSUE THREAD

**Issue by mindlessroman** [MicrosoftDocs/power-platform#1725]
Context: Have been using the ALM Accelerator for a project with a customer, but wanted to do a fresh install.

The installation guide in the [docs](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/cli/install.md) refer to an older build (September 2022). Is it reasonable to link to the latest release? Or in the case of the accelerator, document that the templates will need to be updated once installed?

**Comment by mindlessroman** [comment]
https://aka.ms/CoEStarterKitCurrentMonthRelease Or this URL needs to be updated.

**Comment by mikefactorial** [comment]
@mindlessroman thanks for reporting this. Will update the link as suggested. Adding to https://github.com/microsoft/coe-starter-kit/issues/4645 in the coe-starter-kit repo. Closing this for now and you can track the progress / add updates to the issue in the CoE Starter Kit repo

**Comment by mindlessroman** [comment]
⚡ Replied so fast! Thanks @mikefactorial !!
