### ISSUE TITLE
Download link for CreatorKit is broken

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/power-platform#1728]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a869972-ce34-c5c9-c591-fd25347181c1
* Version Independent ID: 9a869972-ce34-c5c9-c591-fd25347181c1
* Content: [Set up the Creator Kit - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/setup)
* Content Source: [power-platform/guidance/creator-kit/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/creator-kit/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ahmadpirani. This issue has been assigned to the doc author for review.

**Comment by denisem-msft** [comment]
This has been fixed. Thank you for letting us know.
