### ISSUE TITLE
Download link to Creator kit not found

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/power-platform#1734]
There is a **Download the Creator kit** link on: https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/overview
![image](https://user-images.githubusercontent.com/47530580/214240561-0b974fcf-a896-49ed-b53f-b9ef3647a325.png)
the link goes to: https://github.com/microsoft/powercat-creator-kit/releases/download/CreatorKit-November2022/CreatorKitCore_1.0.20221205.2_managed.zip but results in:
![image](https://user-images.githubusercontent.com/47530580/214240438-aecc36a6-9e7f-4d4e-ac1e-3584898ba80e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74154c-ce00-1e30-0806-9d9a1d5923ea
* Version Independent ID: 6b74154c-ce00-1e30-0806-9d9a1d5923ea
* Content: [Creator Kit - overview (preview) - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/overview)
* Content Source: [power-platform/guidance/creator-kit/overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/creator-kit/overview.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @m3ngi3. This issue has been assigned to the doc author for review.

**Comment by slaouist** [comment]
Fixed.
