### ISSUE TITLE
Connect to (PowerBI) reporting

### ISSUE THREAD

**Issue by JorisKamma** [MicrosoftDocs/power-platform#174]
Common Data Service analytics - Power Platform Admin center: would be great if I could pull this data into a Power BI dashboard. Is it possible to connect to the source? If so, how?

**Comment by jimholtz** [comment]
@JorisKamma 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
