### ISSUE TITLE
PowerPlatform DLP resource exemption - Any limits ?

### ISSUE THREAD

**Issue by nrd2015** [MicrosoftDocs/power-platform#1743]
I am trying out the PowerShell scripts to exempt resources from DLP policy (New-PowerAppDlpPolicyExemptResources and Set-PowerAppDlpPolicyExemptResources) and would like to understand if there is a limit on the number of Apps and Flows that can be exempted from a DLP policy ?

I have gone through the GitHub documentation and Powershell help for the DLP exemption commands but could not find any details on exemption limits.

**Comment by phecke** [comment]
@nrd2015 I have forwarded your issue to the team that owns the PowerShell scripts.

**Comment by kavehkazms** [comment]
The limit is 2,000 resources. The public documentation has been updated to reflect this:
https://learn.microsoft.com/en-us/power-platform/admin/dlp-resource-exemption

**Comment by phecke** [comment]
Thanks for the feedback.

**Comment by nrd2015** [comment]
Thank you for the update
