### ISSUE TITLE
book the room

### ISSUE THREAD

**Issue by bongbong0000** [MicrosoftDocs/power-platform#175]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eebb06d-174a-4f38-6e9e-c6176e97b3ba
* Version Independent ID: b3feb7ce-6756-29af-f18b-2b9fd4e29f3e
* Content: [Purchase Power Apps for your organization - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/signup-for-powerapps-admin#feedback)
* Content Source: [power-platform/admin/signup-for-powerapps-admin.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/signup-for-powerapps-admin.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@bongbong0000 
Please provide feedback on what should change in the documentation. Thanks.
