### ISSUE TITLE
Value of Empty String?

### ISSUE THREAD

**Issue by jh-sigmadx** [MicrosoftDocs/power-platform#1766]
Documentation does not include what the Value function returns if the input is Blank() or an Empty String""

i.e. that it returns _Blank_

By the Way - this is also stupid - the Value() function should return 0 (zero) for Blank() or empty string inputs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f25fe284-01c5-a660-f595-e06327e0f334
* Version Independent ID: f25fe284-01c5-a660-f595-e06327e0f334
* Content: [Value function in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-value)
* Content Source: [power-platform/power-fx/reference/function-value.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-value.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jh-sigmadx. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
This is generic behavior in Power Fx to treat empty, blank or null as Blank() and Blank usually falls through in functions. This behavior is fairly consistent with Excel.
