### ISSUE TITLE
Incorrect info if input is not in correct format

### ISSUE THREAD

**Issue by jh-sigmadx** [MicrosoftDocs/power-platform#1767]
The Document states:
"If the number is not in a proper format, Value will return blank."

This is incorrect

If the number is not in a proper format. Value will return _Error_

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f25fe284-01c5-a660-f595-e06327e0f334
* Version Independent ID: f25fe284-01c5-a660-f595-e06327e0f334
* Content: [Value function in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-value)
* Content Source: [power-platform/power-fx/reference/function-value.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-value.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jh-sigmadx. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
doc update in progress

**Comment by mduelae** [comment]
@jh-sigmadx The help topic has been updated.

Thank you,
Power Apps Doc Team.
