### ISSUE TITLE
Project Roadmap connector is missing in data policy - data groups selection list

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/power-platform#177]
I created a DLP policy to separate connectors within the two data groups.

**The connectors list seems to be missing the "Project Roadmap" ('shared_projectroadmap') connector. Can anybody verify that behavior?**

When I try to create a Project Roadmap and sync rows in the Project Roadmap with Microsoft Project projects (classic as well as modern), the auto-generated flow in Power Automate (see [Original template](https://emea.flow.microsoft.com/en-us/galleries/public/templates/0924e1395f0146599f7d174bc830cdc8/))fails due to the following error message:
> Configured data policies prevent activation of flows which use the 'shared_commondataservice' and 'shared_projectroadmap' connectors. Visit the Power Automate Admin Center to view applied policies for your organization.

My DLP policy (tenant-wide) already includes among other the following connectors:
- Common Data Service (current environment)
- Common Data Service
- Project Online
- Common Data Service

The list of connectors does not include any connector labeled with "Project Roadmap"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4970680e-b08e-7c4c-4f0b-79c51cc13bcb
* Version Independent ID: 8a110f10-3076-7595-6cac-67ce2c108c9f
* Content: [Manage data loss prevention (DLP) policies - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/prevent-data-loss)
* Content Source: [power-platform/admin/prevent-data-loss.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/prevent-data-loss.md)
* Service: **power-platform**
* GitHub Login: @manasmams
* Microsoft Alias: **manasma**

**Comment by Markus-Hanisch** [comment]
@jimholtz 
I have just received the following  update notification in the Microsoft 365 admin center > message center:
[Office 365 User view access to Project and Roadmap](https://docs.microsoft.com/en-us/project-for-the-web/office-365-user-view-access-to-project-and-roadmap), associated with feature [60646: Office 365 user view to Project and Roadmap](https://www.microsoft.com/de-de/microsoft-365/roadmap?filters=&searchterms=60646)
Maybe this will relieve my issue.

**Comment by jimholtz** [comment]
@Markus-Hanisch 
Greetings. We've revised the DLP documentation since your original question. Please reopen the issue if your question is not answered.

**Comment by hquaintrell** [comment]
Hi, how did you resolve this. I can't find the shared_projectroadmap connector via the DLP GUI

**Comment by Lock-He** [comment]
We are having the exact same issue. Roadmap can not connect with projects in Project Online or Project for the Web. The error indicates that we have a DPL policy that prevents the connector "Project roadmap" from reading data. However, no such "Project Roadmap" connector exists in our admin center. Currently I have a ticket with Microsoft but they have not been able to provide a solution yet.
I would be happy to hear what others have done..?

**Comment by ferrety2006** [comment]
Same issue here. I guess I'll open a service ticket...

**Comment by Markus-Hanisch** [comment]
@jimholtz 
The issue still persists. Just retried today.
There is still no connector for Project Roadmap available in the DLP policy connectors view.

What license plan is required?
I have Project P3. All services enabled.

**Comment by ferrety2006** [comment]
@Markus-Hanisch - here's what Microsoft Support just replied with this morning on the ticket I opened:

This is a know limitation with the connector that we have been working to get resolved but at this time the solution is to manually add the connector into your DLP Policy.
To do this, you will need to have the GUID of your policy and then run the following PowerShell Command(if you do not have the GUID for your Policy on hand, you can use this PowerShell command to list your DLP Policies: Get AdminDlpPolicy )
 
Add-CustomConnectorToPolicy -PolicyName <Your-Policy-GUID> -ConnectorId '/providers/Microsoft.PowerApps/apis/shared_projectroadmap' -GroupName hbi -ConnectorName "Project Roadmap" -ConnectorType "Microsoft.PowerApps/apis"
 
Please note that for -GroupName hbi stands for the “Business data only Data Group” and lbi would stand for the “No business data allowed Data Group”
Once the connector is added in via PowerShell you will be able to locate the connector and manage it inside of the DLP UI like any other custom connector added to a DLP Policy.
 
Note: To perform these actions you will want to have the PowerApps Module for PowerShell installed and be an Administrator to perform the actions. More details on installing the PowerApps module can be found in the following document: https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#installation

**Comment by Markus-Hanisch** [comment]
> We are having the exact same issue. Roadmap can not connect with projects in Project Online or Project for the Web. The error indicates that we have a DPL policy that prevents the connector "Project roadmap" from reading data. However, no such "Project Roadmap" connector exists in our admin center. Currently I have a ticket with Microsoft but they have not been able to provide a solution yet.
> I would be happy to hear what others have done..?

So far no solution. I raised a service ticket in April 2020 already. Due to lacking time and no satisfying solution I could not follow up with enough endurance... 
So I closed the case.

**Comment by Markus-Hanisch** [comment]
> Same issue here. I guess I'll open a service ticket...

Would you mind to keep us up to Date on the outcome? Thanks in advance.

**Comment by ferrety2006** [comment]
> > Same issue here. I guess I'll open a service ticket...
> 
> @ferrety2006
> Would you mind to keep us up to Date on the outcome? Thanks in advance.

Sure thing - just connected up to the module and did some fetching first to make sure I knew what the policy was before I used their instructions:

Get-AdminDlpPolicy 'OurPolicyIDHere' | Select –ExpandProperty BusinessDataGroup

Confirmed Project Roadmap wasn't there to start with.

Then used their command:
Add-CustomConnectorToPolicy -PolicyName 'OurPolicyIDHere' -ConnectorId '/providers/Microsoft.PowerApps/apis/shared_projectroadmap' -GroupName hbi -ConnectorName "Project Roadmap" -ConnectorType "Microsoft.PowerApps/apis"

Got a success message:
Code        : 200
Description : OK
Headers     : {[Pragma, no-cache], [...

Fetched the policy with the first line again - last entry now shows:
/providers/Microsoft.PowerApps/apis/shared_projectroadmap                 Project Roadmap                           Microsoft.Powe...

Went to the flow, tried to turn it on - SUCCESS! No DLP warning!

**Comment by Markus-Hanisch** [comment]
@ferrety2006 
Thank you so much for your guidance :-)
Works like a charm!

**Comment by mm2221** [comment]
Hi, 
I am trying to enable Roadmap in a non-default environment and I get the following error while running the Power Shell commands in the documentation:
 "The DLP policy
'd9591068-7efc-499a-ad56-c97cc5a3c6e9' is applied to a different environment 'xxxxxxxxx-e2a8-9f9f-358e8cbef616' from the provided environment ''."}}
In the O365 Admin center the feature is allowed. Anyone run in to this issue? Please advise.
