### ISSUE TITLE
Orphaned Environments

### ISSUE THREAD

**Issue by nrd2015** [MicrosoftDocs/power-platform#1776]
Dear Power Platform experts, 

I need your advice on this particular situation. There are many environments in our tenant where the owner has left the company. and there is no option to update the environment owner. 

Can you please help me understand -
If there is any loss of functionality for these types of environments ?
How can we update the environment owner ?

Thank you.

**Comment by phecke** [comment]
@nrd2015 Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ Closing this issue.
