### ISSUE TITLE
Unable to embed PDF where access requires windows authentication. 

### ISSUE THREAD

**Issue by agbeaton** [MicrosoftDocs/power-platform#1780]
We have an Intranet network file share with over 3 GB of files what we would like to allow users to open from within a PowerApp.  To accomplish that, we've exposed the files through a web server that limits access to those who are in the security group also being used to grant access to the application.  With that set-up, users can open PDF documents in a new windows but Developer Tools is displaying an authentication error when we try to all them to view the PDF using the new PDF viewer control - even with Cross-Origin Resource Sharing (CORS) configured to allow access from Power Apps. 

If that is a due to a limitation of the PDF viewer control, it would be helpful to clarify that here... and if it can be changed, that would be even better.

Thank-you,

Adam  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0699d67f-ae0a-7421-d0bc-ac8e61d88e6f
* Version Independent ID: 0699d67f-ae0a-7421-d0bc-ac8e61d88e6f
* Content: [PDF function in Power Apps (experimental) - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-pdf?source=recommendations)
* Content Source: [power-platform/power-fx/reference/function-pdf.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-pdf.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @TashasEv
* Microsoft Alias: **tashas**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @agbeaton. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@agbeaton Thank you for the feedback. I am checking with our team to see if this is a limitation that we can document. I will get back to you as soon as I hear back.

Thanks,
Mints

**Comment by mduelae** [comment]
@agbeaton  My internal team is not aware of this limitation. For further help with your issue, please contact support.

To contact Support, see here: https://powerapps.microsoft.com/support/

Thanks,
Mints
