### ISSUE TITLE
Gallery not visible 

### ISSUE THREAD

**Issue by arielcyl** [MicrosoftDocs/power-platform#1783]
[Hi, when I insert the gallery and connect data source, the gallery became invisible When in app mode. Please advise:) thanks # ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae46e7b-18ee-f3a0-0dfd-209e0d093ea5
* Version Independent ID: 6ae46e7b-18ee-f3a0-0dfd-209e0d093ea5
* Content: [ReadNFC function - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-readnfc)
* Content Source: [power-platform/power-fx/reference/function-readnfc.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-readnfc.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @mikepenaMS
* Microsoft Alias: **mikepena**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @arielcyl. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/

Thanks,
Mints
