### ISSUE TITLE
Documentation should mention that COE service account needs to be an owner of the Maker M365 Group

### ISSUE THREAD

**Issue by waiholiu** [MicrosoftDocs/power-platform#1784]
The Power Platform Maker Microsoft 365 Group environment variable needs to be a group ID of a M365 group that the COE service account has to be an owner of or otherwise have some sort of administrative access to add / remove users.

This should be clearly stated in the environment variable description and also in the Persona set up step of the COE Setup Wizard. 

If this is not the case already, consider also sending an alert email to the Admin Email address if the Welcome Email flow fails to add new members to the group due to not having access and also adding in validation in the wizard to check if COE service account has this access.

![image](https://user-images.githubusercontent.com/8047097/219322087-0a07f524-4c61-4eb3-bf41-843c5d17108b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @waiholiu. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
This is already mentioned in our documentation 
![image](https://github.com/MicrosoftDocs/power-platform/assets/55705669/6cce33e3-40ac-41a7-b657-c336424dff19)
