### ISSUE TITLE
pac solution import --settings-file parameter missing alias.

### ISSUE THREAD

**Issue by DesuNinshu** [MicrosoftDocs/power-platform#1789]
Hello,

I noticed the --settings-file parameter in the Pac CLI is missing an alias. Would you guys be willing to add it? It would be meaningful for me. 

https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/solution#--settings-file

**Comment by JimDaly** [comment]
@DesuNinshu 
This reference documentation is generated by a program. It shows the parameters and aliases that are defined. 
Your ask is a feature request, which isn't actionable in the documentation.
Alerting @kkanakas by assigning it this to him, but closing this as an issue that can't be addressed in the documentation.
