### ISSUE TITLE
Applicability to PowerApps, PowerAutomate, PVA, and AI Builder

### ISSUE THREAD

**Issue by shawnnandi** [MicrosoftDocs/power-platform#179]
Hi - I understand that the policies and schedules outlined in this document apply to PowerApps, PowerAutomate, PVA, and AI Builder as well. It would be good to update the introductory paragraph and the rest of the content to reference these products, alongside D365. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13124815-8bd7-6c5d-c123-4b3c049bbf90
* Version Independent ID: 92e1fc93-fd81-9d05-f71d-7dd189ca19a0
* Content: [Policies and Communications for service incidents - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/policies-communications#maintenance-timeline)
* Content Source: [power-platform/admin/policies-communications.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/policies-communications.md)
* Service: **power-platform**
* GitHub Login: @astockli
* Microsoft Alias: **astockli**

**Comment by jimholtz** [comment]
@shawnnandi 
This content has been updated. Thanks for the feedback.
