### ISSUE TITLE
Missing parameter --forceUploadAll for paportal upload

### ISSUE THREAD

**Issue by ager0sa** [MicrosoftDocs/power-platform#1793]
Hello,

Using pac cli 1.21.8.8+ga93a2c3 the following command is available :
pac portal upload --forceUploadAll

The parameter "--forceUploadAll" is not docummented anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1eb674-0b15-eeb1-3b38-afe6498a5354
* Version Independent ID: 0f1eb674-0b15-eeb1-3b38-afe6498a5354
* Content: [Microsoft Power Platform CLI paportal command group - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/paportal)
* Content Source: [power-platform/developer/cli/reference/paportal.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/reference/paportal.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ager0sa. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@ager0sa 
Thanks for pointing this out. I do see this parameter in the help.

This reference content is generated by a program when significant changes occur in the commands and their parameters. Looks like this parameter was added in a recent update.

This parameter will appear when we generate the content again. I'll sync with @kkanakas  about the right time to do this.
