### ISSUE TITLE
Update documentation for [Child] Admin | Sync Logs

### ISSUE THREAD

**Issue by rahine** [MicrosoftDocs/power-platform#1794]
Changes were made to the [Child] Admin | Sync Logs flow to use a child flow for sending emails vs using the Outlook connector. Please update the documentation to show these changes as the outlook connector is no longer referenced in this flow.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rahine. This issue has been assigned to the doc author for review.
