### ISSUE TITLE
Supported Variable Types

### ISSUE THREAD

**Issue by CKeene78** [MicrosoftDocs/power-platform#18]
Would be helpful to have a list of supported variable types when passing from PVA to PA. 

Ran into an issue where I was trying to send back a JSON array from a PA Action and could not see/select the PA Action in PVA until I changed the return object to a non-array JSON object. Figured out that JSON arrays are not (currently?) supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0488e418-391f-0641-c1dd-c8615f8054ea
* Version Independent ID: 91929a7a-0690-4497-091a-5f7134a66284
* Content: [Automate Power Virtual Agents bot activities with flows - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-flow#feedback)
* Content Source: [power-virtual-agents/advanced-flow.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-flow.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by makolomi** [comment]
The list of supported variable types is listed under "Create a new flow from the Power Virtual Agents authoring canvas", section, right above "Input parameters" sub-section. Would you propose moving it to a separate section?

**Comment by CKeene78** [comment]
Promoting it to a section, rather than a sub-section, might be helpful. A table/list specifying which supported variable types are *and* are not supported might be helpful. Surprised that JSON and Array types were not supported because PA can handle those formats fine. Just so used to using objects containing "Number, String, Boolean" that it did not occur to me that using objects in PVA would not work. 

On the troubleshooting side: would rather have a non-supported return function be shaded or otherwise indicate that a return type is not supported. At least then I would know that the PA can be seen by the PVA even if I cannot use it until the return type is corrected.

**Comment by iaanw** [comment]
I've made updates to pull the input/output params into their own section and added unsupported params. The updates should be live later today or tomorrow. Thanks for the feedback!
