### ISSUE TITLE
dead Link in  Licensing Guide document

### ISSUE THREAD

**Issue by bonserem** [MicrosoftDocs/power-platform#180]
In the explanation about sessions on page 17 there is a link to more details. This however forwards to a sharepoint site: microsoft-my.sharepoint.com for which I do not have access. So these details are not accessable. Also the price of Power Virtual Agents Capacity add-on is not mentioned on the link for pricing information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd5c132-57b9-d038-7e20-8f9d94d53bd3
* Version Independent ID: a436faf7-de5e-cfe5-34af-c8cc6e075cdd
* Content: [Assign user licenses and manage access to Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/requirements-licensing#feedback)
* Content Source: [power-virtual-agents/requirements-licensing.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/requirements-licensing.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
We're working to get these links updated, and they should be updated in the latest version of the licensing guide.
