### ISSUE TITLE
Security Issues with this solution.

### ISSUE THREAD

**Issue by lsousa-code** [MicrosoftDocs/power-platform#1805]
[Enter feedback here]
The required permissions are to extensive to be able to run this on a properly secured enterprise environment.
It does not provide any least privilege guidelines. Can the solution and the page be improved regarding security.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lsousa-code. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
The CoE Starter Kit is a reference implementation of a tooling approach for how to admin and governance Power Platform, it's built on top of the platform and as such relies on capabilities in the platform to work. As a reference implementation, it may not meet the needs of every customer and some customers will need to implement their own tooling approach for admin and governance vs using the CoE kit if the solution we provide doesn't meet their needs. 

Here's how the kit works and some of the limitations:

- The CoE kit works by using admin connectors in cloud flows (such as [https://learn.microsoft.com/en-us/connectors/powerappsforadmins/](https://learn.microsoft.com/en-us/connectors/powerappsforadmins)) to crawl the tenant on a daily basis and check for Power Platform resources and inventory. These connectors require to be run by an account that has Power Platform Admin access to retrieve the inventory of the entire tenant - a role with lesser privileges would not see all resources in the inventory. Hence the requirement for permanent admin access.
- The flows using these connectors run on a schedule, sometimes trigger each other or trigger when a specific activity happens - based on the number of resources in the tenant, they can take a long time to run as well. Therefore it's not possible to provide time based access via PIM, as if the account running the flows loses access whilst they run, again not all the inventory would be retrieved. 
- The MFA requirements of this solution are based on the MFA requirements for Power Automate, and not specific to the CoE kit, [Conditional access and multi-factor authentication in Flow - Power Automate | Microsoft Learn](https://learn.microsoft.com/en-us/troubleshoot/power-platform/power-automate/conditional-access-and-multi-factor-authentication-in-flow)

If the above means that you can't use the CoE kit, you need to evaluate other options for admin and governance tooling such as Managed Environments (out of the box feature), and self-serve analytics ([Microsoft Power Platform self-service analytics export Power Platform inventory and usage data (preview) - Power Platform | Microsoft Learn](https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics) for reporting.
