### ISSUE TITLE
No breakdown of capacity usage by Product Family (Storage Type)

### ISSUE THREAD

**Issue by MrEcrm** [MicrosoftDocs/power-platform#1808]
As we are almost on total capacity usage, we wanted to buy more capacity. Easy? Of course not. File, Log, and Database capacity come with different prices. We only want to buy more capacities from the ones needed. But the portal only gives a total no breakdown.

e.g. 290/300, for all of them, assuming we have already made the necessary deletions and the log or file usage we really use: 

Log 10/10
File: 10/10
Database: 270 / 280.  

This would mean:  that we won't need to buy more Database right now, but Log or File would be needed.

Right now, we can only see that we have 270/300 GB used, and are asked to buy either more file, log or database, without the knowledge in which one of them we fall short! :-(

**Comment by Mattp123** [comment]
@MrEcrm - The storage model lets you view capacity by storage type. More information: https://learn.microsoft.com/en-us/power-platform/admin/capacity-storage
