### ISSUE TITLE
Reopen #149

### ISSUE THREAD

**Issue by pkothree** [MicrosoftDocs/power-platform#181]
The issue #149 is not solved. The explanation is still wrong. The explanation given in the issue does not match the explanation given on the docs page. Neither the explaination in the issue nor the explanation on docs match the example given.
Please provide a example on the docs that matches the description. Business decisions are depending on this, which are currently impacted by misleading and incorrect information.

**Comment by jimholtz** [comment]
We revised the content to clarify. We hope that addresses your issue.
