### ISSUE TITLE
Avoid Using Animated Graphics \ Short Videos That Automatically Play in Articles

### ISSUE THREAD

**Issue by d0finley** [MicrosoftDocs/power-platform#1812]
[Enter feedback here]
Please stop putting graphics in these articles that automatically plays a short video clip, this is INCREDIBLY distracting when trying to read the rest of the page. At least give the reader a way to stop the video from playing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93752ff7-69cf-1dd6-500e-fb367b4eb123
* Version Independent ID: 514cfff9-e0ea-836f-cd42-9089585e2578
* Content: [Microsoft Power Fx overview - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/overview)
* Content Source: [power-platform/power-fx/overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/overview.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @d0finley. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
I couldn't agree more, I hate them too. Additionally, they are not accessible at all. I will keep this in mind when editing existing pages to see while I'm there if I can replace some of these with text.
