### ISSUE TITLE
Update address for Tutorial: Get started with GitHub Actions for Microsoft Power Platform - Power Platform

### ISSUE THREAD

**Issue by HarryDriscollTWE** [MicrosoftDocs/power-platform#1814]
Address for Application User Creation, step 1 should be: aka.ms/ppac

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce8d679-77f4-99c0-8d7f-f25db4ba1c9c
* Version Independent ID: daf77157-6c6f-7c3e-7f74-a6f9ba528ec1
* Content: [Tutorial: Get started with GitHub Actions for Microsoft Power Platform - Power Platform](https://learn.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-start)
* Content Source: [power-platform/alm/tutorials/github-actions-start.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/tutorials/github-actions-start.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @HarryDriscollTWE. This issue has been assigned to the doc author for review.

**Comment by kkanakas** [comment]
@phecke  looks like step1 needs to be updated

**Comment by phecke** [comment]
@HarryDriscollTWE @kkanakas 

Address updated. Updated topic to be published later today.

Thanks Harry.
