### ISSUE TITLE
Solution Checker role?

### ISSUE THREAD

**Issue by lkuhn65** [MicrosoftDocs/power-platform#182]
Shouldn't this page also explain Solution Checker, Knowledge Manager, etc?  (in other words I see more roles in my selection box than are explained in this article).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure environment security - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/database-security)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/database-security.md)
* Service: **power-platform**
* GitHub Login: @manasmams
* Microsoft Alias: **manasma**

**Comment by jimholtz** [comment]
@lkuhn65 
Thanks for the suggestion. We'll consider for future documentation updates.
