### ISSUE TITLE
Clicking on a link gives a 404 error

### ISSUE THREAD

**Issue by vibraniumforge** [MicrosoftDocs/power-platform#1824]
1. Load this page: [DateAdd, DateDiff, and TimeZoneOffset functions in Power Apps](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-dateadd-datediff)
2. Go to this part: "Also see [Date, Time, and DateTime data types](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/functions/data-types#date-time-and-datetime) and [working with dates and times](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/show-text-dates-times) for more information."
3. Click on the first link, [Date, Time, and DateTime data types](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/functions/data-types#date-time-and-datetime)
4. Notice a 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77554a1d-d853-8718-d703-b4f8ac76f1e9
* Version Independent ID: 77554a1d-d853-8718-d703-b4f8ac76f1e9
* Content: [DateAdd, DateDiff, and TimeZoneOffset functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-dateadd-datediff)
* Content Source: [power-platform/power-fx/reference/function-dateadd-datediff.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-dateadd-datediff.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vibraniumforge. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
Thanks for your feedback; this is resolved now.
