### ISSUE TITLE
Typographical error

### ISSUE THREAD

**Issue by karlkranich** [MicrosoftDocs/power-platform#1829]
[Enter feedback here]
"data and processes that's used by business..." should say "data and processes that are used by business..."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c38b14c5-3129-b593-0901-775bbfb2427a
* Version Independent ID: c3624c25-4f2b-4bef-70a4-950533343332
* Content: [Application lifecycle management (ALM) with Microsoft Power Platform - Power Platform](https://learn.microsoft.com/en-us/power-platform/alm/overview-alm)
* Content Source: [power-platform/alm/overview-alm.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/overview-alm.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @shmcarth
* Microsoft Alias: **shmcarth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @karlkranich. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
This is resolved and will be refreshed in public site soon.
