### ISSUE TITLE
DLP Violation

### ISSUE THREAD

**Issue by rsch136** [MicrosoftDocs/power-platform#183]
Hi,
We are currently trying to set up the CoE Audit Log Components and are running into the follwoing error when trying to turn on the [Child] Admin | Sync Logs:

> Your flow could not turn on: [Child] Admin | Sync Logs. Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Flow '' cannot be activated due to admin API policies."}}".

The flow also claims not to have any connections for this flow.

What could be the cause for these errors? There were no errors when installing the solution.

Please let us know what connections are being used so that we can build a custom DLP for the environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

this is an issue with the CoE Starter Kit itself, not the Documentation. Could you please raise this issue here https://aka.ms/coe-starter-kit-issues

Thank you
Manuela

**Comment by rsch136** [comment]
Will do. Thanks.

**Comment by garygooding** [comment]
Hi,
I had the same problem today. The flow uses two connectors: Common Data Service and Office 365 Audit Logs. The Office 365 Audit Logs is the custom connector you created following this document. I needed to add this to the DLP business data group which I did using the DLP Customizer app in the COE Kit

**Comment by jimholtz** [comment]
@garygooding 
Please raise this issue here: https://aka.ms/coe-starter-kit-issues
