### ISSUE TITLE
Enable Dynamics 365 apps for Trial environments

### ISSUE THREAD

**Issue by davins-msft** [MicrosoftDocs/power-platform#1830]
The article mentions "Currently, Dynamics 365 apps cannot be enabled for trial environments."
![image](https://user-images.githubusercontent.com/91287781/224369859-86b52d59-7059-446c-9e99-39f1e3d9ce82.png)

however I am able to toggle the "Enable Dynamics 365 apps" switch during environment creation to enabled for Trial (Subscription-based) environment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform admin center - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/create-environment#create-an-environment-and-add-model-driven-apps)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Mattp123
* Microsoft Alias: **kvivek**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @davins-msft. This issue has been assigned to the doc author for review.

**Comment by marcelbf** [comment]
@Matt ***@***.***>

I believe the owner for this doc is @***@***.***>
