### ISSUE TITLE
PAC not installable via the command line in mac

### ISSUE THREAD

**Issue by MCKevmeister** [MicrosoftDocs/power-platform#1835]
A CLI tool should be installable from the command line. Currnely users must download a gui application to use a cli tool. Please provide a cross platform CLI install command, rather than requring users to fisrt install VS Code. This is gatekeeping a CLI tool

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Version Independent ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Content: [Microsoft Power Platform CLI - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction#install-using-power-platform-tools-for-visual-studio-code)
* Content Source: [power-platform/developer/cli/introduction.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/introduction.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@MCKevmeister 
Thanks for your feedback.

Issues in this repository are for issues with the documentation, not feature requests.

It is clear that you understand that the cross-platform installation requires Visual Studio Code.  We can't fix that by changing the documentation.

The actionable item for documentation is to make it easier for people to find how they can submit feature requests.

Assigning @snizar007.

**Comment by rajyraman** [comment]
@MCKevmeister - Do you have Docker or Podman? I am currently working on containerising pac, but you still need additional applications like Docker or Podman to run pac.

**Comment by kkanakas** [comment]
The Power Platform Command line tool installer, is only for Windows, there is no stand alone installer for mac. If you would like to install on mac you can download it from nuget.org https://www.nuget.org/packages/Microsoft.PowerApps.CLI.Core.osx-x64 and containerize it

**Comment by MCKevmeister** [comment]
![image](https://user-images.githubusercontent.com/53839878/224861792-c87cca1e-e593-45a9-8e7b-4311d9c372b6.png)
I beg to disagree

**Comment by MCKevmeister** [comment]
After install the plugin (wait is this a CLI tool? or a gui tool?), running `which pac` in vs code's terminal, then adding that to PATH allow me to use it in a non visual studio code (and cli installer apparently) terminal.

It's possible to install cli tools via the cli that are cross platform, look at dotnet.

**Comment by snizar007** [comment]
Please take a look at below document on how to install PAC on MacOS/Linux using dotnet tools install.

https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction
