### ISSUE TITLE
Environment Variable , clarification of where used

### ISSUE THREAD

**Issue by binaryjam** [MicrosoftDocs/power-platform#1838]
The Env variable Companyu name is new to me since installing Feb 23 from Oct.  I have no idea where this variable is used and what the knock on effect will look like.

So can I have links to where this is used and how, so that If I need to make changes to emails or apps I know which ones it effects.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Currently it is only used in the Video Hub (Nurture components) solution, we added the environment variable to Core as it seemed like something that we might want to use in other apps as well.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @binaryjam. This issue has been assigned to the doc author for review.
