### ISSUE TITLE
Failed Test for Custom connector (MFA)

### ISSUE THREAD

**Issue by malkhawaja** [MicrosoftDocs/power-platform#184]
Hi,
I have a failed response (400) when trying to start the subscription:

{
  "error": {
    "code": "StartSubscription [CorrId=1be932f4-b140-45b6-a970-83c131738fd7][TenantId=ead03517-1798-484e-b93e-0b73f75e43dd,ContentType=Audit.General,ApplicationId=4864ee8e-abc0-41dd-b038-d3226d26d252,PublisherId=4864ee8e-abc0-41dd-b038-d3226d26d252][AppId",
    "message": "864ee8e-abc0-41dd-b038-d3226d26d252] failed. Exception: Microsoft.Office.Compliance.Audit.DataServiceException: Tenant ead03517-1798-484e-b93e-0b73f75e43dd does not exist.\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.&lt;GetSubscriptionTableClientForTenantAsync&gt;d__50.MoveNext() in d:\\dbs\\sh\\nibr\\0413_071452\\cmd\\v\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 1786\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.&lt;GetAPISubscriptionAsync&gt;d__23.MoveNext() in d:\\dbs\\sh\\nibr\\0413_071452\\cmd\\v\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 498\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.StartController.&lt;StartSubscription&gt;d__0.MoveNext() in d:\\dbs\\sh\\nibr\\0413_071452\\cmd\\y\\sources\\dev\\auditing\\src\\auditapiservice\\apifrontendservicerole\\Controllers\\StartController.cs:line 75"
  }
}

so what should I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#feedback)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The error message points out that
Tenant ead03517-1798-484e-b93e-0b73f75e43dd does not exist

So I would make sure you've entered the correct tenant ID from the Azure App Registration. This will be different to your environment ID etc.

Also please note that issues for the CoE Starter Kit solution should be raised via https://aka.ms/coe-starter-kit-issues, as this page is only for issues with the documentation (e.g. if you find a missing screenshot, or step in the documentation)

**Comment by malkhawaja** [comment]
thanks for the quick response... issue resolved as it was that the audit log search was turned off for my tenant... so I think updating the documentation (to make sure that audit log is already turned on on the tenant) can be beneficial!

thanks
