### ISSUE TITLE
Instructions and Screenshots for Custom Connector outdated

### ISSUE THREAD

**Issue by SkippingAdi** [MicrosoftDocs/power-platform#1840]
The screenshots for the Custom Connector are outdated and the instructions no longer fit. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Which screenshots and instructions are outdated? Could you provide a bit more details please.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SkippingAdi. This issue has been assigned to the doc author for review.

**Comment by RedsGT** [comment]
@manuelap-msft https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector
CC Node is on root of PApps Maker portal now and creating a new CC doesn't move you to the PAuto portal.

**Comment by SkippingAdi** [comment]
Hello Manuela

All Screenshots related to the configuration of the Custom Connector are outdated.
Two days ago, as I installed Center of Excellence Audit Log, the properties for configuring the Custom Connector were completely different to the once in the documentation.

Actual Screenshot from the documentation:
[cid:f9d2eb87-33ef-4df5-9233-8a95291649d7]

Screenshot how actual Custom Connector looks like:
[cid:f2df0e3f-bfcd-4c8b-903d-75bf46066848]

Differences:

  *   No Logging Url property
  *   No Tenant Id property
  *   No Resource Url

Instead:

  *   Authorization URL
  *   Token URL
  *   Refresh URL

For me totally unclear, what values I have to write where and where I should get e.g. the token Url?

Maybe the differences come from the fact that you have to choose a different Identity Provider? Because OAuth2 as described in your documentation seems to be replaced by Generic OAuth2 or just renamed?

With kind regards
Adrian

________________________________

**Comment by SkippingAdi** [comment]
Supplement:

Please find below the available Identity Providers as seen two days ago, when configuring Custom Connector:
[cid:a6a99f80-de6f-476e-966f-23332f1a6ac1]

Regards
Adrian

________________________________
