### ISSUE TITLE
Report of users and their assigned security roles

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/power-platform#185]
Hello guys,

Please, where is the option to get a report of the user and their security role assigned? I need to extract all security roles assigned to respective users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74e68eaf-8937-279f-d707-ac7a1d2c2ff6
* Version Independent ID: bb4d936b-bac2-411e-9afd-d0d7ca0c88c3
* Content: [Security roles and privileges - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/security-roles-privileges)
* Content Source: [power-platform/admin/security-roles-privileges.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/security-roles-privileges.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@ingd
See: https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service#download-reports
