### ISSUE TITLE
No need to grant ServiceMessage.Read.All Delegated permissions for Service Message AAD App

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#1852]
Only application permissions are needed as messages are fetched using HTTP action which does not have user context i.e. no delegated auth context.

Select Microsoft Graph, and configure permissions as follows:
- ~~Select Delegated permissions, and then select ServiceMessage.Read.All.~~
- Select Application permissions, and then select ServiceMessage.Read.All.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @petepuu. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
This has been updated. Closing out.
