### ISSUE TITLE
Social engagement and social selling discontinued?

### ISSUE THREAD

**Issue by cxr-dev** [MicrosoftDocs/power-platform#186]
The 16 January 2020 Microsoft Social Engagement was discontinued, and I can't find the Social selling app in AppSource. you should update the documentation with a notification about its status.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8cb33b1-f624-71dd-5cd6-66b2ad9e3562
* Version Independent ID: 278c97e4-60af-2a85-0b38-1dabc92de60d
* Content: [Install the Social Selling Assistant - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/install-social-selling-assistant)
* Content Source: [power-platform/admin/install-social-selling-assistant.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/install-social-selling-assistant.md)
* Service: **power-platform**
* GitHub Login: @m-hartmann
* Microsoft Alias: **mhart**

**Comment by jimholtz** [comment]
@cxr-dev 
Thanks for the feedback. We've added a link to an FAQ for more information.
