### ISSUE TITLE
PDF function missing on Power Apps functions overview documentation page

### ISSUE THREAD

**Issue by e-gallis** [MicrosoftDocs/power-platform#1860]
The PDF function is missing in the Power Apps functions overview page located at : https://learn.microsoft.com/en-us/power-platform/power-fx/formula-reference

![image](https://user-images.githubusercontent.com/32480338/228809419-2f327727-8015-4ebf-9b97-69d2de582e31.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4db6d199-e58a-d817-6da3-66fbfacef44b
* Version Independent ID: 4db6d199-e58a-d817-6da3-66fbfacef44b
* Content: [Power Fx formula reference for Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/formula-reference)
* Content Source: [power-platform/power-fx/formula-reference.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/formula-reference.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @e-gallis. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@e-gallis I updated the topic and added a link to the PDF function. Thanks for catching it.

You should see the changes live on our site by end of day today.

Thanks,
Mints
