### ISSUE TITLE
Wrong rename instruction for release-solution-with-inputs.yaml

### ISSUE THREAD

**Issue by bambooch** [MicrosoftDocs/power-platform#1861]
On [this section's](https://learn.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-deploy#create-a-reusable-workflow-to-generate-a-build-artifact-and-import-to-production) step 3, the docs say to rename the the title of the workflow to `release-solution-to-prod-with-inputs` and then on [this section's](https://learn.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-deploy#call-the-reusable-workflow-on-the-release-event) step 3 the docs say to copy the workflow from [here](https://github.com/microsoft/powerplatform-actions-lab/blob/main/sample-workflows/release-action-call.yml). The copied workflow references a file with the name of `release-solution-with-inputs` not `release-solution-to-prod-with-inputs` thus making the rename suggestion in the first section incorrect. The rename instruction should be `release-solution-with-inputs` instead of `release-solution-to-prod-with-inputs`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59ea9b81-aed6-cf71-becc-305d2e87936f
* Version Independent ID: 0fa54745-8952-a630-6b35-0db1971c0275
* Content: [Tutorial: Automate solution deployment using GitHub Actions for Microsoft Power Platform - Power Platform](https://learn.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-deploy)
* Content Source: [power-platform/alm/tutorials/github-actions-deploy.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/tutorials/github-actions-deploy.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bambooch. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@bambooch The copied workflow now references release-solution-to-prod-with-inputs.

[release-action-call.yml](https://github.com/microsoft/powerplatform-actions-lab/blob/main/sample-workflows/release-action-call.yml)
