### ISSUE TITLE
outdirectory Parameter is not optional

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/power-platform#1865]
Even though --outdirectory -o is listed under Optional Parameters, the command fails with the following error when the outdirectory Parameter is not provided.

`Required argument OUTDIRECTORY or OUT is not set.  One or the other is required for this command to execute`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1611ae-9de7-ba15-c06d-beab6c256df6
* Version Independent ID: 5e1611ae-9de7-ba15-c06d-beab6c256df6
* Content: [Microsoft Power Platform CLI modelbuilder command group - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/modelbuilder)
* Content Source: [power-platform/developer/cli/reference/modelbuilder.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/reference/modelbuilder.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @snizar007
* Microsoft Alias: **snizar**

**Comment by JimDaly** [comment]
@LinnZawWin 

Spoke with the dev team. They are fixing the metadata so that this will be correct the next time we generate these docs.

Thanks for raising this.
I've also applied a change to represent this correctly until the article is regenerated.

> ### Required Parameters
> 
> #### `--outdirectory` `-o`
> 
> Write Directory for entity, message and optionset files
