### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mhuguet** [MicrosoftDocs/power-platform#1866]
Also see Date, Time, and DateTime data types link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77554a1d-d853-8718-d703-b4f8ac76f1e9
* Version Independent ID: 77554a1d-d853-8718-d703-b4f8ac76f1e9
* Content: [DateAdd, DateDiff, and TimeZoneOffset functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-dateadd-datediff)
* Content Source: [power-platform/power-fx/reference/function-dateadd-datediff.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-dateadd-datediff.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mhuguet. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
@mhuguet Thanks for reporting this. It is resolved now.
