### ISSUE TITLE
SharePoint Power Apps are now available in GCC

### ISSUE THREAD

**Issue by brendon-colburn** [MicrosoftDocs/power-platform#187]
A colleague and I just saw this capability turned on in GCC today, so the documentation needs to be updated here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea524f2a-1e2a-6ade-8e2b-bc61173107c5
* Version Independent ID: 5990c060-8907-62b4-a8b3-f7ed8339a70e
* Content: [Microsoft Power Apps US Government - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government?source=docs#feedback)
* Content Source: [power-platform/admin/powerapps-us-government.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-us-government.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@brendon-colburn 
Thanks for bringing this to our attention. We'll be making an update to the documentation.
