### ISSUE TITLE
Links in powerapps-powershell.md do not work

### ISSUE THREAD

**Issue by SEsnorre** [MicrosoftDocs/power-platform#1879]
Links in the section

"For information on the Power Apps admin module, see [Get started using the Power Apps admin module](https://github.com/MicrosoftDocs/power-platform/blob/main/powershell/powerapps/get-started-powerapps-admin) and [Microsoft.PowerApps.Administration.PowerShell](https://github.com/MicrosoftDocs/power-platform/blob/main/powershell/module/microsoft.powerapps.administration.powershell)." 

do not work and give a 404 error

**Comment by JimDaly** [comment]
@SEsnorre 
Hi - 
Thanks for your feedback.
You seem to be referring to this article:
[PowerShell support for Power Apps](https://learn.microsoft.com/en-us/power-platform/admin/powerapps-powershell)

And this section:

> For information on the Power Apps admin module, see [Get started using the Power Apps admin module](https://learn.microsoft.com/en-us/powershell/powerapps/get-started-powerapps-admin) and [Microsoft.PowerApps.Administration.PowerShell](https://learn.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell).

Those links seem to work fine when viewed on https://learn.microsoft.com/

I'd like to confirm that you are aware that the content in this repo is the source for content published on https://learn.microsoft.com/. It isn't intended to be used directly.

Are you reporting that the links don't work when viewed as Markdown on https://github.com/MicrosoftDocs/power-platform?

Please advise so we can take action to fix the problem.

**Comment by Mattp123** [comment]
@SEsnorre - The GitHub repo is intended for contributing to our documentation not for viewing. As suggested in the previous reply, please view our documentation on learn.microsoft.com, such as https://learn.microsoft.com/en-us/power-platform/admin/powerapps-powershell. 

If I misunderstood what your issue is, reopen this issue. Closing issue.
