### ISSUE TITLE
This Page Needs a section called DLP Requirements / Settings -

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/power-platform#188]
Hi Manuela
When I try and turn the flows on I get an error - Your flow could not turn on: Admin | Sync Template v2. Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Flow '' cannot be activated due to admin API policies."}}".  What admin API policies ?  I think I have the correct connectors in the DLP Policy, but I cannot be sure as there is no list of connectors in the which should be in the DLP Policies in the documentation.
Thanks
Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#feedback)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The DLP Policy requirements are mentioned in the pre-requisites in the overall set up instructions
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

It currently says:
The environment must have a DLP Policy that allows Common Data Service, Power Platform Management connectors, Office 365 Users, and Office 365 Outlook to be used together. Those connectors must be in the business data–only bucket of the DLP policy for this environment.

I have updated this now to list all the Power Platform management connectors seperately:
The environment must have a DLP Policy that allows Common Data Service, Common Data Service (current environment), Office 365 Users, Power Platform for Admins, Power Automate Management, Office 365 Outlook, Power Apps for Admins, Power Apps for Makers to be used together. Those connectors must be in the business data–only bucket of the DLP policy for this environment.

If you still experience issues after moving those connectors to your DLP policy, you might have a tenant wide policy that's conflicting.

**Comment by manuelap-msft** [comment]
PS: The update mentioned above will be live when we next merge our changes!

**Comment by EditK** [comment]
We get the same error when trying to turn on both audit Flows (parent and child), even after adding the aforementioned connectors to the business-data-only bucket of the DLP policy.

A reason might be the fact that we are using the custom connector (Office 365 Management API) in the same Flow with the business-data-only connectors. Unfortunately, when trying to enter this custom connector to the same DLP policy, using DLP Customizer App, the custom connector is not even listed.

It is listed in make.powerapps.com, Data > Custom Connectors.
It is not listed inside a Flow, when searching for custom connectors.

The solution has installed without errors and the customizations have been published.

**Comment by manuelap-msft** [comment]
Here's the documentation on how to move the custom connector to business data only. There's currently a limitation with the DLP Customizer, which means the tool currently does not work for custom connectors that are installed as part of a managed solution. This is documented in the same feature. 

https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#custom-connectors-and-dlp

**Comment by EditK** [comment]
Adding the custom connector to the same DLP policy as the other connectors used in the flows, solved the error, and made turning on the flows succeed.

**Comment by pjrech** [comment]
I'm facing the same issue, but no custome connectors is used. 
It happen only in flows that call child flows and starts with no reason... 
The flows was ok, including the call to child flows... but suddenly the error appers and turned off the flows that calls childs.
Any sugestion?

**Comment by manuelap-msft** [comment]
If you are having issues with using the kit please report your issue here: https://aka.ms/coe-starter-kit-issues, providing as much detail as possible. Screenshots of error messages also help! The issues section here is only used to track documentation gaps and issues.
