### ISSUE TITLE
Missing information about Training in a day - Feedback Form

### ISSUE THREAD

**Issue by prawnz** [MicrosoftDocs/power-platform#189]
Might want to put in a screenshot or more details on the Feedback Form as it is not part of the package and needed to be manually created

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fc749-2ecd-61d7-4146-16fe1a373848
* Version Independent ID: fcd148f1-795e-a99c-e2e9-da06e1129d3c
* Content: [Set up nurture components - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#feedback)
* Content Source: [power-platform/guidance/coe/setup-nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-nurture-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you for the feedback, we have added this information now
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#set-up-a-feedback-form-for-your-training-in-a-day
