### ISSUE TITLE
Clarify API request limits for 'per app' plan

### ISSUE THREAD

**Issue by rhaines46** [MicrosoftDocs/power-platform#19]
I see the API request limit is "1,000 per user pass" within a 24 hour window, but I'm unclear on what exactly constitutes a 'user pass'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#feedback)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@rhaines46 
User pass is the terminology used to describe a per app license instance. So a user using a per app licence instance is described as having a user pass.

**Comment by roozbehtk** [comment]
How would these limits impact Dynamics/PowerApps Portals? Given all the request from the Portals is made through SYSTEM user, would those limits also applied to SYSTEM

**Comment by jimholtz** [comment]
@roozbehtk 
Portal API requests depends on the type of user using the portal. 
For internal users using Dynamics or Power Apps license, they are bound by daily API limits which their license type allows. That information is gathered by platform internally and their usage is reconciled.
For external users, API limits come with logins and page view capacity. Details are in the Power Apps licensing guide.
