### ISSUE TITLE
Content order is not correct

### ISSUE THREAD

**Issue by abhiseksinhaGIT** [MicrosoftDocs/power-platform#190]
Create a SharePoint site section should be before Update environment variables section.
The environment variable for Power User Site URL (SharePoint Site) comes pre-populated with Microsoft's internal portal URL (I've noticed the same issue with some env variables in the Governance Component's page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fc749-2ecd-61d7-4146-16fe1a373848
* Version Independent ID: fcd148f1-795e-a99c-e2e9-da06e1129d3c
* Content: [Set up nurture components - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#create-a-sharepoint-document-library)
* Content Source: [power-platform/guidance/coe/setup-nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-nurture-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you, this update is now live
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components
