### ISSUE TITLE
Security Group is now mandatory when creating a new Dataverse enabled Environment

### ISSUE THREAD

**Issue by philipverlinden** [MicrosoftDocs/power-platform#1904]
When I want to create an environment today in crm4, it seems the Security Group is now mandatory.
This is not reflected in this documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform](https://learn.microsoft.com/en-gb/power-platform/admin/control-user-access?WT.mc_id=ppac_inproduct_env)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by sericks007** [comment]
@philipverlinden, thank for letting us know about this! This content has now been updated.
