### ISSUE TITLE
Dataverse security role by Power Platfrom admin

### ISSUE THREAD

**Issue by lukas-nC** [MicrosoftDocs/power-platform#1906]
![image](https://user-images.githubusercontent.com/113470539/234847103-2f7d255b-4116-4683-93e9-456d6a34a1f9.png)

Does only the Dynamics Admin get System Administrator role in every Environment with Dataverse or the PowerPlatform Admin as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c1dd41e-5994-2eb5-f659-af836a1a3fc1
* Version Independent ID: f70008c9-ea14-96f1-8b29-d94bb510b680
* Content: [Use service admin roles to manage your tenant - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/use-service-admin-role-manage-tenant)
* Content Source: [power-platform/admin/use-service-admin-role-manage-tenant.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/use-service-admin-role-manage-tenant.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by srpoduri** [comment]
@lukas-nC @sericks007 Global Admin, Power Platform Admin, and Dynamics Admin get the System Administrator role in all environments with Dataverse. Documentation has been updated to reflect this.
