### ISSUE TITLE
You CAN edit security roles for Application users now.

### ISSUE THREAD

**Issue by Turbo549** [MicrosoftDocs/power-platform#1917]
The documentation incorrectly states (regarding Application users) "The security role that is assigned to these accounts cannot be updated either. This is to prevent any service outages."  This functionality now exists in the Power Platform admin center.  New security roles may be assigned and existing ones may be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 436a3b84-3edb-8d4e-bc7e-51488b8f879a
* Version Independent ID: 634e9777-62b1-01e6-6db1-eafbfe5d8d7d
* Content: [Special system users and application users - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/system-application-users?source=recommendations)
* Content Source: [power-platform/admin/system-application-users.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/system-application-users.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by sericks007** [comment]
@Turbo549, thanks for letting us know about this.  The content has now been updated.  The updated content will be published at noon, Pacific time.
