### ISSUE TITLE
How are active users calculated?

### ISSUE THREAD

**Issue by RohitBundele** [MicrosoftDocs/power-platform#193]
Can you please elaborate on the metric definition of an "Active User", I think this it is not same as "Unique Users". 
- Is there any time span/session which is considered for calculating an Active users?
- At what level are the duplicated filtered?
- Does this count multiple visits only once during any time period?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2bb683-51c1-2dbb-d65d-20f879320106
* Version Independent ID: cd768223-1723-b37a-9537-5398761b0fe0
* Content: [Power Apps analytics - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/analytics-powerapps?source=docs)
* Content Source: [power-platform/admin/analytics-powerapps.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/analytics-powerapps.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by pnghub** [comment]
Thx for the feedback Rohit. The metric by itself should be calculating daily unique users. However the views are refreshed approximately every few hours or so and that could cause a double count if a user returns. This is a known issue which is in our backlog.

**Comment by dhendonato** [comment]
Hi, Good day!
Any update on this issue? It still not calculating based on unique users.
Thank you.
