### ISSUE TITLE
New Dataverse Environment requirier a Security Group

### ISSUE THREAD

**Issue by Prov-Matthias** [MicrosoftDocs/power-platform#1931]
When I want to create an environment today and a Security Group is mandatory now.
This is not reflected in this documentation page.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#create-your-environments

![image](https://github.com/MicrosoftDocs/power-platform/assets/57126812/bb57bb21-0a6d-45b7-88ea-26712cbbddbe)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
You can select None for open access. That means the environment is not restricted, which is our recommendation.

**Comment by Prov-Matthias** [comment]
Hi @manuelap-msft 

Ok, I saw that on another page as well. Maybe it would be better for dummies like me if it was described directly here.
Thanks for the info!

Best regards,
Matthias
