### ISSUE TITLE
Connector list miss some

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/power-platform#1941]
Hi, to install COE core component you request to create some prior connection, i think those are missing because i had to create it after importing COE starter kit core component 

Coe Core - Dataverse Legacy
CoE Core - Dataverse (Env Request)
CoE BYODL - Power Query

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-gb/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

all the connections to connectors that the CoE needs are called out here in this list: 
https://learn.microsoft.com/en-gb/power-platform/guidance/coe/setup-core-components#create-connections
![image](https://github.com/MicrosoftDocs/power-platform/assets/55705669/f14014de-2dfc-4b42-8659-cb99cd49ee7d)

When you import the solution, you'll fill out connection references with the established connections - the names you shared are connection references. We don't maintain a list of connection references in our docs as they change all the time, and once you have established the connections they will all be populated correctly on import anyway. 

Hope this helps
Manuela

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jeffangama. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
No further action required here, the connector list is up to date.
