### ISSUE TITLE
Missing Admin | Sync Template v3

### ISSUE THREAD

**Issue by ReneTest998** [MicrosoftDocs/power-platform#1944]
Hello, 

I am currently on version 4.7, and it appears Admin | Sync Template v3 was not included in the core components. 

![image](https://github.com/MicrosoftDocs/power-platform/assets/131083902/09f3711b-bd1b-4aa0-ae86-cc7d89dd680c)

**Comment by manuelap-msft** [comment]
Hello,

this flow has been renamed to Admin | Sync Template v3 (Driver) as we had some issues with the flow name not being unique. It's been updated in our documentation now as well.

Thank you,
Manuela
