### ISSUE TITLE
Not Found error

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/power-platform#195]
You might get the Not Found respond when you run the script though the environment is listed in 

Get-AdminPowerAppSoftDeletedEnvironment

If so, you need to specify the environment name in the script like this format:

Recover-AdminPowerAppEnvironment -EnvironmentName 1111aaa-2aaa-1aaaa-asasdsd-b4g5455g5 -WaitUntilFinished $true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cebc0b7d-f846-a1c9-1deb-09195a7b7980
* Version Independent ID: c628f385-7bb4-3534-2c97-9733d687f9e7
* Content: [Recover environment - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/recover-environment)
* Content Source: [power-platform/admin/recover-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/recover-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@DavidPaf 
Thanks for the feedback. Help documentation will be updated with the above settings.
