### ISSUE TITLE
Security for Environments without CDS

### ISSUE THREAD

**Issue by swettstein** [MicrosoftDocs/power-platform#196]
What about configuring environment security for environments without Common Data Service? It seems that the group membership is not transitive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure environment security - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/database-security)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/database-security.md)
* Service: **power-platform**
* GitHub Login: @manasmams
* Microsoft Alias: **manasma**

**Comment by jimholtz** [comment]
@swettstein 
Configuring user security to resources (apps, data) in an environment needs to be done using security roles, explained in this doc: https://docs.microsoft.com/en-us/power-platform/admin/database-security. This is available to both CDS and non-CDS environments.

Whereas, configuring user access to an environment itself is only possible for CDS environments and this needs to be done through Security Groups: https://docs.microsoft.com/en-us/power-platform/admin/control-user-access
