### ISSUE TITLE
not able to post signIn/tokenExchange activity back to bot in configuring SSO using AAD 

### ISSUE THREAD

**Issue by pryadav** [MicrosoftDocs/power-platform#1964]
<img width="932" alt="Screenshot 2023-05-25 at 10 29 39" src="https://github.com/MicrosoftDocs/power-platform/assets/15320067/e1813fa2-0ad4-43b0-999b-b6dd5111a865">

[Enter feedback here]
- followed https://learn.microsoft.com/en-us/power-virtual-agents/configure-sso?tabs=preview 
- log into custom website using AAD 
- starts chat with 
- signIn/tokenExchange http POST fails with 500 error
- ss attached. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68d60dd9-05e9-9c78-7d7b-53b26a92af06
* Version Independent ID: 282e50ba-61cf-6574-94ad-4dcf82b71a72
* Content: [Configure single sign-on with Azure Active Directory  - Power Virtual Agents](https://learn.microsoft.com/en-us/power-virtual-agents/configure-sso?tabs=preview)
* Content Source: [power-virtual-agents/configure-sso.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/configure-sso.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pryadav. This issue has been assigned to the doc author for review.

**Comment by pryadav** [comment]
I was able to resolve this issue. Looks like it was missing some api-permissions in azure. Closing the issue. Thanks.
