### ISSUE TITLE
Document very outdated

### ISSUE THREAD

**Issue by armely** [MicrosoftDocs/power-platform#1968]
The document is very outdated, it does not align with either of the product thus becoming a nightmare to follow in order to configure ALM Accelerator. 

Please update it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39c2203e-00d5-acb0-9f4b-c2daefe27403
* Version Independent ID: 39c2203e-00d5-acb0-9f4b-c2daefe27403
* Content: [Set up ALM accelerator for Power Platform components manually - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually)
* Content Source: [power-platform/guidance/alm-accelerator/setup-components-manually.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/alm-accelerator/setup-components-manually.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @jenschristianschroder
* Microsoft Alias: **jeschro**

**Comment by jenschristianschroder** [comment]
Thanks for reporting this. We will plan update of the relevant docs.
