### ISSUE TITLE
there is a spelling mistake in the CoE page -- instead of CoE it is printed coE

### ISSUE THREAD

**Issue by yogipappu** [MicrosoftDocs/power-platform#1969]
[Enter feedback here]
Please correct the **coE** to **CoE**. please find the attached. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**
![Screenshot 2023-05-31 at 4 31 18 PM](https://github.com/MicrosoftDocs/power-platform/assets/64506215/bbf551fa-5df1-48d4-a6a6-5a31e7dbda6b)
![Screenshot 2023-05-31 at 4 31 18 PM](https://github.com/MicrosoftDocs/power-platform/assets/64506215/fe7f2bed-fbf2-4282-82cf-c7a2a9966597)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @yogipappu. This issue has been assigned to the doc author for review.

**Comment by sericks007** [comment]
@yogipappu, this issue has been fixed!  The updated content will be published later today.
