### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by stephenedwardprice** [MicrosoftDocs/power-platform#197]
Looks like the first two groups in Consolidated grouping are incorrect:
-E1-, -E2-, -E3- Group 1 – Office 365 Outlook
-E1-, -E2-, -E6- Group 2 – SharePoint, Basecamp 3

I think it should be:
E1, E3, E5
E1, E3, E6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea178b4-f20a-747b-9e84-8b09ab6218d4
* Version Independent ID: e97f75e7-469e-0dc1-319c-0fe0a84c4e2e
* Content: [Data loss prevention policies - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention#feedback)
* Content Source: [power-platform/admin/wp-data-loss-prevention.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/wp-data-loss-prevention.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@stephenedwardprice 
Thanks for the update. This content has been corrected.
