### ISSUE TITLE
XCreateSidePaneActionForEntity - link never works

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/power-platform#1970]
[Enter feedback here]

Here is my code snippet. The notification is shown, and the link is shown for XCreateSidePaneActionForEntity. However, clicking on the link does not work at all. This is an example straight from the documentation.

XSendAppNotification("Title",
    AsType(ThisRecord.Owner, Users),
    "A new account record has been assigned to you",
    [XCreateSidePaneActionForEntity("Parent Account", 1234, "Open parent account", "account", LookUp(Accounts, Account = ThisRecord.'Parent Account'.Account).Account)])

![image](https://github.com/MicrosoftDocs/power-platform/assets/11561396/6ad3ac87-f1de-4fc4-9aab-53cd921f260b)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 636c9143-3812-476a-6b47-b729286d2017
* Version Independent ID: 636c9143-3812-476a-6b47-b729286d2017
* Content: [XSendAppNotification and related functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-send-app-notification)
* Content Source: [power-platform/power-fx/reference/function-send-app-notification.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-send-app-notification.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by jaredha** [comment]
Thanks for raising this issue, @ahmadpirani. After investigation, we found that there was an issue with the rollout of the required components. The Power Fx functions have been available in environments for a few weeks, but the changes to the back end API to support the new actions is still rolling out to environments. These changes are available in version 9.2.23052.00226. When your Power Platform environment is updated to at least that version, the notifications links should then work. The rollout for this version is almost complete, so it's likely that your environment has now been updated.

For the syntax, this should work. You shouldn't need to use LookUp to get the account record for the parent account.

XSendAppNotification("Title",
    AsType(ThisRecord.Owner, Users), 
    "A new account record has been assigned to you", 
    [XCreateSidePaneActionForEntity( 
        "Parent Account", 
        1234, 
        "Open parent account", 
        "account", 
        ThisRecord.'Parent Account'.Account 
        )
    ]
)
