### ISSUE TITLE
Wrong screenshot for the Azure AD app registration

### ISSUE THREAD

**Issue by TodoroskiAco** [MicrosoftDocs/power-platform#1971]
[Create an Azure AD app registration to connect to Microsoft Graph](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-an-azure-ad-app-registration-to-connect-to-microsoft-graph) under step #9 there is a screenshot which is irrelevant to the topic. Perhaps you would like to fix it :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TodoroskiAco. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Thank you, fixed for the next docs update.

**Comment by manuelap-msft** [comment]
This has been updated. Closing out.
