### ISSUE TITLE
Invoking admin.powerplatform APIs

### ISSUE THREAD

**Issue by Rajen-Sharma** [MicrosoftDocs/power-platform#198]
Hi Guys, 

Is there an example of calling below powerplatform API through powershell. I am looking at capturing the data usage of CRM instances to monitor them efficiently.

https://admin.powerplatform.microsoft.com/api/Capacity/environments

Thanks

**Comment by jimholtz** [comment]
@Rajen-Sharma 
There's this content which we update as new cmdlets are added:
https://docs.microsoft.com/power-platform/admin/powerapps-powershell#power-apps-cmdlets-for-administrators-preview

**Comment by Rajen-Sharma** [comment]
Thanks @jimholtz 
Don't think there is any at the moment around Capacity, will keep checking the link. Appreciate your response.
