### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by jef3003** [MicrosoftDocs/power-platform#199]
Link: "What are powerapps tools" gives page not found.
(https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-overview.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc6c5a2-f29f-12bd-c619-a1b8503517c5
* Version Independent ID: 773f57ee-ff34-04d0-43d9-6cc268e6a8c1
* Content: [Application lifecycle management (ALM) basics with Microsoft Power Platform - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/alm/basics-alm#feedback)
* Content Source: [power-platform/alm/basics-alm.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/basics-alm.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@jef3003 - thanks for bringing this to our attention. Should be fixed now. Closing issue.
