### ISSUE TITLE
CoE Kit Roles clarification please. 

### ISSUE THREAD

**Issue by Travis-at-Kiewit** [MicrosoftDocs/power-platform#1991]
the sentence "Microsoft Power Platform service admin, global tenant admin, or Dynamics 365 service admin. " reads as if a user must have the roles Microsoft Power Platform service admin and global tenant admin or Dynamics 365 service admin. When you stick a comma in between a set of options and throw OR on the last one. The language isn't as clear or concise as it could be. I find that anyone I talk to regarding Microsoft Power Platform service admin, global tenant admin, or Dynamics 365 service admin roles for PPAC is some folks think you have to have PPA and Global roles to facilitate the CoE Kits, or Global and Dynamics 365 roles. 

Do you are do you not HAVE to have a Global admin role to facilitate the CoE starter kit plus updates??

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
I'm not sure I understand. 

Like the documentation states, you need an
Microsoft Power Platform service admin OR global tenant admin OR Dynamics 365 service admin

Let me know how we can improve the sentence so it's more clear?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Travis-at-Kiewit. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
