### ISSUE TITLE
how patch API counts

### ISSUE THREAD

**Issue by huyi2218** [MicrosoftDocs/power-platform#20]
When we call a Patch function within a PowerApps app to modify a set of records, is that counted as 1 API call or whatever number of records we’re adding/updating in this Patch call?
See this page for reference about the function: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch

**Comment by tapanm-MSFT** [comment]
@huyi2218 thank you for submitting your question. Will review and reach out with the answer.

**Comment by tapanm-MSFT** [comment]
Thank you for your patience. It will be more than 1 API call. For example, a ClearCollect() for table with 7 record updates shows at least 7 POSTs while tracing the browser.
