### ISSUE TITLE
App Registration

### ISSUE THREAD

**Issue by joepurnell88** [MicrosoftDocs/power-platform#200]
Does the ps interface support the use of a app registration, or must it be username and password?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc997189-b9f4-653c-1188-5663e1a6367e
* Version Independent ID: 3113cafa-56e7-0e45-999f-fa18d50e28cb
* Content: [Deploy packages using Dynamics CRM Package Deployer and Windows PowerShell - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/deploy-packages-using-package-deployer-windows-powershell#feedback)
* Content Source: [power-platform/admin/deploy-packages-using-package-deployer-windows-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/deploy-packages-using-package-deployer-windows-powershell.md)
* Service: **power-platform**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
The package deployer PowerShell Import-CrmPackage cmdlet uses the -CrmConnection parameter that requires the environment name and credential object (made up of user's UNC address and password) as described here: https://docs.microsoft.com/en-us/powershell/powerapps/get-started-onlinemanagementapi?view=pa-ps-latest#establish-your-credentials-and-connection. 

Closing issue.
