### ISSUE TITLE
Setup flow missing in core components v 4.9

### ISSUE THREAD

**Issue by rahine** [MicrosoftDocs/power-platform#2002]
When manually turning on the inventory components the the Turn On Setup Flows documentation ask you to turn on  "Command Center App > Get CoE Flows". 
![image](https://github.com/MicrosoftDocs/power-platform/assets/64918957/b8330ae6-d95c-4f89-b780-82f42fd166fd)

This flow does not exist in core components solution 4.9
![image](https://github.com/MicrosoftDocs/power-platform/assets/64918957/bbe8a431-4904-4f90-ac3c-f0398f1ceb5f)

![image](https://github.com/MicrosoftDocs/power-platform/assets/64918957/0d9e2b10-5a31-4167-b7c2-8665f81a5d3d)

CLEANUP - Admin | Sync Template v3 (Connection Status) is also missing from core components

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rahine. This issue has been assigned to the doc author for review.

**Comment by rahine** [comment]
No problem always happy to help!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by manuelap-msft** [comment]
Update has been published today!
