### ISSUE TITLE
cannot modify frame-ancestor if enforcement is disabled

### ISSUE THREAD

**Issue by briangre** [MicrosoftDocs/power-platform#2004]
In the second example on this page:  https://learn.microsoft.com/en-us/power-platform/admin/content-security-policy#example-2

The image shows that CSP is disabled for Canvas apps and yet the frame-ancestor is set to custom. In the actual UI, if enforcement is disabled for Canvas then you cannot modify the frame-ancestor. The option to modify frame-ancestor only is displayed if enforcement is enabled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31dbf39f-257e-cbd1-b100-c63428608b1e
* Version Independent ID: 31dbf39f-257e-cbd1-b100-c63428608b1e
* Content: [Content security policy - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/content-security-policy)
* Content Source: [power-platform/admin/content-security-policy.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/content-security-policy.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @JesseParsons
* Microsoft Alias: **jeparson**

**Comment by JesseParsons** [comment]
Hi @briangre - the custom frame-ancestor is enabled in Example 2 because **_reporting_** is turned on.  If either reporting and/or enforcement are turned on, then the `Content-Security-Policy` or `Content-Security-Policy-Report-Only` header are used and can be customized.
