### ISSUE TITLE
Control who can allocate add-on capacity is missing

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/power-platform#201]
In my tenant, the section "Who can allocated add-on capacity to environments" is missing. I believe this is because I haven't purchased any capacity add-ons, or? If yes, please update the article accordingly.
One more comment, for now I cannot see this configuration, but i can change it using PowerShell. Maybe documenting the PowerShell command will be useful for the users, or? 

Getting the setting
Get-TenantSettings | select disableCapacityAllocationByEnvironmentAdmins

Changing the value
$settings = @{ disableCapacityAllocationByEnvironmentAdmins = $true }
Set-TenantSettings $settings 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0cbf8c-5c12-5aa2-3786-392d0f498303
* Version Independent ID: 2774f5ca-1c86-4fe6-c296-6f7f45aa6702
* Content: [Capacity add-ons for Power Apps and Power Automate - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on?source=docs#feedback)
* Content Source: [power-platform/admin/capacity-add-on.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-add-on.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@ahamin01 
Your assumption is correct and is indicated in this sentence:
If your organization has purchased capacity add-ons, an Add-ons tile appears on the Capacity screen in the Power Platform admin center.
