### ISSUE TITLE
Incomplete, Wrong and Missing steps?

### ISSUE THREAD

**Issue by tmsquared** [MicrosoftDocs/power-platform#202]
7. appears to be lcoked (as a SysAd) and defaults to one or the other.
8. I couldn't go directly from #8 to #9. You have to SAVE then the Select Data Fields appears.
9. Unless you have to create a template first? You can't just pull one and it has to be an XML file?  

Picking some of this up from other posts/blogs...but the 10 steps above do not allow you to create a Mail Merge Template!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0a4189-13aa-26fb-e2d9-76fa745da9c1
* Version Independent ID: 0a658845-bbed-539f-23c1-dae24def7f84
* Content: [Work with mail merge templates - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/work-mail-merge-templates#feedback)
* Content Source: [power-platform/admin/work-mail-merge-templates.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/work-mail-merge-templates.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@tmsquared 
Thanks for the feedback. I've done a rewrite to address the user interface currently in the product. I'll make another pass doing more revisions and adding images as time allows.
