### ISSUE TITLE
Please provide an example of SelectColumns with multiple columns.  Or state how this is presented as parameters to the function. 

### ISSUE THREAD

**Issue by StrawberryAnemone** [MicrosoftDocs/power-platform#2020]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b83b2196-8c32-86db-3c76-5464a62ae70f
* Version Independent ID: b83b2196-8c32-86db-3c76-5464a62ae70f
* Content: [AddColumns, DropColumns, RenameColumns, and ShowColumns functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-table-shaping)
* Content Source: [power-platform/power-fx/reference/function-table-shaping.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-table-shaping.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jorisdg** [comment]
Although there is no specific example with multiple columns, the syntax section explains the parameters: ShowColumns(table, "column1", "column2", "column3")

Note that there is no SelectColumns() function and I'm assuming you meant ShowColumns()
