### ISSUE TITLE
Account and Contact cannot be included in a solution

### ISSUE THREAD

**Issue by rappen** [MicrosoftDocs/power-platform#204]
This text seems quite misleading:
_Notice that not all entities can be included in a solution. For example, the account and contact entities aren't solution components._

It looks like you cannot include these entities in a solution, while they are probably the most common entities to be included in any solution anywhere since forever.
https://docs.microsoft.com/en-us/power-platform/alm/basics-alm#solutions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc6c5a2-f29f-12bd-c619-a1b8503517c5
* Version Independent ID: 773f57ee-ff34-04d0-43d9-6cc268e6a8c1
* Content: [Application lifecycle management (ALM) basics with Microsoft Power Platform - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/alm/basics-alm#solutions)
* Content Source: [power-platform/alm/basics-alm.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/basics-alm.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@rappen - The text has been revised to better clarify a few tables/entities that can't be added to a solution.

 Notice that not all entities can be included in a solution. For example, the Application User, Custom API, and Organization Setting system tables can't be added to a solution.
