### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by MichaelChadbourne** [MicrosoftDocs/power-platform#2041]
[Enter feedback here]
Hi Guys

Just a small thing, there is a smelling error under Personas for Fusion Development, Bellow should be Below. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cc1b143-7a86-2db1-3d08-5e0f066f78f3
* Version Independent ID: 3cc1b143-7a86-2db1-3d08-5e0f066f78f3
* Content: [fusion development in Power Platform - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/fusion-development)
* Content Source: [power-platform/developer/fusion-development.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/fusion-development.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @marcelbf
* Microsoft Alias: **marcelbf**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MichaelChadbourne. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Thanks @MichaelChadbourne  and @RedsGT
