### ISSUE TITLE
Feedback: Provide guidance on support for GCCH and DoD

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/power-platform#2044]
Hey Team!  It says here that Power Platform CLI is not approved for GCCH and DoD yet when you look at the CLI command it appears it should work.

![image](https://github.com/MicrosoftDocs/power-platform/assets/26752719/05e9a782-2b1f-4476-a884-66a5d9911cd7)

CLI: https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/auth#--cloud--ci

![image](https://github.com/MicrosoftDocs/power-platform/assets/26752719/995c3be5-7271-49ad-bf81-04c97f9f7fd0)

I think it will help provide guidance to our customer to clarify the support.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Version Independent ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Content: [Microsoft Power Platform CLI - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction)
* Content Source: [power-platform/developer/cli/introduction.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/introduction.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @snizar007
* Microsoft Alias: **snizar**

**Comment by JimDaly** [comment]
@snizar007 

Unless there are some regions we do not support, I think it may be clearer to remove the whole paragraph?
Or just change it to say that all regions are supported.

It seems to be an artifact of a time when only partial support was offered? If all regions are supported, then there shouldn't be a need to call out a subset.

**Comment by snizar007** [comment]
Hello @brmcmill - 
Please see REMARKS for clarity: https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/auth#remarks 
Thank you.
