### ISSUE TITLE
Wrong install command

### ISSUE THREAD

**Issue by AlexSchwerzmann** [MicrosoftDocs/power-platform#2051]
Hi guys

I think, the install cmd is wrong.

Your docu says:
`dotnet tool install --global Microsoft.PowerApps.CLI.Tool`

probably correct would be:
`dotnet tool install --global Microsoft.PowerApps.CLI`

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Version Independent ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Content: [Microsoft Power Platform CLI - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction)
* Content Source: [power-platform/developer/cli/introduction.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/introduction.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @snizar007
* Microsoft Alias: **snizar**

**Comment by JimDaly** [comment]
@AlexSchwerzmann 

I just tested this using the `dotnet tool install --global Microsoft.PowerApps.CLI.Tool` command in the doc:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\{me}> dotnet tool install --global Microsoft.PowerApps.CLI.Tool

Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.306

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
You can invoke the tool using the following command: pac
Tool 'microsoft.powerapps.cli.tool' (version '1.24.3') was successfully installed.
PS C:\Users\{me}>
```

Of course, I already had this installed... but it doesn't throw any error.

Why do you think this is not correct?

**Comment by AlexSchwerzmann** [comment]
Hi Jim

Thanks for your fast answer. Indeed, I tried on another test system now and there it worked. I thought, it's `.Tool` too much because when installing from https://aka.ms/PowerAppsCLI package, it seems to call only `dotnet tool install --global Microsoft.PowerApps.CLI`

However, `dotnet tool install --global Microsoft.PowerApps.CLI.Tool `is very correct!

Sorry for that one...

Regards
Alex
