### ISSUE TITLE
Request to add clear step by step set up of Azure Key Vault in relation to COE setup

### ISSUE THREAD

**Issue by robertmaraan** [MicrosoftDocs/power-platform#2052]
[Enter feedback here]
The setup of for Azure Key Vault found in this [link](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables) in relation to updating environment variables is generic. Maybe you can add COE specific so it would be easier to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-coe-admin-command-center-app)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @robertmaraan. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Made some changes to this section, update published today!
