### ISSUE TITLE
Where can I find the step "In the upper-right corner, select Test, and then select I'll perform the trigger action."

### ISSUE THREAD

**Issue by robertmaraan** [MicrosoftDocs/power-platform#2055]
[Enter feedback here]
Where can I find the step "In the upper-right corner, select Test, and then select I'll perform the trigger action."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a50a381e-f728-50ed-e5d4-5605b948c57f
* Version Independent ID: a50a381e-f728-50ed-e5d4-5605b948c57f
* Content: [Get started setting up the governance components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov)
* Content Source: [power-platform/guidance/coe/before-setup-gov.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/before-setup-gov.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @robertmaraan. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
If you have the flow open in edit mode, you'll have a Test button in the top right corner and from there you can select Manually > I'll perform the trigger action.
![image](https://github.com/MicrosoftDocs/power-platform/assets/55705669/af4f7ad9-7d74-4764-842c-b810c4efdfb3)

**Comment by robertmaraan** [comment]
Yes, and it does not specifically says how it is laid out in the UI.

**Comment by manuelap-msft** [comment]
Ok, which step are you struggling with there? The product UI should be intuitive enough to follow and trigger the flow.

**Comment by robertmaraan** [comment]
Yes agree it is intuitive. but the documentation has to tell it how exactly
the experience should be.

**Comment by manuelap-msft** [comment]
With frequent changes to the Product UX, it'd be very hard and expensive for us to maintain screenshots for every single step and we'd have to frequently change them and review them. It's best practice for our docs to only include screenshots and step by step instructions were absolutely necessary, to make maintenance easier. If steps are intuitive enough, we will not explain them - as if they change, they'd be out of date and it'd be even more difficult to follow.
