### ISSUE TITLE
AppTemplatePhone.msapp and AppTemplateTablet.msapp files are not editable.

### ISSUE THREAD

**Issue by robertmaraan** [MicrosoftDocs/power-platform#2057]
[Enter feedback here]
AppTemplatePhone.msapp and AppTemplateTablet.msapp files are not editable.

The message "You are missing the necessary privilege to edit the selected Canvas app." appears when the apps are clicked.

Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81d37c64-f695-5fa4-5c81-d1045155bf1b
* Version Independent ID: 68f35a4b-7a59-f681-ef38-62a40437bdab
* Content: [Theming components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/theming-components?source=recommendations)
* Content Source: [power-platform/guidance/coe/theming-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/theming-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @robertmaraan. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
You have to be the app owner or co-owner to be able to edit the app.

**Comment by robertmaraan** [comment]
> You have to be the app owner or co-owner to be able to edit the app.

Which I am.

<img width="715" alt="image" src="https://github.com/MicrosoftDocs/power-platform/assets/78089983/faba7a34-d395-40a9-9852-5458bdba0a64">

**Comment by manuelap-msft** [comment]
Can you try these steps:

1. Go to [make.powerapps.com](https://make.powerapps.com/), and then go to your CoE environment where the theming solution is installed.
1. On the left pane, select **Apps**
1. Select Edit to edit AppTemplatePhone canvas app.

**Comment by robertmaraan** [comment]
The app can be seen as editable from outside the Solution space.[image:
image.png]

**Comment by manuelap-msft** [comment]
Update has just been published. Closing out!
