### ISSUE TITLE
Unable to locate the step, Browse Files, and then select the template file downloaded from the theme gallery.

### ISSUE THREAD

**Issue by robertmaraan** [MicrosoftDocs/power-platform#2058]
[Enter feedback here]
How to perform this step?
Select Open > Browse Files, and then select the template file downloaded from the theme gallery.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a50a381e-f728-50ed-e5d4-5605b948c57f
* Version Independent ID: a50a381e-f728-50ed-e5d4-5605b948c57f
* Content: [Get started setting up the governance components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov)
* Content Source: [power-platform/guidance/coe/before-setup-gov.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/before-setup-gov.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @robertmaraan. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Looks like the Product UX for this has changed and you can now find open under the ... next to Settings
![image](https://github.com/MicrosoftDocs/power-platform/assets/55705669/d99eb4e9-d6df-4ae5-9b13-100af8d8d7d6)

Will update the documentation to reflect this.

**Comment by robertmaraan** [comment]
Thanks!
