### ISSUE TITLE
Please provide example of accessing the X column from the First function

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/power-platform#2069]
Thank you for showing examples of how to get specific rows. Please show example of how t reference specific Columns. If unable to reference a column please state as much. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48c1eee2-a654-b2d2-f89f-73469c617071
* Version Independent ID: 48c1eee2-a654-b2d2-f89f-73469c617071
* Content: [First, FirstN, Index, Last, and LastN functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-first-last)
* Content Source: [power-platform/power-fx/reference/function-first-last.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-first-last.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @devman2k. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
These functions either return a record or a table of records, depending on the function. Accessing fields on a record is consistent across Power Fx using the . (dot) operator, you can find more information about this in the article about Tables, Records and Fields: https://learn.microsoft.com/en-us/power-platform/power-fx/tables#fields

In the article you linked, there's one example showing how to access a field from a record returned from the Index() function, in one expression: Index( IceCream, 4 ).Quantity
