### ISSUE TITLE
Unable to select Flow inside authoring canvas

### ISSUE THREAD

**Issue by BeigeBadger** [MicrosoftDocs/power-platform#208]
I followed the steps [here](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-flow#create-a-new-flow-from-the-power-virtual-agents-authoring-canvas) to create a flow using the GUI within PVA. According to [this documentation](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-flow#flows-created-from-the-power-virtual-agents-authoring-canvas-are-immediately-available-to-the-bot) the flow should be immediately available to selected from the list of actions (which it is), however I am unable to select the created flow. When I click on it nothing happens. Yet I can create new flows, and even select some existing ones.

I have tried moving the flow into a different solution but that didn't seem to make a different. I also tried recreating the flow from scratch but that also failed. I have tried different browsers and with browser extensions disabled, but I still get Javascript errors in the console whenever I attempt to select specific flows from the actions list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 010269b1-237d-eb71-7014-9d8ee8a29659
* Version Independent ID: b96cb487-cfc9-e60b-12e9-3c02efa06b99
* Content: [Automate Power Virtual Agents bot actions with flows - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-flow#feedback)
* Content Source: [power-virtual-agents/advanced-flow.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-flow.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
I believe this was answered on the community site: https://powerusers.microsoft.com/t5/Calling-Actions-from-PVA/Unable-to-call-Flow-from-within-PVA-topic/m-p/556403
