### ISSUE TITLE
Reference documentation on the App object missing?

### ISSUE THREAD

**Issue by wimcraig** [MicrosoftDocs/power-platform#2084]
Surely there needs to be more documentation on the App object and how it e.g. determines it Width and Height values. Can the link to such documentation be included here?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ccb9938d-ce23-17cb-cf5c-45301bdf1dc7
* Version Independent ID: ccb9938d-ce23-17cb-cf5c-45301bdf1dc7
* Content: [App object in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/object-app)
* Content Source: [power-platform/power-fx/reference/object-app.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/object-app.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @wimcraig. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
Unfortunately we don't have detailed reference documentation for a lot of properties including on controls, etc. Currently for the app object only formula properties have been documented, and that will unfortunately likely stay that way for the foreseeable future as we do not have any priority for this sort of updates.
