### ISSUE TITLE
CoE fails to install without Creator Kit Core

### ISSUE THREAD

**Issue by jdottdotmess** [MicrosoftDocs/power-platform#2088]
Please update the instructions to remind users to install the Creator Kit Core before attempting to import the Core kit. Right befoore this section. 

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-using-the-setup-wizard

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up inventory components - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jdottdotmess. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
Hello,

this is already highlighted here in the Before you Start section
![image](https://github.com/MicrosoftDocs/power-platform/assets/55705669/2541a79d-0f11-413e-b40c-d2f92a6c60e9)

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#before-you-start
