### ISSUE TITLE
Audit Logs retention time in Dataverse (CoE Starter Kit Audit Log Component)?

### ISSUE THREAD

**Issue by ramonabadea** [MicrosoftDocs/power-platform#2093]
Hello,

Not sure if this is the right location to ask this, but: Could someone please let me know for how long are the audit logs records kept by default in Dataverse when we use the CoE Starter Kit Audit Log sync flow? 🙂

Thanks in advance,
Ramona

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26a9f869-6c71-46e5-341e-4b61b427ff01
* Version Independent ID: 26a9f869-6c71-46e5-341e-4b61b427ff01
* Content: [Collect audit logs using an HTTP action - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http)
* Content Source: [power-platform/guidance/coe/setup-auditlog-http.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog-http.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

by default, they are kept in the Dataverse table from the moment you set up the Audit Log sync flows forever. There's no retention/delete policies set on that table. If the table is taking up a lot of space in your environment, you may want to set retention policies or perform a bulk delete job (e.g. delete audit log events older than 2 years, 1 year,...) depending on how long back your reporting requirements are. 

In the future - for general questions related to the CoE kit (not the documentation) it's best to raise questions in the CoE Starter Kit repository here: https://github.com/microsoft/coe-starter-kit/issues/new/choose - one of the issue types is Question.

Hope that helps,
Manuela

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ramonabadea. This issue has been assigned to the doc author for review.

**Comment by ramonabadea** [comment]
Thanks a lot for the info, @manuelap-msft! Actually, this does help a lot to be known.
For future references & questions, will use the coe-starter-kit repo. 

Ramona
