### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by infoseconline-pt** [MicrosoftDocs/power-platform#2095]
[Enter feedback here]

This link is not working: https://aka.ms/PVATeamsAppazure-portal=true

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85d9a99e-c1d1-d2c6-3306-b9603ac5db77
* Version Independent ID: 799a66d3-bf5b-0309-794f-41396aabb619
* Content: [Overview - Power Virtual Agents](https://learn.microsoft.com/en-us/power-virtual-agents/fundamentals-what-is-power-virtual-agents)
* Content Source: [power-virtual-agents/fundamentals-what-is-power-virtual-agents.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/fundamentals-what-is-power-virtual-agents.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks, I've queued the update for that link and it should go live shortly.
