### ISSUE TITLE
No renderer for this activity (go to another topic> use escalate )

### ISSUE THREAD

**Issue by AndrewCussons** [MicrosoftDocs/power-platform#21]
Workaround select  "go to another topic -&gt; search for and select Escalate (system topic) and it is easier than writing custom code because you can just add some text and a link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3066493-cbbd-bcfa-df8f-594966ef2a38
* Version Independent ID: ef53a9ed-7794-4873-24c5-39cf03bff477
* Content: [Use hand-off to live agent - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-hand-off)
* Content Source: [power-virtual-agents/advanced-hand-off.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-hand-off.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for the feedback - I'll be adding in a note about doing this shortly!
