### ISSUE TITLE
PowerPlatformAdminDashboard

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/power-platform#210]
Hi

In the Power BI Desktop client, open the PowerPlatformAdminDashboard.pbix file, which can be found in the CoE Starter Kit you downloaded from aka.ms/CoeStarterKitDownload.

Should this be Dashboard-PowerPlatformAdminDashBoard_2020-02-12_basic.pbix or Dashboard-PowerPlatformAdminDashBoard_2020-05-04_advanced.pbix ?

Regards

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c365c412-6317-0eb4-b7a1-0a5cc84b1cbd
* Version Independent ID: 9e39031d-66dd-bf29-1b5c-a93608badc60
* Content: [Set up the Power BI dashboard - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi)
* Content Source: [power-platform/guidance/coe/setup-powerbi.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-powerbi.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Either, based on your requirements. The advanced one contains the tabs for risk assessments and archiving as well as the embedded apps. The basic one only includes the tabs to get insights into your tenant wide usage.

We'll work on making that clearer in the documentation. Thanks for the feedback.

Adding @JeneferM-MSFT
