### ISSUE TITLE
CoE Admin PowerBI Dashboard - Manage App Access Tab not working 

### ISSUE THREAD

**Issue by Labhesh007** [MicrosoftDocs/power-platform#2100]
Hello Team,

We need documentation on what "Manage App Access", "Manage Flow Access" Tab does on the Power Bi Dashboard( Production_CoEDashboard_August2023.pbit ), 

The issue is explained below: 
1) When Configured the "Manage App Access" tab. with a Single Environment and AppID( Environment ID, App IDm Fields). It does not populate all the users in that environment, as you see in screenshot it is only showing 1 admin, but there was a additional admin added but it did not show. 

2). in another client tenant the same  ,"Manage App Access" tab was showing multiple admin and it was showing the admin even from the different environment which are not part of the environment which we have filtered. 

3) When adding new user using the "Manage App Access", it is giving error as "failed to call helper"
3) all above 2 issues are also coming for "Manage Flow Access:.

Can you kindly share the detailed documentation around this. 

thank  you
Labhesh

![Error_1234](https://github.com/MicrosoftDocs/power-platform/assets/13569445/31b0d556-9d59-4302-884e-a087e6b89c7f)

![Error123](https://github.com/MicrosoftDocs/power-platform/assets/13569445/a012b90e-bcdc-4602-ac59-8a72b97683a9)

 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c365c412-6317-0eb4-b7a1-0a5cc84b1cbd
* Version Independent ID: 9e39031d-66dd-bf29-1b5c-a93608badc60
* Content: [Set up the Power BI dashboard - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard)
* Content Source: [power-platform/guidance/coe/setup-powerbi.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-powerbi.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Labhesh007. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
In this repo, we're only able to triage issues related to the documentation. If you experience issues with the features and capabilities of the CoE kit, please raise an issue here: https://github.com/microsoft/coe-starter-kit/issues

Thank you
Manuela
