### ISSUE TITLE
Step 5 of Option 2: Adding Custom Connector to the DLP using PowerShell Add-CustomConnectorToPolicy  fails looking for a Connector Type

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/power-platform#211]
Hi Manuela

In PowerShell, use Add-CustomConnectorToPolicy to add the custom connector to your policy.

PowerShell

Copy
Add-CustomConnectorToPolicy -PolicyName {your policy name GUID} -ConnectorName {the nName you copied from above} -GroupName hbi -ConnectorId /providers/Microsoft.PowerApps/scopes/admin/environments/{your environment GUID{/apis/{your connector name} - fails
![PowerShell Error](https://user-images.githubusercontent.com/8484048/81707096-4c8c6380-9468-11ea-8416-a478fd6002f4.jpg)  - looking for a Connector Type which it says is an empty string.

REgards

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d61c7e5-8eda-2412-1bef-ffc9b74887bb
* Version Independent ID: 45d039f7-eb71-efdb-334e-2dad2db5aac1
* Content: [Limitations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#Custom-Connectors-and-DLP)
* Content Source: [power-platform/guidance/coe/limitations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/limitations.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Can you try -Connector Type Custom

**Comment by NPrice99** [comment]
Will do – I am assuming there is no space between Connector and Type

**Comment by manuelap-msft** [comment]
Yes, no space! That was an autocorrect issue

**Comment by NPrice99** [comment]
Yes -ConnectorType “Custom” works

**Comment by manuelap-msft** [comment]
Awesome, will add that to the documentation with the next release

**Comment by NPrice99** [comment]
Am now getting 404 error – Resource not found for the segment “UnifiedAuditLog”.  I suspect that Audit Logging is not switched on yet.
