### ISSUE TITLE
Hyperlink bad markup... at the bottom

### ISSUE THREAD

**Issue by sasrsc** [MicrosoftDocs/power-platform#2116]
[Enter feedback here]
https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern#app-and-flow-archive
the last few paragraph's seem to be missing a closing a tag for the hyperlink so everything is hyperlinked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3d9f529-ccac-c9f5-8133-a3c31f1a6f3e
* Version Independent ID: 099d9362-d7be-3df2-cab2-0f68e3f28dfd
* Content: [Govern with the CoE Power BI dashboard - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern)
* Content Source: [power-platform/guidance/coe/power-bi-govern.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/power-bi-govern.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sasrsc. This issue has been assigned to the doc author for review.
