### ISSUE TITLE
English to be corrected to paragraph reads correctly

### ISSUE THREAD

**Issue by sletley** [MicrosoftDocs/power-platform#2118]
The end of the page there is a bulleted point in the last sentence of the page that reads as follows.

_ALM Accelerator for Makers (AA4M) - Contains a reference app and GitHub workflows to demonstrate allow makers to source control and deploy their solutions in a limited fashion._ 

This sentence does not read properly and the English should be corrected. Specifically I refer to the part "..workflows to demonstrate allow makers..." which does not read correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f114490b-229f-3825-8d46-16afaf43a4c5
* Version Independent ID: d6a29e5e-7731-78f2-991f-0137e3bbb81b
* Content: [CoE Starter Kit explained: building blocks and add-ons - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/starter-kit-explained)
* Content Source: [power-platform/guidance/coe/starter-kit-explained.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/starter-kit-explained.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sletley. This issue has been assigned to the doc author for review.

**Comment by manuelap-msft** [comment]
The documentation has now been updated!
