### ISSUE TITLE
I miss a command to add security group in the creation of the instance.

### ISSUE THREAD

**Issue by javiercheke** [MicrosoftDocs/power-platform#2121]
https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/admin#advanced-creation-of-an-environment

Maybe the config.json in the future can have the security groups as a parameter to use in the creation of the instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 488078c6-838d-1722-114e-4eb64d94aa0d
* Version Independent ID: 488078c6-838d-1722-114e-4eb64d94aa0d
* Content: [Microsoft Power Platform CLI admin command group - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/admin)
* Content Source: [power-platform/developer/cli/reference/admin.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/reference/admin.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @snizar007
* Microsoft Alias: **snizar**

**Comment by JimDaly** [comment]
@javiercheke 

Thanks for your feedback.

Issues reported against the documentation must include some specific feedback to be actionable, preferably relating to a specific topic. This appears to be a feature request. 

Use [github.com/microsoft/powerplatform-build-tools/discussions](https://github.com/microsoft/powerplatform-build-tools/discussions) to view and submit feedback for PAC CLI.

@snizar007  FYI
