### ISSUE TITLE
Reserving publisher's prefix

### ISSUE THREAD

**Issue by shlemonz** [MicrosoftDocs/power-platform#2125]
[Enter feedback here]
How do we reserve publisher's prefix? for D365 Business Central we use d365val@microsoft.com, if same email applies to Power Platform App Source submission then, this email should be mentioned here. See **Affixes Requirements for Extensions** from the link below:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70abf16d-ef73-cdfc-1f92-d01dd8f265e5
* Version Independent ID: 70abf16d-ef73-cdfc-1f92-d01dd8f265e5
* Content: [Step 2: Create a managed solution for your app (Microsoft Dataverse) - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/appsource/create-solution-app)
* Content Source: [power-platform/developer/appsource/create-solution-app.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/appsource/create-solution-app.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @shlemonz. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@shlemonz 
I don't believe that there is a way for an ISV to reserve a publisher prefix. You need to choose a name that will clearly identify your company, but anyone else could create their own publisher that uses the same value.

Assigning this to @angela21k to confirm.

**Comment by shlemonz** [comment]
I'm not sure that is a good idea. How come Business central app submission
processes includes an email to reverse a prefix?
Your suggestion allows object names conflict that are going to error out on
a customer when they buy apps that have the same table and prefix names
from different vendors and that something can be easily prevented by
reserving the prefix/suffix like Dynamics 365 Business Central has done.

**Comment by shlemonz** [comment]
Hi @angela21k <https://github.com/angela21k> , please clarify what you mean
by that is correct, like is it ok to let the customer face object names
conflicts when installing solutions from App Source?
I'm a bit confused here, this is not about manually installing private apps
on a customer's environment, it's more about the apps published in App
Source. So next question will be who is going to pay for conflicted objects
names? First app ISV or the second App ISV?

**Comment by angela21k** [comment]
@shlemonz I meant that Jim's statement is correct, there is no way to reserve a publisher prefix for apps published to AppSource. Although this is a capability available for BC products, this is not available for CE and Power Platform apps published on AppSource today. We don't have any direction on "who is going to pay for conflicted objects names" but if you've experience this, please feel free to provide more details so we can better understand and prioritize the need.

**Comment by shlemonz** [comment]
Ok, thanks  @angela21k <https://github.com/angela21k>  for the
clarification.
