### ISSUE TITLE
How to find the Bot ID in power virtual agent portal?

### ISSUE THREAD

**Issue by zhenchaoni** [MicrosoftDocs/power-platform#2126]
In the "Get Direct Line token" section of this document, it requires a Bot ID to call the API.
GET https://powerva.microsoft.com/api/botmanagement/v1/directline/directlinetoken?botId=<ENTER-YOUR-BOTID>&tenantId=<ENTER-YOUR-TENANTID>

We can find the Tenant ID from the bot details page. **But the Bot app ID is not the Bot ID.**. As a workaround, we find the bot ID from the browser URL.
<img width="980" alt="image" src="https://github.com/MicrosoftDocs/power-platform/assets/10322359/332235bc-4009-4688-9da1-579b1f21a564">

My question is: Is there a place in power virtual agent portal which shows the correct Bot ID?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9865af04-81ed-3c40-e245-a9f85a3c947a
* Version Independent ID: c0c7d6d8-d210-4810-67f9-6f1d0e933d07
* Content: [Add a chatbot to mobile and web apps - Power Virtual Agents](https://learn.microsoft.com/en-us/power-virtual-agents/publication-connect-bot-to-custom-application#retrieve-your-power-virtual-agents-bot-parameters)
* Content Source: [power-virtual-agents/publication-connect-bot-to-custom-application.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/publication-connect-bot-to-custom-application.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @zhenchaoni. This issue has been assigned to the doc author for review.

**Comment by johnmichalak** [comment]
The document has been updated and the changes have been published and should be live later today.
