### ISSUE TITLE
Please improve documentation and give customers the option to define settings themselves

### ISSUE THREAD

**Issue by lantrobin** [MicrosoftDocs/power-platform#2127]
Please update documentation about configuration opportunities for Power Platform Administrators. 
Curently the text is misleading. 

Please also provide us (as a customer) the option to configure cleanup settings, criteria, time limits etc based on usage. Ideally we as a customer would like to configure the emails that is sent out, so you at Microsoft do not contact business users directly. 
Please consider Enterprise IT processes, that you at Microsoft should not take actions without letting customers decide themselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb4f7d04-385f-8955-949c-b0d55c431919
* Version Independent ID: 7a5ea130-6772-f330-67fb-32fa1a193d07
* Content: [Dataverse for Teams environment management - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/teams-governance)
* Content Source: [power-platform/guidance/coe/teams-governance.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/teams-governance.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The documentation has been updated to remove the misleading / confusing language!
