### ISSUE TITLE
Please add links for power apps player

### ISSUE THREAD

**Issue by JeneferM-MSFT** [MicrosoftDocs/power-platform#213]
The document lists most of the URI's I need, but not these:

For Commercial: https://apps.powerapps.com/
For GCC: https://apps.gov.powerapps.us/
Not certain for GCC High, but I think its https://apps.high.gov.powerapps.us/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea524f2a-1e2a-6ade-8e2b-bc61173107c5
* Version Independent ID: 5990c060-8907-62b4-a8b3-f7ed8339a70e
* Content: [Microsoft Power Apps US Government - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government#feedback)
* Content Source: [power-platform/admin/powerapps-us-government.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-us-government.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Thanks for the feedback. We will be updating the document to reflect changes.
