### ISSUE TITLE
Convert from Developer to Sandbox 

### ISSUE THREAD

**Issue by leon1093** [MicrosoftDocs/power-platform#2130]
the article only describes converting from Sandbox to Production , but does not mention if we can or cannot convert from 
Developer to Sandbox , or Sandbox to Developer  possible ?

**Comment by JimDaly** [comment]
@leon1093 

Thanks for your feedback. The documentation feedback process works best when you create issues using the documentation feedback link at the bottom of the page. This links your feedback to a specific article, and we can assign the issue to the author.

Is your feedback about this article: [Change the environment type](https://learn.microsoft.com/en-us/power-platform/admin/switch-environment) ?

**Comment by sericks007** [comment]
Hi @leon1093 - Your question is in regard to the [Change the environment type](https://learn.microsoft.com/power-platform/admin/switch-environment) article, correct?

The article describes converting from sandbox to production, as well as converting from production to sandbox. Those are the types of conversions that are supported.
