### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by rappen** [MicrosoftDocs/power-platform#214]
The screenshot under [Get the Power Apps Build Tools](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools#get-the-power-apps-build-tools) is from way back in beta when the tools didn't even have an icon.
Time to replace it :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Power Apps build tools for Azure DevOps - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tools.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by Mattp123** [comment]
@rappen - Thank you for your feedback. The screenshot has been updated to reflect the current Azure Dev Ops pipeline experience.

Closing issue.
