### ISSUE TITLE
Flow quarantine statement correction

### ISSUE THREAD

**Issue by umeshbarapatre** [MicrosoftDocs/power-platform#2142]
![image](https://github.com/MicrosoftDocs/power-platform/assets/42261593/7760e042-9c0f-47ed-9383-6ecdaab1feb3)

The section mentions flow quarantine and i believe there is no quarantine of flows as yet. so may be changed to apps ? or just update not having quarantine feature for flow

**Comment by phecke** [comment]
@umeshbarapatre Please provide the URL of the article in question.

**Comment by umeshbarapatre** [comment]
https://learn.microsoft.com/en-us/power-platform/guidance/white-papers/migrating-from-default-environment

**Comment by JimDaly** [comment]
@Ravi-Chada 
Some feedback on your article.

@umeshbarapatre 
Feedback works best when you start with the **Feedback** link at the bottom of the article. This way it is automatically routed to the author.

**Comment by Ravi-Chada** [comment]
@rsantos00 - Can you please have a look at this?

**Comment by rsantos00** [comment]
Fixed, waiting to be merged
