### ISSUE TITLE
Running multiple Cloud Flows with RPA (unattended) with single Power Automate Process license

### ISSUE THREAD

**Issue by aagirre92** [MicrosoftDocs/power-platform#2157]
[Enter feedback here]

Could you add the following question, which is something pretty standard in RPA scenarios:

**Can I run multiple Cloud Flows, each of them invoking their own corresponding RPA flows in unattended mode with one Power Automate Process license?** I do not mean running all of them in parallel, but queueing them. For instance I have 4 different Cloud Flows, each of them invokes their own Power Automate Desktop flows and I want to run the first at 09:00, second at 11:00, and so on (in the same VM)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b98a3d2-eee9-5956-4e6f-65a0240db884
* Version Independent ID: 8b98a3d2-eee9-5956-4e6f-65a0240db884
* Content: [Frequently asked questions about Power Automate licensing - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/power-automate-licensing/faqs)
* Content Source: [power-platform/admin/power-automate-licensing/faqs.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/power-automate-licensing/faqs.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @PriyaKodukula
* Microsoft Alias: **prkoduku**

**Comment by v-aangie** [comment]
@aagirre92 - Thanks for your feedback. I'm working with one of our Principal Program Managers to resolve this and will get back to you soon.

**Comment by v-aangie** [comment]
@aagirre92 - Thanks for your feedback. We've updated the documentation with your question, provided the answer, and added a screenshot for clarity here: https://learn.microsoft.com/en-us/power-platform/admin/power-automate-licensing/faqs#how-many-process-licenses-do-i-need-if-i-have-multiple-cloud-flows-each-of-them-invoking-its-own-rpa-flows-in-unattended-mode-on-a-machine. Closing the issue.
