### ISSUE TITLE
Duplication of Example/For example text

### ISSUE THREAD

**Issue by mcclimont** [MicrosoftDocs/power-platform#218]
Link to section with duplicate text:

https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#what-is-the-minimum-number-of-logins-and-page-view-that-i-need-to-assign-to-a-specific-portal

Quote:
Example: If you have 3 portals and bought 4 login packs (400 logins). You can assign them in the following way:
For example, if you have 3 portals and bought 4 login packs (400 logins), you can assign them in the following ways:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#feedback)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@mcclimont 
Thanks for bringing this to our attention. Corrected.
