### ISSUE TITLE
transposed letters for ALM in pipelines

### ISSUE THREAD

**Issue by coloradojules** [MicrosoftDocs/power-platform#2194]
[In this bullet point "Pipelines in Power Platform bring application lifecycle management (AML) automation to streamline development processes with reduced effort." the letters for ALM are transposed as AML.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8951c0a-f807-3e8d-2fa2-abeb81042296
* Version Independent ID: e8951c0a-f807-3e8d-2fa2-abeb81042296
* Content: [Activating Managed Environments - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/white-papers/managed-environment-activation)
* Content Source: [power-platform/guidance/white-papers/managed-environment-activation.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/white-papers/managed-environment-activation.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @rsantos00
* Microsoft Alias: **rstand**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @coloradojules. This issue has been assigned to the doc author for review.

**Comment by rsantos00** [comment]
Fixed, waiting for merge
