### ISSUE TITLE
"Transfer to agent" replaced Escalate (preview version)

### ISSUE THREAD

**Issue by AndrewCussons** [MicrosoftDocs/power-platform#22]
When we removed "Escalate" in preview and now refer only to "Transfer to agent" we have lost significant usability for non developers. Non developers do not have an easy "End the conversation" option like before when we had Escalate. For non developers adding text and a link still gets the job done.

Design change:
For "End the Conversation " add an option for Escalate.
Why? then users have the choice of easy functionality that works without code and the richer "Transfer to agent"  functionality that requires code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3066493-cbbd-bcfa-df8f-594966ef2a38
* Version Independent ID: ef53a9ed-7794-4873-24c5-39cf03bff477
* Content: [Use hand-off to live agent - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-hand-off)
* Content Source: [power-virtual-agents/advanced-hand-off.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-hand-off.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Hi, you can still end the conversation with an 'escalation', when adding a node, select 'Go to another topic' and then 'Escalate'. I'll update the documentation here!
