### ISSUE TITLE
Power Automate Per Flow allocation per environment

### ISSUE THREAD

**Issue by lammy82** [MicrosoftDocs/power-platform#221]
My client has purchased some Power Automate "per-flow" licences but there doesn't seem to be a way to restrict these by number to a specific environment. This isn't about Business Process flows which are something else. If at least one Business Process flow capacity is assigned to an environment, users can create an unlimited number of regular scheduled/instant flows and assign them to the Per-Flow plan. Is there any way to specify how many per-flow licences are available per environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@lammy82 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Please reopen if this issue still exists.
