### ISSUE TITLE
AML should be replaced with ALM

### ISSUE THREAD

**Issue by rsk2013** [MicrosoftDocs/power-platform#2213]
Please check for the below sentence on top of the page:
"Pipelines in Power Platform bring application lifecycle management (AML) automation to streamline development processes with reduced effort."

In the above statement, "(AML)" should be replaced with "(ALM)". Looks like a typo error.

This may mislead new users.

Regards
Krishna Rachakonda
MVP

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8951c0a-f807-3e8d-2fa2-abeb81042296
* Version Independent ID: e8951c0a-f807-3e8d-2fa2-abeb81042296
* Content: [Activating Managed Environments - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/white-papers/managed-environment-activation)
* Content Source: [power-platform/guidance/white-papers/managed-environment-activation.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/white-papers/managed-environment-activation.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @rsantos00
* Microsoft Alias: **rstand**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rsk2013. This issue has been assigned to the doc author for review.

**Comment by rsantos00** [comment]
Fixed, waiting for merge
