### ISSUE TITLE
PDF Function not working in customized forms

### ISSUE THREAD

**Issue by PaWeg** [MicrosoftDocs/power-platform#2214]
I used this PDF function in a customized form, but it only takes the content visible on the screen.
I used this command: PDF(TestScreen,{Orientation:PaperOrientation.Portrait,Size:PaperSize.A4,ExpandContainers:true})
It works well in make.powerapps/play mode where all the content is added in the PDF, but after publishing and using it in the list I don't have all content in the PDF file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0699d67f-ae0a-7421-d0bc-ac8e61d88e6f
* Version Independent ID: 0699d67f-ae0a-7421-d0bc-ac8e61d88e6f
* Content: [PDF function in Power Apps (experimental) - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-pdf)
* Content Source: [power-platform/power-fx/reference/function-pdf.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-pdf.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @TashasEv
* Microsoft Alias: **tashas**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PaWeg. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Thanks for contacting us. Since this isn't  an issue with documentation please contact support for further help: https://docs.microsoft.com/dynamics365/get-started/support/ 

Closing this issue
