### ISSUE TITLE
Unable to open "DLP Editor" and "Set new App owner" canvas apps 

### ISSUE THREAD

**Issue by EditK** [MicrosoftDocs/power-platform#223]
CoE solutions have been currently installed, but we are unable to open the following Canvas Apps in Core Components: DLP Editor and Set new App owner. When clicking on any of them, we get redirected to the general Apps view in Power Apps.
Are we missing any configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#apps)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
This issue appears to be related to the CoE Starter Kit itself, and not the documentation. Could you please raise the issue via https://aka.ms/coe-starter-kit-issues instead.
