### ISSUE TITLE
unclear statement for region of processing data

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/power-platform#2238]
All data from the copilots and generative AI features in the Europe region (including France and Germany) are handled by the underlying infrastructure hosted in the **Sweden** region.

A bit below on this page it says the data are stored and processed in **Sweden or Switzerland**. So which statement is true

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f607742-cce6-5f36-a26f-d27e89f7b077
* Version Independent ID: 1f607742-cce6-5f36-a26f-d27e89f7b077
* Content: [Enable copilots and generative AI features outside United States - Power Platform](https://learn.microsoft.com/en-gb/power-platform/admin/geographical-availability-copilot?WT.mc_id=ppac_inproduct_settings)
* Content Source: [power-platform/admin/geographical-availability-copilot.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/geographical-availability-copilot.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sidhartg
* Microsoft Alias: **sidhartg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LennartaeHoefer. This issue has been assigned to the doc author for review.

**Comment by LennartaeHoefer** [comment]
[heart]         Lennart Hoefer reacted to your message:
________________________________

**Comment by sericks007** [comment]
@LennartaeHoefer, thanks for letting us know about this! **Sweden or Switzerland** is the correct answer. We're in the process of updating the content in this article, so hope of have this corrected soon!
