### ISSUE TITLE
Power Apps Connectors Report

### ISSUE THREAD

**Issue by Daleyon** [MicrosoftDocs/power-platform#224]
What prevents a Power Platform Admin Role from seeing all cross-tenant analytical data within Power Apps Connectors Report?
No issues with seeing my own data (my owned apps + flows and the ones shared with me) in Connectors Report.

I can get the above data using PP Admin connectors, PowerShell cmdlets, and CoE kit. 

Within Power Automate Connectors Report, no similar issues as described above. 

It is puzzling to me why I cannot view all cross-tenant analytical data within Power Apps Connectors Report.

**Comment by jimholtz** [comment]
@Daleyon 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.

**Comment by Daleyon** [comment]
@jimholtz you may have read my comment as an idea, but it is an actual issue. Please reopen.

**Comment by JimDaly** [comment]
This is the documentation feedback area. If you have issues with the documentation, they can be addressed here.

What you are describing is a product issue, or a feature request.
This is the place to provide feedback on the documentation. Documentation can't solve this problem, so it should be directed elsewhere. Make sense?

**Comment by Daleyon** [comment]
@JimDaly makes perfect sense theoretically. My issue proves the documentation does not cover the the scope when selecting "who can view these reports" from the PPAC:
https://docs.microsoft.com/en-us/power-platform/admin/analytics-powerapps#who-can-view-these-reports

![image](https://user-images.githubusercontent.com/17080282/82542160-82dc7980-9b1f-11ea-931b-b0c6e6a25c8c.png)

Maybe the issue is related to Data Center locations or GDPR policies. Just having the PPA role does not solve all. Maybe you add more detail to that documentation section.

Make sense?

**Comment by JimDaly** [comment]
@Daleyon 

Thanks for taking the time to submit feedback on the documentation. We do appreciate it. 

I would recommend you use the Doc feedback button at the bottom of the page for the [Admin Analytics for Power Apps](https://docs.microsoft.com/en-us/power-platform/admin/analytics-powerapps) topic.

This would establish a connection to a specific document and make it more actionable. You can also frame your feedback in reference to the documentation, i.e. 

> In this document I expect to find the answer to "X", but I can't find it here.

**Comment by Daleyon** [comment]
@JimDaly thank you for instruction. Will do!
