### ISSUE TITLE
PowerApps Admin Powershell Returns Incorrect Region Hint for usgovhigh

### ISSUE THREAD

**Issue by jordanabakerafs** [MicrosoftDocs/power-platform#2241]
This is less of a docs issue but more of a question.

Is there a Github Repo for the maintainers of the Microsoft.PowerApps.Administration.PowerShell (The Common Data Source Team) or a means to get in contact with them to submit an issue?  I was unable to find a repo or contact info.

We've encountered an issue with the response object for one of the cmdlets in this Module:

` Get-AdminPowerAppEnvironment ` returns a large amount of data.  The piece of data we are interested in specifically is ` $response.internal.properties.azureRegionHint ` which returns ` usgovtexas ` for every environment, which we have verified is incorrect.

Thanks for helping to get us in touch with the right folks?

**Comment by phecke** [comment]
@jordanabakerafs 

If you are referring to this module [Microsoft.PowerApps.Administration.PowerShell](https://www.powershellgallery.com/packages/Microsoft.PowerApps.Administration.PowerShell/), you would click the "Contact owners" link on that page.
