### ISSUE TITLE
SSO using this approach

### ISSUE THREAD

**Issue by robertwood62** [MicrosoftDocs/power-platform#226]
How would SSO work in this scenario.  If PVA wanted to authenticate the user, would the SSO context flow correctly from the end-user?  In the example above, the "user" is the bot calling PVA using direct-line.  Just not sure if SSO is supported correctly in the example above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a1322f-8123-d498-1a5c-431ad816c389
* Version Independent ID: a5f4b3d4-2a1a-edcc-c9fa-b3e2154e65ff
* Content: [Use a Microsoft Bot Framework bot with Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-use-dispatcher)
* Content Source: [power-virtual-agents/advanced-use-dispatcher.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-use-dispatcher.md)
* Service: **dynamics-365-ai**
* GitHub Login: @pawant-ms
* Microsoft Alias: **iawilt**

**Comment by pawant-ms** [comment]
// Adding @Bo Li<mailto:libo@microsoft.com>

Our implementation of SSO (releasing in a few weeks) will be supporting Skills as well. @Bo Li<mailto:libo@microsoft.com> can deep dive into it if you like.

Thank you,
Pawan

**Comment by iaanw** [comment]
Our SSO documentation is now live: https://docs.microsoft.com/en-us/power-virtual-agents/configure-sso
