### ISSUE TITLE
Need to update Storage reporting

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/power-platform#227]
Storage reporting is based on customer Paid/Purchased licenses and capacity add-ons. Trials do not count.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5297a60-9f8d-0a32-5d51-4adc5fbb7856
* Version Independent ID: 2a027441-3f4d-42a8-b6b3-c24b54947b09
* Content: [What's new for storage - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/whats-new-storage#feedback)
* Content Source: [power-platform/admin/whats-new-storage.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/whats-new-storage.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@DavidPaf 
Check out the note in this content: https://docs.microsoft.com/en-us/power-platform/admin/capacity-storage#storage-capacity-tab
