### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by Mhudson97** [MicrosoftDocs/power-platform#2270]
[[Enter feedback here]](https://github.com/microsoft/PowerVirtualAgentsSamples/tree/master/BotTestFramework)

this link doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: deb0e97d-631b-859c-1576-2e7a8609e5b6
* Version Independent ID: deb0e97d-631b-859c-1576-2e7a8609e5b6
* Content: [Unified authoring canvas migration guidance - Microsoft Copilot Studio](https://learn.microsoft.com/en-us/microsoft-copilot-studio/unified-authoring-conversion)
* Content Source: [power-virtual-agents/unified-authoring-conversion.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/unified-authoring-conversion.md)
* Service: **power-virtual-agents**
* GitHub Login: @sarahc916
* Microsoft Alias: **scritchley**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mhudson97. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mhudson97. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mhudson97. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mhudson97. This issue has been assigned to the doc author for review.

**Comment by iaanw** [comment]
Apologies for the delay, I've updated and this fix should go live soon. The correct URL is: [CopilotStudioSamples/tree/master/PVATestFramework](https://github.com/microsoft/CopilotStudioSamples/tree/master/PVATestFramework)
