### ISSUE TITLE
Contradictory 'Applies to'

### ISSUE THREAD

**Issue by danielatdigital** [MicrosoftDocs/power-platform#2272]
Why does this page have 'applies to' canvas apps as a context when the very next box says that it only applies to model-driven-apps?

Thanks for your attention, and the excellent documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 322b9dba-de52-6ef7-542f-a9f268fb906c
* Version Independent ID: 322b9dba-de52-6ef7-542f-a9f268fb906c
* Content: [Confirm function - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-confirm)
* Content Source: [power-platform/power-fx/reference/function-confirm.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-confirm.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @danielatdigital. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
These applies-to labels are a working in progress.
@tapanm-MSFT @gregli-msft are looking into these things afaik

**Comment by tapanm-MSFT** [comment]
@danielatdigital thank you for catching that, I've fixed the applies to. Changes will reflect soon on live topic.
