### ISSUE TITLE
Microsoft Power Platform requests allocations for Dynamics 365 Customer Engagement Plan

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/power-platform#228]
Hello team,

Kindly check and update the document for Microsoft Power Platform requests allocations for Dynamics 365 Customer Engagement Plan

Dynamics 365 Enterprise applications1	20,000
Dynamics 365 Professional 2	10,000

As I understand, Dynamics 365 Customer Engagement Plan includes both Professional and Enterprise applications, therefore, API limit/24 hours for this CE plan is 20,000. 

Can you confirm and update this information for old sku license?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#feedback)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@DavidPaf 
Content updated. Thanks for the feedback.
