### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by tstjohnsfg** [MicrosoftDocs/power-platform#229]
Neither CreateCoEArchivalDocLibraryinSP.zip or CreateCoETemplateLibaryDocLibraryinSP.zip would import to solutions. Both said that the solution files were invalid and I had to create libraries manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8fc749-2ecd-61d7-4146-16fe1a373848
* Version Independent ID: fcd148f1-795e-a99c-e2e9-da06e1129d3c
* Content: [Set up nurture components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components)
* Content Source: [power-platform/guidance/coe/setup-nurture-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-nurture-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
These are not solutions, but individual helper flows. Navigate to flow.microsoft.com > + Create > Import the zip file here, not under Solutions.

**Comment by tstjohnsfg** [comment]
Thank you, I went back and reread the documentation and it seems unclear where it should be imported. No mention of navigating to flow.

**Comment by manuelap-msft** [comment]
You're right, I have made a note to update this in our documentation!
