### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by garykywu** [MicrosoftDocs/power-platform#2292]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7606c4b-c8c1-d1f8-2839-9fb587e49f79
* Version Independent ID: e7606c4b-c8c1-d1f8-2839-9fb587e49f79
* Content: [AI-based chatbot authoring overview - Microsoft Copilot Studio](https://learn.microsoft.com/en-us/microsoft-copilot-studio/nlu-gpt-overview)
* Content Source: [power-virtual-agents/nlu-gpt-overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/nlu-gpt-overview.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
No details, closing issue.
