### ISSUE TITLE
Need valid skill manifest format example

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/power-platform#23]
This one https://microsoft.github.io/botframework-solutions/skills/handbook/manifest/ from bot framework does not work.
![image](https://user-images.githubusercontent.com/2876650/69712716-44e93480-113e-11ea-80c8-61d7fbb95af0.png)

Thanks~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3987009c-4054-5e8e-8fdc-2e1291ded8f6
* Version Independent ID: 43ab4768-00c0-6fca-4fde-951406022248
* Content: [Extend your bot using Bot Framework Skills - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-add-skills)
* Content Source: [power-virtual-agents/configuration-add-skills.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/configuration-add-skills.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by Subabrota** [comment]
I have tried to implement the Bot skill guided by document. However in Power Virtual Agent I have received the same errors. 
My manifest URL is - https://skillbot-etdg3gt.azurewebsites.net/api/skill/manifest

**Comment by dhinag** [comment]
For the first error, in your manifest.json file, change the "locale": "en-us" to "locale": "en".
I am not familiar with the second error as I don't see that on my end.

**Comment by xieofxie** [comment]
@dhinag, thanks~ The first problem is resolved.

But for the second one, it says "Contact your Skills developer". So what the developer should do? Since developer is myself.. The endpoint is https://someskill.azurewebsites.net/api/skill/messages while manifest url is https://someskill.azurewebsites.net/api/skill/manifest. It seems they match perfectly..

**Comment by dimasguillermo** [comment]
Receiving similar errors, "There's a mismatch in your skill endpoints.
Contact your skill developer. Learn more" and "Something went wrong while checking your skill.
Try again or contact your skill developer." My skill works fine in emulation and when using webchat.

**Comment by sbacha** [comment]
@dimasguillermo  to fix this issue please do the following:
Follow these steps [link](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps)

Make sure you are updating the app you used to deploy your skill bot.
We have this check to ensure users using PVA can only add skills deployed in there tenant.

Please try this and see if this works for you.

**Comment by xieofxie** [comment]
@sbacha Thanks!

**Comment by xieofxie** [comment]
@sbacha could you add the link under the error 'There's a mismatch in your Skill endpoints.'? Thanks
