### ISSUE TITLE
StageAndUpdate option is missing in docs

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/power-platform#2302]
According to release notes Stage and Upgrade is a new option available. But it is not mentioned in the docs (https://learn.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks#parameters-import)

![image](https://github.com/MicrosoftDocs/power-platform/assets/5035266/d098abaa-f504-4d62-b9c3-018d04edcd73)

**Comment by phecke** [comment]
@rajyraman Thanks for pointing this out. I have contacted the article owners.

**Comment by phecke** [comment]
@rajyraman Thanks for pointing this out. There is a new software update release for the build tools coming out soon. We will update the docs around when that ships.
