### ISSUE TITLE
Is this extension still in preview?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/power-platform#2304]
I've installed this extension yesterday and noticed today that the title in Visual Studio is _Power Platform Tools for VS 2022 [Preview]_ 

Calling `dotnet restore` removes important parts of the files `project.asset.json` and `.nuget.dgspec.json` which will result in an unbuildable project, until you clean the `obj` directory and restore the nuget packages again. This issue also makes me believe that the extension is still in preview.

If it is still in preview, I think that this should be mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9dcb052-17a9-544f-ced8-9aa64b8defed
* Version Independent ID: f9dcb052-17a9-544f-ced8-9aa64b8defed
* Content: [What is Power Platform Tools for Visual Studio - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/devtools-vs)
* Content Source: [power-platform/developer/devtools-vs.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/devtools-vs.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@darshSWL No, the extension is no longer in preview. You can ask a question on the download site: [Q & A](https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatformToolsVS2022&ssr=false#qna)

Also, I forwarded your issue to one of the extension developers.

**Comment by Pankaj-Thakur** [comment]
@darshSWL Could you share repro steps with powerplatformvs@microsoft.com. We plan to remove preview tag in coming months.
