### ISSUE TITLE
Select Settings > Behavior

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/power-platform#231]
This is not quite right, You need to Select Settings &gt; Product &gt; Behavior  to get to where you can turn Power Automate on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63017419-1a44-fb00-68c3-a1f09b624f7d
* Version Independent ID: 8df68bc2-e216-f967-8b95-e76173587799
* Content: [Enable Power Automate integration to automate processes - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/enable-embedded-flow-in-your-organization#feedback)
* Content Source: [power-platform/admin/enable-embedded-flow-in-your-organization.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/enable-embedded-flow-in-your-organization.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@JerryCRMI 
Thanks for bringing to our attention. Topic corrected.
