### ISSUE TITLE
Deployment setting file for package deployer

### ISSUE THREAD

**Issue by h-karthik12** [MicrosoftDocs/power-platform#2313]
Can we have deployment setting which we have in solution import for package deployer it will be helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78dd2e38-9d0c-3bbf-0db3-138416d4063b
* Version Independent ID: 51455bd4-3294-0ccd-2b1b-6d9857c0f50f
* Content: [Package Deployer tool - Power Platform](https://learn.microsoft.com/en-us/power-platform/alm/package-deployer-tool?tabs=cli)
* Content Source: [power-platform/alm/package-deployer-tool.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/package-deployer-tool.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by JimDaly** [comment]
Adding @marcelbf  to respond.

**Comment by phecke** [comment]
@h-karthik12 I have passed your request on to the product engineering team. Thanks for the feedback.
