### ISSUE TITLE
DateDiff Function Return Type Unclear

### ISSUE THREAD

**Issue by ransomnia** [MicrosoftDocs/power-platform#2314]
The page's description of the data type of DateDiff's result is ambigious. Please clarify the exact data type it is. 

Text in question: "The DateDiff function returns the difference between two date/time values. The result is a whole number of units." To me, "whole number" implies integer, but a pure datediff isn't working in a Condition Expression I'm using in a Power Automate flow as the thing being checked as to whether it's less than or equal to 31. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77554a1d-d853-8718-d703-b4f8ac76f1e9
* Version Independent ID: 77554a1d-d853-8718-d703-b4f8ac76f1e9
* Content: [DateAdd, DateDiff, and TimeZoneOffset functions - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-dateadd-datediff)
* Content Source: [power-platform/power-fx/reference/function-dateadd-datediff.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-dateadd-datediff.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jorisdg** [comment]
Power Fx does not differentiate between a whole or floating point number. There's one type: Number. We will be introducing a Decimal type to have an option to avoid floating point math (and all the pitfalls that brings along) when for example dealing with financial data.

You mention Power Automate though. Power Automate does not use Power Fx so the DateDiff function may not exist there at all (I checked this list: https://learn.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference )

**Comment by ransomnia** [comment]
Oh damn, I'm sorry for getting that confused! I apologize; I did get it
confused with the dateDifference function which is at the link you
provided. Sorry for that wild goose chase, thanks for sending me that link!

Bset,
Ransom Taylor
***@***.***
