### ISSUE TITLE
Default privacy and tou links from copilot studio 404

### ISSUE THREAD

**Issue by jwmiller5** [MicrosoftDocs/power-platform#2315]
The default links provided for copilots in copilot studio for privacy statement go.microsoft.com/fwlink/?linkid=2138950 and terms of use go.microsoft.com/fwlink/?linkid=2138865 both redirect to a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce60ea6f-d01c-9714-f3f7-db3a11806a34
* Version Independent ID: 435cfd9f-8b1d-d810-a58c-655ca6780286
* Content: [Add a chatbot to Microsoft Teams - Microsoft Copilot Studio](https://learn.microsoft.com/en-us/microsoft-copilot-studio/publication-add-bot-to-microsoft-teams)
* Content Source: [power-virtual-agents/publication-add-bot-to-microsoft-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/publication-add-bot-to-microsoft-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jwmiller5. This issue has been assigned to the doc author for review.

**Comment by iaanw** [comment]
Thanks for this info @jwmiller5, I've requested the update and the links should change, hopefully today. If they are still going to a 404 tomorrow, please don't hesitate to re-open this issue.
