### ISSUE TITLE
Administration mode change can only be done in sandbox, not clear in documentation

### ISSUE THREAD

**Issue by Pjetter** [MicrosoftDocs/power-platform#232]
After I restored a backup (the 1st time) I got a notification that it is in administration mode and you change it in settings. Alas there was no administration choice in settings.
This can only be done in sandbox mode.
This is not clear in the documentation.

Even that you have to change to sandbox mode in order to restore a backup, was not so clear in the documentation. It is in there, but it was not very clear.

For newbees restoring a backup is quite a challenge and the documentation might make this easier. 

Thanks

https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments

**Comment by jimholtz** [comment]
@Pjetter 
Thanks for the suggestion. Content updated.
