### ISSUE TITLE
Set function almost never works

### ISSUE THREAD

**Issue by victorsj1** [MicrosoftDocs/power-platform#2328]
[Enter feedback here]
When using the set function, set(varNum, 33) for example. the variable is almost always blank and rarely works. Useless function.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36cb2e4e-44ca-3d84-d872-9d1e55034a51
* Version Independent ID: 36cb2e4e-44ca-3d84-d872-9d1e55034a51
* Content: [Set function - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-set)
* Content Source: [power-platform/power-fx/reference/function-set.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-set.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @victorsj1. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
This is not a documentation issue.
The Set() function is a core function of the language. If you're not seeing the results as you expect, it's likely your formula is not being executed, or something else is overriding your variable somewhere else. If you have problems using it, you can file an issue with support or consider posting on https://powerusers.microsoft.com/ for help.
