### ISSUE TITLE
Security Group based restriction doesn't work

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/power-platform#233]
The configuration steps made on a trial environment with CDS database inside don't have effect: No of existing users got disabled. No difference in access to the environment for the non-admin users before and after association. Tested with an empty Power App, that was shared to a single user. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/control-user-access#feedback)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@soutchilin 
Sorry for the very delayed response. If this is still an issue, please contact Support: https://powerapps.microsoft.com/support/
