### ISSUE TITLE
pac org fetch --xmlFile seems to ignore order attribute

### ISSUE THREAD

**Issue by alx-kpk** [MicrosoftDocs/power-platform#2336]
When executing `pac org fetch --xmlFile "MyFilter.xml"` the order attribute `<order attribute="modifiedon" descending="true" />` seems to be ignored.

Here is the entire FetchXML

`<fetch>
  <entity name="contact">
    <attribute name="fullname" />
    <attribute name="modifiedon" />
    <order attribute="modifiedon" descending="true" />
  </entity>
</fetch>`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10bda820-3ad2-29d7-9cb2-bc87afbd1f7b
* Version Independent ID: 10bda820-3ad2-29d7-9cb2-bc87afbd1f7b
* Content: [Microsoft Power Platform CLI org command group - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/org#pac-org-fetch)
* Content Source: [power-platform/developer/cli/reference/org.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/reference/org.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @snizar007
* Microsoft Alias: **snizar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @alx-kpk. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@alx-kpk 
Sorry for the delay in responding. 
Issues in this repo are for the documentation.  Nothing actionable to document here.
Use [github.com/microsoft/powerplatform-build-tools/discussions](https://github.com/microsoft/powerplatform-build-tools/discussions) to view and submit feedback for PAC CLI.
