### ISSUE TITLE
Works with SQL Managed Instance?

### ISSUE THREAD

**Issue by dhinag** [MicrosoftDocs/power-platform#234]
Just curious as there is no indication of the SQL Managed Instance. Would Data Export Service work with the SQL Managed Instance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by sabinn-msft** [comment]
No. DES does not support SQL managed instance

**Comment by sdarana** [comment]
Sabinn - Is there any alternative way we can connect to Azure Managed Instances. We have all DBs configured in managed instances. We really wanted to replicate to MI .Your reply will be really appreciated.

**Comment by sabinn-msft** [comment]
No. We unfortunately do not support it. Moreover, we are encouraging everyone to move to Synapse Link for Dataverse which would let you connect to a myriad of sources and destinations. Our sincere request is for you to evaluate and start moving to Synapse Link.
