### ISSUE TITLE
Missleading code examples

### ISSUE THREAD

**Issue by patrykr2001** [MicrosoftDocs/power-platform#2344]
[Enter feedback here]
Hi,
please change in your article commas to semicolons in functions examples.
Commas doesn't work in current version of Power Apps.
Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 272cabaf-bc47-a119-d964-ee1bc9ca17b7
* Version Independent ID: 272cabaf-bc47-a119-d964-ee1bc9ca17b7
* Content: [Relate and Unrelate functions - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-relate-unrelate)
* Content Source: [power-platform/power-fx/reference/function-relate-unrelate.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-relate-unrelate.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @patrykr2001. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
The use of commas or semi-colons depends on your localization settings. Unfortunately the documentation site does not support switching code examples automatically based on your language, so the examples are all in the default localization of en-us using commas.
