### ISSUE TITLE
Incorrect Nomenclature

### ISSUE THREAD

**Issue by diyd365** [MicrosoftDocs/power-platform#235]
Power App Site/Admin site/instance/makers experience is referred to as Power Apps Portals which is a completely different thing. Also the left navigation pane is referred to as 'Side navigation'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fded0a67-519d-8aca-c6d0-c44038c14b22
* Version Independent ID: b9c0832f-3cdb-8029-7171-66df4bb8f517
* Content: [Download Power Virtual Agents bot sessions - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/analytics-sessions#feedback)
* Content Source: [power-virtual-agents/analytics-sessions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/analytics-sessions.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for your comments, I've made updates to make it clearer when referencing between the Power Apps admin center and the Power Apps Studio. "Side navigation pane" is an appropriate term to distinguish it from the other menus etc (we shouldn't refer to is 'left' or 'right' as positioning can change based on customer location).

**Comment by diyd365** [comment]
Thanks Iaan, but I don't see any change in the document.
