### ISSUE TITLE
PAC CLI Unpack and Pack managed solution organization setting missing

### ISSUE THREAD

**Issue by h-karthik12** [MicrosoftDocs/power-platform#2357]
I am trying to pack the managed solution using PAC CLI for our automated pipeline. I am seeing some peculiar behavior

when we use unpack command it unpacks all the components

```pac solution unpack -z solution.zip -f CustomCode  -p managed -loc -lcid```

This is the folder after extract
![image](https://i.stack.imgur.com/jxCnW.png)

but when we pack the same soultion again the organization setting folder will be removed

```pac solution pack -z solution.zip -f CustomCode  -p managed -loc -lcid``` 

![image](https://i.stack.imgur.com/in8YC.png)
Not sure why this behaviour in the pac cli
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Version Independent ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Content: [Microsoft Power Platform CLI - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction)
* Content Source: [power-platform/developer/cli/introduction.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/introduction.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @snizar007
* Microsoft Alias: **snizar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @h-karthik12. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@h-karthik12 
Sorry for the delay in responding.
Issues in this repository are for the documentation. I don't see any actionable items to change for this in the docs.

Use [github.com/microsoft/powerplatform-build-tools/discussions](https://github.com/microsoft/powerplatform-build-tools/discussions) to view and submit feedback for PAC CLI.
