### ISSUE TITLE
Environment-level view of apps upgrades

### ISSUE THREAD

**Issue by hbazerbashi** [MicrosoftDocs/power-platform#236]
The legacy view of Environment-level apps shows if an upgrade is available, but the new view doesn't. Is that something that will be added later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7afcf1bf-4570-e586-a016-3273589910cf
* Version Independent ID: 47488450-bc47-aead-2c22-7c0989de4cbb
* Content: [Manage Dynamics 365 apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-apps#feedback)
* Content Source: [power-platform/admin/manage-apps.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-apps.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@hbazerbashi 
Thanks for your feedback. We are working to add this in to the Power Platform admin center.

**Comment by pieterh** [comment]
Any new information on this?
