### ISSUE TITLE
Admin Analytics for Power Apps: 'Who can view these reports'

### ISSUE THREAD

**Issue by Daleyon** [MicrosoftDocs/power-platform#237]
In section [https://docs.microsoft.com/en-us/power-platform/admin/analytics-powerapps#who-can-view-these-reports](url), the documentation makes it seem simplistic in viewing analytical data as long as the user has one of the defined roles. 
However, the documentation should include information related to why the defined roles may not render all data. 
Related information like Data Center locations or GDPR policies. 

Just speaking from current experience. Having the Power Platform Admin role as a region America employee, emphasis on the location, renders a limited amount of data.

**Comment by pnghub** [comment]
HII! Daleyon, Are you seeing this issue with the Connector report only?

**Comment by Daleyon** [comment]
Hi!
Yes, the Power Apps connector report.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jimholtz** [comment]
@Daleyon 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Please reopen if this issue still exists.
