### ISSUE TITLE
This page doesn't mention preview's major downside

### ISSUE THREAD

**Issue by TubanMicrosoft** [MicrosoftDocs/power-platform#238]
Apps you make in preview environments generally cannot be opened in production environments. That should be mentioned here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da4e83ac-52bb-6aff-0796-c19341377412
* Version Independent ID: e122c886-ca3c-afba-2870-809849903700
* Content: [Preview environments - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/preview-environments#feedback)
* Content Source: [power-platform/admin/preview-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/preview-environments.md)
* Service: **power-platform**
* GitHub Login: @manasmams
* Microsoft Alias: **manasma**

**Comment by jimholtz** [comment]
@TubanMicrosoft 
Have you tried exporting/importing the app as directed here:
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-solutions

**Comment by TubanMicrosoft** [comment]
@jimholtz 
That handles a lot of issues you run into when moving apps between environments, but it's not relevant to what I'm talking about. I am on the PowerApps Canvas team and I have been dealing with this issue with multiple customers as DRI so I have a good amount of background on this problem. The core issue is that apps from newer versions of PowerApps cannot be opened in older versions of PowerApps, regardless of how you export them. Preview is always using a newer version of PowerApps then Production, so we need to warn the user about that.

The closest thing we have to a consistent way to move apps from preview to production is to roll back to a version from a week ago and hope that version has made it to production in your region. That solution has enough potential problems that I wouldn't be comfortable recommending it to customers. That's why I suggest we note that moving apps from Preview to Production is not supported, even if it is technically doable. Customers using Preview environments should know what they're getting into.

**Comment by jimholtz** [comment]
Taking this to internal for resolution.
