### ISSUE TITLE
This page doesn't mention versioning issues

### ISSUE THREAD

**Issue by TubanMicrosoft** [MicrosoftDocs/power-platform#239]
There are issues moving apps between environment's with different versions. At time of speaking if you switch an environment to Moderate you won't be able to open any of your apps because they're from a later (frequent) version of PowerApps. Something about that should be mentioned

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-environment#feedback)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@TubanMicrosoft 
Thanks for the feedback. We're aware of the issue and are working on a fix.
