### ISSUE TITLE
PAC Command Description not correct

### ISSUE THREAD

**Issue by allandecastro** [MicrosoftDocs/power-platform#2392]
Hello,

Description for the pac command "pac admin set-backup-retention-period" is set with "Takes a manual backup of your environment" which is not correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 488078c6-838d-1722-114e-4eb64d94aa0d
* Version Independent ID: 488078c6-838d-1722-114e-4eb64d94aa0d
* Content: [Microsoft Power Platform CLI admin command group - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/admin)
* Content Source: [power-platform/developer/cli/reference/admin.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/reference/admin.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @snizar007
* Microsoft Alias: **snizar**[pac admin set-backup-retention-period](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/admin#pac-admin-set-backup-retention-period)	Takes a manual backup of your environment.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @allandecastro. This issue has been assigned to the doc author for review.

**Comment by snizar007** [comment]
Ack. We are looking into this. Thank you.

**Comment by JimDaly** [comment]
@allandecastro 

Thanks for your feedback. This part of the reference documentation comes from the pac cli code. This is the description when you use the help command:

```
PS C:\Users\you> pac admin set-backup-retention-period help
Microsoft PowerPlatform CLI
Version: 1.29.11+g9e2b163
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Help:
Takes a manual backup of your environment.

Commands:
Usage: pac admin set-backup-retention-period [--environment] --backup-retention-period [--async] [--max-async-wait-time]

  --environment               Environment URL or ID of the Environment that requires backup. (alias: -env)
  --backup-retention-period   Sets the backup retention period in days as provided. Valid values are: 7, 14, 21, 28. (alias: -br)
  --async                     Optional boolean argument to run pac verbs asynchronously, defaults to false. (alias: -a)
  --max-async-wait-time       Max asynchronous wait time in minutes. The default value is 60 minutes. (alias: -wt)
```

Since this documentation is generated using the product help as the data source, this description will be updated when the product help description is updated.

I just checked for v1.30, and the description is still "Takes a manual backup of your environment.".

@allandecastro What do you think the description should be?

@petrochuk & @snizar007 I've assigned this to you.

**Comment by snizar007** [comment]
We can fix it in the next version.
