### ISSUE TITLE
Export model drive app is not available

### ISSUE THREAD

**Issue by tyrfing666** [MicrosoftDocs/power-platform#24]
I'm not sure where the screen shots are coming from - the "export model-driven (preview)" link is not visible, probably because web.powerapps.com bounces over to make.powerapps.com. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f7d9def-ccc0-6bf9-d9b4-945f4ccfd19b
* Version Independent ID: cd12491c-b19e-d626-a9e1-e8fc57ccd242
* Content: [Migrate apps between environments and tenants - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/environment-and-tenant-migration#feedback)
* Content Source: [power-platform/admin/environment-and-tenant-migration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/environment-and-tenant-migration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@tyrfing666 
You can export and import canvas apps. Model-driven apps are done via adding to a solution and exporting the solution. I have updated the topic to reflect canvas app info.

**Comment by CraigJahnke** [comment]
I don't see a Choose design mode or and an Advanced tab in my tenant.  Is that something still being rolled out?
