### ISSUE TITLE
is no longer needed to convert an instance to sanbox to delete a production instance, can you pls update the article? thank you 

### ISSUE THREAD

**Issue by anapereiCRMSE** [MicrosoftDocs/power-platform#241]
is no longer needed to convert an instance to sanbox to delete a production instance, can you pls update the article? thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb92ca9-41dc-d1d0-90df-09e7159e47d7
* Version Independent ID: 6c2a02de-a8db-cafa-6d81-861a027c07f2
* Content: [Delete environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/delete-environment)
* Content Source: [power-platform/admin/delete-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/delete-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@anapereiCRMSE 
Thanks for the feedback. The topic has been updated.
