### ISSUE TITLE
Need update on products

### ISSUE THREAD

**Issue by tombyang** [MicrosoftDocs/power-platform#242]
[Enter feedback here]
Hi folks, need an update on the products listed here, for example Power Virtual Agents, Omnichannel for Customer Service, etc are not available in China, but are not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a599dbd-52ca-de58-f785-eb15b8ff088f
* Version Independent ID: e33ca597-5871-344b-a813-7911d2f48519
* Content: [Model-driven apps in Dynamics 365 - operated by 21Vianet in China - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-microsoft-cloud-china)
* Content Source: [power-platform/admin/about-microsoft-cloud-china.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/about-microsoft-cloud-china.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@tombyang 
Sorry for the delayed response. Plans are underway for additional supported apps. Can't provide an ETA yet.
