### ISSUE TITLE
Comments on the Note regarding updates sync flows after new import

### ISSUE THREAD

**Issue by RebekkaAalbers** [MicrosoftDocs/power-platform#243]
A Note on the page states the following:

> Due to a current product limitation in this methodology, you won't get updates for these flows as new versions of the CoE are released. You'll have to import the new solution and copy the flows again to upgrade them to the latest version. This experience will improve when the modern solution import experience (Power Apps 2020 release wave 1) is available.

But there actually is a setting when you import the solution to overwrite the flows with the newer version by choosing the option **Overwrite Customizations (not recommended)** in the customization options section. 
When you choose this option the flows will be replaced by the newer version while preserving the run history of the flow.
The title of the section states this is not recommended, but I actually prefer this option regarding Canvas Apps and Flows. A lot of other customizations like adding fields to entities and such will be 
preserved. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
This has been solved, as modern solution import experience is now available and connection references are used across all flows in the CoE Starter Kit.
