### ISSUE TITLE
Assignment expiry timeframe

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/power-platform#2430]
The doc says "_after the assignment expires in PIM._", but does not define what the actual valid timeframe for the assignment is. Is the sysadmin role assignment setup for 1 day when you call the applyAdminRole API?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 677e918d-e3bd-4f2e-708a-c06a77ed6826
* Version Independent ID: 677e918d-e3bd-4f2e-708a-c06a77ed6826
* Content: [Use Entra Privileged Identity Management in Power Platform admin center to manage high-privileged admin roles - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/manage-high-privileged-admin-roles)
* Content Source: [power-platform/admin/manage-high-privileged-admin-roles.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/manage-high-privileged-admin-roles.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @srpoduri
* Microsoft Alias: **sripod**

**Comment by srpoduri** [comment]
The assignment in Dataverse is permanent since we do not know how long the assignment in PIM is. Remove the sysadmin role assignment using the Powershell script provided depending on how your IT policies are structured around PIM defaults.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rajyraman. This issue has been assigned to the doc author for review.

**Comment by rajyraman** [comment]
Thank you for the clarification @srpoduri
