### ISSUE TITLE
Missing action information

### ISSUE THREAD

**Issue by DennisGaida** [MicrosoftDocs/power-platform#244]
The visualizations on this page are very nice, however the concrete action on how to do cross-tenant  restrictions is missing.

I can only assume that this documentation is supposed to be implemented by leveraging Azure AD tenant restrictions: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/tenant-restrictions, but I am unsure on how one would implement outbound tenant restrictions that "only target canvas apps and flows" as stated on this page.

Please add more information on how to do cross-tenant restrictions with a concrete action or example of e.g. restricting all flows to the current tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daeff591-4edf-8cc0-614a-47e59bec3825
* Version Independent ID: bad9dc45-d9f9-62c6-a7fd-7aa97fd8e3fd
* Content: [Restrict cross-tenant access - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/cross-tenant-restrictions)
* Content Source: [power-platform/admin/cross-tenant-restrictions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/cross-tenant-restrictions.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@DennisGaida 
Sorry for the late response. You're right about the content lacking actionable information. We'll work on getting this updated.
