### ISSUE TITLE
Error in https://learn.microsoft.com/en-us/power-platform/power-fx/variables#power-fx

### ISSUE THREAD

**Issue by jhstevens001** [MicrosoftDocs/power-platform#2448]
This section states: "If you then set the Text property of Label1 to TextInput1 + TextInput2, it will always show the sum of whatever numbers are in TextInput1 and TextInput2 automatically."

This doesn't work for me - I needed to set the Text property of Label1 to TextInput1.Text + TextInput2.Text to prevent it from showing an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb684a50-ef20-b9c9-2b24-415b07db190a
* Version Independent ID: 3ec54769-5275-be1b-cf4b-ccbe366266f0
* Content: [Understand variables in Microsoft Power Fx - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/variables)
* Content Source: [power-platform/power-fx/variables.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/variables.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jorisdg** [comment]
Thank you for reporting this. Previously, some controls would have what's called a "default property" so one could refer to a textinput and it would imply you want the text property. This was not consistent across the feature set and had other limitations in the language. So this was changed and default properties are no longer there.

I've sent changes to this doc to our editing team.

**Comment by jhstevens001** [comment]
Correction has not been completed - the animated png below the text still shows the wrong version
