### ISSUE TITLE
Is this page connected to the TOC?

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/power-platform#245]
Somehow it appears, but doesn't seem connected to the TOC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51751e6d-1972-f37e-9232-43dbb33b9209
* Version Independent ID: 2172da05-5bd8-9722-2f72-d421458e6b30
* Content: [Management and monitoring - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/wp-management-monitoring)
* Content Source: [power-platform/admin/wp-management-monitoring.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/wp-management-monitoring.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@JimDaly 
Thanks for bringing this to my attention. Topic now restored to TOC.
