### ISSUE TITLE
Audit Logs guidance on Power Platform

### ISSUE THREAD

**Issue by breakpoint7** [MicrosoftDocs/power-platform#246]
It's not clear from this documentation where to find this configuration (e.g.- what is the landing page to get to these settings).  With the multiple admin portals integrated for Power Platform alongside dynamics, some of this is buried in Dynamics while some if exposed through Power Platform admin center.  I can't see how to get to this configuration based on a simple Power Platforms configurations with CDS.  There needs to be better guidance on which UI you need to go through to get to these settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f28a46-531e-d373-40ad-f9e81b55fdf3
* Version Independent ID: a47230d1-92c1-28a3-2f2c-ada21450b1f2
* Content: [Enable and use Activity Logging - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/enable-use-comprehensive-auditing)
* Content Source: [power-platform/admin/enable-use-comprehensive-auditing.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/enable-use-comprehensive-auditing.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@breakpoint7 
Thanks for the feedback. We are working to consolidate the various admin centers and settings locations. Can't provide an ETA but work is progressing.
