### ISSUE TITLE
How to set value of Power Virtual Agent Bot variable when using custom canvas

### ISSUE THREAD

**Issue by andrewevers** [MicrosoftDocs/power-platform#247]
[Enter feedback here]
This page indicates that it is possible to pass variables to a PVA bot via query string parameters when embedding the bot (which works), and also when using a custom canvas.

When using a custom canvas, the obvious approaches of 1) using the embedding page's query string, or 2) adding to https://powerva.microsoft.com/api/botmanagement/v1/directline/directlinetoken?botId=" + BOT_ID + "&var=value"; 
don't work.

An example on this page or the embedding page would be very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55fe673f-f192-7048-930a-5feb6c145e13
* Version Independent ID: a8c05263-0297-db71-c210-4d923a878282
* Content: [Use bot variables to carry content across topics - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/authoring-variables-bot)
* Content Source: [power-virtual-agents/authoring-variables-bot.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/authoring-variables-bot.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
I'm just updating this now with some clearer examples of how to pass variables when using a custom canvas. It should be live within a few hours.
