### ISSUE TITLE
Improve the instructions for specifying the environment type, when trialing Power Virtual Agents

### ISSUE THREAD

**Issue by Robert-Tortorelli** [MicrosoftDocs/power-platform#248]
In the first occurrence of the instructions for creating an environment for a virtual agent, include the fact that when you are performing a free trial of Power Virtual Agents, you must specify the environment type as 'Trial', and note Trial environments only last 30 days.
This will be helpful, as specifying any other environment type results in the cryptic message, "Creating an environment requires at least 1 GB of database capacity".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91193d3-c726-bf8c-311e-f9c733136b57
* Version Independent ID: bbfb1d2f-6f4f-6d0a-b38b-879054d32bba
* Content: [Create and use Power Apps environments in Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/environments-first-run-experience)
* Content Source: [power-virtual-agents/environments-first-run-experience.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/environments-first-run-experience.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for the feedback, I've made this update and it should be live within the next few hours.
