### ISSUE TITLE
missing --max-async-wait-time in pac application install

### ISSUE THREAD

**Issue by jfurtz** [MicrosoftDocs/power-platform#2487]
When installing D365 Intelligent Order Management, it times out because it ran for more than 60 min.

So it would be nice with the same feature as on -import solution with --max-async-wait-time

`Error: Failed to install application within maximum timeout of 60 minutes`

**Comment by JimDaly** [comment]
Issues reported against the documentation must include some specific feedback to be actionable, preferably relating to a specific topic.

Use [github.com/microsoft/powerplatform-build-tools/discussions](https://github.com/microsoft/powerplatform-build-tools/discussions) to view and submit feedback for PAC CLI.
