### ISSUE TITLE
Host.OSType for Mac

### ISSUE THREAD

**Issue by rehkech** [MicrosoftDocs/power-platform#2488]
The Microsoft documentation is incorrect for the terminology on the OSType property when a Mac is being used. It is noted as returning 'macOS'. My testing confirms it is actually returned as '**Mac OS**'.

It is noted as returning 'macOS'. My testing confirms it is actually returned as 'Mac OS'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d166c439-3e39-d35b-f534-a733b28c89d5
* Version Independent ID: d166c439-3e39-d35b-f534-a733b28c89d5
* Content: [Host object in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/object-host)
* Content Source: [power-platform/power-fx/reference/object-host.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/object-host.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rehkech. This issue has been assigned to the doc author for review.

**Comment by rehkech** [comment]
Hello,

Since that comment (which I appreciate was only very recent!), further discussion on the related thread on the Community reveals there may be cases where it is output as ‘Mac OS’ OR ‘macOS’.

This is the relevant thread: Solved: Re: Determine Current Connection Method - Canvas A... - Power Platform Community (microsoft.com)<https://powerusers.microsoft.com/t5/Building-Power-Apps/Determine-Current-Connection-Method-Canvas-App/m-p/2609016/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExTT1NUVTdERzFGTVU1fDI2MDkwMTZ8U1VCU0NSSVBUSU9OU3xoSw#M644682>

Happy to elaborate further if needed.

Best Wishes,
Edd

**Comment by mduelae** [comment]
Thank you for sending us the feedback. I updated the topic the topic with the correct value for Mac OS.

Thanks,
Mints
