### ISSUE TITLE
Page needs to be updated

### ISSUE THREAD

**Issue by ahueyz** [MicrosoftDocs/power-platform#2494]
The page does not give accurate steps as the Settings options have changed. There is no visible option to modify the settings mentioned in the page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 173c05a8-b0af-5139-80c1-ec153a88c922
* Version Independent ID: 7427a8f1-b48f-0180-f1c7-940700192eb6
* Content: [Control environment creation and management - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/control-environment-creation)
* Content Source: [power-platform/admin/control-environment-creation.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/control-environment-creation.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ahueyz. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@ahueyz - Thank you for your feedback. The article has been updated to reflect the current UI and will be published today.
