### ISSUE TITLE
Licensing complexity seems an obvious barrier to uptake

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/power-platform#25]
The length and complexity of this incomplete FAQ highlights that the complexity of the licensing is a barrier to the uptake of these otherwise useful products. Your audience who will drive the success or failure of these products are busy knowledge workers who just want to get on with producing results - they dont have time for this complexity.  Its frustrating because it is holding back otherwise useful products from broader adoption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#power-automate)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by Cloudmaister** [comment]
Please specify whether any of the power platform services are included in an E3 or E5 MICROSOFT 365 license

**Comment by Pierrers** [comment]
> Please specify whether any of the power platform services are included in an E3 or E5 MICROSOFT 365 license
As I understood from the licencing guide, any F1-E1-E3 user may have up to 2000 of daily executions, but only standard connectors. Bye-bye nice time when for 5$ per month we could convert word to pdf or other premium stuff... The other way is to user Logic apps.

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback, visit <https://ideas.powerapps.com>.  

Closing this issue.
