### ISSUE TITLE
Restoring from the default environment

### ISSUE THREAD

**Issue by agbeaton** [MicrosoftDocs/power-platform#2524]
Does the default environment have limitations when it comes to data recovery/rollback that aren't present with sandbox/production environments?  I'm trying to understand why some recommend having customized SharePoint form stored in a production environment, rather than in the default environment, - and whether there still good reasons for recommending that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c36038a8-28f7-cb20-dc2c-caa3186b9aba
* Version Independent ID: c36038a8-28f7-cb20-dc2c-caa3186b9aba
* Content: [Manage the default environment - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/adoption/manage-default-environment)
* Content Source: [power-platform/guidance/adoption/manage-default-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/adoption/manage-default-environment.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @rranjit83
* Microsoft Alias: **rranjit**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @agbeaton. This issue has been assigned to the doc author for review.

**Comment by iscohen-microsoft** [comment]
Added Imad Yanni to help

**Comment by ImadYanni** [comment]
Although all environments including Default have system backups, the standard retention period is 7 days; Production environment retention period is longer and can be up to 28 days. In addition, admins can create labeled backups for Production environments and are able to perform self-self restore from system or manual backups, this is not possible for Default.  recommend the user read environment strategy guidance here https://learn.microsoft.com/en-us/power-platform/guidance/adoption/environment-strategy
