### ISSUE TITLE
Title broken in German version

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/power-platform#253]
Hello,

the title of the article is broken in German version. Please fix it and check article for other issues.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1b845f2-dab8-a8c5-52ce-88f78e2e1885
* Version Independent ID: a599ae52-a9c3-815c-87b7-59d2711a8f36
* Content: [Responding to Data Subject Rights (DSR) requests for Power Apps customer data - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-gdpr-dsr-guide)
* Content Source: [power-platform/admin/powerapps-gdpr-dsr-guide.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-gdpr-dsr-guide.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@GiantCrocodile 
Thanks for the notice. We'll fix the title.
