### ISSUE TITLE
The text says App Owner role i guess it should be App Opener Role

### ISSUE THREAD

**Issue by hanslinder** [MicrosoftDocs/power-platform#2531]
The document says 
To allow users to open a model-driven app or any Dynamics 365 customer engagement app, assign the App Owner role.

I think it should be To allow users to open a model-driven app or any Dynamics 365 customer engagement app, assign the App Opener role.

Kind Regars,
Hans Linder

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c40f87c-1a3a-399d-d25f-ae348dc5e248
* Version Independent ID: 4784510f-a482-f73a-85e2-f2e6d74168c3
* Content: [Create or edit a security role to manage access - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/create-edit-security-role)
* Content Source: [power-platform/admin/create-edit-security-role.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-edit-security-role.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hanslinder. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@hanslinder - Thank you for your feedback. You're correct that the App Opener should be the security role mentioned in the article. I've made the change and it will be published soon.

Closing issue.
