### ISSUE TITLE
Page out dated content

### ISSUE THREAD

**Issue by jamilhaddadin** [MicrosoftDocs/power-platform#254]
This content is out dated
On the left navigation pane, select Billing -> Subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eebb06d-174a-4f38-6e9e-c6176e97b3ba
* Version Independent ID: b3feb7ce-6756-29af-f18b-2b9fd4e29f3e
* Content: [Purchase Power Apps for your organization - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/signup-for-powerapps-admin#power-apps-per-app-plan)
* Content Source: [power-platform/admin/signup-for-powerapps-admin.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/signup-for-powerapps-admin.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jamilhaddadin 
Thanks for bringing this to our attention. Content has been updated.
