### ISSUE TITLE
This guidance is not up-to-date

### ISSUE THREAD

**Issue by bdelvauxevscom** [MicrosoftDocs/power-platform#255]
You don't switch the instance type as described here.
Instead you have to use the Convert function.

![image](https://user-images.githubusercontent.com/53932927/83619798-a9bd9580-a58c-11ea-8111-73ff1db312ce.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35d3f3b-0007-bbb7-fe0b-000e76932281
* Version Independent ID: d937d8d8-232d-ce0e-ae88-38d95e501793
* Content: [Change environment type - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/switch-environment)
* Content Source: [power-platform/admin/switch-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/switch-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@bdelvauxevscom 
Thanks for bringing this to our attention. We've updated the topic.
