### ISSUE TITLE
Can’t find this setting

### ISSUE THREAD

**Issue by mbrg** [MicrosoftDocs/power-platform#2561]
I can’t find this setting in the environment page. Is this page up to date?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f607742-cce6-5f36-a26f-d27e89f7b077
* Version Independent ID: 1f607742-cce6-5f36-a26f-d27e89f7b077
* Content: [Enable copilots and generative AI features - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/geographical-availability-copilot)
* Content Source: [power-platform/admin/geographical-availability-copilot.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/geographical-availability-copilot.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @caitlinshaw1
* Microsoft Alias: **caitlinshaw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mbrg. This issue has been assigned to the doc author for review.

**Comment by caitlinshaw1** [comment]
@mbrg @bishalgoswami in the case where data doesn't move across boundaries (environment is hosted in the US, India, UK, or Australia) there is no setting because there is no action required from admins.
