### ISSUE TITLE
Capitalization error - 'environment to environment migration' sentence needs to start with capital E

### ISSUE THREAD

**Issue by krouskop** [MicrosoftDocs/power-platform#2564]
Within:

> Important
> 
> Document template downloaded from one environment can only be used within that environment. **e**nvironment to environment migration for Word or Excel templates isn't currently supported.
> 
> During the creation of an Excel template, a maximum of 50 records are exported in the template file.

Capitalize the E.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08b06ee8-f9a7-2b0c-80d6-4297aa4f27ab
* Version Independent ID: 553a86b0-0e79-3ed1-0d4f-3db1fd91c5ed
* Content: [Create and share data analysis Excel templates - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/analyze-your-data-with-excel-templates)
* Content Source: [power-platform/admin/analyze-your-data-with-excel-templates.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/analyze-your-data-with-excel-templates.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@krouskop, thanks for letting us know about this!  Just fixed the capitalization!  The update will be published later today.
