### ISSUE TITLE
typo in your copy

### ISSUE THREAD

**Issue by Lydja** [MicrosoftDocs/power-platform#2566]
"Production" is spelled wrong in the third paragraph. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9c58fb1-e6a2-5210-3774-4ea4bbff4572
* Version Independent ID: 57c1780c-b097-af8c-82fa-47e38a63995c
* Content: [Back up and restore environments - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/backup-restore-environments)
* Content Source: [power-platform/admin/backup-restore-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/backup-restore-environments.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @matapg007
* Microsoft Alias: **matgupta**

**Comment by sericks007** [comment]
Fixed! Will be published later today. Thanks!
