### ISSUE TITLE
"Incorrect description" for Create CoE Archival Doc Lib in SP

### ISSUE THREAD

**Issue by sundium** [MicrosoftDocs/power-platform#257]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/11729099/83811118-4dce4a80-a70d-11ea-86ae-0e56b165d65e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14181d4-574f-95e3-c2c9-545116549c9b
* Version Independent ID: bf449b92-6756-e08a-a58c-d561e36947cb
* Content: [Set up governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components)
* Content Source: [power-platform/guidance/coe/setup-governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-governance-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
This has been fixed with the latest release.
