### ISSUE TITLE
Support for Exchange 2019?

### ISSUE THREAD

**Issue by phyle** [MicrosoftDocs/power-platform#258]
This page doesn't list Exchange 2019... is it supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5033cf14-8912-471d-66b7-61ca7e29d752
* Version Independent ID: a7c05a79-cd65-1717-d4a4-0dde3c368263
* Content: [Connect to Exchange Server (on-premises) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-server-on-premises#prerequisites)
* Content Source: [power-platform/admin/connect-exchange-server-on-premises.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/connect-exchange-server-on-premises.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by phyle** [comment]
My initial question was to confirm support of Exchange 2019 for Server-side Sync on [Connect to Exchange Server (on-premises)](https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-server-on-premises#prerequisites)

Can I please add the same question for support of Exchange 2019 with the Dynamics 365 App for Outlook on page [Deploy Dynamics 365 App for Outlook](https://docs.microsoft.com/en-us/dynamics365/outlook-app/deploy-dynamics-365-app-for-outlook) 

Thanks

**Comment by jimholtz** [comment]
@phyle 
I've updated the content for the first topic: Connect to Exchange Server (on-premises) 

Exchange 2019 support for Outlook app is under investigation.
