### ISSUE TITLE
Default Environment Routing:  Second environment created.

### ISSUE THREAD

**Issue by rarroyo111** [MicrosoftDocs/power-platform#2590]
I had a developer environment automatically created for myself, but it took a couple of weeks after configuring the default environment routing.  The next day I had _another_ developer environment automatically created for me.  Any thoughts on how come? Now I have 2 developer environments with the same name.

**Comment by phecke** [comment]
@rarroyo111 Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ Closing this issue.
