### ISSUE TITLE
Teams permissions details

### ISSUE THREAD

**Issue by tombyang** [MicrosoftDocs/power-platform#26]
Please provide details about the level of Teams permissions needed to complete this task

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce60ea6f-d01c-9714-f3f7-db3a11806a34
* Version Independent ID: 435cfd9f-8b1d-d810-a58c-655ca6780286
* Content: [Add a Power Virtual Agents bot to Microsoft Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/publication-add-bot-to-microsoft-teams#feedback)
* Content Source: [power-virtual-agents/publication-add-bot-to-microsoft-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/publication-add-bot-to-microsoft-teams.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by mkchow5928** [comment]
Thank you for your inquiry.  The information has been updated to the document.
