### ISSUE TITLE
Obsolete page

### ISSUE THREAD

**Issue by jhornych** [MicrosoftDocs/power-platform#260]
[Enter feedback here]
This page is outdated, after clicking on the security tab, it redirects me to the Power Platform

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure user security in an environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/database-security)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/database-security.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jhornych 
Please note that the procedure in the topic is for environments with no database. On the Details page, you'll see Create my database, if this environment has no database.
