### ISSUE TITLE
Images don't match what you see in Azure

### ISSUE THREAD

**Issue by Tom-H2oThermo** [MicrosoftDocs/power-platform#2600]
The steps in this page don't match what I see on Azure.  Not a big deal, I can find the correct steps.  Under item 8 it mentions Step 4:  This should be Step 3:  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d0fddb7-43df-2ee6-39f6-a8294977de90
* Version Independent ID: 6d0fddb7-43df-2ee6-39f6-a8294977de90
* Content: [Step 3: Create an AppSource package for your app - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/appsource/create-package-app)
* Content Source: [power-platform/developer/appsource/create-package-app.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/appsource/create-package-app.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @angela21k
* Microsoft Alias: **angelakim**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Tom-H2oThermo. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@Tom-H2oThermo 
Thanks for your feedback. 
I found that your comments related to this article [Step 4: Store your AppSource Package on Azure Storage and generate a URL with SAS key](https://learn.microsoft.com/en-us/power-platform/developer/appsource/store-package-azure-storage) and I fixed the title of the link under item 8.

The screenshots take more time and effort to update, as long as you can find the right steps, we will leave them 'as-is'.  What would you think if we replaced them with AZ CLI commands?

**Comment by JimDaly** [comment]
@Tom-H2oThermo 
Thanks. This is something we have been debating. Appreciate your input.
