### ISSUE TITLE
Error adding a new custom connector to DLP through PowerShell

### ISSUE THREAD

**Issue by Bryand13** [MicrosoftDocs/power-platform#261]
[Enter feedback here]
Hello there,

I'm just trying to use the add-ConnectorToBusinessDataGroup cmdlet but i'm getting this error:

"Get-PowerAppConnector : El término 'Get-PowerAppConnector' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable. Compruebe si escribió 
correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e inténtelo de nuevo.
En C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerApps.Administration.PowerShell\2.0.65\Microsoft.PowerApps.Administration.Powershell.psm1: 65 Carácter: 41
+         $connector = $environments[0] | Get-PowerAppConnector -Connec ...
+                                         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PowerAppConnector:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Add-ConnectorToBusinessDataGroup : No connector with specified name found
En línea: 1 Carácter: 1
+ Add-ConnectorToBusinessDataGroup -PolicyName "ba3990ab-9ef2-416f-a837 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-ConnectorToBusinessDataGroup"

The PowerShell module is update on day.

![image](https://user-images.githubusercontent.com/50946094/84044970-89387580-a9a8-11ea-8dec-7180a9239101.png)

I've tried through PowerShell ISE but the same problem. Any idea on what could be the issue?

Thanks in advance
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Bryand13 
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see https://powerapps.microsoft.com/support/
