### ISSUE TITLE
Get-FlowRun returns details only for flow owner

### ISSUE THREAD

**Issue by marekbuban** [MicrosoftDocs/power-platform#262]
When running Get-FlowRun with admin account (account that has access to all Power Platform resources), Get-FlowRun returns nothing for flows that were not created by that account. There's no alternative like Get-AdminFlowRun, is there a way to export runs from all flows in environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by BenWilliamsLuc** [comment]
Hi @jimholtz  - I'm trying to do this exact thing.
Is there a way to do this? I'd be really keen to get this working for one of our automation solutions!

**Comment by aliyoussefi** [comment]
Hi @BenWilliamsLuc 

Have you had a chance to evaluate usage of the Log Analytics Data Collector API within Power Automate? The API, coupled with the functions within Power Automate, can provide not only run information but details not normally shown within the Get-FlowRun cmdlet. I wrote about my experience using it within Power Automate, I hope it helps! 

References:
Community: https://community.dynamics.com/crm/b/crminthefield/posts/monitoring-the-power-platform-power-automate---run-time-part-3-implementing-a-monitoring-strategy
GitHub: https://github.com/aliyoussefi/MonitoringPowerPlatform/blob/master/docs/05.03.03%20-%20Monitoring%20Power%20Automate%20-%20Run%20Time%20-%20Implementing%20a%20Monitoring%20Strategy.md

Thanks!

Ali

**Comment by BenWilliamsLuc** [comment]
Hi @aliyoussefi 

Thanks for the unbelievably quick answer.. I've been digging around for days trying to put in place my own scheduled monitoring of Power Automates.. I'll have a read and try implement this myself 👍 

Thanks
Ben

**Comment by aliyoussefi** [comment]
Hi @BenWilliamsLuc,

Happy to help, if I can help further please let me know!

Thanks!

Ali
