### ISSUE TITLE
Support for SQL Always encrypted with Data export service

### ISSUE THREAD

**Issue by rupeshprasad** [MicrosoftDocs/power-platform#263]
Hi All - 

I am planning to use Data Export Service to replicate Dynamics data to Azure SQL database for some offline/reporting purposes. The method is outlined in below article. Following this article i was able to make it work without any issue. 

Few of my entities has PII data and as per my companies security guide lines i have to make sure data is encrypted at rest and transit along with always encrypted. 

I know encryption at rest (TDE) is default feature of Azure SQL however i still have below two question and this document does not mention anything about this - 

Can i enable always encryption (column level encryption) and still do data replication
Can i change my connection string to include Encrypt=True and TrustServerCertificate=False in connection string in key vault and it will do encryption in transit as it say in MSFT docs below ? 
https://docs.microsoft.com/en-us/azure/azure-sql/database/security-overview#transport-layer-security-encryption-in-transit

Any help around this will be very helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#how-to-delete-data-export-profile-tables-and-stored-procedures-for-a-specific-entity)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@rupeshprasad 
Sorry for the late response. Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
