### ISSUE TITLE
Is Activity Logging available in GCC and GCCH tenants?

### ISSUE THREAD

**Issue by yashpatel22** [MicrosoftDocs/power-platform#266]
Is activity logging enabled for GCC and GCCH tenants? Clarification on this page would be helpful. 
This link here shows it is not available:
https://docs.microsoft.com/en-us/power-platform/admin/government-feature-availability

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 184dd591-1250-2bcc-db42-35afc3a77bce
* Version Independent ID: 75aaea0f-6f52-3977-77ba-a79f3604ef5e
* Content: [Activity logging for Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps)
* Content Source: [power-platform/admin/logging-powerapps.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/logging-powerapps.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by pnghub** [comment]
The current ETA for Activity logging to be made available in GCC and GCCH by late Sept timeframe.
