### ISSUE TITLE
Stub Users in PowerApps environment

### ISSUE THREAD

**Issue by bpremji** [MicrosoftDocs/power-platform#267]
Has anyone tried creating Stub users in a PowerApps environment (one without the Salesperson security role)?
The following statement doesn't seem to apply"
A default security role is automatically assigned to these imported users. The Salesperson security role is assigned in an environment and the **Common Data Service User security role is assigned in a Power Apps environment.**

I get 'Could not retrieve salesperson role' when trying to create the stub user.  I have confirmed I have the Common Data Service User security role  in my environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6159c3d-47a4-bc29-7dda-52777db307c2
* Version Independent ID: 426568f9-3742-b39e-600d-5f3afd251c19
* Content: [Create users and assign security roles - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-users-assign-online-security-roles#how-stub-users-are-created)
* Content Source: [power-platform/admin/create-users-assign-online-security-roles.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-users-assign-online-security-roles.md)
* Service: **power-platform**
* GitHub Login: @jayasreekumar
* Microsoft Alias: **jkumar**

**Comment by jimholtz** [comment]
@bpremji 
Sorry for the very delayed response. If this is still an issue, please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
