### ISSUE TITLE
Typeo error

### ISSUE THREAD

**Issue by javirivas80** [MicrosoftDocs/power-platform#271]
There are many tipeos error in table https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service#about-this-dashboard API Calls, example Number of API calls that were made by the **Customer** Data Service environment for the selected time period. This should be Common instaead customer?.
Other
API Pass Rate
Executions
Total Operations
Top Plug-ins by Failures
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c99626-6458-46b4-f099-ce10c30890c7
* Version Independent ID: d3766ded-359b-160c-d7f5-a7e6ffa103d6
* Content: [Common Data Service analytics - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service)
* Content Source: [power-platform/admin/analytics-common-data-service.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/analytics-common-data-service.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@javirivas80 
Good grief. Thanks for bringing to my attention. Fixing now.
