### ISSUE TITLE
Out of the Box System Customizer Role.

### ISSUE THREAD

**Issue by learnmsdynamics** [MicrosoftDocs/power-platform#273]
Out of the box **_"System Customizer"_** role does not have **Create Sales Territories** and "Assign Territory to a user" 

![image](https://user-images.githubusercontent.com/67049756/84881443-7c540a00-b0ab-11ea-9cd1-cee99acd2eb3.png)

![image](https://user-images.githubusercontent.com/67049756/84881458-81b15480-b0ab-11ea-95f5-15c96a49bda8.png)

Please change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b40650-ab97-435c-7cfe-d8d581338e15
* Version Independent ID: aa587d84-04c5-ca35-8344-750e5e1008a9
* Content: [Set up sales territories to organize business markets by geographical area - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/set-up-sales-territories-organize-business-markets-geographical-area#create-a-sales-territory-sales-hub-app)
* Content Source: [power-platform/admin/set-up-sales-territories-organize-business-markets-geographical-area.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/set-up-sales-territories-organize-business-markets-geographical-area.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@learnmsdynamics 
Sorry for the very delayed response. For product-related feedback, visit https://ideas.powerapps.com.
