### ISSUE TITLE
Doc Check Request: Exchange 2019 is not mentioned as a supported version, yet is mentioned in the article as a link.

### ISSUE THREAD

**Issue by HugoDurana** [MicrosoftDocs/power-platform#274]
In step 2 of the pre-requisites, we are linking Exchange 2019, yet we don't mention it as a supported version in step 1. Can we please verify and correct this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5033cf14-8912-471d-66b7-61ca7e29d752
* Version Independent ID: a7c05a79-cd65-1717-d4a4-0dde3c368263
* Content: [Connect to Exchange Server (on-premises) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-server-on-premises)
* Content Source: [power-platform/admin/connect-exchange-server-on-premises.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/connect-exchange-server-on-premises.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@HugoDurana 
Thanks for bringing this to our attention. This has been corrected.
