### ISSUE TITLE
Step missing for "Assign a service admin role to a user"

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/power-platform#275]
Under section [Assign a service admin role to a user]( https://docs.microsoft.com/en-us/power-platform/admin/use-service-admin-role-manage-tenant#assign-a-service-admin-role-to-a-user)

Between step 2 and step 3, please add step 2.5 something like the following:

- Under Account > Roles, select to navigate "Manage Roles"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c1dd41e-5994-2eb5-f659-af836a1a3fc1
* Version Independent ID: f70008c9-ea14-96f1-8b29-d94bb510b680
* Content: [Use service admin roles to manage your tenant - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/use-service-admin-role-manage-tenant#assign-a-service-admin-role-to-a-user)
* Content Source: [power-platform/admin/use-service-admin-role-manage-tenant.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/use-service-admin-role-manage-tenant.md)
* Service: **power-platform**
* GitHub Login: @jayasreekumar
* Microsoft Alias: **jkumar**

**Comment by jimholtz** [comment]
@softwarecraft 
Thanks for the suggestion. Text revised.
