### ISSUE TITLE
Trying to make sense of the latest updates to the Power Platform COE Kit?  The install page said all updates are posted in GitHub.  When I downloaded them the files are dated 5/13/20?

### ISSUE THREAD

**Issue by lubergst** [MicrosoftDocs/power-platform#277]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Could you try and elaborate on your question? I am not sure I understand. 

All documentation and setup instructions are hosted on aka.ms/coestarterkit and updated in line with updates to the solution. 

Latest updates and what has changed are called out on the GitHub Repo
https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit (scroll down to the Readme)

![image](https://user-images.githubusercontent.com/55705669/84997710-d655dd80-b146-11ea-970d-3f59f5bdfecf.png)

**Comment by lubergst** [comment]
All set sorry about the cryptic decoding of my post

**Comment by manuelap-msft** [comment]
That's great! Thanks for using the CoE Starter Kit
