### ISSUE TITLE
Slides Linked for THR3005.pptx Has a Confusing Typo

### ISSUE THREAD

**Issue by jameswh3** [MicrosoftDocs/power-platform#279]
Slide 10 of the deck says "Pre license capacity" instead of "Per license capacity."
![image](https://user-images.githubusercontent.com/4581067/85064432-2b0e4e00-b171-11ea-9e8c-90278836b32f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85f443e7-db53-067e-0fc6-73f2e294ef11
* Version Independent ID: 906bfc9f-cb6c-df52-63e0-63cd177d2b9c
* Content: [Videos - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/videos)
* Content Source: [power-platform/admin/videos.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/videos.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jameswh3 
Thanks for bringing this to our attention. We'll try to get this corrected.
