### ISSUE TITLE
Documentation on business process / data model level

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/power-platform#281]
Maybe I missed it, but is there any more data-model / dependency like documentatie on the Flows?
Mainly for troubleshooting and explanation purposes: 

- Flow 1 is scheduled and creates / updates environments / flows / apps
- Flow 2 triggers when flows are created / updated and created connector references / flow action details etc
- Etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
No, you haven't missed it but it's on our documentation roadmap to both draw out a data and dependency model.

**Comment by manuelap-msft** [comment]
We have added type, interval and description columns to the flows here to explain this better https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#flows
