### ISSUE TITLE
Numbering of methods, two Method #10, and update storage information timeframe change

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/power-platform#282]
I'm sure there is a reason, but can the method numbers either be set to go from 1-11 (There are two method 10s) or an explanation for the reasoning of putting methods in a different order. 

The page says it may take 24 hours for storage information to be updated. This is inaccurate, the Power Platform page says it can up to 72 hours now. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9c9aae-ceaa-2e78-3752-2770327f49a7
* Version Independent ID: acd2ddc9-6225-92e8-2636-2a02437c3d82
* Content: [Free up storage space - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/free-storage-space)
* Content Source: [power-platform/admin/free-storage-space.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/free-storage-space.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@StuBeck32 
Thanks for bringing the step text to our attention. This has been corrected. I've been told by the product team that 24 hours is correct. What page did you see 72 hours?

**Comment by StuBeck32** [comment]
Your support team told me it can take up to 72 hours. We’ve found it can be closer to 96 to 120 hours for changes to occur.

Stuart
________________________________
