### ISSUE TITLE
Manage security for your environments - out of date

### ISSUE THREAD

**Issue by hayes3d** [MicrosoftDocs/power-platform#285]
The manage security for environments has been moved to the new Power Platform admin center. Managing users is different...and much more complicated now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6bf79b0-5e31-ebc4-2397-c7274967dd8f
* Version Independent ID: 9b67d821-bfc9-eb04-c10d-31187c655984
* Content: [Manage environments in the Power Apps Admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/environments-administration)
* Content Source: [power-platform/admin/environments-administration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/environments-administration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@hayes3d 
Thanks for bringing this to our attention. We've updated the topic with a link to the current security content.
