### ISSUE TITLE
Please confirm and add the integration with Exchange 2019. 

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/power-platform#287]
Please confirm and add the integration with Exchange 2019. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5033cf14-8912-471d-66b7-61ca7e29d752
* Version Independent ID: a7c05a79-cd65-1717-d4a4-0dde3c368263
* Content: [Connect to Exchange Server (on-premises) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-server-on-premises#prerequisites)
* Content Source: [power-platform/admin/connect-exchange-server-on-premises.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/connect-exchange-server-on-premises.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@MichaelWeberMSFT 
Thanks for your feedback. Confirmed Exchange Server 2019 is supported and added to the list.
