### ISSUE TITLE
Documentation is not up to date

### ISSUE THREAD

**Issue by mcampsteyn** [MicrosoftDocs/power-platform#288]
The documentation on assigning per app licenses is not up to date.
The interface and menu structure is different.

![image](https://user-images.githubusercontent.com/20879893/85545925-b4fc6200-b61c-11ea-89e1-34873fd5e4ae.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1f9ece-05b6-907c-9d52-5a19f5bf9872
* Version Independent ID: 9eaed30a-4c07-ef03-e3b4-d3db9989a760
* Content: [About Power Apps per app plans - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-powerapps-perapp)
* Content Source: [power-platform/admin/about-powerapps-perapp.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/about-powerapps-perapp.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by fitzgeezy** [comment]
I would also like the document updated to more accurately reflect the new menu structure and licensing process.

**Comment by jimholtz** [comment]
Thanks for the feedback. We've updated the topic.
