### ISSUE TITLE
No Documentation for $NewPolicy or $UpdatedPolicy

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/power-platform#289]
Hi

The DLP commands New-DLPPolicy and Set-DLPPolicy have parameters $NewPolicy and $UpdatedPolicy respectively which define the new DLPPolicy or the Updated DLPPolicy is..  But I cannot find any examples of what a $NewPolcy Object or an $UpdatedPolicy look like..

Thanks

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@NPrice99 
We've recently published the following. Check to see if it provides what you're looking for.
https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/?view=pa-ps-latest
