### ISSUE TITLE
Power BI Dashboard App Last Launch

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/power-platform#290]
Could it be that Last Launch data is not being filled in?
I would expect it in the **Admin | Sync Template v2 (Apps)** flow, but no data of field **App Last Launched On** being updated in the Switch?

**Comment by jimholtz** [comment]
@m3ngi3 
Sorry for the delayed response. This is likely no longer an issue. Please reopen if that is not the case.
