### ISSUE TITLE
Assign Security Roles to an AAD Security Group Connected Team??

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/power-platform#291]
Where to assign Security Roles to an AAD Security Group Connected Team??
When selecting Owner Team the **Manage Roles** button shows, but for an AAD Security Group Connected Team the button does not show...

**Comment by jimholtz** [comment]
@m3ngi3 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
