### ISSUE TITLE
Incorrect instructions link

### ISSUE THREAD

**Issue by correnasergent** [MicrosoftDocs/power-platform#292]
The current instructions say:  Environments > [select an environment] > Settings > Integration > Manage document suggestions.

The actual link is:  Environments > [select an environment] > Settings > Integration > Document Management settings > Manage document suggestions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d19ecb2e-fd52-8bfe-87a9-3cc6039c5bd1
* Version Independent ID: 1ffff37c-c73b-d07f-5312-7049730dfa90
* Content: [Enable document suggestions for Dynamics 365 for Customer Engagement apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/enable-document-suggestions)
* Content Source: [power-platform/admin/enable-document-suggestions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/enable-document-suggestions.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@correnasergent 
Thanks for bringing this to our attention. Content has been updated.
