### ISSUE TITLE
Max teams increase

### ISSUE THREAD

**Issue by correnasergent** [MicrosoftDocs/power-platform#293]
I believe the max entities for access teams (MaxEntitiesEnabledForAutoCreatedAccessTeams) was increased from 5 to 100 per this work item:
https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/1058331

Due to performance considerations, maybe we are still suggesting to stay under 5 but we should update the documentation either way.  

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148f041b-a63f-470c-ec11-08a2ebd3bde1
* Version Independent ID: 546ce331-8abc-4187-9bfa-6f4d4e03e62c
* Content: [Manage teams - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-teams)
* Content Source: [power-platform/admin/manage-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-teams.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Thanks for the info. The content has been updated.
