### ISSUE TITLE
DLP Editor Data Group Blocked

### ISSUE THREAD

**Issue by javirivas80** [MicrosoftDocs/power-platform#295]
Hi, I wanted to ask you if you plan to include the new Block Data Group classification in the DLP editor. Https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention#the-effect-of -the-blocked-data-group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e88f289-b527-30ab-a2b5-a27d98745516
* Version Independent ID: 4fffa137-7df2-546c-988e-fa7ddf1028b5
* Content: [Microsoft Power Platform Center of Excellence Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/starter-kit)
* Content Source: [power-platform/guidance/coe/starter-kit.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/starter-kit.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback; we are currently waiting for an update to the Power Platform Management Connectors (https://docs.microsoft.com/en-us/connectors/powerplatformforadmins/) and will then evaluate making that change!

**Comment by javirivas80** [comment]
Oh great, what kind of update are waiting on the connector?. 👍

**Comment by manuelap-msft** [comment]
Three-way DLP policy creation isn't available through admin connectors, as documented here https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention#known-issues

As the DLP Editor also allows you to save policies, we need to wait for this feature to be available before we can make any changes.
