### ISSUE TITLE
Suggestion - Add text in Dynamics 365 COM add-in deprecation detailing what is going out of support.

### ISSUE THREAD

**Issue by HugoDurana** [MicrosoftDocs/power-platform#297]
On the document below, I would suggesting adding a reference to page 19 of the Dynamics COM add-in playbook for more information on deprecation.

Also, the way that the text is written is likely to cause panic between fully On-Premises users. We should make it very clear that the deprecation is targeted solely at the users that are using the Online environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and model-driven apps in Dynamics 365 - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/important-changes-coming.md)
* Service: **dynamics-365-crossapp**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KendalBond007** [comment]
Closing this issue because it has been open for over 3 years. The referenced doc was updated 29 Jun 2023. If you're still experiencing the issue described here, please reopen or create a new issue.
