### ISSUE TITLE
The first paragraph is repeated twice

### ISSUE THREAD

**Issue by lucashuet93** [MicrosoftDocs/power-platform#298]
[Enter feedback here]

The first paragraph is repeated twice by mistake. It currently reads "Use Microsoft Power Platform Build Tools to automate common build and deployment tasks related to apps built on the Power Platform. These tasks include: Use Microsoft Power Platform Build Tools to automate common build and deployment tasks related to apps built on the Power Platform. These tasks include:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Microsoft Power Platform Build Tools for Azure DevOps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tools.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by mikkelsen2000** [comment]
Which paragrap – create environment? One is the title, the next is what the task does

**Comment by Mattp123** [comment]
@lucashuet93 - I'm sorry, but I don't see the first paragraph repeated per your issue. 

Closing issue.
