### ISSUE TITLE
Are non-public sites supported for getting PVA topic suggestions?

### ISSUE THREAD

**Issue by BeigeBadger** [MicrosoftDocs/power-platform#299]
As the title states, the documentation does not explicitly state whether or not a site must be publicly accessible to be able to be ingested (my assumption is that only public sites can be ingested).

Are there plans to add support for authenticated sites, such as what QnA Maker has with the [SharePoint connection functionality](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/add-sharepoint-datasources)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78f1747-04bf-3bb7-c1e1-9025710e022f
* Version Independent ID: 1da1f8d8-f0e5-64e1-7503-39973b0f38e2
* Content: [Get Power Virtual Agents topic suggestions from support pages - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-create-topics-from-web)
* Content Source: [power-virtual-agents/advanced-create-topics-from-web.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-create-topics-from-web.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
I'm investigating/confirming this now, but I believe you are correct in that suggestions from web won't work on authenticated sites.

**Comment by iaanw** [comment]
I have confirmation that currently only publicly-accessible sites are allowed.
