### ISSUE TITLE
What is relationship? Is it only the metadata or actual data?

### ISSUE THREAD

**Issue by MikeSpark** [MicrosoftDocs/power-platform#3]
I found my profile will fail if I include relationship, therefore excluding them; however I don't know what are they.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#feedback)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@MikeSpark 
Please see: https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-edit-entity-relationships. I'll make an addition to the topic to point to this content.
