### ISSUE TITLE
Steb 3.b add entire orgianization

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/power-platform#30]
I cant find any feature in the admin center that lets me add the entire organization. my only option seems to be add 1 user at a time..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6bf79b0-5e31-ebc4-2397-c7274967dd8f
* Version Independent ID: 9b67d821-bfc9-eb04-c10d-31187c655984
* Content: [Manage environments in the Power Apps Admin center - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/environments-administration)
* Content Source: [power-platform/admin/environments-administration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/environments-administration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Ballzer0 
I'm not sure I understand the issue. Are you looking to bulk add users?
See:
[Add users individually or in bulk to Office 365](https://docs.microsoft.com/en-us/office365/admin/add-users/add-users?redirectSourcePath=%252fen-US%252fArticle%252fCreate-or-edit-users-in-Office-365-1970f7d6-03b5-442f-b385-5880b9c256ec&view=o365-worldwide)

**Comment by Ballzer0** [comment]
Under the section **Manage security for your environments** at step 3.b it says I should be able to add an entire organization to an environment. But I can only add a single user at a time

**Comment by jimholtz** [comment]
@Ballzer0 
Ah, I see the issues. This content needs updating. I'll do so soon.

**Comment by jimholtz** [comment]
@Ballzer0 
I updated the screenshot which shows "Add everyone in my org". To see that setting, you need to have an environment created without a database. If you have such an environment and still no add everyone setting, please contact support.

**Comment by Ballzer0** [comment]
> @Ballzer0
> I updated the screenshot which shows "Add everyone in my org". To see that setting, you need to have an environment created without a database. If you have such an environment and still no add everyone setting, please contact support.

Is there a reason why I can't add the entire organization to an environment with a database?

**Comment by jimholtz** [comment]
@Ballzer0 
It’s not supported due to implementation limitations. There are differences in the authorization layer between environments with and without databases. Environments without databases don't support role association to the tenant.

**Comment by Ballzer0** [comment]
@jimholtz do you have any idea if this is planned functionality? 
It's really inconvenient to have to add and remove users 2 places as they join and leave the organization. Especially we where unde the understanding that this was a part of our platform.
