### ISSUE TITLE
Does Power Virtual Agent supports Alphanumeric and Non List Domain Custom entities

### ISSUE THREAD

**Issue by Murgates** [MicrosoftDocs/power-platform#300]
I'm designing a bot using Microsoft Power Virtual Agent. I want to create a custom entity which is type of Alphanumeric. And I want to create a custom entities which captures source and destination city for flight booking topic.

Custom Entities by default has "List" as a method, there is no option to choose different methods. How to we add Alphanumeric custom entities ?

Though it has a prebuilt entity for "City" that just extracts the city names, whereas in my scenario based on the context city can be either Source city or destination city. Looks like there is no provision to handle this ?

Is there a roadmap to add it ?

**Comment by iaanw** [comment]
Thanks for your question! The best place for product requests or troubleshooting is the Power Virtual Agents forum at https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums - repost your question there and an engineer will be able to help you.
