### ISSUE TITLE
The tenant option is not avaialble

### ISSUE THREAD

**Issue by thealisakhi** [MicrosoftDocs/power-platform#301]
[Enter feedback here]
The page is not available to download the user license guide. Admin center is moved, and there is no tab of Tenant on the left side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b45f80-ff57-2bfe-2195-1a9376986b59
* Version Independent ID: 1e776630-ea6f-ac89-14ef-d767575a870d
* Content: [Licensing and license management - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/wp-license-management)
* Content Source: [power-platform/admin/wp-license-management.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/wp-license-management.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@thealisakhi 
Tenant does appear in the Power Apps admin center. This admin center will be retired soon and the documentation will be updated then.

**Comment by thealisakhi** [comment]
Hi @jimholtz 

What is the alternative to get the report, on what date a licensed was assigned to users. Currently in Dynamics 365 you will see a full list of office 365 users.
