### ISSUE TITLE
manifest.json Error When Following These Instructions

### ISSUE THREAD

**Issue by jameswh3** [MicrosoftDocs/power-platform#302]
A colleague of mine and I both followed these instructions and were presented with an error regarding the manifest.json.  The error detail was:
Error while reading manifest.json: "staticTabs[0].name" is required 
 "staticTabs[0].contentUrl" is required 
 "staticTabs[1].name" is required 
 "staticTabs[1].contentUrl" is required 

It appears that the App Studio generates two tabs automatically, and the automatically-generated manifest.json does not have these properties present.  If we attempt to edit the properties for these tabs, that is not possible in App Studio (screenshot below).

![image](https://user-images.githubusercontent.com/4581067/86407459-b6600700-bc7a-11ea-8247-41706c4fa57f.png)

Furthermore, the error page that's presented when the app fails to install is designed in such a way that the most prominent control for the user jumps to the app store and loses the context without informing the user that it saved the progress thus far.

![image](https://user-images.githubusercontent.com/4581067/86407568-e8716900-bc7a-11ea-8093-f999997db80c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce60ea6f-d01c-9714-f3f7-db3a11806a34
* Version Independent ID: 435cfd9f-8b1d-d810-a58c-655ca6780286
* Content: [Add a Power Virtual Agents bot to Microsoft Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/publication-add-bot-to-microsoft-teams#add-your-bot-to-microsoft-teams)
* Content Source: [power-virtual-agents/publication-add-bot-to-microsoft-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/publication-add-bot-to-microsoft-teams.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
I'm investigating this issue and will hope to have an answer for you. I'm not sure if this is something that can be fixed with documentation, so you might want to post this on the PVA forum https://powerusers.microsoft.com/t5/Power-Virtual-Agents-Community/ct-p/PVACommunity

**Comment by iaanw** [comment]
Please repost this on the community forum as it's not a doc issue unfortunately, thanks.
