### ISSUE TITLE
What is about Power Platform Model-driven Apps

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/power-platform#305]
[Enter feedback here]
Hi,

I'm a bit confused about the wording in this page. The page is under Power Platform, but doesn't mention anything about Power Platform model-driven apps. Only Dynamics model-driven apps are mentioned. Does it mean, that server-side synchronization is not available for Power Platform model-driven apps?

Regards,
Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152838a5-73a6-4470-03fc-f372f99d3a97
* Version Independent ID: 83bbd4a6-586f-4f70-bddb-beaabfbdb7b9
* Content: [Server-side synchronization - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/server-side-synchronization)
* Content Source: [power-platform/admin/server-side-synchronization.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/server-side-synchronization.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@soutchilin 
We are working to clarify terminology. Server-side sync is available for Power Platform model-driven apps. For example:
https://docs.microsoft.com/powerapps/sample-apps/regional-emergency-response/deploy#step-9-set-up-server-side-synchronization-of-emails
