### ISSUE TITLE
Build pipeline: Build a managed solution

### ISSUE THREAD

**Issue by jef3003** [MicrosoftDocs/power-platform#306]
[Enter feedback here]
Build pipeline: Build a managed solution
==> this pipeline seems to be wrong.  You are importing a unmanaged solution and exporting the solution again without publishing the customizations.  This can cause unexpected behaviour in the managed solution that is being created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tool-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment]
@jef3003 If you are still having this problem, please file a new issue.
