### ISSUE TITLE
Reuse existing QnA maker Knowledge Base 

### ISSUE THREAD

**Issue by Expecho** [MicrosoftDocs/power-platform#31]
We have an existing QnA maker Knowledge Base and would like to reuse it in our Virtual Agent , is that possible using the way documented here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78f1747-04bf-3bb7-c1e1-9025710e022f
* Version Independent ID: 1da1f8d8-f0e5-64e1-7503-39973b0f38e2
* Content: [Get Power Virtual Agents topic suggestions from support pages - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-create-topics-from-web)
* Content Source: [power-virtual-agents/advanced-create-topics-from-web.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-create-topics-from-web.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
@michaeltjalve Please take a look

**Comment by iaanw** [comment]
This should be possible. Please let us know if you have issues at the aka.ms/pvaideas forum.
