### ISSUE TITLE
Incorrect documentation - add-powerappsaccount is not functional

### ISSUE THREAD

**Issue by seanmcne** [MicrosoftDocs/power-platform#310]
These two examples are non-functional / do not work and must be updated - or the module has a bug: 

![image](https://user-images.githubusercontent.com/2292260/87346328-20986780-c517-11ea-8516-d19cb2957a93.png)

![image](https://user-images.githubusercontent.com/2292260/87346359-2db55680-c517-11ea-8b38-fa906b2938ac.png)

----------------------------------
![image](https://user-images.githubusercontent.com/2292260/87346382-360d9180-c517-11ea-864d-02f2de264a8b.png)

![image](https://user-images.githubusercontent.com/2292260/87346466-5b9a9b00-c517-11ea-9453-2ba8fe083040.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by aliyoussefi** [comment]
@seanmcne Hi Sean, I'm curious as these are working fine for me. Are you using version  2.0.70 for the Administration module?
![image](https://user-images.githubusercontent.com/20861971/87549961-1b046400-c674-11ea-842c-288a3a09b6d9.png)
Here is the code I used...it worked for both passed in arguments and passive:
![image](https://user-images.githubusercontent.com/20861971/87550028-30798e00-c674-11ea-9ed6-7a451d60d740.png)

NOTE: I did run into an issue with MFA, AAD returns AADSTS50076

**Comment by seanmcne** [comment]
I think the team broke this in .67 and must have fixed it in .70

I’ll try to test it again today.
