### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by PhilLeitch** [MicrosoftDocs/power-platform#311]
I followed the instructions and yet my Power Platform Admin Centre has not changed.  It's been two days. Is there another task I need to take to make it refresh?  The date it shows in the Power Platform Admin Centre is last month.  How do I get current information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a8f913f-f933-fb4b-9453-7a9e840de127
* Version Independent ID: fd928fdf-b49b-aa46-26d5-efdb861dc83f
* Content: [Recover database space by deleting audit logs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/recover-database-space-deleting-audit-logs)
* Content Source: [power-platform/admin/recover-database-space-deleting-audit-logs.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/recover-database-space-deleting-audit-logs.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@PhilLeitch 
Please create a support request:
https://powerapps.microsoft.com/support/

**Comment by PhilLeitch** [comment]
No - this is a documentation issue.  The documentation does not describe how to see the effect of the action.  How do I get current information?
