### ISSUE TITLE
problem installing sample data

### ISSUE THREAD

**Issue by khinethinzarsoe** [MicrosoftDocs/power-platform#312]
I installed sample data for customer service to follow exercise for MB-230. 
I've got "Sample data is currently being installed/removed. Only one install/remove operation is allowed at a time".
It has been nearly 24 hours since I started installing it. Only close button is enable, how should I proceed?

**Comment by jimholtz** [comment]
@khinethinzarsoe 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/

**Comment by khinethinzarsoe** [comment]
Thank you!
