### ISSUE TITLE
Set up core components - Activate the Sync Template flows - #7 Issue: Many flows Listed to be copied not found

### ISSUE THREAD

**Issue by TLBGT** [MicrosoftDocs/power-platform#315]
According to Step 7, the user is to copy the following flows:
Admin | Sync Template v2 – Apps, Connectors, Custom Connectors, Flows, Model Driven Apps, Sync Flow Errors, Check Deleted, Flow Action Details, Power Apps User Shared With, PVA

However, the following flows can't be found:
Check Deleted, Flow Action Details, Power Apps User Shared With, PVA
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Those flows have been introduced with the latest version; you can find information about the release in our [release notes](https://docs.microsoft.com/en-us/power-platform/guidance/coe/release-notes/core-1.52). If you are using an older version of the CoE Starter Kit, those flows won't exist.
