### ISSUE TITLE
Please update incorrect steps

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/power-platform#316]
Under "Add a partner to an existing subscription" this step is incorrect:

2. Go to Billing > Products & services and select a subscription.

"Products & Services" is not an option. Under Licenses > "Go to Products & services" there is no option for partners.

I would also like to add that it is extremely frustrating  how often I find mistakes like this in documentation. If the instruction manual isn't ready, the product isn't ready. The amount of compounded wasted time that results from all the pointless Office 365 GUI changes must be incalculable and astronomical. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6985ca13-b574-4d28-52f1-eca702b268bb
* Version Independent ID: d15b3013-95b5-1e57-825c-055f50d45878
* Content: [Add a Partner of Record (POR) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/add-partner-record-subscription)
* Content Source: [power-platform/admin/add-partner-record-subscription.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/add-partner-record-subscription.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@ckssaas 
Thanks for bringing this to our attention. The procedure has been corrected.
