### ISSUE TITLE
PowerApps vs. Dynamics Environment

### ISSUE THREAD

**Issue by dhawal16** [MicrosoftDocs/power-platform#317]
Can you please provide a way to identify if the Environment is a PowerApps environment or D365 ?
Eariler it use to a property called CreationType to identify if the environment is PowerApps or D365 but now creation moved under admin.powerplatform.com there is no way to identify that.

Please let me know.

Thanks,
Dhawal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-environment#provisioning-a-new-environment)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@dhawal16 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
