### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by LevGelman** [MicrosoftDocs/power-platform#318]
This links is broken - https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/Audit%20Log%20(MFA)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-an-azure-app-registration)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you for pointing that out! We have shuffled a few things around in the GitHub repo and must have missed updating this link - will do that the next time we update docs.

In the meantime, here's the correct link: [Download Audit Log solution ](https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceAuditLogs_1_0_0_17_managed.zip)

**Comment by LevGelman** [comment]
Thanks !!!

**Comment by Craig-Humphrey** [comment]
Note: This is still broken, however the connector is included in the CoE Starter Kit ZIP file.

**Comment by manuelap-msft** [comment]
The instructions here have been changed to download the entire CoE solution from GitHub via https://aka.ms/coestarterkitdownload, extracting the zip and importing the Audit Log solution (CenterofExcellenceAuditLogs_x_x_x_xxx_managed.zip). Thank you for pointing this out!
