### ISSUE TITLE
Vague definition "1,000 per user pass". What is "user pass"

### ISSUE THREAD

**Issue by keijiinoue** [MicrosoftDocs/power-platform#319]
[Enter feedback here]
This page describes limitations.
The text "1,000 per user pass" in "Microsoft Power Platform requests allocations based on licenses" section is vague.
This page should define what is "user pass", because audiences cannot understand the "user pass" text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@keijiinoue 
Finally getting this corrected. Thanks for the feedback.
