### ISSUE TITLE
URLs to find the right portal

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/power-platform#32]
Use https://admin.powerplatform.microsoft.com/ instead of https://admin.powerapps.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcbc305a-4582-7c46-7716-93c192a0f4d5
* Version Independent ID: 9fcacd77-43c3-4281-c891-f72721493a4f
* Content: [Manage Common Data Service settings - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/admin-settings?source=docs#feedback)
* Content Source: [power-platform/admin/admin-settings.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/admin-settings.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@soutchilin 
Thanks for the suggestion. We've updated the topic with a link to the Power Platform Admin center.
