### ISSUE TITLE
Description for "Administrative users" should be added

### ISSUE THREAD

**Issue by keijiinoue** [MicrosoftDocs/power-platform#320]
[Enter feedback here]
There is a following sentence in "Non-licensed users/application users/Users with special free licenses" section:
--
"Base request capacity is defined at the tenant level and can only be used by non-licensed users, application users, and users who have free ($0) licenses."
--
The sentence should have any description for "Administrative users", because it was mentioned earlier in the section. 
The lack of the description for "Administrative users" would cause that audiences got lost.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@keijiinoue 
You can click on the link for administrative users which will lead you to the definition.
