### ISSUE TITLE
Where can I find information on removing Dynamics 365 Apps?

### ISSUE THREAD

**Issue by kg6wtr** [MicrosoftDocs/power-platform#321]
This documents the installation of D365 apps but does not document how to remove them.    Since this doc is titled "Manage Dynamics 365 apps" I expected to see some reference to how to remove apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7afcf1bf-4570-e586-a016-3273589910cf
* Version Independent ID: 47488450-bc47-aead-2c22-7c0989de4cbb
* Content: [Manage Dynamics 365 apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-apps)
* Content Source: [power-platform/admin/manage-apps.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-apps.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@kg6wtr 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Thanks for the suggestion. We've added a link to the remove app content.
