### ISSUE TITLE
Fix Connections Instead of "Save-As"

### ISSUE THREAD

**Issue by swoodhousecoop** [MicrosoftDocs/power-platform#323]
In the guides for the flows provided for this solution it recommends you "Save As" each of the flows and then run them. Other than it being easier to save-as, is there any drawback to manually going into each flow and fixing broken connections so that the flow remains within the solution? Does the solution still function correctly if you fix connections and turn on the flow within the solution?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-gb/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Yes, the solution will still function correctly if you turn on the flows inside the solution. The other drawback is that if you choose to make customizations to any of the flows, they would get overwritten during an upgrade. 

Hope that helps, and thanks for using the CoE Starter Kit!
