### ISSUE TITLE
PVA on Yammer Site

### ISSUE THREAD

**Issue by cleonmukul** [MicrosoftDocs/power-platform#325]
It is possible to add an IFRAME to a Yammer site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf0132e7-6b99-b0ff-650f-bf7db1dece23
* Version Independent ID: 5ee9108a-a8ed-f5f3-d496-df8f995aca52
* Content: [Configure a Power Virtual Agents bot for a live or demo website - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/publication-connect-bot-to-web-channels)
* Content Source: [power-virtual-agents/publication-connect-bot-to-web-channels.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/publication-connect-bot-to-web-channels.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for your question! The best place to get an answer to this is at the Power Virtual Agents forum at https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums - repost your question there and an engineer will be able to help you, or someone from the community might already have tried publishing a bot on a Yammer page. You could also try the Yammer docs at https://docs.microsoft.com/en-us/yammer/
