### ISSUE TITLE
Where is the AI free trial?

### ISSUE THREAD

**Issue by FireRiverWalk** [MicrosoftDocs/power-platform#327]
How do I sign up for my 30 day trial for AI Builder.  I already have Power Apps.  Each time I click on the AI drop down and select Model or Build I get a something went wrong error.  You should put a link to the 30 day trial sign up in the 
page

 https://docs.microsoft.com/en-us/ai-builder/administer-licensinghttps://docs.microsoft.com/en-us/ai-builder/administer-licensing

![image](https://user-images.githubusercontent.com/68390395/88311373-d06f9100-ccde-11ea-8ab5-c274caa3c3bb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#ai-builder)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@FireRiverWalk 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Please reopen if this issue still exists.
