### ISSUE TITLE
How to consume Automate Per Flow

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/power-platform#328]
there are no details on how to assign power automate per flow licensing once it has been purchased.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#the-power-apps-per-app-plan-allows-users-to-run-specific-apps-can-you-explain-what-this-means-in-terms-of-the-number-and-types-of-apps-i-can-use)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@bakerm00 
Please see: https://docs.microsoft.com/power-platform/admin/create-users-assign-online-security-roles#add-a-license-to-a-user-account
