### ISSUE TITLE
Missing Instructions to Unhide Tabs

### ISSUE THREAD

**Issue by WhereCodeGoesToDie** [MicrosoftDocs/power-platform#329]
Embed Power App sections is missing a step to unhide the tabs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c365c412-6317-0eb4-b7a1-0a5cc84b1cbd
* Version Independent ID: 9e39031d-66dd-bf29-1b5c-a93608badc60
* Content: [Set up the Power BI dashboard - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi)
* Content Source: [power-platform/guidance/coe/setup-powerbi.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-powerbi.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Could you share some more details please? The App and Flow Details tabs in the dashboard are hidden by default.

**Comment by manuelap-msft** [comment]
Closing as no action on CoE Team.
