### ISSUE TITLE
How does an MPN Partner use Signature Cloud support ?

### ISSUE THREAD

**Issue by AndrewCussons** [MicrosoftDocs/power-platform#33]
For 
4. … Create a support request and 5. … access or contract ID
Q1. How does an MPN Partner use Signature Cloud Support (professional, no premier)?
Do  they need to select Yes for File as a Premier support request? Then enter the  Signature Cloud Support access ID and contract ID.

IF we select the premier option
Q2. Will we be able to use a single shared access ID for multiple users (normal for professional contracts) or be forced to use a single access ID per users (required for premier) ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3296698b-48cc-9655-267e-92775f33e0b7
* Version Independent ID: fe8f88d2-5fd4-6946-4ae6-d1abb856bf2f
* Content: [Get Help + Support - Power Platform Admin center](https://docs.microsoft.com/en-gb/power-platform/admin/get-help-support?source=docs)
* Content Source: [power-platform/admin/get-help-support.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/get-help-support.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@AndrewCussons 
You will need an access ID and contract ID.
https://support.microsoft.com/en-us/help/2904733/microsoft-partner-network-support-contract-activation
https://support.microsoft.com/en-us/help/4020188/technical-support-for-microsoft-partners
