### ISSUE TITLE
How to add only specific connectors into "Non-Business" category using Powershell Commands?

### ISSUE THREAD

**Issue by dips23** [MicrosoftDocs/power-platform#330]
Hello,

Currently MPP is having three groups to classify the connectors, while there is only one PowerShell command to add connectors in "Business" Only data group as follows:

Add-ConnectorToBusinessDataGroup

However, to keep specific connectors ( 5/6 connectors) in non-business data group, there is no easy way as, not all ( 300+) connectors can be moved easily into "Blocked" category, so I have to manually select connectors except specific connectors from "Non-Business" category and move them into the "Blocked" category which is a little tedious task, while there is no PowerShell command available on the same as per my current knowledge.

Is there any other work around to keep only only specific "Connectors" into "Non-Business" category and move rest of the connectors into "Blocked" category?

Thanks and Regards,
Dipti

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@dips23 
Thanks for the feedback. From the product team, please consider using DLP cmdlets and SDK samples:
https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#data-loss-prevention-dlp-policy-commands
https://docs.microsoft.com/en-us/power-platform/admin/data-loss-prevention-sdk
