### ISSUE TITLE
link is broken for prerequisites of DES

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/power-platform#331]
[Reference link mentioned in prerequisites of DES for **'Azure SQL database service'** is broken "or SQL Server on Azure VM, the "Connect to SQL Server over the Internet" option should be enabled. More information:" 

:  https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-windows-classic-sql-connect?toc=%2fazure%2fvirtual-machines%2fwindows%2fclassic%2ftoc.json

Please edit/update it with correct link/URL. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#best-practices-when-using-azure-sql-database-with-data-export)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@HinaMS 
Thanks for bringing this to our attention. The link has been updated.
