### ISSUE TITLE
Dynamics 365 Finance is missing under Dynamics 365 Enterprise applications

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/power-platform#332]
Why Dynamics 365 Enterprise applications doesn't include Dynamics 365 Finance? In licensing guide, it mentions Dynamics 365 Finance as qualifying licenses for Power Automate.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@sbaber82 
Sorry for the delayed response. This is likely no longer an issue. Please reopen if that is not the case.
