### ISSUE TITLE
Forward looking guidance for CDS connector

### ISSUE THREAD

**Issue by magesoe** [MicrosoftDocs/power-platform#333]
In the coming deprecations section you hint that you intent on removing the CDS connector where you connect to a specific environment https://docs.microsoft.com/en-us/power-platform/important-changes-coming#forward-looking-guidance

This seems to have undesired consequences for the data integrator, where you want to send/fetch data to/from a specific environment. There you create connection sets, something that is done from the admin site, thus it is not deployed to different environments. How do you plan on handling this if you resort to only having the current environment connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and model-driven apps in Dynamics 365 - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/important-changes-coming.md)
* Service: **dynamics-365-crossapp**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by JimDaly** [comment]
Currently the Common Data Service (Current Environment) connector is limited to the current environment.
But that just describes the way it works today.
To enable people to migrate from older connectors, we will need to provide equal capabilities, including connecting to different environments.  

I hope that answers your question.

**Comment by magesoe** [comment]
What you're saying  conflicts with what you write in your documentation.

"When the Common Data Service (Current Environment) connector represents a viable replacement for all situations where the Dynamics 365 and Common Data Service connectors are used today, we intend to remove both the current Dynamics 365 and Common Data Service connectors so that a single connector based on the Common Data Service (Current Environment) connector will remain. At that time it will be required to convert any Flows, Logic Apps and Canvas Apps still using the Dynamics 365 and Common Data Service connectors."

How can you have a current environment connector that can also connect to other environments?

**Comment by JimDaly** [comment]
We will change the name.
