### ISSUE TITLE
PVA with Facebook Messenger

### ISSUE THREAD

**Issue by rubentlc** [MicrosoftDocs/power-platform#334]
I have already configured my bot with Facebook Messenger and it works. My question now are the follow:

- PVA should have information about the user that is talking with the bot, right? How can I get this information? For example, the userId, the name.

- How can I show Facebook Message Templates to the user? Do I need to do POST requests to Facebook API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b159b2e-9bec-64bf-6597-7d0dba599f34
* Version Independent ID: 1546d70b-b24c-f1d6-1448-1c5d0768909c
* Content: [Add a Power Virtual Agents bot to Facebook - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/publication-add-bot-to-facebook#configure-the-facebook-channel-in-power-virtual-agents)
* Content Source: [power-virtual-agents/publication-add-bot-to-facebook.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/publication-add-bot-to-facebook.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for your questions! The best place for product requests or troubleshooting - especially for info to/from Facebook - is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
