### ISSUE TITLE
Package Deployer runs "non-threaded" while importing via PowerShell

### ISSUE THREAD

**Issue by jaredhilton** [MicrosoftDocs/power-platform#339]
While running using the desktop client, Package Deployer runs on 5 threads. Running Package Deployer through PowerShell it runs on one thread and therefore reducing the efficiency of the package deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc997189-b9f4-653c-1188-5663e1a6367e
* Version Independent ID: 3113cafa-56e7-0e45-999f-fa18d50e28cb
* Content: [Deploy packages using Package Deployer and Windows PowerShell - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/deploy-packages-using-package-deployer-windows-powershell)
* Content Source: [power-platform/admin/deploy-packages-using-package-deployer-windows-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/deploy-packages-using-package-deployer-windows-powershell.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by jaredhilton** [comment]
Curious if there are any updates here?

**Comment by jimholtz** [comment]
@jaredhilton 
Sorry for the delayed response. I'm raising this with the product team for a response.

**Comment by laneswenka** [comment]
I am following up internally to see who owns this area, as it falls outside of mine at the moment.

**Comment by MattB-msft** [comment]
Hi @jaredhilton, the PowerShell limitation on import threads is intentional due to the variety of authentication types and behaviors supported by the underlying code.  We have considered adding thread counts for oAuth based authentication flows but have not picked up the work for it yet. 

Note: we have also added PackageDeployment support to the PowerApps CLI.
