### ISSUE TITLE
Command needs update to new one.

### ISSUE THREAD

**Issue by abdulhaqsayed** [MicrosoftDocs/power-platform#34]
The command "Get-AdminPowerAppEnvironment -Default | Get-AdminConnection" needs update to "Get-AdminPowerAppEnvironment -Default | Get-AdminPowerAppConnection"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#feedback)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@abdulhaqsayed 
Thanks for bringing this to our attention. We've corrected the text.
