### ISSUE TITLE
Related to Copy an environment 

### ISSUE THREAD

**Issue by sathi0212** [MicrosoftDocs/power-platform#340]
In this documentation _**we can see that source and destination environments must be in the same region**_. (in the note).
However, as far as i know the Copy operation is only possible if the environments are under same tenant. If it is true, would it be possible to update the Note section with this one as well, else if there is any possible way please share the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95518171-ce8d-6336-2a3e-9fecc18b49e8
* Version Independent ID: 650cb6e1-85bd-15e5-92fc-4b30b93a1a03
* Content: [Copy an environment to a sandbox environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/copy-environment#copy-an-environment-to-a-sandbox-environment)
* Content Source: [power-platform/admin/copy-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/copy-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@sathi0212 
You are correct. Same tenant required. We'll update the topic note. Thanks for the feedback.
