### ISSUE TITLE
Download List of Users

### ISSUE THREAD

**Issue by swettstein** [MicrosoftDocs/power-platform#341]
The PowerApps Admin center is no longer available. How can we download a list of users to see which ones are still on trial licenses?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b45f80-ff57-2bfe-2195-1a9376986b59
* Version Independent ID: 1e776630-ea6f-ac89-14ef-d767575a870d
* Content: [Licensing and license management - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/wp-license-management)
* Content Source: [power-platform/admin/wp-license-management.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/wp-license-management.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@swettstein 
This is now down with a PowerShell command which is documented here: https://docs.microsoft.com/en-us/power-platform/admin/wp-license-management#what-users-are-licensed
