### ISSUE TITLE
Rename Admin Roles for environment creation

### ISSUE THREAD

**Issue by sebastianzolg** [MicrosoftDocs/power-platform#342]
The role names recently changed. Please update: 

Power Platform service admins >> **Power Platform admin**
Dynamics 365 service admins >> **Dynamics 365 admin**

![image](https://user-images.githubusercontent.com/12109119/89273223-8c19b480-d63f-11ea-8708-7297e884faf3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173c05a8-b0af-5139-80c1-ec153a88c922
* Version Independent ID: 7427a8f1-b48f-0180-f1c7-940700192eb6
* Content: [Control environment creation and management - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/control-environment-creation)
* Content Source: [power-platform/admin/control-environment-creation.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/control-environment-creation.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by sebastianzolg** [comment]
Here's a suggestion #343

**Comment by jimholtz** [comment]
@sebastianzolg 
Thanks for bringing this to our attention. Multiple topics have been updated with the correct role names.
