### ISSUE TITLE
Infinite Email Loop?

### ISSUE THREAD

**Issue by jameswh3** [MicrosoftDocs/power-platform#344]
In the rule configuration, the notification sent to the end user about the email being blocked could create an infinite loop if the user in question is forwarding all emails externally (common for data exfiltration scenarios) or even if the user is filtering based on text in the subject.

This could be avoided by not sending a notification to the end user and instead sending a notification to admins who could reach out to the user separately for remediation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d16c2c-fbad-7ed0-ea2d-fd8faee42054
* Version Independent ID: 44d87949-1656-7360-e1e5-c8f45e029604
* Content: [Email exfiltration controls for Office 365 connectors - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/block-forwarded-email-from-power-automate)
* Content Source: [power-platform/admin/block-forwarded-email-from-power-automate.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/block-forwarded-email-from-power-automate.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jameswh3 
Taking this to internal thread.

**Comment by prashant1380** [comment]
Any updates on this? Is this handled?
