### ISSUE TITLE
Wrong word in step description

### ISSUE THREAD

**Issue by jorgemorenog** [MicrosoftDocs/power-platform#347]
In "Allocate or change capacity in an environment", the step "2. Select Analytics > Capacity in the left-side navigation pane", I think it means "Resources" instead of "Capacity".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0cbf8c-5c12-5aa2-3786-392d0f498303
* Version Independent ID: 2774f5ca-1c86-4fe6-c296-6f7f45aa6702
* Content: [Capacity add-ons for Power Apps and Power Automate - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on)
* Content Source: [power-platform/admin/capacity-add-on.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-add-on.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jorgemorenog 
Thanks for bringing this to our attention. We'll get this updated today.
