### ISSUE TITLE
Step 1 URL should be updated

### ISSUE THREAD

**Issue by jorgemorenog** [MicrosoftDocs/power-platform#348]
It seems that the current Step 1 URL should be appropriately updated with the Power Platform administration panel.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb92ca9-41dc-d1d0-90df-09e7159e47d7
* Version Independent ID: 6c2a02de-a8db-cafa-6d81-861a027c07f2
* Content: [Delete environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/delete-environment)
* Content Source: [power-platform/admin/delete-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/delete-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jorgemorenog 
Thanks for bringing this to our attention. This will be corrected today.
