### ISSUE TITLE
new popup message on merge

### ISSUE THREAD

**Issue by RaviKKashyap** [MicrosoftDocs/power-platform#349]
Hi,

There is currently a note "_Other transactions, such as merge, share/unshare, rollup view, and re-parent are are currently under review for asynchronous processing._" however, it has been noticed that upon merge a popup appears to confirm that the records will be merged in the background.

Is this note still applicable? Does this need to be enabled manually or we need to request for this? 

Thanks,
Ravi Kashyap

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba582be6-c286-8c1b-b836-e0e993a5efed
* Version Independent ID: e73113c5-1a80-67c3-1429-3f226c074924
* Content: [Asynchronous processing of cascading transactions - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/async-cascading)
* Content Source: [power-platform/admin/async-cascading.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/async-cascading.md)
* Service: **power-platform**
* GitHub Login: @NHelgren
* Microsoft Alias: **matp**

**Comment by NHelgren** [comment]
Hi RaviKKashyap, We have just recently started rolling out out asynchronous cascade for merge operations. I will updating this document.

**Comment by NHelgren** [comment]
@RaviKKashyap The document has been updated and a new blog post has been published as well: https://powerapps.microsoft.com/en-us/blog/improvements-to-cascading-merge-transactions/
