### ISSUE TITLE
New-AdminPowerApp Support

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/power-platform#35]
Any planned support for a `New-AdminPowerApp`? Would be happy to test if there's a beta in the CLI for this functionality.

Would like to see this for both Canvas and Model-drive apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#operation-examples)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@gregdegruy 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
