### ISSUE TITLE
Relay bot for PVA not working on Microsoft Teams

### ISSUE THREAD

**Issue by MariaMendietaSpur** [MicrosoftDocs/power-platform#350]
I'm working on with the [Relay Bot sample](https://github.com/microsoft/PowerVirtualAgentsSamples/tree/master/RelayBotSample) to expand the capabilities of my Power Virtual Agent and I'm running into issues when using it on Microsoft teams. My relay bot works fine when tested on the Azure Web Chat and when I tested it locally. However, when I install the relay bot on Teams, the bot seems to work (I added a welcome message) but it's not connecting to my power virtual agent.  I'm following some of the steps mentioned in https://docs.microsoft.com/en-us/power-virtual-agents/publication-connect-bot-to-azure-bot-service-channels

Any ideas how to make the relay bot work on Microsoft teams? Is there something I need to add to the Teams Manifest ( e.g. valid domain, permission, connector) to get the Power Virtual Agent work? 

My ultimate goal is to create a proactive messaging bot using PVA, is there another path to do that?

**Comment by iaanw** [comment]
Thanks for your questions! The best place for product troubleshooting - is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
