### ISSUE TITLE
Revisit the note

### ISSUE THREAD

**Issue by marcomangiante** [MicrosoftDocs/power-platform#351]
In "Microsoft Power Platform requests allocations based on licenses" the note 3 point to a document appendix that is not correct: at the day of writing, 08/11/2020 the correct appendix is C.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@marcomangiante 
Thanks for bringing this to our attention. We'll get this corrected today.
