### ISSUE TITLE
Wrong navigation detail in article

### ISSUE THREAD

**Issue by deepprashant** [MicrosoftDocs/power-platform#352]
[instead of "Announcement" you should use "Auto numbering"]
![image](https://user-images.githubusercontent.com/12823859/90020965-aac41f00-dcc1-11ea-9f7f-28e06c9c16bb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cc1a076-0bb1-6e89-f726-c2c3ac51f98d
* Version Independent ID: e5aece18-c664-cd6a-2c94-c74d6deb644c
* Content: [Change auto-numbering prefixes for contracts, cases, articles, quotes, orders, invoices, campaigns, categories, and knowledge articles - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/change-auto-number-prefix-contract-case-article-quote-order-invoice-campaign-category-knowledge-articles#feedback)
* Content Source: [power-platform/admin/change-auto-number-prefix-contract-case-article-quote-order-invoice-campaign-category-knowledge-articles.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/change-auto-number-prefix-contract-case-article-quote-order-invoice-campaign-category-knowledge-articles.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@deepprashant 
Thanks for bringing this to our attention. We'll get this corrected today.
