### ISSUE TITLE
Incorrect menu listing for office 365

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/power-platform#353]
This says: To see whether you have any of these licenses, sign in to the Microsoft 365 admin center, and then go to Billing > Products & Services.

However there is no Product and Service menu item in the Billings category.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f8c1ca-4250-85c7-2b8e-caab633d8d9d
* Version Independent ID: 70065f90-617e-d812-e04e-7594708b0cce
* Content: [New Common Data Service storage capacity - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/capacity-storage)
* Content Source: [power-platform/admin/capacity-storage.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-storage.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@JerryCRMI 
Thanks for bringing this to our attention. We'll get this corrected today.
