### ISSUE TITLE
Page needs updating

### ISSUE THREAD

**Issue by pawant-ms** [MicrosoftDocs/power-platform#355]
I tried to follow steps here on 8/13 and got lost mid-way. Suggest updating guidance based on new flow from Facebook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b159b2e-9bec-64bf-6597-7d0dba599f34
* Version Independent ID: 1546d70b-b24c-f1d6-1448-1c5d0768909c
* Content: [Add a chatbot to Facebook - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/publication-add-bot-to-facebook)
* Content Source: [power-virtual-agents/publication-add-bot-to-facebook.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/publication-add-bot-to-facebook.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Will revisit this and update accordingly - will work internally with PM
