### ISSUE TITLE
Wild card urls

### ISSUE THREAD

**Issue by avi-dev-git** [MicrosoftDocs/power-platform#356]
Customers has reservation whitelisting request especially for wildcard URLs below. Can we provide strong technical justification for these wildcards. Otherwise, is it possible to provide the extended list of URLs without wildcards (e.g. https://*.windows.net  = 50 URLS)?

• https://*.windows.net
• https://*.microsoftonline.com
• http://*.passport.net
• https://*.azureedge.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bad26a7-056d-6855-1bca-39be98071659
* Version Independent ID: b438f290-83cd-6a24-6549-d12d45ac0ed8
* Content: [Required URLs for Asia/Pacific area-based organizations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/internet-url-asia-pacific)
* Content Source: [power-platform/admin/internet-url-asia-pacific.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/internet-url-asia-pacific.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@avi-dev-git 
Please contact technical support for this issue. https://powerapps.microsoft.com/support/
