### ISSUE TITLE
Unpack solution overwrites the folder, deleting git repository files

### ISSUE THREAD

**Issue by kornakar** [MicrosoftDocs/power-platform#357]
You might want to add some documentation on what the Unpack solution task actually does.

By default it "overrides" the folder. So if you unpack to `$(Build.SourcesDirectory)`, then it "takes control" over that folder. And when "Allow overwrite on existing files", the task actually performs a cleanup and deletes files from ./.git/ folder.

If you try to use git (to for example push the unpacked files back to repository), then you'll get an error `fatal: not a git repository (or any of the parent directories): .git`

A snippet from Unpack solution task log:
```
Unmanaged Extract complete.


There are 27 unnecessary files
Deleting files...
Clobbering: d:\a\1\s\.git\objects\00\a551c619efcf7954152885f52c71094127b703
Clobbering: d:\a\1\s\.git\objects\0c\a446aab9d09eac8625b53e3df8da661976c458
Clobbering: d:\a\1\s\.git\objects\98\04b758e84cac41a6acc4d011f57310a1f63102
5 warnings encountered
0
Finishing: Power Platform Unpack Solution
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tool-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by jimholtz** [comment]
@kornakar 
Please provide the topic where this content occurred.

**Comment by kornakar** [comment]
> 
> 
> @kornakar
> Please provide the topic where this content occurred.

Added the document link to the original message.
