### ISSUE TITLE
Improper formatting and broken links in PowerApps administration Powershell module docs

### ISSUE THREAD

**Issue by rohannevrikar** [MicrosoftDocs/power-platform#358]
In PowerApps administration Powershell module, in some examples of [Add-PowerAppsAccount ](https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/add-powerappsaccount?view=pa-ps-latest) cmdlet, formatting is not done properly as shown in the image here: 

![image](https://user-images.githubusercontent.com/26645175/90371077-0d376980-e08c-11ea-8713-32c5f3647966.png)

While trying to fix this issue, I came to know that the "Edit" button on the top right position of every doc of this module is a broken link. It redirects to a GitHub path which is not present. It should redirect to the page where the document can be edited and the fix can be committed in the repo. 

![image](https://user-images.githubusercontent.com/26645175/90371571-c7c76c00-e08c-11ea-8ef4-adcf30579a82.png)
![image](https://user-images.githubusercontent.com/26645175/90371597-cf871080-e08c-11ea-876b-4103102f4d10.png)

**Comment by jimholtz** [comment]
@rohannevrikar 
Thanks for the notification. We've revised the formatting. For the 404, please contact Support: 
https://powerapps.microsoft.com/support/
