### ISSUE TITLE
Power Virtual Agents - Permanently remove the authentication configuration

### ISSUE THREAD

**Issue by sebastianzolg** [MicrosoftDocs/power-platform#359]
According to the documentation, the authentication configuration for Power VA needs to be 
[deleted from Bot Services](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-end-user-authentication#remove-the-authentication-configuration) in Azure too. 

This seems a bit strange to me and I can't see any connection there. 

**Is this information correct?**
Shouldn't this section describe the deletion of the App Registration? I can't think of any way how Power VA authentication is related to anything in a specific Azure Subscription. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f11f0ed-eec4-dfbc-4498-87690a569091
* Version Independent ID: 7c3ba7b6-5874-2cbb-0aef-aef24489d0b0
* Content: [Configure user authentication - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-end-user-authentication)
* Content Source: [power-virtual-agents/configuration-end-user-authentication.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/configuration-end-user-authentication.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
OK after discussing with the product team, we've decided to remove this section from the docs as it's misleading and not necessarily appropriate. For more information or to discuss this further with our product team, please submit a question at the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums).

Thanks for your feedback and sorry for the delay on this one.
