### ISSUE TITLE
Dynamics?

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/power-platform#36]
Where is the connection to dynamics?  Is this type of word document automation only applicable/usable from dynamics?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae661c5-51cd-2050-3dcf-36a48966130d
* Version Independent ID: 20ef03e9-52a1-8c24-1868-9bbbd5b95cc9
* Content: [Use Word templates to create standardized documents - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/using-word-templates-dynamics-365#feedback)
* Content Source: [power-platform/admin/using-word-templates-dynamics-365.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/using-word-templates-dynamics-365.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@chris7777au 
This is a feature within model-driven apps in Dynamics 365.
