### ISSUE TITLE
DLP Editor - Power Automate

### ISSUE THREAD

**Issue by swoodhousecoop** [MicrosoftDocs/power-platform#360]
I see that the DLP editor allows you to see what apps would be impacted based on the DLP rules that are selected on the app. Is there a simple way to modify this so that it can show affected Power Automate flows? The same layout exactly, just showing affected Power Automate flows instead of Power Apps.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-gb/power-platform/guidance/coe/core-components#apps)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Unfortunately not. This app is using the [Power Apps for Admins](https://docs.microsoft.com/en-us/connectors/powerappsforadmins/) connector, the Get Apps as Admin connector returns the connector information per app - so one call per environment returns all the information needed for the DLP Editor.
The List Flows as Admin of the [Power Automate Management](https://docs.microsoft.com/en-us/connectors/flowmanagement/) connector does not return the connectors a flow is using, so we don't have all the information needed for the DLP Editor. Instead, we would have to retrieve each flow information individually (Get Flow as Admin) to get this information which is not feasible from a performance point of view.
