### ISSUE TITLE
volume is to quiet on video

### ISSUE THREAD

**Issue by joellindstrom** [MicrosoftDocs/power-platform#361]
I can barely hear the audio on this video.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
This video has been removed as it's been out of date. We're just working on re-recording it and will address the volume issues! Thank you for letting us know
