### ISSUE TITLE
Meaning of Double Asterisk in FAQ Pages

### ISSUE THREAD

**Issue by hitendra72** [MicrosoftDocs/power-platform#363]
Many of the questions on the[ FAQ page](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq) have a double asterisk (**), but there is no explanation for what these double asterisks mean

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq?source=docs)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@hitendra72 
Thanks for bringing this to our attention. This is a formatting error and will be corrected soon.
