### ISSUE TITLE
Restrict Provisioning Developer Environment #1693

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/power-platform#364]
[Enter feedback here]

Kindly review the steps to Restrict Provisioning Developer Environment #1693

https://github.com/MicrosoftDocs/powerapps-docs/issues/1693

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4deb237b-2aaa-88d5-ae53-dc8dff4c1410
* Version Independent ID: a440d8b3-aa78-7546-8785-5b8cd4c78bf7
* Content: [Environments overview - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/environments-overview)
* Content Source: [power-platform/admin/environments-overview.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/environments-overview.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@DavidPaf 
Handling via internal mail.
