### ISSUE TITLE
Broken link to Getting Started

### ISSUE THREAD

**Issue by Zerg00s** [MicrosoftDocs/power-platform#365]
The "Getting started" link in the very first paragprah is broken: gives us a 404 when we click it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f108b474-2f9c-4b76-3d0f-e85bf77985ed
* Version Independent ID: 9627f1f9-82c5-49c8-5506-d3e09b977673
* Content: [Work with solutions using PowerShell - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/powershell-api)
* Content Source: [power-platform/alm/powershell-api.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/powershell-api.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by JimDaly** [comment]
@jimholtz 
The link is just malformed.
It  goes to 
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/checker/webapi/overview.md#getting-started

It needs to go to:
https://docs.microsoft.com/en-us/power-platform/alm/checker-api/overview#getting-started

Remove the .md from the url.

**Comment by Mattp123** [comment]
@Zerg00s - Thank you for your feedback. The link has been fixed and will be published live in a few hours.

Closing issue.
