### ISSUE TITLE
Page makes mention to Forms Pro but it is now renamed to Customer Voice

### ISSUE THREAD

**Issue by carterbarry** [MicrosoftDocs/power-platform#367]
Page makes mention to Forms Pro but it is now renamed to Customer Voice. Forms Pro has been rebranded. please update
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and model-driven apps in Dynamics 365 - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming?source=docs#process-dialogs-are-deprecated)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/important-changes-coming.md)
* Service: **dynamics-365-crossapp**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by jimholtz** [comment]
@carterbarry 
Thanks for the suggestion. Content updated and published to live.
