### ISSUE TITLE
Excange Sync "When would I want to use this check box?" refers to "Model Driven App" where it means "Org" which is confusing/misleading

### ISSUE THREAD

**Issue by krouskop** [MicrosoftDocs/power-platform#368]
The wording:

> A user can be a **member of more than one model-driven apps** in Dynamics 365, such as Dynamics 365 Sales and Customer Service, organization, but an Exchange mailbox (email address) can only synchronize emails, appointments, contacts, and tasks with one organization

is confusing.

The issue is belonging to multiple **Organizations**, not having access to multiple Model Driven Apps in one Org.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b53089f-cc3d-2149-05c4-49820074d029
* Version Independent ID: 2f1723be-4cc3-fb4d-dd09-c7800c16f64b
* Content: [When would I want to use this check box? - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/when-would-want-use-check-box)
* Content Source: [power-platform/admin/when-would-want-use-check-box.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/when-would-want-use-check-box.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@krouskop 
Thanks for bringing this to our attention. You're quite correct. Looks like a terminology search and replace error. We'll get this corrected today.
