### ISSUE TITLE
Default Environment Backup and Restore

### ISSUE THREAD

**Issue by donalmc** [MicrosoftDocs/power-platform#369]
How do I backup and restore the Default Environment?
We are building a Project for the Web solution in here and had a situation that would have been resolved by restoring yesterday's backup; however, there are no backups for the Default Environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c58fb1-e6a2-5210-3774-4ea4bbff4572
* Version Independent ID: 57c1780c-b097-af8c-82fa-47e38a63995c
* Content: [Back up and restore environments - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments)
* Content Source: [power-platform/admin/backup-restore-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/backup-restore-environments.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@donalmc 
Thanks for the feedback. We've updated the following topics:
https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments#manual-backups
https://docs.microsoft.com/en-us/power-platform/admin/environments-overview#the-default-environment
