### ISSUE TITLE
Power App Plans link is incorrect

### ISSUE THREAD

**Issue by james-reinhardt** [MicrosoftDocs/power-platform#37]
In the topmost "Notes" section, the "Power App Plans" link does not open a new page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f8c1ca-4250-85c7-2b8e-caab633d8d9d
* Version Independent ID: 70065f90-617e-d812-e04e-7594708b0cce
* Content: [Preview: Common Data Service storage capacity - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/capacity-storage#feedback)
* Content Source: [power-platform/admin/capacity-storage.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-storage.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@james-reinhardt 
The link opens a .pdf.

**Comment by james-reinhardt** [comment]
Thanks for the quick reply. Yep, looks like I have 15 of them in my downloads folder.
