### ISSUE TITLE
Built-In Connectors

### ISSUE THREAD

**Issue by dhawal16** [MicrosoftDocs/power-platform#372]
None of the PS Command is giving list of Built-In Connectors
Eg. HTTP, HTTP Webhook etc.

Moreover there is no documentation as well for Built-In connectors

Cheers,
Dhawal Mehta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@dhawal16 
Please review the cmdlets listed on this page:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/?view=pa-ps-latest

If you're not finding what you need for connectors, please add a suggestion:
https://ideas.powerapps.com.
