### ISSUE TITLE
Can't submit PR to fix translation

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/power-platform#373]
The Japanese translation says (April and May) instead of (April and October) regarding the major update timing.
I tried to submit a PR but it errors out and I can't get any useful info from the error message. Something about the repo seems to be misconfigured.
https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/pull/2

Can you either fix the repo or just have the Japanese localization team fix the error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13124815-8bd7-6c5d-c123-4b3c049bbf90
* Version Independent ID: 92e1fc93-fd81-9d05-f71d-7dd189ca19a0
* Content: [Policies and Communications for service incidents - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/policies-communications)
* Content Source: [power-platform/admin/policies-communications.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/policies-communications.md)
* Service: **power-platform**
* GitHub Login: @astockli
* Microsoft Alias: **astockli**

**Comment by jimholtz** [comment]
@dcbrown16 
Thanks for the notice. Taking to internal mail.
