### ISSUE TITLE
Client credential flow

### ISSUE THREAD

**Issue by malaker** [MicrosoftDocs/power-platform#374]
Hi all

Microsoft - good guys that you exposes web api for powerapp checker. For those people who want to use this web api and they want to use client credential flow I have already implemented small library https://github.com/malaker/PowerAppsTools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f7950ef-3132-ab0d-57ff-abb4cd44ac38
* Version Independent ID: c5ff8a83-a8bc-fd3a-288a-b6c1d4cf809e
* Content: [Use the Power Apps checker web API - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/checker-api/overview)
* Content Source: [power-platform/alm/checker-api/overview.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/checker-api/overview.md)
* Service: **powerapps**
* GitHub Login: @mhuguet
* Microsoft Alias: **mhuguet**

**Comment by mhuguet** [comment]
@malaker thank you for your contribution to the community. Does you API have a wait time between status checks built in? Please do not constantly call that API in a loop without some wait time. In the future we will be adding throttling, which will likely break your API.

**Comment by malaker** [comment]
@mhuguet hi thanks for Feedback in the example loop indeed I should put some delay it may lead to problems related to throttling as you mentioned. I will update read me in my project. Library implements c# Client for powerapp Checker . Users of this Library should keep in mind to have between calls delay.

**Comment by Mattp123** [comment]
Closing issue.
