### ISSUE TITLE
foo@bar.com

### ISSUE THREAD

**Issue by mauledbyjesus** [MicrosoftDocs/power-platform#376]
I think it's time we retire the foo@bar.com example username. While I've always known its origins (FUBAR), how problematic it might be just occurred to me somehow. Ha.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@mauledbyjesus 
Thanks for the suggestion. Updated.
