### ISSUE TITLE
Describe how there are dependencies in access rights

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/power-platform#377]
There should be some information about dependencies in access rights as described in this OLD doc:

[Docs / Dynamics 365 / Customer Engagement (on-premises) / version 9 / Developer Guide / Use record-based security to control access to records / Dependencies between access rights](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/security-dev/use-record-based-security-control-access-records#dependencies-between-access-rights)

You must have READ access to do just about anything. Simply granting WRITE is not enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c40f87c-1a3a-399d-d25f-ae348dc5e248
* Version Independent ID: 4784510f-a482-f73a-85e2-f2e6d74168c3
* Content: [Create or edit a security role - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-edit-security-role)
* Content Source: [power-platform/admin/create-edit-security-role.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-edit-security-role.md)
* Service: **power-platform**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by jimholtz** [comment]
Security content rewrite is ongoing and will include this.
