### ISSUE TITLE
App for applying CA on Dynamics 365

### ISSUE THREAD

**Issue by jagustin19** [MicrosoftDocs/power-platform#378]
Is the Common Data Service app still the right app? This does not seem to be an option in the list of apps to assign CA policies to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 003fe16c-7cf4-14c6-09f2-7b18b047cbf7
* Version Independent ID: 3c7059c0-3aff-2729-42a7-88c4e7de0157
* Content: [Block access by location with Azure AD Conditional Access - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/restrict-access-online-trusted-ip-rules)
* Content Source: [power-platform/admin/restrict-access-online-trusted-ip-rules.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/restrict-access-online-trusted-ip-rules.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jagustin19 
Sorry for the delayed response. Please reopen if this is still a question.
