### ISSUE TITLE
Wrong information and broken hyperlink

### ISSUE THREAD

**Issue by readyxrm** [MicrosoftDocs/power-platform#38]
The statement "If you need to back up your templates, or use them in a different implementation of model-driven apps in Dynamics 365, such as Dynamics 365 Sales and Customer Service, you can export them as part of exporting customizations." is incorrect as Campaign Templates are metadata, not solution assets.  They could be transported to different environments via the Configuration Data Migration Tool.

Also, the hyperlink  "More information: Export your customizations as a solution" is broken and leads to a 404 page.

Cheers
Nick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b83abde-90c5-0fca-8b67-780213daecff
* Version Independent ID: c7df047d-0696-cdc5-8b25-06bf4b15adcf
* Content: [Create or edit a campaign template using in-app marketing (Sales) - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/create-edit-campaign-template-using-app-marketing-sales#feedback)
* Content Source: [power-platform/admin/create-edit-campaign-template-using-app-marketing-sales.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-edit-campaign-template-using-app-marketing-sales.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@readyxrm 
Thanks for the correction. We've updated the content.
