### ISSUE TITLE
Missing info regarding remove or delete members of a security profile

### ISSUE THREAD

**Issue by JMountainFrame** [MicrosoftDocs/power-platform#381]
I believe information on how to remove user or teams from a field security profile needs to be added. Currently it seems like a bug because a system admin don't have access to a remove / delete button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456f59f-f459-0ea0-a5f4-2b618596a6e8
* Version Independent ID: 50779a95-a93b-df0b-a00d-cb217c2b1a7f
* Content: [Add teams or users to a field security profile - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/add-teams-users-field-security-profile)
* Content Source: [power-platform/admin/add-teams-users-field-security-profile.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/add-teams-users-field-security-profile.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@JMountainFrame 
Sorry for the delayed response. Security content is frequently being rewritten. Please reopen if this is still an issue.
