### ISSUE TITLE
invalid code

### ISSUE THREAD

**Issue by jwayne554** [MicrosoftDocs/power-platform#384]
When inserting the code from steps 4-5 into the custom canvas, the webchat stops from loading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d60dd9-05e9-9c78-7d7b-53b26a92af06
* Version Independent ID: 282e50ba-61cf-6574-94ad-4dcf82b71a72
* Content: [Configure single sign-on - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configure-sso)
* Content Source: [power-virtual-agents/configure-sso.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/configure-sso.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for your questions! The best place for product troubleshooting - is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
