### ISSUE TITLE
Please clarify - "not honored any more"

### ISSUE THREAD

**Issue by MSIH** [MicrosoftDocs/power-platform#385]
I do not understand what this means. Please add more words and provide specifics.

>  Note
> 
> On creating the database, any security group assigned to Environment Admin or Environment Maker role will not be honored any more. Currently, assigning permissions in database, do not support Azure AD security group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3f6c7c-bb0e-ad08-b081-4d19223ef823
* Version Independent ID: 31baba85-90bf-511b-7a0b-c77861d72f64
* Content: [Add a Common Data Service database - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-database)
* Content Source: [power-platform/admin/create-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@MSIH 
Sorry for the delayed response. Content is frequently being rewritten. Please reopen if this is still an issue.
