### ISSUE TITLE
Updates to page to manage customer questions

### ISSUE THREAD

**Issue by dynamic-pindar** [MicrosoftDocs/power-platform#386]
The last question on the page specifically calls out the creation of PRODUCTION environments but it should apply to sandbox environments as well.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-environment)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@dynamic-pindar 
Sorry for the delayed response. This is likely no longer an issue. Please reopen if that is not the case.
