### ISSUE TITLE
Suggested Transport Rule solution leads to infinite mail-routing loop

### ISSUE THREAD

**Issue by stukey** [MicrosoftDocs/power-platform#387]
The suggested solution to block Power Automated based forwarding using Exchange Transport Rules causes a infinite mail-routing loop. The “reject the message with the explanation” action generates an email to the sender (forwarder) with the non-delivery report. This NDR email is then automatically forwarded by the Power Automation flow and blocked by the transport rule on so on... Therefore the Microsoft recommended solution is not fit for purpose and we still need better admin controls to block Power Automate email forwarding. The workaround is to change the Transport Rule to just drop the message using the “delete the message without notifying the recipient or sender” but this isn’t ideal because then the sender isn’t informed as to why their flow isn’t working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d16c2c-fbad-7ed0-ea2d-fd8faee42054
* Version Independent ID: 44d87949-1656-7360-e1e5-c8f45e029604
* Content: [Email exfiltration controls for connectors - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/block-forwarded-email-from-power-automate)
* Content Source: [power-platform/admin/block-forwarded-email-from-power-automate.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/block-forwarded-email-from-power-automate.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@stukey 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
Or create a support request:
https://powerapps.microsoft.com/support/
