### ISSUE TITLE
Limits to using Power Platform Build Tools with Canvas Apps - Known issue or am I doing it wrong?

### ISSUE THREAD

**Issue by joegithub** [MicrosoftDocs/power-platform#388]
Hello, and first of all thank you for providing the Power Platform devops tool set and continuing to add more features.

I am developing a Canvas app and have so far done everything within the context of a solution in our development environment. I've gone through the process to create devops pipelines that run the tasks to export the solution and check it into source control, then another to export a managed solution from Dev and import it into our Test environment.

This solution contains the canvas app, some environment variables, and many Flows. I make changes in Dev, update the solution version, then export a managed copy to import into Test.

The issue I've run into is that when running the pipeline to import the managed solution the result is that updates from Dev are applied to the Test solution, but within the Canvas app all flows are "broken", i.e. they appear in the Data pane as "Not Connected" and require manually removing and then adding back, then saving the app and publishing to finally get the app in Test working.
This happens each time the solution is imported and it is a huge hassle, made even more onerous by the fact that adding a flow to a Canvas app auto-inserts the flow's run command into the current screen's function bar, completely erasing the existing code that was there. So it's remove all flows, then Add flow, click Undo button, Add flow, click undo button...over and over.

Going the alternate route of exporting the Canvas app as a package will not work for me as the process doesn't include the environment variables and additional flows that are in the solution to get called as child flows by the flows that are referenced by the Canvas app.

I would appreciate it if you could confirm that what I'm experiencing is a known issue or limitation of Canvas app ALM, and if this  will be addressed in a future update to the Power Platform. I'm not sure it's an issue specific to the build tools.
Alternatively, if what I've described is not the correct way to handle ALM for Canvas apps then I would appreciate guidance on that because I have found ALM documentation for Canvas apps lacking in details of how to support apps that must also use flows and environment variables across multiple environments.

Thank you

**Comment by jimholtz** [comment]
@joegithub 
Thanks for the thorough write up. Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
