### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by phyle** [MicrosoftDocs/power-platform#389]
I was working with someone who is color-blind and I asked to click one of the links that is present on the word "here" in this document (multiple places). That person was using the dark theme and the links are light blue compared to white text.  It wasn't visible to that person where the links are.  I would suggest to review the stylesheet to have more distinction between links and texts and possibly use the actual title in quotes of the target link page instead of just the very small word "here" (where's here?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Microsoft Power Platform Build Tools for Azure DevOps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tools.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by Mattp123** [comment]
@phyle - Thank you for your feedback. I've changed the link text to include the article section title of the link destination. I've also passed on your feedback concerning the Microsoft Docs stylesheet to our internal Docs platform contacts for consideration.

Closing issue.
