### ISSUE TITLE
Missing Documentation on how to Delete a Bot?

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/power-platform#39]
After reviewing all the documentation here, I'm not seeing instructions on how to Delete a bot. Is that documented, available, or was I blind and missed it? Thanks! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02cd3021-0b6a-6819-5ba2-dd8c15a8da50
* Version Independent ID: cda6b8ff-46a4-0bc7-c4f7-9afe8364c1d1
* Content: [Create conversational bots in Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/authoring-first-bot)
* Content Source: [power-virtual-agents/authoring-first-bot.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/authoring-first-bot.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
It's in the GDPR section here: https://docs.microsoft.com/en-us/power-virtual-agents/gdpr-delete#power-virtual-agents-bot-content

But this is a great bit of feedback, we'll add it to the topic here.
