### ISSUE TITLE
New-DLPPolicy not working

### ISSUE THREAD

**Issue by dhawal16** [MicrosoftDocs/power-platform#390]
What is the expected value for EnvironmentType in New-DLPPolicy command?
It is a mandatory property and examples doesn't show anything, please let me know.

Thanks,
Dhawal Mehta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#data-loss-prevention-dlp-policy-commands)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@dhawal16 

We have 4 predefined EnvironmentType.

    public enum DLPPolicyEnvironmentType
    {
        /// <summary>
        ///  Data Loss Prevention Policy Environment Type is not specified
        /// </summary>
        NotSpecified,

        /// <summary>
        ///  Data Loss Prevention Policy Environment Type is set to apply to all environments
        /// </summary>
        AllEnvironments,

        /// <summary>
        ///  Data Loss Prevention Policy Environment Type is set to apply to only specific environments
        /// </summary>
        OnlyEnvironments,

        /// <summary>
        ///  Data Loss Prevention Policy Environment Type is set to exclude specific environments
        /// </summary>
        ExceptEnvironments,

        /// <summary>
        ///  Data Loss Prevention Policy Environment Type is set to a single specific environment
        /// </summary>
        SingleEnvironment
    }
