### ISSUE TITLE
[Authentication] UI has changed and Generic OAuth 2 may not use same scope profile and openid

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/power-platform#393]
UI has changed and we don't have authentication any more:
![image](https://user-images.githubusercontent.com/2876650/93584887-8baf6000-f9d8-11ea-97ea-835df97ef465.png)

Also `Generic OAuth 2` may not use same scope `profile` and `openid`, so we should not set them by default.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f11f0ed-eec4-dfbc-4498-87690a569091
* Version Independent ID: 7c3ba7b6-5874-2cbb-0aef-aef24489d0b0
* Content: [Configure user authentication - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-end-user-authentication)
* Content Source: [power-virtual-agents/configuration-end-user-authentication.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/configuration-end-user-authentication.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for your feedback! The best place for product requests or troubleshooting is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
