### ISSUE TITLE
Roles required

### ISSUE THREAD

**Issue by irideostriches** [MicrosoftDocs/power-platform#396]
Would be helpful to list the roles required to delete an environment here, as a reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb92ca9-41dc-d1d0-90df-09e7159e47d7
* Version Independent ID: 6c2a02de-a8db-cafa-6d81-861a027c07f2
* Content: [Delete environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/delete-environment)
* Content Source: [power-platform/admin/delete-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/delete-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@irideostriches 
Sorry for the delayed response and thanks for the suggestion. We'll be rewriting this content and adding requirements information in a future revision.

**Comment by irideostriches** [comment]
Hey Jim. Thanks for the update. As a professional who relies on your work I want to thank you for your efforts.
