### ISSUE TITLE
Please clarify what "types" mean

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/power-platform#399]
In this sentence "Project Oakdale environments won't be allowed to change types", does "types" mean Production to Sandbox and vice-versa?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66be7882-5440-7cff-142f-4436a2d648ca
* Version Independent ID: b1876c76-62e5-2e0f-c823-09be35cfd7a5
* Content: [About the Project Oakdale environment (Preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#promotion-process)
* Content Source: [power-platform/admin/about-teams-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/about-teams-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@rajyraman 
Yes. Type refers to environment type.
