### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by Illeris** [MicrosoftDocs/power-platform#4]
page : https://docs.microsoft.com/en-us/power-platform/admin/manage-configuration-data
Link "Download tools from NuGet" =&gt; dead / 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaafdc52-4a26-ecd5-83f8-25373eb053f5
* Version Independent ID: ada1a415-a53f-21fb-948a-79245c3c68f4
* Content: [Move configuration data across organizations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/manage-configuration-data)
* Content Source: [power-platform/admin/manage-configuration-data.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-configuration-data.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Illeris 
The link has been fixed. Thanks for bringing this to our attention.
