### ISSUE TITLE
Links to admin centre

### ISSUE THREAD

**Issue by sionide0278** [MicrosoftDocs/power-platform#40]
All the links to "Microsoft 365 admin center" currently 404 - looks like https:// needs adding to make them not relative to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eebb06d-174a-4f38-6e9e-c6176e97b3ba
* Version Independent ID: b3feb7ce-6756-29af-f18b-2b9fd4e29f3e
* Content: [Purchase Power Apps for your organization - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/signup-for-powerapps-admin#feedback)
* Content Source: [power-platform/admin/signup-for-powerapps-admin.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/signup-for-powerapps-admin.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@sionide0278 
Thanks for bringing this to our attention. Links updated.
