### ISSUE TITLE
The Azure section contains information related to a deprecated portal

### ISSUE THREAD

**Issue by boachim** [MicrosoftDocs/power-platform#401]
The section "Configure self-service password reset and other settings in Azure" contains steps that are no longer available, referencing manage.azure.com portal. This was deprecated more than 2 years ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998c5ac7-53b7-548a-4f73-7f8d586abffb
* Version Independent ID: 6ea1d35d-3459-34f9-aa01-e113dc7cb0c6
* Content: [Use the Microsoft 365 admin center to manage your subscription - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/use-office-365-admin-center-manage-subscription)
* Content Source: [power-platform/admin/use-office-365-admin-center-manage-subscription.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/use-office-365-admin-center-manage-subscription.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@boachim 
Handling via email.
