### ISSUE TITLE
Delegated Admin can not access make.powerapps.com

### ISSUE THREAD

**Issue by robertoilidio** [MicrosoftDocs/power-platform#402]
There are few Partner development tasks, for instance create modern Flows, which requires access to make.powerapps.com.

But Partners gets follow error:
![image](https://user-images.githubusercontent.com/10701939/94407520-70c4b480-016b-11eb-93cc-dc2ee3fd8913.png)

+ Error verified in http traces:
![image](https://user-images.githubusercontent.com/10701939/94407567-833eee00-016b-11eb-9e2d-893aa740bab1.png)

"message=The environment  **GUID_1** could not be found in the tenant  **GUID_2**."
 
Where environment Id **GUID_1** is  the OrgId of end customer organization which Partner is trying to access and tenant Id **GUID_2** is the Partner's tenant.

The error message is self explanatory, It is occurring because Partner is using a Partner delegated admin to access customer's environment, as recommended by this documentation, but such feature is not ready to work in make.powerapps.com.   

Could you please add in this documentation the proper recommendation for such scenario in make.powerapps.com, as from now on, all features are migrating to this Portal.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac2d3b5f-d732-4c74-8876-03e495098c0f
* Version Independent ID: 7a5d097a-47b4-1306-a0e1-52c3e4dc9d6f
* Content: [For partners: the Delegated Administrator - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/for-partners-delegated-administrator)
* Content Source: [power-platform/admin/for-partners-delegated-administrator.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/for-partners-delegated-administrator.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@robertoilidio 
Handling via email.
