### ISSUE TITLE
Spelling of 'provisioning'

### ISSUE THREAD

**Issue by bdgit** [MicrosoftDocs/power-platform#403]
Under the section "Provisioning a new environment"
The start is "You can provisioning a new environment based on"

Consider "You can provision a new environment based on"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-environment)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@bdgit 
Thanks for bringing this to our attention. This will be corrected today.
