### ISSUE TITLE
Page Says to make sure you have .Net 4.6.2 but the Picture is 4.5.2 and there is no 4.6.2

### ISSUE THREAD

**Issue by mgernaey** [MicrosoftDocs/power-platform#404]
Title says it all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc997189-b9f4-653c-1188-5663e1a6367e
* Version Independent ID: 3113cafa-56e7-0e45-999f-fa18d50e28cb
* Content: [Deploy packages using Package Deployer and Windows PowerShell - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/deploy-packages-using-package-deployer-windows-powershell#use-package-deployer-tool-to-deploy-packages)
* Content Source: [power-platform/admin/deploy-packages-using-package-deployer-windows-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/deploy-packages-using-package-deployer-windows-powershell.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@mgernaey - This article suggests there is a .NET version 4.6.2. [.NET Framework 4.6.2]( https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-462)  

Closing issue.

**Comment by mgernaey** [comment]
Tue issue isn't whether there is or isn't, it is that it says to use 4.6.2 but the picture shows 4.5.2, we should be consistent between the images and the words

**Comment by mgernaey** [comment]
and the page literally says
Ensure that .NET Framework 4.6.2 is selected.
Select Dynamics 365 Package.
Specify the name and location of the project, and click OK.

Ensure that .NET Framework 4.6.2 is select and we have 4.5.2 selected lol :-)
