### ISSUE TITLE
assigning licenses of per app per user plan

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/power-platform#405]
needs a more description with diagrams on how we assign these type of licenses and how to maintain them, for example if I assign 50 licenses to an environment, as an admin how would I know howmany are consumed and by whom? without a way to see that info this is an half-baked admin experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4ff6033-4188-72a1-a775-867273fe1d96
* Version Independent ID: 9250b4bd-f0ce-f0a4-7ebf-fb2bd3492910
* Content: [Manage licenses in your organization - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/signup-question-and-answer)
* Content Source: [power-platform/admin/signup-question-and-answer.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/signup-question-and-answer.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@mganeshphani 
Sorry for the delayed response and thanks for the feedback. We'll consider this for addition to the content with future revisions.
