### ISSUE TITLE
Data Locations

### ISSUE THREAD

**Issue by adityansnair** [MicrosoftDocs/power-platform#406]
[Enter feedback here]
"Data will be stored in the United States if a bot author's tenant location isn't listed under the Data locations table below. For France, data will be stored in Europe."
Doesn't it should be France for Data in France instead of Europe.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e70f6fe-7a68-4e00-f773-3ace1a90ed03
* Version Independent ID: b07a0a86-410e-98d2-87bf-2ffde9354ebb
* Content: [Regional settings and data locations - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/data-location)
* Content Source: [power-virtual-agents/data-location.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/data-location.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for this feedback, I've corrected it and it should be fixed on the site later today.
