### ISSUE TITLE
Boi id not found error

### ISSUE THREAD

**Issue by santhoshstark** [MicrosoftDocs/power-platform#408]
While converting topics of power virtual agent into JSON file as mentioned in the [document](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-use-dispatcher#:~:text=Register%20and%20trigger%20your%20new%20dispatch%20endpoint%20in%20code,-The%20following%20steps&text=json%20in%20your%20dispatcher%20app,your%20Power%20Virtual%20Agents%20bot.&text=Add%20a%20new%20DynamicsBot%20class%20to%20your%20project.&text=Add%20a%20reference%20to%20the,cs%20file.) it is said to download two CSV files (annotations and msdynce_botcontents) and after running contentconverter utility it is throwing "bot id not found error" though bot id has been passed as an argument when executing the mentioned command, On opening the CSV files it is found that the CSV file contains only variable, not data, It is not clear whether to export the contents of bot created using PWA into power apps and it is so and how to do that. 

![image](https://user-images.githubusercontent.com/13182723/94656105-3b5fc880-031d-11eb-90b0-0b945f2c5f3e.png)

**Comment by iaanw** [comment]
Thanks for your questions! The best place for product troubleshooting - is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
