### ISSUE TITLE
Ability to Migrate Environment to Another Region

### ISSUE THREAD

**Issue by berellax** [MicrosoftDocs/power-platform#409]
Power Platform Admin Center should provide the ability to initiate a request to migrate a CDS environment to another region (i.e. Canada to US East). Alternatively, this should be something that MSFT Support should be able to handle on request. The current solution is to re-create the environment in the new region is not particularly practical, and this scenario does come up from time to time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4df941f8-45db-4cdd-c7d1-363febdd42dc
* Version Independent ID: cc136308-8205-6516-e05e-1c8e5a94f3c0
* Content: [Regions overview  Microsoft Docs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/regions-overview)
* Content Source: [power-platform/admin/regions-overview.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/regions-overview.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@berellax 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
