### ISSUE TITLE
Can I use model-driven apps by consuming app passes?

### ISSUE THREAD

**Issue by hajekj** [MicrosoftDocs/power-platform#41]
This section appears to be missing a lot of key information. For example, to do group-based licensing, you need to have Azure AD Premium licenses. There is no information whatsoever how-to do it without Group-based licensing. I would appreciate much more information about the entire process to get more insight into how does works and how-to do it properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0cbf8c-5c12-5aa2-3786-392d0f498303
* Version Independent ID: 2774f5ca-1c86-4fe6-c296-6f7f45aa6702
* Content: [Capacity add-ons for Power Apps and Power Automate - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on#feedback)
* Content Source: [power-platform/admin/capacity-add-on.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-add-on.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@hajekj 
Does this topic provide what you're looking for:
https://docs.microsoft.com/en-us/power-platform/admin/signup-for-powerapps-admin#power-apps-per-app-plan
