### ISSUE TITLE
Additional OOB application user - enterprisesurveyappuser@contoso.com for Forms Pro

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/power-platform#410]
enterprisesurveyappuser@contoso.com looks to be the application user for Microsoft Forms Pro. Could that be added to this list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 436a3b84-3edb-8d4e-bc7e-51488b8f879a
* Version Independent ID: 634e9777-62b1-01e6-6db1-eafbfe5d8d7d
* Content: [System and application users - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/system-application-users)
* Content Source: [power-platform/admin/system-application-users.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/system-application-users.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@samadane 
Thanks for the feedback. Handling internally.
