### ISSUE TITLE
Microsoft 365 A3

### ISSUE THREAD

**Issue by philipverlinden** [MicrosoftDocs/power-platform#411]
Is the functionality also available for Microsoft 365 A3 and/or A5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f28a46-531e-d373-40ad-f9e81b55fdf3
* Version Independent ID: a47230d1-92c1-28a3-2f2c-ada21450b1f2
* Content: [Common Data Service and model-driven apps activity logging - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/enable-use-comprehensive-auditing)
* Content Source: [power-platform/admin/enable-use-comprehensive-auditing.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/enable-use-comprehensive-auditing.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by pnghub** [comment]
Activity logging first needs to be setup and enabled by user and believe it should be available at https://protection.office.com/unifiedauditlog. Have you got a chance to check that out?
