### ISSUE TITLE
All environments with or without Common Data Service will consume at least 1GB capacity?

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftDocs/power-platform#413]
All environments with or without Common Data Service will consume at least 1GB capacity.

here you don't specify which capacity is consumed: the databse , the file, or the log?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00543757-56fc-9709-49be-16970ffbb774
* Version Independent ID: c2c1da0b-c7a4-1128-f9de-1f2fae684a11
* Content: [Create and manage environments in the Power Platform admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-environment?source=docs#create-an-environment-without-a-database)
* Content Source: [power-platform/admin/create-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by Nicokirr** [comment]
Each env consumes 1 GB of Database capacity

**Comment by jimholtz** [comment]
@MTawfik86 
Sorry for the delayed response. This is likely no longer an issue. Please reopen if that is not the case.
