### ISSUE TITLE
Disable the ability to create app or bots using Project Oakdale in Teams

### ISSUE THREAD

**Issue by pezlin** [MicrosoftDocs/power-platform#414]
Disabling the Power Apps and Power Virtual Agent app in Teams is enough to stop the users from creating new apps or bots but it is **not enough to stop Project Oakdale environments to be created**. There are other apps (Inspection, Employee Ideas and Issue reporting) that will create a Project Oakdale environment if you add one of those apps to a team. So if a company wants to stop Project Oakdale environments from being created also those apps need to be blocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66be7882-5440-7cff-142f-4436a2d648ca
* Version Independent ID: b1876c76-62e5-2e0f-c823-09be35cfd7a5
* Content: [About the Project Oakdale environment (Preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment)
* Content Source: [power-platform/admin/about-teams-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/about-teams-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by fowl2** [comment]
FWIW disabling the service plan "Common Data Service for Teams" does not disable the creation of Project Oakdale environments or apps either.

**Comment by jimholtz** [comment]
@pezlin 
Thanks for the feedback. The content has been updated.
