### ISSUE TITLE
Deploy Package Task timesout after 30 mins

### ISSUE THREAD

**Issue by karankkrj2020** [MicrosoftDocs/power-platform#415]
The Power Platform Build Tools "Deploy Package" task time out after 30 mins and there is no option to configure the timeout against this task while the import solution task has an option to increase the timeout. Please look into this.

**Comment by jimholtz** [comment]
@karankkrj2020 
For this issue, please create a support request:
https://powerapps.microsoft.com/support/

**Comment by karankkrj2020** [comment]
> @karankkrj2020
> For this issue, please create a support request:
> https://powerapps.microsoft.com/support/

I have already tried raising the support ticket and the same was rejected suggesting Power Platform Build Tools is not under scope and the only supported channel is to go via PPTools@microsoft.com or github.

![image](https://user-images.githubusercontent.com/72430817/95236398-2a282780-0807-11eb-8eaa-b3fa53ef7586.png)
