### ISSUE TITLE
Support lifecycle of Exchange 2010 SP3 and support boundaries of Hybrid setup for SSS

### ISSUE THREAD

**Issue by v-iliva** [MicrosoftDocs/power-platform#417]
[Enter feedback here]
Hello,

We have to update this article since the support of Exchange 2010 SP3 will end on 13.10.2020 according to its extended support lifecycle mentioned here:

https://docs.microsoft.com/en-us/lifecycle/products/exchange-server-2010

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5033cf14-8912-471d-66b7-61ca7e29d752
* Version Independent ID: a7c05a79-cd65-1717-d4a4-0dde3c368263
* Content: [Connect to Exchange Server (on-premises) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-server-on-premises)
* Content Source: [power-platform/admin/connect-exchange-server-on-premises.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/connect-exchange-server-on-premises.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@v-iliva 
Thanks for the update. Revised the article.
