### ISSUE TITLE
No Export Capability with Teams App

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/power-platform#418]
It would be worth noting in the capability comparison table that ALM/DevOps capability via solutions is NOT possible with the Teams app. That could be a driving factor for some to go the standalone PVA subscription route vs. M365 Teams subscription route.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba9447d-2627-7e6f-968d-93b9915c4e1c
* Version Independent ID: 06da4457-9766-4492-e9cb-89a6d7d072d3
* Content: [Get access to Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/requirements-licensing-subscriptions)
* Content Source: [power-virtual-agents/requirements-licensing-subscriptions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/requirements-licensing-subscriptions.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Hi, this is the reply from the PM for the feature:

Sorry for the delay in response. Today, you cannot export/import bot using the PVA Teams app yet. However, you can export/import bots created in Team using Power Automate maker. Select the Teams environment, create a solution, and add the Teams chatbot before export. You can import that bot to another team in Microsoft Teams using the Power Apps Teams app.
