### ISSUE TITLE
Can customers with Power Apps, Power Automate, and Power Virtual Agents subscriptions use premium connectors with Project Oakdale?

### ISSUE THREAD

**Issue by CarstenGrowth** [MicrosoftDocs/power-platform#420]
Can we clarify this. The "Yes" leads to wrong interpretation of licensing. The example outlines a different licensing will be needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@CarstenGrowth 
Handling via email.
