### ISSUE TITLE
No more "Environment Administrator"

### ISSUE THREAD

**Issue by FoxyChmoxy** [MicrosoftDocs/power-platform#421]
In the **Environment Permissions** section, the role of the **Environment Administrator** is described, although when creating a new environment this role is no longer there. I may be wrong, correct me please if I am wrong.

![image](https://user-images.githubusercontent.com/38606307/95440896-4c42b680-097b-11eb-8b1e-fb1bb50430d4.png)

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4deb237b-2aaa-88d5-ae53-dc8dff4c1410
* Version Independent ID: a440d8b3-aa78-7546-8785-5b8cd4c78bf7
* Content: [Environments overview - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/environments-overview)
* Content Source: [power-platform/admin/environments-overview.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/environments-overview.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by DrFdisk** [comment]
We have the same problem.
Does anyone have a solution or explanation here?
I'm trying to create a DLP in the scope "environment", which only the environment admin can do.

**Comment by jimholtz** [comment]
@FoxyChmoxy and @DrFdisk 
Sorry for the delated response.
The environment admin role is only for environments without a Dataverse database.
https://docs.microsoft.com/en-us/power-platform/admin/database-security#environments-without-a-dataverse-database
