### ISSUE TITLE
More clarity on powerapps per app license

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/power-platform#422]
when I assign a per app license to a environment, when is that license consumed? 

- is it consumed when i share app with users?
- if it is consumed when app is shared, what happens when such user is never logged in or log in once and doesn't return to the app for months
- is it consumed when a user log in?
- if it is consumed when a user log in, then when user log out, will the license be released?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@mganeshphani 
Sorry for the delayed response. Licensing content is frequently being rewritten. Please reopen if this is still an issue.
