### ISSUE TITLE
DLP canvas apps are not included anymore in newest version Core Component

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#423]
DLP Editor and Customizer canvas apps are not included anymore in the newest version of Core Component, so please update the documentation. These apps can be still downloaded separately from github https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/Individual%20Components/Canvas%20Apps 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The reference to the CoE apps has been removed.
