### ISSUE TITLE
ADAL Error on "Add-PowerAppsAccount"

### ISSUE THREAD

**Issue by BohrenAn** [MicrosoftDocs/power-platform#425]
Hi all,

Tried to use the Powershell Modules for PowerApps
Login with "Add-PowerAppsAccount" was not possible due an ADAL Error

PS C:\> Import-Module -Name Microsoft.PowerApps.Administration.PowerShell
WARNUNG: Die Namen einiger importierter Befehle auf Modul "Microsoft.PowerApps.Administration.PowerShell" enthalten nicht genehmigte Verben, sodass
deren Auffindbarkeit erschwert werden kann. Wenn Sie die Befehle mit nicht genehmigten Verben finden möchten, führen Sie den Import-Module-Befehl
erneut mit dem Verbose-Parameter aus. Sie können durch Eingeben von "Get-Verb" eine Liste der genehmigten Verben anzeigen.
PS C:\> Import-Module -Name Microsoft.PowerApps.PowerShell
PS C:\> Add-PowerAppsAccount
Add-PowerAppsAccount : Fehler beim Aufrufen der Methode, da [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] keine Methode
mit dem Namen "AcquireToken" enthält.
In Zeile:1 Zeichen:1
+ Add-PowerAppsAccount
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Add-PowerAppsAccount], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,Add-PowerAppsAccount

Tried to install the ADAL Module --> Resulted in an Error 
PS C:\> Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'MyNuGet'?
[J] Ja  [A] Ja, alle  [N] Nein  [K] Nein, keine  [H] Anhalten  [?] Hilfe (Standard ist "N"): j
Install-Package : Dependency loop detected for package 'Microsoft.IdentityModel.Clients.ActiveDirectory'.
In Zeile:1 Zeichen:1
+ Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Deadlock detected: (Microsoft.Ident...ActiveDirectory:String) [Install-Package],
   Exception
    + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPack
   age

Should ADAL not be migrated to this Library anyway?
https://www.nuget.org/packages/Microsoft.Identity.Client/

Regards
Andres

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@BohrenAn 
Sorry you're having this issue. Please contact support for resolution: 
https://powerapps.microsoft.com/support/
