### ISSUE TITLE
Cannot find Set retention policy when following instructions

### ISSUE THREAD

**Issue by robotwyatt** [MicrosoftDocs/power-platform#427]
Section 3 appears to be out of date or incorrect when following the instructions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837f9db7-667d-814f-1df6-98e2f89a44cc
* Version Independent ID: f53ea984-3798-d3fb-ec0c-d31f81db9250
* Content: [Audit data and user activity for security and compliance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity)
* Content Source: [power-platform/admin/audit-data-user-activity.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/audit-data-user-activity.md)
* Service: **power-platform**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by jimholtz** [comment]
@robotwyatt 
Sorry for the delayed response. We've added a note that the data retention setting isn't available until the environment is updated which will happen over time.
