### ISSUE TITLE
Powershell script for KeyVault setup references old powershell modules

### ISSUE THREAD

**Issue by bugblatter2016** [MicrosoftDocs/power-platform#430]
Old AzureRM Powershell modules are referenced in the Key Vault setup script.  Suggest making the Azure powershell versions in use obvious and/or update the script to use the latest...

Get-AzureRmResourceGroup -> Get-AzResourceGroup
New-AzureRmResourceGroup -> New-AzResourceGroup
Get-AzureRmKeyVault -> Get-AzKeyVault
New-AzureRmKeyVault -> New-AzKeyVault

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#how-to-set-up-azure-key-vault)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by laneswenka** [comment]
I am following up to see who owns this feature, as it falls outside of my current purview.

**Comment by laneswenka** [comment]
Reassigned to Sabin to follow up.  Thanks!

**Comment by jimholtz** [comment]
Closing this as it appears to be documented and updated in Azure documentation. For example:
https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azresourcegroup?view=azps-6.4.0
