### ISSUE TITLE
Default audit retention period is forever for newly provisioned instance.

### ISSUE THREAD

**Issue by TakiyaNakano-MSFT** [MicrosoftDocs/power-platform#431]
[Enter feedback here]
> The default audit retention period is 30 days for new environments and existing environments without any audit data.

As of 10/16/2020, default audit retention period isn't 30 days but forever for the instance newly provisioned on SAM region.

![image](https://user-images.githubusercontent.com/41457269/96236846-83e2db80-0fd7-11eb-9d72-86e706f4a504.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837f9db7-667d-814f-1df6-98e2f89a44cc
* Version Independent ID: f53ea984-3798-d3fb-ec0c-d31f81db9250
* Content: [Audit data and user activity for security and compliance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity)
* Content Source: [power-platform/admin/audit-data-user-activity.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/audit-data-user-activity.md)
* Service: **power-platform**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by jimholtz** [comment]
@TakiyaNakano-MSFT 
Taking to internal thread.
