### ISSUE TITLE
Project Oakdale - Admin Role Required to Enable Model Driven Apps

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/power-platform#432]
> Microsoft Teams Integration
> Tenant admins can select Microsoft Teams Integration to enable embedding model-driven apps into Teams

Presumably "Tenant admins" means the "Global Administrator"? 

"CRM Service Administrator" aka "Dynamics 365 Administrator" is not sufficient.  The (redacted) error message - from the developer console, as there is no message - is:

> User [redacted user guid] should be a global/tenant administrator to modify MS Teams embedding setting [redacted environment guid].

It would be great if this page could be clarified to indicate the exact [Azure AD role and/or role permission](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles). 

Thanks!
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66be7882-5440-7cff-142f-4436a2d648ca
* Version Independent ID: b1876c76-62e5-2e0f-c823-09be35cfd7a5
* Content: [About the Project Oakdale environment (Preview) - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/about-teams-environment#microsoft-teams-integration)
* Content Source: [power-platform/admin/about-teams-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/about-teams-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@fowl2 
This content was broadly revised. Let us know if this is still an issue.
