### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by interfacemirror** [MicrosoftDocs/power-platform#434]
The link on the line You can review your audit data in the Microsoft 365 Security and Compliance Center. **_See Search the audit log for user and admin activity_**. is broken. I see 404 error when I click on the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 184dd591-1250-2bcc-db42-35afc3a77bce
* Version Independent ID: 75aaea0f-6f52-3977-77ba-a79f3604ef5e
* Content: [Power Apps activity logging - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps)
* Content Source: [power-platform/admin/logging-powerapps.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/logging-powerapps.md)
* Service: **power-platform**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by jimholtz** [comment]
@interfacemirror 
Thanks for bringing this to our attention. The link has been corrected.
https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps#review-your-audit-data-using-reports-in-microsoft-365-security-and-compliance-center
