### ISSUE TITLE
Access related information is out dated

### ISSUE THREAD

**Issue by babakdanyal** [MicrosoftDocs/power-platform#435]
I was trying to find the environment admin role but I am not able to locate it as mentioned in this documentations, also the displayed screenshots of the admin center are different from the current admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure user security in an environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/database-security)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/database-security.md)
* Service: **power-platform**
* GitHub Login: @jayasreekumar
* Microsoft Alias: **jkumar**

**Comment by jimholtz** [comment]
@babakdanyal 
The screenshots and roles vary based on whether a Common Data Service database was added to the environment.

**Comment by babakdanyal** [comment]
@jimholtz 
Can you please share the difference, as I have tried it with different roles under different release settings but I get this screen and CDS or no CDS I get this 
![image](https://user-images.githubusercontent.com/11374923/97240185-b3001500-1841-11eb-9b88-42f3bedc6847.png)

Thanks
