### ISSUE TITLE
Dynamics additional capacity storage user licenses

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/power-platform#438]
>
> User licenses: Additional capacity added for every user license purchased
>
I have some questions on the above quote from this doc.
* Is there documentation that shows the breakdown for how much storage is added for every user license purchased?
* Is there documentation that which licenses this additional capacity applies too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb490ef-2fd6-0f32-3b9b-c0cbbdc19110
* Version Independent ID: db3a8404-a0b7-19c7-3f12-289187549cb4
* Content: [Legacy storage capacity - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/legacy-capacity-storage)
* Content Source: [power-platform/admin/legacy-capacity-storage.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/legacy-capacity-storage.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@gregdegruy 
Please see the licensing guide: https://go.microsoft.com/fwlink/?linkid=2085130
