### ISSUE TITLE
Limit on number of Power Automate outputs

### ISSUE THREAD

**Issue by AutomationTeamVA** [MicrosoftDocs/power-platform#44]
I am in the process of creating a bot that can use Office 365 User data to portray a users department, title, location, and phone number.  I am successful when pulling data from a flow once it gets passed four Power Automate outputs I get the following error
> Sorry, something went wrong. I am not able to help you at the moment, please check back later.

Will work: 
![image](https://user-images.githubusercontent.com/54072694/70814146-87428080-1d90-11ea-8ca9-f77eafbbf66d.png)

Will not work because it has 4 outputs:
![image](https://user-images.githubusercontent.com/54072694/70814170-91fd1580-1d90-11ea-8514-01135497dc8b.png)

This is happening on all flows that I create. I have verified that both flows shown above are indeed pulling all the data properly as well and the flows are running successfully.

**Comment by iaanw** [comment]
@makolomi Can you help troubleshoot this?

**Comment by iaanw** [comment]
For product issues please check the PVA forum: https://powerusers.microsoft.com/t5/Power-Virtual-Agents-Forum/bd-p/10292019

This looks like a feature request or feature issue - there are other PMs and devs at that forum that will be able to best help resolve this problem :(
