### ISSUE TITLE
Request to export and download data for newly created bots

### ISSUE THREAD

**Issue by KoradaRajesh** [MicrosoftDocs/power-platform#444]
While exporting bot content from power apps. The newly created bot's contents(topics, phrases) are not getting updated in csv file(annotations, msdynce_botcontents), we are getting only default data(topics, phrases).

We have followed instructions mentioned in this document.
https://docs.microsoft.com/en-us/power-virtual-agents/gdpr-export

Here we have created Topic named NewTopic
![image](https://user-images.githubusercontent.com/51915291/97168206-0cb6ff80-17ae-11eb-941c-c53d42bef73a.png)

After converting to .lu format we didn't found  newly created topicNewTpoic) here.
![topic not found in lu](https://user-images.githubusercontent.com/51915291/97168349-51db3180-17ae-11eb-8acd-be6b85b2987a.png)

**Comment by srisilex** [comment]
Yes, i'm also facing the same issue, the bot content is not updated even republished after add/delete topics from PVA.

**Comment by Harshul9089** [comment]
Same with me, newly updated bot content is not getting retrieved in my exported csv file.

**Comment by Harshul9089** [comment]
Hi all, 
Are there any updates regarding this issue? As this becoming a major roadblock in our project. Or If there is any other channel to get help regarding this issue, please post here.

**Comment by ambuj74** [comment]
Did you guys got any update on this, I am  having the same issue I am not able to get any topic content.

**Comment by iaanw** [comment]
Thanks for your questions! The best place for product troubleshooting - is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
