### ISSUE TITLE
Storage notification

### ISSUE THREAD

**Issue by clora28** [MicrosoftDocs/power-platform#445]
Are there any plans to enable storage notification - possibly email or an API for reporting purposes?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f8c1ca-4250-85c7-2b8e-caab633d8d9d
* Version Independent ID: 70065f90-617e-d812-e04e-7594708b0cce
* Content: [New Common Data Service storage capacity - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/capacity-storage)
* Content Source: [power-platform/admin/capacity-storage.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-storage.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@clora28 

Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
