### ISSUE TITLE
Is modifying the url directly in the mashup editor really not supported? Or only filtering in the url?

### ISSUE THREAD

**Issue by JeroenLeeflang** [MicrosoftDocs/power-platform#447]
Question about the sentence: "Modifying the url directly in the mashup editor is not supported. Only the filter applied using the mashup editor UI or specified in source filter edit field on mapping page will be used."

What is meant with modifying in this sentence? Adding a filter? Because sometimes it is needed to edit the url for adding expands, order by's, etc. 

In light of the rest of the sentence, I think only add filtering on url level is not supported. It would be good to make this more clear.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd884343-7f2e-9765-4860-4cb4981a908e
* Version Independent ID: efe70284-6f99-698c-9406-802595535d97
* Content: [Integrate data into Common Data Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/data-integrator#advanced-data-transformation-and-filtering)
* Content Source: [power-platform/admin/data-integrator.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/data-integrator.md)
* Service: **power-platform**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sabinn-msft** [comment]
In general, we do not recommended to modify url directly unless customers are very familiar with ODATA request syntax. And here’s a list of things that you should be aware of

1.	The query part of the odata requests has to strictly follow the format of 
https://.../api/data/v.../...?$select=...&$expand=...&$filter=...&$orderby=versionnumber desc
2.	$filter clause will not be honored at runtime, and it should be defined on source filter editor on the mapping page

**Comment by JeroenLeeflang** [comment]
We are familiar with the OData request syntax. Actually, getting the integration working is not possible without it.

Not recommended is different from "not supported" and the "not supported" is only applicable to the filter clause.

I think it would be good to update this on the doc page itself.

**Comment by sabinn-msft** [comment]
Thanks for the feedback Jeroen. I'll work on updating this part to call out the 'filter part' specifically not being supported.

**Comment by JeroenLeeflang** [comment]
Thanks @sabinn-msft!
