### ISSUE TITLE
Please use correct terminology

### ISSUE THREAD

**Issue by tombyang** [MicrosoftDocs/power-platform#45]
Azure Bot Framework doesn't exist... it is either Microsoft Bot Framework or Azure Bot Service. For PVA, we should refer to Bot Framework (this is where the skills are)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2319511e-b541-6ffc-8c02-387e6ff0885f
* Version Independent ID: 24f5443f-d50b-6be9-674f-38c0400d9953
* Content: [Use Azure Bot Framework Skills in Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-use-skills)
* Content Source: [power-virtual-agents/advanced-use-skills.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-use-skills.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for the heads up, I made the updates, they should go live shortly.
