### ISSUE TITLE
Power Automate activity logging missing

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/power-platform#450]
Power Automate also logs activity events in the Audit Log, this is missing here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 184dd591-1250-2bcc-db42-35afc3a77bce
* Version Independent ID: 75aaea0f-6f52-3977-77ba-a79f3604ef5e
* Content: [Power Apps activity logging - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps)
* Content Source: [power-platform/admin/logging-powerapps.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/logging-powerapps.md)
* Service: **power-platform**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by jimholtz** [comment]
@manuelap-msft 
Taking to email.
