### ISSUE TITLE
синхронизация

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/power-platform#451]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4ff6033-4188-72a1-a775-867273fe1d96
* Version Independent ID: 9250b4bd-f0ce-f0a4-7ebf-fb2bd3492910
* Content: [Manage licenses in your organization - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/signup-question-and-answer)
* Content Source: [power-platform/admin/signup-question-and-answer.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/signup-question-and-answer.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@matuhinal 
Please provide a description of issue with the documentation. Thanks.
