### ISSUE TITLE
Assigning Capacity Add On

### ISSUE THREAD

**Issue by wisc75** [MicrosoftDocs/power-platform#452]
We purchased the Add-on Capacity but we can't find a way to assign it to a user.  Why do you allow us to purchase it but not assign it?  Do we need to contact customer service now to have the licenses refunded?  We tried through the portal and using powershell.  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@wisc75 
Please create a support request:
https://powerapps.microsoft.com/support/
