### ISSUE TITLE
Methods listed out of order

### ISSUE THREAD

**Issue by nikkelly** [MicrosoftDocs/power-platform#454]
Looks like they were all in order to start and then split up to the reduce file/log/database storage sections. 

Example: 
Reduce file storage
Method 3: Remove email attachments using Advanced Find

Reduce log storage
Method 10: Delete audit logs

Reduce database storage
Method 1: Delete bulk email and workflow environments using a bulk deletion job

Easier to read and understand if they flow 1-11 instead of: 
3,4,5,6,10,1,2,7,8,9,11
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9c9aae-ceaa-2e78-3752-2770327f49a7
* Version Independent ID: acd2ddc9-6225-92e8-2636-2a02437c3d82
* Content: [Free up storage space - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/free-storage-space)
* Content Source: [power-platform/admin/free-storage-space.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/free-storage-space.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@nikkelly 
Thanks for the suggestion, Nik. We'll consider this for future content revision.
