### ISSUE TITLE
Issue with "Set up the custom connector"

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftDocs/power-platform#455]
Trying to reproduce the installation steps for the COE Starter Kit -> configuration of the Office 365 Management API custom connector. All goes well, until the test of the connector configuration. The error message thrown when starting the test is below. The tenant ID is OK and everything else was done exactly as described.

{
  "error": {
    "code": "StartSubscription [CorrId=4230ba8e-d741-4f34-b018-5e9f53187d45][TenantId=10d8221e-c91b-469d-9176-79fe854e685d,ContentType=Audit.General,ApplicationId=79b089f6-97d9-4267-abe4-b62603c43485,PublisherId=79b089f6-97d9-4267-abe4-b62603c43485][AppId",
    "message": "9b089f6-97d9-4267-abe4-b62603c43485] failed. Exception: Microsoft.Office.Compliance.Audit.DataServiceException: Tenant 10d8221e-c91b-469d-9176-79fe854e685d does not exist.\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetSubscriptionTableClientForTenantAsync>d__50.MoveNext() in d:\\dbs\\sh\\nibr\\1014_061443_0\\cmd\\18\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 1872\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetAPISubscriptionAsync>d__22.MoveNext() in d:\\dbs\\sh\\nibr\\1014_061443_0\\cmd\\18\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 497\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.StartController.<StartSubscription>d__0.MoveNext() in d:\\dbs\\sh\\nibr\\1014_061443_0\\cmd\\1a\\sources\\dev\\auditing\\src\\auditapiservice\\apifrontendservicerole\\Controllers\\StartController.cs:line 76"
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The error message indicates that the Tenant ID does not exist - maybe you've had a copy&paste error pasting the Tenant ID into the  Tenant field? Double check that that's the correct tenant, from your Azure App Registration before trying again!

**Comment by RobertRybaric** [comment]
Hi Manuela, no, it is to 1000% a correct tenant ID.

**Comment by manuelap-msft** [comment]
The error message states
**Tenant 10d8221e-c91b-469d-9176-79fe854e685d does not exist**

Which leads me to believe either some of the IDs are wrong, or the permissions are set up incorrectly. When did you enable Audit Log for this tenant? If it has been very recently, it can take a few hours to activate and that configuration might not exist yet.

**Comment by RobertRybaric** [comment]
That is true, I was following the steps one after another, so I enabled the Audit Log just few minutes before I went ahead with the subsequent steps. Will try continue tomorrow then.

**Comment by manuelap-msft** [comment]
That's great - yes, it can take a couple of hours to turn on and activate. More details here: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#requirements-to-search-the-audit-log

Fingers crossed it will work tomorrow!

**Comment by RobertRybaric** [comment]
Hi Manuela, I was successful the day after, so that this issue is resolved. However in my opinion, the overall installation is terribly complex and time consuming. Someone without proper IT skills would never be able to install the whole COE package. Would it be possible to simplify the whole process somehow?

Thanks, Robert

**Comment by manuelap-msft** [comment]
Thanks for confirming and using the CoE Starter Kit!

With the modern solution import experience and connection references, the install of the main components has improved. For the Audit Log, there are some pre-requisites that connector requires that we can't influence as we're just consumers of the API. That connector also requires Global Admin or Audit Log permission, which in our experience is only granted to IT administrators. 

Thanks for the feedback!
