### ISSUE TITLE
Condition "None of these expressions" is not getting triggered.  

### ISSUE THREAD

**Issue by KamBabu** [MicrosoftDocs/power-platform#456]
I have a custom Entity just like the sample, 'Outdoor store categories' now, when I am testing for an exception condition meaning, a phrase that has a keyword not listed in the custom entity list, I was expecting the bot to trigger "All other condition" branch but I don't see it happening.
An example 
User: I want to buy something.
BOT:  I can help you with outdoor stuff purchasing. Which product department you're looking for? 
User: none of them or something else
This is not taking me to the "All other Condition" branch. 

VA is prompting me with the same question " I can help you with outdoor stuff purchasing. Which product department you're looking for? ".

**Comment by jimholtz** [comment]
@KamBabu 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1

**Comment by KamBabu** [comment]
Thanks Jim.
