### ISSUE TITLE
URL in Article not working

### ISSUE THREAD

**Issue by fvanrijt** [MicrosoftDocs/power-platform#457]
The last line in the article contains a Link which no longer works, it currently links towards: https://support.microsoft.com/kb/2655102 which no longer exists.

"For a list of other URLs you may need to add to unblock, see Internet accessible URLs required for Microsoft Dynamics CRM Online"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ad60e7-0308-31f9-8e05-31020e3d4b67
* Version Independent ID: 30cbae86-6165-5c35-45af-a5b21ac32247
* Content: [Troubleshooting: Unblock required URLs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/troubleshooting-unblock-urls-required?source=docs)
* Content Source: [power-platform/admin/troubleshooting-unblock-urls-required.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/troubleshooting-unblock-urls-required.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@fvanrijt 
The link appears to work now:
https://support.microsoft.com/help/2655102/internet-accessible-urls-required-for-connectivity-to-microsoft-dynami
