### ISSUE TITLE
No Double Counting

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/power-platform#458]
Thanks for adding this clarification to the docs page: **Moreover, requests from Power Automate to the Common Data Service are not double-counted, a flow that calls one action will only count as one request against their limit, not two**.

However, what isn't stated is which limit is hit with the API call  - I have a flow that has an action step in it to Create a new CDS record. In the above statement I don't get hit with 2 API calls - flow and CDS. they get counted as one. But which service has the API call counted against it- the Flow allotment or the Dynamics 365 application?

Thank you.

Jerry

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#frequently-asked-questions)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@JerryCRMI 
From the product team: API Request limits are not scoped to services. The capacity pools are per-user or per-flow, with API Requests counting against one of these pools.

Implementation wise, it will just follow the [Microsoft Power Apps and Power Automate Licensing Guide](https://go.microsoft.com/fwlink/?linkid=2085130). There’s no mention in there of service-scoped limits.
