### ISSUE TITLE
Correct the 'Azure Bot Framework' term

### ISSUE THREAD

**Issue by tombyang** [MicrosoftDocs/power-platform#46]
It's either Microsoft Bot Framework or Azure Bot Service. For the dispatcher, it should be MBF

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a1322f-8123-d498-1a5c-431ad816c389
* Version Independent ID: a5f4b3d4-2a1a-edcc-c9fa-b3e2154e65ff
* Content: [Use an Azure Bot Framework bot with Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-use-dispatcher)
* Content Source: [power-virtual-agents/advanced-use-dispatcher.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-use-dispatcher.md)
* Service: **dynamics-365-ai**
* GitHub Login: @pawant-ms
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks, I've updated all instances. The updates should go live shortly.
