### ISSUE TITLE
Please incorporate the latest document updates into the Japanese version of the document.

### ISSUE THREAD

**Issue by AsamiKondo** [MicrosoftDocs/power-platform#460]
![image](https://user-images.githubusercontent.com/71856763/98092835-7a5bdd80-1eca-11eb-941c-b10a74b0ba83.png)

Please reflect the following additional information changed on 10/28/2020 in the Japanese version of the publication.

<description>
As of October, 2020, the baseline access license is no longer required. 

<place>
FAQ
I assigned the baseline access license to my users as a workaround suggested earlier. Now that this workaround is not needed, what should I do to ensure my users are setup correctly?

**Comment by jimholtz** [comment]
@AsamiKondo 
Taking this to email.
