### ISSUE TITLE
Pre-migration verification time not communicated in document

### ISSUE THREAD

**Issue by tangkevin88** [MicrosoftDocs/power-platform#461]
[Enter feedback here]
G2G requires a week's worth of time for verification purposes before performing the actual move. There have been many requests from support end that have been raised unnecessarily as high severity cases due to customer expecting this to be able to be done within a day or two. This front-facing document does not indicate that and give customers unrealistic expectations. Please consult the support team on expectations on steps prior to migration and write explicitly what customers should expect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029aa7d3-e3e1-f99a-3f71-e11e998cb543
* Version Independent ID: 3d87af00-dcfd-697c-87df-3990a4cc8027
* Content: [Geo to geo migrations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/geo-to-geo-migrations)
* Content Source: [power-platform/admin/geo-to-geo-migrations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/geo-to-geo-migrations.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@tangkevin88 
Taking this to internal thread.
