### ISSUE TITLE
Child Flows API calls

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/power-platform#464]
Can you add to this docs page information on which user account is charged for the API calls made by a child Power Automate Flow? Is it the owner of the parent? Is it the owner of the child flow?

Jerry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@JerryCRMI 
Sorry for the delayed response. Here's what I heard back from the product team.

Can you help clarify? I would assume that this should be the “Caller” of the child if this runtime else in case of background ones, this would be the owner of the child flow.

**Comment by JerryCRMI** [comment]
@jimholtz Exactly, perhaps stating the obvious in the documentation. Child flow API calls are assigned to the owner of the Child flow and not to the owner of the Parent flow that called the Child flow.
