### ISSUE TITLE
Change use of word "Broadcast"

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/power-platform#466]
[Enter feedback here]

Don't use the word "Broadcast". That suggests to me at least, that a proactive email or something is sent to users. Whereas nothing of the short happens. Instead a user has to specifically go to wherever the web resource is published to see the announcements.

Also, describing the use of announcements as message boards doesn't make sense to me either. That suggests some form of interactivity like a forum between the author of the announcement and users - I don't see a way for that kind of interaction.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f73d22d2-bd94-7644-9aed-9edc19fd9b91
* Version Independent ID: bf4d1b9d-65e1-f937-17c1-6fe7f062b212
* Content: [Broadcast announcements to an entire organization - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/settings-announcements?source=docs)
* Content Source: [power-platform/admin/settings-announcements.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/settings-announcements.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@feridunkadir 
Thanks for the terminology suggestions. We'll consider making revisions in future documentation updates.
