### ISSUE TITLE
Reference to DLP management should be removed

### ISSUE THREAD

**Issue by ZaarourOmar** [MicrosoftDocs/power-platform#467]
Since DLP apps are removed, the reference to their functionality should be removed as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2713d356-fba8-b8d1-cd56-c949e8c01fe5
* Version Independent ID: 9dc32bb0-30fb-2bc2-a92a-b4f3ef24d984
* Content: [What is a Center of Excellence - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/motivation)
* Content Source: [power-platform/guidance/coe/motivation.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/motivation.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
On this page, we are no longer referring to any DLP apps part of the CoE Starter Kit - only to DLP policies and management available in the Admin Center PPAC. It is important for customers establishing a CoE and Admin best practices to understand both out of the box functionality, as well as customizations that can be done via the CoE Starter Kit.
