### ISSUE TITLE
Dynamics 365 Customer Engagement Web Services s/b CDS

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/power-platform#469]
Topic still has reference to 'Dynamics 365 Customer Engagement Web Services'
Should be Common Data Service 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d0d5ce-9fb1-926e-ef38-18f70e200c3b
* Version Independent ID: 88ae146e-1e90-21a3-5c83-917e3a5d0f48
* Content: [Field-level security - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/field-level-security)
* Content Source: [power-platform/admin/field-level-security.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/field-level-security.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@JimDaly 
Changing to Microsoft Dataverse web services. Thanks for the alert.
