### ISSUE TITLE
Thorsten Sasse, Microsoft Employee

### ISSUE THREAD

**Issue by ThoSa1971** [MicrosoftDocs/power-platform#47]
Hi team, I find the following confusing:

1.) "You can connect your bot to existing Azure Bot Service channels. This can be helpful if you want to connect your bot to end users on Azure Bot Service channels."

In this article we are talking about connecting the Power Virtual Agent to an existing Azure Bot Service channel, right?

2.) I find the term "Power Virtual Agent bot"  on the webpage misleading. The official product name is: "Power Virtual Agent", right?

Thanks, Thorsten Sasse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f021302-c22b-04cb-db6a-91ded1835057
* Version Independent ID: 9348c068-b8be-bf05-d94a-df03147fa0ad
* Content: [Add a Power Virtual Agents bot to Azure Bot Service channels - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/publication-connect-bot-to-azure-bot-service-channels#feedback)
* Content Source: [power-virtual-agents/publication-connect-bot-to-azure-bot-service-channels.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/publication-connect-bot-to-azure-bot-service-channels.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
1. That's correct, it's for adding to existing ABS channels. @pawant-ms to confirm.
2. The correct name is 'Power Virtual Agents', within which you can create bots. So for this article, it's about adding a specific bot you've created in Power Virtual Agents to an ASC channel.
