### ISSUE TITLE
Which version of azure ad premium

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/power-platform#470]
Please add to documentation which version of azure ad premium is required. Right now its too vague.. does it require P1 or P2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 003fe16c-7cf4-14c6-09f2-7b18b047cbf7
* Version Independent ID: 3c7059c0-3aff-2729-42a7-88c4e7de0157
* Content: [Block access by location with Azure AD Conditional Access - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/restrict-access-online-trusted-ip-rules)
* Content Source: [power-platform/admin/restrict-access-online-trusted-ip-rules.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/restrict-access-online-trusted-ip-rules.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jebalert 
Sorry for the delayed response. Security content is frequently being rewritten. Please reopen if this is still an issue.
