### ISSUE TITLE
Missing step in View Audit Logging Details section

### ISSUE THREAD

**Issue by jdballard** [MicrosoftDocs/power-platform#471]
In the View Audit Logging Details sections, ("https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity#view-audit-logging-details"), step 2 is missing an important step. The part in bold should be added.

Go to Environments > [select an environment] > **Select Settings from the top menu** > expand Audit and logs > Audit Summary View.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837f9db7-667d-814f-1df6-98e2f89a44cc
* Version Independent ID: f53ea984-3798-d3fb-ec0c-d31f81db9250
* Content: [Audit data and user activity for security and compliance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity#view-audit-logging-details)
* Content Source: [power-platform/admin/audit-data-user-activity.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/audit-data-user-activity.md)
* Service: **power-platform**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by jimholtz** [comment]
@jdballard 
Thanks for bringing this to our attention. Steps in the topic have been corrected.
