### ISSUE TITLE
Add-on option for extending "Service protection limits" might be wrong

### ISSUE THREAD

**Issue by iiu-dk** [MicrosoftDocs/power-platform#472]
Under Heading "Requests limits not based on licensed users or flows"
"After base request capacity is exhausted, customers can increase this capacity by purchasing a Power Apps and Power Automate capacity add-on."

Please verify that this is correct, both Fasttrack and MS support are saying that "Service protection limits" cannot be extended with add-on.. only "Entitlement limits" can.. but I could have been understanding it wrong :)

Please also update this page to use same terminology as other pages on topic of "api limits" please use "Service protection limits" & "Entitlement limits" as this is confusing and it creates Community Paranoia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#feedback)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by iiu-dk** [comment]
@cpdSeattle issue have a relationship with [https://github.com/MicrosoftDocs/powerapps-docs/issues/1930](https://github.com/MicrosoftDocs/powerapps-docs/issues/1930)

**Comment by jimholtz** [comment]
@iiu-dk 
Sorry for the delayed response. Here's info from the product team.
Q1: Referring to [this section](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#requests-limits-not-based-on-licensed-users-or-flows), for the page this content is on, it is specific to Entitlement limits and is accurate.  If wanted, there could be clarity added to specify “base entitlements.”  Further down the page [here](https://docs.microsoft.com/en-us/power-pla:tform/admin/api-request-limits-allocations#will-there-be-a-transition-period-for-existing-customers), there is mention of the ability to purchase capacity, but no method to assign it yet.  Again, factually correct, but could be confusing.
Q2: The page referred to is related to Power Platform Request limits, and is not about Service Protection Limits.
