### ISSUE TITLE
Please clarify Dynamics 365 FinOps and CRM

### ISSUE THREAD

**Issue by bcaillet** [MicrosoftDocs/power-platform#475]
The Page is saying Dynamics 365 Administrator which can bring confusion to customers.

can you add that This is only realted to Dynamics 365 Customer Engagement and Sales, not Finance and Supply Chain?

Thanks,
Bertrand Caillet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c1dd41e-5994-2eb5-f659-af836a1a3fc1
* Version Independent ID: f70008c9-ea14-96f1-8b29-d94bb510b680
* Content: [Use service admin roles to manage your tenant - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/use-service-admin-role-manage-tenant?source=docs)
* Content Source: [power-platform/admin/use-service-admin-role-manage-tenant.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/use-service-admin-role-manage-tenant.md)
* Service: **power-platform**
* GitHub Login: @jayasreekumar
* Microsoft Alias: **jkumar**

**Comment by jimholtz** [comment]
@bcaillet 
Taking to internal thread.
