### ISSUE TITLE
Implementation information for cross-tenant isolation incorrect

### ISSUE THREAD

**Issue by jessierobbins** [MicrosoftDocs/power-platform#476]
The implementation information in bullet points is backwards:

Current state: 
Restricting outbound connections means a user in your tenant is blocked from connecting to a third-party tenant. Restricting inbound cross-tenant connections requires a support ticket—this restriction then only applies to Power Apps and Power Automate.

Restricting inbound connections means a user in a third-party tenant is blocked from creating a connection to your tenant. Restricting outbound cross-tenant connections can be done using tenant restrictions that apply to all Azure Active Directory (Azure AD) software as a service (SaaS) cloud apps, or at the API Hub level, which would block outbound connections just for canvas apps and flows.

Corrected:
Restricting outbound connections means a user in your tenant is blocked from connecting to a third-party tenant. Restricting outbound cross-tenant connections can be done using tenant restrictions that apply to all Azure Active Directory (Azure AD) software as a service (SaaS) cloud apps, or at the API Hub level, which would block outbound connections just for canvas apps and flows.

Restricting inbound connections means a user in a third-party tenant is blocked from creating a connection to your tenant. Restricting inbound cross-tenant connections requires a support ticket—this restriction then only applies to Power Apps and Power Automate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21c5d280-6884-6b8a-c6dd-cc77d988fa14
* Version Independent ID: 7a0cfc73-8ade-01b1-f364-4fcb4d13f7cd
* Content: [Enable cross-tenant isolation - Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/adoption/tenant-isolation)
* Content Source: [power-platform/guidance/adoption/tenant-isolation.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/adoption/tenant-isolation.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Content has been amendended now.
