### ISSUE TITLE
What impact does Limited-Web-Only create..

### ISSUE THREAD

**Issue by thomasforde** [MicrosoftDocs/power-platform#478]
[Enter feedback here]
Any updates on this setting in regards to modifying access from unmanaged devices?
Does it have any effect on limited web-only and using the workaround is practically making the whole access part useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b6702c-b45c-9c90-f809-fe0d276ab526
* Version Independent ID: fc9e44c1-fa3e-93c4-f574-ae2cd6c3ffdc
* Content: [Set up customer engagement apps to use SharePoint Online - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online#known-issue)
* Content Source: [power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online.md)
* Service: **power-platform**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@thomasforde - as per the link to the SharePoint article referenced, there's the following: 

When Access Control for Unmanaged Devices in SharePoint is set to Allow limited, web-only access, SharePoint files cannot be downloaded but they can be previewed. The previews of Office files work in SharePoint but the previews do not work in Microsoft Yammer.

Closing issue.
