### ISSUE TITLE
Show welcome screen on sign in - Description Missing

### ISSUE THREAD

**Issue by Sinha-Abhisek** [MicrosoftDocs/power-platform#481]
"Show welcome screen on sign in" has the same description as "Show dashboard cards in expanded state". They both say: "Default: Off. Select On to see the detailed card form in a dashboard. If set to Off, only the header and minimal details are displayed in the card form."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d941b293-2873-2c2c-6f44-9a4c28aa98e5
* Version Independent ID: e704ed8d-7769-b9ff-7028-d684044788c0
* Content: [Manage behavior settings - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/settings-behavior)
* Content Source: [power-platform/admin/settings-behavior.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/settings-behavior.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Sinha-Abhisek 
Thanks for bringing this to our attention. The incorrect text has been removed.
