### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by GarryPope** [MicrosoftDocs/power-platform#482]
Hello, 
I was reading this page, and I think I spotted a spelling mistake.

On this page there is a sentence that says, " If your user looses admin access during the run of the sync flows", I think it's meant to be  If your user **loses** admin access during the run of the sync flows.

![image](https://user-images.githubusercontent.com/68440710/100007573-2dca3a80-2dc4-11eb-9b35-1c73bf43a315.png)

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d61c7e5-8eda-2412-1bef-ffc9b74887bb
* Version Independent ID: 45d039f7-eb71-efdb-334e-2dad2db5aac1
* Content: [Limitations - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations)
* Content Source: [power-platform/guidance/coe/limitations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/limitations.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Fixed, thank you for letting us know
