### ISSUE TITLE
Flow repeated twice CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With)

### ISSUE THREAD

**Issue by GarryPope** [MicrosoftDocs/power-platform#483]
Hello,
I was reading this document and you mention this flow CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With) twice. I think it is only needed once. The description is a little bit different, but I think it's the same. I maybe wrong. 

![image](https://user-images.githubusercontent.com/68440710/100008088-e2fcf280-2dc4-11eb-875d-492738bab146.png)

Thanks,

Garry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
We have updated this now, thanks for letting us know!
