### ISSUE TITLE
Security Roles and how to add users to security roles information is out dated

### ISSUE THREAD

**Issue by babakdanyal** [MicrosoftDocs/power-platform#484]
@jimholtz 
Can you please share the difference, as I have tried it with different roles under different release settings but I get this screen and CDS or no CDS I get this 
![image](https://user-images.githubusercontent.com/11374923/97240185-b3001500-1841-11eb-9b88-42f3bedc6847.png)

Thanks

_Originally posted by @babakdanyal in https://github.com/MicrosoftDocs/power-platform/issues/435#issuecomment-716886669_

**Comment by jimholtz** [comment]
@babakdanyal 
Sorry for the delayed response. Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
