### ISSUE TITLE
Broken link - "limitations information"

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#486]
Following link on page https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components seems to be broken

![image](https://user-images.githubusercontent.com/8307644/100268674-01e2bc80-2f5e-11eb-8ef9-53b9d6782211.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you for pointing that out! This is meant to take you to https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#long-running-flows

We'll fix that when we next update the docs!

**Comment by manuelap-msft** [comment]
Fixed, thanks for letting us know
