### ISSUE TITLE
we see a new user that is not listed here: 

### ISSUE THREAD

**Issue by HelioFerreira** [MicrosoftDocs/power-platform#489]
we see a new user in the list of users that is not documented here: CDSUserManagment  this doc needs to be updated as soon as possible as this is causing questions around this user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 436a3b84-3edb-8d4e-bc7e-51488b8f879a
* Version Independent ID: 634e9777-62b1-01e6-6db1-eafbfe5d8d7d
* Content: [System and application users - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/system-application-users)
* Content Source: [power-platform/admin/system-application-users.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/system-application-users.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@HelioFerreira 
Handling via internal thread.
