### ISSUE TITLE
Roadmap Item for Customizing SharePoint List Form in GCC?  

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/power-platform#49]
It is possible to get an ETA for the following item?  I don't see it listed in the [Roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=GCC&searchterms=power%2Capps). Thanks! :-)  
![image](https://user-images.githubusercontent.com/38665906/70950448-d5b87f00-201d-11ea-8672-9c613f6876d2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea524f2a-1e2a-6ade-8e2b-bc61173107c5
* Version Independent ID: 5990c060-8907-62b4-a8b3-f7ed8339a70e
* Content: [Microsoft Power Apps US Government - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government#power-apps-us-government-feature-limitations)
* Content Source: [power-platform/admin/powerapps-us-government.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-us-government.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by mrpullen** [comment]
Seconded!! Would like a timeline / ETA for this functionality.

**Comment by jenjenva** [comment]
+1 for timeline / ETA

**Comment by jimholtz** [comment]
Sorry for the delay. This feature is in planning but we cannot provide an ETA.
