### ISSUE TITLE
When API Limits Capacity Add-ons will be available?

### ISSUE THREAD

**Issue by dimazoin** [MicrosoftDocs/power-platform#490]
When API Limits Capacity Add-ons will be available for purchase and assignment?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#power-apps-and-power-automate-capacity-add-on)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@dimazoin 
They appear as “Power Apps and Power Automate capacity add-on”. However, they cannot be assigned to environment or user yet.
