### ISSUE TITLE
Missing Information: Where can I track the usage per user?

### ISSUE THREAD

**Issue by pkothree** [MicrosoftDocs/power-platform#491]
According to this article, the usage is tracked per user and per 24h. But I don't see any option to get information per user om 24h. This would be helpful to decide which licenses should be used. Is the information missing in the article or is there no way for an admin to track the actual per user usage, which is important for the correct licensing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#microsoft-power-platform-requests-allocations-based-on-licenses)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@pkothree 
We are working on providing this in Power Platform admin center. No ETA yet.
