### ISSUE TITLE
Dataverse phrasing

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/power-platform#492]
It doesn't seem like the global search and replace for the name change worked so well in this sentence?

The Dataverse provides the ability to have identities that do not require any user license to interact with the service. There are four types of these users:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#microsoft-power-platform-requests-allocations-based-on-licenses)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@JerryCRMI 
Greetings. Is it the "interact with the service" that you recommend be changed?

**Comment by JerryCRMI** [comment]
@jimholtz Jim there are actually several but this sentence initially caught my attention: The Dataverse provides the ability to have identities that do not require any user license to interact with the service. There are four types of these users:

and
If your apps or flows primarily use the Dataverse, then these reports can serve as good approximations of the total usage of your solutions.

and
However, if your apps or flows do not use the Dataverse, then at this time there are no reports available in the Power Platform Admin center, although this will be available during 2020 Release Wave 2. 

and
Thus, there is no difference whether you choose to use Power Automate or a third-party tool. Moreover, requests from Power Automate to the Dataverse are not double-counted, a flow that calls one action will only count as one request against their limit, not two.

**Comment by jimholtz** [comment]
@JerryCRMI 
It looks like "the Dataverse" is the accepted verbiage, At least for now.
