### ISSUE TITLE
Dynamics 365 Portal still available?

### ISSUE THREAD

**Issue by TennysonLKS** [MicrosoftDocs/power-platform#494]
[Enter feedback here]
The FAQ compare Power apps portals and Dynamics 365 Portals. We are being told that Dynamics 365 Portals no longer available for partner to sell.  If that is true, it may be useful to highlight in this FAQ. Else the vague assumptions to the readers is that both portal options are available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd73afb-e2cf-acba-4d91-ec5700c36864
* Version Independent ID: 83657a57-1fc6-8270-24cf-00d68f9918de
* Content: [Sandbox environments - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/sandbox-environments)
* Content Source: [power-platform/admin/sandbox-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/sandbox-environments.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@TennysonLKS 
This article does not mention portals. Perhaps you meant a different article?
