### ISSUE TITLE
Key Vault requirements

### ISSUE THREAD

**Issue by idunbar46** [MicrosoftDocs/power-platform#495]
Documentation states:

The Key Vault should be tagged with the organization (OrgId) and tenant ids (TenantId). This can be completed by running the AzurePowerShell command below. More information: How to set up Azure Key Vault

The Key Vault does not need to be tagged, and the powershell does not perform this.  The secret within the Key Vault needs to be tagged, which the powershell does perform.
---

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@idunbar46 
Thanks for bringing this to our attention. The documentation has been updated.
