### ISSUE TITLE
Incorrect Information for "Show welcome screen on sign in"

### ISSUE THREAD

**Issue by Marksatx23** [MicrosoftDocs/power-platform#497]
"Show welcome screen on sign in" has the description from "Show dashboard cards in expanded state" which is incorrect!

![image](https://user-images.githubusercontent.com/54391739/100827661-dc085c80-3422-11eb-9fb5-ea99014095a2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d941b293-2873-2c2c-6f44-9a4c28aa98e5
* Version Independent ID: e704ed8d-7769-b9ff-7028-d684044788c0
* Content: [Manage behavior settings - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/settings-behavior)
* Content Source: [power-platform/admin/settings-behavior.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/settings-behavior.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Marksatx23 
Thanks for bringing this to our attention. I'll remove the incorrect text for now and replace the replace with text when I hear back from the product team.
