### ISSUE TITLE
Dynamics plan do not exist anymore, please update

### ISSUE THREAD

**Issue by RaphaelTagliani** [MicrosoftDocs/power-platform#498]
[Enter feedback here]
Hello,

The licensing referenced in this page is not current anymore (1000 users with a Dynamics *plan*). Please update with base/attach terminology.

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c43b88-32f5-49ab-d715-bfcf75c9ba3e
* Version Independent ID: 70179da7-e3b6-8775-97cc-361990404677
* Content: [Manage the encryption key - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-encryption-key)
* Content Source: [power-platform/admin/manage-encryption-key.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-encryption-key.md)
* Service: **power-platform**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by jimholtz** [comment]
@RaphaelTagliani 
Taking this to internal thread.
