### ISSUE TITLE
#BIZqa user not documented

### ISSUE THREAD

**Issue by crh03** [MicrosoftDocs/power-platform#499]
#Bizqa user is not documented.  This service account is showing up in the list of users in all environments but isn't documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 436a3b84-3edb-8d4e-bc7e-51488b8f879a
* Version Independent ID: 634e9777-62b1-01e6-6db1-eafbfe5d8d7d
* Content: [System and application users - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/system-application-users?source=docs)
* Content Source: [power-platform/admin/system-application-users.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/system-application-users.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by C0mmanderCrud** [comment]
I am getting the same user generating 365 alerts in my orginisation

**Comment by jimholtz** [comment]
@crh03 
Thanks for the feedback. This has been added to the content.
