### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by RickardNo** [MicrosoftDocs/power-platform#5]
The link to the programmatic interface (https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/data-export-service.md) gives a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@RickardNo 
Thanks for bringing this to our attention. The link has been fixed.
