### ISSUE TITLE
Exporting Power Virtual Agent

### ISSUE THREAD

**Issue by AutomationTeamVA** [MicrosoftDocs/power-platform#50]
If a user creates a bot in their environment and then we need to transfer it to another environment, what would the process be?
If a user is deleted will their bot data be wiped?

Clarification on how to handle any possible migration of bots, their data, their topics, and their analytics. 

Thank you!

**Comment by iaanw** [comment]
We're working on this feature and updated documentation. I'll reply back here once it's published.

**Comment by iaanw** [comment]
This content is now live! https://docs.microsoft.com/power-virtual-agents/authoring-export-import-bots
