### ISSUE TITLE
Please remove the link to the Discover the URL for your organization using the Web API topic

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/power-platform#500]
This link is included here:

> More information: Direct sign in and [Discover the URL for your organization using the Web API](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/discover-url-organization-web-api)

But that topic doesn't contain the list of regional data centers that an older version did:  https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/gg328127(v=crm.8)?redirectedfrom=MSDN

Also that is a list of regional discovery services, which have been deprecated. That list has no value for developers using the discovery service and that topic isn't the right place to have a reference list. It should be in the admin guide.
Also, the content today here is not satisfactory: https://docs.microsoft.com/en-us/power-platform/admin/new-datacenter-regions
There should be a simple table with the current list of regions rather than these copy/paste announcements of new regions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029aa7d3-e3e1-f99a-3f71-e11e998cb543
* Version Independent ID: 3d87af00-dcfd-697c-87df-3990a4cc8027
* Content: [Geo to geo migrations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/geo-to-geo-migrations)
* Content Source: [power-platform/admin/geo-to-geo-migrations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/geo-to-geo-migrations.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@JimDaly 
Thanks for the feedback. Changes made.
