### ISSUE TITLE
Support of DES for Microsoft Dataverse environment

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/power-platform#501]
If the Data Export Service is only supported for the environments with D365 customer engagement apps installed and not for pure Microsoft Dataverse environment at the moment, it would be great if that fact is mentioned in the document specifically until it is supported for all Dataverse environments.
E.g. At the moment, you cannot install the Data Export Service in the Microsoft Dataverse environments without customer engagement apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by sabinn-msft** [comment]
DES is an add-on for CE. WE also cover this under pre-requisites - https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#prerequisites-for-using-

For exporting Dataverse table data to data lake, we recommend 'Export to data lake' - 
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake#:~:text=Transporting%20an%20Export%20to%20Data%20Lake%20configuration%20across,to%20Data%20Lake%20configuration.%20...%204%20See%20also
