### ISSUE TITLE
IE deprecation link forbidden

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/power-platform#502]
The Link "FAQ: Internet Explorer 11 deprecation for Dynamics 365 and Microsoft Power Platform Products" https://aka.ms/IEsupportDeprecationBAG returns a 403 error after logging in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and customer engagement apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/important-changes-coming.md)
* Service: **power-platform**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by jimholtz** [comment]
@darshSWL 
Please check your credentials. I tested and was able to sign in.

**Comment by darshSWL** [comment]
Why does this information require a login at all?
My credentials are okay, the login is successful, but I don't have access to this resource.
