### ISSUE TITLE
Can "Dataverse for Teams" can have CMK enabled, Documentation not clear.

### ISSUE THREAD

**Issue by iiu-dk** [MicrosoftDocs/power-platform#504]
Due to new naming, it is not super clear if "Dataverse for Teams" can have CMK enabled in documentation.
Feedback given by @paulliew indicate that "Dataverse for Teams" cannot be enabled for CMK
Please verify and update documentation to make it clear if "Dataverse for Teams" can by CMK enabled or not.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c43b88-32f5-49ab-d715-bfcf75c9ba3e
* Version Independent ID: 70179da7-e3b6-8775-97cc-361990404677
* Content: [Manage the encryption key - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-encryption-key)
* Content Source: [power-platform/admin/manage-encryption-key.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-encryption-key.md)
* Service: **power-platform**
* GitHub Login: @jayasreekumar
* Microsoft Alias: **jkumar**

**Comment by jimholtz** [comment]
@iiu-dk 
Sorry for the delayed response. This is likely no longer an issue. Please reopen if that is not the case.
