### ISSUE TITLE
[Question] How to support manual authentication in Power Virtual Agent to get token to different resources.

### ISSUE THREAD

**Issue by adashen** [MicrosoftDocs/power-platform#505]
[Enter feedback here]
From https://docs.microsoft.com/en-us/power-virtual-agents/configuration-end-user-authentication
We could add the manual authentication to the node. But the question is the AAD app has multiple permissions to different resources, graph, azure management. How to configure to get the desired token to specified resouce?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f11f0ed-eec4-dfbc-4498-87690a569091
* Version Independent ID: 7c3ba7b6-5874-2cbb-0aef-aef24489d0b0
* Content: [Configure user authentication - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-end-user-authentication)
* Content Source: [power-virtual-agents/configuration-end-user-authentication.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/configuration-end-user-authentication.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for your questions! The best place for product troubleshooting/issues/questions - is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
