### ISSUE TITLE
Docs needs to be updated to correctly describe environment with "app passes" allocated

### ISSUE THREAD

**Issue by adner** [MicrosoftDocs/power-platform#506]
The documentation describes scenarios where users are disabled from the environment, for example when removed from the security group associated with the environment or if the users Dataverse license is removed. With the new license model users without individial licenses can have access to the environment using "Power Apps Per App" licenses, by allocating "app passes" to an environment. It is my understanding that in an environment where app passes are allocated, users are no longer disabled - even if the users Dataverse license is removed. The docs could benefit from e clear description on how the behavior of an environment with app passes allocted differs from an environment with no pass passes allocated, with regard to disabling of users, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/control-user-access)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* GitHub Login: @jayasreekumar
* Microsoft Alias: **jkumar**

**Comment by paulliew** [comment]
we need to get Austin Laugesen to help with the doc

**Comment by jimholtz** [comment]
@adner 
Sorry for the delayed response. Thanks for the feedback. We'll make changes in future document revisions to clarify this.
