### ISSUE TITLE
Conflict in documentation pages

### ISSUE THREAD

**Issue by noorrocks** [MicrosoftDocs/power-platform#509]
[Enter feedback here]

"Secure access enabled by default, **no ability** to generate secrets to enable secure access" is mentioned in https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/requirements-licensing-subscriptions.md document but when we clicked on the linked article, it says it can be done.

"You can configure advanced web channel security options with the Power Virtual Agents app in Microsoft Teams."

https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/teams/configure-web-security-teams.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba9447d-2627-7e6f-968d-93b9915c4e1c
* Version Independent ID: 06da4457-9766-4492-e9cb-89a6d7d072d3
* Content: [Get access to Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/requirements-licensing-subscriptions)
* Content Source: [power-virtual-agents/requirements-licensing-subscriptions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/requirements-licensing-subscriptions.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
You can configure security options, but you can't generate secrets if you only have a Teams license. To generate secrets, you need to have a full Power Virtual Agents license. I've updated the docs to hopefully make this a bit clearer! It should go live in the next day or so.

**Comment by noorrocks** [comment]
Thanks a lot
