### ISSUE TITLE
Power Virtual Agent Import Entities

### ISSUE THREAD

**Issue by AutomationTeamVA** [MicrosoftDocs/power-platform#51]
Currently there is a way to use an existing FAQ page and pull Question and Answers, will that being coming for entities as well? Will there be an option to pull from LUIS libraries?

Or in this case is there going to be guidance released on when there will be use case to import LUIS as a skill versus creating your own entities within VA?

**Comment by iaanw** [comment]
I'd suggest you open a thread at aka.ms/pvaideas to discuss this with our engineers and PMs - they'll be able to talk more about future plans and how to get what you're looking for into the product.
