### ISSUE TITLE
Confusing explanation, might want to reformat

### ISSUE THREAD

**Issue by alexshte** [MicrosoftDocs/power-platform#511]
It seems you intended to have two paragraphs one on inbound the other on outbound.  Currently each paragraph contains both statements which makes it hard to read/understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21c5d280-6884-6b8a-c6dd-cc77d988fa14
* Version Independent ID: 7a0cfc73-8ade-01b1-f364-4fcb4d13f7cd
* Content: [Enable cross-tenant isolation - Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/adoption/tenant-isolation?source=docs)
* Content Source: [power-platform/guidance/adoption/tenant-isolation.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/adoption/tenant-isolation.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Content has been amended now.
