### ISSUE TITLE
Unclear minimum license requirements for Powerapps Portals

### ISSUE THREAD

**Issue by NathanSushi** [MicrosoftDocs/power-platform#512]
It is not clear in the article whether are not you have to buy the Page Views add-on if all content that is hosted in the portal is behind a login-page (and not available anonymously).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#what-is-the-difference-between-power-apps-portals-and-dynamics-365-portals-in-terms-of-licensing)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@NathanSushi 
Sorry for the delayed response. Licensing content is frequently being rewritten. Please reopen if this is still an issue.
