### ISSUE TITLE
Step three is confusing

### ISSUE THREAD

**Issue by staehelir** [MicrosoftDocs/power-platform#513]
Step three is confusing. I think to use per app plan, the Auto assign per app passes must set to yes. But the screenshot show, that is disabled and in the description it says, "Follow these steps to turn **off**...".
Please clarify step three so it is clear, what you need to do, to use per app plans. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1f9ece-05b6-907c-9d52-5a19f5bf9872
* Version Independent ID: 9eaed30a-4c07-ef03-e3b4-d3db9989a760
* Content: [About Power Apps per app plans - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-powerapps-perapp)
* Content Source: [power-platform/admin/about-powerapps-perapp.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/about-powerapps-perapp.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@staehelir 
Sorry for the delayed response and thanks for the suggestion. We've updated the topic.
