### ISSUE TITLE
Power Platform COE

### ISSUE THREAD

**Issue by jpanderson91** [MicrosoftDocs/power-platform#516]
The CreateCoETemplateLibaryDocLibraryinSP.zip download from the powerplatform COE nurture components section is missing xml files. This gives an error when attempting to import into the solutions page of power apps. 

![sharepoint_library_error](https://user-images.githubusercontent.com/74209806/101920711-bea96000-3b91-11eb-9ec4-86678ad7cfcb.PNG)
![sharepoint_library_error_missing_xml](https://user-images.githubusercontent.com/74209806/101920818-e26ca600-3b91-11eb-9c9a-30e87bc3ad5a.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9308772f-10e4-9cd6-a94b-d92fad005365
* Version Independent ID: f90c550d-e8f7-b563-4a04-a1a3b894bc79
* Content: [Feedback and support - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support)
* Content Source: [power-platform/guidance/coe/feedback-support.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/feedback-support.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

this file is not a solution, but a standalone flow. You will have to import it from flow.microsoft.com > My Flows > Import and not use the Solutions import. We'll make that clearer in the documentation, thanks for pointing that out!
