### ISSUE TITLE
ToolIcons.zip is missing from the download

### ISSUE THREAD

**Issue by morismm99** [MicrosoftDocs/power-platform#518]
The ToolIcons.zip is missing from the initial download. Looks like it was not included in the CoEStarterKit zip folder.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c74207b-a220-3f22-4f0a-1505c8848770
* Version Independent ID: 49a8f967-a8a6-5500-dbd9-256d568d73f9
* Content: [Set up Innovation Backlog components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-innovationbacklog)
* Content Source: [power-platform/guidance/coe/setup-innovationbacklog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-innovationbacklog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Apologies, we've uploaded it now - you can get it directly from here https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/ToolIcons.zip now

**Comment by morismm99** [comment]
Perfect!

Thanks!

Moris Montejo

On Dec 15, 2020, at 9:26 AM, Manuela Pichler <notifications@github.com> wrote:

﻿

Closed #518<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpower-platform%2Fissues%2F518&data=04%7C01%7C%7C0e7ace2402744f41a6a208d8a10dd264%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637436428012549483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vUtJ8dxXOiUNmh1p5%2FNVoZmu3LL6RIvrWREZ5cc8ZUo%3D&reserved=0>.
