### ISSUE TITLE
Power Virtual Agent Appearance Customization

### ISSUE THREAD

**Issue by AutomationTeamVA** [MicrosoftDocs/power-platform#52]
Looking through the documentation I do see that it is noted Bot appearance and [customization ](https://docs.microsoft.com/en-us/power-platform-release-plan/2019wave2/power-virtual-agents/customize-canvas-themes) was released on December 2 but I can't seem to find documentation. I have also looked within the dashboard but I cannot see a way to change the icon or color of the bot.

**Comment by iaanw** [comment]
It's available through Microsoft Bot Framework: https://docs.microsoft.com/en-us/power-virtual-agents/extend-custom-canvas-connect 

This does require some dev coding to get the two to interact. I'm closing this for now but feel free to open a thread at aka.ms/pvaideas if you want to discuss the customization options further etc.
