### ISSUE TITLE
Insufficient whitelisted IPs required to connect Dynamics

### ISSUE THREAD

**Issue by YoshikaSuzuki** [MicrosoftDocs/power-platform#520]
[Enter feedback here]
The following URLs listed on the following pages are not listed on this page's whitelist

Internet accessible URLs required for connectivity to Microsoft Dynamics CRM Online
https://support.microsoft.com/en-us/help/2655102/internet-accessible-urls-required-for-connectivity-to-microsoft-dynami

ex) japan reasion
https://mem.gfx.ms
https://www.d365ccafpi.com/

Please add the URL of the missing whitelist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215ab00d-9ad0-1e91-184c-218dd64a7d73
* Version Independent ID: 337562d4-dab0-ccf9-b272-5de16e88476a
* Content: [Requirements/supported configurations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/online-requirements#ip-addresses-and-urls)
* Content Source: [power-platform/admin/online-requirements.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/online-requirements.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@YoshikaSuzuki 
Thanks for bringing this to our attention. The URLs have been added.

**Comment by YoshikaSuzuki** [comment]
@jimholtz  Thank you for quick fix.
Need to be added not only in Japan but also in other regions
