### ISSUE TITLE
Improve installation instructions of Innovation Backlog solution

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#521]
Just few small suggestions to improve instructions

Innovation backlog seems to have 4 connections, so would be good to have screenshot updated to match which connections needs configuration even that those are mentioned in the text

![image](https://user-images.githubusercontent.com/8307644/102375553-53b1bc00-3fcb-11eb-9a30-186be04a63ae.png)

Also include comment about **InnovationBacklogAppURL** environment variable that it cannot be set during import as app url can be get after import

![image](https://user-images.githubusercontent.com/8307644/102375889-b60abc80-3fcb-11eb-82f4-7c0edddf622f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c74207b-a220-3f22-4f0a-1505c8848770
* Version Independent ID: 49a8f967-a8a6-5500-dbd9-256d568d73f9
* Content: [Set up Innovation Backlog components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-innovationbacklog)
* Content Source: [power-platform/guidance/coe/setup-innovationbacklog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-innovationbacklog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
We have updated the installation instructions now. Thanks for your feedback!
