### ISSUE TITLE
I don't see "Open in Bot Framework" when in any of my 4 bots on the topic page in PVA

### ISSUE THREAD

**Issue by DS2019** [MicrosoftDocs/power-platform#526]
I've been following through this document: https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer?WT.mc_id=AZ-MVP-5003365#composer-features-not-supported-with-power-virtual-agents and I wanted to test accessing Bot Framework Composer from within Power Virtual Agents. 
1) I have 4 bots, and have tested with them all - I have composer (1.3) installed on my machine. Closed or open made no diference.
2) I go to the topics tab for any of the bots
3) in the screenshot in the documentation, it shows "Open in Bot Framework (preview) across from "suggest topics"
4) I do not have Open in Bot Framework (Preview)

Is there something I need to do for this to show up for me? 
![Open in Bot Framework](https://user-images.githubusercontent.com/44073678/102552308-d7c07e00-4075-11eb-8506-6d6a9a8b43bd.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc0b9a3-1ec0-d1df-1b5d-2ae1ca2d2f20
* Version Independent ID: aca14f37-8e54-2eca-3c05-03ce50189010
* Content: [Use Bot Framework Composer with chatbots - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer?WT.mc_id=AZ-MVP-5003365#composer-features-not-supported-with-power-virtual-agents)
* Content Source: [power-virtual-agents/advanced-bot-framework-composer.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-bot-framework-composer.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by DS2019** [comment]
Any ideas? Thanks!

**Comment by iaanw** [comment]
Thanks for your questions! The best place for product troubleshooting - is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
