### ISSUE TITLE
Documentation referencing deprecated PowerShell option, please update 

### ISSUE THREAD

**Issue by iiu-dk** [MicrosoftDocs/power-platform#527]
This page refs Microsoft.Xrm.OnlineManagementAPI for PowerShell option to set encryption key, this is deprecated and replaced with https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/?view=pa-ps-latest 
Please go through all documentation and update reference
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c43b88-32f5-49ab-d715-bfcf75c9ba3e
* Version Independent ID: 70179da7-e3b6-8775-97cc-361990404677
* Content: [Manage the encryption key - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-encryption-key)
* Content Source: [power-platform/admin/manage-encryption-key.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-encryption-key.md)
* Service: **power-platform**
* GitHub Login: @jayasreekumar
* Microsoft Alias: **jkumar**

**Comment by Mattp123** [comment]
@iiu-dk - Sorry for the delay. This has been fixed to point to the new Power Platform admin module. Closing issue.
