### ISSUE TITLE
Recommend updating the "where is my data?" link

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/power-platform#529]
Link currently points to https://o365datacentermap.azurewebsites.net, which advises users to use other resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6e0ce6-b90d-ae6a-d9bc-89b693fbe4e3
* Version Independent ID: 46b8668e-b83f-5681-0d37-88fb08fbdcd5
* Content: [Datacenter regions - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/new-datacenter-regions)
* Content Source: [power-platform/admin/new-datacenter-regions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/new-datacenter-regions.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@joshtransient 
The content on that page looks to be valid as it applies to Dynamics 365 services.
