### ISSUE TITLE
Per User

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/power-platform#53]
So if I design a PowerApp using an SQL On-Premises Gateway connector (really, this is considered Premium instead of Standard?!?) with my fancy new per app or per user plan, does the end users of my PowerApp also need to have a per app or per user plan? Or can they use the app with their Office 365 E5 subscription? 
This is not at all clear in the documentation above - and it really needs to be...

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform Admin center](https://docs.microsoft.com/en-au/power-platform/admin/powerapps-flow-licensing-faq)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by JMTeamway** [comment]
Hi @HairyDrumroll ,
I have the same question with no answer so far. If you got news, let me know.

Only intersting clue I found may indicates that GUEST users of Premium Power Apps may need per app ou per user plan.
It seems to be described this way on this Microsoft document :
https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/share-app#what-license-must-be-assigned-to-my-guest-so-they-can-run-an-app-shared-with-them

It would still certainly by risky to guass a final answer based on this ...

**Comment by JMTeamway** [comment]
Seems I found clear answer, it depends on the execution context of the flow.
If it is an automated flow, it runs only on one context, only one per app or per user licence.
If it is a manually trigerred flow for example, it runs on the user context, the user needs per app or per user licence.
https://powerusers.microsoft.com/t5/Connecting-To-Data/HTTP-Request-for-Graph-Connector-Moving-to-Premium-Licence/m-p/322712#M5940
