### ISSUE TITLE
errors in PowerShell script. instructions no longer work

### ISSUE THREAD

**Issue by bpasham** [MicrosoftDocs/power-platform#530]
Can you update the guide and the script so that it works.? or provide underlying concepts so we can figure things out.

`New-CrmServicePrincipal.ps1 : A parameter cannot be found that matches parameter name 
'TenantId'.
At line:1 char:1
+ .\New-CrmServicePrincipal.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-CrmServicePrincipal.ps1], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-CrmServicePrincipal.ps1```

**Comment by jimholtz** [comment]
@bpasham 
Sorry for the delayed response. If this is still and issue, please reopen.
