### ISSUE TITLE
Use XML web resources as language resources

### ISSUE THREAD

**Issue by mathiasbl** [MicrosoftDocs/power-platform#531]
Question about the example code provided under the '[Use XML web resources as language resources](https://docs.microsoft.com/en-us/power-platform/alm/create-solutions-support-multiple-languages#use-xml-web-resources-as-language-resources)' section.

This looks very expensive to do on every plugin invoke.

1. Download resx webresources (even tho it's local, these files could potentially get very large.)
2. Parse resx webresource

Is this really the way Microsoft advises to do multi language in plugins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8985926-ff0d-8c03-2fda-089cf6e7a881
* Version Independent ID: e87feff3-266f-dc8f-590a-7aa0c35b35c1
* Content: [Create solutions that support multiple languages (Microsoft Dataverse) - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/create-solutions-support-multiple-languages)
* Content Source: [power-platform/alm/create-solutions-support-multiple-languages.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/create-solutions-support-multiple-languages.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
This was written a long time ago and it has been carried forward. It isn't a great solution, but it is a solution.
Today, we even have [RESX web resources](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/resx-web-resources) which would be better than the XML Web resources used in the example.
Other options include having an entity where the localized strings could be retrieved, but then you would require some post install step to populate the entity data. The advantage that Web Resources provide is that they can be installed with the solution that contains your plug-in.

Tell me: How would you like it to work?

**Comment by mathiasbl** [comment]
The addition of RESX web resources is great.
However, retrieving this web resource and parsing it during every plugin invoke seems like a performance hit to me.

It would be nice if we would have an equivalent to the client API Xrm.Utility.getResourceString in plugins. Which MS can optimize.

**Comment by JimDaly** [comment]
Thanks. We are looking at how this can be done in a more efficient and intuitive way.
