### ISSUE TITLE
Domain Name is not used when creating an environment

### ISSUE THREAD

**Issue by oarbaji** [MicrosoftDocs/power-platform#532]
When I use the Create Environment task and pass a DomainName it is not used when excecutig. All other fields are used like DisplayName.  Can you please fix?

![image](https://user-images.githubusercontent.com/74710773/103295376-15b58e80-49f4-11eb-9edf-81261c79a099.png)

**Comment by jimholtz** [comment]
@oarbaji 
Can you provide the article where you saw this documented?
