### ISSUE TITLE
No information about how to filter repeating records from 1:N relationships

### ISSUE THREAD

**Issue by stevenfayers** [MicrosoftDocs/power-platform#533]
There is no information about filtering 1:N records in the templates. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae661c5-51cd-2050-3dcf-36a48966130d
* Version Independent ID: 20ef03e9-52a1-8c24-1868-9bbbd5b95cc9
* Content: [Use Word templates to create standardized documents - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/using-word-templates-dynamics-365)
* Content Source: [power-platform/admin/using-word-templates-dynamics-365.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/using-word-templates-dynamics-365.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@stevenfayers 
Thanks for the feedback. We'll consider adding this coverage when the content goes through it's next review.

**Comment by samadane** [comment]
@jimholtz did filtering get added to word templates?
