### ISSUE TITLE
Unable to configure Audit log connector

### ISSUE THREAD

**Issue by jazizka** [MicrosoftDocs/power-platform#534]
Hi guys,
we are trying to deploy CoE Starter Kit to our environment. Unfortunately, we are unable to get through audit log connections. We tried both options the Azure AD app registration and the basic authentication.

Issues facing with Azure App: 
We follow the deployment process described [here](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog). Everything goes fine until we hit the "Test Operation" button at the "TEST" tab of the connector.

We always get following error:
**Headers**
`{
  "cache-control": "no-cache",
  "content-length": "71",
  "content-type": "application/json; charset=utf-8",
  "date": "Tue, 05 Jan 2021 09:22:33 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "x-aspnet-version": "4.0.30319",
  "x-ms-apihub-cached-response": "false",
  "x-powered-by": "ASP.NET"
}`

**Body**
`{
  "error": {
    "code": "AF20023",
    "message": "The subscription was disabled."
  }
}`

Not sure if it might be related but we also see this in the "Schema validation" section:
`Property "" type mismatch, Expected: "array", Actual: "object".`

The question is which subscription was disabled and how to enable it. MS case did not help...

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
For issues with the CoE Starter Kit itself (and not with the documentation), could you please raise them through https://github.com/microsoft/powerapps-tools/issues where they'll be assigned to the appropriate team. 

From looking at the error message, have you completed this step to start a subscription, before trying to pull content from the Audit Log?
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content

When was the Audit Log enabled in your tenant? Often it can take up to 24hrs to be active, and for the API to works.

**Comment by manuelap-msft** [comment]
(closing here, please re-raise via https://github.com/microsoft/powerapps-tools/issues if you continue to see issues)
