### ISSUE TITLE
Configuration migration tool - Export/Import product catalog

### ISSUE THREAD

**Issue by mathiasbl** [MicrosoftDocs/power-platform#535]
According to this document you should be able to import active/retired products however every active product fails to import with following message:
14:57 Insert Record - Result: False - Entity: product - Insert to product with Record Id 32053f45-434f-eb11-a812-000d3a3a10ea - PrimaryId Field productid and PrimaryName Field name - FAILED with Error : 1 is not a valid status code for state code ProductState.Draft on product with Id 32053f45-434f-eb11-a812-000d3a3a10ea

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92223bea-a1d0-21a4-16a2-dd4c41ee61ec
* Version Independent ID: 65752571-4b87-948c-701a-65c4bf2e63a3
* Content: [Manage product catalog configuration - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-product-catalog-configuration)
* Content Source: [power-platform/admin/manage-product-catalog-configuration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-product-catalog-configuration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by RedsGT** [comment]
Per https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/product?view=dynamics-ce-odata-9#properties this seem like an issue with the underlying data, not the tool.  You should file a support case.

**Comment by mathiasbl** [comment]
Only including statecode, excluding statuscode, fixed this problem.
