### ISSUE TITLE
Include a YAML code block for each task of the Power Platform Build Tools extension

### ISSUE THREAD

**Issue by rpothin** [MicrosoftDocs/power-platform#536]
I think it could be great to have a YAML code block for each task of the Power Platform Build Tools extension directly integrated in the documentation page so people could easily copy-paste it and directly start building their YAML pipeline (without using the assistant in Azure DevOps).

Also, it can help in some situations to understand what the task exactly expects as input.

If it is ok for you, I can try to work on a proposition and submit it as a pull request later this month.

Thank you for your work and happy new year!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tool-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by mikkelsen2000** [comment]
Hey Raphael, sorry for not getting back to you - I would be delighted if you'd contribute with templates here.

Thanks

**Comment by rpothin** [comment]
Hey @mikkelsen2000,

There's no problem, I totally understand you have many things to manage 😊

2 questions:
- Regarding your last comment, why did you close the issue?
- Do you want me to share with you YAML template examples using Power Platform Build Tools tasks?

What I had in mind was more for each task to have 2 tabs (like here: [Az modules / AzureRM modules](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-service-principals?view=azs-2008&tabs=az1%2Caz2&pivots=state-connected#create-a-service-principal-that-uses-client-secret-credentials)) - 1 for Classic UI and 1 for YAML - describing how to configure it.

What do you think regarding this idea?
