### ISSUE TITLE
Link to limitations information in documentation

### ISSUE THREAD

**Issue by marcster** [MicrosoftDocs/power-platform#537]
The link to limitations information does not work.
![image](https://user-images.githubusercontent.com/1025102/103767035-c684e480-5017-11eb-897e-47b9dee4b9e9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Link is now fixed. Thanks for letting us know!
