### ISSUE TITLE
Question around the InnovationBacklogAppURL 

### ISSUE THREAD

**Issue by marcster** [MicrosoftDocs/power-platform#538]
Hi,

When importing the solution, I get the below screen in the screenshot below after step 10 in the instructions
![image](https://user-images.githubusercontent.com/1025102/103777894-74e55580-5029-11eb-8885-922e5f87cc60.png)

So, I entered a random text for the InnovationBacklogAppURL. The solution imports fine but when I go to Step 21 in the instructions, I am unable to update the environment variable as shown in the next screenshot. So, is this a bug? Should there be something in the instructions to tell the user not to ignore that option during the import proces?

![image](https://user-images.githubusercontent.com/1025102/103778309-f89f4200-5029-11eb-9557-2c632c29e543.png)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c74207b-a220-3f22-4f0a-1505c8848770
* Version Independent ID: 49a8f967-a8a6-5500-dbd9-256d568d73f9
* Content: [Set up Innovation Backlog components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-innovationbacklog)
* Content Source: [power-platform/guidance/coe/setup-innovationbacklog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-innovationbacklog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
For issues with the CoE Starter Kit itself (and not with the documentation), could you please raise them through https://github.com/microsoft/powerapps-tools/issues where they'll be assigned to the appropriate team.

**Comment by marcster** [comment]
This is a bit of both as it is an issue with the Coe Starter Kit when I try to install it.
