### ISSUE TITLE
New terminology errors

### ISSUE THREAD

**Issue by MattNC** [MicrosoftDocs/power-platform#539]
It looks like someone did a search and replace on the word “instances” in this article to change it to “environments” – but in this case the word “instances” was correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9c9aae-ceaa-2e78-3752-2770327f49a7
* Version Independent ID: acd2ddc9-6225-92e8-2636-2a02437c3d82
* Content: [Free up storage space - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/free-storage-space)
* Content Source: [power-platform/admin/free-storage-space.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/free-storage-space.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@MattNC 
Thanks for bringing this to our attention. This has been corrected.
