### ISSUE TITLE
Incomplete Script in Deleted records may get reinserted into entity table after a synchronization failure

### ISSUE THREAD

**Issue by saviegas** [MicrosoftDocs/power-platform#540]
[Incomplete Script in Deleted records may get reinserted into entity table after a synchronization failure

https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#deleted-records-may-get-reinserted-into-entity-table-after-a-synchronization-failure

The query that is there and customers use as reference to delete the records fails to run in SQL: 

DELETE  FROM [dbo].[prefix_account] A
WHERE id IN (SELECT CONVERT(uniqueidentifier, recordid) FROM [dbo].[prefix_DeleteLog] DL WHERE DL.entityname =’account’
AND DL.VersionNumber &gt; A.VersionNumber)

I’m able to run it when adding the A and update the &gt;

DELETE  A FROM [dbo].[prefix_account] A
WHERE id IN (SELECT CONVERT(uniqueidentifier, recordid) FROM [dbo].[prefix_DeleteLog] DL WHERE DL.entityname ='account'
AND DL.VersionNumber > A.VersionNumber)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://review.docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database?branch=main&source=docs)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@saviegas 
Thanks for making this change. The content was published to live.
