### ISSUE TITLE
How can I modify the translation of a Japanese article?

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [MicrosoftDocs/power-platform#541]
I would like to edit the article below and send a PR to correct the Japanese translation.
https://docs.microsoft.com/ja-jp/power-platform/admin/powerapps-flow-licensing-faq

But when I click the [Edit] button, I get a 404 error on GitHub.
Which repository is the ja-JP article linked to?

**Comment by jowilco** [comment]
@ShintakuNobuhiro I apologize, but the Japanese repo does not currently support PRs. Would it be possible for you to send me the recommended changes directly (e.g. Word document) and I will work with our translation team to review and implement the changes?

Thank you for helping us make the Japanese content as good as possible for Japanese-speaking users!

**Comment by ShintakuNobuhiro** [comment]
The corrections have been made bold.

https://docs.microsoft.com/ja-jp/power-platform/admin/powerapps-flow-licensing-faq#how-does-the-change-to-power-apps-and-power-automate-use-rights-for-microsoft-365-applications-affect-me-if-i-purchased-the-subscriptions-prior-to-oct-1st-2019-will-my-existing-power-apps-applications-and-power-automate-workflows-continue-to-work

Current: 
> はい、既存のアプリ**ケーション**およびワークフローは、引き続き機能します。 上記のコネクタを 1 つ以上使用して Microsoft 365 で Power Apps または Power Automate を使用しているお客様は、コネクタの再分類が有効になる前に移行期間が与えられな**sy**。 この移行期間は、2020 年 10 月 1 日または現在の Microsoft 365 サブスクリプション期間の満了日のどちらか長い方が適用されます。 移行期間中、顧客はこれらのコネクタを使用して追加のアプリとフローを作成し続けることができます。
> 
> さらに、これらのコネクタを使用している 2019 年 10 月 1 日より前に作成されたアプリとフローは、2024 年 10 月 1 日まで移行期間が延長されます。 この期間中、これらの対象アプリとフローは、再分類されたコネクタ**の**プレミアム コネクタ ライセンス要件から除外されます。
> 
> 延長された移行期間**で**は、上記のコネクタを使用できますが、これらのコネクタでゲートウェイを使用することはできません。 移行前、ゲートウェイはプレミアム機能でしたが、継続してプレミアム機能です。
> 
> 移行期間を延長して Dynamics 365 Connector を使用することをアプリに許可することはできますが、コネクタを使用する機能では Dataverse のキャパシティは提供されません。 Dataverse のキャパシティは、Power Apps および Power Automate ワークフローが Dataverse を使用するための前提条件です。

After change:

> はい、既存のアプリおよびワークフローは、引き続き機能します。 上記のコネクタを 1 つ以上使用して Microsoft 365 で Power Apps または Power Automate を使用しているお客様は、コネクタの再分類が有効になる前に移行期間が与えられ**ます**。 この移行期間は、2020 年 10 月 1 日または現在の Microsoft 365 サブスクリプション期間の満了日のどちらか長い方が適用されます。 移行期間中、顧客はこれらのコネクタを使用して追加のアプリとフローを作成し続けることができます。
> 
> さらに、これらのコネクタを使用している 2019 年 10 月 1 日より前に作成されたアプリとフローは、2024 年 10 月 1 日まで移行期間が延長されます。 この期間中、これらの対象アプリとフローは、再分類されたコネクタ**が**プレミアム コネクタ ライセンス要件から除外されます。
> 
> 延長された移行期間**中**は、上記のコネクタを使用できますが、これらのコネクタでゲートウェイを使用することはできません。 移行前、ゲートウェイはプレミアム機能でしたが、継続してプレミアム機能です。
> 
> 移行期間を延長して Dynamics 365 Connector を使用することをアプリに許可することはできますが、コネクタを使用する機能では Dataverse のキャパシティは提供されません。 Dataverse のキャパシティは、Power Apps および Power Automate ワークフローが Dataverse を使用するための前提条件です。

**Comment by jowilco** [comment]
@ShintakuNobuhiro Thank you for the detailed description of the change. We are working on it now.

**Comment by jowilco** [comment]
@ShintakuNobuhiro Thank you for your patience. We have implemented the changes that you requested. Thank you again for helping us improve the quality for all Japanese customers!
