### ISSUE TITLE
Model-driven Power Apps don't retain their icon in the office.com experience

### ISSUE THREAD

**Issue by TrutzS** [MicrosoftDocs/power-platform#542]
Model-driven Power Apps don't retain their icon in the office.com experience when compared to home.dynamics.com
Only Canvas Power Apps bring over their icon to the office.com experience. The page should explain how a consistent user experience can be achieved in which icons for all apps regardless of Power Apps type can be rendered visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a027bf-62d9-07f6-c15c-fc0e4d5b8686
* Version Independent ID: f88d00be-be73-a187-c287-66f151073abb
* Content: [Quickly navigate with the Microsoft 365 app launcher - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/quickly-navigate-office-365-app-launcher)
* Content Source: [power-platform/admin/quickly-navigate-office-365-app-launcher.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/quickly-navigate-office-365-app-launcher.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@TrutzS 
Thanks for the feedback. I've made the product group aware of this for them to take action on it.
