### ISSUE TITLE
Add details on updating existing templates

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/power-platform#546]
Missing details on the recommended way to update existing templates that are in the system

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae661c5-51cd-2050-3dcf-36a48966130d
* Version Independent ID: 20ef03e9-52a1-8c24-1868-9bbbd5b95cc9
* Content: [Use Word templates to create standardized documents - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/using-word-templates-dynamics-365)
* Content Source: [power-platform/admin/using-word-templates-dynamics-365.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/using-word-templates-dynamics-365.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@danmyhre 
Updating existing templates is currently not supported. You can delete the existing template and upload the new one.

**Comment by danmyhre** [comment]
Should add that to the page then, thanks!

**Comment by ChrisGarty** [comment]
Added a note about updating: https://github.com/MicrosoftDocs/power-platform/pull/576
