### ISSUE TITLE
Incorrect PowerShell cmdlet name

### ISSUE THREAD

**Issue by dragonraelms** [MicrosoftDocs/power-platform#547]
When reviewing the "PowerShell support for Power Apps" documentation. I noticed one of Maker Cmdlets is written as the following SetPowerAppAsSolutionAware. For the command to work without confusing new users it should instead say Set-PowerAppAsSolutionAware

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@dragonraelms 
Thanks for the feedback. We'll make this correction soon.
