### ISSUE TITLE
Need for steps after end of Step 5

### ISSUE THREAD

**Issue by nipaul** [MicrosoftDocs/power-platform#548]
After step 5 "Select Save.", users will need to click on the _Additional Teams settings_ link to open the Dynamics Administration settings and enable the Enhanced Microsoft Teams integration (requires tenant admin permissions) under System Settings > General options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c8b0956-de34-a40f-2ccd-913528e7e328
* Version Independent ID: fe934752-f895-622a-2d12-776320ac43cd
* Content: [Enable Microsoft Teams Integration for model-driven apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/enable-teams-integration)
* Content Source: [power-platform/admin/enable-teams-integration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/enable-teams-integration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@nipaul 
Thanks for the feedback. Updated content with additional steps.
