### ISSUE TITLE
Get visibility into the apps that your organization is building

### ISSUE THREAD

**Issue by davidvansickle** [MicrosoftDocs/power-platform#549]
This utility was not replaced with any simple way to get this information. Not in the CoE, not via PowerShell.  We need this to help us identify connection information related to apps and more.  We should be able to have MUCH more granular control over reporting to Apps, Flows, UI Flows etc. and not have to spend all day digging through dataverse for crumbs.

https://docs.microsoft.com/en-us/power-platform/admin/admin-view-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1707c4e1-2990-c7ac-5133-3014d5b5392f
* Version Independent ID: 961e2599-82ac-ed6c-2f11-cfe4809b988e
* Content: [Download a list of apps created in your environments - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/admin-view-apps)
* Content Source: [power-platform/admin/admin-view-apps.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/admin-view-apps.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@davidvansickle 
Thanks for your feedback. Please visit https://ideas.powerapps.com and enter your suggestion there.
