### ISSUE TITLE
Creating topic from SPO content

### ISSUE THREAD

**Issue by shajumohamed** [MicrosoftDocs/power-platform#55]
Suggested topics for Virtual Agents seems to support un-authenticated websites only. How can I add authenticated pages such as SPO content ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78f1747-04bf-3bb7-c1e1-9025710e022f
* Version Independent ID: 1da1f8d8-f0e5-64e1-7503-39973b0f38e2
* Content: [Get Power Virtual Agents topic suggestions from support pages - Power Virtual Agents](https://docs.microsoft.com/en-gb/power-virtual-agents/advanced-create-topics-from-web)
* Content Source: [power-virtual-agents/advanced-create-topics-from-web.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/advanced-create-topics-from-web.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by snakebte75** [comment]
+1 For this request. This looks like it would be a great tool, but I am not going to take the time to migrate my content to an unsecured web server. I know this is still an early product as it isn't even in the O365 menu yet, but I'm surprised it doesn't already have the ability to pull from my SharePoint sites.

**Comment by renatoromao** [comment]
Please, vote here: https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Add-SharePoint-lists-like-Suggested-topics-Power-Virtual-Agents/idi-p/482951

Post related: https://powerusers.microsoft.com/t5/Power-Virtual-Agents-Forum/Suggest-Topics-via-Tables/m-p/482936/highlight/false#M806
