### ISSUE TITLE
Whole list of Power Apps and Power Automate actions that counts towars API request

### ISSUE THREAD

**Issue by dimazoin** [MicrosoftDocs/power-platform#551]
Could you please provide whole list of Power Apps and Power Automate actions that counts towars API request? There are some rumors that launching application, call any kind of connector, each action inside Power Automate count as API request and affects user's limits that we have.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#microsoft-power-platform-requests-allocations-based-on-licenses)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@dimazoin 
Sorry for the delayed response. Please see: 
https://docs.microsoft.com/en-us/power-automate/limits-and-config#daily-limits
