### ISSUE TITLE
Most of the Reports don't work

### ISSUE THREAD

**Issue by PeterHale53** [MicrosoftDocs/power-platform#552]
The last are probably the most important and both produce empty reports (which I know isn't true). Only other report looked at was the entity usage report and it at least had some data in it - which appeared credible.

Furthermore, I get the customary email saying your tenant is using non-compliant team licence and to go the report to find out who,what where etc. Produces a blank report. 

And to top it off, the licencing document is unreadable, too complicated, too many if and buts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c99626-6458-46b4-f099-ce10c30890c7
* Version Independent ID: d3766ded-359b-160c-d7f5-a7e6ffa103d6
* Content: [Microsoft Dataverse analytics - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service#download-reports)
* Content Source: [power-platform/admin/analytics-common-data-service.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/analytics-common-data-service.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@PeterHale53 
Sorry for the delayed response. If this is still and issue, please contact support: 
https://powerapps.microsoft.com/support/
