### ISSUE TITLE
Out of date screenshots of the PowerBi report

### ISSUE THREAD

**Issue by mwolfaardt** [MicrosoftDocs/power-platform#553]
I'm not sure if it is just me, but is the screenshots of the Power BI report out of date with the latest report release?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c365c412-6317-0eb4-b7a1-0a5cc84b1cbd
* Version Independent ID: 9e39031d-66dd-bf29-1b5c-a93608badc60
* Content: [Set up the Power BI dashboard - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi)
* Content Source: [power-platform/guidance/coe/setup-powerbi.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-powerbi.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The screenshots are up to date. Screenshots are taken from a sample of the report that's published as an app. If you are working in Power BI Desktop or have published the report to a workspace, your navigation and view will be different. (see https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi) 

What are you seeing?

**Comment by mwolfaardt** [comment]
Thanks for the prompt response, I'm trying to embed Power Apps into the Power BI report as per https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi the setup guide. What the guide shows is :
![image](https://user-images.githubusercontent.com/11614412/104615719-2c194680-5692-11eb-8567-a3df09e44bb8.png)

and in my Power Bi Desktop, I see 
![image](https://user-images.githubusercontent.com/11614412/104615805-405d4380-5692-11eb-85e0-d2605f643b29.png)

This is both Page 19 of the report, I could not find any reference to AppDetails tab as well.

**Comment by manuelap-msft** [comment]
Thanks for sharing - it's possible that the page numbers on the report change as we add new pages or shuffle things about. We wouldn't always be able to update the docs to match the page number. You will have to scroll to the right to find the App Detail page, its towards the end of the list.
