### ISSUE TITLE
10 unit minimum for Tier 2 and 3 Portal Authenticated licenses

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/power-platform#554]
I've been informed that there's a 10 unit minimum on the Tier 2 and 3 Portal Authenticated license packs.

It would be good to have this in the documentation, as currently it reads like you can get discounts from 1000 and 5000 logins/month, but it's actually 10,000 and 50,000.

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-nz/power-platform/admin/powerapps-flow-licensing-faq#portals)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by Craig-Humphrey** [comment]
Actually, sounds like it's more complex than that.

Both Tier 2 and 3 are sold in 100 login blocks, but have a minimum of 10 and 50 respectively (which gives the US$1000 for 1000 logins and US$3500 for 5000 logins, prices respectively).

This is totally not clear in the documentation, which reads like you have to buy Tier 2 and 3 in blocks of 1000 and 5000 logins respectively.

**Comment by jimholtz** [comment]
@Craig-Humphrey 
Thanks for the feedback. Taking to internal thread.
