### ISSUE TITLE
Typo on step 3.7 of the article.

### ISSUE THREAD

**Issue by v-iliva** [MicrosoftDocs/power-platform#555]
[Enter feedback here]

Hello, 

On this section: https://docs.microsoft.com/en-us/power-platform/admin/connect-gmail-oauth2#step-3-configure-oauth-consent

Step 7:

Authorized redirect URIs

There is a typo on the environment URL:

Current value:
Your environment's URL with "/_grid/cmds?dlg_gmailoauth.aspx"

Expected:
Your environment's URL with "/_grid/cmds/dlg_gmailoauth.aspx"

The URL example and the screenshot is correct but this value is wrong and confuses the customer and they submit tickets for troubleshooting. Please correct this.

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ab446-3f0a-aabb-82d5-b57938d12def
* Version Independent ID: b7159cad-3458-6cbf-e915-fe77e1f2b372
* Content: [Connect Gmail accounts using OAuth 2.0 - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/connect-gmail-oauth2)
* Content Source: [power-platform/admin/connect-gmail-oauth2.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/connect-gmail-oauth2.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@v-iliva 
Thanks for bringing this to my attention. The content has been corrected.
