### ISSUE TITLE
Submit feedback link for this product is too generic

### ISSUE THREAD

**Issue by amervitz** [MicrosoftDocs/power-platform#556]
Please update this link to one that is more relevant:

![image](https://user-images.githubusercontent.com/10599498/104797053-ed15ee80-5780-11eb-950b-d0f82752be85.png)

It currently links to https://powerusers.microsoft.com/. This is not a helpful destination to get sent to and requires additional exploring to find where to submit feedback. I'm guessing the intended location is https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas. However, none of the feedback/ideas on this site for the configuration migration tool have been responded to, and they've been there for several years, which isn't a good indication that submitting feedback will even get looked at by the team in Microsoft responsible for this tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaafdc52-4a26-ecd5-83f8-25373eb053f5
* Version Independent ID: ada1a415-a53f-21fb-948a-79245c3c68f4
* Content: [Move configuration data across organizations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-configuration-data)
* Content Source: [power-platform/admin/manage-configuration-data.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-configuration-data.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by KendalBond007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://flow.microsoft.com/support/. Closing this issue.
