### ISSUE TITLE
"Block trial licenses commands" section - AllowedConsentPlans types, relevance to Community Plan

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/power-platform#558]
[This doc on the Power Apps Community Plan](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan#can-i-reset-my-developer-environment), that links to this, indicates that "consent plans" of type "Internal" include the "Power Apps Community Plan" as well as trials. Could this be clarified/included on this page? 

I've also noticed there is a "Viral" consent plan type in my tenant. This seems to be explained by [this forum post](https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/Self-service-licenses/m-p/451537/highlight/true#M1911), but seems to have dropped of the actual docs.

> The allowed consent plans cmdlets can be used to add or remove access to a particular type of consent plan from a tenant. “Internal” consent plans are either trial licenses or community plans that users can sign themselves up for via Power Apps/Power Automate portals. “Viral” consent plans are trial licenses that users can sign themselves up for via https://signup.microsoft.com or admins can assign to users via Azure Active Directory (Azure AD) or the Office 365 admin portal. By default all types of consent plans are allowed in a tenant. A common use case for these cmdlets is if a tenant admin wants to block users within their tenant from the ability to assign themselves trial licenses but retain the ability to assign trial licenses on behalf of users. This can be accomplished by using the Remove-AllowedConsentPlans -Types “Internal” command as well as disabling the setting AllowAdHocSubscriptions in Azure AD. It is important to note that when using Remove-AllowedConsentPlans all existing plans of the specified type will be removed from all users in the tenant and will not be recoverable. In addition, it will block all further assignment of plans of that type. If, at a later time, the tenant admin wishes to re-enable plans of that type they can use Add-AllowedConsentPlans. If they want to view the current state of allowed consent plans they can use Get-AllowedConsentPlans.

Finally, this section really could use some paragraphs to improve readabilty..

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#block-trial-licenses-commands)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@fowl2 
Sorry for the delayed response and thanks for your suggestions. We've modified the content and added "Viral" to the explanation.
