### ISSUE TITLE
Microsoft Power Platform Build Tools tasks - Create Environment error with Regions

### ISSUE THREAD

**Issue by BillPOwens** [MicrosoftDocs/power-platform#559]
I am trying to create an environment and I am getting an error with the region. None work for me
##[error]The region 'unitedstates' is invalid. Please enter the valid region or select from the picklist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tool-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by FH-Inway** [comment]
I'm getting the same issue, in my case it is region 'europe', but I also tried 'unitedstates', same result.
