### ISSUE TITLE
add groups as users

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/power-platform#56]
instead of adding 1 by 1 user, it would be nice to add users in a security group. I just had to manually imput over 200 users to an environment because we are on a time crunch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6bf79b0-5e31-ebc4-2397-c7274967dd8f
* Version Independent ID: 9b67d821-bfc9-eb04-c10d-31187c655984
* Content: [Manage environments in the Power Apps Admin center - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/environments-administration?fbclid=IwAR1alAOXAiHKQ52cv0ufrDuby-rmlx5xQTxXXlp9NTzyvmMccOHq_roQcSQ)
* Content Source: [power-platform/admin/environments-administration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/environments-administration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Ballzer0 
Does this content provide what you need?
https://docs.microsoft.com/en-us/power-platform/admin/create-users-assign-online-security-roles#enable-or-disable-users

https://docs.microsoft.com/en-us/office365/enterprise/add-several-users-at-the-same-time?redirectSourcePath=%252farticle%252fAdd-several-users-at-the-same-time-to-Office-365-Admin-Help-1f5767ed-e717-4f24-969c-6ea9d412ca88
