### ISSUE TITLE
Single Line of Text columns do also appear as facet

### ISSUE THREAD

**Issue by acieslik** [MicrosoftDocs/power-platform#561]
Reg. this paragraph stating:
_All View Columns with data types other than Single Line of Text and Multiple Lines of Text are marked as facetable and filterable in the index. By default, the first four facetable fields in the Quick Find view for the selected entity are displayed as facets when users search by using Relevance Search._ 

I actually experienced that this behavior is not right. I can also confirm that Single Line of Text columns will also appear as facet in the search results of the relevance search which is actually good and makes totally sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f4b53c-095c-4bf9-46dd-62299f2568e5
* Version Independent ID: 92a06c7b-d9b6-1a85-fb46-8378273a5994
* Content: [Configure Relevance Search to improve search results and performance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/configure-relevance-search-organization#configure-searchable-fields-for-relevance-search)
* Content Source: [power-platform/admin/configure-relevance-search-organization.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/configure-relevance-search-organization.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@acieslik 
Thanks for the feedback. We'd like to contact you and discuss this issue. Do you have an internal source you could contact to get this started?
