### ISSUE TITLE
Export your Dataverse data to Azure Data Lake Gen2 is not in preview

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/power-platform#563]
The text "We're now previewing a similar capability to export your Dataverse data to Azure Data Lake Gen2. " should be updated, as this is now GA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#SQLDB_IP_addresses)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@algattik 
Thanks for bringing this to our attention. This will be updated today.
