### ISSUE TITLE
Video content need to be updated with latest information from feature PM

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/power-platform#566]
Hi Team, 

The content or information in the video are old or not updated with latest information. We need to do a Maintenance of this page. Kindly connect with feature PM and get the latest video recorded and added in this public facing page. 

And one more thing, why will you give reference of a video:Best practices for setting up security and environments in the Power Platform admin center:  https://youtu.be/SVY-h5YRMEY on public page which has lot of background noise ? 

Listen to this video:  https://youtu.be/SVY-h5YRMEY , it has lot of background noise. All the videos on this page, need to be reviewed by feature PM's and accordingly record a new video and add new video on this page for public consumption with latest information.  

**Topic** 
Top 10 tips to securely roll out Microsoft Power Apps and Microsoft Power Automate 
What's new for Power Apps and Microsoft Dynamics 365 admins
Best practices for managing and automating (ALM)
Modernizing the way we update Dynamics 365, Power Apps, and Microsoft Dataverse 
Monitoring and supporting Power Apps at scale 
How to get the best support for Power Apps, Power Automate, and Dynamics 365 
Planning your enterprise deployment - Capacity Management
Best practices for setting up security and environments in the Power Platform admin center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85f443e7-db53-067e-0fc6-73f2e294ef11
* Version Independent ID: 906bfc9f-cb6c-df52-63e0-63cd177d2b9c
* Content: [Videos - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/videos?source=docs)
* Content Source: [power-platform/admin/videos.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/videos.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@HinaMS 
Thanks for the feedback. We'll try to get these videos updated as soon as possible.
