### ISSUE TITLE
Sync template flows already turned on - but not visible on Cloud Flows page

### ISSUE THREAD

**Issue by BasvGMRN** [MicrosoftDocs/power-platform#568]
Downloaded and installed version 1.78

In the section:
> **Activate the sync template flows**

It is stated to turn on the flows in a particular order.
However, in my environment the "Cloud Flows" were not shown under Flows > Cloud Flows
![image](https://user-images.githubusercontent.com/57066702/106155986-546c6f00-6181-11eb-9a90-d912ea26a263.png)

In the solution, I found the flow "CLEANUP - Admin | Sync Template v3 (Check Deleted)" and it was already running!
![image](https://user-images.githubusercontent.com/57066702/106156546-f724ed80-6181-11eb-840a-6335144a41e8.png)

Expected to see the cloud flow "CLEANUP - Admin | Sync Template v3 (Check Deleted)" on the page: Flows > Cloud Flows
and to enable it from there.

Please update the documentation and perhaps provide an explanation why the flows in the solution are not shown in the flows page.

Thanks,
Bas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you for the feedback!

Solution aware flows will only show in the solution.  I encourage you to give feedback to the product team in https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas to consider changing this.

**Comment by BasvGMRN** [comment]
Hi Manuela, 

Thanks, will give my feedback about the flows not visible on the flows > Cloud Flows page.

The other topic was about the automatic enablement of the flows during solution import - hence not requiring manual task - this is mentioned on the page but seems to be not relevant anymore?

**Comment by manuelap-msft** [comment]
I will check that - they should be switched off by default, so if we have an issue there we will address this with our February release next week.
