### ISSUE TITLE
You don't have permissions to add XXX to this team

### ISSUE THREAD

**Issue by itslaurajohnson** [MicrosoftDocs/power-platform#57]
Hi, I tried these steps out - but I got the message "You don't have permissions to add XXX to this team" when I try to Install. What could be causing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce60ea6f-d01c-9714-f3f7-db3a11806a34
* Version Independent ID: 435cfd9f-8b1d-d810-a58c-655ca6780286
* Content: [Add a Power Virtual Agents bot to Microsoft Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/publication-add-bot-to-microsoft-teams#feedback)
* Content Source: [power-virtual-agents/publication-add-bot-to-microsoft-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/publication-add-bot-to-microsoft-teams.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by itslaurajohnson** [comment]
So I think I have resolved this by following the steps in "Add an app to the Tenant Apps Catalog". Although my Virtual Agent conversation is now not correct / up to date... hoping it is a time lag that resolves!

**Comment by iaanw** [comment]
Glad it worked out - if you're still seeing problems please open a thread at the aka.ms/pvaideas forum - we have engineers who can help out there.

**Comment by joanteixi** [comment]
I've the same problem, trying to add a bot in my Teams company... and no idea which kind of permissions do I have... can you help me? Thanks!

**Comment by itslaurajohnson** [comment]
Hi @joanteixi, so two things I learn't when deploying my PVA bot to Teams. 1) There is a known product limitation: Currently only the Personal scope is supported for Microsoft Teams. 2) I was able to bypass the permissions error I was receiving by seleting "Upload a custom app" as shown in the screenshot attached - I hope this works for you?
![image](https://user-images.githubusercontent.com/59015839/76757071-d8db1c80-677e-11ea-8148-40b96dba5491.png)

**Comment by joanteixi** [comment]
yes.. it works this way, thanks @itslaurajohnson

**Comment by mogadanez** [comment]
If I upload custom app - how can I update it later?
