### ISSUE TITLE
Is the base schema accurate and wholistic?

### ISSUE THREAD

**Issue by denisem-msft** [MicrosoftDocs/power-platform#577]
The base schema has different field names displayed than what shows in the audit logs fields response (export). There are more fields in the actual response, and there are some fields that seem wrong -- for example, "Operation" is type Edm.Date... seems wrong. Can we validate this with the engineering team (anupma sharma is PM for admin and might be able to help route to the owning team)

Also, what is the scope? Does this include solution aware powerapps canvas apps too? Can there be links added to the other power platform components (e.g., dataverse audit logging, power automate (currently in progress), power virtual agents, PBI)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 184dd591-1250-2bcc-db42-35afc3a77bce
* Version Independent ID: 75aaea0f-6f52-3977-77ba-a79f3604ef5e
* Content: [Power Apps activity logging - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps)
* Content Source: [power-platform/admin/logging-powerapps.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/logging-powerapps.md)
* Service: **power-platform**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by jimholtz** [comment]
@denisem-msft 
Taking to internal thread.
