### ISSUE TITLE
CoE license requirements 

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#579]
Question about licensing requirements. Power Apps canvas/model-driven in CoE of course require Premium license but isn't so that **also** Power Automate Premium license is required because Flows uses Premium connectors like Dataverse? If so then I think we should state that requirement more clearly on this page like Power Apps per User/App **AND** Power Automate per User/Flow is needed? Now it is mentioned that 1 of the Power Apps OR Power Automate license is the requirement

_Premium licenses are required to use the CoE Starter Kit. Depending on what components you will use, your organization size and the existing licenses available in your organization, you will require either a Power Apps per user or per app **or** Power Automate per user or per flow license or a combination of these licenses._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
We updated the license requirements pre-reqs!
