### ISSUE TITLE
Suggest a value for Scope

### ISSUE THREAD

**Issue by Grudgeboy** [MicrosoftDocs/power-platform#58]
It would be very useful for readers if you suggested openid as a value for scope in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f11f0ed-eec4-dfbc-4498-87690a569091
* Version Independent ID: 7c3ba7b6-5874-2cbb-0aef-aef24489d0b0
* Content: [Configure user authentication in Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-end-user-authentication#feedback)
* Content Source: [power-virtual-agents/configuration-end-user-authentication.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/configuration-end-user-authentication.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
We've added in more information about scopes to this article.
