### ISSUE TITLE
Missing dependencies when following instructions, asking to install "Active" solution

### ISSUE THREAD

**Issue by tonyk451** [MicrosoftDocs/power-platform#581]
I've created a new sandbox environment to test the CoE and, when following the instructions, get the following error when attempting to import the solution "CenterofExcellenceCoreComponents_1_85_managed.zip" 
"There are missing dependencies. Install the following solutions before installing this one: "Active" "
Details
Name
CenterofExcellenceCoreComponents
Type
Managed
Publisher
Power Platform Admin
Version
1.85
Patch
No

Any advice would be much appreciated.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

issues with the platform, and not the documentation, should be raised via the repository the CoE starter kit is hosted in: https://github.com/microsoft/powerapps-tools/issues where issues will be appropriately tagged and assigned to the correct team to respond.

We had noticed this issue earlier today, and provided an update already - see details and link to the download of the new version here: https://github.com/microsoft/powerapps-tools/issues/742

Thanks for using the CoE
