### ISSUE TITLE
incorrect

### ISSUE THREAD

**Issue by denaskrb** [MicrosoftDocs/power-platform#582]
According to Jeff Levinson (jeff.levinson@microsoft.com), the Tech Strategist for Boeing
**The info below is incorrect. In the GCC (IL2 environment), content is not guaranteed to be accessed by a US Person. Also, unless something has changed it is not a US Citizen but a US Person and those are two completely different things. Only the IL 4 environment is guaranteed to be accessed by a US Person. This needs fixing ASA**P.

The Power Apps GCC environment provides compliance with federal requirements for cloud services, including FedRAMP High, DoD DISA IL2, and requirements for criminal justice systems (CJI data types). - However GCCH is IL4. In addition, in another part of the document it states:
Access to Power Apps US Government customer content by Microsoft administrators is restricted to personnel who are US citizens. These personnel undergo background investigations in accordance with relevant government standards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea524f2a-1e2a-6ade-8e2b-bc61173107c5
* Version Independent ID: 5990c060-8907-62b4-a8b3-f7ed8339a70e
* Content: [Microsoft Power Apps US Government - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government)
* Content Source: [power-platform/admin/powerapps-us-government.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-us-government.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@denaskrb 
Sorry for the delayed response. Please contact Jeff Levinson who was on a recent thread discussing this.
