### ISSUE TITLE
Update screenshots using maker portal

### ISSUE THREAD

**Issue by mlathouwers** [MicrosoftDocs/power-platform#583]
Screenshot should be updated.  Please include the screenshots using the make.powerapps.com way of working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69aeb6e6-2819-2fc8-e06f-8bd13f6767a0
* Version Independent ID: ac4f825f-a16c-9292-1486-f6a0ac0d4c82
* Content: [Create and update solutions in Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/update-solutions-alm)
* Content Source: [power-platform/alm/update-solutions-alm.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/update-solutions-alm.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@mlathouwers - Thank you for your feedback. The screenshot has been updated to use the maker portal solution import experience. 
Closing issue.
