### ISSUE TITLE
RPM Clarification

### ISSUE THREAD

**Issue by NikitaSkitsko** [MicrosoftDocs/power-platform#584]
Does RPM limit mean that there can be up to 800 concurrent users talking with the bot at the same time?
If yes, is there any way to notify users that they have to wait for a minute, because bot is very busy at the moment? 
Does MS have plans to increase this limit or better strategy would be to create many different bots on different topics? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07c96368-89fa-6451-b091-d59ed754cd75
* Version Independent ID: 140f2cc2-70d0-334a-8707-a1cde39fd75b
* Content: [Rate limits for chatbots - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/requirements-quotas)
* Content Source: [power-virtual-agents/requirements-quotas.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/requirements-quotas.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for your feedback! The best place for product requests or troubleshooting is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
