### ISSUE TITLE
How are read operations counted

### ISSUE THREAD

**Issue by matejskubic** [MicrosoftDocs/power-platform#585]
How is one select counted against CRUD request limit if statement returns 1.000 records?
Is same answer for joined read operations (FetchXML with 2, 3 joined tables)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#will-there-be-a-transition-period-for-existing-customers)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@matejskubic 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Here's what the product team reported:
Customer generated actions/ API calls are what gets counted and these limits on APIs don’t depend on the number of records returned. We recommend that you refer the capacity entitlement report which will be made available in Power Platform Admin center:  https://docs.microsoft.com/en-us/power-platform/admin/capacity-storage.  There will be a new API consumption report available soon on this page and until then you can refer to https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service as a close approximation.
