### ISSUE TITLE
Need to change from UI to Desktop flow

### ISSUE THREAD

**Issue by narismadz** [MicrosoftDocs/power-platform#586]
Dear team 

I think the analytics section is change from UI flows to Desktop flows
Please check
![image](https://user-images.githubusercontent.com/16915716/106868367-45496c00-6701-11eb-9f49-6efb904e1c28.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7b5964c-b2b0-7487-3bd1-ef03b5621cb8
* Version Independent ID: 3bce966f-4d3a-f46d-b2f9-aa4a43002e61
* Content: [View UI flows analytics in the Power Platform admin center - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/analytics-ui-flow)
* Content Source: [power-platform/admin/analytics-ui-flow.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/analytics-ui-flow.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by KendalBond007** [comment]
As of content publish on 8 March 2023 images show Desktop flows highlighted. Closing issue.
