### ISSUE TITLE
Missing Connector in doc

### ISSUE THREAD

**Issue by 4DaddyT** [MicrosoftDocs/power-platform#587]
Under the 'Import the Solution' heading, step 4e, can you add HTTP Connector. It is missing from the list and is req for the 'Admin | Sync Template v3 (Custom Connectors)' flow. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
I'm not sure I understand what you mean. You don't create connections for HTTP under Data > Connections. Although it is required in the DLP policy, which is mentioned in our pre-requisites, it is not a connection you create or set during Import. 

Under connections you may find the HTTP with Azure AD connector, but that's not the one we are using.

**Comment by 4DaddyT** [comment]
Totally overlooked that info in pre-req’s!

**Comment by manuelap-msft** [comment]
Great, thank you - closing this issue now but let me know if you have any additional questions, or find something in our setup instructions unclear!
