### ISSUE TITLE
Make it easier to understand how to use tasks with YAML

### ISSUE THREAD

**Issue by devkeydet** [MicrosoftDocs/power-platform#589]
Azure DevOps documentation makes it easier to understand how to use tasks with YAML.  They basically share what the YAML would look like in a snippet, with some comments to help, then they explain the arguments.  Example:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=azure-devops

Please consider doing the same for this docs page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tool-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment]
@devkeydet YAML snippets have been added to the documentation.
