### ISSUE TITLE
Delete system users

### ISSUE THREAD

**Issue by tgradu** [MicrosoftDocs/power-platform#59]
[Enter feedback here]
As per the documentation "You can't delete a business unit until you delete any associated users, teams, and child business units."
However in CRM you can't delete a System User. Could you please confirm?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c0d7bf-68ca-29b6-75a3-5e8543340293
* Version Independent ID: c6cd2144-8fa1-0e8a-cd6f-1fbfc81815ab
* Content: [Delete a business unit - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/delete-business-unit?source=docs)
* Content Source: [power-platform/admin/delete-business-unit.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/delete-business-unit.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@tgradu 
Thanks for bringing this to our attention. We've updated the text to:
"You can’t delete a business unit until you reassign all the business unit records to another business unit. "
