### ISSUE TITLE
Move Azure Subscription any impact on sync operations?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/power-platform#590]
Wanted to understand will moving my azure sql databases can break the sync if I have been using data export service?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Anmolgan81 
This can happen only if you change the tenant when you redo the steps to create a link from Dynamics to Azure SQL. Moving the subscription alone (within the same tenant) should not be problem.
