### ISSUE TITLE
Missing instructions on how to enable for other regions 

### ISSUE THREAD

**Issue by denisem-msft** [MicrosoftDocs/power-platform#591]
We have to enable CMK for each region independently (and we need to call this out in our doc).  You need to submit an ICM to enable CMK for each region.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c43b88-32f5-49ab-d715-bfcf75c9ba3e
* Version Independent ID: 70179da7-e3b6-8775-97cc-361990404677
* Content: [Manage the encryption key - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-encryption-key)
* Content Source: [power-platform/admin/manage-encryption-key.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-encryption-key.md)
* Service: **power-platform**
* GitHub Login: @Mattp123
* Microsoft Alias: **miferlan**

**Comment by jimholtz** [comment]
@denisem-msft 
Taking this to internal communication for text addition.
