### ISSUE TITLE
Documentation should point out that underscores in schema name cause failure

### ISSUE THREAD

**Issue by hitzand** [MicrosoftDocs/power-platform#592]
We were struggling a lot to get this to work.  The key vault connection and secret were fine, and it passed validation, but on the final step it would always say "Create Data Export Profile failed. Error validating profile registration", with no further information.  We tried MANY different configurations, and finally found the issue.  **For some reason, if the target schema has underscores (such as "CRM_ABC_DEF"), the profile creation would fail.**  This should be corrected or included in the documentation.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#feedback)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@hitzand 
We do state the following:
Schema. Name for an alternative database schema. **Only alphanumeric characters are valid**. This field is optional. By default, dbo is the schema that is used for the destination SQL Database.

https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#create-an-export-profile:~:text=Only%20alphanumeric%20characters%20are%20valid.

We'll see if this needs to be called out more in future updates.

**Comment by hitzand** [comment]
Oh thanks, sorry, I missed that distinction.  It certainly would be helpful if the field pointed out an invalid value when entering the name, the validation caught an invalid schema name, or the error message pointed out that the schema name was the issue.
