### ISSUE TITLE
Service Principal Connection Availability

### ISSUE THREAD

**Issue by vgawande-git** [MicrosoftDocs/power-platform#593]
Is this available now? We are upgrading to use GitHub with Power Platform and need this feature to migrate ALM processes

https://docs.microsoft.com/en-us/power-platform/alm/devops-github-actions Page still says:
Service principal and client secret: This connection type uses service principal–based authentication and supports multifactor authentication. Service principal authentication availability in late 2020.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a110f4b-e1a1-ac97-f6f2-4723a6f53dd3
* Version Independent ID: 36551e12-f118-cc21-6953-1f5f953bbeb1
* Content: [GitHub Actions for Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-github-actions)
* Content Source: [power-platform/alm/devops-github-actions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-github-actions.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment]
@vgawande-git Yes, this is now available and the documentation has been updated.
