### ISSUE TITLE
How to recover the space if it's the current log file that's taking the space

### ISSUE THREAD

**Issue by paulhasell** [MicrosoftDocs/power-platform#594]
[Enter feedback here]
Dynamics has created a future dated log file through to 1st Apr 2021 so I can't delete it but this is the file that's hogging all the space :( What do I do now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a8f913f-f933-fb4b-9453-7a9e840de127
* Version Independent ID: fd928fdf-b49b-aa46-26d5-efdb861dc83f
* Content: [Recover database space by deleting audit logs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/recover-database-space-deleting-audit-logs)
* Content Source: [power-platform/admin/recover-database-space-deleting-audit-logs.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/recover-database-space-deleting-audit-logs.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@paulhasell 
Please contact support: https://powerapps.microsoft.com/support/
