### ISSUE TITLE
Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Environments' of type 'OpenApiConnection' at line '1' and column '7933' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

### ISSUE THREAD

**Issue by compkos** [MicrosoftDocs/power-platform#595]
Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Environments' of type 'OpenApiConnection' at line '1' and column '7933' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

---
#### Λεπτομέρειες εγγράφου

⚠ *Μην επεξεργαστείτε αυτή την ενότητα. Απαιτείται για σύνδεση θεμάτων docs.microsoft.com ➟ GitHub.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Ρύθμιση κύριων στοιχείων - Power Platform](https://docs.microsoft.com/el-gr/power-platform/guidance/coe/setup-core-components#update-environment-variables)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform-pr.el-GR/blob/live/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by compkos** [comment]
Power Apps COE starter kit 
on turn on
Cleanup - Admin Sync Template v3 check deleted

**Comment by manuelap-msft** [comment]
As per https://docs.microsoft.com/en-us/power-automate/limits-and-config, section Concurrency, looping, and debatching limits if you are running the flow with a Low Performance profile (Free, Microsoft 365 plans, Power Apps Plan 1, Per App plans, Power Automate Plan 1, All license trials) you are limited to a pagination of 5,000. All the flows in the CoE starter kit require a Medium or High license plan, thus you will either need to assign a Per Flow license to this flow or get a Per User license.
