### ISSUE TITLE
No notification storage issues

### ISSUE THREAD

**Issue by FerrousJack** [MicrosoftDocs/power-platform#598]
We aren't getting any notifications of storage capacity being exceeded. Our apps just stop working.
Where do we purchase additional capacity? There isn't just a link on the capacity page (which would make this easy).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f8c1ca-4250-85c7-2b8e-caab633d8d9d
* Version Independent ID: 70065f90-617e-d812-e04e-7594708b0cce
* Content: [New Microsoft Dataverse storage capacity - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/capacity-storage)
* Content Source: [power-platform/admin/capacity-storage.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-storage.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@FerrousJack 
Please review the following and see if that provides the information you need for adding capacity:
https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on

**Comment by jimholtz** [comment]
@FerrousJack 
After further reviewing content, I will add content on how to purchase additional capacity. Thanks for the feedback.
