### ISSUE TITLE
Microsoft Center of Excellence: Start a subscription to audit log content

### ISSUE THREAD

**Issue by unclejdl1979** [MicrosoftDocs/power-platform#599]
Please see screen shots below. I am running into this error when trying to complete the following steps in flow.

1. On the Custom Connector page, select 4. Test.

2. Select + New connection, and then sign in with your account.

3. Under Operations, select StartSubscription.

I'm using the correct client secret and client ID.

Please advise!

![image](https://user-images.githubusercontent.com/79171757/108123835-74060180-7074-11eb-84c5-03aba37824e4.png)

![image](https://user-images.githubusercontent.com/79171757/108123401-cc88cf00-7073-11eb-9b69-f6e33afe4ea9.png)

**Comment by manuelap-msft** [comment]
Hello,

if you are experiencing any issues with the CoE Starter Kit, please raise them here https://github.com/microsoft/powerapps-tools/issues

The issues here are only to do with our documentation (e.g. incorrect instructions).

Thank you Manuela
