### ISSUE TITLE
Getting a GUID Error

### ISSUE THREAD

**Issue by moonplanter** [MicrosoftDocs/power-platform#60]
developer.mpnId | String "6e3xxx39e-xxxx-xxxx-xxxx-97aa66193xxx" exceeds maximum length of 10.

Anyone else getting the same or have any ideas why?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce60ea6f-d01c-9714-f3f7-db3a11806a34
* Version Independent ID: 435cfd9f-8b1d-d810-a58c-655ca6780286
* Content: [Add a Power Virtual Agents bot to Microsoft Teams - Power Virtual Agents](https://docs.microsoft.com/en-gb/power-virtual-agents/publication-add-bot-to-microsoft-teams)
* Content Source: [power-virtual-agents/publication-add-bot-to-microsoft-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/publication-add-bot-to-microsoft-teams.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Please open a thread on the aka.ms/pvaideas forum - engineers/PMs should be able to help identify and solve the problem there.

Thanks!
