### ISSUE TITLE
How to change the audit retention value using the Web Api

### ISSUE THREAD

**Issue by robertoilidio** [MicrosoftDocs/power-platform#600]
Regarding this section "_Start/stop auditing and set retention policy_", it says that it is possible to change the audit retention value using the Web Api, but it doesn't explain how.

Ideally, this documentation could share an sample on how to change it using the Web Api, sharing a sample code, similar as below:

var data =    {
  
        "auditretentionperiod": 60
    }
Xrm.WebApi.updateRecord("organization", "a587c196-0fb4-4044-b9bc-065b86fe7537", data).then(
    function success(result) {
        console.log("Account updated");
    },
    function (error) {
        console.log(error.message);
    }
);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837f9db7-667d-814f-1df6-98e2f89a44cc
* Version Independent ID: f53ea984-3798-d3fb-ec0c-d31f81db9250
* Content: [Audit data and user activity for security and compliance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity#startstop-auditing-and-set-retention-policy)
* Content Source: [power-platform/admin/audit-data-user-activity.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/audit-data-user-activity.md)
* Service: **power-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by jimholtz** [comment]
@robertoilidio 
Sorry for the delay. Thanks for the suggestion. We'll consider this for future revisions to this content.
