### ISSUE TITLE
Screenshots are still from the old Power Apps admin center

### ISSUE THREAD

**Issue by anmateusMSFT** [MicrosoftDocs/power-platform#602]
Screenshots are still from the old Power Apps admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd884343-7f2e-9765-4860-4cb4981a908e
* Version Independent ID: efe70284-6f99-698c-9406-802595535d97
* Content: [Integrate data into Microsoft Dataverse - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/data-integrator)
* Content Source: [power-platform/admin/data-integrator.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/data-integrator.md)
* Service: **power-platform**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by jimholtz** [comment]
@anmateusMSFT 
Taking to internal thread.
