### ISSUE TITLE
Missing Power Virtual Agents for Teams service limit

### ISSUE THREAD

**Issue by israelarribas** [MicrosoftDocs/power-platform#605]
Missing Power Virtual Agents for Teams service limit in Spanish @shellyhaverkamp 

It should be something like this:
_Las sesiones de Power Virtual Agents que se incluyen en determinadas suscripciones de Microsoft 365 no se agrupan y tienen los siguientes límites:

LÍMITE DE SERVICIO DE POWER VIRTUAL AGENTS PARA TEAMS
Licencia: Power Virtual Agents para Teams
Límites de sesión cada 24 horas: 10 por usuario_ 

[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 07c96368-89fa-6451-b091-d59ed754cd75
* Version Independent ID: 140f2cc2-70d0-334a-8707-a1cde39fd75b
* Content: [Límites de frecuencia para chatbots - Power Virtual Agents](https://docs.microsoft.com/es-es/power-virtual-agents/requirements-quotas)
* Content Source: [power-virtual-agents/requirements-quotas.md](https://github.com/MicrosoftDocs/power-platform-pr.es-ES/blob/live/power-virtual-agents/requirements-quotas.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by jowilco** [comment]
@israelarribas 
Thank you for bringing this to our attention. The Spanish version is now up to date with the English.
