### ISSUE TITLE
environments missing from admin center

### ISSUE THREAD

**Issue by Karenzhang7717** [MicrosoftDocs/power-platform#607]
hi, when I tried to access my environment from admin center, it says there are no environments. However I do have an environment but it is missing, can you please let me know how to fix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6bf79b0-5e31-ebc4-2397-c7274967dd8f
* Version Independent ID: 9b67d821-bfc9-eb04-c10d-31187c655984
* Content: [Manage environments in the Power Apps Admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/environments-administration)
* Content Source: [power-platform/admin/environments-administration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/environments-administration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Karenzhang7717 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
