### ISSUE TITLE
Instead of Parature - word Armature is used in couple of places

### ISSUE THREAD

**Issue by arunvinoth** [MicrosoftDocs/power-platform#608]
Instead of Parature - word Armature is used in couple of places.

Also word Pasture used once. Pls fix them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and customer engagement apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming?WT.mc_id=linkedin)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/important-changes-coming.md)
* Service: **power-platform**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
This is fixed.
