### ISSUE TITLE
DLP base schema information

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#611]
Is the DLP base schema information correct as it seems to be exact same list as in PowerApps including "App Name" field with description "Unique Identifier of the PowerApp"?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e67d79-53b0-8303-d759-c2a3dd971556
* Version Independent ID: d4f73e5c-1960-e1b9-e94c-8cf65eb5671a
* Content: [Data loss prevention activity logging - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/dlp-activity-logging)
* Content Source: [power-platform/admin/dlp-activity-logging.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/dlp-activity-logging.md)
* Service: **power-platform**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by jimholtz** [comment]
@petepuu 
Taking to email.
