### ISSUE TITLE
Approvals Connector and Dataverse

### ISSUE THREAD

**Issue by fredericklin** [MicrosoftDocs/power-platform#612]
Is there any documented guidance for using the standard Approvals connector in a flow that resides in a non-default environment.  It looks like provisioning Dataverse in another environment requires a premium license but this standard functionality doesn't work without Dataverse.

https://support.microsoft.com/en-us/topic/power-automate-approvals-provisioning-overview-and-troubleshooting-2306313a-49fa-efde-c716-a34c573ec942

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Licensing overview - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@fredericklin 
Sorry for the delayed response. I have not heard back from the product team in a timely manner so I'm closing this. If you still have this question, please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
