### ISSUE TITLE
assign a security role to a group of users by assigning the security role to a D365 Group team.

### ISSUE THREAD

**Issue by MattHoag-MS** [MicrosoftDocs/power-platform#613]
Hi Jim,
Regarding this specific header : https://docs.microsoft.com/en-us/power-platform/admin/security-roles-privileges#assigning-security-roles

This section is very helpful about how to assigns security role to an individual user.  But it is also possible to assign a security role to a group of users by assigning the security role to a D365 Group team.

If there isn't an existing article that explains this, could a header and  paragraph be added to this document to explain how to assign a security role to a group of users who are in a D365 Group Team?

Thanks
Matt
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6159c3d-47a4-bc29-7dda-52777db307c2
* Version Independent ID: 426568f9-3742-b39e-600d-5f3afd251c19
* Content: [Create users and assign security roles - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-users-assign-online-security-roles)
* Content Source: [power-platform/admin/create-users-assign-online-security-roles.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-users-assign-online-security-roles.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@MattHoag-MS 
Taking this to internal thread.
