### ISSUE TITLE
This page seriously needs an update :)

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/power-platform#614]
The geo has been GA for years - this page needs a thorough once over... 🙂

"What app **data be in Australia** datacenters at general availability?"

"With the inclusion of datacenters in Japan (recently announced) and Australia, both **targeting Q1 CY2015**, our global customers will be served by 17 datacenters covering 6 global regions around the world."
About Microsoft Cloud Australia - Power PlatformAbout Microsoft Cloud Australiadocs.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c97d6779-f8df-2152-fcc7-b83ad9c3a4f6
* Version Independent ID: fe6e30d0-50b2-688f-ce54-7256c5bddcaa
* Content: [About Microsoft Cloud Australia - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-microsoft-cloud-australia)
* Content Source: [power-platform/admin/about-microsoft-cloud-australia.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/about-microsoft-cloud-australia.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@PeteHaigh-MSFT 
Taking to internal thread.
