### ISSUE TITLE
Link to "Where is my data?" points to old information

### ISSUE THREAD

**Issue by pieterh** [MicrosoftDocs/power-platform#615]
Please verify the link to "Where is my data?"It points to a page that is indicating to have old information and that you should seek an other location for more up-to-date information. This is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6e0ce6-b90d-ae6a-d9bc-89b693fbe4e3
* Version Independent ID: 46b8668e-b83f-5681-0d37-88fb08fbdcd5
* Content: [Datacenter regions - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/new-datacenter-regions)
* Content Source: [power-platform/admin/new-datacenter-regions.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/new-datacenter-regions.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@pieterh 
Thanks for bringing this to our attention. We will correct the documentation.
