### ISSUE TITLE
Instructions do not include grant oAuth Access for App

### ISSUE THREAD

**Issue by coatsy** [MicrosoftDocs/power-platform#617]
When setting up the GitHub connector, an oAuth app registration is created in GitHub. If that app is not granted access via the link sent in the GitHub email, creation of the repo for a project fails and an email is sent with the error

``` text
Hi, 

The Project [project name] creation has failed due to system error. 

Flow Name: CreateProject 
Flow Run ID: [run ID]
Error Details: Error found in action: Create_Repo with code: InternalServerError Error: Error Creating Repo with name [project name]

Thanks.

```
On further investigation, the `CreateRepo` flow fails on the `Create a Repository` step with the following body:

``` json
{
  "message": "The OAuth application is not authorized for access to [org name].",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-using-a-template"
}
```
There is nothing in the docs to suggest this granting is required. There should be an explicit step calling out the requirement to Grant the oAuth app based on the link sent from GitHub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d3a97-f062-9c7c-a5b6-8ec69178e1bc
* Version Independent ID: 476f4f57-b869-c759-74cc-beb4e2deaa26
* Content: [Set up ALM Accelerator for Makers components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator)
* Content Source: [power-platform/guidance/coe/setup-almaccelerator.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-almaccelerator.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by mikefactorial** [comment]
Thanks for pointing this out @Coatsy. We'll work on adding this to the docs.

**Comment by NIhil1409** [comment]
HI,

Any updates on this issue  ? as I am having same issue

**Comment by SeanKe11y** [comment]
> HI,
> 
> Any updates on this issue ? as I am having same issue

As coatsy mentioned, you should have received an email after setting up the connection (mine had a subject of "_[GitHub] A third-party OAuth application has been added to your account_").

Click the first link in that email and you'll be able to grant access to the app in GitHub (under Organization Access).

Or follow these steps: https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization

Thanks coatsy for the pointer!

**Comment by NIhil1409** [comment]
Thanks SearnKelly,

It worked

**Comment by NIhil1409** [comment]
@SeanKe11y :- i am having another issue with authentication while deploying solution to test. if you can have a look and help ? Thanks Please find attached error log 
[logs_1.zip](https://github.com/MicrosoftDocs/power-platform/files/6397365/logs_1.zip)

**Comment by mikefactorial** [comment]
Closing this and moving to microsoft/coe-starter-kit#799
