### ISSUE TITLE
Guest Users Access to PVA

### ISSUE THREAD

**Issue by SarathKumarUtla** [MicrosoftDocs/power-platform#618]
[The documentation regarding guest user access to PVA is not detailed. eg: How Guest Users need to be configured to have access to PVA Bot? What are the Limitations? etc.,]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e466d2-32aa-9e1d-f892-75938c32d170
* Version Independent ID: b0dcce21-95ae-0c66-c236-e3cde47f94d3
* Content: [Configure access and authentication - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configuration-security)
* Content Source: [power-virtual-agents/configuration-security.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/configuration-security.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
@clmori I'm assuming that access will be the same for guest users within an organization as standard org members, is that correct? We mention this here https://docs.microsoft.com/en-us/power-virtual-agents/configuration-security#guest-and-external-access-users but may need to be more explicit and link back to the assigning procedures at the top of the article.
