### ISSUE TITLE
Not clear where GitHub Environment Variables (Org Secrets) come from 

### ISSUE THREAD

**Issue by coatsy** [MicrosoftDocs/power-platform#619]
In the `Configure GitHub org secrets` section, it's not clear what the value of the secrets needs to be. It should be made explicit that the secret should be the password for the admin user used for running each deployment stage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d3a97-f062-9c7c-a5b6-8ec69178e1bc
* Version Independent ID: 476f4f57-b869-c759-74cc-beb4e2deaa26
* Content: [Set up ALM Accelerator for Makers components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator)
* Content Source: [power-platform/guidance/coe/setup-almaccelerator.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-almaccelerator.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by mikefactorial** [comment]
Agreed. I will include this along with your other feedback on oAuth.

**Comment by mikefactorial** [comment]
Closing this issue as no further action is required from our team at this time. Created a new Issue here to address doc updates microsoft/coe-starter-kit#798
