### ISSUE TITLE
On-Going Availability of Power Platform Features/Functionality w/o Grandfathered?

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/power-platform#62]
### **Just to clarify my understanding, does this statement:**  

![image](https://user-images.githubusercontent.com/38665906/71125080-84d29300-21a3-11ea-91ac-d6413373e1de.png)

### Or am I misunderstanding?

**Comment by jimholtz** [comment]
@TracyGH 
Sorry for the very delayed response. If this is still a question, please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
