### ISSUE TITLE
Old AzureRM + Az PowerShell mixup

### ISSUE THREAD

**Issue by relexx** [MicrosoftDocs/power-platform#620]
The code/snippet to create a key vault does not work anymore with any up-to-date PowerShell environment (with installed AzureRM or Az). The reason for this is that either connect-azaccount works, or New-AzureRmResourceGroup, but not both.
The script should be updated to reflect the current Az version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by jimholtz** [comment]
@relexx 
Sorry for the delayed response. We'll be updating this content in the future and will review your suggestion then.
