### ISSUE TITLE
Incorrect level of permissions required to use some cmdlets

### ISSUE THREAD

**Issue by prejedj** [MicrosoftDocs/power-platform#622]
Specifically in this section of the page. https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#prerequisite-1
I have confirmed, with a call to Microsoft that you must be the owner of the MS Team if you want to view the Dataverse for Teams environment and it's resources and policies that apply to it.

Please update the documentation to show this discrepancy 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#prerequisite-1)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by laneswenka** [comment]
Made the update on the new Getting Started page for Powershell.  This will go out in a subsequent doc wave.
