### ISSUE TITLE
Size of the @entityName variable is to small

### ISSUE THREAD

**Issue by filipliwinski** [MicrosoftDocs/power-platform#626]
In the `How to delete Data Export Profile tables and stored procedures for a specific entity` script the `@entityName` variable is set to `nvarchar(32)`. This is definitely not enough, as some entities or relationships may have names containing more than 32 characters. 

    -----------------------------------------------------------------
    -- Provide the value for the following parameters
    DECLARE @prefix nvarchar(32) ='crm'
    DECLARE @schema nvarchar(32) ='dbo'
    DECLARE @entityName nvarchar(32) ='lead'
    -----------------------------------------------------------------

In our case, the name of one of the entities was 37 characters long and because of that, the `@entityName` was set to null. Then the `@sql` variable is set to null too (because `@prefix + @entityName` is also null) and consequently no tables are deleted from the database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#drop_entity)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by jimholtz** [comment]
@filipliwinski 
Sorry for the delayed response. We've passed this on to the product group for their attention.
