### ISSUE TITLE
Start a subscription to audit log content

### ISSUE THREAD

**Issue by BandyCh** [MicrosoftDocs/power-platform#627]
When trying Start a subscription to audit log content, in Step 2 where I would establish a new connection, I get an error during the sign.  I am signing in with an admin account that has PP admin, and audit log read access.

Sorry, but we’re having trouble signing you in.

AADSTS700016: Application with identifier 'd94c19aa-1596-xxxx-xxxx-a34b77408a0f' was not found in the directory '3596192b-xxxx-xxxx-a6fa-acb706c963d8'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by jimholtz** [comment]
@BandyCh 
Please contact support: https://powerapps.microsoft.com/support/
