### ISSUE TITLE
Extend and modify components - Additional step needed

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/power-platform#628]
Please add a #10 step which states to Save and Publish your changes. 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/modify-components#set-up-the-template-catalog-and-upload-components

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fca9317c-5e95-d1f6-ba87-c35eb318d2a6
* Version Independent ID: 1d2db196-8d00-d357-a4fc-e13cfa702d0b
* Content: [Extend, customize, and modify components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/modify-components#set-up-the-template-catalog-and-upload-components)
* Content Source: [power-platform/guidance/coe/modify-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/modify-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
This step has now been added.
