### ISSUE TITLE
Billing unit and billing sessions

### ISSUE THREAD

**Issue by AyeChan1309** [MicrosoftDocs/power-platform#63]
If used sessions is more than 2000 or your limit, how can we increase the number of sessions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd5c132-57b9-d038-7e20-8f9d94d53bd3
* Version Independent ID: a436faf7-de5e-cfe5-34af-c8cc6e075cdd
* Content: [Assign user licenses and manage access to Power Virtual Agents - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/requirements-licensing)
* Content Source: [power-virtual-agents/requirements-licensing.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/requirements-licensing.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by mvakoc** [comment]
We are working on experience to surface the fact that your tenant went overcapacity. We are aiming to launch this in the first half of 2020.

**Comment by smpredith** [comment]
Without knowing what PVA does the start of this sentence "To use Power Virtual Agents, you need a license for each user " suggests that for my users to use a PVA solution that I create, I must assign a license to all users in my tenant.  My understanding is that only the technicians that create an Agent are required to have a license.  Anyone in the tenant can use the solution that the technician builds using PVA.   I recommend some clarity if possible.

**Comment by iaanw** [comment]
> Without knowing what PVA does the start of this sentence "To use Power Virtual Agents, you need a license for each user " suggests that for my users to use a PVA solution that I create, I must assign a license to all users in my tenant.  My understanding is that only the technicians that create an Agent are required to have a license.  Anyone in the tenant can use the solution that the technician builds using PVA.   I recommend some clarity if possible.

Thanks for the feedback, I'm updating it now to make it a bit clearer.
