### ISSUE TITLE
Copy Production to Sandbox managed/unmanaged

### ISSUE THREAD

**Issue by urklnme** [MicrosoftDocs/power-platform#631]
After the copy are the copied managed production solution(s) managed or unmanaged in the sandbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95518171-ce8d-6336-2a3e-9fecc18b49e8
* Version Independent ID: 650cb6e1-85bd-15e5-92fc-4b30b93a1a03
* Content: [Copy an environment to a sandbox environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/copy-environment)
* Content Source: [power-platform/admin/copy-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/copy-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@urklnme 
Sorry for the delay. Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
