### ISSUE TITLE
Why are the methods out of order?

### ISSUE THREAD

**Issue by mortkar** [MicrosoftDocs/power-platform#632]
Why are the methods all out of order.  Starts with Method 3.  Skips from method 6 to Method 10 and so on
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9c9aae-ceaa-2e78-3752-2770327f49a7
* Version Independent ID: acd2ddc9-6225-92e8-2636-2a02437c3d82
* Content: [Free up storage space - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/free-storage-space)
* Content Source: [power-platform/admin/free-storage-space.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/free-storage-space.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@mortkar 
Thanks for the feedback. We group methods under the storage capacity type. We'll continue to review and revise based on feedback.
