### ISSUE TITLE
Allocate or change capacity in an environment

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/power-platform#634]
I have a use case where I want to manage my Dataverse capacity across environments. As described [here](https://docs.microsoft.com/en-us/power-platform/guidance/adoption/capacity-and-licenses#storage-capacity) "Each additional licensed user provides an additional per-user capacity grant that increases the overall tenant available capacity. There are also capacity add-ons available to purchase additional database, file, and log capacity."

In my use case I have a total of 16.25 GB available to me to split between my environments. There's a doc that walks through how to [Allocate or change capacity in an environment](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on#allocate-or-change-capacity-in-an-environment), but it does not show how to allocate storage. Only how to allocate ai builder credits, app passes etc.

Is there some other way to do this? I want to strictly allocate storage across my environments using some configuration in the admin portal.

![image](https://user-images.githubusercontent.com/8151045/110404127-28bb8f00-8033-11eb-9e12-5705fbc1ce9c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0cbf8c-5c12-5aa2-3786-392d0f498303
* Version Independent ID: 2774f5ca-1c86-4fe6-c296-6f7f45aa6702
* Content: [Capacity add-ons for Power Apps and Power Automate - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on#allocate-or-change-capacity-in-an-environment)
* Content Source: [power-platform/admin/capacity-add-on.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-add-on.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@gregdegruy 
Taking to internal thread.

**Comment by gregdegruy** [comment]
Dataverse storage is entitled for a Tenant through three ways:

1. Tenant-level default
2. Per-USL accrued
3. Optional purchased per GB add-ons

From the perspective of storage usage vs. entitlements and technical enforcement, usage is summed across ALL environments in a Tenant and compared to the entitlements from the sources above, according to whether the tenant is on the legacy or new storage model.  See the links below for info on the differences in storage model if you’re not familiar.

[What’s new for Storage](https://docs.microsoft.com/en-us/power-platform/admin/whats-new-storage)
[New Model capacity storage](https://docs.microsoft.com/en-us/power-platform/admin/capacity-storage)
[Legacy capacity storage](https://docs.microsoft.com/en-us/power-platform/admin/legacy-capacity-storage)

Usage reporting can be viewed at an environment-level in both PPAC and Unify, and there is the ability to drill down into table capacity trends, etc.  But a customer cannot currently ‘carve up’ the tenant-level entitlement and assign portions of the entitlements to different lower granularities such as a specific environment.
