### ISSUE TITLE
Duplicate paragraph

### ISSUE THREAD

**Issue by cesar-younes** [MicrosoftDocs/power-platform#635]
First 2 paragraphs are duplicates. One of them needs cleaning up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be8aa07f-6145-c3a7-b527-aa3d4931d87a
* Version Independent ID: 442e92d2-93bb-addc-de9b-4817d428f355
* Content: [Grant users access - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/grant-users-access?source=docs)
* Content Source: [power-platform/admin/grant-users-access.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/grant-users-access.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@cesar-younes 
Thanks for bringing this to our attention. This will be corrected.
