### ISSUE TITLE
How to setup Dynamics 365 Developer Toolkit in VS2019 Community

### ISSUE THREAD

**Issue by zhinigami** [MicrosoftDocs/power-platform#636]
How to setup Dynamics 365 Developer Toolkit in VS2019 Community? It prompts message with "Invalid signature" and not compatible with the selected version of Visual Studio. Installation may cause VS to be unstable. Any advice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78dd2e38-9d0c-3bbf-0db3-138416d4063b
* Version Independent ID: 51455bd4-3294-0ccd-2b1b-6d9857c0f50f
* Content: [Package Deployer tool - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/package-deployer-tool)
* Content Source: [power-platform/alm/package-deployer-tool.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/package-deployer-tool.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment]
@zhinigami The Developer Toolkit has not been updated and there are no plans that I know of to do so. You should look at the new Power Platform Tools for Visual Studio. You can find it in the VS extension marketplace.

**Comment by phecke** [comment]
@zhinigami  Documentation is here: https://docs.microsoft.com/powerapps/developer/data-platform/developer-tools#integrated-development-environment-ide-extensions
