### ISSUE TITLE
Whish list - add a link on "How to change the Unique Name"

### ISSUE THREAD

**Issue by luconsta** [MicrosoftDocs/power-platform#637]
Hello,
It would be nice, after I found a way to get the Organization ID and Unique Name, to have a link to "extra information" like how to change that "Unique Name".
Kind Regards,
Lucian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf73e46f-9ed3-cd73-fe3c-dca0c74f329e
* Version Independent ID: 11b2f145-ae97-416d-5536-0365be23a68d
* Content: [Determine your environment's organization ID and name - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/determine-org-id-name)
* Content Source: [power-platform/admin/determine-org-id-name.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/determine-org-id-name.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@luconsta 
Thanks for the suggestion. We'll update the topic with that info.
