### ISSUE TITLE
Etape manquante présente dans la doc anglause

### ISSUE THREAD

**Issue by Philippe-ecomcs** [MicrosoftDocs/power-platform#638]
Merci de mettre à jour la procédure avec les éléments déjà présent dans la version en-US.
Cela nous fera gagner beaucoup de temps.

Version US ok 
![image](https://user-images.githubusercontent.com/80249823/110671149-7ddfd800-81ce-11eb-9d0f-338d771bf1a8.png)

Version FR KO !!
![image](https://user-images.githubusercontent.com/80249823/110671172-82a48c00-81ce-11eb-8406-f8db1f4b09db.png)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e14181d4-574f-95e3-c2c9-545116549c9b
* Version Independent ID: bf449b92-6756-e08a-a58c-d561e36947cb
* Content: [Configurer les composants de gouvernance - Power Platform](https://docs.microsoft.com/fr-fr/power-platform/guidance/coe/setup-governance-components)
* Content Source: [power-platform/guidance/coe/setup-governance-components.md](https://github.com/MicrosoftDocs/power-platform-pr.fr-FR/blob/live/power-platform/guidance/coe/setup-governance-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
@jimholtz There seems to be a difference in viewing the content in en-us and in fr-ko in our docs. Is there a delay in the translation or is there anything I need to do on my side to get this corrected?

**Comment by manuelap-msft** [comment]
I believe this is correct now, the translation lags a bit behind the English version.
