### ISSUE TITLE
Broken Link on Page

### ISSUE THREAD

**Issue by gtageek** [MicrosoftDocs/power-platform#639]
The FAQ link labelled "FAQ: Internet Explorer 11 deprecation for Dynamics 365 and Microsoft Power Platform Products" is broken on this page: https://docs.microsoft.com/en-us/power-platform/important-changes-coming#internet-explorer-11-support-for-dynamics-365-and-microsoft-power-platform-is-deprecated

Clicking on the FAQ link opens a page at https://businessapplications.transform.microsoft.com/ and expects the user to login.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and customer engagement apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/important-changes-coming.md)
* Service: **power-platform**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by jimholtz** [comment]
@gtageek 
Thanks for bringing this to our attention. We'll remove the link and replace if a suitable replacement is found.
