### ISSUE TITLE
Power Virtual Agents - Per User license not available in Admin portal

### ISSUE THREAD

**Issue by cjscholten** [MicrosoftDocs/power-platform#64]
In 'power-virtual-agents/requirements-licensing.md', 
under section 'Buy tenant and per user licenses', it says 
'Search for and select the subscriptions you want to purchase'.

However, the Admin portal 'store' doesn't have the license mentioned later as 'Power Virtual Agents user license'. Only the tenant license is available.

**Comment by mvakoc** [comment]
Hi, you will need to use the non-preview version of the admin portal. I've updated the documentation accordingly.
