### ISSUE TITLE
Request: Minimum DLP Requirements for CoE

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/power-platform#641]
Would you be able to create a page documenting the minimum Power Platform DLP requirements for the environment running the CoE?  I think this would be good reference material when security teams need to review. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

our DLP requirements and all other pre-requisites are listed under https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites 

We'll add a note from the setup instructions to the pre-requisites with our next docs updates! Thanks for the feedback!

**Comment by robertcaretta** [comment]
Thank you. So Power BI doesn't need to be in the DLP??  The CoE uses a Power BI dashboard.

**Comment by manuelap-msft** [comment]
Yes, it is! We just noticed this as well - we introduced Notifications with the latest release and have not yet updated the documentation. It's on our to-do list for the next docs update.

We don't use the Power BI connector in our apps or flows, so Power BI doesn't need to be in the DLP policy. The Power BI dashboard is separate from DLP.
