### ISSUE TITLE
Additional Microsoft Teams settings not shown

### ISSUE THREAD

**Issue by Dlutchy** [MicrosoftDocs/power-platform#642]
[Enter feedback here]
In Step 5 under Additional Microsoft Teams settings > System Settings > General tab you show a screen shot of 2 options for Microsoft Teams Integration. 

I cannot see these options on my Tenants Systems Settings. Do you know why?

thanks
Darren

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c8b0956-de34-a40f-2ccd-913528e7e328
* Version Independent ID: fe934752-f895-622a-2d12-776320ac43cd
* Content: [Enable Microsoft Teams Integration for model-driven apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/enable-teams-integration)
* Content Source: [power-platform/admin/enable-teams-integration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/enable-teams-integration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Dlutchy 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. If this issue still exists:

Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
