### ISSUE TITLE
document updation

### ISSUE THREAD

**Issue by PranjaliShetty** [MicrosoftDocs/power-platform#643]
documentbody attribute of annotation entity is not supported for Data Export Service.
reference for confirmation: https://portal.microsofticm.com/imp/v3/incidents/details/197359010/home 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#entities-that-dont-support-data-export)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by jimholtz** [comment]
@PranjaliShetty 
Taking to internal thread.
