### ISSUE TITLE
Wrong anchor in the page?

### ISSUE THREAD

**Issue by anmateusMSFT** [MicrosoftDocs/power-platform#644]
The link on 

Archive unused apps
App and Flow Archive and Clean Up – Start Approval and Check Approval (flows)

takes you to the section

https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#flows

It doesn't seem right.
It should point to this https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#admin--archive-and-clean-up-v2-start-approval-for-apps or this: https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#admin--archive-and-clean-up-v2-start-approval-for-flows
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3445b35a-114e-010d-a42b-3d738fa68c56
* Version Independent ID: 87fcef34-4b4a-cee9-f171-e1bd1e8ec970
* Content: [Governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#flows)
* Content Source: [power-platform/guidance/coe/governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/governance-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
This has been updated yesterday!
