### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by sqlarcher** [MicrosoftDocs/power-platform#646]
Currently in the prerequisites listed in the following URL (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites) the current licenses are referred to:

Quote:
"_Power Apps per user or per app or Power Automate per user or per flow license or a combination of these licenses._"

To install the CoE core components, the service account used should also be sufficiently licensed for MS Teams, or you are not able to register the component.

This is reflected in the following error captured from dev tools:

**`{"code":"Forbidden","message":"Failed to get license information for the user. Ensure user has a valid Office365 license assigned to them.","innerError"....}`**

If any error is received on configuring the connection(s) used by the CoE the import of the solution cannot continue.

Can the full list of required licenses outside of just Power Platform licenses be updated in the documentation?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
This has been added now.
