### ISSUE TITLE
Have text along side of screenshots.

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/power-platform#647]
Please note that the expand properties are needed in order to get the capacity back.  Also put text in to show that it is a comma separating the properties.addons and properties.capacity 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 816403f3-0104-3d3a-e889-bf0d4cf9bcae
* Version Independent ID: 0f0d27e8-2aaa-0d7c-ea3e-fe949bd9b3b1
* Content: [Preview: Programmability and extensibility - Tutorial - Create a daily capacity report - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report)
* Content Source: [power-platform/admin/programmability-tutorial-create-daily-capacity-report.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/programmability-tutorial-create-daily-capacity-report.md)
* Service: **power-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by jimholtz** [comment]
@samadane 
Thanks for the feedback. Taking to internal thread.
