### ISSUE TITLE
Include prereqs at the top

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/power-platform#648]
Consider adding prereqs at the top.  What type of O365 role is needed to hit the api, link to app registration, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 816403f3-0104-3d3a-e889-bf0d4cf9bcae
* Version Independent ID: 0f0d27e8-2aaa-0d7c-ea3e-fe949bd9b3b1
* Content: [Preview: Programmability and extensibility - Tutorial - Create a daily capacity report - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report)
* Content Source: [power-platform/admin/programmability-tutorial-create-daily-capacity-report.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/programmability-tutorial-create-daily-capacity-report.md)
* Service: **power-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by jimholtz** [comment]
@samadane 
Thanks for the feedback. Taking this to internal thread.
