### ISSUE TITLE
Clear what happen after transition period and the cost expected for licensing

### ISSUE THREAD

**Issue by paololec** [MicrosoftDocs/power-platform#649]
Need more transparent and trust information and a clear vision, a "transitional period" of undefined duration and a "capacity add-ons" at undefined price and "we change any condition/functionality/licensing every few months" is not acceptable, all my customers say to stay away from this Microsoft solution and are very dissappointed (that rember infopath and workflow 2010 deprecation/dead causing a big waste of money, time and disservice for operationals)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@paololec 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
