### ISSUE TITLE
License related query

### ISSUE THREAD

**Issue by samikshashetty** [MicrosoftDocs/power-platform#65]
As I know :

 Per App plan  has 30 licenses for one app,  basically we can share one app to 30 users.

What is Per User Plan then?... I do know that  it has unlimited app access.. But what about the licenses?... How many users can access it once we share?.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Licensing overview - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus#feedback)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@samikshashetty 
Please review and see if that answers your question:
https://go.microsoft.com/fwlink/?linkid=2085130
