### ISSUE TITLE
Text values important to the scenario should be provided as text and not only as a screenshot

### ISSUE THREAD

**Issue by seanmcne** [MicrosoftDocs/power-platform#650]
For the screenshots which contain text relevant to the topic ($expand and api version#) these should be provided as text in a table as well as in the screenshot. For example the $Expand parameter is hard to decipher between a period and a comma. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 816403f3-0104-3d3a-e889-bf0d4cf9bcae
* Version Independent ID: 0f0d27e8-2aaa-0d7c-ea3e-fe949bd9b3b1
* Content: [Preview: Programmability and extensibility - Tutorial - Create a daily capacity report - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report)
* Content Source: [power-platform/admin/programmability-tutorial-create-daily-capacity-report.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/programmability-tutorial-create-daily-capacity-report.md)
* Service: **power-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by seanmcne** [comment]
Dup of #647

**Comment by jimholtz** [comment]
@seanmcne 
Thanks for the feedback. Taking this to internal communication.
