### ISSUE TITLE
Is Parature mis-titled as "Armature"?

### ISSUE THREAD

**Issue by krouskop** [MicrosoftDocs/power-platform#651]
I think the section talking about the **Parature** deprecation is mis-titled as "_Armature_"?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and customer engagement apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/important-changes-coming.md)
* Service: **power-platform**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by jimholtz** [comment]
@krouskop 
Thanks for the feedback. This looks to have been corrected.
