### ISSUE TITLE
REQUEST:  Detailed Flow Documentation

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/power-platform#652]
Would it be possible to provide additional documentation for all of the flows? 

1. Within each flow please add a description of what it does. 

2. An excel file with a detailed breakdown would be really handy. Example columns might be:

Solution | Flow Name | Type | Interval | Schedule | Description

Solution:  {Core|Governance|Nurture}
Type: {Scheduled|Automated}
Interval: {Hourly|Daily|Weekly|Monthly}
Schedule:  Time when flow runs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
We have added more details here and a table overview to the docs. We are not going to be able to keep an excel file up to date with every release, but will have this information in docs.
