### ISSUE TITLE
What is the definition of a Dataverse Environment?

### ISSUE THREAD

**Issue by JohnYu500** [MicrosoftDocs/power-platform#653]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22df4a82-a072-f324-8500-2e62fe120d3a
* Version Independent ID: d4fb1c9b-7dfc-5b4a-7e07-f6515b150e25
* Content: [Solution layers in Power Apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/solution-layers-alm)
* Content Source: [power-platform/alm/solution-layers-alm.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/solution-layers-alm.md)
* Service: **power-platform**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@JohnYu500 - You'll find an overview and can continue reading to go much deeper here: [What is Dataverse?](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-intro)

Closing issue.
