### ISSUE TITLE
so... how do you do it?? I'm reading your document titled Assigning Users to Security Roles. Lots of blah blah blah, nothing about how to do it. As usual. Either change the titlet to About Assigning... or put some steps in there about how to do it. 

### ISSUE THREAD

**Issue by peteravila** [MicrosoftDocs/power-platform#654]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74e68eaf-8937-279f-d707-ac7a1d2c2ff6
* Version Independent ID: bb4d936b-bac2-411e-9afd-d0d7ca0c88c3
* Content: [Security roles and privileges - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/security-roles-privileges#assigning-security-roles)
* Content Source: [power-platform/admin/security-roles-privileges.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/security-roles-privileges.md)
* Service: **power-platform**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by jimholtz** [comment]
@peteravila 
Thanks for the feedback. The security and user management content is due for a major rewrite. We'll add your feedback to the list of content requests.
