### ISSUE TITLE
Where are PowerApps and PowerAutomate Flows in the Default Environment displayed ?

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/power-platform#655]
Hi

Where are PowerApps and PowerAutomate Flows in the Default Environment shown in the CoE ?

eg those generated by SharePoint.

Thanks

Nigel

**Comment by manuelap-msft** [comment]
Hello,

apps and flows from Default environment are displayed like from any other environment and on all pages you should find an "Environment" filter (in the grey area on the right hand side) to filter down to only display resources in the Default environment.

For SharePoint specific, see https://github.com/microsoft/powerapps-tools/issues/848

Thank you for using the CoE,
Manuela
