### ISSUE TITLE
A lot of detail missing on the Data Integrator

### ISSUE THREAD

**Issue by sy-huss** [MicrosoftDocs/power-platform#656]
[Enter feedback here]

There is a lot of detail and documentation missing on the Data Integrator.

1. UI has changed, this needs to be updated.
2. Integration Key - where is the usage of this documented?
3. How do you stop a test integration or migration job?

A lot is missing.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd884343-7f2e-9765-4860-4cb4981a908e
* Version Independent ID: efe70284-6f99-698c-9406-802595535d97
* Content: [Integrate data into Microsoft Dataverse - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/data-integrator)
* Content Source: [power-platform/admin/data-integrator.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/data-integrator.md)
* Service: **power-platform**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sabinn-msft** [comment]
We are recommending all our customers to start using dual-write (https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/dual-write-home-page). I request you review this for your use to integrate Finance and operations apps with Dataverse
