### ISSUE TITLE
Error in text

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/power-platform#657]
"File Size (Bytes) – Is Greater Than - In the text box, type a byte value, such as 1,048,576 (1MB in binary)."

Thats not 1 MB in binary, its 1 MB to bytes. Binary would be 100000000000000000000. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9c9aae-ceaa-2e78-3752-2770327f49a7
* Version Independent ID: acd2ddc9-6225-92e8-2636-2a02437c3d82
* Content: [Free up storage space - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/free-storage-space)
* Content Source: [power-platform/admin/free-storage-space.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/free-storage-space.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@StuBeck32 
Thanks for the suggestion. We'll revise for clarity.

**Comment by StuBeck32** [comment]
This was closed but is still not updated.
