### ISSUE TITLE
Need clarification on PowerApps Licensing 

### ISSUE THREAD

**Issue by Jayesh040** [MicrosoftDocs/power-platform#66]
We want to share PowerApps with 40 users but don't want to buy/assign licenses for each user, What would be the best option for this ?
PS : We are okay buying licenses for admin.

 Kindly, Suggest the licensing options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Licensing overview - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus#feedback)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by Jayesh040** [comment]
Can anyone help me with this ?

**Comment by simb55** [comment]
I need answers to this as well.
A guest who tries to use our organizations PowerApps gets the message, that he needs a license assigned, either in his home tenant or the tenant he is a guest in (our tenant).
We tested this for another Office 365 user and assigned him an E5 license in a test tenant. He still receives this message, so it seems the first option does not work atm.

**Comment by jimholtz** [comment]
@Jayesh040 
Power Apps does require licenses for end users using the app. Based on the connectors used in the app, the end user license can be an Office 365 license or a Power Apps license. Within Power Apps, based on how many apps are used by each user, you can either user per app license or per user license. 

Users creating the app don't require licenses and can create any app with any connector, however end users using it do require licenses.

**Comment by jimholtz** [comment]
@simb55 
Bring your own license (BYOL) works with a couple of caveats. How the guest user is invited to the directory determines whether BYOL works. 
•	Specifically, Azure AD guests of type External Azure Active Directory or Microsoft Account, BYOL works. (Guests in state 1 and state 2 in this documentation: https://docs.microsoft.com/en-us/azure/active-directory/b2b/user-properties) 
•	If the guest user is ‘DirSync-ed’ to Azure AD, BYOL is currently not supported. Guests in state 3: https://docs.microsoft.com/en-us/azure/active-directory/b2b/user-properties)

**Comment by Jayesh040** [comment]
@jimholtz 
Can you please help me what are differences between PowerApp License I get with Office 365 and PowerApps standalone license.
Like is there anything difference with capabilities.
Because PowerApp per app per use license costs $10, where Office 365 E3 license costs $8 which also includes license for other services.

**Comment by simb55** [comment]
Thank you jimholtz,

@Jayesh040, if you have an Office 365 license, you will not be able to use apps, that contain a premium connector or to build apps with premium connectors. This would be for example the SQL connector. For those premium connectors you would need a PowerApps plan.
