### ISSUE TITLE
Power Platform Build Tools: Backup Environment Build Task not working for GCC

### ISSUE THREAD

**Issue by sendsunilmail** [MicrosoftDocs/power-platform#660]
Service Connection point to a URL in GCC.

Environment not being found

; Error=; Message=The environment '' could not be found in the tenant 'xxx-xxx-xxx-xxx-xxx'.; Internal=System.Net.HttpWebResponse}

User has admin rights to all environments and can create a backup from https://gcc.admin.powerplatform.microsoft.us/

**Comment by jimholtz** [comment]
@sendsunilmail 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/

**Comment by sanjeev40084** [comment]
@sendsunilmail were you able to get this resolved? i am running into same issue now.
