### ISSUE TITLE
CoE Power BI Dashboard - Dataset Refresh Schedule

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/power-platform#662]
Please add an additional step at the bottom of this documentation to remind people to schedule a dataset refresh schedule.
Power BI Report -> Settings -> Datasets -> Schedule refresh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c365c412-6317-0eb4-b7a1-0a5cc84b1cbd
* Version Independent ID: 9e39031d-66dd-bf29-1b5c-a93608badc60
* Content: [Set up the Power BI dashboard - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi)
* Content Source: [power-platform/guidance/coe/setup-powerbi.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-powerbi.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

with the April release in a few weeks time, we're changing the Power BI to use Direct Query and then a schedule refresh will not be required any more as the data will always reflect what's in Dataverse.

Thank you for the feedback and for using the CoE
Manuela

**Comment by mitchonfire** [comment]
I have tried both versions of the .pbit, both work in power bi desktop (I performed the production env deployment)
BUT
When published to the Power BI Service, the OAuth2 dialog just hangs and remains blank.
![image](https://user-images.githubusercontent.com/17173734/135399052-4fe75247-62f3-4318-a377-d86f58a1b4b5.png)
Any advice?

**Comment by manuelap-msft** [comment]
Hello,

this seems to be a product issue, not related to the CoE Starter Kit. Please raise a support ticket through your regular support channels, https://docs.microsoft.com/en-us/power-platform/admin/get-help-support
