### ISSUE TITLE
How to automatically bulk delete the duplicate records thus detected? 

### ISSUE THREAD

**Issue by abhaybhangale** [MicrosoftDocs/power-platform#664]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82accdd0-bbe1-8292-a855-5767b26c53e1
* Version Independent ID: 74ea4feb-ebb6-994e-c12e-69d4b23b873a
* Content: [Run bulk system jobs to detect duplicate records - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/run-bulk-system-jobs-detect-duplicate-records)
* Content Source: [power-platform/admin/run-bulk-system-jobs-detect-duplicate-records.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/run-bulk-system-jobs-detect-duplicate-records.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@abhaybhangale 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
