### ISSUE TITLE
Feature Request: Support for Certificate-based Authentication

### ISSUE THREAD

**Issue by bo-stig-christensen** [MicrosoftDocs/power-platform#666]
As far as I can see, Power Platform Build Tools support only user/pass (deprecated) or Client Secret auth flow. - Although, when creating new Service Connections only the Client Secret flow is configurable.

More projects are starting to use Certificate-Based Authentication, which is also Microsoft's recommendded production setup.

**Comment by jimholtz** [comment]
@bo-stig-christensen 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
