### ISSUE TITLE
Feature Request: Support for Connection String instead of Service Connections

### ISSUE THREAD

**Issue by bo-stig-christensen** [MicrosoftDocs/power-platform#667]
Currently Power Platform Build Tools only support defining a connection to an environment via Azure DevOps Service Connections, which is not that flexible considering the need for a more dynamic configuration, e.g. Script-based.

It would be a huge thing to be able to define a Connection String for the tools to use instead of relying solely on Service Connections (which is of course nice for some, given the UI). - For Power Users / Developers, a Connection String is far more valuable.

Using Connection Strings also gives the flexibility to use new Service Client features released by Microsoft immediately and not having to await a new release of Power Platform Build Tools.

Connection Strings simply provide for at much more flexible configuration, including dynamically generated connection strings from previous tasks in a pipeline, based on whatever parameters / situation.

**Comment by jimholtz** [comment]
@bo-stig-christensen 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
