### ISSUE TITLE
How can we add Azure DevOps Repos instead Github as a repo 

### ISSUE THREAD

**Issue by bhanumuddhana** [MicrosoftDocs/power-platform#668]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7aec3bb-623f-4cfd-2886-d83f4fbff5f3
* Version Independent ID: 3ddb998e-8664-8527-50e0-7d8a271cac55
* Content: [ALM Accelerator for Makers - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-components)
* Content Source: [power-platform/guidance/coe/almaccelerator-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/almaccelerator-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

this is currently not possible, but we're working on releasing a version of this that works with Azure DevOps. Stay tuned for updates here in the coming weeks!

Thank you
Manuela
