### ISSUE TITLE
Entities are now called tables

### ISSUE THREAD

**Issue by gkccf-kaffenberger** [MicrosoftDocs/power-platform#669]
Entities are now called tables. This page is critical because it is an essential step in using Power Automate Desktop or abandoning it. I haven't done a lot with flows before this, so you should assume this is my first encounter with dataverse. 
Documentation says click entities. No Entities, so I click table because I heard that entities are now tables. Can't create a database. I only have the option to create an environment. I'm done with trying Power Automate Desktop for today. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3f6c7c-bb0e-ad08-b081-4d19223ef823
* Version Independent ID: 31baba85-90bf-511b-7a0b-c77861d72f64
* Content: [Add a Microsoft Dataverse database - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-database)
* Content Source: [power-platform/admin/create-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@gkccf-kaffenberger 
Thanks for the feedback. The terminology has been updated. Screenshots to follow. If you're still having issues creating a database, please contact support: https://powerapps.microsoft.com/support/
