### ISSUE TITLE
Licensing Costs

### ISSUE THREAD

**Issue by davidvansickle** [MicrosoftDocs/power-platform#67]
It's so frustrating to begin projects with projected costs based on existing licensing only to have that superseded by enormously complex and far more expensive licensing at renewal.  It causes hesitancy for adoption of new technology when customers are continually waiting for the REAL cost. This completely has stagnated a 1500 seat 365 E5 plan that considered adopting Power Automate (Power Apps & Flow). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#feedback)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@davidvansickle 
Thanks for your feedback. I've passed this on to the Product team.
