### ISSUE TITLE
RBAC roles

### ISSUE THREAD

**Issue by s0041464** [MicrosoftDocs/power-platform#671]
Is there a way to RBAC this particular permission?
We don't want to give our CRM admins GA or Exchange Admin just to approve mailboxes

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d917db-1300-f212-067f-4ac688c18bec
* Version Independent ID: d19b118a-eddc-dc4f-75ad-2640f02aaeb4
* Content: [Connect to Exchange Online - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/connect-exchange-online#approve-email)
* Content Source: [power-platform/admin/connect-exchange-online.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/connect-exchange-online.md)
* Service: **power-platform**
* GitHub Login: @revachauhan
* Microsoft Alias: **rechauha**

**Comment by jimholtz** [comment]
@s0041464 
Sorry for the delayed response. We're looking into adding scenarios not requiring global admin approval as noted:
https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-online#require-admin-approval

RBAC is not currently planned.
