### ISSUE TITLE
The instructions for allowing global admins to allocate capacity (add on) do not work

### ISSUE THREAD

**Issue by inzi** [MicrosoftDocs/power-platform#672]
Despite being a global admin, and following the directions on this page for configuring global admins to allocate capacity, the capacity admin portal still instructs the global admin to contact the admin to get permission to assign an add-on app pass to the environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0cbf8c-5c12-5aa2-3786-392d0f498303
* Version Independent ID: 2774f5ca-1c86-4fe6-c296-6f7f45aa6702
* Content: [Capacity add-ons for Power Apps and Power Automate - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on)
* Content Source: [power-platform/admin/capacity-add-on.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-add-on.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@inzi 
Thanks for bringing this to our attention. We'll monitor this feature and documentation for this issue. If you continue to have this issue, please contact support: https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on
