### ISSUE TITLE
Update PS Script to have consistent use of AZ module

### ISSUE THREAD

**Issue by shammyowens** [MicrosoftDocs/power-platform#675]
Hi

The following document has a PS script to create keyvault for data export service.  It is a bit inconsistent in its use of AzureRM and AZ modules, can it be updated to AZ only please?

https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md
 e.g. change New/Get-AzureRmResourceGroup with New/Get-AZResourceGroup
New/Get-AzureRmKeyVault to New/Get-AZRMKeyVault

Thanks
Sam

**Comment by jimholtz** [comment]
@shammyowens 
Thanks for the feedback. We've updated the content.
