### ISSUE TITLE
Slight clarification on configuring fields steps

### ISSUE THREAD

**Issue by cwanja** [MicrosoftDocs/power-platform#676]
Only suggestion is on step 4 under [Configure searchable fields for Relevance Search](https://docs.microsoft.com/en-us/power-platform/admin/configure-relevance-search-organization#configure-searchable-fields-for-relevance-search) would be to include the word "Double click the view you want to edit". Currently says "Double-click Quick Find View" and I was think that was a button or something. Was not immediately clear that is the _view_ you are wanting to edit. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f4b53c-095c-4bf9-46dd-62299f2568e5
* Version Independent ID: 92a06c7b-d9b6-1a85-fb46-8378273a5994
* Content: [Configure Relevance Search to improve search results and performance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/configure-relevance-search-organization)
* Content Source: [power-platform/admin/configure-relevance-search-organization.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/configure-relevance-search-organization.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by cwanja** [comment]
Or maybe I am misunderstanding the documentation. Is the _only_ view Relevance Search works against is the "Quick View"?

**Comment by jimholtz** [comment]
@cwanja 
Thanks for the input. We've revised that step for clarity and will publish the update today.
