### ISSUE TITLE
Questions Given Need Answers

### ISSUE THREAD

**Issue by daryllabar** [MicrosoftDocs/power-platform#677]
The questions in this section of the document need answers or resources.

> **You should answer questions such as:**
> 
> How many development environments do I need?
> 
> How can I automatically provision environments from source code?
> 
> What are the dependencies on my environments?

How does one determine the # of development environments needed?  Where does one go to learn how to provision environments from source code?  What is a dependency in this situation, and what sort of dependencies do I need to be concerned about?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c863c91e-c9a1-8064-2dac-ffba215afb94
* Version Independent ID: a6e75e07-5043-44e8-28fe-fb83ef690969
* Content: [Environment strategy for ALM - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/environment-strategy-alm)
* Content Source: [power-platform/alm/environment-strategy-alm.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/environment-strategy-alm.md)
* Service: **power-platform**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@daryllabar - The link to the [Establishing an environment strategy](https://docs.microsoft.com/en-us/power-platform/guidance/adoption/environment-strategy) article from the article you referenced has more information about what goes into determining the number (and type) of environments your organization needs. The short answer is it depends on your organization's needs. The longer answer is to take all the strategic aspects into consideration as described here: [Developing a strategy](https://docs.microsoft.com/en-us/power-platform/guidance/adoption/environment-strategy#developing-a-strategy)

Closing issue.
