### ISSUE TITLE
Typo on "updated"

### ISSUE THREAD

**Issue by danfay** [MicrosoftDocs/power-platform#678]
Type on "updated" - Here's the line
Configured: This app has been configured to an environment. It can be reconfigured to a different environment or configuration to current environment can be udpated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7afcf1bf-4570-e586-a016-3273589910cf
* Version Independent ID: 47488450-bc47-aead-2c22-7c0989de4cbb
* Content: [Manage Dynamics 365 apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-apps)
* Content Source: [power-platform/admin/manage-apps.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/manage-apps.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@danfay 
Thanks for bringing this to our attention. We'll get this corrected.
