### ISSUE TITLE
Add screenshot for 'Note' export

### ISSUE THREAD

**Issue by tombyang** [MicrosoftDocs/power-platform#68]
Right now there is a screenshot for showing 'Bot Content' checked, but it's easy to miss that you need to export 'Note' as well. This is step 4. Please add a screenshot below 'Bot Content', showing the 'Note' entity checked. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756e108a-a50d-979a-e666-be528905039c
* Version Independent ID: 5424086c-2f63-7048-a472-2cab1649687b
* Content: [Responding to GDPR Data Subject Export Requests - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/gdpr-export)
* Content Source: [power-virtual-agents/gdpr-export.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-virtual-agents/gdpr-export.md)
* Service: **dynamics-365-ai**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
I've made this update and it should be live.
