### ISSUE TITLE
The linked page does not exist.

### ISSUE THREAD

**Issue by noriji** [MicrosoftDocs/power-platform#680]
「Power Virtual Agents のライセンス」部分のURL先のページが404になっている。
（https://docs.microsoft.com/ja-jp/power-virtual-agents/requirements-licensing-subscriptions.md）

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [ライセンスの概要 - Power Platform](https://docs.microsoft.com/ja-jp/power-platform/admin/pricing-billing-skus#feedback)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by iaanw** [comment]
Hey @jowilco looks like an issue in the ja-jp repo for the pricing-billing-skus page. It looks like an errant .md in the link.

**Comment by jowilco** [comment]
@noriji 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
