### ISSUE TITLE
Email Templates documentation needs updating

### ISSUE THREAD

**Issue by roryd** [MicrosoftDocs/power-platform#681]
- The current documentation refers to an Insert/Update button, which is non-existent.
- The documentation needs to be updated as to how to include non-standard tables and fields using the {!EntityLogicalName:FieldLogicalName;Default Text} syntax along with the special syntax for Lookup fields
- A list of fields that cannot be dynamically resolved (e.g., multi-select options or choices)
- Other limitations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eae83e71-1253-2894-8a38-669d26e100ec
* Version Independent ID: a2c48126-6401-3ea4-42fe-1c98a1e2cc55
* Content: [Create templates for email - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-templates-email)
* Content Source: [power-platform/admin/create-templates-email.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-templates-email.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@roryd 
Thanks for the feedback. We've passed this information on to the product group for attention.
