### ISSUE TITLE
Secrets?

### ISSUE THREAD

**Issue by readyxrm** [MicrosoftDocs/power-platform#682]
What are we supposed to enter for the secrets on GitHub?  The password for the Dataverse account?  Or other?  The wording is unclear.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d3a97-f062-9c7c-a5b6-8ec69178e1bc
* Version Independent ID: 476f4f57-b869-c759-74cc-beb4e2deaa26
* Content: [Set up ALM Accelerator for Makers components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator)
* Content Source: [power-platform/guidance/coe/setup-almaccelerator.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almaccelerator.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by mikefactorial** [comment]
Hey Nick, it is the password for the Dataverse account. We have it in the backlog to fix that part of the doc to make it more clear. Thanks for reaching out!

**Comment by mikefactorial** [comment]
Closing this issue as no action required from our team at this time.
