### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by BetimBeja** [MicrosoftDocs/power-platform#683]
There is a broken link in the Dependency Entity (Table) definition
![image](https://user-images.githubusercontent.com/11160171/114181861-53567b80-9942-11eb-9d38-cca27bf372ef.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ab5250-fc17-78d3-6a3b-fd630a2400d8
* Version Independent ID: d890b9f9-324c-e3b6-7bfd-f8b3e0fe8c65
* Content: [Dependency tracking for solution components (Microsoft Dataverse) - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/dependency-tracking-solution-components)
* Content Source: [power-platform/alm/dependency-tracking-solution-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/dependency-tracking-solution-components.md)
* Service: **power-platform**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by laschultz** [comment]
@jimholtz I fixed the link and created a PR for this bug.

**Comment by Mattp123** [comment]
@BetimBeja - Thank you for your feedback. The link has been fixed.

Closing issue.
