### ISSUE TITLE
Why we need Per User / Per Flow license for Dataverse for Teams COE?

### ISSUE THREAD

**Issue by krishnaVSU2020** [MicrosoftDocs/power-platform#684]
Hi Team,

Congratulations on your new release of COE with Dataverse for Teams (D4T), but I am a little confused on the below point.

Feature | Dataverse for Teams environment | Production environment
-- | -- | --
Syncing inventory to Dataverse tables | Yes, will require a Power Automate Per User/Per Flow license | Yes, will require a Power Automate Per User/Per Flow license

When we are configuring in Dataverse for Teams why we need the Per User / Per Flow license? and what you exactly mean by Syncing inventory to Dataverse tables. 

**My understanding:**
This only applies to the organizations who want to sync the data from D4T tables to Classic Dataverse Tables. If my understanding is right please confirm back on this.

Once again congratulations on your new milestone.

Regards,
Krishna Vandanapu
**Business Applications MVP**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#production-vs-dataverse-for-teams-environment)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

the CoE Starter Kit uses flows to look at all environments, apps and flows in your tenant and store their information in Dataverse tables - we call this syncing, and the flows are called Admin | Sync Template in the Core Components.

Due to API call throttling limits and pagination settings in these flows, a Power Automate license will be required to run these flows in any environment type.

Thanks for exploring the CoE 
Manuela

**Comment by krishnaVSU2020** [comment]
Hi Manuela,

Thank you for the reply, I see the same throttling limits and pagination settings as 100K in regular COE also but it did not force me to get the Per User License.

So I am not sure why we need to get Per User license only when we configure COE with Teams.

Regards,
Krishna Vandanapu
