### ISSUE TITLE
Not able to run the flow CLEANUP - Admin | Sync Template v3 (Check Deleted) in DataVerse for Teams

### ISSUE THREAD

**Issue by krishnaVSU2020** [MicrosoftDocs/power-platform#685]
Hi Team,

I am configuring COE for Data Verse for Teams, when I try to run the Flow CLEANUP - Admin | Sync Template v3 (Check Deleted) I see the below error:

I see this issue in various actions of the flow. However, these actions went well when I change the pagination count to 5000. This works fine for a small company but doesn't work for organizations with more than 5K environments. 

I need to do the same for all the other actions in each flow maybe we need to look at this, if not user needs a Per User / Per Flow license.

**Error:**
Your flow could not turn on: CLEANUP - Admin | Sync Template v3 (Check Deleted). Error: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Environments' of type 'OpenApiConnection' at line '1' and column '7941' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

Regards,
Krishna Vandanapu
Business Applications MVP

**Comment by manuelap-msft** [comment]
Hello,

In this repository we only address issues with documentation (such as incorrect setup instructions or missing steps). Any issues with the actual CoE Starter Kit need to be raised via the CoE Starter Kits repository https://github.com/microsoft/powerapps-tools/issues

However, reading the below I can tell you the issue you're experiencing is because the user trying to run the flow does not have the accurate license assigned. Our pagination settings are high on all actions to ensure the kit works well for all tenant sizes. You can find out more about Power Automate performance profiles and limitations here https://docs.microsoft.com/en-us/power-automate/limits-and-config

Thanks for using the CoE
Manuela

**Comment by krishnaVSU2020** [comment]
Yes I agree I have purchased the Per-User license and configured the Flows. However, I never purchased the Per-User License while I am configuring the classic COE tool kit.

Please help me if my understanding is wrong.

**Comment by manuelap-msft** [comment]
Yes, your understanding here is incorrect. Because of our pagination policy you would need a premium licence in both regular and Teams environments.

**Comment by krishnaVSU2020** [comment]
I am 100% sure I have not purchased Per-User license last time when I configured the previous version V 1.85.

Sorry, This is the question from my customer because my team configured the V 1.85 on personal tenants without a premium license but it went well. I can reproduce this for you if that helps.

**Comment by manuelap-msft** [comment]
How license and pagination limits are enforced in the product is out of scope for the CoE Starter Kit - we have always documented and required a premium license being required to turn on the flows.

Here are the performance profiles per license for flows:
![image](https://user-images.githubusercontent.com/55705669/114362068-d3612900-9b6e-11eb-8d50-b67b16349e17.png)

And here is the pagination limit per license type - as you can see, 100,000 is only supported for performance profiles that aren't Low. All actions in the CoE Starter Kit are set to 100,000 - thus, it would never have worked for Low performance profiles. This has been the case going back a year or so.
![image](https://user-images.githubusercontent.com/55705669/114362141-eaa01680-9b6e-11eb-94e8-8e77049d1ced.png)

Unfortunately, I'm unable to help you further here but if you feel license limits are incorrectly enforced you may have to raise a support ticket for the product.
