### ISSUE TITLE
Support for Managed Patches.

### ISSUE THREAD

**Issue by craig-lund** [MicrosoftDocs/power-platform#686]
Upon extensity using and  testing the Package Deployment tool I have found an issue I don't see a option to change. When utilizing patches and performing updates to managed patches the tool tries to perform a Hold and upgrade pattern. This fails, as the system does not support that for patches. This is being done through 100% automation. 

I looked through the available parameters that can be passed, but can' seem to find on for forcing update rather than upgrade. 

If I am missing it please let me know. Otherwise, this seems to be a needed capability. 

Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78dd2e38-9d0c-3bbf-0db3-138416d4063b
* Version Independent ID: 51455bd4-3294-0ccd-2b1b-6d9857c0f50f
* Content: [Package Deployer tool - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/package-deployer-tool)
* Content Source: [power-platform/alm/package-deployer-tool.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/package-deployer-tool.md)
* Service: **power-platform**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by jimholtz** [comment]
@craig-lund 
Sorry for the delayed response. Thanks for your feedback. For product-related feedback, visit https://aka.ms/ppac-ideas
