### ISSUE TITLE
Get-AdminFlow + Flows imported as disabled

### ISSUE THREAD

**Issue by jlattimer** [MicrosoftDocs/power-platform#687]
Get-AdminFlow (v2.0.112) will not return a flow that was imported into an environment in a disabled state via solution. If the disabled flow is activated then deactivated then it is returned in the results.

Repro steps:
- Create a solution with 2 flows, disable one of them and export the solution as managed
- Import into a new environment (didn't seem to make a different if there were existing flows in the environment or not)
- Run Get-AdminFlow - it will only return the enabled flow - Expected result: it returns both the enabled and disabled flows
- Enable the disabled flow and then once again disable it
- Run Get-AdminFlow - it now returns both flows

**Comment by jlattimer** [comment]
This is in Microsoft.PowerApps.Administration.PowerShell

**Comment by jimholtz** [comment]
@jlattimer 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/

**Comment by rafaelkhalilyullov** [comment]
@jlattimer have you resolved this issue somehow?
I've faced the same issue and didn't find a solution yet

**Comment by spatialcase** [comment]
This is still an issue. Imported flows are not listed by Get-AdminFlow unless they have been turned on.

**Comment by frederikbisback** [comment]
Any update? Facing same issue.

**Comment by davcano** [comment]
Hello. 
I'm facing the same issue. May be weirder than this, because I did a deployment yesterday, all my flows were disabled and impossible to retrieve them with the Get-AdminFlow on the moment. But this morning, my flows are still disabled but I can retrieve them with the Get-AdminFlow command...
Can anyone help us on this?
Best regardes
