### ISSUE TITLE
Import the Package Deployer PowerShell module is outdated

### ISSUE THREAD

**Issue by tdashworth** [MicrosoftDocs/power-platform#692]
This PowerShell module is no longer installed with Nuget but instead with `Install-Module`. 

Please see: 
- https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.PackageDeployment.PowerShell/
- https://www.powershellgallery.com/packages/Microsoft.Xrm.Tooling.PackageDeployment.Powershell/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc997189-b9f4-653c-1188-5663e1a6367e
* Version Independent ID: 3113cafa-56e7-0e45-999f-fa18d50e28cb
* Content: [Deploy packages using Package Deployer and Windows PowerShell - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/deploy-packages-using-package-deployer-windows-powershell#import-the-package-deployer-powershell-module)
* Content Source: [power-platform/admin/deploy-packages-using-package-deployer-windows-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/deploy-packages-using-package-deployer-windows-powershell.md)
* Service: **power-platform**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by tdashworth** [comment]
@Mattp123 @jimholtz Any update on this?

**Comment by Mattp123** [comment]
@tdashworth - Thank you for your feedback. The article has been updated to replace the nuget/register script steps with the Install-Module cmdlet for the package deployer PowerShell module. 

Closing issue.
