### ISSUE TITLE
Please explain, how to enable multi-region environment?

### ISSUE THREAD

**Issue by msvayani** [MicrosoftDocs/power-platform#694]
[Enter feedback here]
This page doesn't say what steps needs to be taken to enable multi-region environment deployment. This is the key information I believe.

Do we need to get multi-geo for the Microsoft 365 tenant? What else?

Default region of Microsoft 365 tenant is Australia, trying to create Dynamics 365 instance in the USA region. Getting this error:

![image](https://user-images.githubusercontent.com/10917140/114820090-d1fb5f00-9e01-11eb-8431-159684c099d1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c5c060a-c1f1-64d8-42fc-dba04c35ac29
* Version Independent ID: 7c4820ec-a83c-141b-dcd2-13fd7c45082b
* Content: [Considerations for choosing multiple environments or tenants - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/multiple-online-environments-tenants#a-multi-environment-deployment)
* Content Source: [power-platform/admin/multiple-online-environments-tenants.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/multiple-online-environments-tenants.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@msvayani 
Sorry you're experiencing this issue. Please create a support request: https://powerapps.microsoft.com/support/.
