### ISSUE TITLE
Customize Business App Tiles

### ISSUE THREAD

**Issue by crmpatrick** [MicrosoftDocs/power-platform#695]
With the move from home.dynamics.com to office.com/apps, the D365 model-driven apps appear as generic purple tiles. Where is the documentation for updating these tiles with custom images?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a027bf-62d9-07f6-c15c-fc0e4d5b8686
* Version Independent ID: f88d00be-be73-a187-c287-66f151073abb
* Content: [Quickly navigate apps with the Microsoft 365 app launcher - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/quickly-navigate-office-365-app-launcher#your-business-apps-are-moving)
* Content Source: [power-platform/admin/quickly-navigate-office-365-app-launcher.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/quickly-navigate-office-365-app-launcher.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@crmpatrick 
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
