### ISSUE TITLE
Typo in Note

### ISSUE THREAD

**Issue by crmpatrick** [MicrosoftDocs/power-platform#696]
https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations?source=docs#what-is-a-microsoft-power-platform-request
Current: there is **_be_** a small set of system
Edit: there is a small set of system

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations?source=docs)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@crmpatrick 
Thanks for bringing this to our attention. This will be corrected soon.
