### ISSUE TITLE
Remove erroneous CoE Starter Kit prereq.

### ISSUE THREAD

**Issue by danielstaleyedf** [MicrosoftDocs/power-platform#697]
Consider removing Content Conversation connector from DLP prereqs as it can no longer be assigned in a DLP policy.

The following page outlines why this is the case:
"The Content Conversion connector is an integral feature of Microsoft Power Platform, used to convert an HTML document to plain text. It applies both to Business and Non-Business scenarios and doesn't store any data context of the content converted through it; therefore, it's not available for classification through DLP policies."
[https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention ](https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
This step has now been removed. Thank you!
