### ISSUE TITLE
"Optimize form performance" link is broken

### ISSUE THREAD

**Issue by cadilu** [MicrosoftDocs/power-platform#7]
"Optimize form performance" link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f749098d-58cd-740f-d6ce-4e7fa3f551be
* Version Independent ID: 665d6606-fb37-220c-87a5-1e5d41ac1c2a
* Content: [Verify network capacity and throughput for clients - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/verify-network-capacity-throughput-clients#feedback)
* Content Source: [power-platform/admin/verify-network-capacity-throughput-clients.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/verify-network-capacity-throughput-clients.md)
* Service: **power-platform**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by jimholtz** [comment]
@cadilu 
Thanks for bringing this to our attention. Link is now fixed.
