### ISSUE TITLE
Failed to locate "Settings > Administration"

### ISSUE THREAD

**Issue by CalvinDale** [MicrosoftDocs/power-platform#70]
I was unable to follow these instructions because I could not find "Settings &gt; Administration". I looked for this menu item in the Power Apps Admin Center, the Power Platform Admin Center, the Office 365 Admin Center, and in the Dynamics 365 Administration Center. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9585e1-b795-d5f5-11d5-494c12f36c5b
* Version Independent ID: 129ca7dc-c826-5657-267f-1601ef025e04
* Content: [Manage Bing Maps for your organizations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/manage-bing-maps-organization)
* Content Source: [power-platform/admin/manage-bing-maps-organization.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-bing-maps-organization.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@CalvinDale 
Thanks for the notice. Updated the steps for Power Platform Admin center.
