### ISSUE TITLE
GCC support missing 

### ISSUE THREAD

**Issue by shsasi** [MicrosoftDocs/power-platform#700]
Looks like GCC orgs are not supported but it is not mentioned in this documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Microsoft Power Platform Build Tools for Azure DevOps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tools.md)
* Service: **power-platform**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by joem-msft** [comment]
Can we get the docs updated for this? We're seeing IcMs where customers are confused.

**Comment by SupportMonkey** [comment]
Please include DoD in edit as well.

**Comment by phecke** [comment]
@shsasi It is mentioned in the first note.

"Microsoft Power Platform Build Tools are currently not available for use in the GCC and GCC High regions."
