### ISSUE TITLE
DLP Editor V2 cannot create policy with scope Single Environment 

### ISSUE THREAD

**Issue by Freesky0605** [MicrosoftDocs/power-platform#703]
The DLP Editor V2 cannot create policy with scope for Single Environment. The error message shows that only one environment is allowed to be selected, which meets the fact that just one environment is selected in the policy. The screenshot shows the error message and also the truth on the review page that just one environment is selected.

![DLP_Editor_Error](https://user-images.githubusercontent.com/15806999/115742479-fa9ad000-a390-11eb-83ca-973ae0e5f7f5.PNG)

**Comment by jimholtz** [comment]
@Freesky0605 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/
