### ISSUE TITLE
References to Common Data Services still here (Dataverse update recommended) 

### ISSUE THREAD

**Issue by bigpix2000** [MicrosoftDocs/power-platform#704]
Images, Screen captures and some text still refer to CDS which adds some confusion for those not familiar with the change. Although I could help edit text, I cannot be the official source for the images (or can I?)  In general, there should be a Dataverse update to the entire CoE docs  THANK YOU! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#feedback)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
All descriptions have been updated to use Dataverse - we will update screenshots over time.
