### ISSUE TITLE
PORTAL and ALM

### ISSUE THREAD

**Issue by astanton-crm** [MicrosoftDocs/power-platform#705]
Power Portal ALM -  Can you add the details for PORTAL and ALM, the older tools are no longer working reliably

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a796fdc-d21d-59c5-2d7a-ec0556558ec0
* Version Independent ID: dc4ca396-3f80-97cc-dc66-19aca5c050e3
* Content: [ALM for developers - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/alm-for-developers)
* Content Source: [power-platform/alm/alm-for-developers.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/alm-for-developers.md)
* Service: **power-platform**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by Mattp123** [comment]
@astanton-crm - I believe you're looking for the accelerator guidance for Power Pages: https://learn.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-powerpages
