### ISSUE TITLE
Page doesn't relate to the 'Previous Capacity Model' alert message

### ISSUE THREAD

**Issue by BrianLeFlem** [MicrosoftDocs/power-platform#708]
On https://admin.powerplatform.microsoft.com/resources/capacity, you get a message about being on the Previous Capacity Model, so you click the link to learn more, and nowhere does it tell you how to switch to the new model.  What's the point of the message taking you to a page that doesn't tell you how or why to switch to the newer model?  Seems pointless and annoying.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb490ef-2fd6-0f32-3b9b-c0cbbdc19110
* Version Independent ID: db3a8404-a0b7-19c7-3f12-289187549cb4
* Content: [Legacy storage capacity - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/legacy-capacity-storage)
* Content Source: [power-platform/admin/legacy-capacity-storage.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/legacy-capacity-storage.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@BrianLeFlem 
Thanks for the feedback. Good suggestion! We've added a link to the legacy topic pointing to the new capacity topic.

**Comment by BrianLeFlem** [comment]
Thanks, Jim, but I'm no wiser.  The old model looks very similar to the new model, and the new article gives no insights regarding how to switch to the new model.
I've been to Billing > Licenses, and there's no indication that I'm on the old or new model.  There's no option to upgrade or switch to the new model, etc, etc.

The whole thing is very confusing.  Am I really on the old model, because it looks like I might be on the new model.  If I am on the Old Model, how do I actually switch to the new model?

I really think the whole thing is a mess.

The link on the https://admin.powerplatform.microsoft.com/resources/capacity should take you to a very simple article that explains whether you CAN switch from the old to the new and if you can, HOW.  That's it.

There is far too much information on all these pages, and most of it has nothing to do with the message in the PowerPlatform Center.  Taking a user to a page that discusses the benefits of the new model without giving them any guidance at all as to how to switch is frustrating and annoying.

***@***.***D73C39.11CA6C00]

Brian
