### ISSUE TITLE
Task flows are going to be deprecated - no conversion, replacement is not ready

### ISSUE THREAD

**Issue by hwythe** [MicrosoftDocs/power-platform#71]
This seems to mean that any 'Task Flow' that I created in the past will break, there is no conversion from 'Task Flow' to 'Business Process Flow' and I cannot create a 'Business Process Flow' because it's not ready.   Seems like a plan for disaster.
---------
Task flows are deprecated
Task flows are used to create a step-by-step data entry form for common tasks, such as after-meeting follow-ups.

Task flows are deprecated and will be removed by October 1, 2020. They will be replaced by the immersive experience for business process flows that is planned for release. More information: Business process flow immersive experiences

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and model-driven apps in Dynamics 365 - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#feedback)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/important-changes-coming.md)
* Service: **dynamics-365-crossapp**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback, visit <https://ideas.powerapps.com>.  

Closing this issue.
