### ISSUE TITLE
Work Flow Error while deploying solution to test ALM Accelerator for Makers

### ISSUE THREAD

**Issue by NIhil1409** [MicrosoftDocs/power-platform#712]
Hi I am getting error in work flow in Github. it says invalid username is anyone getting similar error
**error :- GitHub workflow run Details: { "export-dev": "Error occured in GitHub action export-dev" }** 

Error: AADSTS50126: Error validating credentials due to invalid username or password.
  Trace ID: 302f8a78-0cc0-46b7-961d-1bab3078e300
  Correlation ID: 14066714-32c0-473a-a603-49d665e100e5
  Timestamp: 2021-04-28 11:15:44Z
  Response status code does not indicate success: 400 (BadRequest).
  {"error":"invalid_grant","error_description":"AADSTS50126: Error validating credentials due to invalid username or password.\r\nTrace ID: 302f8a78-0cc0-46b7-961d-1bab3078e300\r\nCorrelation ID: 14066714-32c0-473a-a603-49d665e100e5\r\nTimestamp: 2021-04-28 11:15:44Z","error_codes":[50126],"timestamp":"2021-04-28 11:15:44Z","trace_id":"302f8a78-0cc0-46b7-961d-1bab3078e300","correlation_id":"14066714-32c0-473a-a603-49d665e100e5","error_uri":"https://login.microsoftonline.com/error?code=50126"}: Unknown error

**Comment by NIhil1409** [comment]
Hi Please find attached Log file for the error

[logs_1.zip](https://github.com/MicrosoftDocs/power-platform/files/6393471/logs_1.zip)

**Comment by NIhil1409** [comment]
@bratsche   i am having another issue with authentication while deploying solution to test. if you can have a look and help ? Thanks Please find attached error log
[logs_1.zip](https://github.com/MicrosoftDocs/power-platform/files/6397373/logs_1.zip)

**Comment by NIhil1409** [comment]
@mikefactorial  i am having another issue with authentication while deploying solution to test. if you can have a look and help ? Thanks Please find attached error log
[logs_1.zip](https://github.com/MicrosoftDocs/power-platform/files/6397835/logs_1.zip)

**Comment by jimholtz** [comment]
@NIhil1409 
Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/
