### ISSUE TITLE
API request limits for Power Virtual Agent licensing - documentation discrepency

### ISSUE THREAD

**Issue by fredericklin** [MicrosoftDocs/power-platform#713]
The daily API request limit mentioned in this article is 15,000.  However, the licensing guide mentions 30,000.  Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07c96368-89fa-6451-b091-d59ed754cd75
* Version Independent ID: 140f2cc2-70d0-334a-8707-a1cde39fd75b
* Content: [Rate limits for chatbots - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/requirements-quotas)
* Content Source: [power-virtual-agents/requirements-quotas.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/requirements-quotas.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Hi, we're working on updating the docs at the moment. For now, please refer to the licensing guide for the correct numbers (30,000 for Automate flow daily requests). Sorry for the confusion!
