### ISSUE TITLE
Bot Skills Metadata Issue in Solution

### ISSUE THREAD

**Issue by geinnis** [MicrosoftDocs/power-platform#718]
Hello all,

I'm finding that when I export and import a PVA bot that has some Bot Skills associated with it that the majority of the Skills will function as expected after I update the two necessary environmental variables. But one particular skill does not function unless I import the skills with the new manifest URL, and recreate the associated Bot Skill actions.

This particular skill attempts to send proactive messages to users in Teams using the appropriate Teams channel data for the user in question. 

After import, this skill will fail with a "Forbidden" error while trying to send proactive messages. I suspect that the metadata attached to the proactive message may be coming from the Bot Skills bot from the org that the solution was exported from, rather than the Bot Skills bot in the new environment.

If I reimport the bot skills in the new environment using the appropriate manifest URL, and delete/re-create the actions to invoke this skill, everything then works as expected.

The desired scenario would be to avoid having to re-import skills and recreate actions after having imported the solution.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1239a5a0-fcbc-61ab-e634-333db20f4580
* Version Independent ID: 27d16076-0c87-2902-9bd7-ece10b2c5aad
* Content: [Export and import bots using solutions (preview) - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/authoring-export-import-bots?source=docs)
* Content Source: [power-virtual-agents/authoring-export-import-bots.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/authoring-export-import-bots.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for your message! The best place for product requests or troubleshooting is the Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums) - if you repost your questions there an engineer, PM, or someone with a similar issue/solution should be able to help you.
