### ISSUE TITLE
Disable option not available on the Actions Toolbar

### ISSUE THREAD

**Issue by AgileXRM** [MicrosoftDocs/power-platform#72]
Under Disable a User section point 3, it says select Disable on the Actions Toolbar but in Power Platform, Disable is NOT available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6159c3d-47a4-bc29-7dda-52777db307c2
* Version Independent ID: 426568f9-3742-b39e-600d-5f3afd251c19
* Content: [Create users and assign security roles - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/create-users-assign-online-security-roles)
* Content Source: [power-platform/admin/create-users-assign-online-security-roles.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/create-users-assign-online-security-roles.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@AgileXRM 
Thanks for bringing this to our attention. That content refers to on-premises versions and has been removed. This content describes the process for online versions:
https://docs.microsoft.com/en-us/power-platform/admin/create-users-assign-online-security-roles#enable-or-disable-users
