### ISSUE TITLE
Weird Thai translation

### ISSUE THREAD

**Issue by srakrn** [MicrosoftDocs/power-platform#721]
[ป้อนคำติชมที่นี่]

There is a several mistranslations in this article, for example, how the phrase "Provide internal training events" was translated to "An internal training event was held" and the word "Running" in the phrase "Running App in a Day internally" was considered as a present participle verb instead of a gerund.

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: c88b22a4-1e9b-5d08-856f-5d33c1b32b69
* Version Independent ID: 0fe6bf51-fa94-e988-4ce6-2954fc9a8b84
* Content: [เหตุการณ์การฝึกอบรมภายใน - Microsoft Power Platform - Power Platform](https://docs.microsoft.com/th-th/power-platform/guidance/adoption/in-a-day)
* Content Source: [power-platform/guidance/adoption/in-a-day.md](https://github.com/MicrosoftDocs/power-platform-pr.th-TH/blob/live/power-platform/guidance/adoption/in-a-day.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by jimholtz** [comment]
@srakrn 
Thanks for the feedback. I've passed this on to our localization team for action.

**Comment by jowilco** [comment]
@srakrn 
Thank you for the feedback. We have updated the Thai translations in this article and I hope that the new version is an improvement.
