### ISSUE TITLE
Restart numbering in Team Development section

### ISSUE THREAD

**Issue by cwanja** [MicrosoftDocs/power-platform#725]
The numbering should be restarted when the second example is given under the Team Development section of the linked page. 
https://docs.microsoft.com/en-us/power-platform/alm/use-source-control-solution-files#team-development

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93fe4f56-c8ab-17e5-e1c2-1378fbc7a881
* Version Independent ID: c3f10ce9-0de0-d85a-c35c-bcfe181461ad
* Content: [Source control with solution files (Microsoft Dataverse) - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/use-source-control-solution-files)
* Content Source: [power-platform/alm/use-source-control-solution-files.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/use-source-control-solution-files.md)
* Service: **power-platform**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by Mattp123** [comment]
@cwanja - thank your for your feedback. The article has been revised to separate the two different examples. 

Closing issue.
