### ISSUE TITLE
Dynamics 365 Sales clarification

### ISSUE THREAD

**Issue by crh03** [MicrosoftDocs/power-platform#727]
In the first list of product on this page is lists Dynamics 365 Sales as not available in GCC, but I believe that isn't true and it should say Dynamics 365 Sales Insights.  Later on in the article it lists Dynamics 365 Sales as a license type for GCC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c4c21f6-aad6-d020-8559-ae4a60f287db
* Version Independent ID: fbb9a03c-65b3-9ae8-3b58-b2ac9d15401e
* Content: [Dynamics 365 US Government overview - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/microsoft-dynamics-365-government)
* Content Source: [power-platform/admin/microsoft-dynamics-365-government.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/microsoft-dynamics-365-government.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@crh03 
Thanks for the feedback. We'll make this change.
