### ISSUE TITLE
Extra step needed to prevent error

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/power-platform#729]
[Enter feedback here]

Installing the cmdlet using the steps on this page sometimes gives "CommandNotFoundException" related errors when user runs any PowerApps command such as "Add-PowerAppsAccount".

To prevent/fix that, as pointed out in [this post](https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/Add-PowerAppsAccount-fails-because-method-not-found/m-p/267977/highlight/true#M809), the following commands should be executed by the user:

```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
dir . | Unblock-File
```
Please address the problem and/or add the instructions above so that users will not encounter the same problem in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by laneswenka** [comment]
I was not able to reproduce this error when I installed this Administration module on a new VM.  If you continue to face this error please let us know via support ticket the repro steps.  Thanks!
