### ISSUE TITLE
External users?

### ISSUE THREAD

**Issue by avsrot** [MicrosoftDocs/power-platform#73]
Who exactly is defined as an external user?
Is it:

- A user with a 365 business subscription from a different tenant / domain?
- A user with a private Microsoft account (Hotmail)?
- A user with even no email address at all?
- A user with some other email address such as Google / Yahoo etc.?

Just saying "External" says not much!

**Comment by jimholtz** [comment]
@avsrot 
Can you provide a link to a topic where you saw the term "external". Thanks.

**Comment by avsrot** [comment]
https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq


מאת: Jim Holtzman <notifications@github.com>
נשלח: Thursday, January 2, 2020 9:12 PM
אל: MicrosoftDocs/power-platform‏ <power-platform@noreply.github.com>
עותק: Avinoam Rothenberg‏ <avr@artech.icu>; Mention‏ <mention@noreply.github.com>
נושא: Re: [MicrosoftDocs/power-platform] External users? (#73)


@avsrot<https://github.com/avsrot>
Can you provide a link to a topic where you saw the term "external". Thanks.

**Comment by jimholtz** [comment]
@avsrot 
I have updated the licensing faq content with the following:
External users are those outside of your organization who sign in with a variety of identities such as LinkedIn, Microsoft Account, other commercial login providers, or anonymously.

**Comment by avsrot** [comment]
👍👍
