### ISSUE TITLE
Power platform admins can access admin cmndlets too, but are not listed in the prerequisites

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/power-platform#730]
[Enter feedback here]
The prerequisites [here](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#prerequisite-1) only list M365 Global Admin, AAD Global Admin, and D365 Global Admin to be able to access admin cmndlets. However Power Platform Admins can access those cmndlets too (and it wouldn't make much sense if they cannot). 

Please add Power Platform Admins to both sections of the prerequisites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@user0604 
Thanks for the feedback. This change has been made.

**Comment by user0604** [comment]
@jimholtz thank you for your reply but I currently don't see the change. The content itself has been reorganized into [another page](https://docs.microsoft.com/en-us/power-platform/admin/powershell-getting-started), on which the role (Power platform Administrator) is missing too.
