### ISSUE TITLE
Audit Log connector limited number of records received

### ISSUE THREAD

**Issue by ShaneOss** [MicrosoftDocs/power-platform#731]
When using the Audit Log connector, there seems to be a limit of only 600 records being returned. Is there some limitation
on the https://manage.office.com/api/v1.0/tenantID/activity/feed/audit API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by ShaneOss** [comment]
From the headers looks like the NextPageUri is present but this isn't handled in the [Child] Admin | Sync Logs Flow

**Comment by manuelap-msft** [comment]
Hello,

pagination is not implemented in the custom connector. You can work around this by retrieving smaller chunks of the Audit Log - to do so, edit the parent Admin | Sync Logs Flow, find the variable "Interval" and set it to 1 Hour or 10 Minutes for example. By default, it may be set to one day. This means, the child flow will retrieve the audit log in smaller intervals. 

Thank you for using the CoE
Manuela
