### ISSUE TITLE
Missing DoD URLs

### ISSUE THREAD

**Issue by TurnerMarshall** [MicrosoftDocs/power-platform#734]
Missing DoD URLs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea524f2a-1e2a-6ade-8e2b-bc61173107c5
* Version Independent ID: 5990c060-8907-62b4-a8b3-f7ed8339a70e
* Content: [Microsoft Power Apps US Government - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government)
* Content Source: [power-platform/admin/powerapps-us-government.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-us-government.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@TurnerMarshall 
Thanks for the feedback. The content was updated recently with DoD info.
