### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by uohlukas** [MicrosoftDocs/power-platform#735]
'Tams' should be 'Teams'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b46d058a-2546-b917-1aff-2d15cf0ea76e
* Version Independent ID: 0c35bbb1-08a3-a26f-47de-ff5381522fe8
* Content: [Release notes and latest version of the CoE starter kit Core components for Teams 1.7 - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/release-notes/coreteams-1.7)
* Content Source: [power-platform/guidance/coe/release-notes/coreteams-1.7.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/release-notes/coreteams-1.7.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by laschultz** [comment]
I fixed and created a PR in the private repo. https://github.com/MicrosoftDocs/power-platform-pr/pull/3097
