### ISSUE TITLE
Refer to another article in the PowerApp PowerShell Support page

### ISSUE THREAD

**Issue by mVermaat** [MicrosoftDocs/power-platform#740]
This page gives a good overview about the PowerShell API support. What is not noted is that if you want to use a service principal, you need to specifically register it as a management application. The info can be found [here](https://docs.microsoft.com/en-us/power-platform/admin/powershell-create-service-principal). It took creating a support ticket and a 30 minute call with an engineer to figure out this missing part. I suggest adding this in [this](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#power-apps-cmdlets-for-administrators) paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@mVermaat 
Thanks for the feedback! We've update the topic with a note.
