### ISSUE TITLE
Typo on Resources to manage GDPR Compliance section

### ISSUE THREAD

**Issue by adedaporh** [MicrosoftDocs/power-platform#741]
[Enter feedback here]
There seem to be a typo on line 3 [here](https://docs.microsoft.com/en-us/power-platform/admin/wp-compliance-data-privacy#resources-to-manage-gdpr-compliance)

_Some of these resources and tools may also helpful to assist you in other data privacy-related tasks not directly related to GDPR._
The above statement is missing "be" after "also".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5356b36-4de4-cdce-c585-40ab0adc6710
* Version Independent ID: 4ac3ddec-b31b-c965-b3a2-0e42f4810d90
* Content: [Compliance and data privacy - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/wp-compliance-data-privacy)
* Content Source: [power-platform/admin/wp-compliance-data-privacy.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/wp-compliance-data-privacy.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@adedaporh 
Thanks for the note. We'll get this fixed today.
