### ISSUE TITLE
Correct Feedback Link

### ISSUE THREAD

**Issue by paulhasell** [MicrosoftDocs/power-platform#742]
Hi, the link for feedback on the Product (as opposed to page) now dumps you at the root of the MS communities website, not even in the PowerAutomate area, is this correct? If I'm trying to feedback to MS on a product, I would expect to be taken to a community page at all but more a direct MS idea/suggestion/complaint page? I'm trying to report functionality missing from the product not seeking additional community advice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@paulhasell 
For product-related feedback, visit https://ideas.powerapps.com.
