### ISSUE TITLE
Daily capacity report assistance

### ISSUE THREAD

**Issue by plagooms** [MicrosoftDocs/power-platform#746]
Hi, this article talks about logic apps workflow.  https://docs.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report#create-the-workflow-and-set-up-the-variables
Is there any chance you can provide steps how to do it in Power Automate?

thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 816403f3-0104-3d3a-e889-bf0d4cf9bcae
* Version Independent ID: 0f0d27e8-2aaa-0d7c-ea3e-fe949bd9b3b1
* Content: [Preview: Programmability and extensibility - Tutorial - Create a daily capacity report - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report)
* Content Source: [power-platform/admin/programmability-tutorial-create-daily-capacity-report.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/programmability-tutorial-create-daily-capacity-report.md)
* Service: **power-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by KendalBond007** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.flow.microsoft.com. Closing this issue.
