### ISSUE TITLE
Wrong currency in table

### ISSUE THREAD

**Issue by alrekr** [MicrosoftDocs/power-platform#748]
In the table with pricing, the "price per month" column is displaying the price with DKK as symbol but USD amounts. So $200 is converted to DKK200. 
---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Ofte stillede spørgsmål om Power Apps- og Power Automate-licenser - Power Platform](https://docs.microsoft.com/da-dk/power-platform/admin/powerapps-flow-licensing-faq#can-you-share-more-details-regarding-the-new-power-apps-portals-licensing)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform-pr.da-DK/blob/live/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by jimholtz** [comment]
@alrekr 
Thanks for the information. I've passed this on to the localization team for a fix.
