### ISSUE TITLE
New Connectors asked with 2.6.1

### ISSUE THREAD

**Issue by hadness** [MicrosoftDocs/power-platform#749]
Core Component asked to have connections who are missed in the French documentation such as HTTP with Azure AD Also missing information needed to complete the connection "Base Resource URL"  & "Azure AD Resource URI (Application ID URI)" for "HTTP with Azure AD" for example.

It could be good to update doc regarding missing connections & add updated screenshot (Dataverse vs Common Data Service)

**Comment by jimholtz** [comment]
@hadness 
Thanks for the feedback. Please provide the URL of the topic with the missing information.

**Comment by hadness** [comment]
here is the URL of french topic with missing information : https://docs.microsoft.com/fr-fr/power-platform/guidance/coe/setup-core-components#option-1-import-the-solution-into-a-production-environment

**Comment by manuelap-msft** [comment]
@Jimholtz 

In the English version, we have added this information
![image](https://user-images.githubusercontent.com/55705669/121160928-6dc6ab80-c844-11eb-8c86-f7aaa7852be1.png)

But in French, it is still missing
![image](https://user-images.githubusercontent.com/55705669/121160976-77e8aa00-c844-11eb-8313-5f5393209d46.png)

Do translations automatically happen after some time, and this just hasn't caught up yet (I believe we added this information at the beginning of May)? 

Thank you
Manuela

**Comment by manuelap-msft** [comment]
I see this has now been added to the french version as well.
