### ISSUE TITLE
missing link to LCS for Dynamics 365 Finance, SCM and Commerce

### ISSUE THREAD

**Issue by mirkku550** [MicrosoftDocs/power-platform#750]
https://docs.microsoft.com/en-us/power-platform/admin/support-overview?toc=/dynamics365/fin-ops-core/dev-itpro/toc.json&bc=/dynamics365/breadcrumb/toc.json#where-should-i-go-to-file-a-support-request 

should indicate Dynamics 365 Finance, SCM and Commerce, the portal is https://lcs.dynamics.com/ for any support plan

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d40b926-c24e-dd83-c0db-81ac12b2b7a6
* Version Independent ID: e81e19c4-92aa-40df-8b82-51b56d3d3fa3
* Content: [Support for Microsoft Power Platform and customer engagement apps in Dynamics 365 - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/support-overview?toc=/dynamics365/fin-ops-core/dev-itpro/toc.json&bc=/dynamics365/breadcrumb/toc.json)
* Content Source: [power-platform/admin/support-overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/support-overview.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by sericks007** [comment]
The content has been updated.  The specified row now lists "Dynamics 365 Finance, Dynamics 365 Supply Chain Management, and Dynamics 365 Commerce" instead of "Finance and Operations apps'.
