### ISSUE TITLE
Old Solution File for aka.ms/CoeStarterKitDownload

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/power-platform#756]
The solution file downloaded from aka.ms/CoeStarterKitDownload cannot be imported with the following error. Can that link be re-pointed to the recent up-to-date solution file?

`The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.`

![image](https://user-images.githubusercontent.com/14156926/120854395-39978480-c5d1-11eb-9fb6-2e3048f7c2c0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d3a97-f062-9c7c-a5b6-8ec69178e1bc
* Version Independent ID: 476f4f57-b869-c759-74cc-beb4e2deaa26
* Content: [Set up ALM Accelerator for Makers components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator)
* Content Source: [power-platform/guidance/coe/setup-almaccelerator.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almaccelerator.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
You need to extract the .zip file and the solution file is in there. Thats mentioned as Step 2 in the instructions.
