### ISSUE TITLE
Trial environments not available for developer tenants, why? 

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/power-platform#757]
What is the reason to prohibit M365 Dev-tenants from creating Power Platform test environments? Makes no sense to limit a trial environment just because someone is using a dev-tenant for tests. 

_> The licenses assigned to this user do not allow creation of a Trial environment._

The error is reproducible in tenants with a "Microsoft 365 E5 Developer" license. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2ae3323-da0e-b179-6d08-f08ecff03947
* Version Independent ID: 0ad080d6-6682-7035-7e10-d487ce95ddfe
* Content: [About trial environments: standard and subscription-based - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/trial-environments)
* Content Source: [power-platform/admin/trial-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/trial-environments.md)
* Service: **power-platform**
* GitHub Login: @ImadYanni
* Microsoft Alias: **iyanni**

**Comment by jimholtz** [comment]
@TobiasAT 
Sorry for the delayed response. Any M365 or E365 licensed user (even paid) cannot create a Power Apps trial environment per the following: 
https://docs.microsoft.com/en-us/power-platform/admin/create-environment#who-can-create-environments
