### ISSUE TITLE
Child Flows need to be activated to complete step, as does a flow needing to be saved.

### ISSUE THREAD

**Issue by henryphillipsnimbitech** [MicrosoftDocs/power-platform#758]
In the step where it gets you to copy the http request url in the notification Flow, you first need to save the flow to generate the URL and to save you have to have already turned on Flows that are referenced in the flow being saved.

Thanks in advance,

Henry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d3a97-f062-9c7c-a5b6-8ec69178e1bc
* Version Independent ID: 476f4f57-b869-c759-74cc-beb4e2deaa26
* Content: [Set up ALM Accelerator for Makers components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator?source=docs)
* Content Source: [power-platform/guidance/coe/setup-almaccelerator.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almaccelerator.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by mikefactorial** [comment]
@henryphillipsnimbitech pardon the delay in responding thanks for reporting this. We recently moved to a new GitHub repo for CoE Starter Kit here. https://github.com/microsoft/coe-starter-kit/ Please direct any additional feedback there. I've added this to an issue in that repo to be addressed. microsoft/coe-starter-kit#798

Closing this issue but feel free to comment on the other.
