### ISSUE TITLE
Common Data Service still referenced in a sentence

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/power-platform#759]
Under List of connectors that can't be blocked (https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention#list-of-connectors-that-cant-be-blocked) it still says "Within this, Common Data Service connectors..." where it should say "Microsoft Dataverse connectors".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea178b4-f20a-747b-9e84-8b09ab6218d4
* Version Independent ID: e97f75e7-469e-0dc1-319c-0fe0a84c4e2e
* Content: [Data loss prevention policies - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention#list-of-connectors-that-cant-be-blocked)
* Content Source: [power-platform/admin/wp-data-loss-prevention.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/wp-data-loss-prevention.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by RedsGT** [comment]
https://github.com/MicrosoftDocs/power-platform/pull/760

**Comment by jimholtz** [comment]
@manuelap-msft 
Thanks for the update. Taking to live via internal repo.
