### ISSUE TITLE
Application Users

### ISSUE THREAD

**Issue by ofiryehoshua** [MicrosoftDocs/power-platform#76]
I have a question regarding the Application Users. If for example, I have Dynamics 365 Sales enterprise subscription and I created two Application Users A and B. 
So each one of these Application Users gets 100,000 requests per 24 hours?

**Comment by jimholtz** [comment]
@ofiryehoshua 
Does this content answer your question:
https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#non-licensed-usersapplication-usersusers-with-special-free-licenses
