### ISSUE TITLE
DV for Teams in GCC High?

### ISSUE THREAD

**Issue by markarnolditpro** [MicrosoftDocs/power-platform#761]
Are there plans / timeline for DV for Teams in GCC and GCC High environments?  I would need this before being able to use DV for Teams. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66be7882-5440-7cff-142f-4436a2d648ca
* Version Independent ID: b1876c76-62e5-2e0f-c823-09be35cfd7a5
* Content: [About the Microsoft Dataverse for Teams environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#licensing-and-restrictions)
* Content Source: [power-platform/admin/about-teams-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/about-teams-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@markarnolditpro 
Thanks for the feedback. Check this topic and https://docs.microsoft.com/en-us/dynamics365/release-plans/ for updates on GCC and Dataverse.
