### ISSUE TITLE
No details around new Power Platform Solution Upgrade task

### ISSUE THREAD

**Issue by richsage** [MicrosoftDocs/power-platform#762]
Title is mostly self-explanatory. The new Solution Upgrade Power Platform Azure DevOps task was released in April 2021, but the documentation makes no mention of it. It would be good to understand what the functionality is, and in particular how it may relate / crossover with the Import Solution task (specifically around Upgrade vs Update and similar).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tool-tasks.md)
* Service: **power-platform**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment]
@richsage I have requested a response from the author of the Build Tools task topic.

**Comment by phecke** [comment]
@richsage 
I think this is what you are looking for.
[Power Platform Apply Solution Upgrade](https://docs.microsoft.com/power-platform/alm/devops-build-tool-tasks#power-platform-apply-solution-upgrade)
