### ISSUE TITLE
Unable to manage users from https://admin.powerplatform.microsoft.com/ext/DataGateways

### ISSUE THREAD

**Issue by miniGweek** [MicrosoftDocs/power-platform#763]
I was able to add admins to the Onpremise Datagateway we had from the https://admin.powerplatform.microsoft.com/ext/DataGateways on Monday 7th June 2021.

This isn't working today - 9th June 2021.
I am getting an error "Unable to share this gateway. Ensure you're connected to the Internet. Contact Microsoft support if the issue persists."

Looking into the Chrome Development Tools console I can see 404 error in the network tab for the call 
https://api.powerbi.com/v2.0/myorg/gatewayClusters/xxxxxxxxxx/permissions?region=australiaeast 404

Is there any workaround I can do to add admins to the data gateways?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a44a8eba-1a59-a8d2-d4f2-25562d0b6adf
* Version Independent ID: 2b986d0c-a3c6-f61a-cf2b-3f5f4fbe65fe
* Content: [Preview: View and manage on-premises data gateways - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/onpremises-data-gateway-management)
* Content Source: [power-platform/admin/onpremises-data-gateway-management.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/onpremises-data-gateway-management.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by KendalBond007** [comment]
Thanks for contacting us. If you have been unable to resolve this issue, please contact Support. See https://flow.microsoft.com/support/ to contact Support. Closing this issue.
