### ISSUE TITLE
Term undefined: CSAT??

### ISSUE THREAD

**Issue by NogginBox** [MicrosoftDocs/power-platform#764]
The term CSAT is used on this page with no explanation of what it means.

Description | Details
-- | --
Average CSAT | The average CSAT survey score for the specified time period.

The details here do not really help you understand.

After a quick bingle I found it stands for customer satisfaction. I then found it later down the page with an explanation, but it is not defined when it is first used.

As readers may not read the whole page, I think it needs to be defined in every section it is used and I would use the full term rather than the abbreviation where possible.

Finding CSAT used in more pages now I read more docs. Also here:
https://docs.microsoft.com/en-us/power-virtual-agents/analytics-summary

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59b0eb2-33ef-b6db-7fa8-bcece5d48e95
* Version Independent ID: 7da56bdd-afcc-2bb7-6c41-c88055076ddd
* Content: [Analyze topic performance - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/analytics-topic-details)
* Content Source: [power-virtual-agents/analytics-topic-details.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/analytics-topic-details.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for the feedback, I have updated the topics with the abbreviation definition and will publish these shortly.
