### ISSUE TITLE
Capacity Reporting Tutorial - missing required information

### ISSUE THREAD

**Issue by gbeifuss** [MicrosoftDocs/power-platform#767]
The Capacity Report tutorial is missing a lot of detail that would make it worthy of being called a tutorial. These are more generalized shorthand notes. I'm trying to follow along and it's really difficult since the specific operations are never mentioned.

For example, the step "We then parse the Azure AD token response into a typed object using this JSON schema:" doesn't actually note the operation needed (it's Parse JSON).
On top of that, all the Operations have been renamed, so relying on the pictures is useless. I have resorted to trying to match the icons.

It would also be great if the user/password authentication method could be shown, instead of mentioned as an alternative and never covered.

Overall, I find the PowerPlatform documentation to have such a high barrier for use that the target audience will be extremely small. I'd like to use the tools as they'd solve some challenges our organization has, but I'm a sysadmin, not a PowerPlatform MVP and the targeted audience seems to be experts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 816403f3-0104-3d3a-e889-bf0d4cf9bcae
* Version Independent ID: 0f0d27e8-2aaa-0d7c-ea3e-fe949bd9b3b1
* Content: [Preview: Programmability and extensibility - Tutorial - Create a daily capacity report - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report#save-to-an-html-table)
* Content Source: [power-platform/admin/programmability-tutorial-create-daily-capacity-report.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/programmability-tutorial-create-daily-capacity-report.md)
* Service: **power-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
Hi @gbeifuss this is great feedback, and thank you for giving it a go!  We released this tutorial based on direct calls with several customers that needed to light this up using some Azure tooling.  We are in the process of improving the article to simultaneously show all tool options for each step such as REST / PowerShell / Connector with relevant details.  

Wanted to acknowledge your painpoints here and we will address them over the next few article updates.
