### ISSUE TITLE
No Documentation on What Microsoft Graph Permissions are being requested

### ISSUE THREAD

**Issue by Nigel-Price** [MicrosoftDocs/power-platform#768]
Hi

There is no documentation on what permissions the Microsoft Graph request asks for.

There are some sites which restrict the permissions that Microsoft Graph can ask for for security reasons.

I am assuming that the Microsoft Graph request here does not ask for any admin permissions.

Regards

Nigel

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-gb/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

MS Graph is used in an HTTP with Azure AD call to get the Service Principal name - if an app or flow is owned by an SPN, this information is not available via the Office 365 Users call we usually make here, but only via Graph API. We need to include this information, so apps/flows aren't incorrectly marked as orphaned when in fact they're owned by an SPN.

Is this the information you were looking for?

Thank you
Manuela

**Comment by Nigel-Price** [comment]
So what permissions are requested here - hopefully not admin permissions?

Sent from my iPhone

On 14 Jun 2021, at 10:54, Manuela Pichler ***@***.***> wrote:

﻿

Hello,

MS Graph is used in an HTTP with Azure AD call to get the Service Principal name - if an app or flow is owned by an SPN, this information is not available via the Office 365 Users call we usually make here, but only via Graph API. We need to include this information, so apps/flows aren't incorrectly marked as orphaned when in fact they're owned by an SPN.

Is this the information you were looking for?

Thank you
Manuela

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpower-platform%2Fissues%2F768%23issuecomment-860556048&data=04%7C01%7Cnigel.price%40defra.gov.uk%7Ca90bb0746db64b4d4fec08d92f1a5bd5%7C770a245002274c6290c74e38537f1102%7C1%7C0%7C637592612519717836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wKqqHX6Qxrz5AI7jxnWzExXxDQghLgrS0eor8HDgU%2Bk%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUIKVELW4BLW4QTNZPSYQALTSXGUDANCNFSM46UYTFOA&data=04%7C01%7Cnigel.price%40defra.gov.uk%7Ca90bb0746db64b4d4fec08d92f1a5bd5%7C770a245002274c6290c74e38537f1102%7C1%7C0%7C637592612519717836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pck0%2Bu0Nhs1GIqEjz5xOCkG4wN3%2FWx5Y%2FSy020xY9ak%3D&reserved=0>.

Department for Environment, Food and Rural Affairs (Defra) This email and any attachments is intended for the named recipient only. If you have received it in error you have no authority to use, disclose, store or copy any of its contents and you should destroy it and inform the sender. Whilst this email and associated attachments will have been checked for known viruses whilst within Defra systems we can accept no responsibility once it has left our systems. Communications on Defra's computer systems may be monitored and/or recorded to secure the effective operation of the system and for other lawful purposes.

**Comment by manuelap-msft** [comment]
This is the request we're making and the documentation outlines permissions required for Delegated accounts:
https://docs.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-1.0&tabs=http

We will update our docs with this link to make this more clear.
