### ISSUE TITLE
Please update german translation with Text from English version: "Enhanced Duplicate Detection is activated per default"

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/power-platform#769]
Client has asked why the improved duplicate detection cannot be activated as described on the german page. Screenshot under 3. has an option that isn't on any CRM system.

Checking the english page, https://docs.microsoft.com/en-us/power-platform/admin/enable-improved-duplicate-detection the very first box clarifies that " Important

The improved duplicate detection experience is now enabled by default."

Plese verify and update the german page accordingly.

Thanks, 
Regards,
Bernhard

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 345aa08f-2a2f-16b3-3ad8-db7be4fc2eae
* Version Independent ID: a5d76cbb-a7c0-7e4f-3671-c7ad60a30747
* Content: [Verbesserte Duplikaterkennung aktivieren - Power Platform](https://docs.microsoft.com/de-de/power-platform/admin/enable-improved-duplicate-detection)
* Content Source: [power-platform/admin/enable-improved-duplicate-detection.md](https://github.com/MicrosoftDocs/power-platform-pr.de-DE/blob/live/power-platform/admin/enable-improved-duplicate-detection.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by BernhardRaether** [comment]
...forgot the german Text for the Infobox, if you like to use it "Wichtig Die verbesserte Duplikaterkennung ist standardmäßig eingeschaltet"

**Comment by jowilco** [comment]
@BernhardRaether
Thank you for bringing this to our attention. This paragraph was only added to the English last month, and it takes a little while for the translations to be updated. In a curious coincidence, the translations were returned an hour ago, so the paragraph now appears in the German topic.
