### ISSUE TITLE
Mixed message

### ISSUE THREAD

**Issue by dharger2020** [MicrosoftDocs/power-platform#77]
It appears that PowerApps is included in M365 E3 license:
https://www.microsoft.com/en-us/microsoft-365/compare-all-microsoft-365-plans

But in reality - the data source ‘premium’ tag that has been applied to SQL server and other data sources requires a spectate PowerApps license. 
I wish someone would have known that (at MICROSOFT) before advising us to upgrade from O365 to M365.
Agree with the other comments here - MSFT is limiting development and adoption of promising technology by complicated licensing and misinformed MSFT employees, partner, and customers.

Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#feedback)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback, visit <https://ideas.powerapps.com>.  

Closing this issue.
