### ISSUE TITLE
Improve wording

### ISSUE THREAD

**Issue by yashpatel22** [MicrosoftDocs/power-platform#771]
Quote from note in article:
"The access level is not taken into account in the privilege check, this is done in the access check when the privilege check is passed."

Can this be re-worded? I have checked with 3 escalation resources on the CRM Support team at Microsoft, and all of us are having a hard time understanding it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7869dab1-e8c8-1432-304f-7e02132ad63f
* Version Independent ID: 806b8fab-4cb9-601d-7b9b-3a79ef0963f4
* Content: [How access to a record is determined - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/how-record-access-determined)
* Content Source: [power-platform/admin/how-record-access-determined.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/how-record-access-determined.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@yashpatel22 
Taking to internal thread.
