### ISSUE TITLE
Cannot assign queues to teams that are not owner team.

### ISSUE THREAD

**Issue by simes1** [MicrosoftDocs/power-platform#772]
Important issue re AAD Group Teams missing from the documentation:

**They do appear to be able to have a default queue**:

Message: Cannot assign queues to teams that are not owner team. TeamId: 911aa6e4-75cf-eb11-bacc-00224800ec40, TeamType: AadGroup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc48e173-18f4-85d8-5938-91be592204cd
* Version Independent ID: be1f1a63-c300-b120-0d1a-6c22ebc76e7a
* Content: [Manage group teams - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-group-teams)
* Content Source: [power-platform/admin/manage-group-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/manage-group-teams.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@simes1 
Thanks for the feedback. Currently, this is by-design - Azure AD group teams cannot be assigned to queue.

**Comment by simes1** [comment]
@jimholtz I'm aware this is currently by design (Hopefully that can be changed one day - see https://experience.dynamics.com/ideas/idea/?ideaid=7b7971f6-2bd0-eb11-ba5e-0003ff45807b)

The problem with the documentation is that the current situation is not called out anywhere and that's a big issue - particularly when implementing D365 Customer Service organisation wide.
