### ISSUE TITLE
Proper list of audited events

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/power-platform#773]
Folks, can you please update the article with a proper list of all events that are captured, instead of "sample of user events". Listing events/operations that are not captured would also be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 184dd591-1250-2bcc-db42-35afc3a77bce
* Version Independent ID: 75aaea0f-6f52-3977-77ba-a79f3604ef5e
* Content: [Power Apps activity logging - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps#what-events-are-audited)
* Content Source: [power-platform/admin/logging-powerapps.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/logging-powerapps.md)
* Service: **power-platform**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by jimholtz** [comment]
@michevnew 
Thanks for the feeback. We're considering for a future documentation update.
