### ISSUE TITLE
PVA Web for GCC

### ISSUE THREAD

**Issue by desmay** [MicrosoftDocs/power-platform#774]
I believe Power Virtual agent web app is now live for GCC so this page needs updated to remove the not in GCC note. 
https://docs.microsoft.com/en-us/power-virtual-agents/requirements-licensing-gcc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30a0774-c532-8f84-5e15-fe1755057a3e
* Version Independent ID: 781cccd5-df6b-5b01-b4e8-6ab94e92241f
* Content: [Overview of Power Virtual Agents web app - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/fundamentals-what-is-power-virtual-agents-portal)
* Content Source: [power-virtual-agents/fundamentals-what-is-power-virtual-agents-portal.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/fundamentals-what-is-power-virtual-agents-portal.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for the feedback, I've made this change and it should go live in the next couple of days.
