### ISSUE TITLE
Possibility of an outdated information about mobile phone support

### ISSUE THREAD

**Issue by Lemerika** [MicrosoftDocs/power-platform#778]
Article has a note that declares: "_Duplicate detection works with Dynamics 365 for tablets, but isn't available for Dynamics 365 for phones._"

![image](https://user-images.githubusercontent.com/86103121/122537765-901fac80-d02e-11eb-9686-f08bb265b37b.png)

In history this was the case. Mobile support was only for tablets and not for mobile phones. However this should be thing of a past. I just ran a test on Dynamics mobile client and the duplicate check worked just fine.

If I am correct in my assumption of this article holding outdated information, I would request the referred note to be removed from the article, as it is at the moment causing confusion with our customers.

Thank you,
lemerika/microsoft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ec2130e-e177-cbe3-1b3f-6225d07faa05
* Version Independent ID: 38bad136-38b2-79a8-06b3-24505125cb77
* Content: [Detect duplicate data with match codes and rules - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/detect-duplicate-data)
* Content Source: [power-platform/admin/detect-duplicate-data.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/detect-duplicate-data.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Lemerika 
Taking this to internal thread.
