### ISSUE TITLE
Screenshot points to a missing connection option

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/power-platform#779]
The **How to create a connection** section screenshot suggests selecting a _Dynamics 365 for Operations_ connection, which doesn't appear to exist. _Dynamics 365_ is available, but deprecated. Should this perhaps be _Fin & Ops Apps (Dynamics 365)_?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd884343-7f2e-9765-4860-4cb4981a908e
* Version Independent ID: efe70284-6f99-698c-9406-802595535d97
* Content: [Integrate data into Microsoft Dataverse - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/data-integrator?WT.mc_id=BA-MVP-5003744)
* Content Source: [power-platform/admin/data-integrator.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/data-integrator.md)
* Service: **power-platform**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by jimholtz** [comment]
@rrhkpmg 
Thanks for the feedback. We'll be addressing this content with future updates.
