### ISSUE TITLE
Enable audit history in entity form

### ISSUE THREAD

**Issue by haepeto** [MicrosoftDocs/power-platform#78]
[Enter feedback here]
What I think is missing from this page is the possibility to quickly display the audit history of a record from the normal edit form "Related->Audit history". 
This has to be enabled by adding the Audit History section to the naviagtion of the form. See topic ... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837f9db7-667d-814f-1df6-98e2f89a44cc
* Version Independent ID: f53ea984-3798-d3fb-ec0c-d31f81db9250
* Content: [Audit data and user activity for security and compliance - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity)
* Content Source: [power-platform/admin/audit-data-user-activity.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/audit-data-user-activity.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@haepeto 
Thanks for the feedback. I've passed your suggestion on to the product team.
