### ISSUE TITLE
Dataverse for Teams in GCC 

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/power-platform#780]
Per message center MC243207 Dataverse for Teams should be available to GCC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66be7882-5440-7cff-142f-4436a2d648ca
* Version Independent ID: b1876c76-62e5-2e0f-c823-09be35cfd7a5
* Content: [About the Microsoft Dataverse for Teams environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment)
* Content Source: [power-platform/admin/about-teams-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/about-teams-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@GitWesDone 
Thanks for the feedback. There will be a communication about this coming soon.
