### ISSUE TITLE
Some documentation on system topics would be great

### ISSUE THREAD

**Issue by DS2019** [MicrosoftDocs/power-platform#782]
[I've been working with the system topics so that the chatbot we are creating isn't accidentally triggering them as their triggers (or the system topics themselves) cannot be deleted. It would be good to have some documentation on what runs system topics that have no triggers. We are carefully having to work around them with our own trigger phrases and some of the system topics are getting in our way. There are only a few phrases in the documentation dealing with system topics and it would be good to have a better understanding of how they are working. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0a90fa-97aa-4d20-fae4-d92389fa590b
* Version Independent ID: 46cbddc9-42e6-a034-1a36-3b8129a93631
* Content: [Fix errors, set status, and copy topics - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/authoring-topic-management)
* Content Source: [power-virtual-agents/authoring-topic-management.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/authoring-topic-management.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
@GitikaG please take a look and re-assign as necessary! Thanks!
