### ISSUE TITLE
Link to Solution Component File reference redirects back to this page 

### ISSUE THREAD

**Issue by coatsy** [MicrosoftDocs/power-platform#783]
In the [See also](https://docs.microsoft.com/en-us/power-platform/alm/solution-packager-tool#see-also) section, there's a link to the Solution Component File Reference topic.

This topic [has been removed](https://github.com/MicrosoftDocs/powerapps-docs/commit/074d1c34d73944c90922149cbcaacbeea7d6ec28#diff-24999246ec6962b5810bcc048dbc977502911137de67c0fa11bcc5ead3543ffa), and a redirect back to this page put in place. 

Suggest we remove the link from the **See also** section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79cd601d-fba9-42c0-91b1-49ed185b4a84
* Version Independent ID: 419d1fec-3ca0-919b-4def-d3b87a4fb07e
* Content: [SolutionPackager tool (Microsoft Dataverse) - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/solution-packager-tool)
* Content Source: [power-platform/alm/solution-packager-tool.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/solution-packager-tool.md)
* Service: **power-platform**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by Mattp123** [comment]
@coatsy - Thank you for your feedback. The link has been removed from the article.

Closing issue.
