### ISSUE TITLE
PowerBuild tools support for Dynamics On-premise version 9

### ISSUE THREAD

**Issue by maykul** [MicrosoftDocs/power-platform#785]
Support has few cases from customers asking if PowerBuild tools is supported for Dynamics On-premise version 9. Also we have seen multiple discussions in community forum asking the same questions. Its better to clarify in our documentation about its supportability for Dynamics On-premise version 9 environments. 

https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Power-Platform-Build-Tools-for-Dynamics-365-on-premises/td-p/907019 

https://readyxrm.blog/2020/04/07/simple-alm-for-power-apps-dynamics-365-projects-revisited-power-apps-build-tools-edition/

![image](https://user-images.githubusercontent.com/22687795/123450039-e1391e80-d5a1-11eb-9632-fc344e15f661.png)

https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatform-BuildTools&ssr=false#qna

![image](https://user-images.githubusercontent.com/22687795/123450080-f01fd100-d5a1-11eb-8642-ffd5a8b77209.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Microsoft Power Platform Build Tools for Azure DevOps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools?source=docs#frequently-asked-questions-faqs)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tools.md)
* Service: **power-platform**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by Mattp123** [comment]
As far as I know, there aren't any plans to make the Power Platform Build Tools available for Dynamics 365 Customer Engagement v9.x (on-premises) versions. Closing issue.
