### ISSUE TITLE
Video does not correspond to Documentation - Set up SharePoint Library

### ISSUE THREAD

**Issue by Dlutchy** [MicrosoftDocs/power-platform#786]
[Enter feedback here]
Hi,

I think the Video in this page is out fo date.

From the 5:00 mark in the **Center of Excellence Starter Kit - Governance Components** Video it shows the following sections which do NOT  exist in the Documentation site

- Create a SharePoint Document Library
- Create an Azure AD Security Group

There are other parts of the video that are not in the Documentation

regards
Darren

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3445b35a-114e-010d-a42b-3d738fa68c56
* Version Independent ID: 87fcef34-4b4a-cee9-f171-e1bd1e8ec970
* Content: [Governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components)
* Content Source: [power-platform/guidance/coe/governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/governance-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
That's correct - the CoE Starter Kit has monthly releases, but we do not currently have funding to re-record the videos every month. Some will therefore be out of date. The documentation will always be as up to date as our videos. We have it in our roadmap to create new videos and will update the page then!
