### ISSUE TITLE
What permissions must be given for end users on the Power Platform environment that the chatbot resides on?

### ISSUE THREAD

**Issue by DS2019** [MicrosoftDocs/power-platform#788]
[I can't seem to find what role is required on the environment that the chatbot is hosted on so that end users can access it. Is it the Basic User Role? Under the share and collaborate section, it only talks about those users that would modify or create new chatbots, and it's not mentioned here that I can see. What is required for end users of the chatbots that do not modify or create? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff98b4c0-2c22-79a5-90ed-a4a85612b9d0
* Version Independent ID: 9abcde53-21ea-8dc1-f756-1d3c358db08a
* Content: [Fundamentals - Publish a chatbot to various channels - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/publication-fundamentals-publish-channels)
* Content Source: [power-virtual-agents/publication-fundamentals-publish-channels.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/publication-fundamentals-publish-channels.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
@mvakoc can you advise please?
