### ISSUE TITLE
Translation advice

### ISSUE THREAD

**Issue by HaoHoo** [MicrosoftDocs/power-platform#789]
Suggest that 'Manager' translate to '管理' and ‘Position’ translate to '职位'.
These will help Simple Chinese reader easy to know the points.
 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4e2b746e-8a88-e3f9-9e55-592f2a186c44
* Version Independent ID: 482a7ffd-5ed5-a475-f9ba-6578bb6e97ee
* Content: [层次结构安全性 - Power Platform](https://docs.microsoft.com/zh-cn/power-platform/admin/hierarchy-security#feedback)
* Content Source: [power-platform/admin/hierarchy-security.md](https://github.com/MicrosoftDocs/power-platform-pr.zh-CN/blob/live/power-platform/admin/hierarchy-security.md)
* Service: **power-platform**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by jowilco** [comment]
@HaoHoo 
Thanks for your feedback. We are looking into this issue.

**Comment by jowilco** [comment]
@HaoHoo 
Thanks for your feedback. We have updated the translations, and the updated translations are live. Closing this issue.
