### ISSUE TITLE
path to the logfiles is incorrect

### ISSUE THREAD

**Issue by jellevervloessem** [MicrosoftDocs/power-platform#79]
c:\Users\<UserName>\AppData\Roaming\Microsoft\DataMigrationUtility\<Version>

should be 
c:\Users\<UserName>\AppData\Roaming\Microsoft\Microsoft Dynamics® CRM Configuration Migration Utility\<Version>.

**Comment by KumarVivek** [comment]
@jimholtz This comment is for the Configuration Migration tool.

**Comment by jimholtz** [comment]
@jellevervloessem 
Thanks for the notice. Updated path based on latest package install.
