### ISSUE TITLE
Add a note on how long it takes to populate data

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/power-platform#790]
Hello,

after enabling the tenant analytics, all dashboards show 0 and it takes some time (? how long ?) to populate the dashboards. Could we try and mention this in the docs to set the right customer expectation that there is a delay?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c237709a-db62-a57b-838c-5ee6c004bb55
* Version Independent ID: 3157a6e5-9a05-74b1-12b0-cd563817d327
* Content: [Preview: Tenant-level analytics - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/tenant-level-analytics)
* Content Source: [power-platform/admin/tenant-level-analytics.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/tenant-level-analytics.md)
* Service: **power-platform**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by jimholtz** [comment]
@manuelap-msft 
Thanks for the suggestion. Taking to internal email thread.
