### ISSUE TITLE
Describe env switching scenario

### ISSUE THREAD

**Issue by Triangle333** [MicrosoftDocs/power-platform#791]
Image that you want to substitute env B -> A, where A is an existing env, and B is a freshly created one.
And you want to keep domain name of A to be used for B after the switch.
And you can't just rename A->C and B->A because of 24 hours period that the domain name of A will continue to be used.

But to make this switch almost immediate (5-10 mins of downtime) you can do this:
1. Rename A->C just to be sure that A name is going to be released
2. Delete A (now C) env. Domain name A is definitely released now
3. Rename B->A, and this will work now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99c85c6f-67d8-2397-92c7-5c96744ad65c
* Version Independent ID: ec25f2fb-ff79-8ac7-2733-6f174ecb8cee
* Content: [Edit properties of an environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/edit-properties-environment)
* Content Source: [power-platform/admin/edit-properties-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/edit-properties-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Triangle333 
Thanks for the suggested procedure! We'll consider incorporating in future revisions of the documentation.
