### ISSUE TITLE
COE toolkit > Don't see Developer Compliance Center in the canvas app list

### ISSUE THREAD

**Issue by luisleong** [MicrosoftDocs/power-platform#792]
Hi,

I installed the COE toolkit: Core Components following these steps and I am missing one environment variable: Developer Compliance Center URL, and looking in the docs, I have to go to a canvas app called: Developer Compliance Center but I don't see it in the ones imported. This after I imported the file called: CenterofExcellenceCoreComponents_2_1_70_managed.zip

(https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)

These are the canvas app that I see in the list:
Power Platform Admin View
Set App Permissions
Set Flow Permissions
DLP Editor V2
App Catalog
Solution Health Hub

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
We have updated the setup instructions now. This environment variable can be left blank, until the Governance Components solution is installed - this solution contains the Developer Compliance Center app.
