### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by DougFMS** [MicrosoftDocs/power-platform#793]
In the initial note is says the page will be blank if you try to set currencies from the PPAC.  It actually opens up the classic currencies page which allows you to add new currencies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0752bb06-4f29-c183-351c-8944de46ebd1
* Version Independent ID: 0e1578c2-4921-6c11-8378-a2164a4d1751
* Content: [Manage transactions with multiple currencies - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-transactions-with-multiple-currencies)
* Content Source: [power-platform/admin/manage-transactions-with-multiple-currencies.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/manage-transactions-with-multiple-currencies.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@DougFMS 
Thanks for the feedback. We've updated the documentation.
