### ISSUE TITLE
Please describe about 'Get-FlowRun' command. This is very useful for checking failed flows.

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/power-platform#799]
[Enter feedback here]
Please describe about 'Get-FlowRun' command. This is very useful for checking failed flows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell?source=docs)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@MiyukiAmino 
Taking to internal email.
