### ISSUE TITLE
Add-PowerAppsAccount  - App Registration Support

### ISSUE THREAD

**Issue by philipverlinden** [MicrosoftDocs/power-platform#8]
Would the connection cmdlet Add-PowerAppsAccount support App Registrations at some point in time? Or is there a documented way to use an App Registration as connecting account?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform Admin center](https://docs.microsoft.com/en-gb/power-platform/admin/powerapps-powershell#feedback)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@philipverlinden 
Sorry for the delayed response. I've passed your request on to the product team. No ETA as of yet.

**Comment by binaryjam** [comment]
Hi this was closed, was it closed because there is nothing going to be done, it has been done ?

**Comment by Bryand13** [comment]
Hello, 

Sorry,  ¿Is there any info on how can we use App Registrations with Add-Add-PowerAppsAccount cmdlet ?

Regards,

**Comment by binaryjam** [comment]
Hi 

I have managed to use an App reg/ Service Principal using Azure automation 

In order to do this, I had an azure automation account creation, that has a service principal, 
that SP was added to the PP admin role as it was doing admin work.

 This was the powershell to connect that would fail
 
    Add-PowerAppsAccount `
        -Endpoint "prod" `
        -TenantId $servicePrincipalConnection.TenantId `
        -ApplicationId $servicePrincipalConnection.ApplicationId `
        -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint 

ONLY when you run this command (below) will it actually let you connect.   So investigate this and alternate params for logging on.

New-PowerAppManagementApp -ApplicationId XXXX-XXXX-XXX

associated cmds.
Get-PowerAppManagementApp
Get-PowerAppManagementApps

**Comment by Bryand13** [comment]
I'll check this out. Thank you for the info @binaryjam .

Regards.

**Comment by ElenaDallAgata** [comment]
Hi Binaryjam,
I'm not sure to have understood your solution.
first of all you run the script 
New-PowerAppManagementApp -ApplicationId XXXX-XXXX-XXX
and than
Add-PowerAppsAccount `
    -Endpoint "prod" `
    -TenantId $servicePrincipalConnection.TenantId `
    -ApplicationId $servicePrincipalConnection.ApplicationId `
    -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint 
?
Thanks in advance
