### ISSUE TITLE
Page does not mention requiring any solution (fails missing ActivityFeedsCore )

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/power-platform#800]
The page never mentions how to install this solution (or has a link to it)
If you find it on the power apps admin center solution section and try installing it fails saying that it requires `ActivityFeedsCore ` 

The instructions never mention having a dependency / precondition that needs to be installed.
it also does not mention if it's tied to a specific dynamics 365 license (which maybe why that solution is missing???)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sabinn-msft** [comment]
DES is an add-on on Dynamics 365 Sales. You won't find it on PPAC solutions. Moreover, I would encourage you to use Azure Synapse Link as that's where we are investing all our muscle. You could export the data to ADLS gen2 or use the Preview feature to link and analyze with Synapse.

**Comment by annerajb** [comment]
ok the reason i didnt' use synapse since i wanted to access it using sql server and not analyze it.

**Comment by sabinn-msft** [comment]
Azure Synapse link allows you to query  your data using Serverless SQL. I believe that should suffice your needs? Or was there something else you were trying to do with DES?
