### ISSUE TITLE
June CoE Toolkit release being downloaded from https://aka.ms/CoEStarterKitDownload

### ISSUE THREAD

**Issue by marcster** [MicrosoftDocs/power-platform#802]
Hi,

  I saw that the July version was available but it looks like the https://aka.ms/CoEStarterKitDownload link still seems to point to the June release.  I can download the latest from the Releases on Github but just a heads up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f619bbe-9303-8583-2cb9-a287811cec13
* Version Independent ID: 8e256e0c-38fa-f2ca-58db-550bb6e9802a
* Content: [Set up the CoE Starter Kit - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup)
* Content Source: [power-platform/guidance/coe/setup.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

do you still repo? We updated the link as part of the release, so this should work.

Thank you
Manuela

**Comment by marcster** [comment]
This is now working Manuela as expected. Thanks for sorting it out so quickly.

Friday
![image](https://user-images.githubusercontent.com/1025102/125293791-a8c46f00-e31b-11eb-80bc-dc610e03b759.png)

Today
![image](https://user-images.githubusercontent.com/1025102/125293819-af52e680-e31b-11eb-8520-b11c294adbda.png)

**Comment by manuelap-msft** [comment]
We had to make some changes to the release on Friday still, so waited to update this main link until it was all working.

Thank you
Manuela
