### ISSUE TITLE
Many customers do not understand that a per-app plan requires one license per user.

### ISSUE THREAD

**Issue by AsamiKondo** [MicrosoftDocs/power-platform#803]
Power Apps per app license is required one license per user.
However, many of my customers mistakenly believe that this license is allocated per app and that one license can be used by any number of users.
For example, in the case of the similarly named Power Automate per flow license, this license can be assigned to a flow and can be used by multiple users with whom the flow is shared.
Therefore, in order to reduce misunderstandings among users, could you please clarify somewhere that this license is required 1 license for one user for every two apps and one portal?
We have also received requests for improvement from our customers.

**Comment by jimholtz** [comment]
@AsamiKondo 
Taking this to internal email.
