### ISSUE TITLE
Home.dynamics.com references out of date

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/power-platform#804]
Page includes two references to home.dynamics.com

When you assign a security group to an environment, that environment will not show up in **home.dynamics.com** for users not in the group.

If you do not assign a security group to an environment, the environment will show up in **home.dynamics.com** even for those who have not been assigned a security role in that Dataverse environment.

Home.dynamics.com was retired June 30 2021 and has been deprecated since March 2020.

https://docs.microsoft.com/en-us/power-platform/important-changes-coming#dynamics-365-home-is-deprecated

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/control-user-access)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by jimholtz** [comment]
@thewrabbit 
Thanks for bringing this to our attention. We'll get this content updated.
