### ISSUE TITLE
Contradictory Information on Access to environments

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/power-platform#805]
• If you do not assign a security group to an environment, the environment will show up in home.dynamics.com even for those who have not been assigned a security role in that Dataverse environment.

versus

All licensed users, whether or not they are members of the security groups, must be assigned security roles to access environments. You assign the security roles in the web application. Users can't access environments until they are assigned at least one security role for that environment. For more information, see Configure environment security.

One says that environments without a security group assigned will show in a deprecated area even if they've not been given a security role.  The other states that everyone needs assigned a security role - which is correct?
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/control-user-access)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by jimholtz** [comment]
@thewrabbit 
Thanks for the feedback. The doc is correct.  The 1st bullet is for app visibility in home.dynamics.com.  All users in the environment can see all the apps of the environment in home.dynamics.com  This doesn’t mean that the user can access data.  If they click on the app and they don’t have a security role in the environment, they will get a data access denied error.

We're updating the 2nd bullet a bit for clarity.

**Comment by thewrabbit** [comment]
Point 1 should also be updated as home.dynamics.com no longer exists.
