### ISSUE TITLE
Add Disclaimer 

### ISSUE THREAD

**Issue by SteveoMS** [MicrosoftDocs/power-platform#806]
There should be a section that says 

"Note: Online links to SharePoint, OneDrive or Teams content are not support for inclusion in PVA topics due to the requirement to authenticate to these sources of information"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c99ae3-7f05-4ebb-495c-e94c7c022f6e
* Version Independent ID: eae3c031-6b6a-c99d-b673-33f39d00771c
* Content: [Get topic suggestions from support pages in Microsoft Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/teams/advanced-create-topics-from-web-teams)
* Content Source: [power-virtual-agents/teams/advanced-create-topics-from-web-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/teams/advanced-create-topics-from-web-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Hi there, we describe this in the first paragraph under the heading "Get content from webpages and online files": https://docs.microsoft.com/en-us/power-virtual-agents/teams/advanced-create-topics-from-web-teams#get-content-from-webpages-and-online-files

### Get content from webpages and online files
First you'll need a secure URL (starting with HTTPS) to your content, which must be a publicly available link. _For example, you can't use a file on a SharePoint site or somewhere where you need to log in._
