### ISSUE TITLE
Please specify the items that will not be migrated due to tenant migration

### ISSUE THREAD

**Issue by YoshikaSuzuki** [MicrosoftDocs/power-platform#807]
[Enter feedback here]
Tenant migration is supported by customer request, but SharePoint needs to request integration to support separately from tenant migration.
In addition, there are some applications such as Customer Voice and Flow that are not migrated by tenant migration. Would you please confirm this with the product team and specify it in this document as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf83baaf-d9eb-6e3d-1040-9ae94cd410db
* Version Independent ID: ae37a7a0-1e5a-a2ef-72c8-bf6d2601cae1
* Content: [Migrate an environment to a different tenant - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/move-environment-tenant)
* Content Source: [power-platform/admin/move-environment-tenant.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/move-environment-tenant.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@YoshikaSuzuki 
Taking to internal email thread.
