### ISSUE TITLE
CDMT Limitations not called out and Import Settings dialog not described.

### ISSUE THREAD

**Issue by simes1** [MicrosoftDocs/power-platform#809]
The CDMT Tool has some significant limitations that are not called out in the documentation.

For example it does not allow fields required to create AAD **_Group_** Teams to be exported making their adoption (and their significantly reduced admin burden cf. traditional _Owner_ Teams) unnecessarily difficult to achieve.

For example, the following cannot be added to the schema via the GUI. Although they can be manually added to the schema XML file (and it validates OK if you do this):

  &lt;field displayname=&quot;Azure AD Object Id for a group&quot; name=&quot;azureactivedirectoryobjectid&quot; type=&quot;guid&quot; /&gt;
  &lt;field displayname=&quot;Membership Type&quot; name=&quot;membershiptype&quot; type=&quot;optionsetvalue&quot; /&gt;

...any export using the validated schema fails with an error:

DataMigrationUtility.Export	Error	2	13/07/2021 13:07:08  Failed Schema Vaildation, Missing Fields on team:  

Further issues around Business Unit's, Currencies and Teams, particularly the default record for all of these are also not called out.

In addition more recent changes to the Configure Import Settings dialog - essential for disabling plug-ins on each entity, filtering records and not updating records are not described and the screenshot for this dialog is out of date.

Regards

--
Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba98e367-7715-504c-756d-ed70aa50114c
* Version Independent ID: c6c9e97d-5db6-8aa5-3001-6f985cd5c8f7
* Content: [Create a schema to export configuration data - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-schema-export-configuration-data)
* Content Source: [power-platform/admin/create-schema-export-configuration-data.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-schema-export-configuration-data.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@simes1 
Editing the schema via XML editor is not supported ( and thus not documented ). If the schema is not visible in the schema editor of the tool, that schema element is not supported by the tool, and thus it’s not going to be respected if added to the file. Support for Azure AD Groups is not yet available. 

We'll work on updating the documentation and screenshots.

**Comment by simes1** [comment]
Fortunately, (according to Matthew Barbour), it looks like it is coming in the next NuGet release.

Regards

--
Simon
