### ISSUE TITLE
Provide a sample please

### ISSUE THREAD

**Issue by luoyong0201** [MicrosoftDocs/power-platform#81]
Could you provide a sample for this change? I and most of my friends cannot get the point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148f041b-a63f-470c-ec11-08a2ebd3bde1
* Version Independent ID: 546ce331-8abc-4187-9bfa-6f4d4e03e62c
* Content: [Manage teams - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/manage-teams#feedback)
* Content Source: [power-platform/admin/manage-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/manage-teams.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@luoyong0201 
Please elaborate. What change are you referring to? And what do you mean by sample?
