### ISSUE TITLE
Getting an error: Tenant '5xxxxxxxxxxxxx.com' not found

### ISSUE THREAD

**Issue by wakedude** [MicrosoftDocs/power-platform#810]
Can anyone assist with this?
I have gone through the setup of the daily capacity report and am getting the error in the Call the List Environments Endpoint stage
This my URL: https://login.microsoftonline.com/5xxxxxxxxxx.com/oauth2/v2.0/token
This implies I do not have a subscription, but I do. The subscription is a Trial, does this matter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 816403f3-0104-3d3a-e889-bf0d4cf9bcae
* Version Independent ID: 0f0d27e8-2aaa-0d7c-ea3e-fe949bd9b3b1
* Content: [Preview: Programmability and extensibility - Tutorial - Create a daily capacity report - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report)
* Content Source: [power-platform/admin/programmability-tutorial-create-daily-capacity-report.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/programmability-tutorial-create-daily-capacity-report.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
Hello!

Please create a support ticket and copy me ***@***.***) and we will get you rolling. If a doc change is needed we can assess that as well.

Lane


On Jul 14, 2021, at 6:00 AM, Bishal Goswami ***@***.***> wrote:

﻿

Assigned #810<https://github.com/MicrosoftDocs/power-platform/issues/810> to @laneswenka<https://github.com/laneswenka>.

**Comment by jimholtz** [comment]
@wakedude 
Please see reply and create a support ticket.
