### ISSUE TITLE
GCC High Updates for COE Core Components

### ISSUE THREAD

**Issue by SteveWinward** [MicrosoftDocs/power-platform#811]
Step 9 outlines to set the HTTP connector to use the commercial AAD Graph API (https://graph.microsoft.com/).  GCC High uses the Azure for Government endpoint which is https://graph.microsoft.us/

Step 10 outlines the Power Automate environment variable endpoints.  There should be a new line item for GCC High with this value,

https://high.flow.microsoft.us/manage/environments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you, I have updated the documentation on our end and this will go live with the next release, early August!
