### ISSUE TITLE
About the limitation of number of sessions.

### ISSUE THREAD

**Issue by reshimiz** [MicrosoftDocs/power-platform#812]
Hello team,

According to the license guide, the billable sessions of PVA for Teams is unlimited.
However, this docs says "10 per user every 24 hours across all bots in a tenant".

Please correct the docs or license guide whichever is wrong.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07c96368-89fa-6451-b091-d59ed754cd75
* Version Independent ID: 140f2cc2-70d0-334a-8707-a1cde39fd75b
* Content: [Rate limits for chatbots - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/requirements-quotas)
* Content Source: [power-virtual-agents/requirements-quotas.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/requirements-quotas.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by MiyukiAmino** [comment]
Hi, team. I'm facing same question, so please have a look at this. Thanks.
