### ISSUE TITLE
Documentation Addition for GCC-H

### ISSUE THREAD

**Issue by JuddG-Microsoft** [MicrosoftDocs/power-platform#814]
In the "Set up the custom connector" section, step 2 ("Select Edit at the bottom of the OAuth 2.0 area to edit the authentication parameters."), GCC-H users should be directed to use "https://login.microsoftonline.us" as the value for "Login URL".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Made this changes in our local version, which will get pushed to live with the next release of the CoE Starter Kit - beginning of August
