### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by anbhar** [MicrosoftDocs/power-platform#815]
Power BI “embedded” user dashboard experience - this link goes to an unrelated page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a33278f2-b63d-c61a-920e-7fe85c31dd71
* Version Independent ID: f2f2f47f-6c2c-e49a-daeb-6608e2f47c3a
* Content: [Dynamics 365 US Government - Feature availability - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/government-feature-availability#feedback)
* Content Source: [power-platform/admin/government-feature-availability.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/government-feature-availability.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@anbhar 
Thanks for the feedback. Taking this to internal email.
