### ISSUE TITLE
YAML Schema for Power Platform Copy Environment Task

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/power-platform#816]
Can you provide the full YAML shcema of this task and others in YAML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks#power-platform-copy-environment)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tool-tasks.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment]
@gregdegruy I added the YAML snippets for each task. If this is not what you are asking for, file a new issue.
