### ISSUE TITLE
Firewall on Azure Key Vault

### ISSUE THREAD

**Issue by DaveRuijter** [MicrosoftDocs/power-platform#82]
To be able to get the connection working between the Data Export Service and the Azure Key Vault, people might need to add an exception in the firewall of the Key Vault too (as well as SQL Server). This is missing information on this page and it would be awesome if that could be added.

Furthermore, I think a part of the following text should be changed to "for the region of your Dynamics 365 environment", instead of "for the region of your Azure SQL Database", right?
"In Azure SQL Database, click Set server firewall, turn Allow access to Azure services to OFF, click Add client IP, and then add the IP addresses appropriate for the region of your Azure SQL Database. More information"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#how-to-delete-all-data-export-profile-tables-and-stored-procedures)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@DaveRuijter 
Thanks for the suggestions! We've made additions to this section:
https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#prerequisites-for-using-
And made the edit fix.
