### ISSUE TITLE
Method 4: Remove email messages with attachments using a bulk deletion job - 'Completed' emails?

### ISSUE THREAD

**Issue by ConsoleMAD** [MicrosoftDocs/power-platform#824]
For the bulk deletion of emails with large attachments - https://docs.microsoft.com/en-us/power-platform/admin/free-storage-space#method-4-remove-email-messages-with-attachments-using-a-bulk-deletion-job, the guidance says to choose emails with a Status Reason of Completed. This doesn't seem right as hardly any emails have this status. Wouldn't Sent and/or Received be better?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9c9aae-ceaa-2e78-3752-2770327f49a7
* Version Independent ID: acd2ddc9-6225-92e8-2636-2a02437c3d82
* Content: [Free up storage space - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/free-storage-space)
* Content Source: [power-platform/admin/free-storage-space.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/free-storage-space.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@ConsoleMAD 
Thanks for the suggestion. We'll update the document.
