### ISSUE TITLE
Lost connection reference

### ISSUE THREAD

**Issue by diego8arock** [MicrosoftDocs/power-platform#831]
When importing a solution from a different environment this two connections get lost (image below). The only way I found to fix it is to remove them and add them again in the studio. Is there any cmldet that can fix it wihout the need to open the studio? This is because we already have more than 15 prod env for our clients, and many more to come. One is Power Flow and the other is a shared Azure Blob Storage Connector

![image](https://user-images.githubusercontent.com/15175848/127230719-f8f74fcd-e90c-4ef6-8cf5-a99410ff9a41.png)

**Comment by jimholtz** [comment]
@diego8arock 
Thanks for the feedback. What topic has content for the issue?

**Comment by phecke** [comment]
@diego8arock We need to know what documentation (URL) you were following when you had this problem. Open a new documentation issue when you can provide us that info.

If this is a support request, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.
