### ISSUE TITLE
Create a trial (standard) environment in the Power Platform admin center

### ISSUE THREAD

**Issue by anapereiCRMSE** [MicrosoftDocs/power-platform#832]
Hi Team.
on the steps 
Create a trial (standard) environment in the Power Platform admin center from y experience is not possible to deploy Dynamics apps on configuration. 

![image](https://user-images.githubusercontent.com/62559644/127341184-a74e8bc7-2615-48c8-8931-b361c7cad25f.png)

to deply a D365 apps on a trial the trial needs to set as trial (subscription-based) 

thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2ae3323-da0e-b179-6d08-f08ecff03947
* Version Independent ID: 0ad080d6-6682-7035-7e10-d487ce95ddfe
* Content: [About trial environments: standard and subscription-based - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/trial-environments#create-a-trial-standard-environment-in-the-power-platform-admin-center)
* Content Source: [power-platform/admin/trial-environments.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/trial-environments.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by jimholtz** [comment]
@anapereiCRMSE 
Thanks for feedback. Taking to internal thread.
