### ISSUE TITLE
Default Solutions

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/power-platform#834]
1. If we only ever want components created in "real"/custom solution, is it safe to delete the Common Data Services Default Solution?

-----
>By default, all enabled users can create apps and customize components in the Common Data Services Default Solution.

2. Can/how this be disabled?

-----
> If you'll be customizing this special solution, consider changing the publisher prefix.

It would be great if this was made a little more explicit:

https://make.powerapps.com -> Solutions -> Default Solution -> Edit -> Settings -> Pen icon on the Publisher drop down

I was confused for a while as the _solution_ prefix and solution publisher cannot be changed, only the prefix on the _publisher_ itself.

thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6fd60a-4e8f-8280-cf14-d5721422f39e
* Version Independent ID: 3453f85a-f603-e541-9ee1-b5cd93ab8ee9
* Content: [Default solution vs. custom solution - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/use-solutions-for-your-customizations#common-data-service-default-solution)
* Content Source: [power-platform/alm/use-solutions-for-your-customizations.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/use-solutions-for-your-customizations.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@fowl2 - 1) The platform requires both default solutions so you can't delete either of the them.
2) The enable users with customization privileges by default only applies to the default environment. I've updated the article to mention that. 

You can change the solution publisher for an unmanaged solution [Change a solution publisher](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-solution#change-a-solution-publisher) 

Closing issue.

**Comment by fowl2** [comment]
@Mattp123 thanks for the info.

> The platform requires both default solutions so you can't delete either of the them.

I actually just deleted it. Nothing broken so far 😨


> You can change the solution publisher for an unmanaged solution [Change a solution publisher](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-solution#change-a-solution-publisher)

That illustrates my point, this doesn't change which publisher is associated with the solution, it changes the publisher itself.
