### ISSUE TITLE
PowerShell

### ISSUE THREAD

**Issue by dylanberry** [MicrosoftDocs/power-platform#835]
Logic app is the last thing I would use for monitoring capacity. Here's a PowerShell script you can add to the documentation to make it more useful for admins:

```
param(
  [Parameter(Mandatory=$true)]
  [string]$ClientId,

  [Parameter(Mandatory=$true)]
  [string]$ClientSecret,

  [Parameter(Mandatory=$true)]
  [string]$TenantId,

  [Parameter(Mandatory=$true)]
  [string]$EnvironmentName
)

az login --allow-no-subscriptions --service-principal --username $ClientId --password $ClientSecret --tenant $TenantId

$resource = 'https://api.bap.microsoft.com/'
$token = az account get-access-token --resource $resource | ConvertFrom-Json

$environmentCapacity = Invoke-RestMethod -Uri 'https://api.bap.microsoft.com/providers/Microsoft.BusinessAppPlatform/scopes/admin/environments?api-version=2020-10-01&$expand=properties.capacity,properties.addons' `
    -Method GET `
    -Headers @{'Authorization' = "Bearer $($token.accessToken)"}

$environment = $environmentCapacity.value.properties | ? displayName -eq $EnvironmentName
$environment.capacity
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 816403f3-0104-3d3a-e889-bf0d4cf9bcae
* Version Independent ID: 0f0d27e8-2aaa-0d7c-ea3e-fe949bd9b3b1
* Content: [Preview: Programmability and extensibility - Tutorial - Create a daily capacity report - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report)
* Content Source: [power-platform/admin/programmability-tutorial-create-daily-capacity-report.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/programmability-tutorial-create-daily-capacity-report.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by laneswenka** [comment]
We updated the tutorial with a full powershell example.  Thanks for the feedback, the Azure example is just an indication that you can use any tool that supports HTTP/REST.
