### ISSUE TITLE
Broken link on docs.microsoft.com for power platform licensing

### ISSUE THREAD

**Issue by honestbob** [MicrosoftDocs/power-platform#837]
On this page
https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus
there is a link titled
"Understanding Power Platform Licensing"
it's Broke!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Licensing overview for Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@honestbob 
Thanks for the info. We'll get this link fixed.
