### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/power-platform#838]
The "Understanding Power Platform Licensing" link is a 404.
https://docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Licensing overview for Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@russrimm 
Thanks for the feedback. This link has been fixed.
