### ISSUE TITLE
PowerShell support

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/power-platform#84]
Is there support to import/export Canvas apps using PowerShell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f7d9def-ccc0-6bf9-d9b4-945f4ccfd19b
* Version Independent ID: cd12491c-b19e-d626-a9e1-e8fc57ccd242
* Content: [Migrate apps between environments and tenants - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/environment-and-tenant-migration#feedback)
* Content Source: [power-platform/admin/environment-and-tenant-migration.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/environment-and-tenant-migration.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@gregdegruy 
Import/export of canvas apps via PowerShell is currently not supported.
