### ISSUE TITLE
Details for auto-assignment of security roles when assigning a licence

### ISSUE THREAD

**Issue by Beck0Fish** [MicrosoftDocs/power-platform#840]
In the Note it says "Certain default security roles are assigned to users based on the license and/or solution installed. These security roles only give users Read access to apps that are installed in the environment."
1. It would be helpful to know WHICH roles are assigned based on licence and solution combinations, not just be given one example.  We are experiencing 'Basic User' security role being given on assignment of a licence.  Is this correct and expected, under what circumstances?  Where is the full list documented?
2. The Note goes on to say "These security roles only give users Read access..." which is not correct for Basic User which has Write access (to user-owned records).
3. If a tenant has multiple instances, would the auto-assigned security role be applied in ALL instances, or if not what are the criteria?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32f3d531-d255-ed62-8a20-77aad003e806
* Version Independent ID: d0b1396d-4779-4980-4897-7b9b3ba16d0a
* Content: [Assign licenses - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/assign-licenses)
* Content Source: [power-platform/admin/assign-licenses.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/assign-licenses.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by KendalBond007** [comment]
Thanks for your feedback. We are closing this issue because it has remained unaddressed in nearly two years. If you're still experiencing the issue described here, please reopen or create a new issue.

**Comment by fowl2** [comment]
This is still a major gap and should be addressed.

**Comment by KendalBond007** [comment]
Noted.
