### ISSUE TITLE
IP Addresses & regions of dynamics unclear

### ISSUE THREAD

**Issue by mVermaat** [MicrosoftDocs/power-platform#841]
On this page it states to add the IP address matching the region of your dynamics environment. The regions on this match don't match the regions of the CRM environment. In example I have my dynamics in Europe. So which should I add? West europe, North europe? Both?

![image](https://user-images.githubusercontent.com/13309338/128192612-195fb5f5-f027-46e1-9673-b9e9948827ec.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database#azure-sql-database-static-ip-addresses-used-by-the-data-export-service)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sabinn-msft** [comment]
You need to add both. BTW, it seems like you are just setting this up? We would highly recommend switching to Azure Synapse Link instead as a future path and not take a dependency on DES - https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake
