### ISSUE TITLE
Errors in the document

### ISSUE THREAD

**Issue by timpoll** [MicrosoftDocs/power-platform#842]
In the section: "How to set up Azure Key Vault", the bulleted list does not line up with the placeholders/variables. Additionally, the explanation for "$subscriptionId" is completely wrong, that explanation would align more appropriately with "$resourceGroupName".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sabinn-msft** [comment]
Thanks. Will review. However, please be informed that we are asking all our new customers to use Azure Synapse Link for Dataverse as a go forward path and not take a dependency on DES

**Comment by timpoll** [comment]
Thank you. Can you provide more information on that process?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sabinn-msft** [comment]
Sure. Here you go - https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake
