### ISSUE TITLE
Outdated documentation should be removed

### ISSUE THREAD

**Issue by seanmcne** [MicrosoftDocs/power-platform#844]
This feature has not existed in quite a long while and should be removed, you cannot use "Dynamics CRM Online 2016 Update 1" as customers just use "D365 Online" or "Dataverse" and don't pick the specific version. 

Reference: https://github.com/MicrosoftDocs/dynamics-365-customer-engagement/issues/254
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4135115-9eef-e5a3-cdde-41075c6f75ba
* Version Independent ID: 811682b4-362b-f18b-9286-ec2ad4055786
* Content: [Automatic tuning of data query performance with index management - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/analyze-improve-data-query-performance)
* Content Source: [power-platform/admin/analyze-improve-data-query-performance.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/analyze-improve-data-query-performance.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by jimholtz** [comment]
@seanmcne 
Taking to internal thread.
