### ISSUE TITLE
Linked YouTube video is private

### ISSUE THREAD

**Issue by trongaus** [MicrosoftDocs/power-platform#845]
In the Tip section at the top there is a link to a video walkthrough on how to Connect to Exchange Online using server-side sync. That link directs you to a YouTube video that is Private so we are unable to view it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d917db-1300-f212-067f-4ac688c18bec
* Version Independent ID: d19b118a-eddc-dc4f-75ad-2640f02aaeb4
* Content: [Connect to Exchange Online - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-online)
* Content Source: [power-platform/admin/connect-exchange-online.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/connect-exchange-online.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @revachauhan
* Microsoft Alias: **rechauha**

**Comment by jimholtz** [comment]
@trongaus 
Thanks for the feedback. We don't see a video linked in this topic. Was it a different topic?

**Comment by mduelae** [comment]
@trongaus - I'm closing this since we don't see a video in this topic.

Thanks,
Mints
