### ISSUE TITLE
CRM Security Deprecation > Learn More Page is out of date or incorrect.

### ISSUE THREAD

**Issue by RiccoDeCicco** [MicrosoftDocs/power-platform#846]
In the Help Text it advises for Unified Interface one should click 'Advanced Settings' under the Gear Icon, but this is exactly the process I followed before seeing the 'CRM Security Deprecation' message'

<html>
Web client experience for security settings is being deprecated | Please use the Power Platform admin center to leverage the latest experience and manage security settings.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcbc305a-4582-7c46-7716-93c192a0f4d5
* Version Independent ID: 9fcacd77-43c3-4281-c891-f72721493a4f
* Content: [Manage Microsoft Dataverse settings - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/admin-settings#new-location-for-admin-settings)
* Content Source: [power-platform/admin/admin-settings.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/admin-settings.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@RiccoDeCicco 
Thanks for the feedback. We're migrating settings to the Power Platform admin center and will be adjusting text accordingly.
