### ISSUE TITLE
Missing documentation for installation of governance component in Teams environment

### ISSUE THREAD

**Issue by tmycgn** [MicrosoftDocs/power-platform#847]
See https://github.com/microsoft/coe-starter-kit/issues/1018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14181d4-574f-95e3-c2c9-545116549c9b
* Version Independent ID: bf449b92-6756-e08a-a58c-d561e36947cb
* Content: [Set up governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components)
* Content Source: [power-platform/guidance/coe/setup-governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-governance-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

see: 

> Follow the instructions detailed under[ Set up core components](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components ) to import the solution either into your Production or your Dataverse for Teams environment.

How to install a solution into Production or Teams environments is covered in the Core components setup instructions, solution specific setup is covered here. 

What you experience in https://github.com/microsoft/coe-starter-kit/issues/1018 was a bug in our solution, not related to the documentation.

Thanks for using the CoE
Manuela
