### ISSUE TITLE
Typo and feedback

### ISSUE THREAD

**Issue by ethrashakarchi** [MicrosoftDocs/power-platform#848]
You have a typo in the FAQ section of this page and under "What happens when a Track of email fails?" heading. Instead of "Track to Dynamics 365" it should be "Tracked to Dynamics 365" for the category name. This is important because our client was looking literally for the outlook category starting with "Track" based this FAQ and couldn't find it and we told them this is a typo and it should be "Tracked" basically. Once they used the corrected category, it works.

A second suggestion. Under this same section and heading, you have 3 bullet points stating why an email might not be delivered. These are good suggestions. Can you also consider adding a 4th bullet point to suggest that an email will fail to deliver to CE if the owner of the queue doesn't have security role and hence the owner will not be able to own the email record tracked by the queue. This is fairly common error/issue to why emails fail to track and become undeliverable. Also in CE, the mailbox record might appear as active and test/enable says "Success" under both incoming and outgoing but yet it is only when you check the "Alerts" section, you'll see the logs about failed email delivery with generic message not stating it is due missing security rights. 9/10 cases I've seen the issue is with clients configuring teams/queues and forget to assign security roles to them. We have one client who just removed security role from a team and they didn't realise it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a5e1be-4952-cd1e-7a6c-7aa42900f755
* Version Independent ID: 45bc0d06-ea39-4bbc-d6fa-d0c898b6ee14
* Content: [Use Outlook category to track appointments and emails - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/use-outlook-category-track-appointments-emails#faq)
* Content Source: [power-platform/admin/use-outlook-category-track-appointments-emails.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/use-outlook-category-track-appointments-emails.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@ethrashakarchi thank you for the feedback. I fixed the typo and added the 4th items that you suggested. The updates will go live by end of day today.

Thanks,
Mints

**Comment by ethrashakarchi** [comment]
Beautiful work @mduelae, I checked and the updates are reflected properly on the page now. Thank you.
