### ISSUE TITLE
No "Add-Ons" Tab on Analytics/Capacity Screen

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/power-platform#85]
I don't have the "Add-Ons" tab on my screen as lined out in Step 3 above. The message says: "Your organization can transition to the capacity model when your current term ends or at renewal." I just purchased a P1 License to increase CDS capacity because I'm unable to create a new Prod Env. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0cbf8c-5c12-5aa2-3786-392d0f498303
* Version Independent ID: 2774f5ca-1c86-4fe6-c296-6f7f45aa6702
* Content: [Capacity add-ons for Power Apps and Power Automate - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on)
* Content Source: [power-platform/admin/capacity-add-on.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/capacity-add-on.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@SeaDude 
Sorry you're having this issue. Please contact Support:
[Get Help + Support](https://docs.microsoft.com/power-platform/admin/get-help-support)
