### ISSUE TITLE
Relevance Search is now Available in Gov Clouds

### ISSUE THREAD

**Issue by SteveWinward** [MicrosoftDocs/power-platform#853]
Relevance Search is showing up on our docs as not available.  Just verified that it is in our GCC, GCC High and DOD clouds now.  This feature can now be removed as no longer not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a33278f2-b63d-c61a-920e-7fe85c31dd71
* Version Independent ID: f2f2f47f-6c2c-e49a-daeb-6608e2f47c3a
* Content: [Dynamics 365 US Government - Feature availability - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/government-feature-availability)
* Content Source: [power-platform/admin/government-feature-availability.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/government-feature-availability.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@SteveWinward 
Taking to internal thread.
