### ISSUE TITLE
Github Actions tutorial Entity vs Table

### ISSUE THREAD

**Issue by Freshchris01** [MicrosoftDocs/power-platform#856]
Hello, first of all thanks for the tutorials about ALM with Github Actions.
While following this [tutorial](https://docs.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-build#build-a-model-driven-app), at step 7 you should add a new Entity to your solution. For me. Entity is not an option in the "New" dropdown. After researching & reading [this link](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/understand-terminology#terminology-use-depending-on-protocol-or-technology) it was clear to create a new Table instead of Entity.
Does it make sense to add this link or a short remark to the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a110f4b-e1a1-ac97-f6f2-4723a6f53dd3
* Version Independent ID: 36551e12-f118-cc21-6953-1f5f953bbeb1
* Content: [GitHub Actions for Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-github-actions)
* Content Source: [power-platform/alm/devops-github-actions.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-github-actions.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by phecke** [comment]
@Freshchris01 Topic updated. Should be published live in a little while. Thanks for catching that.
