### ISSUE TITLE
Add links "Manage Microsoft Power Platform apps in the Microsoft Teams admin center"

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/power-platform#859]
Hi, PVA team.
The number of inquiries about PVA is increasing very rapidly.

Sometimes customer asked me about permission of Teams apps, so it would be nice to add below link in this page.
https://docs.microsoft.com/ja-jp/microsoftteams/manage-power-platform-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d57237c4-194c-60b1-8f50-6c171da74a37
* Version Independent ID: d833bef8-ccdd-e2b4-abaa-691a875851cb
* Content: [Publish your chatbot with the Power Virtual Agents app in Microsoft Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams#feedback)
* Content Source: [power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Hi @MiyukiAmino, I have updated the page, in the **Prerequisites** section. I hope this makes it easier to see how to manage Power Platform apps in the Teams admin center.

- https://docs.microsoft.com/power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams#prerequisites

Thank you very much for your feedback! Please re-open and reply if this didn't fix the issue.

**Comment by MiyukiAmino** [comment]
Hi,  @iaanw , thank you so much to add a very clear description!
