### ISSUE TITLE
Removal of parent.Xrm from sitemap Webresources

### ISSUE THREAD

**Issue by paulhasell** [MicrosoftDocs/power-platform#860]
Hi, is there a technical reason for removing/hiding _parent.Xrm_ from 'app' Webresources referenced in the sitemap?

We have a number of utility 'apps' based on Fluent/REACT loaded via HTML webresources that are navigated to via the sitemap. These don't need _Page_ access but **do** need _WebApi, Utility, etc_. I note that the navigation frame that houses full page webresource **has** an Xrm object (I guess needed to get data to render itself) so why would this **not** be available using _parent.Xrm_?

No date has yet been provided for when this will become unavailable but there are currently no alternate options proposed for this scenario so we are apprehensive about how to proceed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and customer engagement apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#some-client-apis-are-deprecated)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/important-changes-coming.md)
* Service: **power-platform**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback and questions, visit [Power Apps Pro Dev & ISV]<https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/bd-p/pa_component_framework>.  

Closing this issue.
