### ISSUE TITLE
Wrong Translation in German

### ISSUE THREAD

**Issue by Mop3D** [MicrosoftDocs/power-platform#861]
In the German version the "No" in the tables are translated as number "Nr."
Which is wrong. It should be "Nein"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66be7882-5440-7cff-142f-4436a2d648ca
* Version Independent ID: b1876c76-62e5-2e0f-c823-09be35cfd7a5
* Content: [About the Microsoft Dataverse for Teams environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment)
* Content Source: [power-platform/admin/about-teams-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/about-teams-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jowilco** [comment]
@Mop3D 
Thanks for your feedback. We have updated the translations, and the updated translations are live.
This was a larger issue affecting a larger set of documentation and multiple languages, so it took a little while to fix.
Closing this issue.
