### ISSUE TITLE
Section 'Environment management tasks' is out of date

### ISSUE THREAD

**Issue by mVermaat** [MicrosoftDocs/power-platform#863]
The section [Environment management tasks](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks#environment-management-tasks) is out of date. The parameters available in the task aren't fully described (i.e. CopyType from the copy environment task) and not all tasks are described (i.e. restore environment).

I was coming here to read about how to set the security group of the environment after a copy/restore as I couldn't find any way to do it. If it's possible to set the security group, it would be useful to describe that in this documentation too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tool-tasks.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by KendalBond007** [comment]
Thanks for your feedback. The document mentioned was last updated 22 May 23; specifically CopyType appears in the parameter description; github Blame shows the restore environment parameters having been updated by that date.
If you're still experiencing the issue described here, please reopen or create a new issue.
