### ISSUE TITLE
Broken links: Create and customize marketing calendars

### ISSUE THREAD

**Issue by modery** [MicrosoftDocs/power-platform#869]
The three links in the _Service Management tab_ section pointing to _Create and customize marketing calendars_ don't work anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f0c2675-2cf5-6319-493b-e5215a0a5dfa
* Version Independent ID: fc57a4d1-852a-ef61-f133-36add99d5323
* Content: [Miscellaneous privileges - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/miscellaneous-privileges)
* Content Source: [power-platform/admin/miscellaneous-privileges.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/miscellaneous-privileges.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@modery 
Thanks for the heads up. Fixing the links now.
