### ISSUE TITLE
DLP Policy Delete Pending

### ISSUE THREAD

**Issue by RickM10** [MicrosoftDocs/power-platform#87]
Following exactly these steps I get the policies sat there in pending state, I tried to use PowerShell script with ForceDeletion but it complains that it is no longer an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4970680e-b08e-7c4c-4f0b-79c51cc13bcb
* Version Independent ID: 8a110f10-3076-7595-6cac-67ce2c108c9f
* Content: [Manage data loss prevention (DLP) policies - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/prevent-data-loss#feedback)
* Content Source: [power-platform/admin/prevent-data-loss.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/prevent-data-loss.md)
* Service: **power-platform**
* GitHub Login: @manasmams
* Microsoft Alias: **manasma**

**Comment by jimholtz** [comment]
@RickM10 
From the product team, is this the scenario?
1. User is an environment admin or tenant admin
2. User creates a DLP (Data Loss Prevention) policy (say contosopolicy1) via UI in Power Apps admin center and applies it to: a specific environment, or multiple environments, or entire tenant
3. User then uses the same UI to delete the policy contosopolicy1
If so, please contact Support: https://dynamics.microsoft.com/support/
