### ISSUE TITLE
I can't get the PowerShell script to return the three values

### ISSUE THREAD

**Issue by vibraniumforge** [MicrosoftDocs/power-platform#873]
I tried to run the PowerShell script at [here](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools#create-service-principal-and-client-secret-using-powershell). It opens a dialog window, I enter my info. The terminal then outputs `Connected to AAD Tennant: microsoft.onmicrosoft.com, a long ID, in Azure cloud.`. Nothing else happens. No error. The terminal does not accept any more input. One of my team members got the same response. Not sure where to go from here. Thanks!

--- Edit below ---

After several hours, the following error appears:
`
Get-AzureADServicePrincipal : Error reading JToken from JsonReader. Path '', line 0, position 0. At C:\Users\New-CrmServicePrincipal.ps1:207 char:11 + $allSPN = Get-AzureADServicePrincipal -All $true +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-AzureADServicePrincipal], JsonReaderException + FullyQualifiedErrorId : Newtonsoft.Json.JsonReaderException,Microsoft.Open.AzureAD16.PowerShell.GetServicePrincipal
`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Microsoft Power Platform Build Tools for Azure DevOps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools#feedback)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tools.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by KendalBond007** [comment]
Thanks for your feedback. We are closing this issue because it has remained unaddressed for nearly two years. If you're still experiencing the issue described here, please reopen or create a new issue.
