### ISSUE TITLE
FAQ needs to be updated to reflect capacity to block connectors

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/power-platform#874]
The FAQ includes the below statements. This is wrong since the introduction of the capability to block connectors . Admins can actually create a DLP that will say no to Dropbox & Twitter, for the whole tenant.

Q: Can I control, on the tenant level, which connector is at all available, for example No to Dropbox or Twitter but Yes to SharePoint)?

A: This is not possible. Customers can subscribe to Audit events to do corrective action if there are flows that have been built that create concerns for customers. In fact, a very large Power Apps customer has leveraged this approach to apply another level of governance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58eb4b8e-13ae-4b99-5863-cfe07b921ea2
* Version Independent ID: 2384f8a9-7698-eb29-c2f4-1a57f9340e47
* Content: [Governance considerations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/governance-considerations)
* Content Source: [power-platform/admin/governance-considerations.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/governance-considerations.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Nicokirr 
Taking to internal thread.
