### ISSUE TITLE
That's not how to enable an entity for access teams

### ISSUE THREAD

**Issue by Customery** [MicrosoftDocs/power-platform#875]
Hello, the steps to enable an entity for access teams is not correct.
https://docs.microsoft.com/en-us/power-platform/admin/create-team-template-add-entity-form#enable-an-entity-for-access-teams

The described procedure is to open Power Platform Admin Centre then...
1. Select an environment and go to Settings > Users + permissions > Teams.
2. Select the check box for a team.
3. On the command bar, select More Commands (...).
4. Select Customize Entity.

These steps are incorrect. You can't change the settings for an entity (now called a table, BTW) from the Power Platform Admin Center or by opening a team.

The correct steps are to open the appropriate table from the Power Apps Maker Portal and to enable the 'Auto create access teams' check box for the table.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1579637e-7845-9830-1d8f-40d371d28587
* Version Independent ID: 6f00c801-369f-01e4-df15-36ad10c5f1bd
* Content: [Create a team template and add to an entity form - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-team-template-add-entity-form)
* Content Source: [power-platform/admin/create-team-template-add-entity-form.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-team-template-add-entity-form.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by jimholtz** [comment]
@Customery 
Thanks for the feedback. We revised this back in September. Forgot to close this issue.
