### ISSUE TITLE
Steps to add an access team view don't work

### ISSUE THREAD

**Issue by Customery** [MicrosoftDocs/power-platform#876]
Hello,

The steps to add an access team subgrid to a form do not work as described:
https://docs.microsoft.com/en-us/power-platform/admin/create-team-template-add-entity-form#add-a-team-template-to-the-entity-form

First of all, you can't customise an entity (now called a table) from the Power Platform Admin Centre. In step 2, there is no More Commands (...) option on the Teams view in the Power Platform Admin Centre.

Instead, I think makers need to use the Power Apps Maker Portal to add a subgrid to a form. Except that the Teams Template described in step 12 isn't available in the Power Apps Maker Portal. Instead, makers will need to revert to the classic web interface to customise the form and add an access team subgrid.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1579637e-7845-9830-1d8f-40d371d28587
* Version Independent ID: 6f00c801-369f-01e4-df15-36ad10c5f1bd
* Content: [Create a team template and add to an entity form - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-team-template-add-entity-form)
* Content Source: [power-platform/admin/create-team-template-add-entity-form.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-team-template-add-entity-form.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by KendalBond007** [comment]
Thanks for your feedback. Note that the document in question was updated 22 Aug 2023, and this issue may have been addressed. We are closing this issue because it has remained unaddressed for nearly two years. If you're still experiencing the issue described here, please reopen or create a new issue.

**Comment by paulliew** [comment]
i verified that the doc steps are correct.

**Comment by KendalBond007** [comment]
Excellent - thanks for noting here, @paulliew!
