### ISSUE TITLE
Please add explanation that customer need to configure cross-tenant isolation after it is enabled via support ticket.

### ISSUE THREAD

**Issue by phjia** [MicrosoftDocs/power-platform#877]
Please make it clearer that MSFT will just be enabling the ability for customers to enable this via their admin consoles per support ticket. Please also add detailed link or explanation on how to configure cross-tenant isolation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daeff591-4edf-8cc0-614a-47e59bec3825
* Version Independent ID: bad9dc45-d9f9-62c6-a7fd-7aa97fd8e3fd
* Content: [Restrict cross-tenant inbound and outbound access - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/cross-tenant-restrictions)
* Content Source: [power-platform/admin/cross-tenant-restrictions.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/cross-tenant-restrictions.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@phjia 
Sorry for the delayed response. The product team is working on feature updates. The documentation will be updated when that work is completed.
