### ISSUE TITLE
Clarification when action control available 

### ISSUE THREAD

**Issue by CarstenGroth** [MicrosoftDocs/power-platform#878]
could we add some clarity, when action control for a connector is available? A lot of requests incoming why for a connector there’s no granular configuration possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e03bf297-7319-c5e7-d0f9-46e1613b7c78
* Version Independent ID: f015c331-8904-bdfc-d90f-6feec512d86b
* Content: [Granular DLP controls - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/dlp-granular-controls)
* Content Source: [power-platform/admin/dlp-granular-controls.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/dlp-granular-controls.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Taking to internal thread.
