### ISSUE TITLE
permission sets

### ISSUE THREAD

**Issue by AndrewMarsh24** [MicrosoftDocs/power-platform#879]
Be good to update the page with what permission role can do this once it goes GA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32112a1e-a859-04ee-ffe1-d7164c061fa2
* Version Independent ID: be22f528-5ad0-c3ed-617e-d813c2c8ef4e
* Content: [Preview: Manage your maintenance window - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/manage-maintenance-window)
* Content Source: [power-platform/admin/manage-maintenance-window.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/manage-maintenance-window.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@AndrewMarsh24 
Thanks for the feedback. We'll keep that in mind for GA.
