### ISSUE TITLE
License requirements for Dynamics 365

### ISSUE THREAD

**Issue by AMSoftwareNL** [MicrosoftDocs/power-platform#88]
This page is part of the Power Platform and CDS documentation, but the requirements are Office 365 licenses. Can Activity Logging not be used without Office licenses if it is just for Dynamics 365? Is there a Dynamics 365 license which includes this capability without an Office 365 license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f28a46-531e-d373-40ad-f9e81b55fdf3
* Version Independent ID: a47230d1-92c1-28a3-2f2c-ada21450b1f2
* Content: [Enable and use Activity Logging - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/enable-use-comprehensive-auditing#feedback)
* Content Source: [power-platform/admin/enable-use-comprehensive-auditing.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/enable-use-comprehensive-auditing.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@AMSoftwareNL 
Activity logging is an Office 365 security and compliance feature. You need the right Office 365 licenses to use this feature.
