### ISSUE TITLE
Please add API calls in the per flow plan to section 'Request limits based on user licenses section'.

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/power-platform#880]
Please add API calls in the per flow plan to section 'Request limits based on user licenses section'.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#will-there-be-a-transition-period-for-existing-customers)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by MiyukiAmino** [comment]
The "per flow plan" has nothing to do with user licenses, so a link to the Power Automate page or an explanation in the annotations would be very helpful.

Customers want to see as much as possible on one page of the options they can take.

**Comment by jimholtz** [comment]
Taking to internal thread.
