### ISSUE TITLE
Qualify different role types when creating Env type Policies.

### ISSUE THREAD

**Issue by binaryjam** [MicrosoftDocs/power-platform#881]
When creating Environment level Policies, you say you need Environment Admin role,  when there is a data verse, this role does not exists, its equivalent is most likely Sys Admin.   You should say so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dea88353-deff-d4d6-c1fc-ab36e1cf9d6d
* Version Independent ID: 600c9506-f379-092b-b32a-2e64b4999bed
* Content: [Create a data loss prevention (DLP) policy - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-dlp-policy)
* Content Source: [power-platform/admin/create-dlp-policy.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-dlp-policy.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@binaryjam 
Thanks for the suggestion. We'll incorporate this change soon.
