### ISSUE TITLE
Add the entity needs to be in the App

### ISSUE THREAD

**Issue by DaveSHarris** [MicrosoftDocs/power-platform#882]
In addition to the configuration included in this page the user also need to ensure that the entity is included in the App that the user in using.   So even if it is not needed in the navigation, the search will not use it unless it in included in the list of entities.   We picked this up from MS support so thank you to them but i think it would be useful to show this here so that other users are aware.   Thanks .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f4b53c-095c-4bf9-46dd-62299f2568e5
* Version Independent ID: 92a06c7b-d9b6-1a85-fb46-8378273a5994
* Content: [Configure Relevance Search to improve search results and performance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/configure-relevance-search-organization)
* Content Source: [power-platform/admin/configure-relevance-search-organization.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/configure-relevance-search-organization.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@DaveSHarris 
Thanks for the suggestion. We'll consider this for future documentation updates.
