### ISSUE TITLE
Delete a bot doesn't work in MS Teams

### ISSUE THREAD

**Issue by GomesLuciano** [MicrosoftDocs/power-platform#883]
I created a bot and associated it to a wrong Team, and since it is not possible to change the Team associated to it, I created a second bot (linked to the right Team this time) and now the old bot is not necessary anymore.

I followed the instructions (https://docs.microsoft.com/en-us/power-virtual-agents/authoring-first-bot) to delete the old bot but it did not work: after the message "Processing your request" disappeared the bot was still there.

Is there any other settings I should check?

**Comment by v-alarioza** [comment]
@GomesLuciano Did you resolve this issue? I'm not sure what the state of the doc was back when you opened this, but looking at it today, it appears to be correct.
