### ISSUE TITLE
Unclear as to how to grant consent

### ISSUE THREAD

**Issue by diverdown1964** [MicrosoftDocs/power-platform#884]
Step number 3 is unclear - the "more information" link doesn't provide any details - how is consent granted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c237709a-db62-a57b-838c-5ee6c004bb55
* Version Independent ID: 3157a6e5-9a05-74b1-12b0-cd563817d327
* Content: [Preview: Tenant-level analytics - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/tenant-level-analytics)
* Content Source: [power-platform/admin/tenant-level-analytics.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/tenant-level-analytics.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by jimholtz** [comment]
@diverdown1964 
Thanks for the feedback. We changed the link to the following:
https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals
