### ISSUE TITLE
Missing dependencies in CenterofExcellenceAuditComponents_2_0_managed - Import is impossible

### ISSUE THREAD

**Issue by megel** [MicrosoftDocs/power-platform#886]
The import of CenterofExcellenceAuditComponents_2_0_managed is Impossible, because there is a missing dependency:
![image](https://user-images.githubusercontent.com/15800069/132650793-e474e71c-6884-4b61-ae59-d96e4fe28031.png)

My environment contains these solutions:
![image](https://user-images.githubusercontent.com/15800069/132650983-4e1e2046-607b-456b-a0ce-bf565d82288d.png)

The environment was created yesterday and I used this CoE Starterkit:
![image](https://user-images.githubusercontent.com/15800069/132651265-95afb706-073d-4ae2-85ed-f1ad8ad1c517.png)

**Comment by RickKush** [comment]
Create and run a dummy Flow with an Approval action, and the missing object will be automatically created.

**Comment by KendalBond007** [comment]
Thanks for your feedback. We are closing this issue because it has been unaddressed since 25 Oct 2022 (with a proposed solution). If you're still experiencing the issue described here, please reopen or create a new issue.
