### ISSUE TITLE
Typo error : globalContext.userSettings.Roles --> globalContext.userSettings.roles

### ISSUE THREAD

**Issue by sybaris** [MicrosoftDocs/power-platform#887]
Hi,

There is a typo error :
It's not "globalContext.userSettings.Roles" but "globalContext.userSettings.roles".
It's important because javascript is case sensitive

Regards
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a241829-ba79-0d2e-d061-cedb8978fbeb
* Version Independent ID: 867a90ce-0a3e-0a82-0458-acf7e783e961
* Content: [Important changes (deprecations) coming in Power Apps, Power Automate and customer engagement apps - Power Platform](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-dataverse)
* Content Source: [power-platform/important-changes-coming.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/important-changes-coming.md)
* Service: **power-platform**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by jimholtz** [comment]
@sybaris 
Thanks for bringing this to our attention. This has been corrected.
