### ISSUE TITLE
Issue with exporting PVA bot content files

### ISSUE THREAD

**Issue by ijarenamrata** [MicrosoftDocs/power-platform#888]
Hi Team,
I have followed the steps given in below link to export annotations.csv and msdynce_botcontents.csv file from power apps Dataverse section for bot created in Power Virtual Agent.
https://docs.microsoft.com/en-us/power-virtual-agents/advanced-use-dispatcher

According to the document, files should contain data related to PVA Bot. But, I am getting empty files.

I tried in different environments. But, still facing the same issue.

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a1322f-8123-d498-1a5c-431ad816c389
* Version Independent ID: a5f4b3d4-2a1a-edcc-c9fa-b3e2154e65ff
* Content: [Use a Microsoft Bot Framework bot - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-use-dispatcher)
* Content Source: [power-virtual-agents/advanced-use-dispatcher.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/advanced-use-dispatcher.md)
* Service: **power-virtual-agents**
* GitHub Login: @pawant-ms
* Microsoft Alias: **iawilt**

**Comment by saikumaru** [comment]
@iaanw please advice if there is any resolution planned, or is there a way we can approach the support to help resolve this.

We are facing the same issue too and its a blocker to integrate this whole product in itself.

**Comment by iaanw** [comment]
Hi @saikumaru, I'm investigating this issue with the project manager for this feature. While we continue to investigate, one suggestion is to try the recently released ['Power Virtual Agents as a skill' feature](https://docs.microsoft.com/power-virtual-agents/advanced-use-pva-as-a-skill).

**Comment by ijarenamrata** [comment]
Hi @iaanw, This feature is still in preview. We cant use that for the project. It will be good if you provide a solution for the above approach.

**Comment by iaanw** [comment]
Hi all, I have heard back from the PMs for this feature, and wanted to share their suggestions. I'll be reviewing this additional documentation and updating our docs to describe how to achieve what the PM suggests. As that may take some time, I wanted to share this with you ASAP in the meantime. I hope it helps!


>Orchestrator works in both Composer and code-first solutions. I’d highly recommend that the customer look at the PVA as a skill route with Composer, even if in preview. Or use PVA as root and turn their bots to skills.
>
>Here’re a few references to get started:
>
>[Use multiple LUIS and QnA models with Orchestrator - Bot Service | Microsoft Docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-orchestrator?view=azure-bot-service-4.0&tabs=cs)
>
>Migration: [botframework-sdk/DispatchMigrationExample.md at main · microsoft/botframework-sdk (github.com)](https://github.com/microsoft/botframework-sdk/blob/main/Orchestrator/docs/DispatchMigrationExample.md)
>
>(more about Orchestrator - [Intent recognition with Orchestrator in Bot Framework Composer | Microsoft Docs](https://docs.microsoft.com/en-us/composer/concept-orchestrator)
>
>The PVA code side should remain the same.

I'm going to close this issue now, if you would like additional help from the engineering team, please feel free to create a post at Power Virtual Agents forum at [https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums).
