### ISSUE TITLE
Incorrect expression to use adaptive card JSON as attachment

### ISSUE THREAD

**Issue by dmvtech** [MicrosoftDocs/power-platform#890]
In the section on Prompt for Text/attachment, it says to use the following:
`-${StartTrialForm()}`

It actually needs to be:
`-${json(StartTrialForm())}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87bc97a8-ee08-44a0-f12c-f674ba05fe14
* Version Independent ID: 3c3e9153-6d8f-9897-e05a-21f01b446545
* Content: [Use Bot Framework Composer to display a form in chatbots - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example4)
* Content Source: [power-virtual-agents/advanced-bot-framework-composer-example4.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/advanced-bot-framework-composer-example4.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
Looks like this was fixed shortly after this issue was opened via [af203ddd](https://github.com/MicrosoftDocs/power-platform-pr/commit/af203ddd5dc714a9081d830312e5402ca52b0253). It's not currently what the proposed fix is here, but that seems intended as the doc/example has changed.
