### ISSUE TITLE
Date for station CRM17

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/power-platform#895]
[Enter feedback here]

Hello,
Switzerland is a new station, can you tell when the wave is available exactly?
Thank you

Pierre-Olivier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dea32204-b115-83f9-daaf-0dfc6a4a7318
* Version Independent ID: 96d429a7-8856-a481-c5df-6b80f0bc632b
* Content: [General availability deployment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/general-availability-deployment#deployment-schedule)
* Content Source: [power-platform/admin/general-availability-deployment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/general-availability-deployment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@popujol 
We've updated the contact with Switzerland deployment information.
