### ISSUE TITLE
Permissions needed to access this page/data

### ISSUE THREAD

**Issue by goantu** [MicrosoftDocs/power-platform#90]
I'd love to see added here the roles required in the platform (global admin, service admin, etc) required to access this page. thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c99626-6458-46b4-f099-ce10c30890c7
* Version Independent ID: d3766ded-359b-160c-d7f5-a7e6ffa103d6
* Content: [Common Data Service analytics - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service#feedback)
* Content Source: [power-platform/admin/analytics-common-data-service.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/analytics-common-data-service.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@goantu 
Thanks for the suggestion. Required roles added.
