### ISSUE TITLE
Where to use the deploymentSettings file in automated ALM?

### ISSUE THREAD

**Issue by maniskt** [MicrosoftDocs/power-platform#900]
Hi, 

This query is for getting clarity on deploymentSettings file usage in automated deployment. I understand this feature is in preview and I'm testing it out.

In our setup, we’ve three Power Platform environments and three pipelines (with separate service connection for each environment) as below – 
Dev environment –> Build pipeline - Import to repository
Build environment –> Build pipeline – Build managed solution
Prod environment –> Release pipeline – Deploy to production environment (as managed solution)
This is as per the Microsoft Build Tool tasks [article](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks#build-and-release-pipelines).

In order to extract the deployment settings file, I’m connecting to the Dev environment with pac CLI. 
As next step, I get the connection ids and environment variable values from my Prod environment because that is where the actual production app will reside. And then check-in my deploymentSettings file with all these details.

Now, as per my understanding, I should be using this deploymentSettings file (obtained from build artifact) in the Import solution task in my Release pipeline as below – 

![image](https://user-images.githubusercontent.com/90703447/134135932-bb65dce3-9f70-4efc-8511-3e04fa5d20a4.png)

This is in contrast to the step provided in the [documentation ](https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools#step-4-use-the-deployment-settings-file-for-build-tools-tasks) where the deploymentSettings file is being used in Build environment’s Build pipeline. Since build and prod environments are different environments, the connection IDs for the connection references won’t be same. 

Can you please confirm if the deploymentSettings file should only be used in Release pipeline in the above setup? Or is there another way to go about this automated deployment?

Regards,
Manish 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1df5d8-ef79-c56d-3950-0617da9f976b
* Version Independent ID: ff132857-2fc9-57d0-df24-d42c054cbf1c
* Content: [Pre-populate connection references and environment variables for automated deployments using Power Platform Build Tools - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools)
* Content Source: [power-platform/alm/conn-ref-env-variables-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/conn-ref-env-variables-build-tools.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by kkanakas** [comment]
You can create multiple deployment settings file for different environments. You can technically create a deploymentsettingsProd.json and then a deploymentsettingsdev.json and use them in the context of the environment that you are deploying to. It is not mandatory to have just one file. Remember in the documentation, we have documented the most simple of scenarios.
