### ISSUE TITLE
Implementation using Power Apps trial plan 2 license

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/power-platform#903]
Good day!
Can we use our existing Power apps trial plan 2 license during the development/uat phase? What could be the limitation? Also the PowerApps app should be hosted on our existing tenant? 

Thank you
Jovel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by jimholtz** [comment]
@jlabustro 
Please see if you can get your question answered here:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
Or create a support request:
https://powerapps.microsoft.com/support/
