### ISSUE TITLE
Grammar error on Operators and Identifiers

### ISSUE THREAD

**Issue by carolinamogas** [MicrosoftDocs/power-platform#905]
Hi! 

There's a small grammar error in the first sentence of the article: 
"The operators in Microsoft Power Fx are described **_bdlow_**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b415bac5-7665-0430-4f5f-c0bc51168580
* Version Independent ID: 2da7b462-e5fa-cf80-ee57-216e485f850a
* Content: [Operators and Identifiers in Microsoft Power Fx - Power Platform](https://docs.microsoft.com/en-us/power-platform/power-fx/operators)
* Content Source: [power-platform/power-fx/operators.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/operators.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jimholtz** [comment]
Taking to internal thread.
