### ISSUE TITLE
Migration only available for Dynamics CRM. 

### ISSUE THREAD

**Issue by Eakawie** [MicrosoftDocs/power-platform#906]
According to Support, Tenant-to-Tenant migration is only possible with Dynamics CRM Environments. Migrating a Power Apps or Power Automate environment is not supported. This should be made clear on this page, as there is nothing specifying that a Power Apps Environment may not be migrated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf83baaf-d9eb-6e3d-1040-9ae94cd410db
* Version Independent ID: ae37a7a0-1e5a-a2ef-72c8-bf6d2601cae1
* Content: [Migrate an environment to a different tenant - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/move-environment-tenant)
* Content Source: [power-platform/admin/move-environment-tenant.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/move-environment-tenant.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Eakawie 
Thanks for the feedback. We're reviewing for a future document update.
