### ISSUE TITLE
"HELPER - ObjectOperations" does not need run-only users permissions setup

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#907]
Child flow "HELPER - ObjectOperations" does not have connections defined as it seems to trigger other HELPER flows. So no need go to run-only permissions just enable the flow 

![image](https://user-images.githubusercontent.com/8307644/134891573-ddb306fd-b3df-4715-8d29-5fdb9c111bd6.png)
 

![image](https://user-images.githubusercontent.com/8307644/134890880-1dab72a3-0b3e-4ecd-a3a1-9eec8be9a970.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
We're reviewing this together with #990 for the next release and will update the docs for December.
