### ISSUE TITLE
Getting error while clicking Dynamics 365 for Outlook

### ISSUE THREAD

**Issue by hem-sharma** [MicrosoftDocs/power-platform#909]
Hi, I am trying to install Dynamics 365 app for outlook and having following issues:

* I can not see the "Dynamics 365 for outlook" security role that is being provided to active user,
* I can not see the navingation under system for sitemap even I tried the [link](https://d365demystified.com/2020/10/01/dynamics-365-app-for-outlook-missing-on-sitemap-in-crm-use-shortcut-link-quick-tip/) for solution but manual url browse and adding under sitemap both gives error as:
![image](https://user-images.githubusercontent.com/15911296/135411794-0584cf61-35c6-4d26-a982-a824af2f5921.png)
* also the snapshot for navigation is:
![image](https://user-images.githubusercontent.com/15911296/135412142-e9165545-afc7-4a1c-9bfc-072e6c59aa05.png)
* App for Dynamics 365 doesn't have outlook app option
![image](https://user-images.githubusercontent.com/15911296/135412606-d100dee7-8b7d-4193-b5ed-443707c5b56b.png)

Version details:

![image](https://user-images.githubusercontent.com/15911296/135412843-b2f1d751-06a2-41bd-8ceb-c4eb2c206aea.png)

For this I am using O365 E3 90 days trial version, enabled server-side sync, test & enabled mailbox, enabled OAuth using PS.

Can somebody from the team help me out what I am missing here?

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eadb9e2-bc3a-25e6-ec3d-e85e1f404405
* Version Independent ID: 5b70c7ac-bce9-36ec-09ce-c9291c1744e0
* Content: [Administer Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/admin-documentation)
* Content Source: [power-platform/admin/admin-documentation.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/admin-documentation.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@hem-sharma 
Please review the following to see if this resolves your issue:
https://docs.microsoft.com/en-us/dynamics365/outlook-app/deploy-dynamics-365-app-for-outlook

If not, please contact support:
https://powerapps.microsoft.com/support/
