### ISSUE TITLE
Integration with Business Central

### ISSUE THREAD

**Issue by tbezzina** [MicrosoftDocs/power-platform#91]
When using the standard Integration between Business Central and Dynamics 365 for Sales a large number of api calls are done from Business Central .  Will these count against the daily limit ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations?source=docs#feedback)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by pm-biteam** [comment]
Great question! I am also curious about how this is counted :-)

**Comment by jimholtz** [comment]
@tbezzina 
Here's the product team response:
Yes. Anything that touches Common Data Service counts. 
This quota is counted at the application user level. So every tenant gets 25K – 100K application user quota of API calls per day. If the integration is setup to run under the application user, it follows the higher limits per day.

**Comment by tbezzina** [comment]
Microsoft insists of provide a seemingly "Clever" response by always involving the Common Data Services as if the client will care what is being accessed in between. The CLIENT IS PAYING FOR LICENSES FOR BOTH MICROSOFT PRODUCTS the least decency Microsoft can have is to integrate between two paid own products without hidden charges to the client. This nonsense is unseen in any other serious multiplatform provider.
