### ISSUE TITLE
Tenent-Level Analytics: "Get Insights" Error

### ISSUE THREAD

**Issue by NathanMTMSFT** [MicrosoftDocs/power-platform#910]
Hello,
The "Get Insights" feature returns a window stating a PPU is required.
The user is a Power BI Admin with PPU license and still receives this message.
When clicking "Try Free" an error message is returned instead. "Sorry, we are unable to start trial at this time."
![image](https://user-images.githubusercontent.com/88182980/135441514-c61457be-63e0-4a5c-ac03-9d241f534cbe.png)
![image](https://user-images.githubusercontent.com/88182980/135441981-e921b4c0-b054-42b2-9d49-9e36e0ecd9c9.png)

Is this feature meant to be available for these reports?
If so, is there any reason why Users cannot use this feature when they have full Power Platform Admin Access & are Power BI PPU?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c237709a-db62-a57b-838c-5ee6c004bb55
* Version Independent ID: 3157a6e5-9a05-74b1-12b0-cd563817d327
* Content: [Preview: Tenant-level analytics - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/tenant-level-analytics)
* Content Source: [power-platform/admin/tenant-level-analytics.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/tenant-level-analytics.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by jimholtz** [comment]
@NathanMTMSFT 
Sorry for the delayed response. For product-related feedback, visit https://aka.ms/ppac-ideas. If this issue still exists, please contact support: https://powerapps.microsoft.com/support/
