### ISSUE TITLE
Validating URLs

### ISSUE THREAD

**Issue by NormanVadnais** [MicrosoftDocs/power-platform#911]
In identifying the Government Power Apps URLs, you take two different commercial URLs and link them to the very same URLs for Government. For commercial you have "make", "create", "flow", and "admin". For Government you have "make", "make", "flow", and "admin".

Blatantly looks wrong so I wanted to confirm. If make and create are combined for Government, you should note that so people understand it is a known convergence.

Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea524f2a-1e2a-6ade-8e2b-bc61173107c5
* Version Independent ID: 5990c060-8907-62b4-a8b3-f7ed8339a70e
* Content: [Microsoft Power Apps US Government - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government)
* Content Source: [power-platform/admin/powerapps-us-government.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-us-government.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@NormanVadnais 
Sorry for the delayed response. We've rewritten this topic. Please let us know if this is still an issue.
