### ISSUE TITLE
ALM Accelerator - Missing configuration steps and recommendation for small changes

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#914]
**Create an Azure AD app registration**

As Azure AD application requires only Dynamics user_impersonation permissions we could use the AAD OOB "1950a258-***" app principal which already has this permission. This way we do not need to register separate app principal for this. Or isn't that OOB app principal recommended to be used in general?

&nbsp;
&nbsp;
**Update the Webhook Url value**

We need to set run-only permissions for **GetAppAndFlows** child flow before it is possible to change, save and enable the **WorkflowCompleteNotification** flow

![image](https://user-images.githubusercontent.com/8307644/135831594-7f74c2f2-49c4-4840-b150-c0e0260f2c21.png)

![image](https://user-images.githubusercontent.com/8307644/135830684-7a8560b2-13c5-4156-bdf7-5fc9fe9331fd.png)

Also mention that we need to enable **WorkflowCompleteNotification** after saving it (to generate the trigger url) and to be able to execure the flow in github action workflow. If it not enabled then you will see this type of error in GitHub actions workflow

![image](https://user-images.githubusercontent.com/8307644/135831961-37f1fe2b-c80d-451c-b235-b0e9c3116b2d.png)

&nbsp;
&nbsp;
**Free GitHub org plan**

I guess this should be moved to **Use the ALM Accelerator for Makers app** instructions as we need to have repo first to configure secrets as there is no option do secrets configuration similarly as in ogr plan

https://docs.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-components

![image](https://user-images.githubusercontent.com/8307644/135832958-9231d2e5-bd79-47a5-8862-5178895ea711.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d3a97-f062-9c7c-a5b6-8ec69178e1bc
* Version Independent ID: 476f4f57-b869-c759-74cc-beb4e2deaa26
* Content: [Set up ALM Accelerator for Makers components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator)
* Content Source: [power-platform/guidance/coe/setup-almaccelerator.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almaccelerator.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by mikefactorial** [comment]
@petepuu thanks for the detailed feedback. Adding an issue to microsoft/coe-starter-kit to track this and get it fixed. https://github.com/microsoft/coe-starter-kit/issues/1338
