### ISSUE TITLE
日本語ページで、日本の営業時間の記載に誤りがあります。

### ISSUE THREAD

**Issue by KoichiKitamura1** [MicrosoftDocs/power-platform#919]
https://docs.microsoft.com/ja-jp/power-platform/admin/support-overview
の「現地の営業時間とはいつですか。」で「日本」は
午前 7 時 ～午後 5 時 30 分 ローカル時刻
と記載がありますが正しくは
午前 9 時 ～午後 5 時 30 分 ローカル時刻
です。

英語サイトの記載は正しくなっています。
https://docs.microsoft.com/en-US/power-platform/admin/support-overview

日本語サイトを正しく修正お願いいたします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4d40b926-c24e-dd83-c0db-81ac12b2b7a6
* Version Independent ID: e81e19c4-92aa-40df-8b82-51b56d3d3fa3
* Content: [Dynamics 365 での Microsoft Power Platform および顧客エンゲージメント アプリのサポート - Power Platform](https://docs.microsoft.com/ja-jp/power-platform/admin/support-overview)
* Content Source: [power-platform/admin/support-overview.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/admin/support-overview.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jowilco** [comment]
@KoichiKitamura1 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jimholtz** [comment]
@KoichiKitamura1 
フィードバックをお寄せいただきありがとうございます。これを修正します。
