### ISSUE TITLE
What happens after an update is published once the app is approved ? 

### ISSUE THREAD

**Issue by vijaysaimutyala** [MicrosoftDocs/power-platform#920]
Once the bot is published after Admin's approval, what happens when you issue an update next time changing some topics. Would there be an submit for app update kind of button like Teams App Studio or once it's approved, it'll stay approved and all the updates will just flow over ? My question comes from the context that an updated should first be tested by a small team (using the Submit for your team) before rolling out to the entire org.

Adding some screenshots in this regard might be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d57237c4-194c-60b1-8f50-6c171da74a37
* Version Independent ID: d833bef8-ccdd-e2b4-abaa-691a875851cb
* Content: [Publish your chatbot with the Power Virtual Agents app in Microsoft Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams#install-a-bot-as-an-app-in-microsoft-teams)
* Content Source: [power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
Admin approval is only required when submitting your bot to the [Teams app store](https://docs.microsoft.com/en-us/power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams#show-the-bot-in-microsoft-teams-app-store). As per the note in [this section](https://docs.microsoft.com/en-us/power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams#submit-for-the-built-by-your-org-section):
> Make sure you review the content when it's ready for an admin to review. You will need to submit new requests to the admin to [update the icon and descriptions](https://docs.microsoft.com/en-us/power-virtual-agents/teams/publication-add-bot-to-microsoft-teams-teams#customize-bots-appearance-in-microsoft-teams) for bots that were previously approved.
> Once approved, all new and existing users of the bot in Teams will receive the update.
> This only applies to the bot details. You can continue to make content updates to your bot by publishing the latest content without needing to re-submit to admin.

If you'd like to make a product request regarding limited rollouts, the best place is [the Power Virtual Agents forum](https://powerusers.microsoft.com/t5/Forums/ct-p/pva_forums).
