### ISSUE TITLE
Referring to wrong PowerApps name in solution (Core Components version 3.13)

### ISSUE THREAD

**Issue by fjoesne** [MicrosoftDocs/power-platform#923]
Step 12 (d) Environment variable that refers to a PowerApp by its old name.

> Turn on the flows starting with Env Request and DLP Request if you are using the Power Platform Request Center. Make sure the Admin eMail and **Environment Request Admin App Url** environment variables are configured before turning on those flows.

[Environment Request Admin App Url](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables) description:

> Link to the Admin - Power Platform Resouce RMS canvas app included in this solution. Leave empty on Import and fill it in once the app is installed.
To do that, navigate to the details page of the **Admin - Power Platform Resouce RMS** (canvas app) included with this solution, and use the wek link (to launch the app).

I assume "**Admin - Power Platform Resouce RMS**" is supposed to be "**Admin - Environment Request**"

It appears that the name "Admin - Power Platform Resouce RMS" is also used[ elsewhere in the documentation](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#admin---power-platform-resource-rms-request-management-system)

Renaming of this app seems to have happened between the september and october release:
September: [Admin - Power Platform Resouce RMS](https://github.com/microsoft/coe-starter-kit/blob/6befae872c027acc7ddcde699a1fe0af3eaab3a8/CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/coe_environmentrequestappadmin_58e3b_DocumentUri_msapp_src/CanvasManifest.json#L83)
October: [Admin - Environment Request](https://github.com/microsoft/coe-starter-kit/blob/f6986de20c14caa859e9e9af7b65335b593e9ef8/CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/coe_environmentrequestappadmin_58e3b_DocumentUri_msapp_src/CanvasManifest.json#L82)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you! Updated this in our local version now for the December release.
