### ISSUE TITLE
Link to defaultStyleOptions.js leads to 404 on GitHub

### ISSUE THREAD

**Issue by pjsummersjr** [MicrosoftDocs/power-platform#927]
The link to _defaultStyleOptions.js file_ in the section _Customize the bot icon, background color and name_ leads to a 404 error on GitHub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b1fcdf-f5ae-8302-1a7c-984c2dd2f81b
* Version Independent ID: ec989e88-349e-6a1b-c55d-7a4b4b600815
* Content: [Customize the web chat canvas - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/customize-default-canvas)
* Content Source: [power-virtual-agents/customize-default-canvas.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/customize-default-canvas.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Please see the link to the js file on this page instead: https://docs.microsoft.com/azure/bot-service/bot-builder-webchat-customization?view=azure-bot-service-4.0

I'll be updating the PVA docs to point to that page instead of directly to the js file.

Hope this helps!
