### ISSUE TITLE
bad sentence structure

### ISSUE THREAD

**Issue by ATDev90** [MicrosoftDocs/power-platform#929]
Ein Schlüsselprinzip besteht darin, klarzustellen, warum Sie einen CoE einrichten, was Sie erreichen wollen und welche wichtigen Geschäftsergebnisse Sie sich erhoffen. Dann fangen Sie an und lernen Sie dabei und entwickeln Sie sich weiter. Für viele ist der CoE der erste Schritt zur Förderung von mehr Kreativität und Innovation in der gesamten Organisation, indem er die Geschäftseinheiten in die Lage versetzt, ihre Geschäftsprozesse zu digitalisieren und zu automatisieren und gleichzeitig das erforderliche Maß an zentraler Aufsicht und Leitung aufrechtzuerhalten.

Has to be something like this:
Ein Schlüsselprinzip besteht darin, klarzustellen, warum Sie einen CoE einrichten, was Sie erreichen **möchten** und welche wichtigen Geschäftsergebnisse Sie sich erhoffen. **Dann fangen Sie an, lernen und entwickeln Sie sich weiter**. Für viele ist der CoE der erste Schritt zur Förderung von mehr Kreativität und Innovation in der gesamten Organisation, indem die Geschäftseinheiten in die Lage versetzt werden, ihre Geschäftsprozesse zu digitalisieren und zu automatisieren und gleichzeitig das erforderliche Maß an zentraler Aufsicht und **Governance** aufrechtzuerhalten.

I didn't mark every change, but for a german native speaker, this paragraph make it more readable.

[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2713d356-fba8-b8d1-cd56-c949e8c01fe5
* Version Independent ID: 9dc32bb0-30fb-2bc2-a92a-b4f3ef24d984
* Content: [Was ist ein Center of Excellence - Power Platform](https://docs.microsoft.com/de-de/power-platform/guidance/coe/motivation)
* Content Source: [power-platform/guidance/coe/motivation.md](https://github.com/MicrosoftDocs/power-platform-pr.de-DE/blob/live/power-platform/guidance/coe/motivation.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
@jimholtz this is a comment regarding the German translation of this page. I'm not sure what action to take here, the pages are auto-translated right?

**Comment by jimholtz** [comment]
@ATDev90 
I've passed this on to the localization team. It may take a few weeks for the changes to go live.
