### ISSUE TITLE
Typo / ambiguous sentence "Create a new connection to the all connectors."

### ISSUE THREAD

**Issue by fjoesne** [MicrosoftDocs/power-platform#931]
* Typo / confusing sentence - [Import the solution (step 3)](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#import-the-solution): 

> "Create a new connection to the all connectors."

* Clarify "**new** connection to **all** connectors": 
This can be interpreted as actually creating new connectors instead of using existing connectors present if the reader has also followed the documentation for installing [core components (step 9)](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#option-1-import-the-solution-into-a-production-environment) and the approvals connector by creating a dummy approvals flow ([Initialize flow approval tables in your environment](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14181d4-574f-95e3-c2c9-545116549c9b
* Version Independent ID: bf449b92-6756-e08a-a58c-d561e36947cb
* Content: [Set up governance components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components)
* Content Source: [power-platform/guidance/coe/setup-governance-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-governance-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Made a local change, will be updated in December. Thank you!
