### ISSUE TITLE
Korean content is wrong - "Consumption of per app licensing"

### ISSUE THREAD

**Issue by mabelmaotest** [MicrosoftDocs/power-platform#938]
"앱별 라이선스 소비" 내용이 틀렸음:

wrong: 2개의 Power Apps 및 하나의 포털
correct: 1개의 Power Apps 혹은 하나의 포털
sample image is wrong too.

>앱별 라이선스 소비
>앱별 라이선스는 사용자에게 단일 환경에 대해 2개의 Power Apps 및 하나의 포털에 대한 액세스 권한을 제공합니다. 애플리케이션 및 사용된 환경 수에 따른 라이선스 소비의 예는 아래 표를 참조하십시오.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 0f1f9ece-05b6-907c-9d52-5a19f5bf9872
* Version Independent ID: 9eaed30a-4c07-ef03-e3b4-d3db9989a760
* Content: [Power Apps 앱별 플랜 정보 - Power Platform](https://docs.microsoft.com/ko-kr/power-platform/admin/about-powerapps-perapp)
* Content Source: [power-platform/admin/about-powerapps-perapp.md](https://github.com/MicrosoftDocs/power-platform-pr.ko-KR/blob/live/power-platform/admin/about-powerapps-perapp.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@mabelmaotest 
Thanks for the note. We'll get this corrected.
