### ISSUE TITLE
The Steps are not reproducible in the last Version of Bot Composer

### ISSUE THREAD

**Issue by AlexandrosIV** [MicrosoftDocs/power-platform#939]
[Enter feedback here]
Hi, is my first time using composer (v2.1) and I found that the steps in the article are not working in the composer.
cant add the steps needed directly to the code section, but to select in the dialog box send attachment to display the adaptative card.

seems that the article is needed an update to reflect the latest version of the composer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309a5abe-486a-bad3-4de9-abb6b7ed0869
* Version Independent ID: 36c5d403-655a-6222-b4db-dcfa73354669
* Content: [Use Bot Framework Composer adaptive cards in chatbots - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example1)
* Content Source: [power-virtual-agents/advanced-bot-framework-composer-example1.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/advanced-bot-framework-composer-example1.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Hi, thank you for the feedback. We're working on updating these docs and I'll reply back to this issue when we publish them. For now, I'll close this comment.
