### ISSUE TITLE
Incorrect details at: https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on#control-who-can-allocate-add-on-capacity

### ISSUE THREAD

**Issue by robfinney** [MicrosoftDocs/power-platform#949]
Trying to follow through the Section on Control who can allocate add-on capacity but the instructions do no line up with what is in the Power Platform Portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0cbf8c-5c12-5aa2-3786-392d0f498303
* Version Independent ID: 2774f5ca-1c86-4fe6-c296-6f7f45aa6702
* Content: [Capacity add-ons for Power Apps and Power Automate - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/capacity-add-on#control-who-can-allocate-add-on-capacity)
* Content Source: [power-platform/admin/capacity-add-on.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/capacity-add-on.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@robfinney 
Taking to internal thread.
