### ISSUE TITLE
Core component description is not accurate

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/power-platform#950]
The description states that "The core components solution contains assets relevant only to admins".
It was true at the begining, but it's not anymore : 
- the welcome email flows sends emails to makers
- App catalog, environment requests, and maker command center are apps for makers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f7e68-a58d-f9a1-1f2a-3f2bec8e58e2
* Version Independent ID: 119292c3-9155-226c-8f26-9b92a86c0aa5
* Content: [Core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components)
* Content Source: [power-platform/guidance/coe/core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thank you, removed this for the December release (updated the local copy).
