### ISSUE TITLE
D365 Licenses

### ISSUE THREAD

**Issue by smgtreker** [MicrosoftDocs/power-platform#951]
It would be helpful if this page explicitly stated the situation in regards to how this fits in with D365 licenses. E.g. Do they work like PowerApps Per User licenses and they would not be counted towards the metered usage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8271e81-5041-5791-4cf8-e2cfbe55656d
* Version Independent ID: a8271e81-5041-5791-4cf8-e2cfbe55656d
* Content: [Preview: Pay-as-you-go meters - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/pay-as-you-go-meters?tabs=image)
* Content Source: [power-platform/admin/pay-as-you-go-meters.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/pay-as-you-go-meters.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by Kavishi** [comment]
@jimholtz any Dynamics license which provides an access to Power Apps per user license will not be counted in the meter unit. We can make a note in the docs that users with Dynamics license that provides access to per user license will not be counted.

**Comment by jimholtz** [comment]
@smgtreker 
Thanks for the feedback. We'll update the content.

**Comment by smgtreker** [comment]
Thanks all!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
