### ISSUE TITLE
Spelling error trials 

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/power-platform#952]
should be trials and not trails. :)

Admins can use PowerShell cmdlets to enable or disable trails.

**Comment by jimholtz** [comment]
@JerryCRMI 
Thanks Jerry, for notification of the somewhat humorous typo. Corrected.
https://docs.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types#how-can-i-convert-a-trial-environment-to-a-production-environment
