### ISSUE TITLE
Typo in "Consumption of per app licensing"

### ISSUE THREAD

**Issue by MichaelKMorrison** [MicrosoftDocs/power-platform#953]
The use of "APP A" appears twice in the User 1 row.  Should be App A - App B

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1f9ece-05b6-907c-9d52-5a19f5bf9872
* Version Independent ID: 9eaed30a-4c07-ef03-e3b4-d3db9989a760
* Content: [About Power Apps per app plans - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-powerapps-perapp)
* Content Source: [power-platform/admin/about-powerapps-perapp.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/about-powerapps-perapp.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@MichaelKMorrison 
Thanks for the notice. Typo fixed.
