### ISSUE TITLE
Several features mentionning 2020 when we are already end of 2021

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/power-platform#960]
Some feature availability mention 2020 as potential availability date.
As we are already end of 2021, these dates should be updated to reflect our current roadmap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19a75e1f-470d-2dda-a269-80d52b2a6314
* Version Independent ID: 634dbb4a-815f-3e65-c99f-1fa75a5752d7
* Content: [Power Apps operated by 21Vianet and Power Automate operated by 21Vianet - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/business-applications-availability-china)
* Content Source: [power-platform/admin/business-applications-availability-china.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/business-applications-availability-china.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Taking to internal thread.
