### ISSUE TITLE
US Government access

### ISSUE THREAD

**Issue by cchapin-ms** [MicrosoftDocs/power-platform#962]
[Enter feedback here]
In the "Who can create environments in these regions" section, there is this line:

Only a US Government associated organization can create an environment in US Government (GCC).

GCC tenants are in Azure Commercial, and GCC High tenants are in the US Government sovereign cloud, also know as Azure Gov. Should the statement read as GCC High?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4df941f8-45db-4cdd-c7d1-363febdd42dc
* Version Independent ID: cc136308-8205-6516-e05e-1c8e5a94f3c0
* Content: [Choose the region when setting up an environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/regions-overview)
* Content Source: [power-platform/admin/regions-overview.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/regions-overview.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Taking to internal thread.
