### ISSUE TITLE
All Power Automate Actions = Power Platform Request?

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/power-platform#963]
In the section, "What is a Microsoft Power Platform request?", the Power Automate bullet says, "all API requests to connectors, process advisor analysis, HTTP actions, and built-in actions from initializing variables to a simple compose action. Both succeeded and failed actions count towards these limits. Additionally, retries and other requests from pagination count as action executions as well."

While it makes sense that requests to connectors, process advisor analysis, and HTTP actions might count as Power Platform Requests, it is very surprising to read that built-in actions from initializing variables to a simple compose action would also count as Power Platform Requests.

I understand that they will count as Power Automate Actions, as this description seems to have been almost copy/pasted from the [Power Automate Limits page](https://docs.microsoft.com/en-us/power-automate/limits-and-config#action-request-limits): "There are limits to the number of _actions_ a cloud flow can run. These runs are counted for all types of actions, including connector actions, HTTP actions, and built-in actions from initializing variables to a simple compose action. Both succeeded and failed actions count towards these limits. Additionally, retries and additional requests from pagination count as action runs."

Is the intention here to convey that _every single action_ within a Power Automate Flow will be counted as a Power Platform Request? If so, it would be clearer to just say that instead of listing out examples. If that is not the intention here, please update this page to better illustrate what actions within a Power Automate Flow are NOT counted as Power Platform Requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@devlinl 
Thanks for the comments. We added the following link to provide more information:
https://docs.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types#what-counts-as-power-platform-request
