### ISSUE TITLE
Docs の記述訂正について

### ISSUE THREAD

**Issue by ShinyaNishimura** [MicrosoftDocs/power-platform#965]
このDocs のページで
"3. Microsoft Dataverse環境で監査ログを保持する期間の保持期間を設定できます。 これらのログを保持する 配下で、ログを保持する期間を選択します。"
と記載されています。
上記機能はリリースされていない機能と認識しています。
しかし、ユーザー様にとっては利用できる機能と認識してしまう文面に思えます。

実装されていない機能について、リリース日が確定していない情報であれば、先行して公開情報に記載するべきではないと思います。

ユーザー様の混乱を防ぐため、以下の公開情報のお見直し、または削除をご検討ください。
Title：監査の開始/停止と保持ポリシーの設定
URL：https://docs.microsoft.com/ja-jp/power-platform/admin/audit-data-user-activity#startstop-auditing-and-set-retention-policy

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 837f9db7-667d-814f-1df6-98e2f89a44cc
* Version Independent ID: f53ea984-3798-d3fb-ec0c-d31f81db9250
* Content: [セキュリティおよび法令遵守の監査データとユーザーの活動 - Power Platform](https://docs.microsoft.com/ja-jp/power-platform/admin/audit-data-user-activity#startstop-auditing-and-set-retention-policy)
* Content Source: [power-platform/admin/audit-data-user-activity.md](https://github.com/MicrosoftDocs/power-platform-pr.ja-JP/blob/live/power-platform/admin/audit-data-user-activity.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by jimholtz** [comment]
Duplicate of PR: https://github.com/MicrosoftDocs/power-platform/issues/966
