### ISSUE TITLE
About Docs description correction

### ISSUE THREAD

**Issue by ShinyaNishimura** [MicrosoftDocs/power-platform#966]
About this document page
"3. You can set a retention period for how long audit logs are kept in a Microsoft Dataverse environment. Under Retain these logs for, choose the period of time you wish to retain the logs."
It has been described as.
The above features have not been released.
However, it seems to the user that it is a function that can be set.

Regarding unimplemented features, if the release date is not fixed, I think that it should not be described in the public information in advance.

To prevent user confusion, please consider reviewing or deleting the following public information.

Title：Start/stop auditing and set retention policy
URL：https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity#startstop-auditing-and-set-retention-policy
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837f9db7-667d-814f-1df6-98e2f89a44cc
* Version Independent ID: f53ea984-3798-d3fb-ec0c-d31f81db9250
* Content: [Audit data and user activity for security and compliance - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/audit-data-user-activity#startstop-auditing-and-set-retention-policy)
* Content Source: [power-platform/admin/audit-data-user-activity.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/audit-data-user-activity.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @TJVass
* Microsoft Alias: **tjvass**

**Comment by jimholtz** [comment]
@ShinyaNishimura 
Taking this to internal thread.
