### ISSUE TITLE
1 or 2 apps per licence?

### ISSUE THREAD

**Issue by Centtaurus** [MicrosoftDocs/power-platform#968]
Hello,

in the this page text you write **_2 apps (and 1 portal)_**. In the document "Power Platform Licensing Guide_November 2021_ FINAL PUB v2" is it on page 4 only **_"1 app or portal"_**. This seem correct for me, so the page text seems to be wrong? Could you please clearify this for me?

### The Power Apps per app plan allows users to run specific apps. Can you explain what this means in terms of the number and types of apps I can use?
The Power Apps per app plan is designed to help organizations solve for one business scenario at a time, which may involve a combination of individual apps. Each “per app” license provides an individual user with rights to **_two apps (canvas and/or model-driven) as well as one Power Apps Portal_**, all within a single environment. A single user might be covered by multiple “per app” licenses to allow the user to use multiple solutions targeted at various business scenarios, without requiring a per-user license. In other words, the “per app” license is stackable.

### Do embedded canvas apps in model-driven apps count toward the **_two-apps limits_**?
No. Embedded canvas components within the model-driven app will not count towards the **_two apps_** limit in the per app licensing model.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [FAQs zur Power Apps- und Power Automate-Lizenzierung - Power Platform](https://docs.microsoft.com/de-de/power-platform/admin/powerapps-flow-licensing-faq)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform-pr.de-DE/blob/live/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by jimholtz** [comment]
@Centtaurus 
Sorry for the delay. We've updated the article which hopefully addresses your questions.
