### ISSUE TITLE
Missing documentation on the "Use quick find view of an entity for searching on grids and sub-grids" setting. 

### ISSUE THREAD

**Issue by jthomps19** [MicrosoftDocs/power-platform#969]
I don't see a reference\documentation related to the "Use quick find view of an entity for searching on grids and sub-grids" setting under search.  Would be nice to have this documented so customers can understand how that changes the behavior of the quick find search.

![FeatureSettings](https://user-images.githubusercontent.com/31544538/141334741-9965d54a-ca8a-4a01-a0de-55862a886e93.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ccbaa1f-671b-d49e-5b18-939d37e5f891
* Version Independent ID: 63e11f1e-c83d-72d6-1ac2-2db0ff76e6df
* Content: [Manage feature settings - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/settings-features)
* Content Source: [power-platform/admin/settings-features.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/settings-features.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@jthomps19 
Thanks for bringing this to our attention. The documentation has been updated.
