### ISSUE TITLE
Conflict between Office365 Pricing page and this one

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/power-platform#97]
Hello,
I need clarity as to whether PowerApps and Power Automate (Flow) still come with Office365 Business Premium. All references to PowerApps and Power Automate have been removed from the O365 Pricing Page [here](https://products.office.com/en-us/compare-all-microsoft-office-products?activetab=tab:primaryr2).  This page MOST CERTAINLY used to include these tools with an O365 subscription. 
Now it appears this is no longer the case which puts it in contradiction to this document. 
Please clarify. 
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b6371f-3a43-09ba-e714-b6a9995a1e19
* Version Independent ID: f1e0a6b5-26c9-3f31-7e8b-4e58c34d9636
* Content: [Licensing overview - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus)
* Content Source: [power-platform/admin/pricing-billing-skus.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/pricing-billing-skus.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@SeaDude 
Please see Appendix D of the Licensing Guide:
https://go.microsoft.com/fwlink/?linkid=2085130
