### ISSUE TITLE
Waiting on Internal Feedback

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/power-platform#972]
This area has to be a joke.  I guess don't waste you time writing here as Jimbo is too busy doing real work to deal with anything regarding Backup and Restore for Dynamics 365 feedback... which, incidentially is still a total joke.  God help you if anyone has issues with a PRODUCTION environment and you have to switch it to a SANDBOX... just to be in ADMIN MODE... then NO ONE has permissions as you have to set it all back up.  Oh, did I mention.. you lose all backups of your production environment past 7 days when you switch.

Microsoft, you really need to get a better grasp on Dynamics 365 Backups...  Getting better, but no cigar.

PS.  I hope I don't sound grumpy and discouraged.  It's just our company and others cry everytime there is an "accident" and there is toss up of dealing with restore.. or just biting the bullet and moving forwards with the lost/destroyed data.  We usually just chose to move forwards than deal with this backup/restore solution.  And no, we don't wish to get a PhD in Dynamics backup and restore.

**Comment by jimholtz** [comment]
@Karr 
Thanks for your feedback. We'll pass this on to the product team. For product-related feedback, visit https://aka.ms/ppac-ideas.
