### ISSUE TITLE
language provision takes almost an hour

### ISSUE THREAD

**Issue by PranjaliShetty** [MicrosoftDocs/power-platform#973]
[note under the section: https://docs.microsoft.com/en-us/power-platform/admin/enable-languages#enable-the-language mentions that it takes several minutes, can it be clarified more that it is expected behavior that it may take an hour or more.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62309ed-19b5-b512-9854-a4b8240fa521
* Version Independent ID: 5892047b-0806-13b6-0c61-4f92c5b42104
* Content: [Regional and language options for your environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/enable-languages#enable-the-language)
* Content Source: [power-platform/admin/enable-languages.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/enable-languages.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@PranjaliShetty 
Taking to internal thread.
