### ISSUE TITLE
need bullet points and/or periods

### ISSUE THREAD

**Issue by awolfin** [MicrosoftDocs/power-platform#974]
The content in the tables on this page needs to have bullet points and/or periods so the Edge "Read Aloud" function will pause when transitioning between paragraphs.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure user security in an environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/database-security#predefined-security-roles)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/database-security.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@awolfin 
Hi Mary. Thanks for the feedback. Can you clarify the ask? As far as I can tell, the format in this topic is commonly used in tables.
