### ISSUE TITLE
Theming Solution needs to be imported as unmanaged to be useful

### ISSUE THREAD

**Issue by JanWillem90** [MicrosoftDocs/power-platform#976]
Hi, 

Small correction:

This page mentions you should import the managed theming solution Theming_x_x_managed.zip

However, to actually apply the new themes you make with this theming solution it is needed to edit the apps inside the solution, as mentioned here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/theming-components#update-msapp-files
This means the solution should be unmanaged. If I'm not mistaken the text should be changed.

Thanks in advance for looking into this.

Kind regards,

Jan-Willem van der Linden

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a548c37-cee0-5dd5-e13d-eb3f7ce3c791
* Version Independent ID: 561fdd6a-2f5b-34af-a8d1-2ffd80267c77
* Content: [Set up the Power Apps theming solution - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-theming)
* Content Source: [power-platform/guidance/coe/setup-theming.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-theming.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

1. Canvas Apps can be edited in a managed solution, which just creates an unmanaged layer. 
2. You download the canvas app in the solution and upload it to the Theme gallery for makers to download and create their own apps with it. They do not create apps in this solution, but start from scratch.
3. Providing an unmanaged solution may lead to many issues, one of them being that a clean uninstall is not possible. All solutions in the CoE kit are provided as managed.

Thanks for the feedback,
Manuela
