### ISSUE TITLE
Access to Preview Feature "Matrix data access structure"

### ISSUE THREAD

**Issue by BMaheu** [MicrosoftDocs/power-platform#977]
I am thrilled to read about this upcoming feature, which will directly address a requirement for a project I'm currently working on. I followed the steps to enable the feature for 3 different environments (distinct tenants, all Region: Canada). In all cases, it _looks_ like the feature was enabled (as per their respective Power Platform admin centre) but the "Owning Business Unit" column became available to add on views and forms only in 1 of the 3 environments. I'm extremely puzzled about it; are there additional parameters that I should check and/or update to successfully enable the preview feature?
Thanks in advance for any guidance you might be able to provide,
Brigitte Maheu
BDO Canada

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f837f71b-c2d0-ad5e-9099-494702864ab5
* Version Independent ID: 569c759e-1ba0-98cf-30e0-014fd0e02856
* Content: [Security concepts in Microsoft Dataverse - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds#matrix-data-access-structure-modernize-business-units---preview)
* Content Source: [power-platform/admin/wp-security-cds.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/wp-security-cds.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@BMaheu 
Hi Brigitte. Sorry you're experiencing this issue. Please contact support: https://powerapps.microsoft.com/support/
