### ISSUE TITLE
Power Platform account feature enablement PowerShell commands missing

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/power-platform#979]
Could you share the PowerShell equivalent of the [AzCLI commands](https://docs.microsoft.com/en-us/power-platform/admin/pay-as-you-go-set-up#get-started)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46390354-a8ec-2960-49dc-4e06cff07be6
* Version Independent ID: 46390354-a8ec-2960-49dc-4e06cff07be6
* Content: [Set up a pay-as-you-go plan - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/pay-as-you-go-set-up)
* Content Source: [power-platform/admin/pay-as-you-go-set-up.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/pay-as-you-go-set-up.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by Ayanmullick** [comment]
The steps below should be sufficient.

```PowerShell
Select-AzSubscription <>
Register-AzProviderFeature -ProviderNamespace Microsoft.PowerPlatform -FeatureName accountPreview 

Get-AzProviderFeature -ProviderNamespace Microsoft.PowerPlatform -FeatureName accountPreview #For verification
````

It could be useful to others if added to the document.

**Comment by jimholtz** [comment]
@Ayanmullick 
Taking to internal thread.
