### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by RaduNegulescuMS** [MicrosoftDocs/power-platform#98]
Hi,

the link "What is Office 365 and how does it relate to Dynamics 365 (online)?" (https://docs.microsoft.com/dynamics365/customer-engagement/admin/what-office-365-how-does-relate) no longer exists. Has this link been replaced? The article contained an important reference that only Office E3 Plans can be used to integrate the Office 365 services with Dynamics 365. Does this still apply? 

Thank you in advance for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d917db-1300-f212-067f-4ac688c18bec
* Version Independent ID: d19b118a-eddc-dc4f-75ad-2640f02aaeb4
* Content: [Connect to Exchange Online - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/connect-exchange-online#feedback)
* Content Source: [power-platform/admin/connect-exchange-online.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/connect-exchange-online.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
Handling via email.
