### ISSUE TITLE
The PublisherIdentifier for "StartSubscription" test should use tenant Id 

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/power-platform#985]
The PublisherIdentifier for "StartSubscription" test should use tenant Id instead of App Id. the "[Child] Admin | Sync Logs" flow is using Tenant Id for the "PublisherIdentifier" at "List audit log content" and "GetContentDetails" actions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Will be updated in the December release, made the change locally for the next update. Thank you!
