### ISSUE TITLE
The content of this page need fixing, its difficult to follow -- consider using tables or dot-points (nesting dotpoint under each other)

### ISSUE THREAD

**Issue by Jaqiness** [MicrosoftDocs/power-platform#986]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7869dab1-e8c8-1432-304f-7e02132ad63f
* Version Independent ID: 806b8fab-4cb9-601d-7b9b-3a79ef0963f4
* Content: [How access to a record is determined - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/how-record-access-determined)
* Content Source: [power-platform/admin/how-record-access-determined.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/how-record-access-determined.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Jaqiness 
Thanks for the suggestion. The content has been revised.
