### ISSUE TITLE
The descripion should clarify that Access Mode "Administrative" does not grant extra access to user

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/power-platform#987]
[Enter feedback here]
Setting a user's Access Mode to "Administrative" only limits the user's access to the system (particularly all data records). In this article the setting is described as below.

"An Administrative user is a user who has access to the Settings and Administration features but has no access to any of the functionality."

The description above might make readers think that changing the Access Mode of a user (thus making that user an Administrative user) would grant that user access to Settings and Administration features, which is not true.

Please rephrase the description so that readers would correctly understand that a user also need a M365/PPAC administrator role in order to be come an Administrative user, and this Access Mode setting should be applied to existing Administrative user, it's not something that makes a non-admin user become an admin user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1b508b-e71a-b577-51cf-f21c76c58035
* Version Independent ID: 8725a7a3-7b54-3402-c94c-c9e9dee577be
* Content: [Create users - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/create-users#create-an-administrative-user-account)
* Content Source: [power-platform/admin/create-users.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/create-users.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@user0604 
Sorry for the delay. Here's what the product team reported back:
Setting a user's Access Mode to "Administrative" does not elevate the user’s privileges. It restricts the user’s permissions to ‘administrative’ if the user has a system administrator security role and also blocks the user’s permissions to apps and data if the user has a non-system administrator security role.
