### ISSUE TITLE
Cloud Flow Monitoring!

### ISSUE THREAD

**Issue by ChrisTheGreek1** [MicrosoftDocs/power-platform#988]
Hello everyone,

the CoE tool is amazing! I hope that cloud flow monitoring (See flows that failed in the orga and click to see the Flow ran) is coming soon :)

Regards
Chris

**Comment by manuelap-msft** [comment]
Hey! Thanks for the feedback - Cloud Flow events are not logged in the Office 365 Audit Log (that's where we get Power Apps launch events from) so there are currently no plans to include cloud flow monitoring in the CoE, as there's no programmatic way for us to get that information.
