### ISSUE TITLE
Gear | Advanced Settings still navigates to legacy web app, which differs from documentation.

### ISSUE THREAD

**Issue by RiccoDeCicco** [MicrosoftDocs/power-platform#989]
Clicking Gear | Advanced Settings still navigates to legacy web app, which differs from documentation provided on this page.
Also, there is no easy link to find Power Admin section referred to by another means.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcbc305a-4582-7c46-7716-93c192a0f4d5
* Version Independent ID: 9fcacd77-43c3-4281-c891-f72721493a4f
* Content: [Manage Microsoft Dataverse settings - Power Platform](https://docs.microsoft.com/en-gb/power-platform/admin/admin-settings#new-location-for-admin-settings)
* Content Source: [power-platform/admin/admin-settings.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/admin-settings.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@RiccoDeCicco 
Legacy settings are still used for settings not yet in the Power Platform admin center. These legacy settings are available using the Settings Gear. We'll update the doc a bit to clarify.
