### ISSUE TITLE
remove unmanaged layers

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/power-platform#990]
Hi Manuela, 

in the documentation it is mentioned to remove all unmanaged layers of the flows before updating the properties. I experienced during installation in a fresh environement that this check is not necessary. So I propose to mention that in the deployement guide. 

**Update and turn on child flows
There are several child flows which will need their Run only users properties updated.

HELPER - CloudFlowOperations
HELPER - CanvasAppOperations
HELPER - ObjectOperations
CLEANUP HELPER - Check Deleted (Canvas Apps)
CLEANUP HELPER - Check Deleted (Cloud Flows)
CLEANUP HELPER - Check Deleted (Model Driven Apps)
CLEANUP HELPER - Check Deleted (PVA)
CLEANUP HELPER - Check Deleted (Custom Connectors)
CLEANUP HELPER - Power Apps User Shared With
First, remove the unmanaged layer for all flows. Then, go to the details page and click the Run only users edit button.**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

thank you - we also noticed this during the testing of our December release, and are working on updating the documentation accordingly.

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are updating our docs for the January release, and I have fixed this locally for the next docs update now!
