### ISSUE TITLE
Questions about ALM > Invoke analysis

### ISSUE THREAD

**Issue by PunkyLama** [MicrosoftDocs/power-platform#991]
Hello I'm currently using the [Invoke analysis](https://docs.microsoft.com/en-us/power-platform/alm/checker-api/analyze) API. To analyse some codes from Dataverse in C# but first of all I need to understand how the API work in Postman.

I would like to know if I'm using right the API : 

Fist of all the HTTP request : 

POST /api/analyze?api-version=1.0 HTTP/1.1
Host: france.api.advisor.powerapps.com
Accept: application/json
x-ms-correlation-id: 9E378E56-6F35-41E9-BF8B-C0CC88E2B832
x-ms-tenant-id: [TenantIDFromAAD]
Authorization: Bearer eyJ0e.....

**First question :** 
  My AAD token request is good for using this API ? 
  
  POST /[TenantIDFromAAD]/oauth2/v2.0/token
  Host: login.microsoftonline.com

  client_id=071427b9-dbed-45cc-b57e-549f17c5a577&scope=user.read openid profile offline_access&username=XXXXX&password=XXXXX&grant_type=password
  
  Result : 
  `{
      "token_type": "Bearer",
      "scope": "AllSites.Manage User.Read profile openid email",
      "expires_in": 4174,
      "ext_expires_in": 4174,
      "access_token": "eyJ0e....",
      "refresh_token": "0.ATo.....",
      "id_token": "eyJ0....."
  }`

**Second question :** 
  The `x-ms-tenant-id` need to come from AAD Tenant ID ? or from Power Platform Admin Center Organization ID ?

**Third question :**
  When I'm execute the API why do I get Status : 401 Unauthorized ? And this Result : 

  `Authentication Failed. IDX10511: Signature validation failed. Keys tried: '[PII is hidden]'. 
  kid: '[PII is hidden]'. 
  Exceptions caught:
   '[PII is hidden]'.
  token: '[PII is hidden]'.`

Does anyone have a functional example of using the invoke analysis API, other than the Microsoft documentation ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 973baa36-3490-f3b9-8c4e-025a48485133
* Version Independent ID: e5801338-5b64-3d7b-8b8d-905e2feedb23
* Content: [Invoke analysis - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/checker-api/analyze)
* Content Source: [power-platform/alm/checker-api/analyze.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/checker-api/analyze.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mhuguet
* Microsoft Alias: **mhuguet**

**Comment by mhuguet** [comment]
@PunkyLama please refer to https://docs.microsoft.com/en-us/power-platform/alm/checker-api/overview for an example and further explanation of usage. Please reply if you still have questions after reviewing.
