### ISSUE TITLE
I think the links to Minimal vs Full copy are pointing to the wrong locations.  Full sounds like it should do everything where minimal doesn't include data

### ISSUE THREAD

**Issue by NadinMerali** [MicrosoftDocs/power-platform#993]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7fd9da-f47a-0ef8-059a-9bdc167a3cf2
* Version Independent ID: f1235742-94d1-d3d5-35c7-23607d4b0f72
* Content: [Manage non-production support environments in your tenant - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/support-environment)
* Content Source: [power-platform/admin/support-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/support-environment.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@NadinMerali 
Taking to internal thread.
