### ISSUE TITLE
Not consistent with the English version

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/power-platform#994]
Number of call included in the french version does not correspond to the ones indicated in the English version of the page 
-the table itself is completely different

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Limites et allocations des requêtes - Power Platform](https://docs.microsoft.com/fr-fr/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform-pr.fr-FR/blob/live/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Nicokirr 
Taking to internal thread.
