### ISSUE TITLE
Incorrect Information in the German article 

### ISSUE THREAD

**Issue by Tiglat1** [MicrosoftDocs/power-platform#997]
The English version Request Limits and allocations states that **50,000 per 24 hour**s are included with each Power Apps and Power Automate capacity add-on, the German article states that only **10,000 per 24 hours** are included

Power Apps and Power Automate capacity add-on

Customers that observe in reporting that they are frequently using more requests than limits can avoid high usage enforcement by purchasing the Power Apps and Power Automate capacity add-on. This add-on allows customers to increase the limits for specific high usage licensed users or high usage non-licensed users. Each capacity add-on raises the request by another **50,000 per 24 hours**

....

Power Apps und Power Automate-Kapazitäts-Add-On

Ein Power Apps- und Power Automate-Kapazitäts-Add-On ermöglicht Kunden, die Grenzwerte für einen bestimmten Benutzer zu erhöhen. Diese können jedem Benutzer zugewiesen werden, der über eine Power Apps-, Power Automate- oder die entsprechende Dynamics 365-Lizenz verfügt.

Jede Kapazitätserweiterung erhöht die Anfragegrenzen um weitere 10.000 pro 24 Stunden. Einem Benutzer können auch mehrere Kapazitäts-Add-Ons zugewiesen werden.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Grenzwerte und Zuteilungen für Anforderungen - Power Platform](https://docs.microsoft.com/de-de/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform-pr.de-DE/blob/live/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@Tiglat1 
Thanks for bringing this to our attention. I've passed this on to the localization team.
