### ISSUE TITLE
MSTeams with PVA in PowerAutomate to post messages into Channel and Groupchat

### ISSUE THREAD

**Issue by Santhosh0505** [MicrosoftDocs/power-platform#998]
Hi Team,

I am trying to use Power Automate to post proactive notification using PVA in MSTeams. 
![image](https://user-images.githubusercontent.com/48650250/143467280-b0c1be8e-108e-49e1-9b48-74922c1fb7fb.png)

Seems this feature is only available with one-on-one chat with bot, but I need channel and Group chat also. Can you please help if there is some way or any release of this feature already in roadmap.

Any suggested alternative way to achieve this is most appreciated.
Thanks in Advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c64db467-2159-e6ab-a4c9-15544eb78660
* Version Independent ID: c64db467-2159-e6ab-a4c9-15544eb78660
* Content: [Notify bot users in Teams with proactive messages and cards - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-proactive-message)
* Content Source: [power-virtual-agents/advanced-proactive-message.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/advanced-proactive-message.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by v-alarioza** [comment]
As noted in the [Known Limitations](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-proactive-message#known-limitations) section, this feature currently only supports personal chats with a bot. While you can't send a message to a group chat or channel, you can [send a message to a security group](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-proactive-message#send-to-a-security-group) where all users in the security group would receive personal message from the bot.
