### ISSUE TITLE
Need more details on how Modern BUs relate to Teams, Also no mention of Group Teams.

### ISSUE THREAD

**Issue by simes1** [MicrosoftDocs/power-platform#999]
**Modern BUs**

The section https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds#to-enable-this-matrix-data-access-structure-preview (or somewhere else) needs more detail on how Modern BUs relate to Teams

In recent years we've been encouraged to apply privileges via teams and NOT individual users (typically using AAD group-teams rather than owner-teams and using Team-member's privilege inheritance for privileges of basic/user scope).  There needs to be more details on how Modern BUs relate to teams, teams with security roles, team-owned records, team-member's privilege inheritance and privileges of basic/user scope.

**Group Teams**

This page only mentions owner teams and access teams - it really should mention group teams and the integration with AAD/Office 365 groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f837f71b-c2d0-ad5e-9099-494702864ab5
* Version Independent ID: 569c759e-1ba0-98cf-30e0-014fd0e02856
* Content: [Security concepts in Microsoft Dataverse - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds#matrix-data-access-structure-modernize-business-units---preview)
* Content Source: [power-platform/admin/wp-security-cds.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/wp-security-cds.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@simes1 
Thanks for the feedback. We're passing this on to the product team for review.

**Comment by jimholtz** [comment]
@simes1 
Thanks for the suggestion. The product team will review this content for a future content update.

**Comment by jimholtz** [comment]
@simes1 
Topic has been updated:
https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds#associate-a-business-unit-with-an-azure-ad-security-group
